"""finetune/simulate/dns.py — Rocky Linux 9 output simulator for the 'dns' tool.

Public API
----------
simulate_dns(op, args, ctx) -> dict
    Returns a dict with exactly four keys mirroring core.tools.ToolResult:
        exit_code : int
        stdout    : str
        stderr    : str
        summary   : str   (MUST be I2-clean — no forbidden terms)

    op   : one of the 6 real operations declared in core/tools/dns.py
    args : dict of op arguments (may be {} for ops with no required args)
    ctx  : system context string from make_context(), OR a profile dict —
           both are supported via isinstance checks (same pattern as services.py).

Realism model
-------------
* dig output uses the standard short-answer format produced by +noall +answer.
* nslookup output follows Rocky 9 bind-utils format.
* host output follows the one-line-per-record format from bind-utils.
* named status follows the systemctl status cgroups-v2 format.
* resolv.conf output is a realistic /etc/resolv.conf with nameservers and
  search domains derived from the context.
* Failure branches are deterministic: names containing "invalid", "notfound",
  "nxdomain", "fail", "bogus", or "missing" trigger NXDOMAIN/error responses.
  A hash-based 15% scatter adds variety across other names.

I2 compliance
-------------
All summary strings are I2-clean (no AI/LLM/model/agent/agentic/neural language).

INV-read-only-core: this module imports NOTHING from core/ or finetune.coreimports.
The 4-key dict mirrors ToolResult with no class dependency.
"""

from __future__ import annotations

import hashlib
from typing import Any


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_result(
    exit_code: int,
    stdout: str,
    stderr: str,
    summary: str,
) -> dict[str, Any]:
    return {
        "exit_code": exit_code,
        "stdout": stdout,
        "stderr": stderr,
        "summary": summary,
    }


def _hostname(ctx: Any) -> str:
    """Extract a short hostname from ctx for use in realistic output."""
    if isinstance(ctx, dict):
        return ctx.get("hostname", "rocky-host.example.com").split(".")[0]
    if isinstance(ctx, str):
        for line in ctx.splitlines():
            if line.lower().startswith("hostname:"):
                parts = line.split(":", 1)
                if len(parts) == 2:
                    return parts[1].strip().split(".")[0]
    return "rocky-host"


def _domain(ctx: Any) -> str:
    """Extract a domain/search suffix from ctx."""
    if isinstance(ctx, dict):
        return ctx.get("domain", "example.com")
    if isinstance(ctx, str):
        for line in ctx.splitlines():
            low = line.lower()
            if low.startswith("domain:") or low.startswith("search domain:"):
                parts = line.split(":", 1)
                if len(parts) == 2:
                    return parts[1].strip()
    return "example.com"


def _nameservers(ctx: Any) -> list[str]:
    """Return a list of nameserver IPs from ctx, with a sane default."""
    if isinstance(ctx, dict):
        ns = ctx.get("nameservers", [])
        if ns:
            return ns
    return ["192.168.1.1", "8.8.8.8"]


def _is_bad_name(name: str) -> bool:
    """Deterministically decide if a name should trigger a DNS failure.

    Triggers: the token "invalid", "notfound", "nxdomain", "fail", "bogus",
    or "missing" in the lowercase name; OR a hash-based 15% scatter.
    """
    lower = name.lower()
    for tok in ("invalid", "notfound", "nxdomain", "fail", "bogus", "missing"):
        if tok in lower:
            return True
    h = int(hashlib.md5(name.encode()).hexdigest(), 16)
    return h % 20 == 0


def _fake_ipv4(name: str) -> str:
    """Produce a deterministic fake IPv4 for a given hostname."""
    h = int(hashlib.md5(name.encode()).hexdigest(), 16)
    a = 10 + (h % 240)
    b = (h >> 8) % 256
    c = (h >> 16) % 256
    d = 1 + (h >> 24) % 254
    return f"{a}.{b}.{c}.{d}"


def _fake_ipv6(name: str) -> str:
    """Produce a deterministic fake IPv6 for a given hostname."""
    h = int(hashlib.md5((name + "v6").encode()).hexdigest(), 16)
    segments = [(h >> (i * 8)) & 0xFFFF for i in range(8)]
    return ":".join(f"{s:04x}" for s in segments)


# ---------------------------------------------------------------------------
# Per-operation simulators
# ---------------------------------------------------------------------------

def _sim_resolv_view(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    domain = _domain(ctx)
    ns_list = _nameservers(ctx)

    lines = [f"# Generated by NetworkManager"]
    lines.append(f"search {domain}")
    for ns in ns_list[:3]:
        lines.append(f"nameserver {ns}")
    lines.append("options ndots:5")
    stdout = "\n".join(lines) + "\n"

    return _make_result(
        exit_code=0,
        stdout=stdout,
        stderr="",
        summary="Read /etc/resolv.conf successfully.",
    )


def _sim_named_status(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    host = _hostname(ctx)

    # Determine whether named looks active based on ctx
    named_active = False
    if isinstance(ctx, dict):
        active = ctx.get("active_services", [])
        named_active = any("named" in s or "bind" in s for s in active)
    elif isinstance(ctx, str):
        named_active = "named" in ctx.lower()

    if named_active:
        pid = 1000 + (sum(ord(c) for c in "named") % 8000)
        stdout = (
            f"● named.service - Berkeley Internet Name Domain (DNS)\n"
            f"     Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; preset: disabled)\n"
            f"     Active: active (running) since Thu 2026-07-03 00:01:12 UTC; 10h 5min ago\n"
            f"   Main PID: {pid} (named)\n"
            f"      Tasks: 4 (limit: 23168)\n"
            f"     Memory: 64.1M\n"
            f"        CPU: 2.453s\n"
            f"     CGroup: /system.slice/named.service\n"
            f"             └─{pid} /usr/sbin/named -u named -c /etc/named.conf\n"
            f"\n"
            f"Jul 03 00:01:12 {host} systemd[1]: Started Berkeley Internet Name Domain (DNS).\n"
            f"Jul 03 00:01:13 {host} named[{pid}]: running\n"
        )
        return _make_result(
            exit_code=0,
            stdout=stdout,
            stderr="",
            summary="The named service is active and running.",
        )
    else:
        stdout = (
            f"○ named.service - Berkeley Internet Name Domain (DNS)\n"
            f"     Loaded: loaded (/usr/lib/systemd/system/named.service; disabled; preset: disabled)\n"
            f"     Active: inactive (dead)\n"
        )
        return _make_result(
            exit_code=3,
            stdout=stdout,
            stderr="",
            summary="The named service reported status exit 3.",
        )


def _sim_dig(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    name = args.get("name", "example.com")
    record_type = (args.get("record_type") or "A").upper()

    if _is_bad_name(name):
        stderr = (
            f";; communications error to 127.0.0.53#53: timed out\n"
            f";; no servers could be reached\n"
        )
        return _make_result(
            exit_code=1,
            stdout="",
            stderr=stderr,
            summary=f"DNS lookup for '{name}' ({record_type}) failed (exit 1).",
        )

    ttl = 300
    if record_type == "A":
        ip = _fake_ipv4(name)
        stdout = f"{name}.\t\t{ttl}\tIN\tA\t{ip}\n"
    elif record_type == "AAAA":
        ip6 = _fake_ipv6(name)
        stdout = f"{name}.\t\t{ttl}\tIN\tAAAA\t{ip6}\n"
    elif record_type == "MX":
        stdout = (
            f"{name}.\t\t{ttl}\tIN\tMX\t10 mail.{name}.\n"
            f"{name}.\t\t{ttl}\tIN\tMX\t20 mail2.{name}.\n"
        )
    elif record_type == "TXT":
        stdout = f'{name}.\t\t{ttl}\tIN\tTXT\t"v=spf1 mx ~all"\n'
    elif record_type == "CNAME":
        stdout = f"{name}.\t\t{ttl}\tIN\tCNAME\tcanonical.{name}.\n"
    elif record_type == "NS":
        stdout = (
            f"{name}.\t\t{ttl}\tIN\tNS\tns1.{name}.\n"
            f"{name}.\t\t{ttl}\tIN\tNS\tns2.{name}.\n"
        )
    else:
        stdout = f"{name}.\t\t{ttl}\tIN\t{record_type}\t<record-data>\n"

    return _make_result(
        exit_code=0,
        stdout=stdout,
        stderr="",
        summary=f"DNS lookup for '{name}' ({record_type}) completed.",
    )


def _sim_nslookup(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    name = args.get("name", "example.com")
    server = args.get("server") or ""
    ns_list = _nameservers(ctx)
    resolver = server if server else ns_list[0]

    if _is_bad_name(name):
        stdout = (
            f"Server:\t\t{resolver}\n"
            f"Address:\t{resolver}#53\n"
            f"\n"
            f"** server can't find {name}: NXDOMAIN\n"
        )
        return _make_result(
            exit_code=1,
            stdout=stdout,
            stderr="",
            summary=f"nslookup for '{name}' failed (exit 1).",
        )

    ip = _fake_ipv4(name)
    # nslookup prints a reverse PTR entry first for the server, then the result
    stdout = (
        f"Server:\t\t{resolver}\n"
        f"Address:\t{resolver}#53\n"
        f"\n"
        f"Name:\t{name}\n"
        f"Address: {ip}\n"
    )
    return _make_result(
        exit_code=0,
        stdout=stdout,
        stderr="",
        summary=f"nslookup for '{name}' returned results.",
    )


def _sim_host(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    name = args.get("name", "example.com")
    server = args.get("server") or ""

    if _is_bad_name(name):
        stdout = f"Host {name} not found: 3(NXDOMAIN)\n"
        return _make_result(
            exit_code=1,
            stdout=stdout,
            stderr="",
            summary=f"host lookup for '{name}' failed (exit 1).",
        )

    ip = _fake_ipv4(name)
    ip6 = _fake_ipv6(name)
    stdout = (
        f"{name} has address {ip}\n"
        f"{name} has IPv6 address {ip6}\n"
        f"{name} mail is handled by 10 mail.{name}.\n"
    )
    return _make_result(
        exit_code=0,
        stdout=stdout,
        stderr="",
        summary=f"host lookup for '{name}' returned results.",
    )


def _sim_flush_caches(args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    # resolvectl flush-caches exits 0 and produces no output on success
    # Simulate occasional failure when resolvectl/systemd-resolved is not running
    h = int(hashlib.md5(b"flush-caches-ctx").hexdigest(), 16)
    # Always succeed in the default simulation
    return _make_result(
        exit_code=0,
        stdout="",
        stderr="",
        summary="DNS resolver cache flushed successfully.",
    )


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

_DISPATCH = {
    "resolv_view":  _sim_resolv_view,
    "named_status": _sim_named_status,
    "dig":          _sim_dig,
    "nslookup":     _sim_nslookup,
    "host":         _sim_host,
    "flush_caches": _sim_flush_caches,
}


def simulate_dns(op: str, args: dict[str, Any], ctx: Any) -> dict[str, Any]:
    """Simulate a 'dns' tool call and return a ToolResult-shaped dict.

    Parameters
    ----------
    op   : operation name; must be one of the 6 real ops declared in
           core/tools/dns.py (resolv_view, named_status, dig, nslookup,
           host, flush_caches).
    args : argument dict (may be {} for ops with no required args).
    ctx  : system context — either the snapshot_text str from make_context(),
           or a profile dict with hostname/domain/nameservers/active_services.

    Returns
    -------
    dict with keys: exit_code (int), stdout (str), stderr (str), summary (str).
    All four keys are always present. summary is I2-clean.

    Raises
    ------
    KeyError  if op is not a recognised operation name.
    """
    handler = _DISPATCH.get(op)
    if handler is None:
        raise KeyError(
            f"simulate_dns: unknown operation '{op}'. "
            f"Valid ops: {sorted(_DISPATCH)}"
        )
    return handler(args, ctx)
