"""finetune/scenarios_v2/aide.py — corpus v2 scenarios for 'aide'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="aide-check-v2-0001", tool="aide", operation="check",
       complexity="single",
       user_input="Kick off an integrity scan against the baseline on db02.",
       args={"operation": "check"},
       answer="aide --check: exit 0\nscanned 48213 entries, 0 added, 0 removed, 0 changed\nno deviations from /var/lib/aide/aide.db.gz"),
    V2(id="aide-check-v2-0002", tool="aide", operation="check",
       complexity="diagnostic",
       user_input="Ticket says someone may have touched files in /etc on web-prod-3 overnight, can you confirm one way or the other?",
       args={"operation": "check"},
       answer="aide --check: exit 1\n3 changed entries under /etc\n/etc/ssh/sshd_config, /etc/sudoers, /etc/crontab\n0 added, 0 removed"),
    V2(id="aide-check-v2-0003", tool="aide", operation="check",
       complexity="single",
       user_input="Use the config at /etc/aide/aide-staging.conf and run the check now.",
       args={"operation": "check", "config": "/etc/aide/aide-staging.conf"},
       answer="aide --check -c /etc/aide/aide-staging.conf: exit 0\nscanned 12904 entries, 0 added, 0 removed, 0 changed"),
    V2(id="aide-check-v2-0004", tool="aide", operation="check",
       complexity="diagnostic",
       user_input="Nightly cron alerted on this box but I have not looked yet, is the filesystem actually different from baseline?",
       args={"operation": "check"},
       answer="aide --check: exit 1\n1 changed entry\n/usr/bin/curl (size, mtime, sha256 mismatch)\n0 added, 0 removed"),
    V2(id="aide-init-v2-0001", tool="aide", operation="init",
       complexity="single",
       user_input="Freshly provisioned rhel9-node07, stand up the initial database for it.",
       args={"operation": "init"},
       answer="aide --init: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n51002 entries recorded\nmove aide.db.new.gz to aide.db.gz to activate"),
    V2(id="aide-init-v2-0002", tool="aide", operation="init",
       complexity="multi",
       user_input="There is no database on this host yet — create one and then run a check to confirm it loads cleanly.",
       args={"operation": "init"},
       answer="aide --init: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n49877 entries recorded"),
    V2(id="aide-init-v2-0003", tool="aide", operation="init",
       complexity="single",
       user_input="Build the reference database using /etc/aide/aide-pci.conf, this host is in scope for the PCI segment.",
       args={"operation": "init", "config": "/etc/aide/aide-pci.conf"},
       answer="aide --init -c /etc/aide/aide-pci.conf: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n38460 entries recorded"),
    V2(id="aide-init-v2-0004", tool="aide", operation="init",
       complexity="diagnostic",
       user_input="db02 has never had a baseline set up, right? Set one up if that is confirmed.",
       args={"operation": "init"},
       answer="aide --init: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n48213 entries recorded\nno prior aide.db.gz found"),
    V2(id="aide-update-v2-0001", tool="aide", operation="update",
       complexity="single",
       user_input="We finished the approved patch window on app-node2, lock in the current state as the new baseline.",
       args={"operation": "update"},
       answer="aide --update: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n42 changed, 6 added, 1 removed against prior baseline"),
    V2(id="aide-update-v2-0002", tool="aide", operation="update",
       complexity="multi",
       user_input="Refresh the aide baseline and then verify it with a check right after.",
       args={"operation": "update"},
       answer="aide --update: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n18 changed, 3 added, 0 removed"),
    V2(id="aide-update-v2-0003", tool="aide", operation="update",
       complexity="single",
       user_input="This box keeps false-alarming on log rotation, roll the current filesystem state into the baseline using /etc/aide/aide-logs.conf.",
       args={"operation": "update", "config": "/etc/aide/aide-logs.conf"},
       answer="aide --update -c /etc/aide/aide-logs.conf: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n214 changed under /var/log, 0 added, 0 removed"),
    V2(id="aide-update-v2-0004", tool="aide", operation="update",
       complexity="diagnostic",
       user_input="We rolled out the kernel update everywhere and now every host is flagging kernel module diffs, is that expected and can we clear it here?",
       args={"operation": "update"},
       answer="aide --update: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n9 changed under /lib/modules, 2 added, 0 removed"),
    V2(id="aide-update-v2-0005", tool="aide", operation="update",
       complexity="single",
       user_input="Accept the current state as the new aide baseline on this host.",
       args={"operation": "update"},
       answer="aide --update: exit 0\nwrote /var/lib/aide/aide.db.new.gz\n5 changed, 0 added, 0 removed"),
    V2(id="aide-db_status-v2-0001", tool="aide", operation="db_status",
       complexity="single",
       user_input="Show me the file details for the aide database on this host.",
       args={"operation": "db_status"},
       answer="/var/lib/aide/aide.db.gz\nsize 9.4M, mode 0600, owner root:root\nmtime 2026-08-30 02:14:11"),
    V2(id="aide-db_status-v2-0002", tool="aide", operation="db_status",
       complexity="diagnostic",
       user_input="Compliance flagged this host's aide baseline as stale, when was it actually last touched?",
       args={"operation": "db_status"},
       answer="/var/lib/aide/aide.db.gz\nsize 7.1M, mode 0600, owner root:root\nmtime 2026-04-02 11:03:47"),
    V2(id="aide-db_status-v2-0003", tool="aide", operation="db_status",
       complexity="multi",
       user_input="Confirm the aide database is present and readable, then go ahead and run a check.",
       args={"operation": "db_status"},
       answer="/var/lib/aide/aide.db.gz\nsize 10.2M, mode 0600, owner root:root\nmtime 2026-09-05 03:00:02"),
    V2(id="aide-db_status-v2-0004", tool="aide", operation="db_status",
       complexity="single",
       user_input="Check the status of /var/lib/aide/aide-secondary.db.gz for me.",
       args={"operation": "db_status", "db_path": "/var/lib/aide/aide-secondary.db.gz"},
       answer="/var/lib/aide/aide-secondary.db.gz\nsize 3.8M, mode 0640, owner root:root\nmtime 2026-07-11 22:41:09"),
    V2(id="aide-db_status-v2-0005", tool="aide", operation="db_status",
       complexity="diagnostic",
       user_input="aide --check keeps failing with a database error on node05, does the db file even exist there?",
       args={"operation": "db_status"},
       answer="stat failed: /var/lib/aide/aide.db.gz: No such file or directory\nno baseline present"),
]

from finetune.scenarios_v2 import check_module; check_module("aide", SCENARIOS_V2)
