"""finetune/scenarios_v2/audit.py — corpus v2 scenarios for 'audit'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id='audit-list-v2-0001', tool='audit', operation='list',
       complexity='single',
       user_input='confirm all kernel audit rules are still loaded after the patch window',
       args={'operation': 'list'},
       answer='auditctl -l\n7 rules loaded\nwatch: /etc/shadow, /etc/gshadow, /etc/sudoers\nexec_watch: execve b64/b32'),
    V2(id='audit-list-v2-0002', tool='audit', operation='list',
       complexity='single',
       user_input='dump the active auditctl rule set',
       args={'operation': 'list'},
       answer='auditctl -l\n5 rules loaded\nkey=identity_watch on /etc/passwd,/etc/group'),
    V2(id='audit-list-v2-0003', tool='audit', operation='list',
       complexity='single',
       user_input='print every rule the kernel audit subsystem currently has loaded',
       args={'operation': 'list'},
       answer='auditctl -l\n9 rules loaded'),
    V2(id='audit-list-v2-0004', tool='audit', operation='list',
       complexity='diagnostic',
       user_input='the compliance scan flagged missing audit coverage on /etc/ssh/sshd_config — is a watch rule actually in place?',
       args={'operation': 'list'},
       answer='auditctl -l\nno rule found for /etc/ssh/sshd_config\n6 other rules loaded'),
    V2(id='audit-list-v2-0005', tool='audit', operation='list',
       complexity='diagnostic',
       user_input='we rebooted the audit host last night, did the persistent rules survive?',
       args={'operation': 'list'},
       answer='auditctl -l\n8 rules loaded, matches /etc/audit/rules.d/audit.rules'),
    V2(id='audit-list-v2-0006', tool='audit', operation='list',
       complexity='multi',
       user_input='list the current audit rules and then export them to back up before the upgrade',
       args={'operation': 'list'},
       answer='auditctl -l\n7 rules loaded\nsaved to /root/audit-rules-backup.txt'),
    V2(id='audit-list-v2-0007', tool='audit', operation='list',
       complexity='single',
       user_input='what audit rules does nftables-adjacent hardening rely on right now?',
       args={'operation': 'list'},
       answer='auditctl -l\n4 rules loaded\nkey=net_watch on /etc/nftables'),
    V2(id='audit-list-v2-0008', tool='audit', operation='list',
       complexity='diagnostic',
       user_input='a firewall change went out overnight — did it also touch our audit watch on /etc/sysconfig/iptables?',
       args={'operation': 'list'},
       answer='auditctl -l\nrule present: -w /etc/sysconfig/iptables -p wa -k net_watch'),
    V2(id='audit-list-v2-0009', tool='audit', operation='list',
       complexity='single',
       user_input='show the loaded audit rules for the PCI scope hosts',
       args={'operation': 'list'},
       answer='auditctl -l\n11 rules loaded'),
    V2(id='audit-list-v2-0010', tool='audit', operation='list',
       complexity='single',
       user_input='list active audit rules, I need to diff them against the CIS baseline',
       args={'operation': 'list'},
       answer='auditctl -l\n7 rules loaded'),
    V2(id='audit-status-v2-0011', tool='audit', operation='status',
       complexity='single',
       user_input='give me the current health of the audit subsystem',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=1142 rate_limit=0 backlog_limit=8192 lost=0'),
    V2(id='audit-status-v2-0012', tool='audit', operation='status',
       complexity='diagnostic',
       user_input='are we dropping any audit records under load?',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: lost=14 backlog=6100/8192 backlog_wait_time=60000'),
    V2(id='audit-status-v2-0013', tool='audit', operation='status',
       complexity='single',
       user_input='check whether auditd is enabled at the kernel level',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 failure=1 pid=1142'),
    V2(id='audit-status-v2-0014', tool='audit', operation='status',
       complexity='diagnostic',
       user_input='the SOC ticket says audit logging might be off on this host, can you verify?',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=1142, logging active'),
    V2(id='audit-status-v2-0015', tool='audit', operation='status',
       complexity='single',
       user_input='what pid is the audit daemon running as',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: pid=1142 rate_limit=0'),
    V2(id='audit-status-v2-0016', tool='audit', operation='status',
       complexity='multi',
       user_input="check audit status and then pull today's report if it looks healthy",
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 lost=0\naureport summary: 412 events today'),
    V2(id='audit-status-v2-0017', tool='audit', operation='status',
       complexity='diagnostic',
       user_input="syslog shows audit backlog warnings, what's the actual backlog number",
       args={'operation': 'status'},
       answer='AUDIT_STATUS: backlog=7800/8192 backlog_wait_time=60000'),
    V2(id='audit-status-v2-0018', tool='audit', operation='status',
       complexity='single',
       user_input='confirm the audit subsystem is running before we start the sssd migration',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=1142'),
    V2(id='audit-status-v2-0019', tool='audit', operation='status',
       complexity='single',
       user_input='show current audit daemon status on db03',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=990 lost=0'),
    V2(id='audit-status-v2-0020', tool='audit', operation='status',
       complexity='diagnostic',
       user_input='did the recent kernel_modules update disable auditing as a side effect?',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=1142, unaffected by module load'),
    V2(id='audit-status-v2-0021', tool='audit', operation='status',
       complexity='single',
       user_input='status of the audit subsystem, please',
       args={'operation': 'status'},
       answer='AUDIT_STATUS: enabled=1 pid=1142 rate_limit=0 lost=0'),
    V2(id='audit-add-rule-v2-0022', tool='audit', operation='add-rule',
       complexity='single',
       user_input='add a rule to log every write to /etc/gshadow',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F path=/etc/gshadow -F perm=wa -k gshadow_watch'},
       answer='auditctl -a always,exit -F path=/etc/gshadow -F perm=wa -k gshadow_watch\nrule added'),
    V2(id='audit-add-rule-v2-0023', tool='audit', operation='add-rule',
       complexity='single',
       user_input='watch /etc/crontab for tampering',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F path=/etc/crontab -F perm=wa -k cron_watch'},
       answer='auditctl -a always,exit -F path=/etc/crontab -F perm=wa -k cron_watch\nrule added'),
    V2(id='audit-add-rule-v2-0024', tool='audit', operation='add-rule',
       complexity='multi',
       user_input='add a rule watching /etc/hosts for writes, then list the rules to confirm it landed',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F path=/etc/hosts -F perm=wa -k hosts_watch'},
       answer='auditctl -a always,exit -F path=/etc/hosts -F perm=wa -k hosts_watch\nrule added\nauditctl -l: 8 rules loaded, hosts_watch present'),
    V2(id='audit-add-rule-v2-0025', tool='audit', operation='add-rule',
       complexity='single',
       user_input='track every setuid syscall on this box',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F arch=b64 -S setuid -k setuid_watch'},
       answer='auditctl -a always,exit -F arch=b64 -S setuid -k setuid_watch\nrule added'),
    V2(id='audit-add-rule-v2-0026', tool='audit', operation='add-rule',
       complexity='diagnostic',
       user_input="we can't tell who is editing /etc/security/limits.conf — set up a watch for it",
       args={'operation': 'add-rule', 'rule': '-a always,exit -F path=/etc/security/limits.conf -F perm=wa -k limits_watch'},
       answer='auditctl -a always,exit -F path=/etc/security/limits.conf -F perm=wa -k limits_watch\nrule added'),
    V2(id='audit-add-rule-v2-0027', tool='audit', operation='add-rule',
       complexity='single',
       user_input='add an audit rule for module load/unload syscalls',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F arch=b64 -S init_module -S delete_module -k module_watch'},
       answer='auditctl -a always,exit -F arch=b64 -S init_module -S delete_module -k module_watch\nrule added'),
    V2(id='audit-add-rule-v2-0028', tool='audit', operation='add-rule',
       complexity='single',
       user_input='start logging unlink and rename calls system-wide',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F arch=b64 -S unlink -S rename -k delete_watch'},
       answer='auditctl -a always,exit -F arch=b64 -S unlink -S rename -k delete_watch\nrule added'),
    V2(id='audit-add-rule-v2-0029', tool='audit', operation='add-rule',
       complexity='multi',
       user_input='add the sudoers watch rule and then search the log for anyone who already triggered it today',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F path=/etc/sudoers -F perm=wa -k sudoers_watch'},
       answer='auditctl -a always,exit -F path=/etc/sudoers -F perm=wa -k sudoers_watch\nrule added\nausearch -k sudoers_watch: no matches today'),
    V2(id='audit-add-rule-v2-0030', tool='audit', operation='add-rule',
       complexity='single',
       user_input='add a rule flagging connect() syscalls from uid 0',
       args={'operation': 'add-rule', 'rule': '-a always,exit -F arch=b64 -S connect -F auid=0 -k root_net_watch'},
       answer='auditctl -a always,exit -F arch=b64 -S connect -F auid=0 -k root_net_watch\nrule added'),
    V2(id='audit-delete-rule-v2-0031', tool='audit', operation='delete-rule',
       complexity='single',
       user_input='remove the exec_watch rule entirely',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F arch=b64 -S execve -k exec_watch'},
       answer='auditctl -d always,exit -F arch=b64 -S execve -k exec_watch\nrule deleted'),
    V2(id='audit-delete-rule-v2-0032', tool='audit', operation='delete-rule',
       complexity='single',
       user_input="wipe every audit rule right now, we're reloading from a fresh ruleset",
       args={'operation': 'delete-rule'},
       answer='auditctl -D\nall rules deleted (was: 7 rules)'),
    V2(id='audit-delete-rule-v2-0033', tool='audit', operation='delete-rule',
       complexity='multi',
       user_input='delete the sudoers_watch rule and then confirm the list is clean',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F path=/etc/sudoers -F perm=wa -k sudoers_watch'},
       answer='auditctl -d always,exit -F path=/etc/sudoers -F perm=wa -k sudoers_watch\nrule deleted\nauditctl -l: 6 rules remain'),
    V2(id='audit-delete-rule-v2-0034', tool='audit', operation='delete-rule',
       complexity='diagnostic',
       user_input='the audit log is being flooded by the net_watch rule, can we pull it off?',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F arch=b64 -S connect -k net_watch'},
       answer='auditctl -d always,exit -F arch=b64 -S connect -k net_watch\nrule deleted'),
    V2(id='audit-delete-rule-v2-0035', tool='audit', operation='delete-rule',
       complexity='single',
       user_input='clear all kernel audit rules',
       args={'operation': 'delete-rule'},
       answer='auditctl -D\nall rules deleted (was: 9 rules)'),
    V2(id='audit-delete-rule-v2-0036', tool='audit', operation='delete-rule',
       complexity='single',
       user_input='remove the identity_watch rule on /etc/group',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F path=/etc/group -F perm=wa -k identity_watch'},
       answer='auditctl -d always,exit -F path=/etc/group -F perm=wa -k identity_watch\nrule deleted'),
    V2(id='audit-delete-rule-v2-0037', tool='audit', operation='delete-rule',
       complexity='multi',
       user_input='delete all current rules then reload the CIS ruleset from /etc/audit/rules.d/cis.rules',
       args={'operation': 'delete-rule'},
       answer='auditctl -D\nall rules deleted (was: 8 rules)\naugenrules --load: 12 rules loaded from cis.rules'),
    V2(id='audit-delete-rule-v2-0038', tool='audit', operation='delete-rule',
       complexity='single',
       user_input="drop the module_watch rule, it's noisy on this kernel build host",
       args={'operation': 'delete-rule', 'rule': 'always,exit -F arch=b64 -S init_module -S delete_module -k module_watch'},
       answer='auditctl -d always,exit -F arch=b64 -S init_module -S delete_module -k module_watch\nrule deleted'),
    V2(id='audit-delete-rule-v2-0039', tool='audit', operation='delete-rule',
       complexity='diagnostic',
       user_input='is there a stale rule left over from the old fapolicyd pilot that we should remove?',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F path=/etc/fapolicyd/fapolicyd.rules -F perm=wa -k fapd_watch'},
       answer='auditctl -d always,exit -F path=/etc/fapolicyd/fapolicyd.rules -F perm=wa -k fapd_watch\nrule deleted'),
    V2(id='audit-delete-rule-v2-0040', tool='audit', operation='delete-rule',
       complexity='single',
       user_input='delete-rule for the delete_watch entry',
       args={'operation': 'delete-rule', 'rule': 'always,exit -F arch=b64 -S unlink -S rename -k delete_watch'},
       answer='auditctl -d always,exit -F arch=b64 -S unlink -S rename -k delete_watch\nrule deleted'),
    V2(id='audit-search-by-comm-v2-0041', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='search the audit trail for anything run by systemctl',
       args={'operation': 'search-by-comm', 'comm': 'systemctl'},
       answer='ausearch -c systemctl\n3 matching events found'),
    V2(id='audit-search-by-comm-v2-0042', tool='audit', operation='search-by-comm',
       complexity='diagnostic',
       user_input='did anyone run visudo on this host in the last week?',
       args={'operation': 'search-by-comm', 'comm': 'visudo'},
       answer='ausearch -c visudo\nno matching events'),
    V2(id='audit-search-by-comm-v2-0043', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='pull every audit event for the crontab binary',
       args={'operation': 'search-by-comm', 'comm': 'crontab'},
       answer='ausearch -c crontab\n6 matching events found'),
    V2(id='audit-search-by-comm-v2-0044', tool='audit', operation='search-by-comm',
       complexity='multi',
       user_input='find audit events for useradd and then check if any of them lack a corresponding audit-log entry for groupadd',
       args={'operation': 'search-by-comm', 'comm': 'useradd'},
       answer='ausearch -c useradd\n2 matching events found\nausearch -c groupadd: 1 matching event found'),
    V2(id='audit-search-by-comm-v2-0045', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='show audit log entries for the su command',
       args={'operation': 'search-by-comm', 'comm': 'su'},
       answer='ausearch -c su\n15 matching events found'),
    V2(id='audit-search-by-comm-v2-0046', tool='audit', operation='search-by-comm',
       complexity='diagnostic',
       user_input='we suspect someone is running setenforce manually — anything in the audit log for it?',
       args={'operation': 'search-by-comm', 'comm': 'setenforce'},
       answer='ausearch -c setenforce\n1 matching event found, auid=1001'),
    V2(id='audit-search-by-comm-v2-0047', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='search audit records for the rsync executable',
       args={'operation': 'search-by-comm', 'comm': 'rsync'},
       answer='ausearch -c rsync\n9 matching events found'),
    V2(id='audit-search-by-comm-v2-0048', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='look for audit entries tied to the mount command',
       args={'operation': 'search-by-comm', 'comm': 'mount'},
       answer='ausearch -c mount\n4 matching events found'),
    V2(id='audit-search-by-comm-v2-0049', tool='audit', operation='search-by-comm',
       complexity='diagnostic',
       user_input='httpd config was reloaded outside the maintenance window, is there an audit trail for apachectl?',
       args={'operation': 'search-by-comm', 'comm': 'apachectl'},
       answer='ausearch -c apachectl\n1 matching event found, timestamp 03:12:07'),
    V2(id='audit-search-by-comm-v2-0050', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='search-by-comm for passwd',
       args={'operation': 'search-by-comm', 'comm': 'passwd'},
       answer='ausearch -c passwd\n3 matching events found'),
    V2(id='audit-search-by-comm-v2-0051', tool='audit', operation='search-by-comm',
       complexity='single',
       user_input='find audit events matching the ssh-keygen executable',
       args={'operation': 'search-by-comm', 'comm': 'ssh-keygen'},
       answer='ausearch -c ssh-keygen\n2 matching events found'),
    V2(id='audit-search-by-key-v2-0052', tool='audit', operation='search-by-key',
       complexity='single',
       user_input='pull all audit events tagged with the hosts_watch key',
       args={'operation': 'search-by-key', 'key': 'hosts_watch'},
       answer='ausearch -k hosts_watch\n2 matching events found'),
    V2(id='audit-search-by-key-v2-0053', tool='audit', operation='search-by-key',
       complexity='diagnostic',
       user_input='is anything actually hitting the setuid_watch key we added last month?',
       args={'operation': 'search-by-key', 'key': 'setuid_watch'},
       answer='ausearch -k setuid_watch\nno matching events'),
    V2(id='audit-search-by-key-v2-0054', tool='audit', operation='search-by-key',
       complexity='single',
       user_input="search the audit log for events keyed 'limits_watch'",
       args={'operation': 'search-by-key', 'key': 'limits_watch'},
       answer='ausearch -k limits_watch\n1 matching event found'),
    V2(id='audit-search-by-key-v2-0055', tool='audit', operation='search-by-key',
       complexity='multi',
       user_input='search for events keyed net_watch and then run a summary report to cross check the count',
       args={'operation': 'search-by-key', 'key': 'net_watch'},
       answer='ausearch -k net_watch\n5 matching events found\naureport summary: 5 net_watch events, 400 total events today'),
    V2(id='audit-search-by-key-v2-0056', tool='audit', operation='search-by-key',
       complexity='single',
       user_input="show me everything tagged 'gshadow_watch'",
       args={'operation': 'search-by-key', 'key': 'gshadow_watch'},
       answer='ausearch -k gshadow_watch\n0 matching events'),
    V2(id='audit-search-by-key-v2-0057', tool='audit', operation='search-by-key',
       complexity='diagnostic',
       user_input='the cron_watch rule fired a lot last night, what does the audit log actually show?',
       args={'operation': 'search-by-key', 'key': 'cron_watch'},
       answer='ausearch -k cron_watch\n22 matching events found, all from user root'),
    V2(id='audit-search-by-key-v2-0058', tool='audit', operation='search-by-key',
       complexity='single',
       user_input='search-by-key module_watch',
       args={'operation': 'search-by-key', 'key': 'module_watch'},
       answer='ausearch -k module_watch\n3 matching events found'),
    V2(id='audit-search-by-key-v2-0059', tool='audit', operation='search-by-key',
       complexity='single',
       user_input="find audit events for key 'delete_watch'",
       args={'operation': 'search-by-key', 'key': 'delete_watch'},
       answer='ausearch -k delete_watch\n7 matching events found'),
    V2(id='audit-search-by-key-v2-0060', tool='audit', operation='search-by-key',
       complexity='diagnostic',
       user_input='we tagged a sudoers watch as sudoers_watch, has it fired since the last audit review?',
       args={'operation': 'search-by-key', 'key': 'sudoers_watch'},
       answer='ausearch -k sudoers_watch\n1 matching event found, 02/14/2026'),
    V2(id='audit-search-by-key-v2-0061', tool='audit', operation='search-by-key',
       complexity='single',
       user_input='pull audit events for the fapd_watch key',
       args={'operation': 'search-by-key', 'key': 'fapd_watch'},
       answer='ausearch -k fapd_watch\n0 matching events'),
    V2(id='audit-search-by-key-v2-0062', tool='audit', operation='search-by-key',
       complexity='single',
       user_input='search audit log for key root_net_watch',
       args={'operation': 'search-by-key', 'key': 'root_net_watch'},
       answer='ausearch -k root_net_watch\n4 matching events found'),
    V2(id='audit-search-by-time-v2-0063', tool='audit', operation='search-by-time',
       complexity='single',
       user_input='pull audit events from the last hour',
       args={'operation': 'search-by-time', 'start': 'recent'},
       answer='ausearch -ts recent\n18 matching events found'),
    V2(id='audit-search-by-time-v2-0064', tool='audit', operation='search-by-time',
       complexity='diagnostic',
       user_input='the breach window looks like it was between 01:00 and 03:00 this morning — pull that range',
       args={'operation': 'search-by-time', 'start': '09/12/2026 01:00:00', 'end': '09/12/2026 03:00:00'},
       answer='ausearch -ts 09/12/2026 01:00:00 -te 09/12/2026 03:00:00\n6 matching events found'),
    V2(id='audit-search-by-time-v2-0065', tool='audit', operation='search-by-time',
       complexity='single',
       user_input="get today's audit events",
       args={'operation': 'search-by-time', 'start': 'today'},
       answer='ausearch -ts today\n412 matching events found'),
    V2(id='audit-search-by-time-v2-0066', tool='audit', operation='search-by-time',
       complexity='single',
       user_input="show yesterday's full audit log window",
       args={'operation': 'search-by-time', 'start': 'yesterday'},
       answer='ausearch -ts yesterday\n389 matching events found'),
    V2(id='audit-search-by-time-v2-0067', tool='audit', operation='search-by-time',
       complexity='multi',
       user_input='pull audit events from today and then run the login report over the same window',
       args={'operation': 'search-by-time', 'start': 'today'},
       answer='ausearch -ts today\n412 matching events found\naureport login: 44 login events today'),
    V2(id='audit-search-by-time-v2-0068', tool='audit', operation='search-by-time',
       complexity='diagnostic',
       user_input='was there any audit activity while the on-call was unreachable, 22:00 to 23:30 last night?',
       args={'operation': 'search-by-time', 'start': '09/11/2026 22:00:00', 'end': '09/11/2026 23:30:00'},
       answer='ausearch -ts 09/11/2026 22:00:00 -te 09/11/2026 23:30:00\n2 matching events found'),
    V2(id='audit-search-by-time-v2-0069', tool='audit', operation='search-by-time',
       complexity='single',
       user_input='search audit events from the last 24 hours starting at midnight',
       args={'operation': 'search-by-time', 'start': '09/11/2026 00:00:00'},
       answer='ausearch -ts 09/11/2026 00:00:00\n401 matching events found'),
    V2(id='audit-search-by-time-v2-0070', tool='audit', operation='search-by-time',
       complexity='single',
       user_input='show audit log entries between 08:00:00 and 08:15:00 on 09/10/2026',
       args={'operation': 'search-by-time', 'start': '09/10/2026 08:00:00', 'end': '09/10/2026 08:15:00'},
       answer='ausearch -ts 09/10/2026 08:00:00 -te 09/10/2026 08:15:00\n3 matching events found'),
    V2(id='audit-search-by-time-v2-0071', tool='audit', operation='search-by-time',
       complexity='diagnostic',
       user_input='the network team says a bring_down happened around 14:00, does the audit trail confirm anything then?',
       args={'operation': 'search-by-time', 'start': '09/12/2026 13:45:00', 'end': '09/12/2026 14:15:00'},
       answer='ausearch -ts 09/12/2026 13:45:00 -te 09/12/2026 14:15:00\n1 matching event found'),
    V2(id='audit-search-by-time-v2-0072', tool='audit', operation='search-by-time',
       complexity='single',
       user_input='pull recent audit events, just the last few minutes',
       args={'operation': 'search-by-time', 'start': 'recent'},
       answer='ausearch -ts recent\n5 matching events found'),
    V2(id='audit-search-by-time-v2-0073', tool='audit', operation='search-by-time',
       complexity='single',
       user_input='get audit records for the past week',
       args={'operation': 'search-by-time', 'start': '09/05/2026 00:00:00'},
       answer='ausearch -ts 09/05/2026 00:00:00\n2890 matching events found'),
    V2(id='audit-report-v2-0074', tool='audit', operation='report',
       complexity='single',
       user_input='run the audit summary report',
       args={'operation': 'report'},
       answer='aureport summary\n412 events, 44 logins, 6 auth failures'),
    V2(id='audit-report-v2-0075', tool='audit', operation='report',
       complexity='single',
       user_input='give me the file access report from audit',
       args={'operation': 'report', 'report_type': 'file'},
       answer='aureport file\n88 file access events, 12 write denials'),
    V2(id='audit-report-v2-0076', tool='audit', operation='report',
       complexity='diagnostic',
       user_input='were there any failed logins overnight worth flagging?',
       args={'operation': 'report', 'report_type': 'login'},
       answer='aureport login\n44 login events, 3 failures, all from 10.0.4.0/24'),
    V2(id='audit-report-v2-0077', tool='audit', operation='report',
       complexity='single',
       user_input='pull the auth report from the audit subsystem',
       args={'operation': 'report', 'report_type': 'auth'},
       answer='aureport auth\n60 auth events, 2 failures'),
    V2(id='audit-report-v2-0078', tool='audit', operation='report',
       complexity='single',
       user_input='show me AVC denials from the audit log',
       args={'operation': 'report', 'report_type': 'avc'},
       answer='aureport avc\n0 AVC denials recorded'),
    V2(id='audit-report-v2-0079', tool='audit', operation='report',
       complexity='multi',
       user_input='run the exec report and then search by key for anything tagged exec_watch',
       args={'operation': 'report', 'report_type': 'exec'},
       answer='aureport exec\n120 exec events\nausearch -k exec_watch: 4 matching events'),
    V2(id='audit-report-v2-0080', tool='audit', operation='report',
       complexity='diagnostic',
       user_input='did anything unusual show up in execs today across the fleet?',
       args={'operation': 'report', 'report_type': 'exec'},
       answer='aureport exec\n120 exec events, top binary: bash (44)'),
    V2(id='audit-report-v2-0081', tool='audit', operation='report',
       complexity='single',
       user_input='generate the standard audit summary report',
       args={'operation': 'report'},
       answer='aureport summary\n412 events, 0 anomalies flagged'),
    V2(id='audit-report-v2-0082', tool='audit', operation='report',
       complexity='single',
       user_input='pull the login report for the audit subsystem',
       args={'operation': 'report', 'report_type': 'login'},
       answer='aureport login\n44 login events, 3 failures'),
    V2(id='audit-report-v2-0083', tool='audit', operation='report',
       complexity='single',
       user_input='give me a summary-type audit report',
       args={'operation': 'report'},
       answer='aureport summary\n412 events total'),
    V2(id='audit-report-v2-0084', tool='audit', operation='report',
       complexity='diagnostic',
       user_input='compliance wants to know if any AVC denials happened this week',
       args={'operation': 'report', 'report_type': 'avc'},
       answer='aureport avc\n2 AVC denials found, both httpd_t'),
    V2(id='audit-auditd-start-v2-0085', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='start the audit daemon',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0086', tool='audit', operation='auditd-start',
       complexity='diagnostic',
       user_input='the compliance scan says auditd is not running, can you bring it up?',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0087', tool='audit', operation='auditd-start',
       complexity='multi',
       user_input='start auditd and then confirm status shows it enabled',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)\nAUDIT_STATUS: enabled=1 pid=2201'),
    V2(id='audit-auditd-start-v2-0088', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='enable the audit daemon on this host',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0089', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='bring auditd back up after the outage',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0090', tool='audit', operation='auditd-start',
       complexity='diagnostic',
       user_input='logins are not being audited, is the daemon even up?',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running), was inactive'),
    V2(id='audit-auditd-start-v2-0091', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='auditd-start on this box',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0092', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='kick off the audit daemon so rule changes take effect',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0093', tool='audit', operation='auditd-start',
       complexity='multi',
       user_input='start auditd then add the exec_watch rule back',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)\nauditctl -a always,exit -F arch=b64 -S execve -k exec_watch\nrule added'),
    V2(id='audit-auditd-start-v2-0094', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='get auditd running again',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0095', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='start audit logging on db02',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0096', tool='audit', operation='auditd-start',
       complexity='diagnostic',
       user_input='the fapolicyd rollout may have stopped auditd as a side effect — check and restart it',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-start-v2-0097', tool='audit', operation='auditd-start',
       complexity='single',
       user_input='turn the audit daemon back on',
       args={'operation': 'auditd-start'},
       answer='systemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-stop-v2-0098', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='stop the audit daemon for maintenance',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0099', tool='audit', operation='auditd-stop',
       complexity='diagnostic',
       user_input='auditd is chewing 40% CPU, can we pause it while we investigate?',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0100', tool='audit', operation='auditd-stop',
       complexity='multi',
       user_input='stop auditd, rotate the log file, then start it again',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)\nlogrotate /etc/audit/audit.log: rotated\nsystemctl start auditd\nauditd.service: active (running)'),
    V2(id='audit-auditd-stop-v2-0101', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='halt the audit subsystem temporarily',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0102', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='shut down auditd while we do disk maintenance on /var/log/audit',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0103', tool='audit', operation='auditd-stop',
       complexity='diagnostic',
       user_input='disk is filling up under /var/log/audit, should we stop the daemon first before cleanup?',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0104', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='auditd-stop please',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0105', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='stop audit logging on this node',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0106', tool='audit', operation='auditd-stop',
       complexity='multi',
       user_input='stop auditd and then delete all its rules before the rebuild',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)\nauditctl -D\nall rules deleted (was: 7 rules)'),
    V2(id='audit-auditd-stop-v2-0107', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='pause the audit daemon',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0108', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='stop auditd on the staging host',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0109', tool='audit', operation='auditd-stop',
       complexity='diagnostic',
       user_input='is it safe to stop auditd before we swap the /var/log/audit disk, and can you do it now?',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
    V2(id='audit-auditd-stop-v2-0110', tool='audit', operation='auditd-stop',
       complexity='single',
       user_input='bring auditd down',
       args={'operation': 'auditd-stop'},
       answer='systemctl stop auditd\nauditd.service: inactive (dead)'),
]

from finetune.scenarios_v2 import check_module; check_module('audit', SCENARIOS_V2)
