"""finetune/scenarios_v2/bond.py — corpus v2 scenarios for 'bond'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="bond-show-v2-0001", tool="bond", operation="show",
       complexity="single",
       user_input="Pull up the connection details for bond2 on db-node-3.",
       args={"operation": "show", "bond": "bond2"},
       answer="bond2: type=bond, state=activated\nmode=active-backup, primary=eno1\nslaves: eno1 (up), eno2 (backup)\nipv4.method=auto, ip4=10.20.4.17/24"),
    V2(id="bond-show-v2-0002", tool="bond", operation="show",
       complexity="diagnostic",
       user_input="One of our aggregated NICs on web-07 seems to have dropped a leg — can you tell me the current state of bond1 before I page the network team?",
       args={"operation": "show", "bond": "bond1"},
       answer="bond1: type=bond, state=activated\nmode=802.3ad, slaves: enp3s0 (up), enp4s0 (down, mii_status=down)\nlacp_rate=fast, ad_actor_key=0x0"),
    V2(id="bond-add-v2-0001", tool="bond", operation="add",
       complexity="single",
       user_input="Create a new bond interface named bond3 using 802.3ad mode.",
       args={"operation": "add", "bond": "bond3", "mode": "802.3ad"},
       answer="Connection 'bond3' (a1f4c2e0-...) successfully added.\nmode=802.3ad"),
    V2(id="bond-add-v2-0002", tool="bond", operation="add",
       complexity="single",
       user_input="I need a bonded interface called bond5 for the storage NICs, just use the default failover mode.",
       args={"operation": "add", "bond": "bond5"},
       answer="Connection 'bond5' (7bd90e11-...) successfully added.\nmode=active-backup (default)"),
    V2(id="bond-add-v2-0003", tool="bond", operation="add",
       complexity="multi",
       user_input="Set up bond4 in balance-rr mode, then I'll attach the two spare 1G ports to it myself.",
       args={"operation": "add", "bond": "bond4", "mode": "balance-rr"},
       answer="Connection 'bond4' (9c22e88a-...) successfully added.\nmode=balance-rr, slaves: none yet"),
    V2(id="bond-add-v2-0004", tool="bond", operation="add",
       complexity="diagnostic",
       user_input="This host only has one live NIC and it's a single point of failure for the cluster heartbeat network — set up bond0 so we have somewhere to attach a second link.",
       args={"operation": "add", "bond": "bond0", "mode": "active-backup"},
       answer="Connection 'bond0' (4e1a7d90-...) successfully added.\nmode=active-backup, slaves: none yet"),
    V2(id="bond-modify-v2-0001", tool="bond", operation="modify",
       complexity="single",
       user_input="Bump the miimon polling interval on bond0 up to 150ms.",
       args={"operation": "modify", "bond": "bond0", "property": "bond.options", "value": "miimon=150"},
       answer="Connection 'bond0' updated.\nbond.options: miimon=150,mode=active-backup"),
    V2(id="bond-modify-v2-0002", tool="bond", operation="modify",
       complexity="single",
       user_input="Set bond1's ipv4 method to manual with address 10.5.0.9/24.",
       args={"operation": "modify", "bond": "bond1", "property": "ipv4.addresses", "value": "10.5.0.9/24"},
       answer="Connection 'bond1' updated.\nipv4.addresses: 10.5.0.9/24"),
    V2(id="bond-modify-v2-0003", tool="bond", operation="modify",
       complexity="single",
       user_input="Turn off autoconnect for bond2, we bring it up manually during maintenance windows.",
       args={"operation": "modify", "bond": "bond2", "property": "connection.autoconnect", "value": "no"},
       answer="Connection 'bond2' updated.\nconnection.autoconnect: no"),
    V2(id="bond-modify-v2-0004", tool="bond", operation="modify",
       complexity="multi",
       user_input="Switch bond0 over to 802.3ad since the switch team finished configuring LACP, and after that show me the resulting config.",
       args={"operation": "modify", "bond": "bond0", "property": "bond.options", "value": "mode=802.3ad"},
       answer="Connection 'bond0' updated.\nbond.options: mode=802.3ad"),
    V2(id="bond-modify-v2-0005", tool="bond", operation="modify",
       complexity="diagnostic",
       user_input="Failover on bond1 is taking almost 5 seconds and dropping the app's health checks — what would tightening the downdelay to 100ms on bond1 look like?",
       args={"operation": "modify", "bond": "bond1", "property": "bond.options", "value": "downdelay=100"},
       answer="Connection 'bond1' updated.\nbond.options: downdelay=100,miimon=100"),
    V2(id="bond-modify-v2-0006", tool="bond", operation="modify",
       complexity="diagnostic",
       user_input="bond3's gateway seems wrong, nothing outside the local subnet is reachable — set the gateway on bond3 to 10.9.0.1.",
       args={"operation": "modify", "bond": "bond3", "property": "ipv4.gateway", "value": "10.9.0.1"},
       answer="Connection 'bond3' updated.\nipv4.gateway: 10.9.0.1"),
    V2(id="bond-remove-v2-0001", tool="bond", operation="remove",
       complexity="single",
       user_input="Delete the bond2 connection, we're going back to a single-NIC layout on that host.",
       args={"operation": "remove", "bond": "bond2"},
       answer="Connection 'bond2' (a1f4c2e0-...) successfully deleted."),
    V2(id="bond-remove-v2-0002", tool="bond", operation="remove",
       complexity="single",
       user_input="Tear down bond5.",
       args={"operation": "remove", "bond": "bond5"},
       answer="Connection 'bond5' (7bd90e11-...) successfully deleted."),
    V2(id="bond-remove-v2-0003", tool="bond", operation="remove",
       complexity="multi",
       user_input="Delete bond1 and then double check it's no longer in the connection list.",
       args={"operation": "remove", "bond": "bond1"},
       answer="Connection 'bond1' (deleted).\nnmcli connection show: bond1 no longer present"),
    V2(id="bond-remove-v2-0004", tool="bond", operation="remove",
       complexity="diagnostic",
       user_input="We're seeing a broadcast storm on the switch and bond4 in balance-rr mode is the suspect — remove it right away to stop the loop.",
       args={"operation": "remove", "bond": "bond4"},
       answer="Connection 'bond4' successfully deleted.\nInterface bond4 no longer active."),
    V2(id="bond-remove-v2-0005", tool="bond", operation="remove",
       complexity="single",
       user_input="Get rid of the old bond0 config, the ports it used were reassigned to individual links last week.",
       args={"operation": "remove", "bond": "bond0"},
       answer="Connection 'bond0' (4e1a7d90-...) successfully deleted."),
    V2(id="bond-remove-v2-0006", tool="bond", operation="remove",
       complexity="diagnostic",
       user_input="bond3 has been flapping between backup members for an hour and network is asking us to just pull it and reconfigure from scratch — remove bond3.",
       args={"operation": "remove", "bond": "bond3"},
       answer="Connection 'bond3' successfully deleted.\nWarning: no aggregated link remained active on that host."),
]

from finetune.scenarios_v2 import check_module; check_module("bond", SCENARIOS_V2)
