"""finetune/scenarios_v2/buildah.py — corpus v2 scenarios for 'buildah'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="buildah-images-v2-0001", tool="buildah", operation="images",
       complexity="single",
       user_input="Show me every OCI image buildah has cached on this box.",
       args={"operation": "images"},
       answer="REPOSITORY                          TAG      IMAGE ID       SIZE\nregistry.access.redhat.com/ubi9/ubi latest   a1b2c3d4e5f6   234 MB\nlocalhost/myapp                     1.0      f00dcafe0011   412 MB\n2 images listed."),
    V2(id="buildah-images-v2-0002", tool="buildah", operation="images",
       complexity="single",
       user_input="Include intermediate layers when you list buildah's local images.",
       args={"operation": "images", "all": True},
       answer="REPOSITORY   TAG      IMAGE ID       SIZE\n<none>       <none>   0011deadbeef   198 MB\nlocalhost/myapp 1.0    f00dcafe0011   412 MB\n5 images listed (includes 3 intermediate)."),
    V2(id="buildah-images-v2-0003", tool="buildah", operation="images",
       complexity="diagnostic",
       user_input="The runner host is out of disk again — can you tell what's eating space in the local image store?",
       args={"operation": "images", "all": True},
       answer="7 images totaling 3.1 GB.\nLargest: localhost/ci-runner:stale 1.4 GB (unused 40 days)\n4 dangling <none> images, 620 MB."),
    V2(id="buildah-images-v2-0004", tool="buildah", operation="images",
       complexity="single",
       user_input="List container images on the fedora build node.",
       args={"operation": "images"},
       answer="REPOSITORY        TAG      IMAGE ID       SIZE\nregistry.fedoraproject.org/fedora latest 7788990011ab 178 MB\n1 image listed."),
    V2(id="buildah-images-v2-0005", tool="buildah", operation="images",
       complexity="multi",
       user_input="List the local images first, then remove the container named stale-ctr.",
       args={"operation": "images"},
       answer="REPOSITORY   TAG    IMAGE ID       SIZE\nlocalhost/app main   334455667788   201 MB\n1 image listed."),
    V2(id="buildah-images-v2-0006", tool="buildah", operation="images",
       complexity="single",
       user_input="What images are sitting in the buildah store right now?",
       args={"operation": "images"},
       answer="REPOSITORY                TAG      IMAGE ID       SIZE\ndocker.io/library/nginx   1.25     9900aabbccdd   187 MB\n1 image listed."),
    V2(id="buildah-images-v2-0007", tool="buildah", operation="images",
       complexity="diagnostic",
       user_input="Before I run a firewall change on this build node, is there anything odd about the image cache — like duplicate tags?",
       args={"operation": "images"},
       answer="4 images, no duplicate tags found.\nAll images pulled within the last 12 days."),
    V2(id="buildah-images-v2-0008", tool="buildah", operation="images",
       complexity="single",
       user_input="pull up the local ubi9-minimal images",
       args={"operation": "images"},
       answer="REPOSITORY                                  TAG      IMAGE ID       SIZE\nregistry.access.redhat.com/ubi9/ubi-minimal latest   00ff11ee22dd   102 MB\n1 image listed."),
    V2(id="buildah-images-v2-0009", tool="buildah", operation="images",
       complexity="single",
       user_input="Show all images, intermediates included, for the nightly cleanup ticket.",
       args={"operation": "images", "all": True},
       answer="6 images listed (2 intermediate).\nTotal size 1.8 GB."),
    V2(id="buildah-images-v2-0010", tool="buildah", operation="images",
       complexity="diagnostic",
       user_input="A colleague says the app image never got rebuilt after last night's commit — can you confirm what's actually in the local store?",
       args={"operation": "images"},
       answer="localhost/myapp:1.0 image ID f00dcafe0011, created 18 hours ago.\nNo newer localhost/myapp tag present."),

    V2(id="buildah-from-v2-0001", tool="buildah", operation="from",
       complexity="single",
       user_input="Start a new working container from registry.access.redhat.com/ubi9/ubi-minimal.",
       args={"operation": "from", "image": "registry.access.redhat.com/ubi9/ubi-minimal"},
       answer="ubi-minimal-working-container\nWorking container ID: 3fa1c9de8b21"),
    V2(id="buildah-from-v2-0002", tool="buildah", operation="from",
       complexity="single",
       user_input="Create a container off the alpine image.",
       args={"operation": "from", "image": "alpine:3.19"},
       answer="alpine-working-container\nWorking container ID: 88bb2211ccdd"),
    V2(id="buildah-from-v2-0003", tool="buildah", operation="from",
       complexity="multi",
       user_input="Create a working container from ubi9 and then copy ./bin/app into it.",
       args={"operation": "from", "image": "registry.access.redhat.com/ubi9/ubi"},
       answer="ubi-working-container\nWorking container ID: aa11bb22cc33"),
    V2(id="buildah-from-v2-0004", tool="buildah", operation="from",
       complexity="single",
       user_input="I need a fresh container based on postgres:16 to test a migration.",
       args={"operation": "from", "image": "docker.io/library/postgres:16"},
       answer="postgres-working-container\nWorking container ID: 5566778899aa"),
    V2(id="buildah-from-v2-0005", tool="buildah", operation="from",
       complexity="diagnostic",
       user_input="The pipeline keeps failing at the from step — can you try creating the working container from ubi9 directly and see what error comes back?",
       args={"operation": "from", "image": "registry.access.redhat.com/ubi9/ubi"},
       answer="ubi-working-container\nWorking container ID: 001122aabbcc\nNo errors during pull or container creation."),
    V2(id="buildah-from-v2-0006", tool="buildah", operation="from",
       complexity="single",
       user_input="spin up a working container from scratch",
       args={"operation": "from", "image": "scratch"},
       answer="scratch-working-container\nWorking container ID: 0000111122223333"),
    V2(id="buildah-from-v2-0007", tool="buildah", operation="from",
       complexity="single",
       user_input="Base a new build container on the rockylinux:9 image for the RPM packaging job.",
       args={"operation": "from", "image": "rockylinux:9"},
       answer="rockylinux-working-container\nWorking container ID: ffeeddccbbaa"),
    V2(id="buildah-from-v2-0008", tool="buildah", operation="from",
       complexity="multi",
       user_input="Create a container from nginx:1.25 and then run a config test inside it.",
       args={"operation": "from", "image": "docker.io/library/nginx:1.25"},
       answer="nginx-working-container\nWorking container ID: 13579bdf2468"),
    V2(id="buildah-from-v2-0009", tool="buildah", operation="from",
       complexity="single",
       user_input="new working container, image is registry.access.redhat.com/ubi9/nodejs-20",
       args={"operation": "from", "image": "registry.access.redhat.com/ubi9/nodejs-20"},
       answer="nodejs-20-working-container\nWorking container ID: 2468ace013579"),
    V2(id="buildah-from-v2-0010", tool="buildah", operation="from",
       complexity="diagnostic",
       user_input="We're not sure the private registry mirror is reachable — try creating a container from myregistry.internal/base:latest and tell me if it succeeds.",
       args={"operation": "from", "image": "myregistry.internal/base:latest"},
       answer="base-working-container\nWorking container ID: 998877665544\nPull succeeded, mirror reachable."),

    V2(id="buildah-copy-v2-0001", tool="buildah", operation="copy",
       complexity="single",
       user_input="Copy ./build/output.bin into the ubi-working-container at /usr/local/bin/output.bin.",
       args={"operation": "copy", "container": "ubi-working-container", "src": "./build/output.bin", "dst": "/usr/local/bin/output.bin"},
       answer="Copied ./build/output.bin -> /usr/local/bin/output.bin\ncontainer: ubi-working-container"),
    V2(id="buildah-copy-v2-0002", tool="buildah", operation="copy",
       complexity="single",
       user_input="Add my custom.conf file into the nginx-working-container at /etc/nginx/conf.d/custom.conf.",
       args={"operation": "copy", "container": "nginx-working-container", "src": "custom.conf", "dst": "/etc/nginx/conf.d/custom.conf"},
       answer="Copied custom.conf -> /etc/nginx/conf.d/custom.conf\ncontainer: nginx-working-container"),
    V2(id="buildah-copy-v2-0003", tool="buildah", operation="copy",
       complexity="multi",
       user_input="Copy the app directory into myapp-working-container at /app, then commit it as myapp:1.1.",
       args={"operation": "copy", "container": "myapp-working-container", "src": "./app", "dst": "/app"},
       answer="Copied ./app -> /app\ncontainer: myapp-working-container"),
    V2(id="buildah-copy-v2-0004", tool="buildah", operation="copy",
       complexity="single",
       user_input="the container is missing its entrypoint script — copy ./scripts/entry.sh to /entrypoint.sh in postgres-working-container",
       args={"operation": "copy", "container": "postgres-working-container", "src": "./scripts/entry.sh", "dst": "/entrypoint.sh"},
       answer="Copied ./scripts/entry.sh -> /entrypoint.sh\ncontainer: postgres-working-container"),
    V2(id="buildah-copy-v2-0005", tool="buildah", operation="copy",
       complexity="diagnostic",
       user_input="The build step after copy keeps failing with a missing file error — can you copy ./dist/app.jar into build-ctr at /opt/app/app.jar and confirm it lands?",
       args={"operation": "copy", "container": "build-ctr", "src": "./dist/app.jar", "dst": "/opt/app/app.jar"},
       answer="Copied ./dist/app.jar -> /opt/app/app.jar\ncontainer: build-ctr\nFile present at destination, 42 MB."),
    V2(id="buildah-copy-v2-0006", tool="buildah", operation="copy",
       complexity="single",
       user_input="put the tls cert bundle into ubi-minimal-working-container under /etc/pki/tls/certs/bundle.pem",
       args={"operation": "copy", "container": "ubi-minimal-working-container", "src": "./certs/bundle.pem", "dst": "/etc/pki/tls/certs/bundle.pem"},
       answer="Copied ./certs/bundle.pem -> /etc/pki/tls/certs/bundle.pem\ncontainer: ubi-minimal-working-container"),
    V2(id="buildah-copy-v2-0007", tool="buildah", operation="copy",
       complexity="single",
       user_input="Copy requirements.txt into python-working-container at /tmp/requirements.txt.",
       args={"operation": "copy", "container": "python-working-container", "src": "requirements.txt", "dst": "/tmp/requirements.txt"},
       answer="Copied requirements.txt -> /tmp/requirements.txt\ncontainer: python-working-container"),
    V2(id="buildah-copy-v2-0008", tool="buildah", operation="copy",
       complexity="multi",
       user_input="Copy the static assets folder into web-working-container at /var/www/html, then run a permissions fix.",
       args={"operation": "copy", "container": "web-working-container", "src": "./static", "dst": "/var/www/html"},
       answer="Copied ./static -> /var/www/html\ncontainer: web-working-container"),
    V2(id="buildah-copy-v2-0009", tool="buildah", operation="copy",
       complexity="single",
       user_input="drop the systemd unit file into rocky-working-container at /etc/systemd/system/myapp.service",
       args={"operation": "copy", "container": "rocky-working-container", "src": "./myapp.service", "dst": "/etc/systemd/system/myapp.service"},
       answer="Copied ./myapp.service -> /etc/systemd/system/myapp.service\ncontainer: rocky-working-container"),
    V2(id="buildah-copy-v2-0010", tool="buildah", operation="copy",
       complexity="diagnostic",
       user_input="Not sure the config volume actually mounted right in the last run — copy ./config/app.yaml into svc-working-container at /etc/app/app.yaml and check it worked.",
       args={"operation": "copy", "container": "svc-working-container", "src": "./config/app.yaml", "dst": "/etc/app/app.yaml"},
       answer="Copied ./config/app.yaml -> /etc/app/app.yaml\ncontainer: svc-working-container\nDestination file present, 1.2 KB."),

    V2(id="buildah-run-v2-0001", tool="buildah", operation="run",
       complexity="single",
       user_input="Run dnf install -y httpd inside the ubi-working-container.",
       args={"operation": "run", "container": "ubi-working-container", "command": "dnf install -y httpd"},
       answer="Installed: httpd-2.4.57-5.el9\nExit code 0."),
    V2(id="buildah-run-v2-0002", tool="buildah", operation="run",
       complexity="single",
       user_input="execute pip install -r requirements.txt in python-working-container",
       args={"operation": "run", "container": "python-working-container", "command": "pip install -r requirements.txt"},
       answer="Successfully installed flask-3.0.0 gunicorn-21.2.0\nExit code 0."),
    V2(id="buildah-run-v2-0003", tool="buildah", operation="run",
       complexity="multi",
       user_input="Run the database migration script inside pg-working-container, then commit the container as pg-migrated.",
       args={"operation": "run", "container": "pg-working-container", "command": "/opt/app/migrate.sh"},
       answer="Migration applied: 12 statements executed.\nExit code 0."),
    V2(id="buildah-run-v2-0004", tool="buildah", operation="run",
       complexity="single",
       user_input="clean the dnf cache in build-working-container to shrink the image",
       args={"operation": "run", "container": "build-working-container", "command": "dnf clean all"},
       answer="Cleaned 3 cache directories.\nExit code 0."),
    V2(id="buildah-run-v2-0005", tool="buildah", operation="run",
       complexity="diagnostic",
       user_input="The commit step later produces a broken image — can you run 'ls -la /opt/app' inside app-working-container and see what's actually there?",
       args={"operation": "run", "container": "app-working-container", "command": "ls -la /opt/app"},
       answer="total 3\ndrwxr-xr-x. 2 root root 4096 Sep 12 10:02 .\n-rwxr-xr-x. 1 root root  812 Sep 12 10:02 app.jar\nExit code 0."),
    V2(id="buildah-run-v2-0006", tool="buildah", operation="run",
       complexity="single",
       user_input="run npm ci inside node-working-container",
       args={"operation": "run", "container": "node-working-container", "command": "npm ci"},
       answer="added 214 packages in 8s\nExit code 0."),
    V2(id="buildah-run-v2-0007", tool="buildah", operation="run",
       complexity="single",
       user_input="Inside rocky-working-container, run 'useradd -r svcacct' to add the service account before commit.",
       args={"operation": "run", "container": "rocky-working-container", "command": "useradd -r svcacct"},
       answer="User svcacct created, UID 986.\nExit code 0."),
    V2(id="buildah-run-v2-0008", tool="buildah", operation="run",
       complexity="diagnostic",
       user_input="ssh into the box isn't needed for this — just run 'systemctl is-enabled httpd' in web-working-container to check the unit state",
       args={"operation": "run", "container": "web-working-container", "command": "systemctl is-enabled httpd"},
       answer="disabled\nExit code 1."),
    V2(id="buildah-run-v2-0009", tool="buildah", operation="run",
       complexity="single",
       user_input="Set the timezone with 'ln -sf /usr/share/zoneinfo/UTC /etc/localtime' in ubi-minimal-working-container.",
       args={"operation": "run", "container": "ubi-minimal-working-container", "command": "ln -sf /usr/share/zoneinfo/UTC /etc/localtime"},
       answer="Symlink updated: /etc/localtime -> /usr/share/zoneinfo/UTC\nExit code 0."),
    V2(id="buildah-run-v2-0010", tool="buildah", operation="run",
       complexity="multi",
       user_input="Run the smoke test script in api-working-container, and if it passes go ahead and push the image afterward.",
       args={"operation": "run", "container": "api-working-container", "command": "/opt/app/smoke_test.sh"},
       answer="8/8 checks passed.\nExit code 0."),

    V2(id="buildah-commit-v2-0001", tool="buildah", operation="commit",
       complexity="single",
       user_input="Commit ubi-working-container as an image named myapp:1.0.",
       args={"operation": "commit", "container": "ubi-working-container", "image": "myapp:1.0"},
       answer="Image committed: myapp:1.0\nImage ID: 6677889900aa"),
    V2(id="buildah-commit-v2-0002", tool="buildah", operation="commit",
       complexity="single",
       user_input="turn nginx-working-container into localhost/webproxy:latest",
       args={"operation": "commit", "container": "nginx-working-container", "image": "localhost/webproxy:latest"},
       answer="Image committed: localhost/webproxy:latest\nImage ID: aabb00ccdd11"),
    V2(id="buildah-commit-v2-0003", tool="buildah", operation="commit",
       complexity="multi",
       user_input="Commit pg-migrated as pg-app:2.3 and then push it to the internal registry.",
       args={"operation": "commit", "container": "pg-migrated", "image": "pg-app:2.3"},
       answer="Image committed: pg-app:2.3\nImage ID: 334455aa66bb"),
    V2(id="buildah-commit-v2-0004", tool="buildah", operation="commit",
       complexity="single",
       user_input="the config test passed, commit web-working-container as web-app:rc1",
       args={"operation": "commit", "container": "web-working-container", "image": "web-app:rc1"},
       answer="Image committed: web-app:rc1\nImage ID: 0099aabbccdd"),
    V2(id="buildah-commit-v2-0005", tool="buildah", operation="commit",
       complexity="diagnostic",
       user_input="A build ticket says the commit step silently failed last night — try committing api-working-container as api:nightly and confirm the image ID comes back.",
       args={"operation": "commit", "container": "api-working-container", "image": "api:nightly"},
       answer="Image committed: api:nightly\nImage ID: ffee11223344\nCommit succeeded, image present in local store."),
    V2(id="buildah-commit-v2-0006", tool="buildah", operation="commit",
       complexity="single",
       user_input="commit node-working-container to node-app:build-42",
       args={"operation": "commit", "container": "node-working-container", "image": "node-app:build-42"},
       answer="Image committed: node-app:build-42\nImage ID: 11223344aabb"),
    V2(id="buildah-commit-v2-0007", tool="buildah", operation="commit",
       complexity="single",
       user_input="Finalize rocky-working-container into an image called svc-base:9.",
       args={"operation": "commit", "container": "rocky-working-container", "image": "svc-base:9"},
       answer="Image committed: svc-base:9\nImage ID: 5566ccdd7788"),
    V2(id="buildah-commit-v2-0008", tool="buildah", operation="commit",
       complexity="multi",
       user_input="Commit ubi-minimal-working-container as base-hardened:1 and run it through the vulnerability scan next.",
       args={"operation": "commit", "container": "ubi-minimal-working-container", "image": "base-hardened:1"},
       answer="Image committed: base-hardened:1\nImage ID: 8899aabbccdd"),
    V2(id="buildah-commit-v2-0009", tool="buildah", operation="commit",
       complexity="single",
       user_input="python-working-container is ready, commit it as pyservice:0.9",
       args={"operation": "commit", "container": "python-working-container", "image": "pyservice:0.9"},
       answer="Image committed: pyservice:0.9\nImage ID: 22334455ffee"),
    V2(id="buildah-commit-v2-0010", tool="buildah", operation="commit",
       complexity="diagnostic",
       user_input="We want to be sure the entrypoint copy actually took before shipping — commit build-working-container as build-check:tmp and check it registers.",
       args={"operation": "commit", "container": "build-working-container", "image": "build-check:tmp"},
       answer="Image committed: build-check:tmp\nImage ID: 99aa11bb22cc\nImage now listed in local store."),

    V2(id="buildah-push-v2-0001", tool="buildah", operation="push",
       complexity="single",
       user_input="Push myapp:1.0 to the internal registry.",
       args={"operation": "push", "image": "myapp:1.0"},
       answer="Pushed myapp:1.0\nDigest: sha256:a1b2c3d4e5f6...\n312 MB transferred."),
    V2(id="buildah-push-v2-0002", tool="buildah", operation="push",
       complexity="single",
       user_input="push localhost/webproxy:latest out to registry.internal.example.com",
       args={"operation": "push", "image": "localhost/webproxy:latest"},
       answer="Pushed localhost/webproxy:latest\nDigest: sha256:00112233aabb...\n198 MB transferred."),
    V2(id="buildah-push-v2-0003", tool="buildah", operation="push",
       complexity="multi",
       user_input="Push pg-app:2.3 and then update the deployment manifest to reference it.",
       args={"operation": "push", "image": "pg-app:2.3"},
       answer="Pushed pg-app:2.3\nDigest: sha256:44556677ccdd...\n256 MB transferred."),
    V2(id="buildah-push-v2-0004", tool="buildah", operation="push",
       complexity="single",
       user_input="ship web-app:rc1 to the registry",
       args={"operation": "push", "image": "web-app:rc1"},
       answer="Pushed web-app:rc1\nDigest: sha256:8899ccdd0011...\n289 MB transferred."),
    V2(id="buildah-push-v2-0005", tool="buildah", operation="push",
       complexity="diagnostic",
       user_input="Deployment says the image isn't found in the registry — push api:nightly again and confirm it actually lands this time.",
       args={"operation": "push", "image": "api:nightly"},
       answer="Pushed api:nightly\nDigest: sha256:ffeeddccbbaa...\n Registry confirms manifest present."),
    V2(id="buildah-push-v2-0006", tool="buildah", operation="push",
       complexity="single",
       user_input="Push node-app:build-42 to docker.io under our org namespace.",
       args={"operation": "push", "image": "node-app:build-42"},
       answer="Pushed node-app:build-42\nDigest: sha256:11ccdd22eeff...\n201 MB transferred."),
    V2(id="buildah-push-v2-0007", tool="buildah", operation="push",
       complexity="single",
       user_input="get svc-base:9 pushed up before the maintenance window",
       args={"operation": "push", "image": "svc-base:9"},
       answer="Pushed svc-base:9\nDigest: sha256:22ddeeaabbcc...\n167 MB transferred."),
    V2(id="buildah-push-v2-0008", tool="buildah", operation="push",
       complexity="multi",
       user_input="Push base-hardened:1, then kick off the downstream image rebuilds that depend on it.",
       args={"operation": "push", "image": "base-hardened:1"},
       answer="Pushed base-hardened:1\nDigest: sha256:33ffeeaacc55...\n144 MB transferred."),
    V2(id="buildah-push-v2-0009", tool="buildah", operation="push",
       complexity="single",
       user_input="push pyservice:0.9",
       args={"operation": "push", "image": "pyservice:0.9"},
       answer="Pushed pyservice:0.9\nDigest: sha256:445566ccddee...\n176 MB transferred."),
    V2(id="buildah-push-v2-0010", tool="buildah", operation="push",
       complexity="diagnostic",
       user_input="Not sure the last push actually went through given the flaky wifi earlier — retry pushing build-check:tmp and check for a digest.",
       args={"operation": "push", "image": "build-check:tmp"},
       answer="Pushed build-check:tmp\nDigest: sha256:99aa11bb22cc33...\nTransfer completed, digest returned."),
    V2(id="buildah-push-v2-0011", tool="buildah", operation="push",
       complexity="single",
       user_input="Push the myapp:1.0 image to quay.io/myorg/myapp:1.0.",
       args={"operation": "push", "image": "myapp:1.0"},
       answer="Pushed myapp:1.0\nDigest: sha256:55667788ffaa...\n312 MB transferred."),

    V2(id="buildah-build-v2-0001", tool="buildah", operation="build",
       complexity="single",
       user_input="Build an image tagged myapp:2.0 from the Containerfile in the current directory.",
       args={"operation": "build", "tag": "myapp:2.0"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9/ubi\nSTEP 6/6: COMMIT myapp:2.0\nSuccessfully tagged myapp:2.0\nExit code 0."),
    V2(id="buildah-build-v2-0002", tool="buildah", operation="build",
       complexity="single",
       user_input="build the frontend image, tag it web:3.1, context is ./frontend",
       args={"operation": "build", "tag": "web:3.1", "context": "./frontend"},
       answer="STEP 1/4: FROM node:20-alpine\nSTEP 4/4: COMMIT web:3.1\nSuccessfully tagged web:3.1\nExit code 0."),
    V2(id="buildah-build-v2-0003", tool="buildah", operation="build",
       complexity="multi",
       user_input="Build api:1.4 from the Dockerfile in ./api and then push it once it's done.",
       args={"operation": "build", "tag": "api:1.4", "context": "./api"},
       answer="STEP 1/8: FROM registry.access.redhat.com/ubi9/ubi-minimal\nSTEP 8/8: COMMIT api:1.4\nSuccessfully tagged api:1.4\nExit code 0."),
    V2(id="buildah-build-v2-0004", tool="buildah", operation="build",
       complexity="single",
       user_input="run a buildah build for the worker service, tag worker:latest",
       args={"operation": "build", "tag": "worker:latest"},
       answer="STEP 1/5: FROM python:3.12-slim\nSTEP 5/5: COMMIT worker:latest\nSuccessfully tagged worker:latest\nExit code 0."),
    V2(id="buildah-build-v2-0005", tool="buildah", operation="build",
       complexity="diagnostic",
       user_input="The CI pipeline says the Containerfile build failed at some step — rebuild db-tools:1.0 from ./tools and show me what breaks.",
       args={"operation": "build", "tag": "db-tools:1.0", "context": "./tools"},
       answer="STEP 3/5: RUN dnf install -y postgresql\nerror: package postgresql not found in enabled repos\nExit code 1."),
    V2(id="buildah-build-v2-0006", tool="buildah", operation="build",
       complexity="single",
       user_input="build proxy:edge with context ./nginx-build",
       args={"operation": "build", "tag": "proxy:edge", "context": "./nginx-build"},
       answer="STEP 1/3: FROM nginx:1.25\nSTEP 3/3: COMMIT proxy:edge\nSuccessfully tagged proxy:edge\nExit code 0."),
    V2(id="buildah-build-v2-0007", tool="buildah", operation="build",
       complexity="single",
       user_input="Kick off a build for report-gen:0.2 using the Containerfile at repo root.",
       args={"operation": "build", "tag": "report-gen:0.2"},
       answer="STEP 1/7: FROM registry.access.redhat.com/ubi9/ubi\nSTEP 7/7: COMMIT report-gen:0.2\nSuccessfully tagged report-gen:0.2\nExit code 0."),
    V2(id="buildah-build-v2-0008", tool="buildah", operation="build",
       complexity="multi",
       user_input="Build cache-svc:1.1 from ./cache-service, run a quick container from it, and check that redis-cli responds.",
       args={"operation": "build", "tag": "cache-svc:1.1", "context": "./cache-service"},
       answer="STEP 1/4: FROM redis:7-alpine\nSTEP 4/4: COMMIT cache-svc:1.1\nSuccessfully tagged cache-svc:1.1\nExit code 0."),
    V2(id="buildah-build-v2-0009", tool="buildah", operation="build",
       complexity="single",
       user_input="tag it batch-job:nightly and build from the current dir",
       args={"operation": "build", "tag": "batch-job:nightly"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9/ubi-minimal\nSTEP 6/6: COMMIT batch-job:nightly\nSuccessfully tagged batch-job:nightly\nExit code 0."),
    V2(id="buildah-build-v2-0010", tool="buildah", operation="build",
       complexity="diagnostic",
       user_input="We think the last image tag never actually got built — rerun the build for auth-svc:1.0 from ./auth and confirm it tags successfully.",
       args={"operation": "build", "tag": "auth-svc:1.0", "context": "./auth"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9/ubi-minimal\nSTEP 6/6: COMMIT auth-svc:1.0\nSuccessfully tagged auth-svc:1.0\nExit code 0."),

    V2(id="buildah-rm-v2-0001", tool="buildah", operation="rm",
       complexity="single",
       user_input="Remove the working container named stale-working-container.",
       args={"operation": "rm", "container": "stale-working-container"},
       answer="Removed container: stale-working-container"),
    V2(id="buildah-rm-v2-0002", tool="buildah", operation="rm",
       complexity="single",
       user_input="clear out all the working containers on this build node",
       args={"operation": "rm", "all": True},
       answer="Removed 5 working containers.\nBuild store now empty of working containers."),
    V2(id="buildah-rm-v2-0003", tool="buildah", operation="rm",
       complexity="multi",
       user_input="Remove ubi-working-container and then rerun the build from scratch.",
       args={"operation": "rm", "container": "ubi-working-container"},
       answer="Removed container: ubi-working-container"),
    V2(id="buildah-rm-v2-0004", tool="buildah", operation="rm",
       complexity="single",
       user_input="the build for node-working-container is a dead end, get rid of it",
       args={"operation": "rm", "container": "node-working-container"},
       answer="Removed container: node-working-container"),
    V2(id="buildah-rm-v2-0005", tool="buildah", operation="rm",
       complexity="diagnostic",
       user_input="Disk usage on the build box looks high and there are leftover in-progress containers from failed jobs — can you clean all of those up?",
       args={"operation": "rm", "all": True},
       answer="Removed 9 working containers.\nReclaimed approximately 4.2 GB."),
    V2(id="buildah-rm-v2-0006", tool="buildah", operation="rm",
       complexity="single",
       user_input="delete the pg-working-container, the migration test is done",
       args={"operation": "rm", "container": "pg-working-container"},
       answer="Removed container: pg-working-container"),
    V2(id="buildah-rm-v2-0007", tool="buildah", operation="rm",
       complexity="single",
       user_input="Drop the web-working-container, we're not shipping that build.",
       args={"operation": "rm", "container": "web-working-container"},
       answer="Removed container: web-working-container"),
    V2(id="buildah-rm-v2-0008", tool="buildah", operation="rm",
       complexity="single",
       user_input="Wipe every working container on this host, we're resetting the build environment.",
       args={"operation": "rm", "all": True},
       answer="Removed 12 working containers.\nAll in-progress build state discarded."),
    V2(id="buildah-rm-v2-0009", tool="buildah", operation="rm",
       complexity="single",
       user_input="remove api-working-container please",
       args={"operation": "rm", "container": "api-working-container"},
       answer="Removed container: api-working-container"),
    V2(id="buildah-rm-v2-0010", tool="buildah", operation="rm",
       complexity="diagnostic",
       user_input="A failed job left an orphaned working container called build-tmp-9f2a — can you confirm it and remove it?",
       args={"operation": "rm", "container": "build-tmp-9f2a"},
       answer="Removed container: build-tmp-9f2a"),
    V2(id="buildah-rm-v2-0011", tool="buildah", operation="rm",
       complexity="single",
       user_input="Tear down rocky-working-container now that svc-base:9 is committed.",
       args={"operation": "rm", "container": "rocky-working-container"},
       answer="Removed container: rocky-working-container"),
]

from finetune.scenarios_v2 import check_module; check_module("buildah", SCENARIOS_V2)
