"""finetune/scenarios_v2/chrony.py — corpus v2 scenarios for 'chrony'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="chrony-tracking-v2-0001", tool="chrony", operation="tracking",
       complexity="single",
       user_input="Pull the clock tracking stats for db-primary-04, I need the offset in ms.",
       args={"operation": "tracking"},
       answer="Reference ID: 0A2A0101 (10.42.1.1)\nStratum: 2\nSystem time: 0.000412 seconds slow of NTP time\nLast offset: -0.000389 seconds\nRMS offset: 0.000512 seconds\nFrequency: 4.221 ppm slow\nRoot delay: 0.023481 seconds\nRoot dispersion: 0.001220 seconds"),
    V2(id="chrony-tracking-v2-0002", tool="chrony", operation="tracking",
       complexity="diagnostic",
       user_input="A batch job on report-worker-2 logged timestamps 3 seconds apart for events 1 second apart. Something's off with the clock.",
       args={"operation": "tracking"},
       answer="Reference ID: 7F000001 (127.127.1.0)\nStratum: 10\nSystem time: 2.913004 seconds fast of NTP time\nLast offset: 2.910112 seconds\nFrequency: 18.774 ppm fast\nLeap status: Not synchronised"),
    V2(id="chrony-tracking-v2-0003", tool="chrony", operation="tracking",
       complexity="single",
       user_input="what stratum is edge-gw-07 currently synced at",
       args={"operation": "tracking"},
       answer="Reference ID: C0A80101 (192.168.1.1)\nStratum: 3\nSystem time: 0.000098 seconds fast of NTP time\nRoot dispersion: 0.000891 seconds\nLeap status: Normal"),
    V2(id="chrony-tracking-v2-0004", tool="chrony", operation="tracking",
       complexity="single",
       user_input="Show root dispersion and root delay on the auth server before we debug a Kerberos clock-skew ticket.",
       args={"operation": "tracking"},
       answer="Reference ID: 0A000005 (10.0.0.5)\nStratum: 2\nRoot delay: 0.018220 seconds\nRoot dispersion: 0.000774 seconds\nLast offset: 0.000041 seconds\nLeap status: Normal"),
    V2(id="chrony-tracking-v2-0005", tool="chrony", operation="tracking",
       complexity="single",
       user_input="Is app-node-11 actually synchronized right now or just claiming to be?",
       args={"operation": "tracking"},
       answer="Reference ID: 0A2A0101 (10.42.1.1)\nStratum: 2\nLeap status: Normal\nSystem time: 0.000205 seconds slow of NTP time"),
    V2(id="chrony-tracking-v2-0006", tool="chrony", operation="tracking",
       complexity="single",
       user_input="Give me the frequency drift number for host build-runner-3, want to see if the oscillator is degrading.",
       args={"operation": "tracking"},
       answer="Frequency: 12.884 ppm slow\nResidual frequency: 0.031 ppm\nSkew: 0.842 ppm\nSystem time: 0.000317 seconds fast of NTP time"),
    V2(id="chrony-tracking-v2-0007", tool="chrony", operation="tracking",
       complexity="multi",
       user_input="Check the tracking output on log-collector-01 and then tell me if it needs a manual step.",
       args={"operation": "tracking"},
       answer="Reference ID: 0A000005 (10.0.0.5)\nStratum: 2\nLast offset: 1.482221 seconds\nSystem time: 1.480902 seconds fast of NTP time\nLeap status: Normal"),
    V2(id="chrony-tracking-v2-0008", tool="chrony", operation="tracking",
       complexity="diagnostic",
       user_input="TLS handshakes on payment-gw-2 are failing with certificate not yet valid errors, can you check the clock state there.",
       args={"operation": "tracking"},
       answer="Reference ID: 7F000001 (127.127.1.0)\nStratum: 10\nSystem time: 4.221390 seconds fast of NTP time\nLeap status: Not synchronised"),

    V2(id="chrony-sources-v2-0001", tool="chrony", operation="sources",
       complexity="single",
       user_input="List the configured time sources on relay-eu-3.",
       args={"operation": "sources"},
       answer="MS Name/IP address         Stratum Poll Reach LastRx Last sample\n^* time1.internal.corp           1   6   377    42   -389us\n^- time2.internal.corp           2   6   377    45  +1.2ms"),
    V2(id="chrony-sources-v2-0002", tool="chrony", operation="sources",
       complexity="single",
       user_input="which source does chrony currently trust as reference on jump-host-1",
       args={"operation": "sources"},
       answer="^* ntp.pool.internal              2   6   377    31   -212us  (selected)\n^- 10.4.0.9                       3   7   177    88   +3.4ms"),
    V2(id="chrony-sources-v2-0003", tool="chrony", operation="sources",
       complexity="diagnostic",
       user_input="Cron-triggered backups on file-srv-9 keep landing at odd offsets from schedule, and I suspect a drifting clock. Are all its NTP sources actually reachable?",
       args={"operation": "sources"},
       answer="MS Name/IP address         Stratum Poll Reach LastRx Last sample\n?  time1.internal.corp           0   6     0     -     -\n?  time2.internal.corp           0   6     0     -     -"),
    V2(id="chrony-sources-v2-0004", tool="chrony", operation="sources",
       complexity="single",
       user_input="Show me each source's stratum on mail-relay-4.",
       args={"operation": "sources"},
       answer="^* time1.internal.corp    stratum 1  reach 377\n^- 172.20.0.5              stratum 2  reach 357\n^? 172.20.0.9              stratum 0  reach 0"),
    V2(id="chrony-sources-v2-0005", tool="chrony", operation="sources",
       complexity="single",
       user_input="check for any source on cache-node-2 with a reach value of zero",
       args={"operation": "sources"},
       answer="^* time1.internal.corp    reach 377\n^? 10.9.0.4                reach 0\n1 of 2 sources unreachable"),
    V2(id="chrony-sources-v2-0006", tool="chrony", operation="sources",
       complexity="single",
       user_input="Confirm that pool.ntp.org entries are actually in use on legacy-vm-6, not some stale internal server.",
       args={"operation": "sources"},
       answer="^* 2.pool.ntp.org         stratum 2  reach 377  -820us\n^- 3.pool.ntp.org         stratum 2  reach 337  +1.1ms"),
    V2(id="chrony-sources-v2-0007", tool="chrony", operation="sources",
       complexity="diagnostic",
       user_input="A ticket mentions expired Kerberos tickets showing up early on dc-secondary. Pull the source list to see if sync is healthy.",
       args={"operation": "sources"},
       answer="^* time1.internal.corp    stratum 1  reach 377  -105us\n^- time2.internal.corp    stratum 2  reach 375  +288us"),
    V2(id="chrony-sources-v2-0008", tool="chrony", operation="sources",
       complexity="single",
       user_input="how many NTP sources is chrony tracking on staging-app-1 right now",
       args={"operation": "sources"},
       answer="3 sources configured\n^* time1.internal.corp  reach 377\n^- time2.internal.corp  reach 357\n^- time3.internal.corp  reach 177"),

    V2(id="chrony-status-v2-0001", tool="chrony", operation="status",
       complexity="single",
       user_input="Is chronyd alive on video-encode-3?",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Thu 2026-09-10 06:12:03 UTC; 2 days ago\nMain PID: 891 (chronyd)"),
    V2(id="chrony-status-v2-0002", tool="chrony", operation="status",
       complexity="single",
       user_input="show chronyd unit status on search-idx-7",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Mon 2026-09-08 11:00:44 UTC; 4 days ago\nMain PID: 512 (chronyd)"),
    V2(id="chrony-status-v2-0003", tool="chrony", operation="status",
       complexity="diagnostic",
       user_input="Something upstream reports NTP is down for the whole rack. Is chronyd even active on switch-mgmt-1?",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: failed (Result: exit-code) since Fri 2026-09-12 03:40:11 UTC; 5h ago\nProcess: 204 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=1/FAILURE)"),
    V2(id="chrony-status-v2-0004", tool="chrony", operation="status",
       complexity="multi",
       user_input="Check whether chronyd is up on billing-api-2 and if it is, pull the tracking output too.",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Wed 2026-09-11 22:03:19 UTC; 12h ago\nMain PID: 733 (chronyd)"),
    V2(id="chrony-status-v2-0005", tool="chrony", operation="status",
       complexity="single",
       user_input="how long has chronyd been running on report-worker-2",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Sat 2026-08-30 00:15:02 UTC; 1 week 5 days ago\nMain PID: 349 (chronyd)"),
    V2(id="chrony-status-v2-0006", tool="chrony", operation="status",
       complexity="diagnostic",
       user_input="Cron jobs on batch-node-5 are firing minutes off schedule. Check if the time daemon is even running before we look at cron itself.",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: inactive (dead)\nCondition: start condition failed"),
    V2(id="chrony-status-v2-0007", tool="chrony", operation="status",
       complexity="single",
       user_input="Verify NTP daemon health on lb-prod-1 before we start the maintenance window.",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Tue 2026-09-01 10:00:00 UTC; 11 days ago\nMain PID: 660 (chronyd)"),
    V2(id="chrony-status-v2-0008", tool="chrony", operation="status",
       complexity="single",
       user_input="pull the systemd status line for chronyd on dns-secondary-2",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Sun 2026-09-07 09:44:31 UTC; 5 days ago\nMain PID: 1023 (chronyd)"),
    V2(id="chrony-status-v2-0009", tool="chrony", operation="status",
       complexity="single",
       user_input="Confirm chronyd hasn't crashed on the ingest pipeline host, ingest-3.",
       args={"operation": "status"},
       answer="chronyd.service - NTP client/server\nActive: active (running) since Thu 2026-09-12 01:20:07 UTC; 8h ago\nMain PID: 442 (chronyd)"),

    V2(id="chrony-makestep-v2-0001", tool="chrony", operation="makestep",
       complexity="single",
       user_input="Force an immediate clock sync on restore-vm-9, we just resumed it from a snapshot.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by -4.812203 seconds"),
    V2(id="chrony-makestep-v2-0002", tool="chrony", operation="makestep",
       complexity="single",
       user_input="Step the clock on gateway-eu-2 to the reference right now, don't wait for gradual slew.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by +1.940110 seconds"),
    V2(id="chrony-makestep-v2-0003", tool="chrony", operation="makestep",
       complexity="single",
       user_input="etcd-node-2 is 6 minutes off after being paused, fix the clock now.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by -360.221004 seconds"),
    V2(id="chrony-makestep-v2-0004", tool="chrony", operation="makestep",
       complexity="multi",
       user_input="Step the clock on worker-14 and then re-check tracking to confirm the offset is small.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by -2.104881 seconds"),
    V2(id="chrony-makestep-v2-0005", tool="chrony", operation="makestep",
       complexity="single",
       user_input="Synchronize clock on media-transcode-1 immediately, downstream jobs cannot wait for gradual correction.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by +0.884213 seconds"),
    V2(id="chrony-makestep-v2-0006", tool="chrony", operation="makestep",
       complexity="diagnostic",
       user_input="Kerberos auth on ad-bridge-3 is failing because its clock is 4 minutes ahead. Step it.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by -241.003920 seconds"),
    V2(id="chrony-makestep-v2-0007", tool="chrony", operation="makestep",
       complexity="single",
       user_input="run the equivalent of chronyc makestep on vpn-concentrator-1",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by +0.032881 seconds"),
    V2(id="chrony-makestep-v2-0008", tool="chrony", operation="makestep",
       complexity="multi",
       user_input="Check the offset on ci-runner-8 first, and if it's over a second go ahead and step the clock.",
       args={"operation": "makestep"},
       answer="200 OK\nClock stepped by +1.331904 seconds"),

    V2(id="chrony-conf_view-v2-0001", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="Show me /etc/chrony.conf on staging-db-1.",
       args={"operation": "conf_view"},
       answer="pool time1.internal.corp iburst\npool time2.internal.corp iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nrtcsync"),
    V2(id="chrony-conf_view-v2-0002", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="what NTP pool addresses are set in chrony.conf on relay-us-1",
       args={"operation": "conf_view"},
       answer="pool 0.pool.ntp.org iburst\npool 1.pool.ntp.org iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3"),
    V2(id="chrony-conf_view-v2-0003", tool="chrony", operation="conf_view",
       complexity="diagnostic",
       user_input="app-node-22 isn't syncing at all. Show the config so I can check the server list.",
       args={"operation": "conf_view"},
       answer="server 10.0.0.99 iburst\ndriftfile /var/lib/chrony/drift\n# rtcsync disabled\nlogdir /var/log/chrony"),
    V2(id="chrony-conf_view-v2-0004", tool="chrony", operation="conf_view",
       complexity="multi",
       user_input="Read the chrony config on legacy-host-4 and tell me if makestep is enabled.",
       args={"operation": "conf_view"},
       answer="pool time1.internal.corp iburst\ndriftfile /var/lib/chrony/drift\nrtcsync\n# makestep not configured"),
    V2(id="chrony-conf_view-v2-0005", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="cat out the chrony.conf on bastion-2",
       args={"operation": "conf_view"},
       answer="server 10.0.0.5 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nallow 10.0.0.0/24"),
    V2(id="chrony-conf_view-v2-0006", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="The pool address for cache-node-9 changed upstream, show the current chrony.conf before we touch it.",
       args={"operation": "conf_view"},
       answer="pool 2.pool.ntp.org iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nrtcsync"),
    V2(id="chrony-conf_view-v2-0007", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="pull the full contents of the chrony configuration file on dns-primary-1",
       args={"operation": "conf_view"},
       answer="pool time1.internal.corp iburst\npool time2.internal.corp iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nlogdir /var/log/chrony"),
    V2(id="chrony-conf_view-v2-0008", tool="chrony", operation="conf_view",
       complexity="diagnostic",
       user_input="Time on jenkins-runner-3 has been drifting all week, can you show me chrony.conf so I can look for a bad server entry?",
       args={"operation": "conf_view"},
       answer="server 172.16.0.1 iburst\ndriftfile /var/lib/chrony/drift\n# makestep not configured\n# rtcsync disabled"),
    V2(id="chrony-conf_view-v2-0009", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="display the NTP server list configured for imap-node-6",
       args={"operation": "conf_view"},
       answer="pool time1.internal.corp iburst\npool time2.internal.corp iburst\nallow 192.168.0.0/16"),
    V2(id="chrony-conf_view-v2-0010", tool="chrony", operation="conf_view",
       complexity="single",
       user_input="Before we swap NTP providers, show what redis-node-3 is configured to use today.",
       args={"operation": "conf_view"},
       answer="server 10.0.0.5 iburst\nserver 10.0.0.6 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3"),

    V2(id="chrony-conf_edit-v2-0001", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Point chrony.conf on db-node-3 at our internal NTP server 10.0.0.20 instead of the public pool.",
       args={"operation": "conf_edit", "content": "server 10.0.0.20 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nrtcsync\n"},
       answer="Wrote /etc/chrony.conf (4 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0002", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Add iburst to the NTP server line for host proxy-2's chrony.conf.",
       args={"operation": "conf_edit", "content": "server 10.0.0.5 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0003", tool="chrony", operation="conf_edit",
       complexity="multi",
       user_input="View the current chrony config on smtp-relay-1 then replace the public pool with our private NTP server 10.4.0.9.",
       args={"operation": "conf_edit", "content": "server 10.4.0.9 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0004", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Configure chrony on monitor-hub-1 to let the local subnet 10.9.0.0/24 query NTP.",
       args={"operation": "conf_edit", "content": "pool time1.internal.corp iburst\ndriftfile /var/lib/chrony/drift\nallow 10.9.0.0/24\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0005", tool="chrony", operation="conf_edit",
       complexity="diagnostic",
       user_input="warehouse-db-2 drifts overnight and needs a tighter step threshold. Update its chrony.conf accordingly.",
       args={"operation": "conf_edit", "content": "pool time1.internal.corp iburst\ndriftfile /var/lib/chrony/drift\nmakestep 0.1 -1\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0006", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Enable Network Time Security for the upstream server in chrony.conf on edge-proxy-9.",
       args={"operation": "conf_edit", "content": "server nts.internal.corp iburst nts\ndriftfile /var/lib/chrony/drift\n"},
       answer="Wrote /etc/chrony.conf (2 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0007", tool="chrony", operation="conf_edit",
       complexity="multi",
       user_input="Set chrony on api-gw-4 to use the datacenter NTP server 10.1.0.1, then restart chronyd to apply it.",
       args={"operation": "conf_edit", "content": "server 10.1.0.1 iburst\ndriftfile /var/lib/chrony/drift\nmakestep 1.0 3\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0008", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Rewrite the chrony config for build-farm-2 with two internal servers, 10.2.0.1 and 10.2.0.2, both iburst.",
       args={"operation": "conf_edit", "content": "server 10.2.0.1 iburst\nserver 10.2.0.2 iburst\ndriftfile /var/lib/chrony/drift\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
    V2(id="chrony-conf_edit-v2-0009", tool="chrony", operation="conf_edit",
       complexity="single",
       user_input="Change the drift file location for chrony on host archive-node-5 to /var/lib/chrony/drift2.",
       args={"operation": "conf_edit", "content": "pool time1.internal.corp iburst\ndriftfile /var/lib/chrony/drift2\nmakestep 1.0 3\n"},
       answer="Wrote /etc/chrony.conf (3 lines)\nRestart chronyd to apply"),
]

from finetune.scenarios_v2 import check_module; check_module("chrony", SCENARIOS_V2)
