"""finetune/scenarios_v2/cron.py — corpus v2 scenarios for 'cron'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="cron-list-v2-0001", tool="cron", operation="list",
       complexity="single",
       user_input="Pull up the crontab for the 'svc-etl' account.",
       args={"user": "svc-etl", "operation": "list"},
       answer="no crontab for user svc-etl"),
    V2(id="cron-list-v2-0002", tool="cron", operation="list",
       complexity="diagnostic",
       user_input="The nightly ETL job seems to have stopped firing \u2014 is there still an entry for it in root's crontab?",
       args={"user": "root", "operation": "list"},
       answer="0 1 * * * /opt/etl/run_nightly.sh\n1 job scheduled"),
    V2(id="cron-list-v2-0003", tool="cron", operation="list",
       complexity="single",
       user_input="What's currently in my crontab?",
       args={"operation": "list"},
       answer="no crontab for aaron"),
    V2(id="cron-list-v2-0004", tool="cron", operation="list",
       complexity="multi",
       user_input="Check the 'jenkins' user's crontab and then tell me if a build-cleanup entry exists.",
       args={"user": "jenkins", "operation": "list"},
       answer="0 3 * * * /opt/jenkins/cleanup.sh\n1 job scheduled"),
    V2(id="cron-list-v2-0005", tool="cron", operation="list",
       complexity="diagnostic",
       user_input="Disk usage alerts fired overnight but nobody remembers scheduling a cleanup \u2014 does the 'ops' user have anything set up?",
       args={"user": "ops", "operation": "list"},
       answer="no crontab for ops"),
    V2(id="cron-list-v2-0006", tool="cron", operation="list",
       complexity="single",
       user_input="Show the scheduled entries for user 'reportgen'.",
       args={"user": "reportgen", "operation": "list"},
       answer="*/15 * * * * /usr/local/bin/gen_report.sh\n1 job scheduled"),
    V2(id="cron-list-all-v2-0007", tool="cron", operation="list-all",
       complexity="single",
       user_input="Give me every user crontab file present on this box.",
       args={"operation": "list-all"},
       answer="aaron  ops  postgres  reportgen\n4 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0008", tool="cron", operation="list-all",
       complexity="diagnostic",
       user_input="A job keeps firing at odd hours and load spikes \u2014 which accounts even have crontabs on this host?",
       args={"operation": "list-all"},
       answer="jenkins  ops  svc-etl\n3 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0009", tool="cron", operation="list-all",
       complexity="single",
       user_input="List every crontab currently installed on the system.",
       args={"operation": "list-all"},
       answer="root  aaron  backup\n3 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0010", tool="cron", operation="list-all",
       complexity="multi",
       user_input="Enumerate all user crontabs and then flag any account we don't recognize as a service account.",
       args={"operation": "list-all"},
       answer="backup  guestuser  ops\n3 crontab files in /var/spool/cron/\nunexpected: guestuser"),
    V2(id="cron-list-all-v2-0011", tool="cron", operation="list-all",
       complexity="diagnostic",
       user_input="We're doing a scheduled-task audit ahead of the SOC2 review \u2014 who has a crontab on this server?",
       args={"operation": "list-all"},
       answer="postgres  reportgen  root\n3 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0012", tool="cron", operation="list-all",
       complexity="single",
       user_input="Show the full directory listing of /var/spool/cron/.",
       args={"operation": "list-all"},
       answer="jenkins  ops  svc-etl  www-data\n4 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0013", tool="cron", operation="list-all",
       complexity="diagnostic",
       user_input="Something is writing to /tmp every minute and filling the disk \u2014 which users have scheduled jobs at all?",
       args={"operation": "list-all"},
       answer="guestuser  ops\n2 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0014", tool="cron", operation="list-all",
       complexity="single",
       user_input="Which accounts on this machine have their own crontab?",
       args={"operation": "list-all"},
       answer="aaron  backup  postgres\n3 crontab files in /var/spool/cron/"),
    V2(id="cron-list-all-v2-0015", tool="cron", operation="list-all",
       complexity="multi",
       user_input="List all crontab files and then check whether the decommissioned 'legacy-user' account still has one.",
       args={"operation": "list-all"},
       answer="backup  ops  postgres\n3 crontab files in /var/spool/cron/\nlegacy-user: not present"),
    V2(id="cron-edit-v2-0016", tool="cron", operation="edit",
       complexity="single",
       user_input="Install this crontab for the 'backup' user: run /opt/backup/run.sh every day at 1am.",
       args={"content": "0 1 * * * /opt/backup/run.sh\n", "user": "backup", "operation": "edit"},
       answer="crontab for backup installed\n1 entry"),
    V2(id="cron-edit-v2-0017", tool="cron", operation="edit",
       complexity="diagnostic",
       user_input="The hourly disk-space check on root never runs anymore \u2014 rewrite root's crontab to add it back at the top of every hour.",
       args={"content": "0 * * * * /usr/local/bin/check_disk.sh\n", "user": "root", "operation": "edit"},
       answer="crontab for root installed\n1 entry"),
    V2(id="cron-edit-v2-0018", tool="cron", operation="edit",
       complexity="single",
       user_input="Set my crontab to run a vacuum on the reports database every Sunday at 4am.",
       args={"content": "0 4 * * 0 /usr/local/bin/vacuum_reports.sh\n", "operation": "edit"},
       answer="crontab for aaron installed\n1 entry"),
    V2(id="cron-edit-v2-0019", tool="cron", operation="edit",
       complexity="multi",
       user_input="Replace the 'svc-etl' crontab with a job that syncs the warehouse every 10 minutes, then confirm it took.",
       args={"content": "*/10 * * * * /opt/etl/sync_warehouse.sh\n", "user": "svc-etl", "operation": "edit"},
       answer="crontab for svc-etl installed\n1 entry"),
    V2(id="cron-edit-v2-0020", tool="cron", operation="edit",
       complexity="diagnostic",
       user_input="Certificate renewal keeps missing its window \u2014 fix the 'certbot' user's crontab so renewal runs on the 1st of each month at 3am.",
       args={"content": "0 3 1 * * /usr/bin/certbot renew --quiet\n", "user": "certbot", "operation": "edit"},
       answer="crontab for certbot installed\n1 entry"),
    V2(id="cron-edit-v2-0021", tool="cron", operation="edit",
       complexity="single",
       user_input="Write a crontab for 'monitoring' that pings the uptime endpoint every 5 minutes.",
       args={"content": "*/5 * * * * /usr/local/bin/uptime_ping.sh\n", "user": "monitoring", "operation": "edit"},
       answer="crontab for monitoring installed\n1 entry"),
    V2(id="cron-edit-v2-0022", tool="cron", operation="edit",
       complexity="diagnostic",
       user_input="Nightly log compression stopped after last week's account cleanup \u2014 reinstall the 'logs' user's crontab with the compression job at 11pm.",
       args={"content": "0 23 * * * /usr/local/bin/compress_logs.sh\n", "user": "logs", "operation": "edit"},
       answer="crontab for logs installed\n1 entry"),
    V2(id="cron-remove-v2-0023", tool="cron", operation="remove",
       complexity="single",
       user_input="Wipe out the entire crontab for the 'tempuser' account.",
       args={"user": "tempuser", "operation": "remove"},
       answer="crontab for tempuser removed"),
    V2(id="cron-remove-v2-0024", tool="cron", operation="remove",
       complexity="diagnostic",
       user_input="We keep seeing stray jobs fire from the 'oldsvc' account that nobody owns anymore \u2014 clear its crontab entirely.",
       args={"user": "oldsvc", "operation": "remove"},
       answer="crontab for oldsvc removed"),
    V2(id="cron-remove-v2-0025", tool="cron", operation="remove",
       complexity="single",
       user_input="Clear my own crontab completely.",
       args={"operation": "remove"},
       answer="crontab for aaron removed"),
    V2(id="cron-remove-v2-0026", tool="cron", operation="remove",
       complexity="multi",
       user_input="Remove the 'staging' user's crontab and then confirm no crontab files remain for it.",
       args={"user": "staging", "operation": "remove"},
       answer="crontab for staging removed\nno crontab for staging"),
    V2(id="cron-remove-v2-0027", tool="cron", operation="remove",
       complexity="single",
       user_input="Delete every scheduled job the 'legacy-user' has.",
       args={"user": "legacy-user", "operation": "remove"},
       answer="crontab for legacy-user removed"),
    V2(id="cron-remove-v2-0028", tool="cron", operation="remove",
       complexity="diagnostic",
       user_input="Duplicate reminder emails are going out \u2014 I suspect two overlapping jobs on the 'notify' account, so just wipe its crontab and I'll reinstall clean.",
       args={"user": "notify", "operation": "remove"},
       answer="crontab for notify removed"),
    V2(id="cron-remove-v2-0029", tool="cron", operation="remove",
       complexity="single",
       user_input="Erase root's crontab.",
       args={"user": "root", "operation": "remove"},
       answer="crontab for root removed"),
    V2(id="cron-remove-v2-0030", tool="cron", operation="remove",
       complexity="diagnostic",
       user_input="The 'batchproc' account is decommissioned but its cron jobs are still hammering the database \u2014 remove its crontab now.",
       args={"user": "batchproc", "operation": "remove"},
       answer="crontab for batchproc removed"),
    V2(id="cron-crond-view-v2-0031", tool="cron", operation="crond-view",
       complexity="single",
       user_input="Show me what's inside /etc/cron.d/nightly-sync.",
       args={"name": "nightly-sync", "operation": "crond-view"},
       answer="0 2 * * * root /opt/sync/nightly.sh"),
    V2(id="cron-crond-view-v2-0032", tool="cron", operation="crond-view",
       complexity="diagnostic",
       user_input="Backups didn't run last night \u2014 check the /etc/cron.d/backup-jobs file for what's actually scheduled.",
       args={"name": "backup-jobs", "operation": "crond-view"},
       answer="0 1 * * * root /opt/backup/run.sh\n30 1 * * * root /opt/backup/verify.sh"),
    V2(id="cron-crond-view-v2-0033", tool="cron", operation="crond-view",
       complexity="single",
       user_input="List what's in the /etc/cron.d/ directory.",
       args={"operation": "crond-view"},
       answer="0hourly  aide  logrotate  sysstat"),
    V2(id="cron-crond-view-v2-0034", tool="cron", operation="crond-view",
       complexity="multi",
       user_input="List /etc/cron.d/ and then show me the contents of the sysstat entry.",
       args={"name": "sysstat", "operation": "crond-view"},
       answer="*/10 * * * * root /usr/lib64/sa/sa1 1 1"),
    V2(id="cron-crond-view-v2-0035", tool="cron", operation="crond-view",
       complexity="diagnostic",
       user_input="The intrusion-detection scan never seems to fire \u2014 check whether /etc/cron.d/aide even has an entry.",
       args={"name": "aide", "operation": "crond-view"},
       answer="30 5 * * * root /usr/sbin/aide --check"),
    V2(id="cron-crond-view-v2-0036", tool="cron", operation="crond-view",
       complexity="single",
       user_input="Read the metrics-collect drop-in file under /etc/cron.d/.",
       args={"name": "metrics-collect", "operation": "crond-view"},
       answer="*/5 * * * * root /usr/local/bin/collect_metrics.sh"),
    V2(id="cron-crond-view-v2-0037", tool="cron", operation="crond-view",
       complexity="diagnostic",
       user_input="Certbot's automated renewal is overdue \u2014 is there even a cron.d entry for it?",
       args={"name": "certbot-renew", "operation": "crond-view"},
       answer="cat: /etc/cron.d/certbot-renew: No such file or directory"),
    V2(id="cron-crond-add-v2-0038", tool="cron", operation="crond-add",
       complexity="single",
       user_input="Create a cron.d file called disk-check that runs the disk monitor every 30 minutes as root.",
       args={"name": "disk-check", "content": "*/30 * * * * root /usr/local/bin/disk_monitor.sh\n", "operation": "crond-add"},
       answer="/etc/cron.d/disk-check written\n1 entry"),
    V2(id="cron-crond-add-v2-0039", tool="cron", operation="crond-add",
       complexity="diagnostic",
       user_input="Log rotation quietly stopped because someone deleted the drop-in \u2014 recreate /etc/cron.d/logrotate-custom to run rotation nightly at 11:30pm.",
       args={"name": "logrotate-custom", "content": "30 23 * * * root /usr/sbin/logrotate /etc/logrotate.d/custom\n", "operation": "crond-add"},
       answer="/etc/cron.d/logrotate-custom written\n1 entry"),
    V2(id="cron-crond-add-v2-0040", tool="cron", operation="crond-add",
       complexity="single",
       user_input="Add a metrics-export cron.d entry that fires every 5 minutes.",
       args={"name": "metrics-export", "content": "*/5 * * * * root /usr/local/bin/export_metrics.sh\n", "operation": "crond-add"},
       answer="/etc/cron.d/metrics-export written\n1 entry"),
    V2(id="cron-crond-add-v2-0041", tool="cron", operation="crond-add",
       complexity="multi",
       user_input="Install a db-vacuum drop-in for Sundays at 2am, then show me /etc/cron.d/ so I can confirm it landed.",
       args={"name": "db-vacuum", "content": "0 2 * * 0 postgres /usr/local/bin/vacuumdb_all.sh\n", "operation": "crond-add"},
       answer="/etc/cron.d/db-vacuum written\n1 entry"),
    V2(id="cron-crond-add-v2-0042", tool="cron", operation="crond-add",
       complexity="diagnostic",
       user_input="The nightly cert renewal drop-in is missing after the config rollback \u2014 write it back to run daily at 4am.",
       args={"name": "cert-renew", "content": "0 4 * * * root /usr/bin/certbot renew --quiet\n", "operation": "crond-add"},
       answer="/etc/cron.d/cert-renew written\n1 entry"),
    V2(id="cron-crond-add-v2-0043", tool="cron", operation="crond-add",
       complexity="single",
       user_input="Deploy a healthcheck cron.d file that pings the app every minute.",
       args={"name": "healthcheck", "content": "* * * * * root /usr/local/bin/ping_app.sh\n", "operation": "crond-add"},
       answer="/etc/cron.d/healthcheck written\n1 entry"),
    V2(id="cron-crond-add-v2-0044", tool="cron", operation="crond-add",
       complexity="diagnostic",
       user_input="The weekly report never generates and I can't find the schedule anywhere \u2014 add a report-weekly drop-in for Mondays at 6am.",
       args={"name": "report-weekly", "content": "0 6 * * 1 root /usr/local/bin/gen_weekly_report.sh\n", "operation": "crond-add"},
       answer="/etc/cron.d/report-weekly written\n1 entry"),
]

from finetune.scenarios_v2 import check_module; check_module("cron", SCENARIOS_V2)
