"""finetune/scenarios_v2/crypto_policies.py — corpus v2 scenarios for 'crypto_policies'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="crypto_policies-get-v2-0001", tool="crypto_policies", operation="get",
       complexity="single",
       user_input="Which cryptographic policy is active on db02 right now?",
       args={"operation": "get"},
       answer="Current policy: DEFAULT\nNo pending changes."),
    V2(id="crypto_policies-get-v2-0002", tool="crypto_policies", operation="get",
       complexity="diagnostic",
       user_input="A vendor scanner just flagged weak TLS 1.1 handshakes on edge03 — what's driving that?",
       args={"operation": "get"},
       answer="Current policy: LEGACY\nLEGACY permits TLS 1.1 and 3DES; switch to DEFAULT or FUTURE to close this."),
    V2(id="crypto_policies-get-v2-0003", tool="crypto_policies", operation="get",
       complexity="single",
       user_input="Print the crypto-policies state for host web07.",
       args={"operation": "get"},
       answer="Current policy: FUTURE\nApplied at boot, no override file present."),
    V2(id="crypto_policies-get-v2-0004", tool="crypto_policies", operation="get",
       complexity="multi",
       user_input="Check what crypto policy app-worker4 is on, then we'll decide if it needs to move to FUTURE.",
       args={"operation": "get"},
       answer="Current policy: DEFAULT\nEligible to switch to FUTURE without known compatibility issues."),
    V2(id="crypto_policies-get-v2-0005", tool="crypto_policies", operation="get",
       complexity="diagnostic",
       user_input="An sshd client is rejecting host key exchange on jump01 — is this a policy restriction?",
       args={"operation": "get"},
       answer="Current policy: FIPS\nFIPS excludes several legacy KEX algorithms; that matches the client error."),
    V2(id="crypto_policies-get-v2-0006", tool="crypto_policies", operation="get",
       complexity="single",
       user_input="What does update-crypto-policies --show report for this box?",
       args={"operation": "get"},
       answer="Current policy: DEFAULT:NO-SHA1\nCustom subpolicy layered on DEFAULT."),
    V2(id="crypto_policies-list-v2-0001", tool="crypto_policies", operation="list",
       complexity="single",
       user_input="What are the valid crypto policy names I could set here?",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-list-v2-0002", tool="crypto_policies", operation="list",
       complexity="multi",
       user_input="List the crypto policy options, then I'll pick one to apply on batch-node9.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-list-v2-0003", tool="crypto_policies", operation="list",
       complexity="single",
       user_input="Enumerate every supported crypto-policies profile.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-list-v2-0004", tool="crypto_policies", operation="list",
       complexity="diagnostic",
       user_input="A build script references a policy called STRICT — does that even exist on this system?",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT\nSTRICT is not a valid policy name here."),
    V2(id="crypto_policies-list-v2-0005", tool="crypto_policies", operation="list",
       complexity="single",
       user_input="Show all named policies available on report-gen1.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-list-v2-0006", tool="crypto_policies", operation="list",
       complexity="single",
       user_input="Give me the full set of crypto policy choices for this Rocky host.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-list-v2-0007", tool="crypto_policies", operation="list",
       complexity="multi",
       user_input="List the available policies, then check whether FUTURE is among them before I apply it.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT\nFUTURE is present."),
    V2(id="crypto_policies-list-v2-0008", tool="crypto_policies", operation="list",
       complexity="diagnostic",
       user_input="Nothing about crypto config looks broken, but confirm what profiles this host can even be set to.",
       args={"operation": "list"},
       answer="Available: DEFAULT, LEGACY, FUTURE, FIPS\nSubpolicies: NO-SHA1, NO-CAMELLIA, AD-SUPPORT"),
    V2(id="crypto_policies-set-v2-0001", tool="crypto_policies", operation="set",
       complexity="single",
       user_input="Apply the FUTURE crypto policy on cache03.",
       args={"operation": "set", "policy": "FUTURE"},
       answer="Policy set to FUTURE.\nRestart affected services (sshd, httpd) to pick up the change."),
    V2(id="crypto_policies-set-v2-0002", tool="crypto_policies", operation="set",
       complexity="multi",
       user_input="A pen-test report wants old ciphers dropped — switch this host to FUTURE and then restart sshd.",
       args={"operation": "set", "policy": "FUTURE"},
       answer="Policy set to FUTURE.\nRestart affected services (sshd, httpd) to pick up the change."),
    V2(id="crypto_policies-set-v2-0003", tool="crypto_policies", operation="set",
       complexity="single",
       user_input="Set the crypto policy on legacy-app2 to LEGACY so the old client can still connect.",
       args={"operation": "set", "policy": "LEGACY"},
       answer="Policy set to LEGACY.\nWarning: LEGACY permits weak ciphers, treat as temporary."),
    V2(id="crypto_policies-set-v2-0004", tool="crypto_policies", operation="set",
       complexity="single",
       user_input="Apply DEFAULT:NO-SHA1 as the system-wide policy on auth-srv1.",
       args={"operation": "set", "policy": "DEFAULT:NO-SHA1"},
       answer="Policy set to DEFAULT:NO-SHA1.\nRestart affected services to pick up the change."),
    V2(id="crypto_policies-fips-status-v2-0001", tool="crypto_policies", operation="fips-status",
       complexity="single",
       user_input="Is FIPS 140 mode turned on for this node?",
       args={"operation": "fips-status"},
       answer="FIPS mode: disabled."),
    V2(id="crypto_policies-fips-status-v2-0002", tool="crypto_policies", operation="fips-status",
       complexity="diagnostic",
       user_input="Our OpenSSL library is throwing a FIPS-required error on node crypto-gw2 but I'm not sure the mode is even set — check it.",
       args={"operation": "fips-status"},
       answer="FIPS mode: disabled.\nThat mismatch explains the library error; enable FIPS mode to resolve it."),
    V2(id="crypto_policies-fips-status-v2-0003", tool="crypto_policies", operation="fips-status",
       complexity="single",
       user_input="Confirm FIPS status on gov-cluster-node1.",
       args={"operation": "fips-status"},
       answer="FIPS mode: enabled."),
    V2(id="crypto_policies-fips-status-v2-0004", tool="crypto_policies", operation="fips-status",
       complexity="diagnostic",
       user_input="The auditor claims this box was never hardened to FIPS — verify one way or the other before the review.",
       args={"operation": "fips-status"},
       answer="FIPS mode: enabled.\nCrypto policy: FIPS. Auditor's claim does not match current state."),
    V2(id="crypto_policies-fips-status-v2-0005", tool="crypto_policies", operation="fips-status",
       complexity="single",
       user_input="Run fips-mode-setup --check on secure-vm3 and tell me the result.",
       args={"operation": "fips-status"},
       answer="FIPS mode: disabled."),
    V2(id="crypto_policies-fips-status-v2-0006", tool="crypto_policies", operation="fips-status",
       complexity="multi",
       user_input="Check FIPS status on hsm-proxy1, and if it's off we'll need to schedule enabling it.",
       args={"operation": "fips-status"},
       answer="FIPS mode: disabled.\nEnabling requires a reboot afterward — schedule a maintenance window."),
    V2(id="crypto_policies-fips-enable-v2-0001", tool="crypto_policies", operation="fips-enable",
       complexity="single",
       user_input="Turn on FIPS 140 mode for gov-cluster-node2.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect."),
    V2(id="crypto_policies-fips-enable-v2-0002", tool="crypto_policies", operation="fips-enable",
       complexity="multi",
       user_input="The compliance checklist requires FIPS on classified-vm5 — enable it and plan the reboot window.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect; schedule the window."),
    V2(id="crypto_policies-fips-enable-v2-0003", tool="crypto_policies", operation="fips-enable",
       complexity="single",
       user_input="Run fips-mode-setup --enable on hsm-proxy1.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect."),
    V2(id="crypto_policies-fips-enable-v2-0004", tool="crypto_policies", operation="fips-enable",
       complexity="single",
       user_input="Put crypto-gw2 into FIPS 140-2 mode.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect."),
    V2(id="crypto_policies-fips-enable-v2-0005", tool="crypto_policies", operation="fips-enable",
       complexity="diagnostic",
       user_input="Security review flagged secure-vm3 as missing FIPS — remediate that now.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect."),
    V2(id="crypto_policies-fips-enable-v2-0006", tool="crypto_policies", operation="fips-enable",
       complexity="multi",
       user_input="If FIPS isn't already on for auth-srv1, enable it and note that a reboot follows.",
       args={"operation": "fips-enable"},
       answer="FIPS mode enabled.\nReboot required before it takes effect."),
]

from finetune.scenarios_v2 import check_module; check_module("crypto_policies", SCENARIOS_V2)
