"""finetune/scenarios_v2/disk.py — corpus v2 scenarios for 'disk'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="disk-usage-v2-0001", tool="disk", operation="usage",
       complexity="single",
       user_input="What's the free space situation on /srv/backups right now?",
       args={"operation": "usage", "path": "/srv/backups"},
       answer="/dev/mapper/vg_data-backups 2.0T 1.6T 400G 81% /srv/backups"),
    V2(id="disk-usage-v2-0002", tool="disk", operation="usage",
       complexity="diagnostic",
       user_input="The nightly job on db02 keeps failing with ENOSPC. Can you tell why?",
       args={"operation": "usage", "path": "/var/lib/pgsql"},
       answer="/dev/nvme1n1p1 500G 498G 1.2G 100% /var/lib/pgsql"),
    V2(id="disk-usage-v2-0003", tool="disk", operation="usage",
       complexity="single",
       user_input="check space on root",
       args={"operation": "usage", "path": "/"},
       answer="/dev/sda2 100G 42G 58G 42% /"),
    V2(id="disk-usage-v2-0004", tool="disk", operation="usage",
       complexity="multi",
       user_input="Check usage on /home first, then if it's tight I'll ask you to clean up old logs.",
       args={"operation": "usage", "path": "/home"},
       answer="/dev/sdb1 200G 190G 10G 95% /home"),
    V2(id="disk-usage-v2-0005", tool="disk", operation="usage",
       complexity="diagnostic",
       user_input="Ticket 4521: user reports 'no space left on device' errors writing to their project dir under /export. Investigate.",
       args={"operation": "usage", "path": "/export"},
       answer="/dev/mapper/vg_export-lv0 4.0T 4.0T 0 100% /export"),
    V2(id="disk-usage-v2-0006", tool="disk", operation="usage",
       complexity="single",
       user_input="Give me a full filesystem usage report across the host.",
       args={"operation": "usage"},
       answer="/ 100G 42G 58G 42%\n/boot 1G 300M 700M 30%\n/var 300G 210G 90G 70%\n/home 200G 190G 10G 95%"),
    V2(id="disk-list-v2-0001", tool="disk", operation="list",
       complexity="single",
       user_input="Show me the partition layout for /dev/nvme0n1.",
       args={"operation": "list", "device": "/dev/nvme0n1"},
       answer="nvme0n1 953.9G disk\n  nvme0n1p1 1G part /boot\n  nvme0n1p2 952.9G part /"),
    V2(id="disk-list-v2-0002", tool="disk", operation="list",
       complexity="single",
       user_input="list all block devices on this box",
       args={"operation": "list"},
       answer="sda 500G disk\n  sda1 500G part /\nnvme0n1 953.9G disk\n  nvme0n1p1 953.9G part /data"),
    V2(id="disk-list-v2-0003", tool="disk", operation="list",
       complexity="diagnostic",
       user_input="I plugged in a new drive but can't find it anywhere — what does the block device table look like?",
       args={"operation": "list"},
       answer="sda 500G disk\n  sda1 500G part /\nsdb 2T disk\nnvme0n1 953.9G disk\n  nvme0n1p1 953.9G part /data"),
    V2(id="disk-list-v2-0004", tool="disk", operation="list",
       complexity="multi",
       user_input="List the partitions on /dev/sdc, then I'll tell you which one to format.",
       args={"operation": "list", "device": "/dev/sdc"},
       answer="sdc 1.8T disk\n  sdc1 1.8T part (no filesystem)"),
    V2(id="disk-list-v2-0005", tool="disk", operation="list",
       complexity="single",
       user_input="What partitions exist on sdb1's parent disk?",
       args={"operation": "list", "device": "/dev/sdb"},
       answer="sdb 2T disk\n  sdb1 1T part /mnt/archive\n  sdb2 1T part (no filesystem)"),
    V2(id="disk-list-v2-0006", tool="disk", operation="list",
       complexity="diagnostic",
       user_input="Is there any unpartitioned space left on nvme1n1? Something about lvm resize came up.",
       args={"operation": "list", "device": "/dev/nvme1n1"},
       answer="nvme1n1 1.8T disk\n  nvme1n1p1 1.5T part /var/lib/pgsql\n  free space: 300G unallocated"),
    V2(id="disk-list-v2-0007", tool="disk", operation="list",
       complexity="single",
       user_input="dump the block device tree",
       args={"operation": "list"},
       answer="sda 500G disk\n  sda1 500G part /\nsdb 2T disk\n  sdb1 2T part /mnt/archive"),
    V2(id="disk-list-v2-0008", tool="disk", operation="list",
       complexity="single",
       user_input="Can you show partitions on /dev/sde? I think it's the USB stick.",
       args={"operation": "list", "device": "/dev/sde"},
       answer="sde 32G disk\n  sde1 32G part (no filesystem)"),
    V2(id="disk-smart-v2-0001", tool="disk", operation="smart",
       complexity="single",
       user_input="Pull SMART data for /dev/sdb1.",
       args={"operation": "smart", "device": "/dev/sdb1"},
       answer="SMART overall-health: PASSED\nReallocated_Sector_Ct: 0\nPower_On_Hours: 18422\nTemperature_Celsius: 34"),
    V2(id="disk-smart-v2-0002", tool="disk", operation="smart",
       complexity="diagnostic",
       user_input="Backups keep stalling and I'm seeing read errors in dmesg for nvme0n1p2 — check the drive's health.",
       args={"operation": "smart", "device": "/dev/nvme0n1p2"},
       answer="SMART overall-health: FAILED\nMedia_and_Data_Integrity_Errors: 14\nPercentage_Used: 97%"),
    V2(id="disk-smart-v2-0003", tool="disk", operation="smart",
       complexity="single",
       user_input="is /dev/sda1 healthy?",
       args={"operation": "smart", "device": "/dev/sda1"},
       answer="SMART overall-health: PASSED\nReallocated_Sector_Ct: 3\nPower_On_Hours: 42011"),
    V2(id="disk-smart-v2-0004", tool="disk", operation="smart",
       complexity="multi",
       user_input="Check SMART on /dev/sdc1, and if it's failing I'll want to schedule an RMA.",
       args={"operation": "smart", "device": "/dev/sdc1"},
       answer="SMART overall-health: PASSED\nCurrent_Pending_Sector: 0\nPower_On_Hours: 5012"),
    V2(id="disk-smart-v2-0005", tool="disk", operation="smart",
       complexity="diagnostic",
       user_input="A user's laptop drive under /dev/nvme1n1p1 keeps throwing filesystem corruption. Worth an RMA?",
       args={"operation": "smart", "device": "/dev/nvme1n1p1"},
       answer="SMART overall-health: FAILED\nMedia_Errors: 231\nAvailable_Spare: 12%"),
    V2(id="disk-smart-v2-0006", tool="disk", operation="smart",
       complexity="single",
       user_input="Run a health check on /dev/sdd.",
       args={"operation": "smart", "device": "/dev/sdd"},
       answer="SMART overall-health: PASSED\nReallocated_Sector_Ct: 0\nPower_On_Hours: 903"),
    V2(id="disk-smart-v2-0007", tool="disk", operation="smart",
       complexity="single",
       user_input="get the smart attributes for /dev/sde1",
       args={"operation": "smart", "device": "/dev/sde1"},
       answer="SMART overall-health: PASSED\nUDMA_CRC_Error_Count: 0\nPower_On_Hours: 22088"),
    V2(id="disk-smart-v2-0008", tool="disk", operation="smart",
       complexity="diagnostic",
       user_input="The RAID monitor flagged degraded array members — check disk health on /dev/sdf1 before we touch mdadm.",
       args={"operation": "smart", "device": "/dev/sdf1"},
       answer="SMART overall-health: PASSED\nReallocated_Sector_Ct: 128\nPower_On_Hours: 61200"),
    V2(id="disk-mount-v2-0001", tool="disk", operation="mount",
       complexity="single",
       user_input="Mount /dev/sdb1 at /mnt/archive.",
       args={"operation": "mount", "device": "/dev/sdb1", "mount_point": "/mnt/archive"},
       answer="mounted /dev/sdb1 at /mnt/archive\nfilesystem: xfs, size: 2.0T"),
    V2(id="disk-mount-v2-0002", tool="disk", operation="mount",
       complexity="multi",
       user_input="Attach the new nvme1n1p1 partition under /data, then I'll update fstab myself.",
       args={"operation": "mount", "device": "/dev/nvme1n1p1", "mount_point": "/data"},
       answer="mounted /dev/nvme1n1p1 at /data\nfilesystem: ext4, size: 1.8T"),
    V2(id="disk-mount-v2-0003", tool="disk", operation="mount",
       complexity="single",
       user_input="attach sdc1 to /srv/media",
       args={"operation": "mount", "device": "/dev/sdc1", "mount_point": "/srv/media"},
       answer="mounted /dev/sdc1 at /srv/media\nfilesystem: xfs, size: 4.0T"),
    V2(id="disk-mount-v2-0004", tool="disk", operation="mount",
       complexity="diagnostic",
       user_input="The backup script says /mnt/nas isn't there — should that be mounted from sdd1?",
       args={"operation": "mount", "device": "/dev/sdd1", "mount_point": "/mnt/nas"},
       answer="mounted /dev/sdd1 at /mnt/nas\nfilesystem: nfs4, size: 8.0T"),
    V2(id="disk-mount-v2-0005", tool="disk", operation="mount",
       complexity="single",
       user_input="Please mount /dev/sde2 onto /var/lib/containers.",
       args={"operation": "mount", "device": "/dev/sde2", "mount_point": "/var/lib/containers"},
       answer="mounted /dev/sde2 at /var/lib/containers\nfilesystem: xfs, size: 500G"),
    V2(id="disk-mount-v2-0006", tool="disk", operation="mount",
       complexity="single",
       user_input="mount the sdf1 volume to /mnt/scratch",
       args={"operation": "mount", "device": "/dev/sdf1", "mount_point": "/mnt/scratch"},
       answer="mounted /dev/sdf1 at /mnt/scratch\nfilesystem: ext4, size: 1.0T"),
    V2(id="disk-mount-v2-0007", tool="disk", operation="mount",
       complexity="multi",
       user_input="Ticket 8890 wants the archive volume back online — mount /dev/sdg1 to /srv/archive, then re-run the sync job.",
       args={"operation": "mount", "device": "/dev/sdg1", "mount_point": "/srv/archive"},
       answer="mounted /dev/sdg1 at /srv/archive\nfilesystem: xfs, size: 6.0T"),
    V2(id="disk-mount-v2-0008", tool="disk", operation="mount",
       complexity="single",
       user_input="Get /dev/sdh1 mounted at /mnt/staging.",
       args={"operation": "mount", "device": "/dev/sdh1", "mount_point": "/mnt/staging"},
       answer="mounted /dev/sdh1 at /mnt/staging\nfilesystem: btrfs, size: 2.0T"),
    V2(id="disk-unmount-v2-0001", tool="disk", operation="unmount",
       complexity="single",
       user_input="Unmount /mnt/archive.",
       args={"operation": "unmount", "target": "/mnt/archive"},
       answer="unmounted /mnt/archive\ndevice /dev/sdb1 detached"),
    V2(id="disk-unmount-v2-0002", tool="disk", operation="unmount",
       complexity="diagnostic",
       user_input="A user can't eject the external drive at /mnt/usb1 cleanly — can you detach it from here first?",
       args={"operation": "unmount", "target": "/mnt/usb1"},
       answer="unmounted /mnt/usb1\ndevice /dev/sdc1 detached"),
    V2(id="disk-unmount-v2-0003", tool="disk", operation="unmount",
       complexity="single",
       user_input="detach /dev/sdd1",
       args={"operation": "unmount", "target": "/dev/sdd1"},
       answer="unmounted /mnt/nas\ndevice /dev/sdd1 detached"),
    V2(id="disk-unmount-v2-0004", tool="disk", operation="unmount",
       complexity="multi",
       user_input="Unmount /data on nvme1n1p1 so I can run fsck on it.",
       args={"operation": "unmount", "target": "/data"},
       answer="unmounted /data\ndevice /dev/nvme1n1p1 detached"),
    V2(id="disk-unmount-v2-0005", tool="disk", operation="unmount",
       complexity="single",
       user_input="Take /mnt/scratch offline.",
       args={"operation": "unmount", "target": "/mnt/scratch"},
       answer="unmounted /mnt/scratch\ndevice /dev/sdf1 detached"),
    V2(id="disk-unmount-v2-0006", tool="disk", operation="unmount",
       complexity="single",
       user_input="please unmount /srv/media before we swap the disk",
       args={"operation": "unmount", "target": "/srv/media"},
       answer="unmounted /srv/media\ndevice /dev/sdc1 detached"),
    V2(id="disk-unmount-v2-0007", tool="disk", operation="unmount",
       complexity="diagnostic",
       user_input="The samba share on /srv/archive is throwing stale-handle errors — should we unmount and remount it?",
       args={"operation": "unmount", "target": "/srv/archive"},
       answer="unmounted /srv/archive\ndevice /dev/sdg1 detached"),
    V2(id="disk-unmount-v2-0008", tool="disk", operation="unmount",
       complexity="single",
       user_input="Detach the volume mounted at /mnt/staging.",
       args={"operation": "unmount", "target": "/mnt/staging"},
       answer="unmounted /mnt/staging\ndevice /dev/sdh1 detached"),
    V2(id="disk-unmount-v2-0009", tool="disk", operation="unmount",
       complexity="single",
       user_input="unmount /var/lib/containers",
       args={"operation": "unmount", "target": "/var/lib/containers"},
       answer="unmounted /var/lib/containers\ndevice /dev/sde2 detached"),
    V2(id="disk-format-v2-0001", tool="disk", operation="format",
       complexity="single",
       user_input="Format /dev/sdc1 as ext4.",
       args={"operation": "format", "device": "/dev/sdc1", "fstype": "ext4"},
       answer="mkfs.ext4 completed on /dev/sdc1\nUUID: 3c9a2e10-6b7a-4a2e-9c11-88f4a2b1e001"),
    V2(id="disk-format-v2-0002", tool="disk", operation="format",
       complexity="multi",
       user_input="Wipe and format /dev/sdd1 with xfs, then I'll mount it at /srv/new.",
       args={"operation": "format", "device": "/dev/sdd1", "fstype": "xfs"},
       answer="mkfs.xfs completed on /dev/sdd1\nUUID: 91af2c40-11d2-4b6e-8a90-cd0021f5a002"),
    V2(id="disk-format-v2-0003", tool="disk", operation="format",
       complexity="single",
       user_input="make sdb2 a fresh ext4 filesystem",
       args={"operation": "format", "device": "/dev/sdb2", "fstype": "ext4"},
       answer="mkfs.ext4 completed on /dev/sdb2\nUUID: 4d2b8e70-8912-4a11-9e5c-0a7fbc330103"),
    V2(id="disk-format-v2-0004", tool="disk", operation="format",
       complexity="single",
       user_input="Create a filesystem on /dev/sde3, default type is fine.",
       args={"operation": "format", "device": "/dev/sde3"},
       answer="mkfs.ext4 completed on /dev/sde3\nUUID: 7f0a3d21-2244-4c88-8b0e-5c9a1e4f0004"),
    V2(id="disk-format-v2-0005", tool="disk", operation="format",
       complexity="diagnostic",
       user_input="The new nvme2n1p1 partition shows as unrecognized filesystem type in blkid — do we need to format it first before mounting?",
       args={"operation": "format", "device": "/dev/nvme2n1p1", "fstype": "xfs"},
       answer="mkfs.xfs completed on /dev/nvme2n1p1\nUUID: 1a2b3c4d-5e6f-4788-9012-abcdef012345"),
    V2(id="disk-format-v2-0006", tool="disk", operation="format",
       complexity="single",
       user_input="Format sdf2 with btrfs.",
       args={"operation": "format", "device": "/dev/sdf2", "fstype": "btrfs"},
       answer="mkfs.btrfs completed on /dev/sdf2\nUUID: 2b3c4d5e-6f70-4899-a123-bcdef0123456"),
    V2(id="disk-format-v2-0007", tool="disk", operation="format",
       complexity="single",
       user_input="lay down ext4 on /dev/sdg2",
       args={"operation": "format", "device": "/dev/sdg2", "fstype": "ext4"},
       answer="mkfs.ext4 completed on /dev/sdg2\nUUID: 3c4d5e6f-7081-4900-b234-cdef01234567"),
    V2(id="disk-format-v2-0008", tool="disk", operation="format",
       complexity="multi",
       user_input="Format /dev/sdh2 as xfs and then set up the samba usershare on top of it.",
       args={"operation": "format", "device": "/dev/sdh2", "fstype": "xfs"},
       answer="mkfs.xfs completed on /dev/sdh2\nUUID: 4d5e6f70-8192-4a11-c345-def012345678"),
    V2(id="disk-partition-v2-0001", tool="disk", operation="partition",
       complexity="single",
       user_input="Create a msdos label on /dev/sdc.",
       args={"operation": "partition", "device": "/dev/sdc", "command": ["mklabel", "msdos"]},
       answer="parted /dev/sdc: mklabel msdos applied\npartition table: msdos, 0 partitions"),
    V2(id="disk-partition-v2-0002", tool="disk", operation="partition",
       complexity="multi",
       user_input="Set up an msdos label on /dev/sdd and add a primary partition spanning the whole disk, then I'll format it.",
       args={"operation": "partition", "device": "/dev/sdd", "command": ["mklabel", "msdos", "mkpart", "primary", "0%", "100%"]},
       answer="parted /dev/sdd: mklabel msdos applied\nmkpart primary 0%-100% created as /dev/sdd1"),
    V2(id="disk-partition-v2-0003", tool="disk", operation="partition",
       complexity="single",
       user_input="add a 100GB primary partition to /dev/sde",
       args={"operation": "partition", "device": "/dev/sde", "command": ["mkpart", "primary", "0%", "100GB"]},
       answer="parted /dev/sde: mkpart primary 0%-100GB created as /dev/sde1"),
    V2(id="disk-partition-v2-0004", tool="disk", operation="partition",
       complexity="diagnostic",
       user_input="The new sdf drive shows no partition table in fdisk -l. Do we need to lay one down before parted can add a partition?",
       args={"operation": "partition", "device": "/dev/sdf", "command": ["mklabel", "msdos"]},
       answer="parted /dev/sdf: mklabel msdos applied\npartition table: msdos, 0 partitions"),
    V2(id="disk-partition-v2-0005", tool="disk", operation="partition",
       complexity="single",
       user_input="Remove partition 2 from /dev/sdg.",
       args={"operation": "partition", "device": "/dev/sdg", "command": ["rm", "2"]},
       answer="parted /dev/sdg: partition 2 removed\nremaining partitions: 1"),
    V2(id="disk-partition-v2-0006", tool="disk", operation="partition",
       complexity="single",
       user_input="print the partition table for /dev/sdh",
       args={"operation": "partition", "device": "/dev/sdh", "command": ["print"]},
       answer="Disk /dev/sdh: 2.0TB, type ATA (scsi)\nPartition Table: msdos\nNumber 1: 0.00TB-2.00TB xfs"),
    V2(id="disk-partition-v2-0007", tool="disk", operation="partition",
       complexity="multi",
       user_input="Wipe the current label on /dev/sdi with a new msdos table, then create partitions for boot and root.",
       args={"operation": "partition", "device": "/dev/sdi", "command": ["mklabel", "msdos", "mkpart", "boot", "0%", "1GB", "mkpart", "root", "1GB", "100%"]},
       answer="parted /dev/sdi: mklabel msdos applied\ncreated /dev/sdi1 (boot), /dev/sdi2 (root)"),
    V2(id="disk-partition-v2-0008", tool="disk", operation="partition",
       complexity="single",
       user_input="resize partition 1 on /dev/sdj to end at 500GB",
       args={"operation": "partition", "device": "/dev/sdj", "command": ["resizepart", "1", "500GB"]},
       answer="parted /dev/sdj: resizepart 1 to 500GB applied\npartition 1 now 500GB"),
    V2(id="disk-partition-v2-0009", tool="disk", operation="partition",
       complexity="single",
       user_input="mark partition 1 on /dev/sdk as bootable",
       args={"operation": "partition", "device": "/dev/sdk", "command": ["set", "1", "boot", "on"]},
       answer="parted /dev/sdk: set 1 boot on applied\nflags on partition 1: boot"),
    V2(id="disk-wipe-v2-0001", tool="disk", operation="wipe",
       complexity="single",
       user_input="Wipe all filesystem signatures from /dev/sdc1 before we reformat it.",
       args={"operation": "wipe", "device": "/dev/sdc1"},
       answer="wipefs completed on /dev/sdc1\nsignatures removed: 1 (ext4)"),
    V2(id="disk-wipe-v2-0002", tool="disk", operation="wipe",
       complexity="diagnostic",
       user_input="mkfs on /dev/sdd1 is refusing because it detects an existing xfs signature — how do we clear that?",
       args={"operation": "wipe", "device": "/dev/sdd1"},
       answer="wipefs completed on /dev/sdd1\nsignatures removed: 1 (xfs)"),
    V2(id="disk-wipe-v2-0003", tool="disk", operation="wipe",
       complexity="single",
       user_input="clear the fs signature on sde2",
       args={"operation": "wipe", "device": "/dev/sde2"},
       answer="wipefs completed on /dev/sde2\nsignatures removed: 1 (ext4)"),
    V2(id="disk-wipe-v2-0004", tool="disk", operation="wipe",
       complexity="multi",
       user_input="Wipe /dev/sdf1's signatures, then repartition it as msdos.",
       args={"operation": "wipe", "device": "/dev/sdf1"},
       answer="wipefs completed on /dev/sdf1\nsignatures removed: 1 (btrfs)"),
    V2(id="disk-wipe-v2-0005", tool="disk", operation="wipe",
       complexity="single",
       user_input="Erase all filesystem markers on /dev/sdg1.",
       args={"operation": "wipe", "device": "/dev/sdg1"},
       answer="wipefs completed on /dev/sdg1\nsignatures removed: 2 (lvm2, luks)"),
    V2(id="disk-wipe-v2-0006", tool="disk", operation="wipe",
       complexity="single",
       user_input="strip the old raid signature off /dev/sdh1",
       args={"operation": "wipe", "device": "/dev/sdh1"},
       answer="wipefs completed on /dev/sdh1\nsignatures removed: 1 (linux_raid_member)"),
    V2(id="disk-wipe-v2-0007", tool="disk", operation="wipe",
       complexity="diagnostic",
       user_input="blkid still shows an old luks header on /dev/sdi1 after we decommissioned the encrypted volume — can that be cleared?",
       args={"operation": "wipe", "device": "/dev/sdi1"},
       answer="wipefs completed on /dev/sdi1\nsignatures removed: 1 (crypto_LUKS)"),
    V2(id="disk-wipe-v2-0008", tool="disk", operation="wipe",
       complexity="single",
       user_input="Wipe /dev/sdj1 clean of any filesystem headers.",
       args={"operation": "wipe", "device": "/dev/sdj1"},
       answer="wipefs completed on /dev/sdj1\nsignatures removed: 1 (ntfs)"),
    V2(id="disk-wipe-v2-0009", tool="disk", operation="wipe",
       complexity="single",
       user_input="remove filesystem signatures from sdk1",
       args={"operation": "wipe", "device": "/dev/sdk1"},
       answer="wipefs completed on /dev/sdk1\nsignatures removed: 1 (swap)"),
    V2(id="disk-dd_write-v2-0001", tool="disk", operation="dd_write",
       complexity="single",
       user_input="Write the image at /root/images/rocky9.img onto /dev/sdc.",
       args={"operation": "dd_write", "source": "/root/images/rocky9.img", "device": "/dev/sdc"},
       answer="dd completed: 4.2GB copied to /dev/sdc\nbs=4M, elapsed 38s"),
    V2(id="disk-dd_write-v2-0002", tool="disk", operation="dd_write",
       complexity="diagnostic",
       user_input="We built a bootable recovery image at /srv/iso/recovery.img and need it on the spare USB stick before the field visit — that's /dev/sdd, right?",
       args={"operation": "dd_write", "source": "/srv/iso/recovery.img", "device": "/dev/sdd"},
       answer="dd completed: 1.1GB copied to /dev/sdd\nbs=4M, elapsed 12s"),
    V2(id="disk-dd_write-v2-0003", tool="disk", operation="dd_write",
       complexity="single",
       user_input="dd /home/ops/rocky-minimal.iso onto /dev/sde",
       args={"operation": "dd_write", "source": "/home/ops/rocky-minimal.iso", "device": "/dev/sde"},
       answer="dd completed: 950MB copied to /dev/sde\nbs=4M, elapsed 9s"),
    V2(id="disk-dd_write-v2-0004", tool="disk", operation="dd_write",
       complexity="multi",
       user_input="Write /var/tmp/clonezilla.img to /dev/sdf, then I'll boot from it to restore the workstation.",
       args={"operation": "dd_write", "source": "/var/tmp/clonezilla.img", "device": "/dev/sdf"},
       answer="dd completed: 2.8GB copied to /dev/sdf\nbs=4M, elapsed 24s"),
    V2(id="disk-dd_write-v2-0005", tool="disk", operation="dd_write",
       complexity="single",
       user_input="Image /dev/sdg from the file /mnt/nas/images/base.img.",
       args={"operation": "dd_write", "source": "/mnt/nas/images/base.img", "device": "/dev/sdg"},
       answer="dd completed: 6.5GB copied to /dev/sdg\nbs=4M, elapsed 55s"),
    V2(id="disk-dd_write-v2-0006", tool="disk", operation="dd_write",
       complexity="single",
       user_input="burn /opt/isos/centos-stream.iso to /dev/sdh",
       args={"operation": "dd_write", "source": "/opt/isos/centos-stream.iso", "device": "/dev/sdh"},
       answer="dd completed: 3.4GB copied to /dev/sdh\nbs=4M, elapsed 30s"),
    V2(id="disk-dd_write-v2-0007", tool="disk", operation="dd_write",
       complexity="diagnostic",
       user_input="The imaging station reported failure halfway through writing /data/images/golden.img to /dev/sdi — can you retry the write?",
       args={"operation": "dd_write", "source": "/data/images/golden.img", "device": "/dev/sdi"},
       answer="dd completed: 5.0GB copied to /dev/sdi\nbs=4M, elapsed 44s"),
    V2(id="disk-dd_write-v2-0008", tool="disk", operation="dd_write",
       complexity="single",
       user_input="Copy /root/win-recovery.img raw onto /dev/sdj.",
       args={"operation": "dd_write", "source": "/root/win-recovery.img", "device": "/dev/sdj"},
       answer="dd completed: 8.1GB copied to /dev/sdj\nbs=4M, elapsed 71s"),
    V2(id="disk-dd_write-v2-0009", tool="disk", operation="dd_write",
       complexity="single",
       user_input="dd the ubuntu-server.iso from /srv/isos onto /dev/sdk",
       args={"operation": "dd_write", "source": "/srv/isos/ubuntu-server.iso", "device": "/dev/sdk"},
       answer="dd completed: 2.1GB copied to /dev/sdk\nbs=4M, elapsed 18s"),
]

from finetune.scenarios_v2 import check_module; check_module("disk", SCENARIOS_V2)
