"""finetune/scenarios_v2/dnf_modules.py -- corpus v2 scenarios for 'dnf_modules'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(
        id='dnf_modules-list-v2-0001',
        tool='dnf_modules',
        operation='list',
        complexity='single',
        user_input='Give me every module stream this box currently knows about.',
        args={'operation': 'list'},
        answer='nodejs        18 [d], 20            common [d], development, minimal\npostgresql    13, 15 [d]         client, server [d]\nphp           8.1, 8.2 [d]        common [d], devel\nruby          3.1 [d], 3.3        common [d]\nGo modules listed: 4',
    ),
    V2(
        id='dnf_modules-list-v2-0002',
        tool='dnf_modules',
        operation='list',
        complexity='single',
        user_input='A build pipeline needs Go — what golang module streams do we have to choose from?',
        args={'operation': 'list', 'module': 'golang'},
        answer='go-toolset   rhel8, rhel9 [d]   common [d]',
    ),
    V2(
        id='dnf_modules-list-v2-0003',
        tool='dnf_modules',
        operation='list',
        complexity='diagnostic',
        user_input='Before I touch anything, can you pull up what mariadb stream options exist on this host?',
        args={'operation': 'list', 'module': 'mariadb'},
        answer='mariadb      10.5 [d], 10.11    client, server [d], galera',
    ),
    V2(
        id='dnf_modules-list-v2-0004',
        tool='dnf_modules',
        operation='list',
        complexity='multi',
        user_input="List module streams, then we'll enable whichever nodejs one is newest.",
        args={'operation': 'list'},
        answer='container-tools  rhel8, rhel9 [d]   common [d]\nnodejs           18 [d], 20         common [d], development, minimal\nperl             5.32 [d]           common [d], minimal',
    ),
    V2(
        id='dnf_modules-list-v2-0005',
        tool='dnf_modules',
        operation='list',
        complexity='diagnostic',
        user_input='Is python3.11 even available as a module here, or do I need a different source?',
        args={'operation': 'list', 'module': 'python3.11'},
        answer="No matches found for module 'python3.11'.",
    ),
    V2(
        id='dnf_modules-list-v2-0006',
        tool='dnf_modules',
        operation='list',
        complexity='single',
        user_input='Full module stream dump for the change ticket, please.',
        args={'operation': 'list'},
        answer='nginx        1.22, 1.24 [d]     common [d]\nswig         3.0, 4.0 [d]       common [d]\nvirt         rhel [d]            common [d], hostdev\nModules listed: 11',
    ),
    V2(
        id='dnf_modules-list-v2-0007',
        tool='dnf_modules',
        operation='list',
        complexity='single',
        user_input="The app team keeps asking which ruby streams we can switch to — check what's on offer.",
        args={'operation': 'list', 'module': 'ruby'},
        answer='ruby         2.7, 3.1 [d], 3.3   common [d]',
    ),
    V2(
        id='dnf_modules-list-v2-0008',
        tool='dnf_modules',
        operation='list',
        complexity='diagnostic',
        user_input='Something in nftables logging looks fine, but separately — what dnf module streams are installed vs just available right now?',
        args={'operation': 'list'},
        answer='postgresql   13 [i], 15 [d]      client, server [d]\nphp          8.1, 8.2 [d]        common [d]\nInstalled streams: postgresql:13',
    ),
    V2(
        id='dnf_modules-info-v2-0009',
        tool='dnf_modules',
        operation='info',
        complexity='single',
        user_input="What's actually in the nodejs:20 stream before I switch the app server over?",
        args={'operation': 'info', 'module': 'nodejs:20'},
        answer='Name: nodejs\nStream: 20\nProfiles: common [d], development, minimal, s2i\nDefault profiles: common\nRepo: appstream\nSummary: Javascript runtime',
    ),
    V2(
        id='dnf_modules-info-v2-0010',
        tool='dnf_modules',
        operation='info',
        complexity='single',
        user_input='Show module info for postgresql:15.',
        args={'operation': 'info', 'module': 'postgresql:15'},
        answer='Name: postgresql\nStream: 15\nProfiles: client, server [d]\nDefault profiles: server\nRepo: appstream\nSummary: PostgreSQL server and client module',
    ),
    V2(
        id='dnf_modules-info-v2-0011',
        tool='dnf_modules',
        operation='info',
        complexity='multi',
        user_input="Pull up the php:8.2 module info, then we'll decide whether to enable it.",
        args={'operation': 'info', 'module': 'php:8.2'},
        answer='Name: php\nStream: 8.2\nProfiles: common [d], devel, minimal\nDefault profiles: common\nRepo: appstream\nSummary: PHP scripting language',
    ),
    V2(
        id='dnf_modules-info-v2-0012',
        tool='dnf_modules',
        operation='info',
        complexity='single',
        user_input='Ticket asks for ruby 3.3 details before the migration window — pull the module info.',
        args={'operation': 'info', 'module': 'ruby:3.3'},
        answer='Name: ruby\nStream: 3.3\nProfiles: common [d]\nDefault profiles: common\nRepo: appstream\nSummary: An interpreter of object-oriented scripting language',
    ),
    V2(
        id='dnf_modules-info-v2-0013',
        tool='dnf_modules',
        operation='info',
        complexity='diagnostic',
        user_input='Podman keeps failing to build on this host — what profile does the container-tools module actually ship?',
        args={'operation': 'info', 'module': 'container-tools:rhel9'},
        answer='Name: container-tools\nStream: rhel9\nProfiles: common [d]\nDefault profiles: common\nRepo: appstream\nSummary: Common tools and dependencies for container runtimes',
    ),
    V2(
        id='dnf_modules-info-v2-0014',
        tool='dnf_modules',
        operation='info',
        complexity='single',
        user_input='Get the details on mariadb:10.11 before we plan the upgrade.',
        args={'operation': 'info', 'module': 'mariadb:10.11'},
        answer='Name: mariadb\nStream: 10.11\nProfiles: client, server [d], galera, devel\nDefault profiles: server\nRepo: appstream\nSummary: MariaDB Server and client module',
    ),
    V2(
        id='dnf_modules-info-v2-0015',
        tool='dnf_modules',
        operation='info',
        complexity='single',
        user_input='info on go-toolset:rhel9',
        args={'operation': 'info', 'module': 'go-toolset:rhel9'},
        answer='Name: go-toolset\nStream: rhel9\nProfiles: common [d]\nDefault profiles: common\nRepo: appstream\nSummary: Go toolset',
    ),
    V2(
        id='dnf_modules-info-v2-0016',
        tool='dnf_modules',
        operation='info',
        complexity='diagnostic',
        user_input='A deploy failed saying the nginx module profile is missing — check what nginx:1.24 actually offers.',
        args={'operation': 'info', 'module': 'nginx:1.24'},
        answer='Name: nginx\nStream: 1.24\nProfiles: common [d]\nDefault profiles: common\nRepo: appstream\nSummary: nginx webserver',
    ),
    V2(
        id='dnf_modules-enable-v2-0017',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='Switch the nodejs module stream over to 20.',
        args={'operation': 'enable', 'module': 'nodejs:20'},
        answer='Enabling module streams:\n nodejs:20\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0018',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='Enable postgresql:15 so we can install it next.',
        args={'operation': 'enable', 'module': 'postgresql:15'},
        answer='Enabling module streams:\n postgresql:15\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0019',
        tool='dnf_modules',
        operation='enable',
        complexity='multi',
        user_input='Enable the php:8.2 stream and then queue up the install for it.',
        args={'operation': 'enable', 'module': 'php:8.2'},
        answer='Enabling module streams:\n php:8.2\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0020',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='The app requires ruby 3.3, not the default — enable that stream.',
        args={'operation': 'enable', 'module': 'ruby:3.3'},
        answer='Enabling module streams:\n ruby:3.3\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0021',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='Turn on container-tools:rhel9.',
        args={'operation': 'enable', 'module': 'container-tools:rhel9'},
        answer='Enabling module streams:\n container-tools:rhel9\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0022',
        tool='dnf_modules',
        operation='enable',
        complexity='diagnostic',
        user_input='The old mariadb 10.5 stream is EOL per the audit — what do we need to enable to move forward?',
        args={'operation': 'enable', 'module': 'mariadb:10.11'},
        answer='Enabling module streams:\n mariadb:10.11\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0023',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='enable go-toolset:rhel9',
        args={'operation': 'enable', 'module': 'go-toolset:rhel9'},
        answer='Enabling module streams:\n go-toolset:rhel9\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-enable-v2-0024',
        tool='dnf_modules',
        operation='enable',
        complexity='single',
        user_input='We need the newer nginx stream active before the install step — enable nginx:1.24.',
        args={'operation': 'enable', 'module': 'nginx:1.24'},
        answer='Enabling module streams:\n nginx:1.24\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0025',
        tool='dnf_modules',
        operation='disable',
        complexity='single',
        user_input="Disable the nodejs module entirely, we're moving to a container image instead.",
        args={'operation': 'disable', 'module': 'nodejs'},
        answer='Disabling modules:\n nodejs\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0026',
        tool='dnf_modules',
        operation='disable',
        complexity='single',
        user_input='php:7.4 is flagged EOL in the security scan — shut that stream off.',
        args={'operation': 'disable', 'module': 'php:7.4'},
        answer='Disabling modules:\n php:7.4\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0027',
        tool='dnf_modules',
        operation='disable',
        complexity='diagnostic',
        user_input='The compliance report says an old postgresql stream is still enabled — turn it off.',
        args={'operation': 'disable', 'module': 'postgresql:13'},
        answer='Disabling modules:\n postgresql:13\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0028',
        tool='dnf_modules',
        operation='disable',
        complexity='multi',
        user_input="Disable ruby:3.0 and I'll enable 3.3 right after.",
        args={'operation': 'disable', 'module': 'ruby:3.0'},
        answer='Disabling modules:\n ruby:3.0\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0029',
        tool='dnf_modules',
        operation='disable',
        complexity='single',
        user_input='Turn off the nginx:mainline module on this host.',
        args={'operation': 'disable', 'module': 'nginx:mainline'},
        answer='Disabling modules:\n nginx:mainline\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0030',
        tool='dnf_modules',
        operation='disable',
        complexity='diagnostic',
        user_input="There's a stale python27 module still active according to the audit — disable it.",
        args={'operation': 'disable', 'module': 'python27'},
        answer='Disabling modules:\n python27\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0031',
        tool='dnf_modules',
        operation='disable',
        complexity='single',
        user_input="We're switching to the base repo package instead of the module — disable mariadb.",
        args={'operation': 'disable', 'module': 'mariadb'},
        answer='Disabling modules:\n mariadb\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0032',
        tool='dnf_modules',
        operation='disable',
        complexity='single',
        user_input='disable container-tools module',
        args={'operation': 'disable', 'module': 'container-tools'},
        answer='Disabling modules:\n container-tools\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-disable-v2-0033',
        tool='dnf_modules',
        operation='disable',
        complexity='diagnostic',
        user_input='libvirt keeps pulling odd package versions — is the virt module still enabled, and can you turn it off?',
        args={'operation': 'disable', 'module': 'virt'},
        answer='Disabling modules:\n virt\n\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0034',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='Install the nodejs:20 development profile, the app needs the headers.',
        args={'operation': 'install', 'module': 'nodejs:20/development'},
        answer='Installing module profile: nodejs:20/development\nDependencies resolved.\nInstalled:\n  nodejs-20.11.0  npm-10.2.4  nodejs-full-i18n\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0035',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='Install postgresql 15 with the server profile.',
        args={'operation': 'install', 'module': 'postgresql:15/server'},
        answer='Installing module profile: postgresql:15/server\nDependencies resolved.\nInstalled:\n  postgresql-server-15.5  postgresql-15.5  postgresql-contrib-15.5\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0036',
        tool='dnf_modules',
        operation='install',
        complexity='multi',
        user_input="Install the php:8.2 common profile, then we'll restart php-fpm.",
        args={'operation': 'install', 'module': 'php:8.2/common'},
        answer='Installing module profile: php:8.2/common\nDependencies resolved.\nInstalled:\n  php-8.2.10  php-common-8.2.10  php-cli-8.2.10\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0037',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='Get ruby 3.3 installed via its module profile.',
        args={'operation': 'install', 'module': 'ruby:3.3/common'},
        answer='Installing module profile: ruby:3.3/common\nDependencies resolved.\nInstalled:\n  ruby-3.3.0  ruby-libs-3.3.0  rubygems-3.5.3\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0038',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='Deployment script needs container-tools — install the module profile.',
        args={'operation': 'install', 'module': 'container-tools:rhel9/common'},
        answer='Installing module profile: container-tools:rhel9/common\nDependencies resolved.\nInstalled:\n  podman-4.6.1  buildah-1.31.0  skopeo-1.13.2\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0039',
        tool='dnf_modules',
        operation='install',
        complexity='diagnostic',
        user_input="The DB team says mariadb isn't installed on the new host yet — get the server profile in via its module.",
        args={'operation': 'install', 'module': 'mariadb:10.11/server'},
        answer='Installing module profile: mariadb:10.11/server\nDependencies resolved.\nInstalled:\n  mariadb-server-10.11.6  mariadb-10.11.6  mariadb-common-10.11.6\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0040',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='install go-toolset module',
        args={'operation': 'install', 'module': 'go-toolset:rhel9/common'},
        answer='Installing module profile: go-toolset:rhel9/common\nDependencies resolved.\nInstalled:\n  golang-1.21.1  go-toolset-1.21.1\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0041',
        tool='dnf_modules',
        operation='install',
        complexity='single',
        user_input='Install nginx via its module profile, version 1.24.',
        args={'operation': 'install', 'module': 'nginx:1.24/common'},
        answer='Installing module profile: nginx:1.24/common\nDependencies resolved.\nInstalled:\n  nginx-1.24.0  nginx-filesystem-1.24.0\nComplete!',
    ),
    V2(
        id='dnf_modules-install-v2-0042',
        tool='dnf_modules',
        operation='install',
        complexity='diagnostic',
        user_input='A cron job is failing with a missing perl interpreter — install the minimal perl module profile to fix it.',
        args={'operation': 'install', 'module': 'perl:5.32/minimal'},
        answer='Installing module profile: perl:5.32/minimal\nDependencies resolved.\nInstalled:\n  perl-interpreter-5.32.1  perl-libs-5.32.1\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0043',
        tool='dnf_modules',
        operation='reset',
        complexity='single',
        user_input='Reset the nodejs module back to its default state.',
        args={'operation': 'reset', 'module': 'nodejs'},
        answer='Resetting module: nodejs\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0044',
        tool='dnf_modules',
        operation='reset',
        complexity='single',
        user_input='We need to switch php streams — reset the module first.',
        args={'operation': 'reset', 'module': 'php'},
        answer='Resetting module: php\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0045',
        tool='dnf_modules',
        operation='reset',
        complexity='diagnostic',
        user_input='The postgresql module is stuck in a weird enabled-but-broken state after a failed upgrade — reset it.',
        args={'operation': 'reset', 'module': 'postgresql'},
        answer='Resetting module: postgresql\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0046',
        tool='dnf_modules',
        operation='reset',
        complexity='multi',
        user_input='Reset the ruby module, then enable ruby:3.3 fresh.',
        args={'operation': 'reset', 'module': 'ruby'},
        answer='Resetting module: ruby\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0047',
        tool='dnf_modules',
        operation='reset',
        complexity='single',
        user_input='Reset the nginx module to its default stream.',
        args={'operation': 'reset', 'module': 'nginx'},
        answer='Resetting module: nginx\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0048',
        tool='dnf_modules',
        operation='reset',
        complexity='diagnostic',
        user_input="mariadb won't enable a different stream and complains about a conflict — reset the module state.",
        args={'operation': 'reset', 'module': 'mariadb'},
        answer='Resetting module: mariadb\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0049',
        tool='dnf_modules',
        operation='reset',
        complexity='single',
        user_input='reset the container-tools module',
        args={'operation': 'reset', 'module': 'container-tools'},
        answer='Resetting module: container-tools\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0050',
        tool='dnf_modules',
        operation='reset',
        complexity='single',
        user_input='Put the go-toolset module back to its default so we can start clean.',
        args={'operation': 'reset', 'module': 'go-toolset'},
        answer='Resetting module: go-toolset\nTransaction Summary\nComplete!',
    ),
    V2(
        id='dnf_modules-reset-v2-0051',
        tool='dnf_modules',
        operation='reset',
        complexity='diagnostic',
        user_input='The virt module is reporting an inconsistent stream after a botched enable — reset it to clear that up.',
        args={'operation': 'reset', 'module': 'virt'},
        answer='Resetting module: virt\nTransaction Summary\nComplete!',
    ),
]

from finetune.scenarios_v2 import check_module; check_module('dnf_modules', SCENARIOS_V2)
