"""finetune/scenarios_v2/fapolicyd.py — corpus v2 scenarios for 'fapolicyd'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="fapolicyd-status-v2-0001", tool="fapolicyd", operation="status",
       complexity="single",
       user_input="Is the file access policy enforcement daemon currently loaded and enforcing?",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nEnforcing mode: enabled\nRules loaded: 214"),
    V2(id="fapolicyd-status-v2-0002", tool="fapolicyd", operation="status",
       complexity="diagnostic",
       user_input="A cron job on host web03 keeps getting permission denied when it tries to exec a script. Could the policy daemon be the culprit?",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nEnforcing mode: enabled\nDenials in last hour: 3"),
    V2(id="fapolicyd-status-v2-0003", tool="fapolicyd", operation="status",
       complexity="single",
       user_input="what's fapolicyd doing right now, is it dead or alive",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nPID 1142, uptime 4d 6h"),
    V2(id="fapolicyd-status-v2-0004", tool="fapolicyd", operation="status",
       complexity="diagnostic",
       user_input="Auditors want to confirm the mandatory access control daemon hasn't silently died since the last audit window opened.",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nEnforcing mode: enabled\nNo restarts since boot."),
    V2(id="fapolicyd-status-v2-0005", tool="fapolicyd", operation="status",
       complexity="multi",
       user_input="Check whether fapolicyd is up, and if it's running go ahead and dump the rule list too.",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nEnforcing mode: enabled\nRules loaded: 198"),
    V2(id="fapolicyd-status-v2-0006", tool="fapolicyd", operation="status",
       complexity="single",
       user_input="Confirm the fapolicyd daemon is enforcing before we roll the new build image out to the fleet.",
       args={"operation": "status"},
       answer="fapolicyd.service - active (running)\nEnforcing mode: enabled\nRules loaded: 220"),

    V2(id="fapolicyd-list_rules-v2-0001", tool="fapolicyd", operation="list_rules",
       complexity="single",
       user_input="Print the full fapolicyd rule set that's currently loaded.",
       args={"operation": "list_rules"},
       answer="allow perm=execute path=/usr/local/bin/deploy-script\ndeny perm=execute path=/tmp/*\n212 rules total"),
    V2(id="fapolicyd-list_rules-v2-0002", tool="fapolicyd", operation="list_rules",
       complexity="diagnostic",
       user_input="/usr/bin/ansible-playbook just started getting blocked on node04 out of nowhere — what does the current rule set say about it?",
       args={"operation": "list_rules"},
       answer="deny perm=execute path=/usr/bin/ansible-playbook\n213 rules total\nMatching deny entry found."),
    V2(id="fapolicyd-list_rules-v2-0003", tool="fapolicyd", operation="list_rules",
       complexity="single",
       user_input="what rules are loaded in fapolicyd?",
       args={"operation": "list_rules"},
       answer="allow perm=any path=/opt/vendor/bin/*\n204 rules total"),
    V2(id="fapolicyd-list_rules-v2-0004", tool="fapolicyd", operation="list_rules",
       complexity="multi",
       user_input="Show me the current rules, then I'll tell you which path to allow next.",
       args={"operation": "list_rules"},
       answer="allow perm=execute path=/usr/local/bin/*\n199 rules total"),
    V2(id="fapolicyd-list_rules-v2-0005", tool="fapolicyd", operation="list_rules",
       complexity="single",
       user_input="I need to see the loaded fapolicyd policy before we roll out the trust list change on host db02.",
       args={"operation": "list_rules"},
       answer="deny perm=execute path=/srv/uploads/*\n216 rules total"),
    V2(id="fapolicyd-list_rules-v2-0006", tool="fapolicyd", operation="list_rules",
       complexity="diagnostic",
       user_input="Something on this box is silently killing every script under /opt/monitoring — check the loaded rules for anything matching that path.",
       args={"operation": "list_rules"},
       answer="deny perm=execute path=/opt/monitoring/*\n209 rules total\nMatching deny entry found."),
    V2(id="fapolicyd-list_rules-v2-0007", tool="fapolicyd", operation="list_rules",
       complexity="single",
       user_input="Dump the fapolicyd rule table for the compliance review packet.",
       args={"operation": "list_rules"},
       answer="allow perm=execute path=/usr/libexec/platform-python\n211 rules total"),

    V2(id="fapolicyd-allow-v2-0001", tool="fapolicyd", operation="allow",
       complexity="single",
       user_input="Add an allow entry for /opt/vendor/bin/agentless-collector.",
       args={"operation": "allow", "path": "/opt/vendor/bin/agentless-collector"},
       answer="Allow rule added for /opt/vendor/bin/agentless-collector.\nRule not yet active — reload required."),
    V2(id="fapolicyd-allow-v2-0002", tool="fapolicyd", operation="allow",
       complexity="diagnostic",
       user_input="/usr/local/bin/backup-runner just got denied on node07 during the nightly job. It needs to be allowed.",
       args={"operation": "allow", "path": "/usr/local/bin/backup-runner"},
       answer="Allow rule added for /usr/local/bin/backup-runner.\nRule not yet active — reload required."),
    V2(id="fapolicyd-allow-v2-0003", tool="fapolicyd", operation="allow",
       complexity="multi",
       user_input="Whitelist /usr/share/nginx/bin/healthcheck and then reload the policy so it takes effect.",
       args={"operation": "allow", "path": "/usr/share/nginx/bin/healthcheck"},
       answer="Allow rule added for /usr/share/nginx/bin/healthcheck.\nRule not yet active — reload required."),
    V2(id="fapolicyd-allow-v2-0004", tool="fapolicyd", operation="allow",
       complexity="single",
       user_input="permit /opt/etl/bin/loader to run please",
       args={"operation": "allow", "path": "/opt/etl/bin/loader"},
       answer="Allow rule added for /opt/etl/bin/loader.\nRule not yet active — reload required."),
    V2(id="fapolicyd-allow-v2-0005", tool="fapolicyd", operation="allow",
       complexity="single",
       user_input="Create a fapolicyd allow rule for /home/svc-jenkins/bin/ci-launcher.",
       args={"operation": "allow", "path": "/home/svc-jenkins/bin/ci-launcher"},
       answer="Allow rule added for /home/svc-jenkins/bin/ci-launcher.\nRule not yet active — reload required."),
    V2(id="fapolicyd-allow-v2-0006", tool="fapolicyd", operation="allow",
       complexity="multi",
       user_input="Add /usr/local/sbin/renew-cert to the allow list and confirm it shows up when you list the rules.",
       args={"operation": "allow", "path": "/usr/local/sbin/renew-cert"},
       answer="Allow rule added for /usr/local/sbin/renew-cert.\nRule not yet active — reload required."),

    V2(id="fapolicyd-deny-v2-0001", tool="fapolicyd", operation="deny",
       complexity="single",
       user_input="Block /var/tmp/dropper from ever executing.",
       args={"operation": "deny", "path": "/var/tmp/dropper"},
       answer="Deny rule added for /var/tmp/dropper.\nRule not yet active — reload required."),
    V2(id="fapolicyd-deny-v2-0002", tool="fapolicyd", operation="deny",
       complexity="diagnostic",
       user_input="EDR flagged an unsigned binary at /home/svc-web/.cache/miner running under the web service account. It needs to be blocked immediately.",
       args={"operation": "deny", "path": "/home/svc-web/.cache/miner"},
       answer="Deny rule added for /home/svc-web/.cache/miner.\nRule not yet active — reload required."),
    V2(id="fapolicyd-deny-v2-0003", tool="fapolicyd", operation="deny",
       complexity="multi",
       user_input="Deny /opt/legacy-app/run and reload fapolicyd right after.",
       args={"operation": "deny", "path": "/opt/legacy-app/run"},
       answer="Deny rule added for /opt/legacy-app/run.\nRule not yet active — reload required."),
    V2(id="fapolicyd-deny-v2-0004", tool="fapolicyd", operation="deny",
       complexity="single",
       user_input="block execution of /srv/uploads/invoice.exe, the security scan flagged it as malicious",
       args={"operation": "deny", "path": "/srv/uploads/invoice.exe"},
       answer="Deny rule added for /srv/uploads/invoice.exe.\nRule not yet active — reload required."),
    V2(id="fapolicyd-deny-v2-0005", tool="fapolicyd", operation="deny",
       complexity="single",
       user_input="Add a deny entry for /opt/downloaded/setup.sh before anyone runs it.",
       args={"operation": "deny", "path": "/opt/downloaded/setup.sh"},
       answer="Deny rule added for /opt/downloaded/setup.sh.\nRule not yet active — reload required."),
    V2(id="fapolicyd-deny-v2-0006", tool="fapolicyd", operation="deny",
       complexity="multi",
       user_input="Deny /usr/local/lib/badhook.so and then show me the rule list so I can confirm it landed.",
       args={"operation": "deny", "path": "/usr/local/lib/badhook.so"},
       answer="Deny rule added for /usr/local/lib/badhook.so.\nRule not yet active — reload required."),

    V2(id="fapolicyd-update-v2-0001", tool="fapolicyd", operation="update",
       complexity="single",
       user_input="Tell fapolicyd to reload its rule set.",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded."),
    V2(id="fapolicyd-update-v2-0002", tool="fapolicyd", operation="update",
       complexity="diagnostic",
       user_input="I edited the fapolicyd rules file an hour ago on host app02 but the new binary is still being blocked — has the config actually been picked up?",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded, timestamp refreshed."),
    V2(id="fapolicyd-update-v2-0003", tool="fapolicyd", operation="update",
       complexity="multi",
       user_input="Refresh the fapolicyd config now, then we'll add the allow rule for /opt/app/bin/worker.",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded."),
    V2(id="fapolicyd-update-v2-0004", tool="fapolicyd", operation="update",
       complexity="single",
       user_input="refresh the file access policy database",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded."),
    V2(id="fapolicyd-update-v2-0005", tool="fapolicyd", operation="update",
       complexity="single",
       user_input="A new package landed on node11 but fapolicyd is still denying its binaries — force it to re-read the rule file.",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded."),
    V2(id="fapolicyd-update-v2-0006", tool="fapolicyd", operation="update",
       complexity="multi",
       user_input="Reload the fapolicyd policy and then list the rules to prove the change is in effect.",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded."),
    V2(id="fapolicyd-update-v2-0007", tool="fapolicyd", operation="update",
       complexity="diagnostic",
       user_input="Deploy pipeline says it applied a new fapolicyd deny rule twenty minutes ago but the target binary still runs fine — was the reload ever triggered?",
       args={"operation": "update"},
       answer="fapolicyd-cli --update: notified daemon.\nRules reloaded, timestamp refreshed."),
]

from finetune.scenarios_v2 import check_module; check_module("fapolicyd", SCENARIOS_V2)
