"""finetune/scenarios_v2/files.py — corpus v2 scenarios for 'files'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id='files-list-v2-0010', tool='files', operation='list',
       complexity='single',
       user_input="show me what's under /etc/audit",
       args={'operation': 'list', 'path': '/etc/audit'},
       answer='total 12\ndrwxr-xr-x rules.d\n-rw-r----- auditd.conf\n-rw-r----- audit.rules'),
    V2(id='files-list-v2-0011', tool='files', operation='list',
       complexity='single',
       user_input='list the contents of /opt/myapp/releases',
       args={'operation': 'list', 'path': '/opt/myapp/releases'},
       answer='total 3 entries\ndrwxr-xr-x 2026.09.01\ndrwxr-xr-x 2026.09.08\ndrwxr-xr-x 2026.09.12'),
    V2(id='files-list-v2-0012', tool='files', operation='list',
       complexity='diagnostic',
       user_input="disk usage jumped overnight on /var/spool — what's actually sitting in there?",
       args={'operation': 'list', 'path': '/var/spool'},
       answer='total 4 entries\ndrwx------ mail\ndrwx------ cron\ndrwxr-xr-x postfix\ndrwxr-xr-x anacron'),
    V2(id='files-list-v2-0013', tool='files', operation='list',
       complexity='single',
       user_input='list /etc/sssd so I can see what config files exist',
       args={'operation': 'list', 'path': '/etc/sssd'},
       answer='total 2 entries\ndrwx------ conf.d\n-rw------- sssd.conf'),
    V2(id='files-list-v2-0014', tool='files', operation='list',
       complexity='single',
       user_input="what's in /home/svc-backup right now?",
       args={'operation': 'list', 'path': '/home/svc-backup'},
       answer='total 3 entries\n-rw------- .bash_history\ndrwx------ .ssh\n-rw-r--r-- backup.log'),
    V2(id='files-list-v2-0015', tool='files', operation='list',
       complexity='diagnostic',
       user_input="the nginx reload failed complaining about a missing include, what's actually in /etc/nginx/conf.d?",
       args={'operation': 'list', 'path': '/etc/nginx/conf.d'},
       answer='total 2 entries\n-rw-r--r-- default.conf\n-rw-r--r-- ssl.conf'),
    V2(id='files-list-v2-0016', tool='files', operation='list',
       complexity='single',
       user_input='list /var/lib/mysql for me',
       args={'operation': 'list', 'path': '/var/lib/mysql'},
       answer='total 5 entries\ndrwxr-x--- appdb\n-rw-rw---- ibdata1\n-rw-rw---- ib_logfile0'),
    V2(id='files-list-v2-0017', tool='files', operation='list',
       complexity='single',
       user_input='show the contents of /root',
       args={'operation': 'list', 'path': '/root'},
       answer='total 6 entries\n-rw------- .bash_history\ndrwx------ .ssh\n-rwx------ deploy.sh'),
    V2(id='files-list-v2-0018', tool='files', operation='list',
       complexity='multi',
       user_input='list /etc/cron.d and then read whichever file looks like the backup job',
       args={'operation': 'list', 'path': '/etc/cron.d'},
       answer='total 2 entries\n-rw-r--r-- nightly-backup\n-rw-r--r-- logrotate-extra'),
    V2(id='files-read-v2-0019', tool='files', operation='read',
       complexity='single',
       user_input='show me /etc/audit/auditd.conf',
       args={'operation': 'read', 'path': '/etc/audit/auditd.conf'},
       answer='log_file = /var/log/audit/audit.log\nmax_log_file = 50\nspace_left_action = email'),
    V2(id='files-read-v2-0020', tool='files', operation='read',
       complexity='single',
       user_input='cat /etc/sssd/sssd.conf for me',
       args={'operation': 'read', 'path': '/etc/sssd/sssd.conf'},
       answer='[sssd]\nservices = nss, pam\ndomains = corp.example.com'),
    V2(id='files-read-v2-0021', tool='files', operation='read',
       complexity='diagnostic',
       user_input="httpd won't start, can you read /etc/httpd/conf/httpd.conf to check the Listen directive?",
       args={'operation': 'read', 'path': '/etc/httpd/conf/httpd.conf', 'lines': 50},
       answer='Listen 80\nServerRoot "/etc/httpd"\nDocumentRoot "/var/www/html"'),
    V2(id='files-read-v2-0022', tool='files', operation='read',
       complexity='single',
       user_input='read /etc/nsswitch.conf',
       args={'operation': 'read', 'path': '/etc/nsswitch.conf'},
       answer='passwd: sss files\nshadow: files sss\ngroup: sss files'),
    V2(id='files-read-v2-0023', tool='files', operation='read',
       complexity='single',
       user_input='show me the first 20 lines of /var/log/secure',
       args={'operation': 'read', 'path': '/var/log/secure', 'lines': 20},
       answer='Sep 12 06:00:01 host sshd[1122]: Accepted publickey for deploy\nSep 12 06:01:44 host sudo: user01 : COMMAND=/bin/systemctl restart nginx'),
    V2(id='files-read-v2-0024', tool='files', operation='read',
       complexity='diagnostic',
       user_input='the cron job seems to have the wrong schedule, read /etc/cron.d/nightly-backup to check',
       args={'operation': 'read', 'path': '/etc/cron.d/nightly-backup'},
       answer='0 2 * * * root /opt/scripts/backup.sh'),
    V2(id='files-read-v2-0025', tool='files', operation='read',
       complexity='single',
       user_input='read /etc/resolv.conf',
       args={'operation': 'read', 'path': '/etc/resolv.conf'},
       answer='nameserver 10.0.0.2\nnameserver 8.8.8.8'),
    V2(id='files-read-v2-0026', tool='files', operation='read',
       complexity='single',
       user_input='show the contents of /proc/meminfo',
       args={'operation': 'read', 'path': '/proc/meminfo', 'lines': 30},
       answer='MemTotal: 16374528 kB\nMemFree: 2210344 kB\nSwapTotal: 4194300 kB'),
    V2(id='files-read-v2-0027', tool='files', operation='read',
       complexity='multi',
       user_input='read /etc/hosts and then check if db01 is listed',
       args={'operation': 'read', 'path': '/etc/hosts'},
       answer='127.0.0.1 localhost\n10.0.4.10 db01\n10.0.4.11 db02'),
    V2(id='files-stat-v2-0028', tool='files', operation='stat',
       complexity='single',
       user_input='what are the permissions on /etc/sssd/sssd.conf?',
       args={'operation': 'stat', 'path': '/etc/sssd/sssd.conf'},
       answer='0600 root:root, size 842B, modified 2026-08-30 11:02'),
    V2(id='files-stat-v2-0029', tool='files', operation='stat',
       complexity='diagnostic',
       user_input='was /etc/audit/audit.rules changed recently, when was it last touched?',
       args={'operation': 'stat', 'path': '/etc/audit/audit.rules'},
       answer='0640 root:root, size 1204B, modified 2026-09-11 22:14'),
    V2(id='files-stat-v2-0030', tool='files', operation='stat',
       complexity='single',
       user_input='give me the stat on /var/log/audit/audit.log',
       args={'operation': 'stat', 'path': '/var/log/audit/audit.log'},
       answer='0600 root:root, size 48213304B, modified 2026-09-12 09:00'),
    V2(id='files-stat-v2-0031', tool='files', operation='stat',
       complexity='single',
       user_input='check the metadata on /etc/nftables.conf',
       args={'operation': 'stat', 'path': '/etc/nftables.conf'},
       answer='0644 root:root, size 2091B, modified 2026-07-19 08:41'),
    V2(id='files-stat-v2-0032', tool='files', operation='stat',
       complexity='diagnostic',
       user_input='is /usr/bin/passwd still setuid root or did something strip it?',
       args={'operation': 'stat', 'path': '/usr/bin/passwd'},
       answer='-rwsr-xr-x root:root, size 34832B'),
    V2(id='files-stat-v2-0033', tool='files', operation='stat',
       complexity='single',
       user_input='stat /opt/myapp/releases/current',
       args={'operation': 'stat', 'path': '/opt/myapp/releases/current'},
       answer='lrwxrwxrwx root:root -> 2026.09.12'),
    V2(id='files-stat-v2-0034', tool='files', operation='stat',
       complexity='single',
       user_input='when was /etc/network-scripts/ifcfg-ens192 last modified?',
       args={'operation': 'stat', 'path': '/etc/network-scripts/ifcfg-ens192'},
       answer='0644 root:root, modified 2026-09-01 14:22'),
    V2(id='files-stat-v2-0035', tool='files', operation='stat',
       complexity='diagnostic',
       user_input='permissions drift check — what does /etc/shadow look like right now?',
       args={'operation': 'stat', 'path': '/etc/shadow'},
       answer='0000 root:root, size 1621B, modified 2026-08-14 03:01'),
    V2(id='files-stat-v2-0036', tool='files', operation='stat',
       complexity='single',
       user_input='give me the file info for /var/lib/pgsql/data/pg_hba.conf',
       args={'operation': 'stat', 'path': '/var/lib/pgsql/data/pg_hba.conf'},
       answer='0600 postgres:postgres, size 4513B, modified 2026-06-02 10:00'),
    V2(id='files-stat-v2-0037', tool='files', operation='stat',
       complexity='single',
       user_input='check the metadata on /etc/pam.d/sshd',
       args={'operation': 'stat', 'path': '/etc/pam.d/sshd'},
       answer='0644 root:root, size 601B, modified 2026-05-11 09:30'),
    V2(id='files-stat-v2-0038', tool='files', operation='stat',
       complexity='diagnostic',
       user_input="we're auditing world-readable secrets, what mode is /etc/mysql/debian.cnf sitting at?",
       args={'operation': 'stat', 'path': '/etc/mysql/debian.cnf'},
       answer='0600 root:root, size 331B, modified 2026-03-20 12:00'),
    V2(id='files-find-v2-0039', tool='files', operation='find',
       complexity='single',
       user_input='find every .repo file under /etc/yum.repos.d',
       args={'operation': 'find', 'path': '/etc/yum.repos.d', 'name': '*.repo'},
       answer='3 matches: rocky.repo, epel.repo, appstream.repo'),
    V2(id='files-find-v2-0040', tool='files', operation='find',
       complexity='single',
       user_input='search for .rules files under /etc/audit',
       args={'operation': 'find', 'path': '/etc/audit', 'name': '*.rules'},
       answer='2 matches: rules.d/audit.rules, rules.d/10-base-config.rules'),
    V2(id='files-find-v2-0041', tool='files', operation='find',
       complexity='diagnostic',
       user_input='are there any leftover .rpmnew files anywhere under /etc?',
       args={'operation': 'find', 'path': '/etc', 'name': '.rpmnew'},
       answer='1 match: /etc/ssh/sshd_config.rpmnew'),
    V2(id='files-find-v2-0042', tool='files', operation='find',
       complexity='single',
       user_input='find directories under /srv with maxdepth 1',
       args={'operation': 'find', 'path': '/srv', 'type': 'd', 'maxdepth': 1},
       answer='3 matches: /srv/www, /srv/ftp, /srv/backups'),
    V2(id='files-find-v2-0043', tool='files', operation='find',
       complexity='single',
       user_input='look for any .sock files under /var/run',
       args={'operation': 'find', 'path': '/var/run', 'name': '*.sock', 'type': 'f'},
       answer='5 matches including docker.sock, mysqld.sock'),
    V2(id='files-find-v2-0044', tool='files', operation='find',
       complexity='diagnostic',
       user_input='hunting for stray core dump files, check under /var/crash and /tmp',
       args={'operation': 'find', 'path': '/var/crash', 'name': 'core.*', 'type': 'f'},
       answer='0 matches under /var/crash'),
    V2(id='files-find-v2-0045', tool='files', operation='find',
       complexity='single',
       user_input='find all files named authorized_keys under /home',
       args={'operation': 'find', 'path': '/home', 'name': 'authorized_keys', 'type': 'f'},
       answer='2 matches: /home/deploy/.ssh/authorized_keys, /home/alice/.ssh/authorized_keys'),
    V2(id='files-find-v2-0046', tool='files', operation='find',
       complexity='single',
       user_input='search for world-writable files under /var/www',
       args={'operation': 'find', 'path': '/var/www', 'type': 'f'},
       answer='0 world-writable files found under /var/www'),
    V2(id='files-find-v2-0047', tool='files', operation='find',
       complexity='multi',
       user_input='find all .conf files under /etc/httpd and then read the first one',
       args={'operation': 'find', 'path': '/etc/httpd', 'name': '*.conf', 'type': 'f'},
       answer='4 matches: conf/httpd.conf, conf.d/ssl.conf, conf.d/welcome.conf, conf.modules.d/00-base.conf'),
    V2(id='files-copy-v2-0048', tool='files', operation='copy',
       complexity='single',
       user_input='copy /etc/sssd/sssd.conf to /etc/sssd/sssd.conf.bak',
       args={'operation': 'copy', 'src': '/etc/sssd/sssd.conf', 'dst': '/etc/sssd/sssd.conf.bak'},
       answer='copied /etc/sssd/sssd.conf -> /etc/sssd/sssd.conf.bak'),
    V2(id='files-copy-v2-0049', tool='files', operation='copy',
       complexity='single',
       user_input='back up /etc/audit/audit.rules to /root/audit.rules.bak',
       args={'operation': 'copy', 'src': '/etc/audit/audit.rules', 'dst': '/root/audit.rules.bak'},
       answer='copied /etc/audit/audit.rules -> /root/audit.rules.bak'),
    V2(id='files-copy-v2-0050', tool='files', operation='copy',
       complexity='diagnostic',
       user_input='before I touch /etc/httpd/conf/httpd.conf, make a safety copy at /root/httpd.conf.orig',
       args={'operation': 'copy', 'src': '/etc/httpd/conf/httpd.conf', 'dst': '/root/httpd.conf.orig'},
       answer='copied /etc/httpd/conf/httpd.conf -> /root/httpd.conf.orig'),
    V2(id='files-copy-v2-0051', tool='files', operation='copy',
       complexity='single',
       user_input='copy the whole /etc/nftables directory to /tmp/nft-backup recursively',
       args={'operation': 'copy', 'src': '/etc/nftables', 'dst': '/tmp/nft-backup', 'recursive': True},
       answer='copied /etc/nftables -> /tmp/nft-backup (recursive, 4 files)'),
    V2(id='files-copy-v2-0052', tool='files', operation='copy',
       complexity='single',
       user_input='copy /var/lib/pgsql/data/postgresql.conf to /root/postgresql.conf.bak',
       args={'operation': 'copy', 'src': '/var/lib/pgsql/data/postgresql.conf', 'dst': '/root/postgresql.conf.bak'},
       answer='copied /var/lib/pgsql/data/postgresql.conf -> /root/postgresql.conf.bak'),
    V2(id='files-copy-v2-0053', tool='files', operation='copy',
       complexity='multi',
       user_input='copy /etc/resolv.conf to /etc/resolv.conf.orig and then read the copy to confirm it matches',
       args={'operation': 'copy', 'src': '/etc/resolv.conf', 'dst': '/etc/resolv.conf.orig'},
       answer='copied /etc/resolv.conf -> /etc/resolv.conf.orig'),
    V2(id='files-copy-v2-0054', tool='files', operation='copy',
       complexity='single',
       user_input='duplicate /opt/app/config.ini to /opt/app/config.ini.20260912',
       args={'operation': 'copy', 'src': '/opt/app/config.ini', 'dst': '/opt/app/config.ini.20260912'},
       answer='copied /opt/app/config.ini -> /opt/app/config.ini.20260912'),
    V2(id='files-copy-v2-0055', tool='files', operation='copy',
       complexity='single',
       user_input='copy /etc/cron.d/nightly-backup to /root/nightly-backup.snapshot',
       args={'operation': 'copy', 'src': '/etc/cron.d/nightly-backup', 'dst': '/root/nightly-backup.snapshot'},
       answer='copied /etc/cron.d/nightly-backup -> /root/nightly-backup.snapshot'),
    V2(id='files-copy-v2-0056', tool='files', operation='copy',
       complexity='diagnostic',
       user_input="we're about to run realm_leave, snapshot /etc/sssd first to /root/sssd-snapshot recursively just in case",
       args={'operation': 'copy', 'src': '/etc/sssd', 'dst': '/root/sssd-snapshot', 'recursive': True},
       answer='copied /etc/sssd -> /root/sssd-snapshot (recursive, 3 files)'),
    V2(id='files-copy-v2-0057', tool='files', operation='copy',
       complexity='single',
       user_input='copy /etc/samba/smb.conf to /etc/samba/smb.conf.bak',
       args={'operation': 'copy', 'src': '/etc/samba/smb.conf', 'dst': '/etc/samba/smb.conf.bak'},
       answer='copied /etc/samba/smb.conf -> /etc/samba/smb.conf.bak'),
    V2(id='files-move-v2-0058', tool='files', operation='move',
       complexity='single',
       user_input='rename /etc/nginx/conf.d/default.conf to /etc/nginx/conf.d/default.conf.disabled',
       args={'operation': 'move', 'src': '/etc/nginx/conf.d/default.conf', 'dst': '/etc/nginx/conf.d/default.conf.disabled'},
       answer='moved /etc/nginx/conf.d/default.conf -> /etc/nginx/conf.d/default.conf.disabled'),
    V2(id='files-move-v2-0059', tool='files', operation='move',
       complexity='single',
       user_input='move /tmp/new-sssd.conf into place at /etc/sssd/sssd.conf',
       args={'operation': 'move', 'src': '/tmp/new-sssd.conf', 'dst': '/etc/sssd/sssd.conf'},
       answer='moved /tmp/new-sssd.conf -> /etc/sssd/sssd.conf'),
    V2(id='files-move-v2-0060', tool='files', operation='move',
       complexity='diagnostic',
       user_input='the stale pid file at /var/run/httpd.pid is blocking startup, move it out of the way',
       args={'operation': 'move', 'src': '/var/run/httpd.pid', 'dst': '/var/run/httpd.pid.stale'},
       answer='moved /var/run/httpd.pid -> /var/run/httpd.pid.stale'),
    V2(id='files-move-v2-0061', tool='files', operation='move',
       complexity='single',
       user_input='move /root/setup.sh to /root/setup.sh.done to mark it complete',
       args={'operation': 'move', 'src': '/root/setup.sh', 'dst': '/root/setup.sh.done'},
       answer='moved /root/setup.sh -> /root/setup.sh.done'),
    V2(id='files-move-v2-0062', tool='files', operation='move',
       complexity='single',
       user_input='relocate /var/log/old-archive to /data/log-archive',
       args={'operation': 'move', 'src': '/var/log/old-archive', 'dst': '/data/log-archive'},
       answer='moved /var/log/old-archive -> /data/log-archive'),
    V2(id='files-move-v2-0063', tool='files', operation='move',
       complexity='multi',
       user_input='move /etc/audit/rules.d/staging.rules to /etc/audit/rules.d/10-staging.rules and then list the rules.d directory',
       args={'operation': 'move', 'src': '/etc/audit/rules.d/staging.rules', 'dst': '/etc/audit/rules.d/10-staging.rules'},
       answer='moved /etc/audit/rules.d/staging.rules -> /etc/audit/rules.d/10-staging.rules'),
    V2(id='files-move-v2-0064', tool='files', operation='move',
       complexity='single',
       user_input='rename /opt/app/config.ini.new to /opt/app/config.ini',
       args={'operation': 'move', 'src': '/opt/app/config.ini.new', 'dst': '/opt/app/config.ini'},
       answer='moved /opt/app/config.ini.new -> /opt/app/config.ini'),
    V2(id='files-move-v2-0065', tool='files', operation='move',
       complexity='diagnostic',
       user_input='the old realm config at /etc/sssd/sssd.conf.old is confusing the audit — move it out to /root/sssd.conf.archived',
       args={'operation': 'move', 'src': '/etc/sssd/sssd.conf.old', 'dst': '/root/sssd.conf.archived'},
       answer='moved /etc/sssd/sssd.conf.old -> /root/sssd.conf.archived'),
    V2(id='files-move-v2-0066', tool='files', operation='move',
       complexity='single',
       user_input='move /tmp/nftables-draft.conf to /etc/nftables.conf',
       args={'operation': 'move', 'src': '/tmp/nftables-draft.conf', 'dst': '/etc/nftables.conf'},
       answer='moved /tmp/nftables-draft.conf -> /etc/nftables.conf'),
    V2(id='files-move-v2-0067', tool='files', operation='move',
       complexity='single',
       user_input='rename /var/run/app.sock.new to /var/run/app.sock',
       args={'operation': 'move', 'src': '/var/run/app.sock.new', 'dst': '/var/run/app.sock'},
       answer='moved /var/run/app.sock.new -> /var/run/app.sock'),
    V2(id='files-move-v2-0068', tool='files', operation='move',
       complexity='single',
       user_input='move /home/deploy/release.tar to /opt/releases/release.tar',
       args={'operation': 'move', 'src': '/home/deploy/release.tar', 'dst': '/opt/releases/release.tar'},
       answer='moved /home/deploy/release.tar -> /opt/releases/release.tar'),
    V2(id='files-mkdir-v2-0069', tool='files', operation='mkdir',
       complexity='single',
       user_input='create the directory /etc/sssd/conf.d',
       args={'operation': 'mkdir', 'path': '/etc/sssd/conf.d'},
       answer='created /etc/sssd/conf.d'),
    V2(id='files-mkdir-v2-0070', tool='files', operation='mkdir',
       complexity='single',
       user_input='make /var/log/audit/archive and any missing parents',
       args={'operation': 'mkdir', 'path': '/var/log/audit/archive', 'parents': True},
       answer='created /var/log/audit/archive (with parents)'),
    V2(id='files-mkdir-v2-0071', tool='files', operation='mkdir',
       complexity='diagnostic',
       user_input="httpd is failing because /run/httpd/tmp doesn't exist, create it",
       args={'operation': 'mkdir', 'path': '/run/httpd/tmp', 'parents': True},
       answer='created /run/httpd/tmp (with parents)'),
    V2(id='files-mkdir-v2-0072', tool='files', operation='mkdir',
       complexity='single',
       user_input='set up /opt/backups/2026-09',
       args={'operation': 'mkdir', 'path': '/opt/backups/2026-09'},
       answer='created /opt/backups/2026-09'),
    V2(id='files-mkdir-v2-0073', tool='files', operation='mkdir',
       complexity='single',
       user_input='create /etc/nftables.d for our new rule fragments',
       args={'operation': 'mkdir', 'path': '/etc/nftables.d'},
       answer='created /etc/nftables.d'),
    V2(id='files-mkdir-v2-0074', tool='files', operation='mkdir',
       complexity='multi',
       user_input='create /data/postgres/wal_archive and then chown it to postgres:postgres',
       args={'operation': 'mkdir', 'path': '/data/postgres/wal_archive', 'parents': True},
       answer='created /data/postgres/wal_archive (with parents)'),
    V2(id='files-mkdir-v2-0075', tool='files', operation='mkdir',
       complexity='single',
       user_input='make the directory /srv/app/releases/2026.09.12',
       args={'operation': 'mkdir', 'path': '/srv/app/releases/2026.09.12', 'parents': True},
       answer='created /srv/app/releases/2026.09.12 (with parents)'),
    V2(id='files-mkdir-v2-0076', tool='files', operation='mkdir',
       complexity='single',
       user_input='create /var/spool/custom-cron',
       args={'operation': 'mkdir', 'path': '/var/spool/custom-cron'},
       answer='created /var/spool/custom-cron'),
    V2(id='files-mkdir-v2-0077', tool='files', operation='mkdir',
       complexity='diagnostic',
       user_input="the deployment script expects /opt/myapp/logs to already exist, it doesn't — create it",
       args={'operation': 'mkdir', 'path': '/opt/myapp/logs'},
       answer='created /opt/myapp/logs'),
    V2(id='files-mkdir-v2-0078', tool='files', operation='mkdir',
       complexity='single',
       user_input='mkdir /home/svc-backup/.ssh with parents',
       args={'operation': 'mkdir', 'path': '/home/svc-backup/.ssh', 'parents': True},
       answer='created /home/svc-backup/.ssh (with parents)'),
    V2(id='files-mkdir-v2-0079', tool='files', operation='mkdir',
       complexity='single',
       user_input='create /mnt/nfs-share/exports',
       args={'operation': 'mkdir', 'path': '/mnt/nfs-share/exports'},
       answer='created /mnt/nfs-share/exports'),
    V2(id='files-chmod-v2-0080', tool='files', operation='chmod',
       complexity='single',
       user_input='make /usr/local/bin/rotate-logs.sh executable',
       args={'operation': 'chmod', 'mode': '755', 'path': '/usr/local/bin/rotate-logs.sh'},
       answer='chmod 755 /usr/local/bin/rotate-logs.sh'),
    V2(id='files-chmod-v2-0081', tool='files', operation='chmod',
       complexity='single',
       user_input='set /etc/sssd/sssd.conf to 600, sssd refuses to start otherwise',
       args={'operation': 'chmod', 'mode': '600', 'path': '/etc/sssd/sssd.conf'},
       answer='chmod 600 /etc/sssd/sssd.conf'),
    V2(id='files-chmod-v2-0082', tool='files', operation='chmod',
       complexity='diagnostic',
       user_input="httpd can't read /var/www/html/index.html, permissions look off",
       args={'operation': 'chmod', 'mode': '644', 'path': '/var/www/html/index.html'},
       answer='chmod 644 /var/www/html/index.html'),
    V2(id='files-chmod-v2-0083', tool='files', operation='chmod',
       complexity='single',
       user_input='chmod 750 on /var/log/audit',
       args={'operation': 'chmod', 'mode': '750', 'path': '/var/log/audit'},
       answer='chmod 750 /var/log/audit'),
    V2(id='files-chmod-v2-0084', tool='files', operation='chmod',
       complexity='single',
       user_input='strip world-write from /tmp/shared-uploads, set it to 1775',
       args={'operation': 'chmod', 'mode': '1775', 'path': '/tmp/shared-uploads'},
       answer='chmod 1775 /tmp/shared-uploads'),
    V2(id='files-chmod-v2-0085', tool='files', operation='chmod',
       complexity='multi',
       user_input='recursively set /opt/app to 755 and then verify with a stat on the top-level dir',
       args={'operation': 'chmod', 'mode': '755', 'path': '/opt/app', 'recursive': True},
       answer='chmod 755 /opt/app (recursive)'),
    V2(id='files-chmod-v2-0086', tool='files', operation='chmod',
       complexity='single',
       user_input="the cron script at /etc/cron.daily/cleanup isn't running, add execute bit",
       args={'operation': 'chmod', 'mode': 'u+x', 'path': '/etc/cron.daily/cleanup'},
       answer='chmod u+x /etc/cron.daily/cleanup'),
    V2(id='files-chmod-v2-0087', tool='files', operation='chmod',
       complexity='single',
       user_input='set /etc/audit/audit.rules to mode 640',
       args={'operation': 'chmod', 'mode': '640', 'path': '/etc/audit/audit.rules'},
       answer='chmod 640 /etc/audit/audit.rules'),
    V2(id='files-chmod-v2-0088', tool='files', operation='chmod',
       complexity='diagnostic',
       user_input='the private key at /home/deploy/.ssh/id_rsa is too permissive, lock it down',
       args={'operation': 'chmod', 'mode': '600', 'path': '/home/deploy/.ssh/id_rsa'},
       answer='chmod 600 /home/deploy/.ssh/id_rsa'),
    V2(id='files-chmod-v2-0089', tool='files', operation='chmod',
       complexity='single',
       user_input='recursively chmod /var/www to 755',
       args={'operation': 'chmod', 'mode': '755', 'path': '/var/www', 'recursive': True},
       answer='chmod 755 /var/www (recursive)'),
    V2(id='files-chown-v2-0090', tool='files', operation='chown',
       complexity='single',
       user_input='change the owner of /var/lib/named to named:named',
       args={'operation': 'chown', 'owner': 'named:named', 'path': '/var/lib/named'},
       answer='chown named:named /var/lib/named'),
    V2(id='files-chown-v2-0091', tool='files', operation='chown',
       complexity='single',
       user_input='give sssd ownership of /var/lib/sss/db',
       args={'operation': 'chown', 'owner': 'sssd:sssd', 'path': '/var/lib/sss/db'},
       answer='chown sssd:sssd /var/lib/sss/db'),
    V2(id='files-chown-v2-0092', tool='files', operation='chown',
       complexity='diagnostic',
       user_input="postgres can't write to /data/pgdata, ownership looks wrong",
       args={'operation': 'chown', 'owner': 'postgres:postgres', 'path': '/data/pgdata'},
       answer='chown postgres:postgres /data/pgdata'),
    V2(id='files-chown-v2-0093', tool='files', operation='chown',
       complexity='single',
       user_input='recursively chown /opt/app to the app service account appsvc:appsvc',
       args={'operation': 'chown', 'owner': 'appsvc:appsvc', 'path': '/opt/app', 'recursive': True},
       answer='chown appsvc:appsvc /opt/app (recursive)'),
    V2(id='files-chown-v2-0094', tool='files', operation='chown',
       complexity='single',
       user_input='set /home/alice/.ssh to be owned by alice',
       args={'operation': 'chown', 'owner': 'alice', 'path': '/home/alice/.ssh'},
       answer='chown alice /home/alice/.ssh'),
    V2(id='files-chown-v2-0095', tool='files', operation='chown',
       complexity='multi',
       user_input='chown /var/www/html to nginx:nginx and then chmod it to 755',
       args={'operation': 'chown', 'owner': 'nginx:nginx', 'path': '/var/www/html'},
       answer='chown nginx:nginx /var/www/html'),
    V2(id='files-chown-v2-0096', tool='files', operation='chown',
       complexity='single',
       user_input='give httpd ownership of /etc/httpd/ssl',
       args={'operation': 'chown', 'owner': 'apache:apache', 'path': '/etc/httpd/ssl'},
       answer='chown apache:apache /etc/httpd/ssl'),
    V2(id='files-chown-v2-0097', tool='files', operation='chown',
       complexity='diagnostic',
       user_input='after restoring from backup, /var/lib/mysql is owned by root instead of mysql — fix it',
       args={'operation': 'chown', 'owner': 'mysql:mysql', 'path': '/var/lib/mysql', 'recursive': True},
       answer='chown mysql:mysql /var/lib/mysql (recursive)'),
    V2(id='files-chown-v2-0098', tool='files', operation='chown',
       complexity='single',
       user_input='recursively chown /srv/ftp to ftpuser:ftpgroup',
       args={'operation': 'chown', 'owner': 'ftpuser:ftpgroup', 'path': '/srv/ftp', 'recursive': True},
       answer='chown ftpuser:ftpgroup /srv/ftp (recursive)'),
    V2(id='files-chown-v2-0099', tool='files', operation='chown',
       complexity='single',
       user_input='set /var/spool/cron to owned by root:crontab',
       args={'operation': 'chown', 'owner': 'root:crontab', 'path': '/var/spool/cron'},
       answer='chown root:crontab /var/spool/cron'),
    V2(id='files-chown-v2-0100', tool='files', operation='chown',
       complexity='single',
       user_input='change owner of /opt/backups to backupsvc',
       args={'operation': 'chown', 'owner': 'backupsvc', 'path': '/opt/backups'},
       answer='chown backupsvc /opt/backups'),
    V2(id='files-write-v2-0101', tool='files', operation='write',
       complexity='single',
       user_input="write /etc/motd with 'Authorized access only. All activity is logged.'",
       args={'operation': 'write', 'path': '/etc/motd', 'content': 'Authorized access only. All activity is logged.'},
       answer='wrote 47 bytes to /etc/motd'),
    V2(id='files-write-v2-0102', tool='files', operation='write',
       complexity='single',
       user_input='create /etc/nftables.d/10-base.conf with a default drop policy for the input chain',
       args={'operation': 'write', 'path': '/etc/nftables.d/10-base.conf', 'content': 'table inet filter {\n  chain input { type filter hook input priority 0; policy drop; }\n}'},
       answer='wrote 78 bytes to /etc/nftables.d/10-base.conf'),
    V2(id='files-write-v2-0103', tool='files', operation='write',
       complexity='diagnostic',
       user_input='/etc/resolv.conf keeps getting wiped by DHCP, rewrite it pointing at 10.0.0.2 and 1.1.1.1',
       args={'operation': 'write', 'path': '/etc/resolv.conf', 'content': 'nameserver 10.0.0.2\nnameserver 1.1.1.1'},
       answer='wrote 33 bytes to /etc/resolv.conf'),
    V2(id='files-write-v2-0104', tool='files', operation='write',
       complexity='single',
       user_input='the sssd domain block is missing, write a fresh /etc/sssd/sssd.conf for corp.example.com',
       args={'operation': 'write', 'path': '/etc/sssd/sssd.conf', 'content': '[sssd]\nservices = nss, pam\ndomains = corp.example.com\n\n[domain/corp.example.com]\nid_provider = ad'},
       answer='wrote 112 bytes to /etc/sssd/sssd.conf'),
    V2(id='files-write-v2-0105', tool='files', operation='write',
       complexity='single',
       user_input='write /etc/cron.d/nightly-audit-report with a 1am job running aureport',
       args={'operation': 'write', 'path': '/etc/cron.d/nightly-audit-report', 'content': '0 1 * * * root /usr/sbin/aureport summary > /var/log/audit-report.log'},
       answer='wrote 63 bytes to /etc/cron.d/nightly-audit-report'),
    V2(id='files-write-v2-0106', tool='files', operation='write',
       complexity='multi',
       user_input='write the new /etc/hosts entry for db03 and then read it back to confirm',
       args={'operation': 'write', 'path': '/etc/hosts', 'content': '127.0.0.1 localhost\n10.0.4.12 db03'},
       answer='wrote 33 bytes to /etc/hosts'),
    V2(id='files-write-v2-0107', tool='files', operation='write',
       complexity='single',
       user_input='create /opt/app/config.ini with the standard defaults, timeout=30 and retries=3',
       args={'operation': 'write', 'path': '/opt/app/config.ini', 'content': '[defaults]\ntimeout=30\nretries=3'},
       answer='wrote 32 bytes to /opt/app/config.ini'),
    V2(id='files-write-v2-0108', tool='files', operation='write',
       complexity='single',
       user_input='write /etc/sysctl.d/99-tuning.conf with net.core.somaxconn=4096',
       args={'operation': 'write', 'path': '/etc/sysctl.d/99-tuning.conf', 'content': 'net.core.somaxconn = 4096'},
       answer='wrote 26 bytes to /etc/sysctl.d/99-tuning.conf'),
    V2(id='files-write-v2-0109', tool='files', operation='write',
       complexity='diagnostic',
       user_input='the audit rules file got corrupted, rewrite /etc/audit/rules.d/base.rules with the exec_watch rule',
       args={'operation': 'write', 'path': '/etc/audit/rules.d/base.rules', 'content': '-a always,exit -F arch=b64 -S execve -k exec_watch'},
       answer='wrote 55 bytes to /etc/audit/rules.d/base.rules'),
    V2(id='files-write-v2-0110', tool='files', operation='write',
       complexity='single',
       user_input='write a basic vhost to /etc/httpd/conf.d/app.conf listening on 8080',
       args={'operation': 'write', 'path': '/etc/httpd/conf.d/app.conf', 'content': '<VirtualHost *:8080>\n  DocumentRoot /var/www/app\n</VirtualHost>'},
       answer='wrote 60 bytes to /etc/httpd/conf.d/app.conf'),
    V2(id='files-remove-v2-0111', tool='files', operation='remove',
       complexity='single',
       user_input='delete the stale lock at /tmp/deploy.lock',
       args={'operation': 'remove', 'path': '/tmp/deploy.lock'},
       answer='removed /tmp/deploy.lock'),
    V2(id='files-remove-v2-0112', tool='files', operation='remove',
       complexity='single',
       user_input='remove /etc/nginx/sites-enabled/legacy-app.conf',
       args={'operation': 'remove', 'path': '/etc/nginx/sites-enabled/legacy-app.conf'},
       answer='removed /etc/nginx/sites-enabled/legacy-app.conf'),
    V2(id='files-remove-v2-0113', tool='files', operation='remove',
       complexity='diagnostic',
       user_input="there's a leftover pid file at /var/run/httpd/httpd.pid blocking startup, clear it",
       args={'operation': 'remove', 'path': '/var/run/httpd/httpd.pid'},
       answer='removed /var/run/httpd/httpd.pid'),
    V2(id='files-remove-v2-0114', tool='files', operation='remove',
       complexity='single',
       user_input='clean up the build artifacts under /tmp/build-9911 recursively',
       args={'operation': 'remove', 'path': '/tmp/build-9911', 'recursive': True},
       answer='removed /tmp/build-9911 (recursive, 214 files)'),
    V2(id='files-remove-v2-0115', tool='files', operation='remove',
       complexity='single',
       user_input='delete /root/rotated-keys.txt now that key rotation is done',
       args={'operation': 'remove', 'path': '/root/rotated-keys.txt'},
       answer='removed /root/rotated-keys.txt'),
    V2(id='files-remove-v2-0116', tool='files', operation='remove',
       complexity='multi',
       user_input='remove the old audit rule backup at /root/audit-rules-backup.txt and then list /root to confirm',
       args={'operation': 'remove', 'path': '/root/audit-rules-backup.txt'},
       answer='removed /root/audit-rules-backup.txt'),
    V2(id='files-remove-v2-0117', tool='files', operation='remove',
       complexity='single',
       user_input="force delete /var/cache/dnf/expired-metadata even if it's in use",
       args={'operation': 'remove', 'path': '/var/cache/dnf/expired-metadata', 'recursive': True, 'force': True},
       answer='removed /var/cache/dnf/expired-metadata (forced, recursive)'),
    V2(id='files-remove-v2-0118', tool='files', operation='remove',
       complexity='diagnostic',
       user_input='disk is full, is there a big leftover core dump at /var/crash/core.12044 we can clear?',
       args={'operation': 'remove', 'path': '/var/crash/core.12044'},
       answer='removed /var/crash/core.12044, freed 2.1G'),
    V2(id='files-remove-v2-0119', tool='files', operation='remove',
       complexity='single',
       user_input='remove the old backup /var/backups/db-2026-01-01.sql.gz',
       args={'operation': 'remove', 'path': '/var/backups/db-2026-01-01.sql.gz'},
       answer='removed /var/backups/db-2026-01-01.sql.gz'),
    V2(id='files-remove-v2-0120', tool='files', operation='remove',
       complexity='single',
       user_input='delete the stale sssd cache file at /var/lib/sss/db/cache_corp.example.com.ldb',
       args={'operation': 'remove', 'path': '/var/lib/sss/db/cache_corp.example.com.ldb'},
       answer='removed /var/lib/sss/db/cache_corp.example.com.ldb'),
]

from finetune.scenarios_v2 import check_module; check_module('files', SCENARIOS_V2)
