"""finetune/scenarios_v2/grub.py — corpus v2 scenarios for 'grub'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="grub-info-v2-0001", tool="grub", operation="info",
       complexity="single",
       user_input="Show me the GRUB entry details for /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64.",
       args={"operation": "info", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="index=0 title=Rocky Linux (5.14.0-427.13.1.el9_4.x86_64) 9.4 (Blue Onyx)\nkernel=/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ninitrd=/boot/initramfs-5.14.0-427.13.1.el9_4.x86_64.img\nargs=ro crashkernel=1G-4G:192M,4G-64G:256M"),
    V2(id="grub-info-v2-0002", tool="grub", operation="info",
       complexity="single",
       user_input="Dump every boot entry currently in the GRUB menu.",
       args={"operation": "info", "kernel": "ALL"},
       answer="index=0 title=Rocky Linux (5.14.0-427.13.1.el9_4.x86_64) 9.4 (Blue Onyx) [DEFAULT]\nindex=1 title=Rocky Linux (5.14.0-362.13.1.el9_3.x86_64) 9.3 (Blue Onyx)\n2 entries total."),
    V2(id="grub-info-v2-0003", tool="grub", operation="info",
       complexity="diagnostic",
       user_input="After the kernel update the box came back up but I want to double check the boot arguments actually applied — what's the entry look like now?",
       args={"operation": "info", "kernel": "ALL"},
       answer="index=0 title=Rocky Linux (5.14.0-427.13.1.el9_4.x86_64) 9.4 (Blue Onyx) [DEFAULT]\nargs=ro crashkernel=auto nvme_core.default_ps_max_latency_us=0"),
    V2(id="grub-info-v2-0004", tool="grub", operation="info",
       complexity="diagnostic",
       user_input="The host booted into single-user mode unexpectedly — can you check what args the current default entry is carrying?",
       args={"operation": "info", "kernel": "ALL"},
       answer="index=0 title=Rocky Linux (5.14.0-427.13.1.el9_4.x86_64) 9.4 (Blue Onyx) [DEFAULT]\nargs=ro systemd.unit=rescue.target crashkernel=auto"),
    V2(id="grub-info-v2-0005", tool="grub", operation="info",
       complexity="single",
       user_input="what's in the rescue kernel entry?",
       args={"operation": "info", "kernel": "/boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c"},
       answer="index=2 title=Rocky Linux (0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c) 9.4 (Blue Onyx)\nkernel=/boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c\ninitrd=/boot/initramfs-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c.img"),
    V2(id="grub-info-v2-0006", tool="grub", operation="info",
       complexity="single",
       user_input="show every entry indexed in the boot loader",
       args={"operation": "info", "kernel": "ALL"},
       answer="index=0 title=Rocky Linux (5.14.0-427.13.1.el9_4.x86_64) 9.4 (Blue Onyx) [DEFAULT]\nindex=1 title=Rocky Linux (5.14.0-362.13.1.el9_3.x86_64) 9.3 (Blue Onyx)\nindex=2 title=Rocky Linux (0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c) 9.4 (Blue Onyx)\n3 entries total."),
    V2(id="grub-info-v2-0007", tool="grub", operation="info",
       complexity="multi",
       user_input="Show the GRUB info for /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64 and then set it as the default.",
       args={"operation": "info", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"},
       answer="index=1 title=Rocky Linux (5.14.0-362.13.1.el9_3.x86_64) 9.3 (Blue Onyx)\nkernel=/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64\nargs=ro crashkernel=auto"),
    V2(id="grub-info-v2-0008", tool="grub", operation="info",
       complexity="single",
       user_input="I need the initrd path for the current running kernel entry.",
       args={"operation": "info", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="initrd=/boot/initramfs-5.14.0-427.13.1.el9_4.x86_64.img\nkernel=/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),

    V2(id="grub-default-kernel-v2-0001", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="Which kernel path will this host boot next time?",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0002", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="print the current default boot kernel",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0003", tool="grub", operation="default-kernel",
       complexity="diagnostic",
       user_input="dnf updated the kernel package two days ago but uname still shows the old version — what does GRUB think the default is?",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"),
    V2(id="grub-default-kernel-v2-0004", tool="grub", operation="default-kernel",
       complexity="diagnostic",
       user_input="Before I touch nftables on this box, I want to confirm we're not accidentally on the rescue kernel — check the default.",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0005", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="what kernel does grubby think is default",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0006", tool="grub", operation="default-kernel",
       complexity="multi",
       user_input="Check the default kernel, then set the new one as default if it isn't already.",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"),
    V2(id="grub-default-kernel-v2-0007", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="show me the kernel path that boots by default on db-node-3",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0008", tool="grub", operation="default-kernel",
       complexity="diagnostic",
       user_input="A ticket claims this host silently rolled back to an older kernel after the last reboot — verify the default entry.",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"),
    V2(id="grub-default-kernel-v2-0009", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="tell me the default boot kernel path",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),
    V2(id="grub-default-kernel-v2-0010", tool="grub", operation="default-kernel",
       complexity="single",
       user_input="Confirm the default kernel on app-node-7 before we schedule the maintenance window.",
       args={"operation": "default-kernel"},
       answer="/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"),

    V2(id="grub-set-default-v2-0001", tool="grub", operation="set-default",
       complexity="single",
       user_input="Set the default boot kernel to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64.",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0002", tool="grub", operation="set-default",
       complexity="single",
       user_input="make the newest kernel the one that boots by default",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0003", tool="grub", operation="set-default",
       complexity="diagnostic",
       user_input="This host keeps booting the old kernel after every reboot — can you point the default at the new one?",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0004", tool="grub", operation="set-default",
       complexity="single",
       user_input="roll the default back to /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0005", tool="grub", operation="set-default",
       complexity="multi",
       user_input="Set the default to the rescue kernel, then reboot the host into it.",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c"},
       answer="Default kernel set: /boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0006", tool="grub", operation="set-default",
       complexity="single",
       user_input="switch the default entry to index kernel /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0007", tool="grub", operation="set-default",
       complexity="diagnostic",
       user_input="the new patched kernel installed cleanly but a reboot last night still landed on 9.3 — set the default to the patched build",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0008", tool="grub", operation="set-default",
       complexity="single",
       user_input="Point all boot entries at the current kernel as default.",
       args={"operation": "set-default", "kernel": "ALL"},
       answer="Default kernel set for ALL entries: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0009", tool="grub", operation="set-default",
       complexity="single",
       user_input="default kernel should be /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64 going forward",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),
    V2(id="grub-set-default-v2-0010", tool="grub", operation="set-default",
       complexity="multi",
       user_input="Set /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64 as default and confirm the change stuck.",
       args={"operation": "set-default", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64"},
       answer="Default kernel set: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\ngrubby: exit code 0."),

    V2(id="grub-args-add-v2-0001", tool="grub", operation="args-add",
       complexity="single",
       user_input="Add the kernel arguments 'nomodeset' to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64.",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "nomodeset"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: nomodeset\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0002", tool="grub", operation="args-add",
       complexity="single",
       user_input="append console=ttyS0,115200n8 to all boot entries",
       args={"operation": "args-add", "kernel": "ALL", "kernel_args": "console=ttyS0,115200n8"},
       answer="Added args to ALL entries: console=ttyS0,115200n8\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0003", tool="grub", operation="args-add",
       complexity="diagnostic",
       user_input="The GPU on this box hard-locks the display on boot — add nomodeset to the default kernel to see if that helps.",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "nomodeset"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: nomodeset\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0004", tool="grub", operation="args-add",
       complexity="single",
       user_input="add crashkernel=256M to the current kernel entry",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "crashkernel=256M"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: crashkernel=256M\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0005", tool="grub", operation="args-add",
       complexity="multi",
       user_input="Add 'audit=1' to the default kernel and then regenerate the GRUB config.",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "audit=1"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: audit=1\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0006", tool="grub", operation="args-add",
       complexity="single",
       user_input="I need selinux=0 enforcement disabled at boot, add that arg to the current kernel entry",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "selinux=0"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: selinux=0\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0007", tool="grub", operation="args-add",
       complexity="diagnostic",
       user_input="Not enough entropy is showing up at boot on this VM — add rng_core.default_quality=1000 to the default kernel and see if it fixes the delay.",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "rng_core.default_quality=1000"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: rng_core.default_quality=1000\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0008", tool="grub", operation="args-add",
       complexity="single",
       user_input="add 'ipv6.disable=1' to /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64", "kernel_args": "ipv6.disable=1"},
       answer="Added args to /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64: ipv6.disable=1\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0009", tool="grub", operation="args-add",
       complexity="single",
       user_input="Add 'transparent_hugepage=never' to the running kernel's boot entry for the database node.",
       args={"operation": "args-add", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "transparent_hugepage=never"},
       answer="Added args to /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: transparent_hugepage=never\ngrubby: exit code 0."),
    V2(id="grub-args-add-v2-0010", tool="grub", operation="args-add",
       complexity="multi",
       user_input="Add 'quiet splash' to all entries, then confirm with info that it applied.",
       args={"operation": "args-add", "kernel": "ALL", "kernel_args": "quiet splash"},
       answer="Added args to ALL entries: quiet splash\ngrubby: exit code 0."),

    V2(id="grub-args-remove-v2-0001", tool="grub", operation="args-remove",
       complexity="single",
       user_input="Remove the 'nomodeset' argument from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64.",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "nomodeset"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: nomodeset\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0002", tool="grub", operation="args-remove",
       complexity="single",
       user_input="strip quiet splash off of every boot entry",
       args={"operation": "args-remove", "kernel": "ALL", "kernel_args": "quiet splash"},
       answer="Removed args from ALL entries: quiet splash\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0003", tool="grub", operation="args-remove",
       complexity="diagnostic",
       user_input="Boot messages are hidden and I can't see where it's hanging — is 'quiet' still set on the default kernel, and can you take it off?",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "quiet"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: quiet\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0004", tool="grub", operation="args-remove",
       complexity="single",
       user_input="take selinux=0 off the current kernel entry, we need enforcing back",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "selinux=0"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: selinux=0\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0005", tool="grub", operation="args-remove",
       complexity="multi",
       user_input="Remove 'ipv6.disable=1' from the default kernel and then regenerate the GRUB config.",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "ipv6.disable=1"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: ipv6.disable=1\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0006", tool="grub", operation="args-remove",
       complexity="single",
       user_input="drop 'audit=1' from /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64", "kernel_args": "audit=1"},
       answer="Removed args from /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64: audit=1\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0007", tool="grub", operation="args-remove",
       complexity="diagnostic",
       user_input="This server keeps crashing on boot after we added a crashkernel reservation — can you pull crashkernel=256M off the default entry?",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "crashkernel=256M"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: crashkernel=256M\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0008", tool="grub", operation="args-remove",
       complexity="single",
       user_input="remove transparent_hugepage=never from the boot args on the db kernel",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "transparent_hugepage=never"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: transparent_hugepage=never\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0009", tool="grub", operation="args-remove",
       complexity="single",
       user_input="Take 'console=ttyS0,115200n8' off every entry, we're moving off serial console.",
       args={"operation": "args-remove", "kernel": "ALL", "kernel_args": "console=ttyS0,115200n8"},
       answer="Removed args from ALL entries: console=ttyS0,115200n8\ngrubby: exit code 0."),
    V2(id="grub-args-remove-v2-0010", tool="grub", operation="args-remove",
       complexity="multi",
       user_input="Remove 'nomodeset' from the default kernel and then check the entry to confirm.",
       args={"operation": "args-remove", "kernel": "/boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64", "kernel_args": "nomodeset"},
       answer="Removed args from /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64: nomodeset\ngrubby: exit code 0."),

    V2(id="grub-mkconfig-v2-0001", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="Regenerate the GRUB config at the default output path.",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nFound linux image: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0002", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="rebuild grub.cfg and write it to /boot/grub2/grub.cfg.new for review first",
       args={"operation": "mkconfig", "output_file": "/boot/grub2/grub.cfg.new"},
       answer="Generating grub configuration file ...\nWrote /boot/grub2/grub.cfg.new\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0003", tool="grub", operation="mkconfig",
       complexity="diagnostic",
       user_input="After adding those kernel args, the boot menu still shows the old options — do we need to regenerate the config?",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nFound linux image: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0004", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="run grub2-mkconfig to pick up the new kernel entry",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nFound linux image: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\nFound linux image: /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0005", tool="grub", operation="mkconfig",
       complexity="multi",
       user_input="Regenerate the GRUB config and then verify the new entry with info.",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0006", tool="grub", operation="mkconfig",
       complexity="diagnostic",
       user_input="A firmware update this weekend may have touched the boot files — should we regenerate grub.cfg to be safe, and did it work?",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nFound linux image: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0007", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="write out a fresh grub config to /mnt/backup/grub.cfg.bak for our change record",
       args={"operation": "mkconfig", "output_file": "/mnt/backup/grub.cfg.bak"},
       answer="Generating grub configuration file ...\nWrote /mnt/backup/grub.cfg.bak\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0008", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="Rebuild the boot config now that the rescue kernel was removed.",
       args={"operation": "mkconfig"},
       answer="Generating grub configuration file ...\nFound linux image: /boot/vmlinuz-5.14.0-427.13.1.el9_4.x86_64\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0009", tool="grub", operation="mkconfig",
       complexity="single",
       user_input="grub2-mkconfig to /boot/grub2/grub.cfg please",
       args={"operation": "mkconfig", "output_file": "/boot/grub2/grub.cfg"},
       answer="Generating grub configuration file ...\nWrote /boot/grub2/grub.cfg\ngrub2-mkconfig: exit code 0."),
    V2(id="grub-mkconfig-v2-0010", tool="grub", operation="mkconfig",
       complexity="multi",
       user_input="Regenerate GRUB config to /tmp/grub-test.cfg first so we can diff before overwriting the real one.",
       args={"operation": "mkconfig", "output_file": "/tmp/grub-test.cfg"},
       answer="Generating grub configuration file ...\nWrote /tmp/grub-test.cfg\ngrub2-mkconfig: exit code 0."),

    V2(id="grub-set-password-v2-0001", tool="grub", operation="set-password",
       complexity="single",
       user_input="Set the GRUB bootloader password to Tr0ub4dor&3.",
       args={"operation": "set-password", "password": "Tr0ub4dor&3"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0002", tool="grub", operation="set-password",
       complexity="single",
       user_input="protect the boot menu with the password CorrectHorse99!",
       args={"operation": "set-password", "password": "CorrectHorse99!"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0003", tool="grub", operation="set-password",
       complexity="diagnostic",
       user_input="A security audit flagged that anyone with physical access can edit our kernel boot args unauthenticated — can you set a GRUB password to close that gap?",
       args={"operation": "set-password", "password": "P@ssphrase-2026rack3"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0004", tool="grub", operation="set-password",
       complexity="single",
       user_input="set a new grub password: Winter2026Vault!",
       args={"operation": "set-password", "password": "Winter2026Vault!"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0005", tool="grub", operation="set-password",
       complexity="multi",
       user_input="Set the GRUB password to Bastion-Node7$ and then regenerate the config so it takes effect.",
       args={"operation": "set-password", "password": "Bastion-Node7$"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0006", tool="grub", operation="set-password",
       complexity="single",
       user_input="apply a boot loader password of RackRoom-42x on this new server before it ships",
       args={"operation": "set-password", "password": "RackRoom-42x"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0007", tool="grub", operation="set-password",
       complexity="diagnostic",
       user_input="Compliance wants proof this host can't have its kernel args edited at boot without a password — is one set, and if not can you set Fleet-Guard91?",
       args={"operation": "set-password", "password": "Fleet-Guard91"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0008", tool="grub", operation="set-password",
       complexity="single",
       user_input="grub password should be Datacenter-Row12!",
       args={"operation": "set-password", "password": "Datacenter-Row12!"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0009", tool="grub", operation="set-password",
       complexity="single",
       user_input="Change the GRUB password to Sw1tchboard-99 for the new hardening baseline.",
       args={"operation": "set-password", "password": "Sw1tchboard-99"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),
    V2(id="grub-set-password-v2-0010", tool="grub", operation="set-password",
       complexity="multi",
       user_input="Set the bootloader password to Vault-Access7! and confirm the current default kernel afterward.",
       args={"operation": "set-password", "password": "Vault-Access7!"},
       answer="GRUB bootloader password updated.\ngrub2-setpassword: exit code 0."),

    V2(id="grub-remove-kernel-v2-0001", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="Remove the kernel entry for /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64.",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0002", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="clean out the old 9.2 kernel from the boot menu",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0003", tool="grub", operation="remove-kernel",
       complexity="diagnostic",
       user_input="/boot is nearly full and dnf refuses to install the next kernel update — can we drop the oldest kernel entry to free space?",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0.\n/boot usage dropped from 96% to 71%."),
    V2(id="grub-remove-kernel-v2-0004", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="get rid of the vmlinuz-5.14.0-362.13.1.el9_3.x86_64 entry, we don't need it anymore",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0005", tool="grub", operation="remove-kernel",
       complexity="multi",
       user_input="Remove the rescue kernel entry and then regenerate the GRUB config.",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c"},
       answer="Removed kernel entry: /boot/vmlinuz-0-rescue-3d9f2a1b8c7e4f6a9b0c1d2e3f4a5b6c\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0006", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="drop every entry except the current default from the boot menu",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0007", tool="grub", operation="remove-kernel",
       complexity="diagnostic",
       user_input="A patch audit flagged a kernel with a known CVE still listed in our boot menu — can you strip out /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64 so it can't be selected?",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0008", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="remove the boot entry at /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-362.13.1.el9_3.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0009", tool="grub", operation="remove-kernel",
       complexity="single",
       user_input="Delete the kernel entry for the 9.2 build now that everything's confirmed running on 9.4.",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
    V2(id="grub-remove-kernel-v2-0010", tool="grub", operation="remove-kernel",
       complexity="multi",
       user_input="Remove the old kernel entry and then confirm with info that only the current one remains.",
       args={"operation": "remove-kernel", "kernel": "/boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64"},
       answer="Removed kernel entry: /boot/vmlinuz-5.14.0-284.11.1.el9_2.x86_64\ngrubby: exit code 0."),
]

from finetune.scenarios_v2 import check_module; check_module("grub", SCENARIOS_V2)
