"""finetune/scenarios_v2/hardware.py — corpus v2 scenarios for 'hardware'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="hardware-cpu-v2-0001", tool="hardware", operation="cpu",
       complexity="single",
       user_input="Pull the processor topology for db-node-7.",
       args={"operation": "cpu"},
       answer="Architecture: x86_64\nCPU(s): 32\nSockets: 2\nCores per socket: 8\nThreads per core: 2\nVendor ID: GenuineIntel\nCPU type: Intel Xeon Silver 4210"),
    V2(id="hardware-cpu-v2-0002", tool="hardware", operation="cpu",
       complexity="single",
       user_input="how many cores does build-farm-3 have",
       args={"operation": "cpu"},
       answer="CPU(s): 16\nSockets: 1\nCores per socket: 8\nThreads per core: 2\nArchitecture: x86_64"),
    V2(id="hardware-cpu-v2-0003", tool="hardware", operation="cpu",
       complexity="diagnostic",
       user_input="Batch jobs on render-node-2 are pinned at 100% across the board. Show the processor topology so I can see if NUMA is a factor.",
       args={"operation": "cpu"},
       answer="Architecture: x86_64\nCPU(s): 64\nSockets: 2\nNUMA node(s): 2\nNUMA node0 CPU(s): 0-31\nNUMA node1 CPU(s): 32-63"),
    V2(id="hardware-cpu-v2-0004", tool="hardware", operation="cpu",
       complexity="diagnostic",
       user_input="We want to run KVM guests on lab-host-4, does the processor even support hardware virtualization?",
       args={"operation": "cpu"},
       answer="Vendor ID: AuthenticAMD\nFlags: ... svm ...\nVirtualization: AMD-V\nCPU(s): 24"),
    V2(id="hardware-cpu-v2-0005", tool="hardware", operation="cpu",
       complexity="multi",
       user_input="Get the CPU details for gateway-3 and confirm the architecture matches our x86_64 baseline.",
       args={"operation": "cpu"},
       answer="Architecture: x86_64\nCPU op-mode(s): 32-bit, 64-bit\nCPU(s): 8\nCPU type: Intel Xeon E-2288G"),
    V2(id="hardware-cpu-v2-0006", tool="hardware", operation="cpu",
       complexity="single",
       user_input="show lscpu for the new bare-metal box, host inv-104",
       args={"operation": "cpu"},
       answer="Architecture: x86_64\nCPU(s): 48\nSockets: 2\nCores per socket: 12\nThreads per core: 2\nCPU type: Intel Xeon Gold 6248"),

    V2(id="hardware-memory-v2-0001", tool="hardware", operation="memory",
       complexity="single",
       user_input="How much RAM is installed on db-node-7?",
       args={"operation": "memory"},
       answer="MemTotal: 64318264 kB\nMemFree: 8213904 kB\nMemAvailable: 41220112 kB\nSwapTotal: 8388604 kB\nSwapFree: 8388604 kB"),
    V2(id="hardware-memory-v2-0002", tool="hardware", operation="memory",
       complexity="single",
       user_input="what's the swap usage look like on cache-node-9",
       args={"operation": "memory"},
       answer="SwapTotal: 4194300 kB\nSwapFree: 1022104 kB\nSwapCached: 88420 kB\nMemAvailable: 6203112 kB"),
    V2(id="hardware-memory-v2-0003", tool="hardware", operation="memory",
       complexity="diagnostic",
       user_input="report-worker-2 is sluggish and slow to respond, check how much free RAM is available.",
       args={"operation": "memory"},
       answer="MemTotal: 16384000 kB\nMemFree: 210448 kB\nMemAvailable: 402112 kB\nSwapFree: 12008 kB of 2097148 kB"),
    V2(id="hardware-memory-v2-0004", tool="hardware", operation="memory",
       complexity="diagnostic",
       user_input="The OOM killer fired on batch-node-5 last night. Show me the current memory situation there.",
       args={"operation": "memory"},
       answer="MemTotal: 32499200 kB\nMemFree: 1233408 kB\nMemAvailable: 4021880 kB\nSwapFree: 0 kB of 4194300 kB"),
    V2(id="hardware-memory-v2-0005", tool="hardware", operation="memory",
       complexity="multi",
       user_input="Check memory usage on web-app-3 and flag if swap is being actively used.",
       args={"operation": "memory"},
       answer="MemTotal: 8175000 kB\nMemFree: 990112 kB\nSwapTotal: 2097148 kB\nSwapFree: 1400220 kB\nSwap in active use: 33%"),
    V2(id="hardware-memory-v2-0006", tool="hardware", operation="memory",
       complexity="diagnostic",
       user_input="postgres keeps getting killed on db-replica-1, is the host actually out of memory?",
       args={"operation": "memory"},
       answer="MemTotal: 16384000 kB\nMemFree: 98104 kB\nMemAvailable: 155600 kB\nSwapFree: 4088 kB of 4194300 kB"),

    V2(id="hardware-pci-v2-0001", tool="hardware", operation="pci",
       complexity="single",
       user_input="List PCI devices on storage-node-2.",
       args={"operation": "pci"},
       answer="00:1f.2 SATA controller: Intel Corporation C620 Series\n03:00.0 Ethernet controller: Intel X710 10GbE\n81:00.0 Non-Volatile memory controller: Samsung PM1733 NVMe"),
    V2(id="hardware-pci-v2-0002", tool="hardware", operation="pci",
       complexity="single",
       user_input="what network cards are in gpu-node-4",
       args={"operation": "pci"},
       answer="03:00.0 Ethernet controller: Mellanox ConnectX-5\n03:00.1 Ethernet controller: Mellanox ConnectX-5"),
    V2(id="hardware-pci-v2-0003", tool="hardware", operation="pci",
       complexity="diagnostic",
       user_input="The 10GbE interface on media-encode-6 disappeared after reboot. Check what network devices are visible on the PCI bus.",
       args={"operation": "pci"},
       answer="00:1f.6 Ethernet controller: Intel I219-LM\n(no discrete 10GbE adapter enumerated)"),
    V2(id="hardware-pci-v2-0004", tool="hardware", operation="pci",
       complexity="diagnostic",
       user_input="Disk latency spiked on nas-appliance-3, list PCI devices and identify any storage controllers that might be involved.",
       args={"operation": "pci"},
       answer="00:1f.2 SATA controller: Intel Corporation C620 Series\n02:00.0 RAID bus controller: Broadcom MegaRAID SAS 9361-8i"),
    V2(id="hardware-pci-v2-0005", tool="hardware", operation="pci",
       complexity="single",
       user_input="verify the HBA is recognized on tape-archive-1",
       args={"operation": "pci"},
       answer="04:00.0 Fibre Channel: QLogic ISP2532-based 8Gb HBA\nDevice recognized, driver qla2xxx bound"),
    V2(id="hardware-pci-v2-0006", tool="hardware", operation="pci",
       complexity="multi",
       user_input="Show PCI devices on accel-box-2 and confirm the new accelerator card is seen.",
       args={"operation": "pci"},
       answer="01:00.0 3D controller: NVIDIA GA104 [RTX 3060]\nDevice present, kernel driver nouveau in use"),
    V2(id="hardware-pci-v2-0007", tool="hardware", operation="pci",
       complexity="single",
       user_input="enumerate PCI bus devices on jump-host-1",
       args={"operation": "pci"},
       answer="00:02.0 VGA compatible controller: Intel HD Graphics\n00:1f.2 SATA controller: Intel Corporation C620 Series\n03:00.0 Ethernet controller: Intel I350"),

    V2(id="hardware-usb-v2-0001", tool="hardware", operation="usb",
       complexity="single",
       user_input="List USB devices connected to kiosk-terminal-4.",
       args={"operation": "usb"},
       answer="Bus 001 Device 002: ID 0781:5581 SanDisk Cruzer\nBus 001 Device 003: ID 046d:c52b Logitech USB Receiver"),
    V2(id="hardware-usb-v2-0002", tool="hardware", operation="usb",
       complexity="single",
       user_input="is there anything plugged into the USB ports on server-rack-b2",
       args={"operation": "usb"},
       answer="Bus 002 Device 001: ID 1d6b:0002 Linux Foundation root hub\n(no external devices attached)"),
    V2(id="hardware-usb-v2-0003", tool="hardware", operation="usb",
       complexity="diagnostic",
       user_input="The USB security key for two factor auth on admin-workstation-2 stopped responding. Check if the OS sees the device at all.",
       args={"operation": "usb"},
       answer="Bus 001 Device 004: ID 1050:0407 Yubico YubiKey\nDevice descriptor read/64, error -71"),
    V2(id="hardware-usb-v2-0004", tool="hardware", operation="usb",
       complexity="single",
       user_input="what does lsusb report for console-server-1",
       args={"operation": "usb"},
       answer="Bus 001 Device 002: ID 067b:2303 Prolific USB-Serial\nBus 001 Device 001: ID 1d6b:0002 Linux Foundation root hub"),
    V2(id="hardware-usb-v2-0005", tool="hardware", operation="usb",
       complexity="diagnostic",
       user_input="Policy on pos-terminal-9 says no mass storage on production hosts. Check what's actually plugged in.",
       args={"operation": "usb"},
       answer="Bus 001 Device 005: ID 0951:1666 Kingston DataTraveler (mass storage class)\nFlagged: unauthorized storage device present"),
    V2(id="hardware-usb-v2-0006", tool="hardware", operation="usb",
       complexity="single",
       user_input="A USB-to-serial adapter was just plugged into rack-console-3, verify it shows up.",
       args={"operation": "usb"},
       answer="Bus 001 Device 006: ID 0403:6001 FTDI USB-Serial Converter\nDriver: ftdi_sio bound"),
    V2(id="hardware-usb-v2-0007", tool="hardware", operation="usb",
       complexity="single",
       user_input="how many USB devices are attached to build-runner-2 right now",
       args={"operation": "usb"},
       answer="3 devices\nBus 001 Device 001: root hub\nBus 001 Device 002: Logitech USB Receiver\nBus 001 Device 003: Kingston DataTraveler"),
    V2(id="hardware-usb-v2-0008", tool="hardware", operation="usb",
       complexity="multi",
       user_input="Check the USB devices on lab-bench-5 and tell me if the printer dongle is one of them.",
       args={"operation": "usb"},
       answer="Bus 001 Device 002: ID 04b8:0202 Epson USB Printer\nBus 001 Device 003: ID 046d:c31c Logitech Keyboard"),

    V2(id="hardware-block-v2-0001", tool="hardware", operation="block",
       complexity="single",
       user_input="Show the block device layout on db-replica-2.",
       args={"operation": "block"},
       answer="sda      8:0    0  500G  0 disk\n├─sda1   8:1    0    1G  0 part /boot\n└─sda2   8:2    0  499G  0 part /\nnvme0n1  259:0  0  1.9T  0 disk /data"),
    V2(id="hardware-block-v2-0002", tool="hardware", operation="block",
       complexity="single",
       user_input="what disks are in warehouse-node-4",
       args={"operation": "block"},
       answer="sda   8:0   0  1T   0 disk\nsdb   8:16  0  1T   0 disk\nsdc   8:32  0  1T   0 disk"),
    V2(id="hardware-block-v2-0003", tool="hardware", operation="block",
       complexity="diagnostic",
       user_input="The root filesystem on log-collector-3 is nearly full. Show the block device list so I can find what disk it's on.",
       args={"operation": "block"},
       answer="sda      8:0    0  200G  0 disk\n└─sda1   8:1    0  199G  0 part /  (98% used)"),
    V2(id="hardware-block-v2-0004", tool="hardware", operation="block",
       complexity="multi",
       user_input="List block devices on analytics-db-1 and confirm the data volume is mounted at /data.",
       args={"operation": "block"},
       answer="sda      8:0    0  100G  0 disk /\nnvme0n1  259:0  0  2T    0 disk /data"),
    V2(id="hardware-block-v2-0005", tool="hardware", operation="block",
       complexity="single",
       user_input="how many drives are in cold-storage-6 and what sizes",
       args={"operation": "block"},
       answer="sda   8:0   0  8T  0 disk\nsdb   8:16  0  8T  0 disk\nsdc   8:32  0  8T  0 disk\nsdd   8:48  0  8T  0 disk"),
    V2(id="hardware-block-v2-0006", tool="hardware", operation="block",
       complexity="diagnostic",
       user_input="A new disk was hot-plugged into san-gateway-2. Verify the kernel has picked it up.",
       args={"operation": "block"},
       answer="sda   8:0   0  1T  0 disk /\nsdb   8:16  0  4T  0 disk  (newly detected, unformatted)"),
    V2(id="hardware-block-v2-0007", tool="hardware", operation="block",
       complexity="single",
       user_input="list block devices along with filesystem types and mount points for imap-node-3",
       args={"operation": "block"},
       answer="sda1  ext4  /boot\nsda2  xfs   /\nsdb1  xfs   /var/mail"),

    V2(id="hardware-sensors-v2-0001", tool="hardware", operation="sensors",
       complexity="single",
       user_input="What are the current temperatures on gpu-node-1?",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +58.0C\nCore 0: +54.0C\nCore 1: +56.0C\nfan1: 2100 RPM"),
    V2(id="hardware-sensors-v2-0002", tool="hardware", operation="sensors",
       complexity="single",
       user_input="pull the hardware sensor readings for rack-node-9",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +41.0C\nfan1: 1800 RPM\nVcore: 1.24 V"),
    V2(id="hardware-sensors-v2-0003", tool="hardware", operation="sensors",
       complexity="diagnostic",
       user_input="build-farm-3 is throttling under load. Check the thermal readings.",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +96.0C  (high)\nCore 3: +98.0C  (high)\nfan1: 3200 RPM"),
    V2(id="hardware-sensors-v2-0004", tool="hardware", operation="sensors",
       complexity="single",
       user_input="are the fans running at the right speed on storage-array-2",
       args={"operation": "sensors"},
       answer="fan1: 2400 RPM\nfan2: 2380 RPM\nfan3: 0 RPM  (stalled)"),
    V2(id="hardware-sensors-v2-0005", tool="hardware", operation="sensors",
       complexity="diagnostic",
       user_input="Datacenter monitoring flagged rack-b3-node2 as running hot. Pull the sensor data.",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +89.0C  (high)\nfan1: 2900 RPM\nVcore: 1.31 V"),
    V2(id="hardware-sensors-v2-0006", tool="hardware", operation="sensors",
       complexity="multi",
       user_input="Show sensor readings on encode-node-5 and flag any temperature above 80 degrees.",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +72.0C\nCore 2: +82.0C  (flagged)\nfan1: 2600 RPM"),
    V2(id="hardware-sensors-v2-0007", tool="hardware", operation="sensors",
       complexity="single",
       user_input="check voltage readings on db-node-8",
       args={"operation": "sensors"},
       answer="Vcore: 1.22 V\n+3.3V: 3.31 V\n+5V: 5.02 V\n+12V: 12.04 V"),
    V2(id="hardware-sensors-v2-0008", tool="hardware", operation="sensors",
       complexity="diagnostic",
       user_input="Kernel logged a thermal warning overnight on lab-host-7, show the current sensor state.",
       args={"operation": "sensors"},
       answer="coretemp-isa-0000\nPackage id 0: +64.0C  (recovered)\nfan1: 2700 RPM\nnvme0n1 composite: +52.0C"),

    V2(id="hardware-summary-v2-0001", tool="hardware", operation="summary",
       complexity="single",
       user_input="Give me a full hardware overview of db-node-7.",
       args={"operation": "summary"},
       answer="CPU: 32 x Intel Xeon Silver 4210\nMemory: 64318264 kB total, 41220112 kB available\nBlock: sda 500G, nvme0n1 1.9T"),
    V2(id="hardware-summary-v2-0002", tool="hardware", operation="summary",
       complexity="single",
       user_input="what hardware does staging-web-2 have",
       args={"operation": "summary"},
       answer="CPU: 8 x Intel Xeon E-2288G\nMemory: 16384000 kB total, 9200000 kB available\nBlock: sda 200G"),
    V2(id="hardware-summary-v2-0003", tool="hardware", operation="summary",
       complexity="diagnostic",
       user_input="Performance on legacy-app-3 is unexpectedly poor. Get a full hardware snapshot so we can check capacity.",
       args={"operation": "summary"},
       answer="CPU: 4 x Intel Xeon E3-1230\nMemory: 8175000 kB total, 512000 kB available\nBlock: sda 100G (91% used)"),
    V2(id="hardware-summary-v2-0004", tool="hardware", operation="summary",
       complexity="multi",
       user_input="Get a hardware snapshot for db-candidate-1 and tell me if CPU and RAM are enough for our database workload.",
       args={"operation": "summary"},
       answer="CPU: 48 x Intel Xeon Gold 6248\nMemory: 128000000 kB total, 98000000 kB available\nBlock: nvme0n1 3.8T"),
    V2(id="hardware-summary-v2-0005", tool="hardware", operation="summary",
       complexity="single",
       user_input="I just inherited server inv-206, show me what it's made of.",
       args={"operation": "summary"},
       answer="CPU: 16 x AMD EPYC 7302P\nMemory: 32499200 kB total, 15200000 kB available\nBlock: sda 1T, sdb 1T"),
    V2(id="hardware-summary-v2-0006", tool="hardware", operation="summary",
       complexity="single",
       user_input="pull the full hardware spec for bare-metal host quote-req-88, sizing team needs it",
       args={"operation": "summary"},
       answer="CPU: 64 x Intel Xeon Platinum 8260\nMemory: 256000000 kB total, 240000000 kB available\nBlock: nvme0n1 7.6T, nvme1n1 7.6T"),
]

from finetune.scenarios_v2 import check_module; check_module("hardware", SCENARIOS_V2)
