"""finetune/scenarios_v2/hostname.py — corpus v2 scenarios for 'hostname'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="hostname-status-v2-0001", tool="hostname", operation="status",
       complexity="single",
       user_input="Pull the full hostnamectl identity block for this box.",
       args={"operation": "status"},
       answer="Static hostname: db02.prod.internal\nIcon name: computer-server\nOperating System: Rocky Linux 9.4 (Blue Onyx)\nKernel: Linux 5.14.0-427.el9.x86_64"),
    V2(id="hostname-status-v2-0002", tool="hostname", operation="status",
       complexity="diagnostic",
       user_input="Kerberos auth keeps failing right after the redeploy \u2014 can you confirm the static hostname actually matches what we expect before I chase the keytab?",
       args={"operation": "status"},
       answer="Static hostname: app03.internal (unexpected \u2014 expected app03.corp.example.com)\nTransient hostname: app03"),
    V2(id="hostname-status-v2-0003", tool="hostname", operation="status",
       complexity="single",
       user_input="What does hostnamectl report for chassis type and machine ID?",
       args={"operation": "status"},
       answer="Chassis: server\nMachine ID: 8f2c1a9d4e6b4c1f9a0d2e3f4a5b6c7d\nBoot ID: 1a2b3c4d5e6f7081"),
    V2(id="hostname-set-hostname-v2-0004", tool="hostname", operation="set-hostname",
       complexity="single",
       user_input="Rename this host to cache-02.internal.example.com.",
       args={"name": "cache-02.internal.example.com", "operation": "set-hostname"},
       answer="hostname set: cache-02.internal.example.com"),
    V2(id="hostname-set-hostname-v2-0005", tool="hostname", operation="set-hostname",
       complexity="diagnostic",
       user_input="The cloud image still has its default hostname and our config management can't match inventory \u2014 set it to prod-web-07.dc2.example.com.",
       args={"name": "prod-web-07.dc2.example.com", "operation": "set-hostname"},
       answer="hostname set: prod-web-07.dc2.example.com"),
    V2(id="hostname-set-hostname-v2-0006", tool="hostname", operation="set-hostname",
       complexity="multi",
       user_input="Set the hostname to queue-worker-05.internal and then show me the updated hostnamectl status to confirm.",
       args={"name": "queue-worker-05.internal", "operation": "set-hostname"},
       answer="hostname set: queue-worker-05.internal\nStatic hostname: queue-worker-05.internal"),
    V2(id="hostname-set-hostname-v2-0007", tool="hostname", operation="set-hostname",
       complexity="single",
       user_input="Give this server the name ns2.corp.example.com.",
       args={"name": "ns2.corp.example.com", "operation": "set-hostname"},
       answer="hostname set: ns2.corp.example.com"),
    V2(id="hostname-hosts-view-v2-0008", tool="hostname", operation="hosts-view",
       complexity="single",
       user_input="Dump the current /etc/hosts contents.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n::1         localhost\n10.0.2.15   db01.internal db01"),
    V2(id="hostname-hosts-view-v2-0009", tool="hostname", operation="hosts-view",
       complexity="diagnostic",
       user_input="The batch job can't reach 'reportdb' by name even though ping to its IP works \u2014 check /etc/hosts for a stale entry.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n10.0.4.20   reportdb.old.internal reportdb"),
    V2(id="hostname-hosts-view-v2-0010", tool="hostname", operation="hosts-view",
       complexity="single",
       user_input="Show what's mapped in /etc/hosts on this node.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost localhost.localdomain\n192.168.5.5 nfs-share.internal nfs-share"),
    V2(id="hostname-hosts-view-v2-0011", tool="hostname", operation="hosts-view",
       complexity="multi",
       user_input="Print /etc/hosts and then tell me if there's a line for 10.0.9.9.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n10.0.9.9    metrics.internal metrics\nfound: 10.0.9.9 -> metrics.internal"),
    V2(id="hostname-hosts-view-v2-0012", tool="hostname", operation="hosts-view",
       complexity="diagnostic",
       user_input="Two services are resolving 'authsvc' to different IPs depending on the host \u2014 check what this box has hardcoded in /etc/hosts.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n10.0.7.30   authsvc.internal authsvc"),
    V2(id="hostname-hosts-view-v2-0013", tool="hostname", operation="hosts-view",
       complexity="single",
       user_input="List the loopback and static entries currently in the hosts file.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n::1         localhost ip6-localhost\n10.0.1.5    db-primary.internal"),
    V2(id="hostname-hosts-view-v2-0014", tool="hostname", operation="hosts-view",
       complexity="diagnostic",
       user_input="nftables rules reference a hostname alias for the mail relay that isn't resolving \u2014 is it even defined in /etc/hosts?",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\ncat: no entry matching mail-relay found"),
    V2(id="hostname-hosts-view-v2-0015", tool="hostname", operation="hosts-view",
       complexity="single",
       user_input="Check whether there are duplicate hostnames mapped in /etc/hosts.",
       args={"operation": "hosts-view"},
       answer="127.0.0.1   localhost\n10.0.1.5    db-primary.internal\n10.0.1.6    db-primary.internal\nduplicate hostname: db-primary.internal"),
    V2(id="hostname-hosts-edit-v2-0016", tool="hostname", operation="hosts-edit",
       complexity="single",
       user_input="Add an entry mapping 10.0.3.40 to jobqueue.internal in /etc/hosts.",
       args={"entry": "10.0.3.40 jobqueue.internal jobqueue", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 10.0.3.40 jobqueue.internal jobqueue"),
    V2(id="hostname-hosts-edit-v2-0017", tool="hostname", operation="hosts-edit",
       complexity="diagnostic",
       user_input="The Ansible controller can't resolve 'worker-09' and there's no internal DNS record for it yet \u2014 add a static entry 10.0.5.9 worker-09.ansible.local as a stopgap.",
       args={"entry": "10.0.5.9 worker-09.ansible.local worker-09", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 10.0.5.9 worker-09.ansible.local worker-09"),
    V2(id="hostname-hosts-edit-v2-0018", tool="hostname", operation="hosts-edit",
       complexity="single",
       user_input="Map 172.16.4.4 to registry-mirror.internal in the hosts file.",
       args={"entry": "172.16.4.4 registry-mirror.internal registry-mirror", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 172.16.4.4 registry-mirror.internal registry-mirror"),
    V2(id="hostname-hosts-edit-v2-0019", tool="hostname", operation="hosts-edit",
       complexity="multi",
       user_input="Add 10.20.1.15 pointing to ldap-secondary.corp.example.com to /etc/hosts and then show me the file to confirm.",
       args={"entry": "10.20.1.15 ldap-secondary.corp.example.com", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 10.20.1.15 ldap-secondary.corp.example.com\n127.0.0.1   localhost\n10.20.1.15  ldap-secondary.corp.example.com"),
    V2(id="hostname-hosts-edit-v2-0020", tool="hostname", operation="hosts-edit",
       complexity="diagnostic",
       user_input="SMTP relay lookups are timing out for smtp-relay.ops.example.com since the DNS zone hasn't propagated yet \u2014 add a temporary static mapping to 192.168.9.9.",
       args={"entry": "192.168.9.9 smtp-relay.ops.example.com smtp-relay", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 192.168.9.9 smtp-relay.ops.example.com smtp-relay"),
    V2(id="hostname-hosts-edit-v2-0021", tool="hostname", operation="hosts-edit",
       complexity="single",
       user_input="Append 127.0.0.2 sandbox.local to /etc/hosts for local testing.",
       args={"entry": "127.0.0.2 sandbox.local", "operation": "hosts-edit"},
       answer="appended to /etc/hosts: 127.0.0.2 sandbox.local"),
]

from finetune.scenarios_v2 import check_module; check_module("hostname", SCENARIOS_V2)
