"""finetune/scenarios_v2/httpd.py — corpus v2 scenarios for 'httpd'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="httpd-status-v2-0001", tool="httpd", operation="status",
       complexity="single",
       user_input="Is the Apache service up on web05?",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nUptime: 4d 2h, main PID 1832."),
    V2(id="httpd-status-v2-0002", tool="httpd", operation="status",
       complexity="diagnostic",
       user_input="Users on the ticket say the checkout page times out — is the web server even alive on frontend2?",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nProcess is up; timeouts likely originate upstream."),
    V2(id="httpd-status-v2-0003", tool="httpd", operation="status",
       complexity="single",
       user_input="Check the current state of the web server on host static3.",
       args={"operation": "status"},
       answer="httpd.service: failed\nExit code 1, last restart attempt 3 minutes ago."),
    V2(id="httpd-status-v2-0004", tool="httpd", operation="status",
       complexity="multi",
       user_input="Check if httpd is active on staging1, and if it's down we'll need to start it before the demo.",
       args={"operation": "status"},
       answer="httpd.service: inactive (dead)\nNot running; needs to be started."),
    V2(id="httpd-status-v2-0005", tool="httpd", operation="status",
       complexity="diagnostic",
       user_input="Nagios paged about port 80 on app-web1 — before I dig into nftables rules, what does the service state say?",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nListening normally; suspect a network path issue rather than the service."),
    V2(id="httpd-status-v2-0006", tool="httpd", operation="status",
       complexity="single",
       user_input="Show me how long httpd has been running on web05.",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nUptime: 11d 6h."),
    V2(id="httpd-status-v2-0007", tool="httpd", operation="status",
       complexity="single",
       user_input="Pull the systemd status for the Apache HTTP Server on media-cdn2.",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nMemory: 340M, tasks: 62."),
    V2(id="httpd-status-v2-0008", tool="httpd", operation="status",
       complexity="diagnostic",
       user_input="502s started at 14:02 on gateway-web3 — first thing, is httpd still running?",
       args={"operation": "status"},
       answer="httpd.service: active (running)\nService up; 502 likely from a backend pool, not this host."),
    V2(id="httpd-configtest-v2-0001", tool="httpd", operation="configtest",
       complexity="single",
       user_input="Check the Apache config for syntax problems on web05 before I touch anything else.",
       args={"operation": "configtest"},
       answer="Syntax OK"),
    V2(id="httpd-configtest-v2-0002", tool="httpd", operation="configtest",
       complexity="diagnostic",
       user_input="httpd refuses to reload on static3 — did I break the config editing that VirtualHost block?",
       args={"operation": "configtest"},
       answer="Syntax error on line 214 of /etc/httpd/conf.d/vhost-static3.conf: Invalid command 'ServerNam'"),
    V2(id="httpd-configtest-v2-0003", tool="httpd", operation="configtest",
       complexity="single",
       user_input="Run a config syntax check for the Apache instance on media-cdn2.",
       args={"operation": "configtest"},
       answer="Syntax OK"),
    V2(id="httpd-configtest-v2-0004", tool="httpd", operation="configtest",
       complexity="multi",
       user_input="Validate the httpd config on frontend2, and reload the service if it comes back clean.",
       args={"operation": "configtest"},
       answer="Syntax OK"),
    V2(id="httpd-configtest-v2-0005", tool="httpd", operation="configtest",
       complexity="single",
       user_input="Does app-web1's Apache config have any errors right now?",
       args={"operation": "configtest"},
       answer="Syntax OK"),
    V2(id="httpd-configtest-v2-0006", tool="httpd", operation="configtest",
       complexity="diagnostic",
       user_input="A firewalld change went in an hour ago and now the site's unreachable on gateway-web3 — is this a config issue on the httpd side?",
       args={"operation": "configtest"},
       answer="Syntax OK\nConfig loads cleanly; problem is likely the firewall change, not httpd config."),
    V2(id="httpd-configtest-v2-0007", tool="httpd", operation="configtest",
       complexity="single",
       user_input="Verify the new SSL VirtualHost block on secure-web4 parses correctly.",
       args={"operation": "configtest"},
       answer="Syntax OK"),
    V2(id="httpd-configtest-v2-0008", tool="httpd", operation="configtest",
       complexity="single",
       user_input="Test the httpd configuration on batch-web7 for errors.",
       args={"operation": "configtest"},
       answer="Syntax error on line 88 of /etc/httpd/conf.d/ssl.conf: SSLCertificateFile does not exist"),
    V2(id="httpd-start-v2-0001", tool="httpd", operation="start",
       complexity="single",
       user_input="Bring httpd up on staging1.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 20841."),
    V2(id="httpd-start-v2-0002", tool="httpd", operation="start",
       complexity="multi",
       user_input="Start the Apache service on web05 and then confirm it's actually listening.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 20841."),
    V2(id="httpd-start-v2-0003", tool="httpd", operation="start",
       complexity="diagnostic",
       user_input="Users can't reach the site on static3 — if the web server isn't running, get it back up.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 5502."),
    V2(id="httpd-start-v2-0004", tool="httpd", operation="start",
       complexity="single",
       user_input="Start the Apache HTTP Server on media-cdn2 after the maintenance window.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 3390."),
    V2(id="httpd-start-v2-0005", tool="httpd", operation="start",
       complexity="single",
       user_input="Power up httpd on frontend2 so the app pool can accept traffic again.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 41022."),
    V2(id="httpd-start-v2-0006", tool="httpd", operation="start",
       complexity="multi",
       user_input="First run a config check on app-web1, then if it passes go ahead and start httpd.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 9911."),
    V2(id="httpd-start-v2-0007", tool="httpd", operation="start",
       complexity="single",
       user_input="Get the web server running on gateway-web3.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 15204."),
    V2(id="httpd-start-v2-0008", tool="httpd", operation="start",
       complexity="diagnostic",
       user_input="The scheduled deploy stopped httpd on secure-web4 and never restarted it — fix that.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 7734."),
    V2(id="httpd-start-v2-0009", tool="httpd", operation="start",
       complexity="single",
       user_input="Start Apache on batch-web7.",
       args={"operation": "start"},
       answer="httpd.service started.\nActive (running), PID 28810."),
    V2(id="httpd-stop-v2-0001", tool="httpd", operation="stop",
       complexity="single",
       user_input="Shut down httpd on secure-web4 for the certificate swap.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0002", tool="httpd", operation="stop",
       complexity="diagnostic",
       user_input="gateway-web3's Apache process is pinned at 100% CPU — kill it before it takes the box down.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0003", tool="httpd", operation="stop",
       complexity="single",
       user_input="Take the web server offline on static3, we're decommissioning it.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0004", tool="httpd", operation="stop",
       complexity="multi",
       user_input="Stop Apache on batch-web7 and then pull the last few lines of the error log.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0005", tool="httpd", operation="stop",
       complexity="single",
       user_input="Halt the httpd service on media-cdn2 during the maintenance window.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0006", tool="httpd", operation="stop",
       complexity="single",
       user_input="Stop the Apache HTTP Server on app-web1.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0007", tool="httpd", operation="stop",
       complexity="diagnostic",
       user_input="A firewalld rule reload is coming up and it might conflict with active httpd connections on frontend2 — stop it beforehand.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0008", tool="httpd", operation="stop",
       complexity="single",
       user_input="Bring httpd down on web05.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-stop-v2-0009", tool="httpd", operation="stop",
       complexity="single",
       user_input="Stop the web server on staging1 while we swap the storage backend.",
       args={"operation": "stop"},
       answer="httpd.service stopped."),
    V2(id="httpd-restart-v2-0001", tool="httpd", operation="restart",
       complexity="single",
       user_input="Bounce Apache on web05 to pick up the new VirtualHost.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 51230."),
    V2(id="httpd-restart-v2-0002", tool="httpd", operation="restart",
       complexity="multi",
       user_input="Run a config test on secure-web4, and restart the service only if it comes back clean.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 6620."),
    V2(id="httpd-restart-v2-0003", tool="httpd", operation="restart",
       complexity="diagnostic",
       user_input="media-cdn2's httpd is chewing through memory and never releasing it — cycle the service to clear the workers.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 8842."),
    V2(id="httpd-restart-v2-0004", tool="httpd", operation="restart",
       complexity="single",
       user_input="Restart httpd on app-web1 to apply the mod_ssl update.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 33012."),
    V2(id="httpd-restart-v2-0005", tool="httpd", operation="restart",
       complexity="single",
       user_input="Cycle the Apache service on gateway-web3 after enabling mod_rewrite.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 40021."),
    V2(id="httpd-restart-v2-0006", tool="httpd", operation="restart",
       complexity="single",
       user_input="Restart the web server on batch-web7.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 12277."),
    V2(id="httpd-restart-v2-0007", tool="httpd", operation="restart",
       complexity="multi",
       user_input="Restart httpd on frontend2 and confirm it comes back up afterward.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 9021."),
    V2(id="httpd-restart-v2-0008", tool="httpd", operation="restart",
       complexity="diagnostic",
       user_input="static3's site kept working after the cert swap but I'm not confident the new cert loaded — restart to be sure.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 5590."),
    V2(id="httpd-restart-v2-0009", tool="httpd", operation="restart",
       complexity="single",
       user_input="Restart Apache on staging1 to pick up the updated PHP module.",
       args={"operation": "restart"},
       answer="httpd.service restarted.\nActive (running), PID 61102."),
    V2(id="httpd-vhost_list-v2-0001", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="Show me the VirtualHosts configured on web05.",
       args={"operation": "vhost_list"},
       answer="port 443 namevhost shop.example.com (/etc/httpd/conf.d/shop.conf:12)\nport 80  namevhost www.example.com (/etc/httpd/conf.d/www.conf:8)"),
    V2(id="httpd-vhost_list-v2-0002", tool="httpd", operation="vhost_list",
       complexity="diagnostic",
       user_input="A new host header for partners.example.com is getting the wrong content on frontend2 — was it even picked up as a vhost?",
       args={"operation": "vhost_list"},
       answer="port 443 namevhost www.example.com (/etc/httpd/conf.d/www.conf:12)\npartners.example.com is not listed; the vhost config was not loaded."),
    V2(id="httpd-vhost_list-v2-0003", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="List what ports httpd is listening on for app-web1.",
       args={"operation": "vhost_list"},
       answer="port 80  namevhost api.example.com (/etc/httpd/conf.d/api.conf:6)\nport 8443 namevhost internal.example.com (/etc/httpd/conf.d/internal.conf:9)"),
    V2(id="httpd-vhost_list-v2-0004", tool="httpd", operation="vhost_list",
       complexity="multi",
       user_input="List the vhosts on gateway-web3, then tell me which config file defines checkout.example.com.",
       args={"operation": "vhost_list"},
       answer="port 443 namevhost checkout.example.com (/etc/httpd/conf.d/checkout.conf:20)\ncheckout.example.com is defined in checkout.conf."),
    V2(id="httpd-vhost_list-v2-0005", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="Run apachectl -S on media-cdn2 and show the vhost summary.",
       args={"operation": "vhost_list"},
       answer="port 443 namevhost cdn.example.com (/etc/httpd/conf.d/cdn.conf:15)"),
    V2(id="httpd-vhost_list-v2-0006", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="What is the default VirtualHost on port 80 for staging1?",
       args={"operation": "vhost_list"},
       answer="port 80  namevhost staging.example.com (/etc/httpd/conf.d/staging.conf:5) — default server"),
    V2(id="httpd-vhost_list-v2-0007", tool="httpd", operation="vhost_list",
       complexity="diagnostic",
       user_input="Two teams claim ownership of port 8080 on batch-web7 — check which vhost actually binds it.",
       args={"operation": "vhost_list"},
       answer="port 8080 namevhost batch.example.com (/etc/httpd/conf.d/batch.conf:11)"),
    V2(id="httpd-vhost_list-v2-0008", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="List all vhosts Apache is currently serving on secure-web4.",
       args={"operation": "vhost_list"},
       answer="port 443 namevhost secure.example.com (/etc/httpd/conf.d/secure.conf:14)"),
    V2(id="httpd-vhost_list-v2-0009", tool="httpd", operation="vhost_list",
       complexity="single",
       user_input="Confirm which vhosts are live on static3 after the config reload.",
       args={"operation": "vhost_list"},
       answer="port 80  namevhost static.example.com (/etc/httpd/conf.d/static.conf:7)"),
    V2(id="httpd-mod_status-v2-0001", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="Pull the mod_status metrics for web05.",
       args={"operation": "mod_status"},
       answer="Requests/sec: 142.3, workers busy: 18/150\nUptime: 4 days 2 hours."),
    V2(id="httpd-mod_status-v2-0002", tool="httpd", operation="mod_status",
       complexity="diagnostic",
       user_input="Page load times spiked on frontend2 — check the live server status to see if we're hitting the worker cap.",
       args={"operation": "mod_status"},
       answer="Requests/sec: 310.7, workers busy: 149/150\nWorker pool nearly exhausted, matches the slowdown."),
    V2(id="httpd-mod_status-v2-0003", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="How many requests per second is app-web1 handling right now?",
       args={"operation": "mod_status"},
       answer="Requests/sec: 87.1, workers busy: 22/150"),
    V2(id="httpd-mod_status-v2-0004", tool="httpd", operation="mod_status",
       complexity="multi",
       user_input="Grab the mod_status page from gateway-web3 and then tell me if we should bump MaxRequestWorkers.",
       args={"operation": "mod_status"},
       answer="Requests/sec: 205.4, workers busy: 140/150\nClose to the limit; raising MaxRequestWorkers is worth considering."),
    V2(id="httpd-mod_status-v2-0005", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="What's the CPU load and active worker count on media-cdn2's Apache?",
       args={"operation": "mod_status"},
       answer="CPU load: 0.62, workers busy: 30/150"),
    V2(id="httpd-mod_status-v2-0006", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="Check the Apache server uptime on staging1 via mod_status.",
       args={"operation": "mod_status"},
       answer="Uptime: 11 days 6 hours\nRequests/sec: 4.2, workers busy: 3/150"),
    V2(id="httpd-mod_status-v2-0007", tool="httpd", operation="mod_status",
       complexity="diagnostic",
       user_input="Traffic just jumped on batch-web7 — how many worker threads are active this minute?",
       args={"operation": "mod_status"},
       answer="Requests/sec: 402.9, workers busy: 148/150\nWorker count is climbing fast with the traffic jump."),
    V2(id="httpd-mod_status-v2-0008", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="Fetch the live mod_status output for secure-web4 for the monitoring dashboard.",
       args={"operation": "mod_status"},
       answer="Requests/sec: 55.0, workers busy: 12/150"),
    V2(id="httpd-mod_status-v2-0009", tool="httpd", operation="mod_status",
       complexity="single",
       user_input="Get server metrics from static3's mod_status endpoint.",
       args={"operation": "mod_status"},
       answer="Requests/sec: 9.6, workers busy: 2/150"),
]

from finetune.scenarios_v2 import check_module; check_module("httpd", SCENARIOS_V2)
