"""finetune/scenarios_v2/kernel_modules.py — corpus v2 scenarios for 'kernel_modules'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="kernel_modules-lsmod-v2-0001", tool="kernel_modules", operation="lsmod",
       complexity="single",
       user_input="What modules are loaded right now?",
       args={"operation": "lsmod"},
       answer="Module                  Size  Used by\nnf_conntrack          172032  3\nbr_netfilter           32768  0\nxfs                  1863680  1"),
    V2(id="kernel_modules-lsmod-v2-0002", tool="kernel_modules", operation="lsmod",
       complexity="diagnostic",
       user_input="Container networking on this host seems broken — bridged traffic isn't forwarding. Can you check what's loaded?",
       args={"operation": "lsmod"},
       answer="Module                  Size  Used by\noverlay               167936  8\nnf_conntrack          172032  2\n(br_netfilter not present)"),
    V2(id="kernel_modules-lsmod-v2-0003", tool="kernel_modules", operation="lsmod",
       complexity="single",
       user_input="show loaded modules",
       args={"operation": "lsmod"},
       answer="Module                  Size  Used by\next4                  798720  1\nixgbe                 331776  0"),
    V2(id="kernel_modules-lsmod-v2-0004", tool="kernel_modules", operation="lsmod",
       complexity="multi",
       user_input="Check the loaded module table, then load nf_conntrack if it's missing.",
       args={"operation": "lsmod"},
       answer="Module                  Size  Used by\nixgbe                 331776  0\nxfs                  1863680  1\n(nf_conntrack not present)"),
    V2(id="kernel_modules-lsmod-v2-0005", tool="kernel_modules", operation="lsmod",
       complexity="diagnostic",
       user_input="samba shares mounted over cifs are hanging — is the cifs module even loaded?",
       args={"operation": "lsmod"},
       answer="Module                  Size  Used by\ncifs                  438272  1\ndns_resolver           16384  1"),
    V2(id="kernel_modules-modinfo-v2-0001", tool="kernel_modules", operation="modinfo",
       complexity="single",
       user_input="Give me the metadata for the ixgbe module.",
       args={"operation": "modinfo", "module": "ixgbe"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/drivers/net/ethernet/intel/ixgbe/ixgbe.ko.xz\nversion: 5.19.5\ndepends: mdio"),
    V2(id="kernel_modules-modinfo-v2-0002", tool="kernel_modules", operation="modinfo",
       complexity="diagnostic",
       user_input="Before I load br_netfilter for the bridge fix, what does it actually depend on?",
       args={"operation": "modinfo", "module": "br_netfilter"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/net/bridge/br_netfilter.ko.xz\nversion: (none)\ndepends: bridge"),
    V2(id="kernel_modules-modinfo-v2-0003", tool="kernel_modules", operation="modinfo",
       complexity="single",
       user_input="show details on the vfio_pci module",
       args={"operation": "modinfo", "module": "vfio_pci"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/drivers/vfio/pci/vfio-pci.ko.xz\nversion: (none)\ndepends: vfio_pci_core,vfio"),
    V2(id="kernel_modules-modinfo-v2-0004", tool="kernel_modules", operation="modinfo",
       complexity="single",
       user_input="What parameters does the nvme module take?",
       args={"operation": "modinfo", "module": "nvme"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/drivers/nvme/host/nvme.ko.xz\nparm: max_retries:int\nparm: io_queue_depth:uint"),
    V2(id="kernel_modules-modinfo-v2-0005", tool="kernel_modules", operation="modinfo",
       complexity="multi",
       user_input="Look up the dependencies of nf_conntrack, then unload it if nothing else needs it.",
       args={"operation": "modinfo", "module": "nf_conntrack"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/net/netfilter/nf_conntrack.ko.xz\nversion: (none)\ndepends: (none)"),
    V2(id="kernel_modules-modinfo-v2-0006", tool="kernel_modules", operation="modinfo",
       complexity="diagnostic",
       user_input="A vendor driver ticket mentions the mlx5_core module needs firmware 22.x — what version is installed here?",
       args={"operation": "modinfo", "module": "mlx5_core"},
       answer="filename: /lib/modules/5.14.0-427.el9/kernel/drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko.xz\nversion: 5.9-0.5.5\nfirmware: mellanox/mlxsw_spectrum"),
    V2(id="kernel_modules-modprobe-v2-0001", tool="kernel_modules", operation="modprobe",
       complexity="single",
       user_input="Load the nf_conntrack module.",
       args={"operation": "modprobe", "module": "nf_conntrack"},
       answer="modprobe nf_conntrack: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-modprobe-v2-0002", tool="kernel_modules", operation="modprobe",
       complexity="diagnostic",
       user_input="Bridged docker traffic isn't being filtered by iptables rules — I think br_netfilter needs to be brought up.",
       args={"operation": "modprobe", "module": "br_netfilter"},
       answer="modprobe br_netfilter: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-modprobe-v2-0003", tool="kernel_modules", operation="modprobe",
       complexity="single",
       user_input="insert the vfio_pci module",
       args={"operation": "modprobe", "module": "vfio_pci"},
       answer="modprobe vfio_pci: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-modprobe-v2-0004", tool="kernel_modules", operation="modprobe",
       complexity="multi",
       user_input="Load overlay for the container runtime, then restart the container service.",
       args={"operation": "modprobe", "module": "overlay"},
       answer="modprobe overlay: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-modprobe-v2-0005", tool="kernel_modules", operation="modprobe",
       complexity="single",
       user_input="bring up the 8021q module for vlan tagging",
       args={"operation": "modprobe", "module": "8021q"},
       answer="modprobe 8021q: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-modprobe-v2-0006", tool="kernel_modules", operation="modprobe",
       complexity="diagnostic",
       user_input="iscsi target discovery is failing with 'module not found' — does iscsi_tcp need loading?",
       args={"operation": "modprobe", "module": "iscsi_tcp"},
       answer="modprobe iscsi_tcp: loaded\nnow present in lsmod: yes"),
    V2(id="kernel_modules-rmmod-v2-0001", tool="kernel_modules", operation="rmmod",
       complexity="single",
       user_input="Unload the pcspkr module.",
       args={"operation": "rmmod", "module": "pcspkr"},
       answer="rmmod pcspkr: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-rmmod-v2-0002", tool="kernel_modules", operation="rmmod",
       complexity="diagnostic",
       user_input="This laptop's speaker keeps clicking on boot — is that the pcspkr module we could remove?",
       args={"operation": "rmmod", "module": "pcspkr"},
       answer="rmmod pcspkr: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-rmmod-v2-0003", tool="kernel_modules", operation="rmmod",
       complexity="single",
       user_input="remove the floppy module, nothing here uses it",
       args={"operation": "rmmod", "module": "floppy"},
       answer="rmmod floppy: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-rmmod-v2-0004", tool="kernel_modules", operation="rmmod",
       complexity="multi",
       user_input="Unload the old nouveau driver, then load nvidia in its place.",
       args={"operation": "rmmod", "module": "nouveau"},
       answer="rmmod nouveau: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-rmmod-v2-0005", tool="kernel_modules", operation="rmmod",
       complexity="single",
       user_input="Take out the joydev module.",
       args={"operation": "rmmod", "module": "joydev"},
       answer="rmmod joydev: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-rmmod-v2-0006", tool="kernel_modules", operation="rmmod",
       complexity="diagnostic",
       user_input="We swapped the storage controller for a different vendor — should the old megaraid_sas module still be loaded?",
       args={"operation": "rmmod", "module": "megaraid_sas"},
       answer="rmmod megaraid_sas: removed\nno longer present in lsmod"),
    V2(id="kernel_modules-modules-load.d-v2-0001", tool="kernel_modules", operation="modules-load.d",
       complexity="single",
       user_input="Make nf_conntrack persist across reboots.",
       args={"operation": "modules-load.d", "module": "nf_conntrack"},
       answer="wrote /etc/modules-load.d/nf_conntrack.conf\ncontents: nf_conntrack"),
    V2(id="kernel_modules-modules-load.d-v2-0002", tool="kernel_modules", operation="modules-load.d",
       complexity="diagnostic",
       user_input="Every time this host reboots I have to reload br_netfilter by hand for the firewall rules to take — can we make that automatic?",
       args={"operation": "modules-load.d", "module": "br_netfilter", "filename": "bridge-netfilter"},
       answer="wrote /etc/modules-load.d/bridge-netfilter.conf\ncontents: br_netfilter"),
    V2(id="kernel_modules-modules-load.d-v2-0003", tool="kernel_modules", operation="modules-load.d",
       complexity="single",
       user_input="persist the vfio_pci module for boot",
       args={"operation": "modules-load.d", "module": "vfio_pci"},
       answer="wrote /etc/modules-load.d/vfio_pci.conf\ncontents: vfio_pci"),
    V2(id="kernel_modules-modules-load.d-v2-0004", tool="kernel_modules", operation="modules-load.d",
       complexity="multi",
       user_input="Set overlay to auto-load at boot, then confirm it's currently loaded too.",
       args={"operation": "modules-load.d", "module": "overlay"},
       answer="wrote /etc/modules-load.d/overlay.conf\ncontents: overlay"),
    V2(id="kernel_modules-modules-load.d-v2-0005", tool="kernel_modules", operation="modules-load.d",
       complexity="single",
       user_input="write a modules-load.d entry for 8021q named vlan-support",
       args={"operation": "modules-load.d", "module": "8021q", "filename": "vlan-support"},
       answer="wrote /etc/modules-load.d/vlan-support.conf\ncontents: 8021q"),
    V2(id="kernel_modules-modules-load.d-v2-0006", tool="kernel_modules", operation="modules-load.d",
       complexity="diagnostic",
       user_input="The tuned throughput profile needs nf_conntrack up before the network target starts — should we persist the module load?",
       args={"operation": "modules-load.d", "module": "nf_conntrack", "filename": "conntrack-boot"},
       answer="wrote /etc/modules-load.d/conntrack-boot.conf\ncontents: nf_conntrack"),
]

from finetune.scenarios_v2 import check_module; check_module("kernel_modules", SCENARIOS_V2)
