"""finetune/scenarios_v2/lvm.py — corpus v2 scenarios for 'lvm'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="lvm-pvdisplay-v2-0001", tool="lvm", operation="pvdisplay",
       complexity="single",
       user_input="Show me the physical volume details for /dev/sdb.",
       args={'operation': 'pvdisplay', 'pv': '/dev/sdb'},
       answer="/dev/sdb   VG Name vg_data\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0002", tool="lvm", operation="pvdisplay",
       complexity="single",
       user_input="List every physical volume on this host.",
       args={'operation': 'pvdisplay'},
       answer="PV /dev/sdb   VG vg_data   lvm2 [500.00 GiB / 5.00 GiB free]\nPV /dev/sdc   VG vg_backup lvm2 [1.00 TiB / 120.00 GiB free]\n2 PVs total"),
    V2(id="lvm-pvdisplay-v2-0003", tool="lvm", operation="pvdisplay",
       complexity="diagnostic",
       user_input="We're not sure /dev/sdd1 was ever initialised for LVM, can you check its current attributes?",
       args={'operation': 'pvdisplay', 'pv': '/dev/sdd1'},
       answer="/dev/sdd1   VG Name vg_data\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0004", tool="lvm", operation="pvdisplay",
       complexity="single",
       user_input="Pull up pvdisplay output for /dev/sde.",
       args={'operation': 'pvdisplay', 'pv': '/dev/sde'},
       answer="/dev/sde   VG Name vg_app\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0005", tool="lvm", operation="pvdisplay",
       complexity="multi",
       user_input="Show all physical volumes and then tell me which one has the least free space.",
       args={'operation': 'pvdisplay'},
       answer="PV /dev/sdb   VG vg_data   lvm2 [500.00 GiB / 5.00 GiB free]\nPV /dev/sdc   VG vg_backup lvm2 [1.00 TiB / 120.00 GiB free]\n2 PVs total"),
    V2(id="lvm-pvdisplay-v2-0006", tool="lvm", operation="pvdisplay",
       complexity="diagnostic",
       user_input="Storage team thinks /dev/nvme1n1 might already be part of a volume group, what does it show?",
       args={'operation': 'pvdisplay', 'pv': '/dev/nvme1n1'},
       answer="/dev/nvme1n1   VG Name vg_app\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0007", tool="lvm", operation="pvdisplay",
       complexity="single",
       user_input="What's the size and free extent count on /dev/sdf1?",
       args={'operation': 'pvdisplay', 'pv': '/dev/sdf1'},
       answer="/dev/sdf1   VG Name vg_data\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0008", tool="lvm", operation="pvdisplay",
       complexity="diagnostic",
       user_input="Before we wipe anything, is /dev/sdg currently allocated to any VG?",
       args={'operation': 'pvdisplay', 'pv': '/dev/sdg'},
       answer="/dev/sdg   VG Name vg_app\n  PV Size 500.00 GiB / not usable 4.00 MiB\n  Free PE / Size 1280 / 5.00 GiB\n  Allocatable yes"),
    V2(id="lvm-pvdisplay-v2-0009", tool="lvm", operation="pvdisplay",
       complexity="single",
       user_input="Give me a full physical volume inventory for mail-gw2.",
       args={'operation': 'pvdisplay'},
       answer="PV /dev/sdb   VG vg_data   lvm2 [500.00 GiB / 5.00 GiB free]\nPV /dev/sdc   VG vg_backup lvm2 [1.00 TiB / 120.00 GiB free]\n2 PVs total"),
    V2(id="lvm-pvdisplay-v2-0010", tool="lvm", operation="pvdisplay",
       complexity="multi",
       user_input="Check the physical volumes on this box, then we'll decide if we need to extend a VG.",
       args={'operation': 'pvdisplay'},
       answer="PV /dev/sdb   VG vg_data   lvm2 [500.00 GiB / 5.00 GiB free]\nPV /dev/sdc   VG vg_backup lvm2 [1.00 TiB / 120.00 GiB free]\n2 PVs total"),
    V2(id="lvm-pvdisplay-v2-0011", tool="lvm", operation="pvdisplay",
       complexity="diagnostic",
       user_input="Capacity planning ticket asks how much unallocated space is left across all PVs.",
       args={'operation': 'pvdisplay'},
       answer="PV /dev/sdb   VG vg_data   lvm2 [500.00 GiB / 5.00 GiB free]\nPV /dev/sdc   VG vg_backup lvm2 [1.00 TiB / 120.00 GiB free]\n2 PVs total"),
    V2(id="lvm-vgdisplay-v2-0012", tool="lvm", operation="vgdisplay",
       complexity="single",
       user_input="Show the volume group details for vg_data.",
       args={'operation': 'vgdisplay', 'vg': 'vg_data'},
       answer="vg_data\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0013", tool="lvm", operation="vgdisplay",
       complexity="single",
       user_input="List all the volume groups configured on this host.",
       args={'operation': 'vgdisplay'},
       answer="VG vg_data   500.00 GiB   10.00 GiB free\nVG vg_backup 1.00 TiB    120.00 GiB free\n2 VGs total"),
    V2(id="lvm-vgdisplay-v2-0014", tool="lvm", operation="vgdisplay",
       complexity="diagnostic",
       user_input="The db team says they're almost out of room, how much free space is actually left in vg_db?",
       args={'operation': 'vgdisplay', 'vg': 'vg_db'},
       answer="vg_db\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0015", tool="lvm", operation="vgdisplay",
       complexity="single",
       user_input="Pull up vgdisplay for vg_logs.",
       args={'operation': 'vgdisplay', 'vg': 'vg_logs'},
       answer="vg_logs\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0016", tool="lvm", operation="vgdisplay",
       complexity="multi",
       user_input="Show me vg_backup first, then we'll extend it if there's less than 10G free.",
       args={'operation': 'vgdisplay', 'vg': 'vg_backup'},
       answer="vg_backup\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0017", tool="lvm", operation="vgdisplay",
       complexity="diagnostic",
       user_input="Is vg_prod even mounted anywhere useful, or is it an orphaned group from the old raid setup?",
       args={'operation': 'vgdisplay', 'vg': 'vg_prod'},
       answer="vg_prod\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0018", tool="lvm", operation="vgdisplay",
       complexity="single",
       user_input="How many physical volumes back vg_staging?",
       args={'operation': 'vgdisplay', 'vg': 'vg_staging'},
       answer="vg_staging\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0019", tool="lvm", operation="vgdisplay",
       complexity="diagnostic",
       user_input="Before we add a new disk, what's the current extent size and total capacity on vg_cache?",
       args={'operation': 'vgdisplay', 'vg': 'vg_cache'},
       answer="vg_cache\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0020", tool="lvm", operation="vgdisplay",
       complexity="single",
       user_input="Give me every volume group on mail-gw2 with their sizes.",
       args={'operation': 'vgdisplay'},
       answer="VG vg_data   500.00 GiB   10.00 GiB free\nVG vg_backup 1.00 TiB    120.00 GiB free\n2 VGs total"),
    V2(id="lvm-vgdisplay-v2-0021", tool="lvm", operation="vgdisplay",
       complexity="multi",
       user_input="Check vg_home's free space, then create a new logical volume in it if there's room.",
       args={'operation': 'vgdisplay', 'vg': 'vg_home'},
       answer="vg_home\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-vgdisplay-v2-0022", tool="lvm", operation="vgdisplay",
       complexity="diagnostic",
       user_input="Ticket #4471 asks whether vg_build has enough headroom for a 50G logical volume.",
       args={'operation': 'vgdisplay', 'vg': 'vg_build'},
       answer="vg_build\n  VG Size 500.00 GiB\n  PE Size 4.00 MiB\n  Total PE 128000\n  Free  PE / Size 2560 / 10.00 GiB\n  Cur LV 3"),
    V2(id="lvm-lvdisplay-v2-0023", tool="lvm", operation="lvdisplay",
       complexity="single",
       user_input="Show me the logical volume attributes for /dev/vg_data/lv_home.",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_data/lv_home'},
       answer="/dev/vg_data/lv_home\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0024", tool="lvm", operation="lvdisplay",
       complexity="single",
       user_input="List every logical volume on this system.",
       args={'operation': 'lvdisplay'},
       answer="LV /dev/vg_data/lv_home   20.00 GiB   active\nLV /dev/vg_data/lv_var    10.00 GiB   active\nLV /dev/vg_backup/lv_backup 200.00 GiB active\n3 LVs total"),
    V2(id="lvm-lvdisplay-v2-0025", tool="lvm", operation="lvdisplay",
       complexity="diagnostic",
       user_input="The app is complaining about disk space, how big is /dev/vg_db/lv_backup actually and how full is it allocated?",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_db/lv_backup'},
       answer="/dev/vg_db/lv_backup\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0026", tool="lvm", operation="lvdisplay",
       complexity="single",
       user_input="Pull up lvdisplay for vg_logs//dev/vg_logs/lv_db.",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_logs/lv_db'},
       answer="/dev/vg_logs/lv_db\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0027", tool="lvm", operation="lvdisplay",
       complexity="multi",
       user_input="Show /dev/vg_backup/lv_logs's current size, then extend it by 5G if it's under 20G.",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_backup/lv_logs'},
       answer="/dev/vg_backup/lv_logs\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0028", tool="lvm", operation="lvdisplay",
       complexity="diagnostic",
       user_input="Is /dev/vg_prod/lv_cache even active right now, or did it get left in an inactive state after the reboot?",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_prod/lv_cache'},
       answer="/dev/vg_prod/lv_cache\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0029", tool="lvm", operation="lvdisplay",
       complexity="single",
       user_input="What LV path and size does /dev/vg_staging/lv_app in vg_staging have?",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_staging/lv_app'},
       answer="/dev/vg_staging/lv_app\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0030", tool="lvm", operation="lvdisplay",
       complexity="diagnostic",
       user_input="Before we shrink anything, confirm /dev/vg_cache/lv_mysql's current size and whether it's in use.",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_cache/lv_mysql'},
       answer="/dev/vg_cache/lv_mysql\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0031", tool="lvm", operation="lvdisplay",
       complexity="single",
       user_input="Give me a full LV listing for mail-gw2.",
       args={'operation': 'lvdisplay'},
       answer="LV /dev/vg_data/lv_home   20.00 GiB   active\nLV /dev/vg_data/lv_var    10.00 GiB   active\nLV /dev/vg_backup/lv_backup 200.00 GiB active\n3 LVs total"),
    V2(id="lvm-lvdisplay-v2-0032", tool="lvm", operation="lvdisplay",
       complexity="multi",
       user_input="Check /dev/vg_home/lv_build first, then we'll decide whether it needs to be reduced.",
       args={'operation': 'lvdisplay', 'lv': '/dev/vg_home/lv_build'},
       answer="/dev/vg_home/lv_build\n  LV Size 20.00 GiB\n  Current LE 5120\n  LV Status available\n  # open 1"),
    V2(id="lvm-lvdisplay-v2-0033", tool="lvm", operation="lvdisplay",
       complexity="diagnostic",
       user_input="Compliance asked for a snapshot of all logical volume sizes on this host.",
       args={'operation': 'lvdisplay'},
       answer="LV /dev/vg_data/lv_home   20.00 GiB   active\nLV /dev/vg_data/lv_var    10.00 GiB   active\nLV /dev/vg_backup/lv_backup 200.00 GiB active\n3 LVs total"),
    V2(id="lvm-pvcreate-v2-0034", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="Initialise /dev/sdd1 as a physical volume, it's a fresh disk we just attached.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdd1'},
       answer="Physical volume \"/dev/sdd1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0035", tool="lvm", operation="pvcreate",
       complexity="multi",
       user_input="Turn /dev/sde into a physical volume, then add it to vg_app right after.",
       args={'operation': 'pvcreate', 'pv': '/dev/sde'},
       answer="Physical volume \"/dev/sde\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0036", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="Prep /dev/nvme0n1p1 for LVM use.",
       args={'operation': 'pvcreate', 'pv': '/dev/nvme0n1p1'},
       answer="Physical volume \"/dev/nvme0n1p1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0037", tool="lvm", operation="pvcreate",
       complexity="diagnostic",
       user_input="We added a new block device but partitioning tools aren't showing it as usable for volume management yet, can you initialise /dev/nvme1n1 directly?",
       args={'operation': 'pvcreate', 'pv': '/dev/nvme1n1'},
       answer="Physical volume \"/dev/nvme1n1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0038", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="Run pvcreate against /dev/sdf1.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdf1'},
       answer="Physical volume \"/dev/sdf1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0039", tool="lvm", operation="pvcreate",
       complexity="multi",
       user_input="Initialise /dev/sdg for LVM, then create a new volume group called vg_prod on top of it.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdg'},
       answer="Physical volume \"/dev/sdg\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0040", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="Mark /dev/xvdb as an LVM physical volume.",
       args={'operation': 'pvcreate', 'pv': '/dev/xvdb'},
       answer="Physical volume \"/dev/xvdb\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0041", tool="lvm", operation="pvcreate",
       complexity="diagnostic",
       user_input="Ticket wants extra capacity on storage04 \u2014 is /dev/xvdc1 even initialised for LVM yet?",
       args={'operation': 'pvcreate', 'pv': '/dev/xvdc1'},
       answer="Physical volume \"/dev/xvdc1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0042", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="Set up /dev/sdh as a physical volume before we hand it to the storage team.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdh'},
       answer="Physical volume \"/dev/sdh\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0043", tool="lvm", operation="pvcreate",
       complexity="multi",
       user_input="Initialise /dev/sdi1, then extend vg_home with it once it's ready.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdi1'},
       answer="Physical volume \"/dev/sdi1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0044", tool="lvm", operation="pvcreate",
       complexity="single",
       user_input="We just partitioned /dev/sdj, go ahead and initialise it for LVM.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdj'},
       answer="Physical volume \"/dev/sdj\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-pvcreate-v2-0045", tool="lvm", operation="pvcreate",
       complexity="diagnostic",
       user_input="The provisioning job failed at the volume-group step because /dev/sdk1 was never set up \u2014 initialise it now.",
       args={'operation': 'pvcreate', 'pv': '/dev/sdk1'},
       answer="Physical volume \"/dev/sdk1\" successfully created.\nsize 500.00 GiB, no VG assigned"),
    V2(id="lvm-vgcreate-v2-0046", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="Create a volume group named vg_app on top of /dev/sdb.",
       args={'operation': 'vgcreate', 'vg': 'vg_app', 'pv': '/dev/sdb'},
       answer="Volume group \"vg_app\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdb"),
    V2(id="lvm-vgcreate-v2-0047", tool="lvm", operation="vgcreate",
       complexity="multi",
       user_input="Build vg_db from /dev/sdc, then we'll carve out a logical volume in it.",
       args={'operation': 'vgcreate', 'vg': 'vg_db', 'pv': '/dev/sdc'},
       answer="Volume group \"vg_db\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdc"),
    V2(id="lvm-vgcreate-v2-0048", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="Set up a new VG called vg_logs using /dev/sdd1 as the backing disk.",
       args={'operation': 'vgcreate', 'vg': 'vg_logs', 'pv': '/dev/sdd1'},
       answer="Volume group \"vg_logs\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdd1"),
    V2(id="lvm-vgcreate-v2-0049", tool="lvm", operation="vgcreate",
       complexity="diagnostic",
       user_input="We have /dev/sde initialised but no group over it yet \u2014 can you create vg_backup on it?",
       args={'operation': 'vgcreate', 'vg': 'vg_backup', 'pv': '/dev/sde'},
       answer="Volume group \"vg_backup\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sde"),
    V2(id="lvm-vgcreate-v2-0050", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="Make vg_prod out of /dev/nvme0n1p1.",
       args={'operation': 'vgcreate', 'vg': 'vg_prod', 'pv': '/dev/nvme0n1p1'},
       answer="Volume group \"vg_prod\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/nvme0n1p1"),
    V2(id="lvm-vgcreate-v2-0051", tool="lvm", operation="vgcreate",
       complexity="multi",
       user_input="Create vg_staging on /dev/nvme1n1, then create a 50G logical volume called lv_app in it.",
       args={'operation': 'vgcreate', 'vg': 'vg_staging', 'pv': '/dev/nvme1n1'},
       answer="Volume group \"vg_staging\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/nvme1n1"),
    V2(id="lvm-vgcreate-v2-0052", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="vgcreate vg_cache using /dev/sdf1 please.",
       args={'operation': 'vgcreate', 'vg': 'vg_cache', 'pv': '/dev/sdf1'},
       answer="Volume group \"vg_cache\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdf1"),
    V2(id="lvm-vgcreate-v2-0053", tool="lvm", operation="vgcreate",
       complexity="diagnostic",
       user_input="Storage expansion ticket asks for a new group called vg_media backed by /dev/sdg \u2014 has that been done yet?",
       args={'operation': 'vgcreate', 'vg': 'vg_media', 'pv': '/dev/sdg'},
       answer="Volume group \"vg_media\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdg"),
    V2(id="lvm-vgcreate-v2-0054", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="Stand up vg_home on /dev/xvdb for the new application.",
       args={'operation': 'vgcreate', 'vg': 'vg_home', 'pv': '/dev/xvdb'},
       answer="Volume group \"vg_home\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/xvdb"),
    V2(id="lvm-vgcreate-v2-0055", tool="lvm", operation="vgcreate",
       complexity="multi",
       user_input="Create vg_build from /dev/xvdc1 and then extend it later with the second disk once it arrives.",
       args={'operation': 'vgcreate', 'vg': 'vg_build', 'pv': '/dev/xvdc1'},
       answer="Volume group \"vg_build\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/xvdc1"),
    V2(id="lvm-vgcreate-v2-0056", tool="lvm", operation="vgcreate",
       complexity="single",
       user_input="We need a fresh volume group vg_archive using /dev/sdh as its only member for now.",
       args={'operation': 'vgcreate', 'vg': 'vg_archive', 'pv': '/dev/sdh'},
       answer="Volume group \"vg_archive\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdh"),
    V2(id="lvm-vgcreate-v2-0057", tool="lvm", operation="vgcreate",
       complexity="diagnostic",
       user_input="Provisioning script says vg_web doesn't exist on this host \u2014 create it against /dev/sdi1.",
       args={'operation': 'vgcreate', 'vg': 'vg_web', 'pv': '/dev/sdi1'},
       answer="Volume group \"vg_web\" successfully created\nExtent Size 4.00 MiB, Total PE 128000, PV /dev/sdi1"),
    V2(id="lvm-lvcreate-v2-0058", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="Create a 10G logical volume called lv_db in vg_data.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_db', 'vg': 'vg_data', 'size': '10G'},
       answer="Logical volume \"lv_db\" created.\n/dev/vg_data/lv_db  10G  active"),
    V2(id="lvm-lvcreate-v2-0059", tool="lvm", operation="lvcreate",
       complexity="multi",
       user_input="Create lv_logs at 500M in vg_app, then format it once it's up.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_logs', 'vg': 'vg_app', 'size': '500M'},
       answer="Logical volume \"lv_logs\" created.\n/dev/vg_app/lv_logs  500M  active"),
    V2(id="lvm-lvcreate-v2-0060", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="Carve out +5G for lv_cache inside vg_db.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_cache', 'vg': 'vg_db', 'size': '+5G'},
       answer="Logical volume \"lv_cache\" created.\n/dev/vg_db/lv_cache  +5G  active"),
    V2(id="lvm-lvcreate-v2-0061", tool="lvm", operation="lvcreate",
       complexity="diagnostic",
       user_input="The app team needs a new mount point for their database, can you provision 20G as lv_app in vg_logs?",
       args={'operation': 'lvcreate', 'lv_name': 'lv_app', 'vg': 'vg_logs', 'size': '20G'},
       answer="Logical volume \"lv_app\" created.\n/dev/vg_logs/lv_app  20G  active"),
    V2(id="lvm-lvcreate-v2-0062", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="lvcreate lv_mysql, 1T, in vg_backup.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_mysql', 'vg': 'vg_backup', 'size': '1T'},
       answer="Logical volume \"lv_mysql\" created.\n/dev/vg_backup/lv_mysql  1T  active"),
    V2(id="lvm-lvcreate-v2-0063", tool="lvm", operation="lvcreate",
       complexity="multi",
       user_input="Create a +20G volume named lv_web in vg_prod, then extend it further if the app team asks.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_web', 'vg': 'vg_prod', 'size': '+20G'},
       answer="Logical volume \"lv_web\" created.\n/dev/vg_prod/lv_web  +20G  active"),
    V2(id="lvm-lvcreate-v2-0064", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="Give me a new logical volume lv_build sized 250G out of vg_staging.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_build', 'vg': 'vg_staging', 'size': '250G'},
       answer="Logical volume \"lv_build\" created.\n/dev/vg_staging/lv_build  250G  active"),
    V2(id="lvm-lvcreate-v2-0065", tool="lvm", operation="lvcreate",
       complexity="diagnostic",
       user_input="Ticket #5521 requests a fresh 50G volume for logs \u2014 call it lv_swap inside vg_cache.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_swap', 'vg': 'vg_cache', 'size': '50G'},
       answer="Logical volume \"lv_swap\" created.\n/dev/vg_cache/lv_swap  50G  active"),
    V2(id="lvm-lvcreate-v2-0066", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="Provision lv_export at +2G in vg_media for the new service.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_export', 'vg': 'vg_media', 'size': '+2G'},
       answer="Logical volume \"lv_export\" created.\n/dev/vg_media/lv_export  +2G  active"),
    V2(id="lvm-lvcreate-v2-0067", tool="lvm", operation="lvcreate",
       complexity="multi",
       user_input="Create lv_tmp (100G) in vg_home, then mount it under /data once it's ready.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_tmp', 'vg': 'vg_home', 'size': '100G'},
       answer="Logical volume \"lv_tmp\" created.\n/dev/vg_home/lv_tmp  100G  active"),
    V2(id="lvm-lvcreate-v2-0068", tool="lvm", operation="lvcreate",
       complexity="single",
       user_input="Set up a 2T LV named lv_media under vg_build.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_media', 'vg': 'vg_build', 'size': '2T'},
       answer="Logical volume \"lv_media\" created.\n/dev/vg_build/lv_media  2T  active"),
    V2(id="lvm-lvcreate-v2-0069", tool="lvm", operation="lvcreate",
       complexity="diagnostic",
       user_input="We're onboarding a new workload that needs its own volume \u2014 create +10G as lv_home in vg_archive.",
       args={'operation': 'lvcreate', 'lv_name': 'lv_home', 'vg': 'vg_archive', 'size': '+10G'},
       answer="Logical volume \"lv_home\" created.\n/dev/vg_archive/lv_home  +10G  active"),
    V2(id="lvm-lvextend-v2-0070", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="Extend /dev/vg_data/lv_cache by 20G.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_data/lv_cache', 'size': '20G'},
       answer="Size of logical volume /dev/vg_data/lv_cache changed.\nLogical volume /dev/vg_data/lv_cache successfully resized."),
    V2(id="lvm-lvextend-v2-0071", tool="lvm", operation="lvextend",
       complexity="multi",
       user_input="Extend /dev/vg_app/lv_app to 1T, then resize the filesystem on top of it.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_app/lv_app', 'size': '1T'},
       answer="Size of logical volume /dev/vg_app/lv_app changed.\nLogical volume /dev/vg_app/lv_app successfully resized."),
    V2(id="lvm-lvextend-v2-0072", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="Grow /dev/vg_db/lv_mysql by +20G, it's running low on space.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_db/lv_mysql', 'size': '+20G'},
       answer="Size of logical volume /dev/vg_db/lv_mysql changed.\nLogical volume /dev/vg_db/lv_mysql successfully resized."),
    V2(id="lvm-lvextend-v2-0073", tool="lvm", operation="lvextend",
       complexity="diagnostic",
       user_input="Disk usage alerts are firing on the app server, can you check /dev/vg_logs/lv_web and add 250G if it's tight?",
       args={'operation': 'lvextend', 'lv': '/dev/vg_logs/lv_web', 'size': '250G'},
       answer="Size of logical volume /dev/vg_logs/lv_web changed.\nLogical volume /dev/vg_logs/lv_web successfully resized."),
    V2(id="lvm-lvextend-v2-0074", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="lvextend /dev/vg_backup/lv_build -L 50G.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_backup/lv_build', 'size': '50G'},
       answer="Size of logical volume /dev/vg_backup/lv_build changed.\nLogical volume /dev/vg_backup/lv_build successfully resized."),
    V2(id="lvm-lvextend-v2-0075", tool="lvm", operation="lvextend",
       complexity="multi",
       user_input="Extend /dev/vg_prod/lv_swap by +2G and then verify the new size with a display.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_prod/lv_swap', 'size': '+2G'},
       answer="Size of logical volume /dev/vg_prod/lv_swap changed.\nLogical volume /dev/vg_prod/lv_swap successfully resized."),
    V2(id="lvm-lvextend-v2-0076", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="Bump /dev/vg_staging/lv_export up by 100G.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_staging/lv_export', 'size': '100G'},
       answer="Size of logical volume /dev/vg_staging/lv_export changed.\nLogical volume /dev/vg_staging/lv_export successfully resized."),
    V2(id="lvm-lvextend-v2-0077", tool="lvm", operation="lvextend",
       complexity="diagnostic",
       user_input="The database is throwing 'no space left' errors \u2014 extend /dev/vg_cache/lv_tmp by 2T to relieve it.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_cache/lv_tmp', 'size': '2T'},
       answer="Size of logical volume /dev/vg_cache/lv_tmp changed.\nLogical volume /dev/vg_cache/lv_tmp successfully resized."),
    V2(id="lvm-lvextend-v2-0078", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="Add +10G of space to /dev/vg_media/lv_media.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_media/lv_media', 'size': '+10G'},
       answer="Size of logical volume /dev/vg_media/lv_media changed.\nLogical volume /dev/vg_media/lv_media successfully resized."),
    V2(id="lvm-lvextend-v2-0079", tool="lvm", operation="lvextend",
       complexity="multi",
       user_input="Extend /dev/vg_home/lv_home to 10G, then run growfs afterward.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_home/lv_home', 'size': '10G'},
       answer="Size of logical volume /dev/vg_home/lv_home changed.\nLogical volume /dev/vg_home/lv_home successfully resized."),
    V2(id="lvm-lvextend-v2-0080", tool="lvm", operation="lvextend",
       complexity="single",
       user_input="Resize /dev/vg_build/lv_var up by 500M for the backup job.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_build/lv_var', 'size': '500M'},
       answer="Size of logical volume /dev/vg_build/lv_var changed.\nLogical volume /dev/vg_build/lv_var successfully resized."),
    V2(id="lvm-lvextend-v2-0081", tool="lvm", operation="lvextend",
       complexity="diagnostic",
       user_input="Backup job keeps failing partway through \u2014 is /dev/vg_archive/lv_backup too small? Extend it by +5G and retry.",
       args={'operation': 'lvextend', 'lv': '/dev/vg_archive/lv_backup', 'size': '+5G'},
       answer="Size of logical volume /dev/vg_archive/lv_backup changed.\nLogical volume /dev/vg_archive/lv_backup successfully resized."),
    V2(id="lvm-vgextend-v2-0082", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="Add /dev/nvme0n1p1 to vg_db.",
       args={'operation': 'vgextend', 'vg': 'vg_db', 'pv': '/dev/nvme0n1p1'},
       answer="Volume group \"vg_db\" successfully extended\nnew PV /dev/nvme0n1p1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0083", tool="lvm", operation="vgextend",
       complexity="multi",
       user_input="Extend vg_logs with /dev/nvme1n1, then extend the logical volume once there's room.",
       args={'operation': 'vgextend', 'vg': 'vg_logs', 'pv': '/dev/nvme1n1'},
       answer="Volume group \"vg_logs\" successfully extended\nnew PV /dev/nvme1n1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0084", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="vgextend vg_backup /dev/sdf1.",
       args={'operation': 'vgextend', 'vg': 'vg_backup', 'pv': '/dev/sdf1'},
       answer="Volume group \"vg_backup\" successfully extended\nnew PV /dev/sdf1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0085", tool="lvm", operation="vgextend",
       complexity="diagnostic",
       user_input="vg_prod is nearly full and we just attached /dev/sdg, can you add it in?",
       args={'operation': 'vgextend', 'vg': 'vg_prod', 'pv': '/dev/sdg'},
       answer="Volume group \"vg_prod\" successfully extended\nnew PV /dev/sdg added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0086", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="Grow vg_staging by adding /dev/xvdb as a new member.",
       args={'operation': 'vgextend', 'vg': 'vg_staging', 'pv': '/dev/xvdb'},
       answer="Volume group \"vg_staging\" successfully extended\nnew PV /dev/xvdb added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0087", tool="lvm", operation="vgextend",
       complexity="multi",
       user_input="Add /dev/xvdc1 to vg_cache, then run a display to confirm the new free space.",
       args={'operation': 'vgextend', 'vg': 'vg_cache', 'pv': '/dev/xvdc1'},
       answer="Volume group \"vg_cache\" successfully extended\nnew PV /dev/xvdc1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0088", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="Bring /dev/sdh into vg_media.",
       args={'operation': 'vgextend', 'vg': 'vg_media', 'pv': '/dev/sdh'},
       answer="Volume group \"vg_media\" successfully extended\nnew PV /dev/sdh added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0089", tool="lvm", operation="vgextend",
       complexity="diagnostic",
       user_input="Storage ticket says /dev/sdi1 is ready to be added \u2014 is vg_home still short on capacity, and should we extend it now?",
       args={'operation': 'vgextend', 'vg': 'vg_home', 'pv': '/dev/sdi1'},
       answer="Volume group \"vg_home\" successfully extended\nnew PV /dev/sdi1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0090", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="Extend vg_build to include /dev/sdj.",
       args={'operation': 'vgextend', 'vg': 'vg_build', 'pv': '/dev/sdj'},
       answer="Volume group \"vg_build\" successfully extended\nnew PV /dev/sdj added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0091", tool="lvm", operation="vgextend",
       complexity="multi",
       user_input="Add /dev/sdk1 to vg_archive, then extend lv_db by 100G.",
       args={'operation': 'vgextend', 'vg': 'vg_archive', 'pv': '/dev/sdk1'},
       answer="Volume group \"vg_archive\" successfully extended\nnew PV /dev/sdk1 added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0092", tool="lvm", operation="vgextend",
       complexity="single",
       user_input="We just initialised /dev/sdb, fold it into vg_web now.",
       args={'operation': 'vgextend', 'vg': 'vg_web', 'pv': '/dev/sdb'},
       answer="Volume group \"vg_web\" successfully extended\nnew PV /dev/sdb added, total VG size increased"),
    V2(id="lvm-vgextend-v2-0093", tool="lvm", operation="vgextend",
       complexity="diagnostic",
       user_input="Capacity planning wants vg_mail bigger before month end \u2014 extend it with /dev/sdc.",
       args={'operation': 'vgextend', 'vg': 'vg_mail', 'pv': '/dev/sdc'},
       answer="Volume group \"vg_mail\" successfully extended\nnew PV /dev/sdc added, total VG size increased"),
    V2(id="lvm-pvremove-v2-0094", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="Remove /dev/sdf1 as a physical volume, it's been fully evacuated.",
       args={'operation': 'pvremove', 'pv': '/dev/sdf1'},
       answer="Labels on physical volume \"/dev/sdf1\" successfully wiped.\n/dev/sdf1 removed from LVM"),
    V2(id="lvm-pvremove-v2-0095", tool="lvm", operation="pvremove",
       complexity="multi",
       user_input="Confirmed with the team, /dev/sdg is decommissioned \u2014 remove it as a PV and then we'll pull the disk.",
       args={'operation': 'pvremove', 'pv': '/dev/sdg'},
       answer="Labels on physical volume \"/dev/sdg\" successfully wiped.\n/dev/sdg removed from LVM"),
    V2(id="lvm-pvremove-v2-0096", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="Wipe the LVM metadata off /dev/xvdb.",
       args={'operation': 'pvremove', 'pv': '/dev/xvdb'},
       answer="Labels on physical volume \"/dev/xvdb\" successfully wiped.\n/dev/xvdb removed from LVM"),
    V2(id="lvm-pvremove-v2-0097", tool="lvm", operation="pvremove",
       complexity="diagnostic",
       user_input="We're retiring an old disk, is /dev/xvdc1 still part of any VG before we remove it?",
       args={'operation': 'pvremove', 'pv': '/dev/xvdc1'},
       answer="Labels on physical volume \"/dev/xvdc1\" successfully wiped.\n/dev/xvdc1 removed from LVM"),
    V2(id="lvm-pvremove-v2-0098", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="pvremove /dev/sdh, it's no longer needed.",
       args={'operation': 'pvremove', 'pv': '/dev/sdh'},
       answer="Labels on physical volume \"/dev/sdh\" successfully wiped.\n/dev/sdh removed from LVM"),
    V2(id="lvm-pvremove-v2-0099", tool="lvm", operation="pvremove",
       complexity="multi",
       user_input="Migrate the data off /dev/sdi1 is done, remove it now and then remove the disk from the chassis.",
       args={'operation': 'pvremove', 'pv': '/dev/sdi1'},
       answer="Labels on physical volume \"/dev/sdi1\" successfully wiped.\n/dev/sdi1 removed from LVM"),
    V2(id="lvm-pvremove-v2-0100", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="Strip the LVM label from /dev/sdj.",
       args={'operation': 'pvremove', 'pv': '/dev/sdj'},
       answer="Labels on physical volume \"/dev/sdj\" successfully wiped.\n/dev/sdj removed from LVM"),
    V2(id="lvm-pvremove-v2-0101", tool="lvm", operation="pvremove",
       complexity="diagnostic",
       user_input="Change ticket #6210 approved removing /dev/sdk1 from LVM entirely \u2014 proceed.",
       args={'operation': 'pvremove', 'pv': '/dev/sdk1'},
       answer="Labels on physical volume \"/dev/sdk1\" successfully wiped.\n/dev/sdk1 removed from LVM"),
    V2(id="lvm-pvremove-v2-0102", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="This disk is being decommissioned, pvremove /dev/sdb.",
       args={'operation': 'pvremove', 'pv': '/dev/sdb'},
       answer="Labels on physical volume \"/dev/sdb\" successfully wiped.\n/dev/sdb removed from LVM"),
    V2(id="lvm-pvremove-v2-0103", tool="lvm", operation="pvremove",
       complexity="multi",
       user_input="Remove /dev/sdc as a physical volume, then verify no VG still references it.",
       args={'operation': 'pvremove', 'pv': '/dev/sdc'},
       answer="Labels on physical volume \"/dev/sdc\" successfully wiped.\n/dev/sdc removed from LVM"),
    V2(id="lvm-pvremove-v2-0104", tool="lvm", operation="pvremove",
       complexity="single",
       user_input="Take /dev/sdd1 out of LVM for good, it's failing SMART checks.",
       args={'operation': 'pvremove', 'pv': '/dev/sdd1'},
       answer="Labels on physical volume \"/dev/sdd1\" successfully wiped.\n/dev/sdd1 removed from LVM"),
    V2(id="lvm-pvremove-v2-0105", tool="lvm", operation="pvremove",
       complexity="diagnostic",
       user_input="Hardware team flagged /dev/sde for replacement \u2014 has it been removed from LVM yet? If not, remove it.",
       args={'operation': 'pvremove', 'pv': '/dev/sde'},
       answer="Labels on physical volume \"/dev/sde\" successfully wiped.\n/dev/sde removed from LVM"),
    V2(id="lvm-vgremove-v2-0106", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="Remove the volume group vg_prod, it's been decommissioned.",
       args={'operation': 'vgremove', 'vg': 'vg_prod'},
       answer="Volume group \"vg_prod\" successfully removed"),
    V2(id="lvm-vgremove-v2-0107", tool="lvm", operation="vgremove",
       complexity="multi",
       user_input="Confirmed with the app owner, tear down vg_staging entirely and then remove the underlying PV.",
       args={'operation': 'vgremove', 'vg': 'vg_staging'},
       answer="Volume group \"vg_staging\" successfully removed"),
    V2(id="lvm-vgremove-v2-0108", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="Delete vg_cache, all its logical volumes have already been backed up and removed.",
       args={'operation': 'vgremove', 'vg': 'vg_cache'},
       answer="Volume group \"vg_cache\" successfully removed"),
    V2(id="lvm-vgremove-v2-0109", tool="lvm", operation="vgremove",
       complexity="diagnostic",
       user_input="We're shutting down the old staging environment, is vg_media safe to remove now?",
       args={'operation': 'vgremove', 'vg': 'vg_media'},
       answer="Volume group \"vg_media\" successfully removed"),
    V2(id="lvm-vgremove-v2-0110", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="vgremove vg_home.",
       args={'operation': 'vgremove', 'vg': 'vg_home'},
       answer="Volume group \"vg_home\" successfully removed"),
    V2(id="lvm-vgremove-v2-0111", tool="lvm", operation="vgremove",
       complexity="multi",
       user_input="Remove vg_build, then wipe the disk it was on.",
       args={'operation': 'vgremove', 'vg': 'vg_build'},
       answer="Volume group \"vg_build\" successfully removed"),
    V2(id="lvm-vgremove-v2-0112", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="Tear down vg_archive, it's an orphaned group from the migration.",
       args={'operation': 'vgremove', 'vg': 'vg_archive'},
       answer="Volume group \"vg_archive\" successfully removed"),
    V2(id="lvm-vgremove-v2-0113", tool="lvm", operation="vgremove",
       complexity="diagnostic",
       user_input="Change ticket #6301 approved deleting vg_web \u2014 go ahead.",
       args={'operation': 'vgremove', 'vg': 'vg_web'},
       answer="Volume group \"vg_web\" successfully removed"),
    V2(id="lvm-vgremove-v2-0114", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="Get rid of vg_mail, it's no longer used by any host.",
       args={'operation': 'vgremove', 'vg': 'vg_mail'},
       answer="Volume group \"vg_mail\" successfully removed"),
    V2(id="lvm-vgremove-v2-0115", tool="lvm", operation="vgremove",
       complexity="multi",
       user_input="Remove vg_data and its LVs, then confirm no volumes remain.",
       args={'operation': 'vgremove', 'vg': 'vg_data'},
       answer="Volume group \"vg_data\" successfully removed"),
    V2(id="lvm-vgremove-v2-0116", tool="lvm", operation="vgremove",
       complexity="single",
       user_input="Decommission vg_app completely.",
       args={'operation': 'vgremove', 'vg': 'vg_app'},
       answer="Volume group \"vg_app\" successfully removed"),
    V2(id="lvm-vgremove-v2-0117", tool="lvm", operation="vgremove",
       complexity="diagnostic",
       user_input="Audit flagged vg_db as unused for 6 months \u2014 remove it since the team confirmed.",
       args={'operation': 'vgremove', 'vg': 'vg_db'},
       answer="Volume group \"vg_db\" successfully removed"),
    V2(id="lvm-lvremove-v2-0118", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="Remove /dev/vg_logs/lv_web, it's been fully migrated off.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_logs/lv_web'},
       answer="Logical volume \"/dev/vg_logs/lv_web\" successfully removed"),
    V2(id="lvm-lvremove-v2-0119", tool="lvm", operation="lvremove",
       complexity="multi",
       user_input="Delete /dev/vg_backup/lv_build now that the data is copied elsewhere, then reclaim the space into the VG.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_backup/lv_build'},
       answer="Logical volume \"/dev/vg_backup/lv_build\" successfully removed"),
    V2(id="lvm-lvremove-v2-0120", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="lvremove /dev/vg_prod/lv_swap.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_prod/lv_swap'},
       answer="Logical volume \"/dev/vg_prod/lv_swap\" successfully removed"),
    V2(id="lvm-lvremove-v2-0121", tool="lvm", operation="lvremove",
       complexity="diagnostic",
       user_input="This volume hasn't been mounted in months according to the audit, is /dev/vg_staging/lv_export safe to remove?",
       args={'operation': 'lvremove', 'lv': '/dev/vg_staging/lv_export'},
       answer="Logical volume \"/dev/vg_staging/lv_export\" successfully removed"),
    V2(id="lvm-lvremove-v2-0122", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="Get rid of /dev/vg_cache/lv_tmp, the app was decommissioned last week.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_cache/lv_tmp'},
       answer="Logical volume \"/dev/vg_cache/lv_tmp\" successfully removed"),
    V2(id="lvm-lvremove-v2-0123", tool="lvm", operation="lvremove",
       complexity="multi",
       user_input="Remove /dev/vg_media/lv_media, then extend lv_backup with the freed space.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_media/lv_media'},
       answer="Logical volume \"/dev/vg_media/lv_media\" successfully removed"),
    V2(id="lvm-lvremove-v2-0124", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="Delete the logical volume /dev/vg_home/lv_home.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_home/lv_home'},
       answer="Logical volume \"/dev/vg_home/lv_home\" successfully removed"),
    V2(id="lvm-lvremove-v2-0125", tool="lvm", operation="lvremove",
       complexity="diagnostic",
       user_input="Change ticket #6455 approved removing /dev/vg_build/lv_var \u2014 confirm and proceed.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_build/lv_var'},
       answer="Logical volume \"/dev/vg_build/lv_var\" successfully removed"),
    V2(id="lvm-lvremove-v2-0126", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="Tear down /dev/vg_archive/lv_backup, it was only used for the migration.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_archive/lv_backup'},
       answer="Logical volume \"/dev/vg_archive/lv_backup\" successfully removed"),
    V2(id="lvm-lvremove-v2-0127", tool="lvm", operation="lvremove",
       complexity="multi",
       user_input="Remove /dev/vg_web/lv_db and then verify the VG shows the space back as free.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_web/lv_db'},
       answer="Logical volume \"/dev/vg_web/lv_db\" successfully removed"),
    V2(id="lvm-lvremove-v2-0128", tool="lvm", operation="lvremove",
       complexity="single",
       user_input="Remove /dev/vg_mail/lv_logs for good, backups are confirmed.",
       args={'operation': 'lvremove', 'lv': '/dev/vg_mail/lv_logs'},
       answer="Logical volume \"/dev/vg_mail/lv_logs\" successfully removed"),
    V2(id="lvm-lvreduce-v2-0129", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="Shrink /dev/vg_cache/lv_var down to +20G.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_cache/lv_var', 'size': '+20G'},
       answer="WARNING: Reducing active logical volume to +20G\nSize of logical volume /dev/vg_cache/lv_var changed to +20G.\nLogical volume /dev/vg_cache/lv_var successfully resized."),
    V2(id="lvm-lvreduce-v2-0130", tool="lvm", operation="lvreduce",
       complexity="multi",
       user_input="Reduce /dev/vg_media/lv_backup to 250G after we've already shrunk the filesystem, then verify the new size.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_media/lv_backup', 'size': '250G'},
       answer="WARNING: Reducing active logical volume to 250G\nSize of logical volume /dev/vg_media/lv_backup changed to 250G.\nLogical volume /dev/vg_media/lv_backup successfully resized."),
    V2(id="lvm-lvreduce-v2-0131", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="lvreduce /dev/vg_home/lv_db to 50G.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_home/lv_db', 'size': '50G'},
       answer="WARNING: Reducing active logical volume to 50G\nSize of logical volume /dev/vg_home/lv_db changed to 50G.\nLogical volume /dev/vg_home/lv_db successfully resized."),
    V2(id="lvm-lvreduce-v2-0132", tool="lvm", operation="lvreduce",
       complexity="diagnostic",
       user_input="We over-provisioned this volume, can /dev/vg_build/lv_logs safely come down to +2G?",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_build/lv_logs', 'size': '+2G'},
       answer="WARNING: Reducing active logical volume to +2G\nSize of logical volume /dev/vg_build/lv_logs changed to +2G.\nLogical volume /dev/vg_build/lv_logs successfully resized."),
    V2(id="lvm-lvreduce-v2-0133", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="Cut /dev/vg_archive/lv_cache back to 100G, the filesystem's already been resized down.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_archive/lv_cache', 'size': '100G'},
       answer="WARNING: Reducing active logical volume to 100G\nSize of logical volume /dev/vg_archive/lv_cache changed to 100G.\nLogical volume /dev/vg_archive/lv_cache successfully resized."),
    V2(id="lvm-lvreduce-v2-0134", tool="lvm", operation="lvreduce",
       complexity="multi",
       user_input="Shrink /dev/vg_web/lv_app to 2T, then reclaim the freed extents into vg_backup.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_web/lv_app', 'size': '2T'},
       answer="WARNING: Reducing active logical volume to 2T\nSize of logical volume /dev/vg_web/lv_app changed to 2T.\nLogical volume /dev/vg_web/lv_app successfully resized."),
    V2(id="lvm-lvreduce-v2-0135", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="Reduce the size of /dev/vg_mail/lv_mysql to +10G.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_mail/lv_mysql', 'size': '+10G'},
       answer="WARNING: Reducing active logical volume to +10G\nSize of logical volume /dev/vg_mail/lv_mysql changed to +10G.\nLogical volume /dev/vg_mail/lv_mysql successfully resized."),
    V2(id="lvm-lvreduce-v2-0136", tool="lvm", operation="lvreduce",
       complexity="diagnostic",
       user_input="Change ticket #6602 wants /dev/vg_data/lv_web reduced to 10G to free up room in the group \u2014 has the filesystem shrink happened first?",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_data/lv_web', 'size': '10G'},
       answer="WARNING: Reducing active logical volume to 10G\nSize of logical volume /dev/vg_data/lv_web changed to 10G.\nLogical volume /dev/vg_data/lv_web successfully resized."),
    V2(id="lvm-lvreduce-v2-0137", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="Bring /dev/vg_app/lv_build down to 500M, it's way oversized for its workload.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_app/lv_build', 'size': '500M'},
       answer="WARNING: Reducing active logical volume to 500M\nSize of logical volume /dev/vg_app/lv_build changed to 500M.\nLogical volume /dev/vg_app/lv_build successfully resized."),
    V2(id="lvm-lvreduce-v2-0138", tool="lvm", operation="lvreduce",
       complexity="multi",
       user_input="Reduce /dev/vg_db/lv_swap to +5G, then extend lv_cache with the space we get back.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_db/lv_swap', 'size': '+5G'},
       answer="WARNING: Reducing active logical volume to +5G\nSize of logical volume /dev/vg_db/lv_swap changed to +5G.\nLogical volume /dev/vg_db/lv_swap successfully resized."),
    V2(id="lvm-lvreduce-v2-0139", tool="lvm", operation="lvreduce",
       complexity="single",
       user_input="Shrink /dev/vg_logs/lv_export to 20G for the capacity reclaim project.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_logs/lv_export', 'size': '20G'},
       answer="WARNING: Reducing active logical volume to 20G\nSize of logical volume /dev/vg_logs/lv_export changed to 20G.\nLogical volume /dev/vg_logs/lv_export successfully resized."),
    V2(id="lvm-lvreduce-v2-0140", tool="lvm", operation="lvreduce",
       complexity="diagnostic",
       user_input="Storage review flagged /dev/vg_backup/lv_tmp as oversized \u2014 reduce it to 1T once the filesystem shrink is confirmed done.",
       args={'operation': 'lvreduce', 'lv': '/dev/vg_backup/lv_tmp', 'size': '1T'},
       answer="WARNING: Reducing active logical volume to 1T\nSize of logical volume /dev/vg_backup/lv_tmp changed to 1T.\nLogical volume /dev/vg_backup/lv_tmp successfully resized."),
]

from finetune.scenarios_v2 import check_module; check_module("lvm", SCENARIOS_V2)
