"""finetune/scenarios_v2/mariadb.py — corpus v2 scenarios for 'mariadb'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="mariadb-status-v2-0001", tool="mariadb", operation="status",
       complexity="single",
       user_input="Check the MariaDB server status on db-replica-02.",
       args={"operation": "status", "host": "db-replica-02"},
       answer="Uptime: 12 days 4h 22m\nThreads: 41 connected, 3 running\nQueries per second avg: 96.2"),
    V2(id="mariadb-status-v2-0002", tool="mariadb", operation="status",
       complexity="diagnostic",
       user_input="Checkout requests are timing out on the store front end — is the MariaDB backend even up?",
       args={"operation": "status"},
       answer="Uptime: 3 days 1h 5m\nThreads: 512 connected, 498 running\nQueries per second avg: 812.4"),
    V2(id="mariadb-status-v2-0003", tool="mariadb", operation="status",
       complexity="single",
       user_input="how long has mysqld been up on 10.4.2.9",
       args={"operation": "status", "host": "10.4.2.9"},
       answer="Uptime: 47 days 9h 0m\nThreads: 18 connected, 1 running\nQueries per second avg: 12.8"),
    V2(id="mariadb-status-v2-0004", tool="mariadb", operation="status",
       complexity="single",
       user_input="Before we cut over the reporting job, confirm the database server is healthy.",
       args={"operation": "status"},
       answer="Uptime: 22 days 0h 40m\nThreads: 9 connected, 0 running\nQueries per second avg: 4.1"),
    V2(id="mariadb-status-v2-0005", tool="mariadb", operation="status",
       complexity="diagnostic",
       user_input="Ticket INC-4471 says the order pipeline is throwing connection refused against the database tier — pull the server status to see if it's even reachable.",
       args={"operation": "status", "host": "orders-db.internal"},
       answer="mysqladmin: connect to server at 'orders-db.internal' failed\nerror: 'Can't connect to MySQL server'"),
    V2(id="mariadb-status-v2-0006", tool="mariadb", operation="status",
       complexity="multi",
       user_input="Check MariaDB status on db01, and if it's up show me the current connection count too.",
       args={"operation": "status", "host": "db01"},
       answer="Uptime: 15 days 2h 12m\nThreads: 63 connected, 5 running\nQueries per second avg: 210.7"),
    V2(id="mariadb-status-v2-0007", tool="mariadb", operation="status",
       complexity="single",
       user_input="Is the database server flapping? We've had two nftables rule changes today and I want to rule out the DB as the cause of the alerts.",
       args={"operation": "status"},
       answer="Uptime: 0 days 0h 6m\nThreads: 2 connected, 0 running\nService restarted recently."),

    V2(id="mariadb-query-v2-0001", tool="mariadb", operation="query",
       complexity="single",
       user_input="Run 'SHOW TABLE STATUS' against the analytics database.",
       args={"operation": "query", "sql": "SHOW TABLE STATUS", "database": "analytics"},
       answer="12 rows returned.\nevents  InnoDB  4,201,932 rows  1.2G\nusers   InnoDB  88,410 rows  40M"),
    V2(id="mariadb-query-v2-0002", tool="mariadb", operation="query",
       complexity="diagnostic",
       user_input="Signups are failing with a duplicate key error — can you check if there's already a row for user_id 88123 in the accounts table of the auth database?",
       args={"operation": "query", "sql": "SELECT * FROM accounts WHERE user_id=88123", "database": "auth"},
       answer="1 row returned.\nuser_id=88123  email=jsmith@example.com  created_at=2026-08-30 14:02:10"),
    V2(id="mariadb-query-v2-0003", tool="mariadb", operation="query",
       complexity="single",
       user_input="what does SHOW VARIABLES LIKE 'wait_timeout' return on the reporting server",
       args={"operation": "query", "sql": "SHOW VARIABLES LIKE 'wait_timeout'", "host": "reporting-db"},
       answer="1 row returned.\nwait_timeout = 28800"),
    V2(id="mariadb-query-v2-0004", tool="mariadb", operation="query",
       complexity="diagnostic",
       user_input="The app team says a query against the billing database has been stuck for ten minutes — list current processes to find it.",
       args={"operation": "query", "sql": "SHOW FULL PROCESSLIST", "database": "billing"},
       answer="14 rows returned.\nId=8821  User=appuser  Time=612  State=Sending data  Info=SELECT * FROM invoices..."),

    V2(id="mariadb-dump-v2-0001", tool="mariadb", operation="dump",
       complexity="single",
       user_input="Dump the billing database so we have a copy before the schema migration.",
       args={"operation": "dump", "database": "billing"},
       answer="mysqldump: dump of 'billing' complete.\nOutput size: 812M\n41 tables exported."),
    V2(id="mariadb-dump-v2-0002", tool="mariadb", operation="dump",
       complexity="diagnostic",
       user_input="A junior engineer ran an update without a WHERE clause on the customers table — grab a dump of the crm database right now before anyone touches it further.",
       args={"operation": "dump", "database": "crm"},
       answer="mysqldump: dump of 'crm' complete.\nOutput size: 340M\n19 tables exported."),
    V2(id="mariadb-dump-v2-0003", tool="mariadb", operation="dump",
       complexity="single",
       user_input="export the wordpress_prod database from db3.internal",
       args={"operation": "dump", "database": "wordpress_prod", "host": "db3.internal"},
       answer="mysqldump: dump of 'wordpress_prod' complete.\nOutput size: 96M\n14 tables exported."),
    V2(id="mariadb-dump-v2-0004", tool="mariadb", operation="dump",
       complexity="multi",
       user_input="Dump the inventory database and then confirm the resulting file isn't empty.",
       args={"operation": "dump", "database": "inventory"},
       answer="mysqldump: dump of 'inventory' complete.\nOutput size: 214M\n27 tables exported."),
    V2(id="mariadb-dump-v2-0005", tool="mariadb", operation="dump",
       complexity="single",
       user_input="We're sunsetting the legacy_reports database next week — take a backup now.",
       args={"operation": "dump", "database": "legacy_reports"},
       answer="mysqldump: dump of 'legacy_reports' complete.\nOutput size: 58M\n9 tables exported."),
    V2(id="mariadb-dump-v2-0006", tool="mariadb", operation="dump",
       complexity="single",
       user_input="Snapshot the sessions database on cache-db01 before the maintenance window.",
       args={"operation": "dump", "database": "sessions", "host": "cache-db01"},
       answer="mysqldump: dump of 'sessions' complete.\nOutput size: 12M\n3 tables exported."),
    V2(id="mariadb-dump-v2-0007", tool="mariadb", operation="dump",
       complexity="diagnostic",
       user_input="The nightly cron for the warehouse database backup silently failed — trigger a manual dump so we're not exposed tonight.",
       args={"operation": "dump", "database": "warehouse"},
       answer="mysqldump: dump of 'warehouse' complete.\nOutput size: 1.1G\n52 tables exported."),
    V2(id="mariadb-dump-v2-0008", tool="mariadb", operation="dump",
       complexity="single",
       user_input="Take a full export of the payments database from host pay-db-primary.",
       args={"operation": "dump", "database": "payments", "host": "pay-db-primary"},
       answer="mysqldump: dump of 'payments' complete.\nOutput size: 640M\n33 tables exported."),

    V2(id="mariadb-grant-v2-0001", tool="mariadb", operation="grant",
       complexity="single",
       user_input="Give the etl_svc account SELECT and INSERT on the warehouse database.",
       args={"operation": "grant", "user": "etl_svc", "database": "warehouse", "privileges": "SELECT, INSERT"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'etl_svc'@'localhost' on warehouse.*"),
    V2(id="mariadb-grant-v2-0002", tool="mariadb", operation="grant",
       complexity="diagnostic",
       user_input="The dashboard service keeps getting access denied hitting the metrics database — what privileges does it currently need, and can you grant SELECT to dash_reader on it?",
       args={"operation": "grant", "user": "dash_reader", "database": "metrics", "privileges": "SELECT"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'dash_reader'@'localhost' on metrics.*"),
    V2(id="mariadb-grant-v2-0003", tool="mariadb", operation="grant",
       complexity="single",
       user_input="set up backup_agent2 with SELECT and LOCK TABLES on all databases from host 10.0.4.5",
       args={"operation": "grant", "user": "backup_agent2", "database": "*", "privileges": "SELECT, LOCK TABLES", "host": "10.0.4.5"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'backup_agent2'@'10.0.4.5' on *.*"),
    V2(id="mariadb-grant-v2-0004", tool="mariadb", operation="grant",
       complexity="single",
       user_input="Create full access for deploy_bot on the staging_app database, connecting only from localhost.",
       args={"operation": "grant", "user": "deploy_bot", "database": "staging_app", "privileges": "ALL PRIVILEGES", "user_host": "localhost"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'deploy_bot'@'localhost' on staging_app.*"),
    V2(id="mariadb-grant-v2-0005", tool="mariadb", operation="grant",
       complexity="single",
       user_input="Grant REPLICATION SLAVE to repl_user on all databases for the new read replica.",
       args={"operation": "grant", "user": "repl_user", "database": "*", "privileges": "REPLICATION SLAVE"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'repl_user'@'localhost' on *.*"),
    V2(id="mariadb-grant-v2-0006", tool="mariadb", operation="grant",
       complexity="multi",
       user_input="Grant reporting_ro SELECT on the sales database, then check the grants took effect.",
       args={"operation": "grant", "user": "reporting_ro", "database": "sales", "privileges": "SELECT"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'reporting_ro'@'localhost' on sales.*"),
    V2(id="mariadb-grant-v2-0007", tool="mariadb", operation="grant",
       complexity="diagnostic",
       user_input="A new hire's account can't write to the audit_log database — was the grant ever applied for user compliance_writer?",
       args={"operation": "grant", "user": "compliance_writer", "database": "audit_log", "privileges": "INSERT, SELECT"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'compliance_writer'@'localhost' on audit_log.*"),
    V2(id="mariadb-grant-v2-0008", tool="mariadb", operation="grant",
       complexity="single",
       user_input="give monitor_check SELECT rights on the mysql system database from host monitor01",
       args={"operation": "grant", "user": "monitor_check", "database": "mysql", "privileges": "SELECT", "host": "monitor01"},
       answer="Query OK, 0 rows affected.\nGrant applied to 'monitor_check'@'localhost' on mysql.*"),

    V2(id="mariadb-drop_database-v2-0001", tool="mariadb", operation="drop_database",
       complexity="single",
       user_input="Drop the sandbox_test database, it's not needed anymore.",
       args={"operation": "drop_database", "database": "sandbox_test"},
       answer="Query OK, database dropped.\n'sandbox_test' removed, 6 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0002", tool="mariadb", operation="drop_database",
       complexity="diagnostic",
       user_input="The old_cms_2019 database hasn't been queried in over a year according to the audit log — is it safe to remove, and can you drop it?",
       args={"operation": "drop_database", "database": "old_cms_2019"},
       answer="Query OK, database dropped.\n'old_cms_2019' removed, 22 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0003", tool="mariadb", operation="drop_database",
       complexity="multi",
       user_input="Drop the archive_2023 database, then double check it no longer shows up when you list all databases.",
       args={"operation": "drop_database", "database": "archive_2023"},
       answer="Query OK, database dropped.\n'archive_2023' removed, 15 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0004", tool="mariadb", operation="drop_database",
       complexity="single",
       user_input="permanently remove the staging_clone database on db-staging",
       args={"operation": "drop_database", "database": "staging_clone", "host": "db-staging"},
       answer="Query OK, database dropped.\n'staging_clone' removed, 18 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0005", tool="mariadb", operation="drop_database",
       complexity="single",
       user_input="The migration off the old ticketing platform finished — drop the ticketing_legacy database.",
       args={"operation": "drop_database", "database": "ticketing_legacy"},
       answer="Query OK, database dropped.\n'ticketing_legacy' removed, 11 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0006", tool="mariadb", operation="drop_database",
       complexity="single",
       user_input="Remove the scratch_import database from the dev server, it was only for a one-off load.",
       args={"operation": "drop_database", "database": "scratch_import"},
       answer="Query OK, database dropped.\n'scratch_import' removed, 4 tables destroyed."),
    V2(id="mariadb-drop_database-v2-0007", tool="mariadb", operation="drop_database",
       complexity="diagnostic",
       user_input="Disk on db02 is at 96 percent full and the unused poc_2024 database is the biggest offender — go ahead and drop it.",
       args={"operation": "drop_database", "database": "poc_2024", "host": "db02"},
       answer="Query OK, database dropped.\n'poc_2024' removed, 8 tables destroyed."),
]

from finetune.scenarios_v2 import check_module; check_module("mariadb", SCENARIOS_V2)
