"""finetune/scenarios_v2/network.py — corpus v2 scenarios for 'network'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id='network-show-v2-0001', tool='network', operation='show',
       complexity='single',
       user_input='list every IP bound to this host',
       args={'operation': 'show'},
       answer='IPv4: ens192 10.20.4.15/24, lo 127.0.0.1/8\nIPv6: ens192 fe80::5054:ff:fe12:3a4b/64'),
    V2(id='network-show-v2-0002', tool='network', operation='show',
       complexity='diagnostic',
       user_input='the load balancer health check keeps failing, what addresses does this box actually have?',
       args={'operation': 'show'},
       answer='IPv4: ens192 10.20.4.15/24 (no VIP found)\nlo 127.0.0.1/8'),
    V2(id='network-show-v2-0003', tool='network', operation='show',
       complexity='single',
       user_input='show all addresses across every interface',
       args={'operation': 'show'},
       answer='IPv4: ens160 10.0.5.20/24, ens161 10.0.6.20/24\nlo 127.0.0.1/8'),
    V2(id='network-show-v2-0004', tool='network', operation='show',
       complexity='multi',
       user_input='show all IP addresses and then bring down whichever one is on the old VLAN',
       args={'operation': 'show'},
       answer='IPv4: ens192 10.20.4.15/24, ens193 172.16.9.5/24'),
    V2(id='network-show-v2-0005', tool='network', operation='show',
       complexity='diagnostic',
       user_input="is the secondary VIP actually assigned to eth0? the failover script says it can't find it",
       args={'operation': 'show'},
       answer='IPv4: eth0 10.5.5.5/24 (no secondary address present)'),
    V2(id='network-show-v2-0006', tool='network', operation='show',
       complexity='single',
       user_input='print all IP addresses configured on this server',
       args={'operation': 'show'},
       answer='IPv4: ens192 10.20.4.15/24\nlo 127.0.0.1/8'),
    V2(id='network-status-v2-0007', tool='network', operation='status',
       complexity='single',
       user_input='give me a one-line status for every interface',
       args={'operation': 'status'},
       answer='ens192: UP, 10.20.4.15/24\nlo: UP, 127.0.0.1/8'),
    V2(id='network-status-v2-0008', tool='network', operation='status',
       complexity='diagnostic',
       user_input='nagios says the host is unreachable, are the interfaces actually up?',
       args={'operation': 'status'},
       answer='ens192: UP, 10.20.4.15/24\nlo: UP, 127.0.0.1/8'),
    V2(id='network-status-v2-0009', tool='network', operation='status',
       complexity='single',
       user_input='quick network summary please',
       args={'operation': 'status'},
       answer='ens192: UP, 10.20.4.15/24\nens193: DOWN, no address'),
    V2(id='network-status-v2-0010', tool='network', operation='status',
       complexity='diagnostic',
       user_input='after the power blip, did every interface come back?',
       args={'operation': 'status'},
       answer='ens192: UP, ens193: UP, ens194: DOWN (was down before outage too)'),
    V2(id='network-status-v2-0011', tool='network', operation='status',
       complexity='single',
       user_input='brief interface status check before the maintenance window',
       args={'operation': 'status'},
       answer='ens192: UP, 10.20.4.15/24\nlo: UP'),
    V2(id='network-status-v2-0012', tool='network', operation='status',
       complexity='diagnostic',
       user_input='the sssd realm join is timing out, is the interface actually up to reach the domain controller?',
       args={'operation': 'status'},
       answer='ens192: UP, 10.20.4.15/24, route to 10.20.0.5 present'),
    V2(id='network-status-v2-0013', tool='network', operation='status',
       complexity='single',
       user_input='how many interfaces are active right now?',
       args={'operation': 'status'},
       answer='3 interfaces total, 2 UP, 1 DOWN\nens192: UP, ens193: UP, ens194: DOWN'),
    V2(id='network-connections-v2-0014', tool='network', operation='connections',
       complexity='single',
       user_input='list every NetworkManager connection profile',
       args={'operation': 'connections'},
       answer='3 profiles: ens192-static (active), ens193-dhcp, VPN-corp (inactive)'),
    V2(id='network-connections-v2-0015', tool='network', operation='connections',
       complexity='diagnostic',
       user_input='the VPN keeps dropping, is the connection profile even still registered?',
       args={'operation': 'connections'},
       answer='VPN-corp: inactive, last activated 09/10/2026 14:02'),
    V2(id='network-connections-v2-0016', tool='network', operation='connections',
       complexity='single',
       user_input='show me the nmcli connection list',
       args={'operation': 'connections'},
       answer='3 profiles: ens192-static (active), ens193-dhcp, VPN-corp (inactive)'),
    V2(id='network-connections-v2-0017', tool='network', operation='connections',
       complexity='diagnostic',
       user_input='we cloned this VM and now something looks off — enumerate connection profiles so I can spot duplicates',
       args={'operation': 'connections'},
       answer='4 profiles: ens192-static (active), ens192-static-1 (inactive, duplicate), ens193-dhcp, VPN-corp'),
    V2(id='network-connections-v2-0018', tool='network', operation='connections',
       complexity='single',
       user_input='list connection profiles including inactive ones',
       args={'operation': 'connections'},
       answer='4 profiles: ens192-static (active), ens193-dhcp, DMZ (inactive), VPN-corp (inactive)'),
    V2(id='network-connections-v2-0019', tool='network', operation='connections',
       complexity='multi',
       user_input='list the connection profiles and then bring up the DMZ one',
       args={'operation': 'connections'},
       answer='3 profiles: ens192-static (active), ens193-dhcp, DMZ (inactive)'),
    V2(id='network-interfaces-v2-0020', tool='network', operation='interfaces',
       complexity='single',
       user_input='what network interfaces does this machine have?',
       args={'operation': 'interfaces'},
       answer='ens192, ens193, lo, bond0'),
    V2(id='network-interfaces-v2-0021', tool='network', operation='interfaces',
       complexity='diagnostic',
       user_input='I added a second NIC to this VM, does the OS actually see it?',
       args={'operation': 'interfaces'},
       answer='ens192, ens193 (new), lo'),
    V2(id='network-interfaces-v2-0022', tool='network', operation='interfaces',
       complexity='single',
       user_input='list all NICs on this host',
       args={'operation': 'interfaces'},
       answer='ens192, ens193, lo'),
    V2(id='network-interfaces-v2-0023', tool='network', operation='interfaces',
       complexity='diagnostic',
       user_input='the bonding config should have produced bond0, is it showing up as an interface?',
       args={'operation': 'interfaces'},
       answer='ens192, ens193, bond0 (present, mode active-backup)'),
    V2(id='network-interfaces-v2-0024', tool='network', operation='interfaces',
       complexity='single',
       user_input='show me every network device',
       args={'operation': 'interfaces'},
       answer='ens160, ens161, lo, bond0'),
    V2(id='network-interfaces-v2-0025', tool='network', operation='interfaces',
       complexity='diagnostic',
       user_input='after the kernel_modules update, are all the expected interfaces still present?',
       args={'operation': 'interfaces'},
       answer='ens192, ens193, lo — all present, no change from baseline'),
    V2(id='network-wifi-v2-0026', tool='network', operation='wifi',
       complexity='single',
       user_input='what wireless network is this box connected to?',
       args={'operation': 'wifi'},
       answer='SSID: CorpNet-5G, signal -52dBm'),
    V2(id='network-wifi-v2-0027', tool='network', operation='wifi',
       complexity='diagnostic',
       user_input="this laptop can't reach internal file shares, what network is it actually on?",
       args={'operation': 'wifi'},
       answer='SSID: GuestWiFi, signal -61dBm — not on CorpNet-5G'),
    V2(id='network-wifi-v2-0028', tool='network', operation='wifi',
       complexity='single',
       user_input='show the current wifi SSID',
       args={'operation': 'wifi'},
       answer='SSID: CorpNet-5G, signal -52dBm'),
    V2(id='network-wifi-v2-0029', tool='network', operation='wifi',
       complexity='diagnostic',
       user_input='after roaming to the second floor AP, are we still on the right SSID?',
       args={'operation': 'wifi'},
       answer='SSID: CorpNet-5G, signal -70dBm, associated AP changed'),
    V2(id='network-wifi-v2-0030', tool='network', operation='wifi',
       complexity='single',
       user_input='check what wireless network this edge device is using',
       args={'operation': 'wifi'},
       answer='SSID: IoT-Segment, signal -58dBm'),
    V2(id='network-wifi-v2-0031', tool='network', operation='wifi',
       complexity='diagnostic',
       user_input="the sssd domain lookups are timing out on this wifi laptop, confirm which network it's on first",
       args={'operation': 'wifi'},
       answer='SSID: GuestWiFi, signal -65dBm — likely blocked from reaching the domain controller'),
    V2(id='network-wifi-v2-0032', tool='network', operation='wifi',
       complexity='single',
       user_input='confirm the wifi SSID for this host',
       args={'operation': 'wifi'},
       answer='SSID: CorpNet-5G, signal -50dBm'),
    V2(id='network-wifi-v2-0033', tool='network', operation='wifi',
       complexity='single',
       user_input='which network is the wireless adapter associated with right now?',
       args={'operation': 'wifi'},
       answer='SSID: CorpNet-5G, signal -55dBm'),
    V2(id='network-bring_up-v2-0034', tool='network', operation='bring_up',
       complexity='single',
       user_input='bring up ens193',
       args={'operation': 'bring_up', 'interface': 'ens193'},
       answer='ens193: brought up, state UP'),
    V2(id='network-bring_up-v2-0035', tool='network', operation='bring_up',
       complexity='single',
       user_input='enable the ens160 interface',
       args={'operation': 'bring_up', 'interface': 'ens160'},
       answer='ens160: brought up, state UP'),
    V2(id='network-bring_up-v2-0036', tool='network', operation='bring_up',
       complexity='diagnostic',
       user_input='the backup NIC ens194 is showing down and we need it for failover, bring it up',
       args={'operation': 'bring_up', 'interface': 'ens194'},
       answer='ens194: brought up, state UP'),
    V2(id='network-bring_up-v2-0037', tool='network', operation='bring_up',
       complexity='single',
       user_input='activate the DMZ connection profile',
       args={'operation': 'bring_up', 'connection': 'DMZ'},
       answer='DMZ: connection activated, state UP'),
    V2(id='network-bring_up-v2-0038', tool='network', operation='bring_up',
       complexity='multi',
       user_input='bring up ens161 and then confirm it picked up a DHCP address',
       args={'operation': 'bring_up', 'interface': 'ens161'},
       answer='ens161: brought up, state UP'),
    V2(id='network-bring_up-v2-0039', tool='network', operation='bring_up',
       complexity='single',
       user_input='turn ens195 back on after the maintenance',
       args={'operation': 'bring_up', 'interface': 'ens195'},
       answer='ens195: brought up, state UP'),
    V2(id='network-bring_down-v2-0040', tool='network', operation='bring_down',
       complexity='single',
       user_input='bring down ens193',
       args={'operation': 'bring_down', 'interface': 'ens193'},
       answer='ens193: brought down, state DOWN'),
    V2(id='network-bring_down-v2-0041', tool='network', operation='bring_down',
       complexity='single',
       user_input='shut down the ens160 interface for maintenance',
       args={'operation': 'bring_down', 'interface': 'ens160'},
       answer='ens160: brought down, state DOWN'),
    V2(id='network-bring_down-v2-0042', tool='network', operation='bring_down',
       complexity='diagnostic',
       user_input='we need to isolate this host during the incident, take ens192 offline',
       args={'operation': 'bring_down', 'interface': 'ens192'},
       answer='ens192: brought down, state DOWN'),
    V2(id='network-bring_down-v2-0043', tool='network', operation='bring_down',
       complexity='single',
       user_input="take ens5 down, it's part of a routing loop",
       args={'operation': 'bring_down', 'interface': 'ens5'},
       answer='ens5: brought down, state DOWN'),
    V2(id='network-bring_down-v2-0044', tool='network', operation='bring_down',
       complexity='multi',
       user_input='bring down ens194 and then bring up ens195 as its replacement',
       args={'operation': 'bring_down', 'interface': 'ens194'},
       answer='ens194: brought down, state DOWN'),
    V2(id='network-bring_down-v2-0045', tool='network', operation='bring_down',
       complexity='single',
       user_input='disable ens161 before we pull the cable',
       args={'operation': 'bring_down', 'interface': 'ens161'},
       answer='ens161: brought down, state DOWN'),
    V2(id='network-set_ip-v2-0046', tool='network', operation='set_ip',
       complexity='single',
       user_input='assign 10.20.4.50/24 to ens193',
       args={'operation': 'set_ip', 'address': '10.20.4.50/24', 'interface': 'ens193'},
       answer='ens193: address 10.20.4.50/24 assigned'),
    V2(id='network-set_ip-v2-0047', tool='network', operation='set_ip',
       complexity='single',
       user_input='set the IP of ens160 to 10.0.5.100/24',
       args={'operation': 'set_ip', 'address': '10.0.5.100/24', 'interface': 'ens160'},
       answer='ens160: address 10.0.5.100/24 assigned'),
    V2(id='network-set_ip-v2-0048', tool='network', operation='set_ip',
       complexity='diagnostic',
       user_input='the DHCP lease on ens194 expired and never renewed, assign a static fallback of 10.0.0.15/24',
       args={'operation': 'set_ip', 'address': '10.0.0.15/24', 'interface': 'ens194'},
       answer='ens194: address 10.0.0.15/24 assigned'),
    V2(id='network-set_ip-v2-0049', tool='network', operation='set_ip',
       complexity='single',
       user_input="configure the 'Management' connection profile with a static IP of 172.16.5.20/28",
       args={'operation': 'set_ip', 'address': '172.16.5.20/28', 'connection': 'Management'},
       answer='Management: address 172.16.5.20/28 assigned'),
    V2(id='network-set_ip-v2-0050', tool='network', operation='set_ip',
       complexity='multi',
       user_input='give ens161 the address 192.0.2.5/30 and then verify with a status check',
       args={'operation': 'set_ip', 'address': '192.0.2.5/30', 'interface': 'ens161'},
       answer='ens161: address 192.0.2.5/30 assigned'),
    V2(id='network-set_ip-v2-0051', tool='network', operation='set_ip',
       complexity='single',
       user_input="the HA cluster's floating IP 192.168.1.200/24 isn't responding, reassign it to ens192",
       args={'operation': 'set_ip', 'address': '192.168.1.200/24', 'interface': 'ens192'},
       answer='ens192: address 192.168.1.200/24 assigned'),
]

from finetune.scenarios_v2 import check_module; check_module('network', SCENARIOS_V2)
