"""finetune/scenarios_v2/nfs.py — corpus v2 scenarios for 'nfs'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # showmount (10)
    V2(id="nfs-showmount-v2-0001", tool="nfs", operation="showmount",
       complexity="single",
       user_input="What does nas02.corp.local actually export?",
       args={"operation": "showmount", "server": "nas02.corp.local"},
       answer="Export list for nas02.corp.local:\n/srv/nfs/home 10.0.0.0/24\n/srv/nfs/media 10.0.0.0/24"),
    V2(id="nfs-showmount-v2-0002", tool="nfs", operation="showmount",
       complexity="single",
       user_input="List the NFS shares advertised by 10.4.2.9.",
       args={"operation": "showmount", "server": "10.4.2.9"},
       answer="Export list for 10.4.2.9:\n/exports/build *"),
    V2(id="nfs-showmount-v2-0003", tool="nfs", operation="showmount",
       complexity="diagnostic",
       user_input="A mount to filer-03 is timing out — is it even exporting anything right now?",
       args={"operation": "showmount", "server": "filer-03"},
       answer="clnt_create: RPC: Program not registered\nfiler-03 not responding on export list"),
    V2(id="nfs-showmount-v2-0004", tool="nfs", operation="showmount",
       complexity="single",
       user_input="Show the exports on storage01.internal.",
       args={"operation": "showmount", "server": "storage01.internal"},
       answer="Export list for storage01.internal:\n/srv/nfs/data 192.168.5.0/24"),
    V2(id="nfs-showmount-v2-0005", tool="nfs", operation="showmount",
       complexity="diagnostic",
       user_input="The backup job says it can't reach its target share on archive-nas — what is that host actually exporting?",
       args={"operation": "showmount", "server": "archive-nas"},
       answer="Export list for archive-nas:\n/srv/nfs/archive 172.16.0.0/16"),
    V2(id="nfs-showmount-v2-0006", tool="nfs", operation="showmount",
       complexity="multi",
       user_input="Check what fileserver.dept.edu exports, then mount its /research share to /mnt/research.",
       args={"operation": "showmount", "server": "fileserver.dept.edu"},
       answer="Export list for fileserver.dept.edu:\n/research 10.20.0.0/16"),
    V2(id="nfs-showmount-v2-0007", tool="nfs", operation="showmount",
       complexity="single",
       user_input="Query the exports on 192.168.9.30.",
       args={"operation": "showmount", "server": "192.168.9.30"},
       answer="Export list for 192.168.9.30:\n/srv/nfs/scratch 192.168.9.0/24"),
    V2(id="nfs-showmount-v2-0008", tool="nfs", operation="showmount",
       complexity="single",
       user_input="I need to see what shares nas-prod.company.com is offering.",
       args={"operation": "showmount", "server": "nas-prod.company.com"},
       answer="Export list for nas-prod.company.com:\n/srv/nfs/apps 10.0.4.0/24\n/srv/nfs/logs 10.0.4.0/24"),
    V2(id="nfs-showmount-v2-0009", tool="nfs", operation="showmount",
       complexity="diagnostic",
       user_input="Users say the shared drive from vault.internal disappeared — check what it's currently exporting.",
       args={"operation": "showmount", "server": "vault.internal"},
       answer="Export list for vault.internal:\n(no exports)"),
    V2(id="nfs-showmount-v2-0010", tool="nfs", operation="showmount",
       complexity="single",
       user_input="showmount against buildsrv01.",
       args={"operation": "showmount", "server": "buildsrv01"},
       answer="Export list for buildsrv01:\n/srv/nfs/ci *"),
    # exportfs_list (11)
    V2(id="nfs-exportfs_list-v2-0001", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="What is this server currently exporting over NFS?",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24\n/srv/nfs/backups    10.0.0.0/8"),
    V2(id="nfs-exportfs_list-v2-0002", tool="nfs", operation="exportfs_list",
       complexity="diagnostic",
       user_input="A client says /projects vanished from this host — what's actually active in exportfs right now?",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24\n(no /projects entry present)"),
    V2(id="nfs-exportfs_list-v2-0003", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="Show the live NFS exports on this box.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/home       10.20.0.0/16\n/srv/nfs/media      10.20.0.0/16"),
    V2(id="nfs-exportfs_list-v2-0004", tool="nfs", operation="exportfs_list",
       complexity="multi",
       user_input="List the active exports and then show me /etc/exports so I can compare the two.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24\n/srv/nfs/backups    10.0.0.0/8"),
    V2(id="nfs-exportfs_list-v2-0005", tool="nfs", operation="exportfs_list",
       complexity="diagnostic",
       user_input="After reloading exports I want to confirm they're actually live — what's exportfs showing?",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24\n/srv/nfs/staging    192.168.1.0/24"),
    V2(id="nfs-exportfs_list-v2-0006", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="Give me the current exportfs table.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/archive    172.16.0.0/16"),
    V2(id="nfs-exportfs_list-v2-0007", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="Show what paths are currently exported on this NFS server.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24"),
    V2(id="nfs-exportfs_list-v2-0008", tool="nfs", operation="exportfs_list",
       complexity="diagnostic",
       user_input="I suspect samba took over this mountpoint instead of NFS — what does exportfs actually report as active?",
       args={"operation": "exportfs_list"},
       answer="(no active exports)"),
    V2(id="nfs-exportfs_list-v2-0009", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="Check the running export table.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/apps       10.0.4.0/24\n/srv/nfs/logs       10.0.4.0/24"),
    V2(id="nfs-exportfs_list-v2-0010", tool="nfs", operation="exportfs_list",
       complexity="single",
       user_input="List exportfs entries currently in the kernel export table.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/ci         *"),
    V2(id="nfs-exportfs_list-v2-0011", tool="nfs", operation="exportfs_list",
       complexity="multi",
       user_input="Confirm the current exports are live and then unexport the ones under /srv/nfs/staging.",
       args={"operation": "exportfs_list"},
       answer="/srv/nfs/data       192.168.1.0/24\n/srv/nfs/staging    192.168.1.0/24"),
    # exportfs_add (11)
    V2(id="nfs-exportfs_add-v2-0001", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="Re-read /etc/exports and push the exports live.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0002", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="I just added a new line to /etc/exports for /srv/nfs/qa — apply it without restarting nfs-server.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0003", tool="nfs", operation="exportfs_add",
       complexity="diagnostic",
       user_input="Clients say the new /projects share isn't visible yet — has it been published from /etc/exports?",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0004", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="Publish everything configured in /etc/exports.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0005", tool="nfs", operation="exportfs_add",
       complexity="multi",
       user_input="Refresh the exports and then list what's active to confirm the new one made it in.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0006", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="Apply the exports file.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0007", tool="nfs", operation="exportfs_add",
       complexity="diagnostic",
       user_input="We edited /etc/exports an hour ago but the share still isn't reachable from the app tier — has this ever been reloaded?",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0008", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="Reload the NFS export table.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0009", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="Make the exports config take effect.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0010", tool="nfs", operation="exportfs_add",
       complexity="diagnostic",
       user_input="This server's exports seem stale compared to what's in the config file — sync them up.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    V2(id="nfs-exportfs_add-v2-0011", tool="nfs", operation="exportfs_add",
       complexity="single",
       user_input="exportfs -a essentially, publish everything in the exports file.",
       args={"operation": "exportfs_add"},
       answer="exportfs: /etc/exports [1]: syntax ok\nexports published"),
    # exportfs_unexport (10)
    V2(id="nfs-exportfs_unexport-v2-0001", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Revoke the export of /srv/nfs/qa to everyone.",
       args={"operation": "exportfs_unexport", "target": "*:/srv/nfs/qa"},
       answer="unexported /srv/nfs/qa"),
    V2(id="nfs-exportfs_unexport-v2-0002", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Remove the NFS export 10.0.0.0/8:/srv/nfs/backups.",
       args={"operation": "exportfs_unexport", "target": "10.0.0.0/8:/srv/nfs/backups"},
       answer="unexported /srv/nfs/backups"),
    V2(id="nfs-exportfs_unexport-v2-0003", tool="nfs", operation="exportfs_unexport",
       complexity="diagnostic",
       user_input="Security flagged that /srv/nfs/legacy is still exported to the whole internal subnet with no reason — pull that export immediately.",
       args={"operation": "exportfs_unexport", "target": "192.168.0.0/16:/srv/nfs/legacy"},
       answer="unexported /srv/nfs/legacy"),
    V2(id="nfs-exportfs_unexport-v2-0004", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Unexport /srv/nfs/staging for the dev subnet 172.20.0.0/24.",
       args={"operation": "exportfs_unexport", "target": "172.20.0.0/24:/srv/nfs/staging"},
       answer="unexported /srv/nfs/staging"),
    V2(id="nfs-exportfs_unexport-v2-0005", tool="nfs", operation="exportfs_unexport",
       complexity="multi",
       user_input="Unexport *:/srv/nfs/tmp and then confirm it's gone from the active list.",
       args={"operation": "exportfs_unexport", "target": "*:/srv/nfs/tmp"},
       answer="unexported /srv/nfs/tmp"),
    V2(id="nfs-exportfs_unexport-v2-0006", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Cut access to /srv/nfs/media for 10.0.0.0/24 immediately.",
       args={"operation": "exportfs_unexport", "target": "10.0.0.0/24:/srv/nfs/media"},
       answer="unexported /srv/nfs/media"),
    V2(id="nfs-exportfs_unexport-v2-0007", tool="nfs", operation="exportfs_unexport",
       complexity="diagnostic",
       user_input="We're decommissioning the old build share — revoke /srv/nfs/build so clients stop depending on it.",
       args={"operation": "exportfs_unexport", "target": "*:/srv/nfs/build"},
       answer="unexported /srv/nfs/build"),
    V2(id="nfs-exportfs_unexport-v2-0008", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Take down the export for /srv/nfs/scratch to the whole 192.168.9.0/24 subnet.",
       args={"operation": "exportfs_unexport", "target": "192.168.9.0/24:/srv/nfs/scratch"},
       answer="unexported /srv/nfs/scratch"),
    V2(id="nfs-exportfs_unexport-v2-0009", tool="nfs", operation="exportfs_unexport",
       complexity="diagnostic",
       user_input="Incident response wants the /srv/nfs/sensitive share cut off from all clients right now.",
       args={"operation": "exportfs_unexport", "target": "*:/srv/nfs/sensitive"},
       answer="unexported /srv/nfs/sensitive"),
    V2(id="nfs-exportfs_unexport-v2-0010", tool="nfs", operation="exportfs_unexport",
       complexity="single",
       user_input="Unexport 10.4.2.0/24:/srv/nfs/archive.",
       args={"operation": "exportfs_unexport", "target": "10.4.2.0/24:/srv/nfs/archive"},
       answer="unexported /srv/nfs/archive"),
    # exports_view (11)
    V2(id="nfs-exports_view-v2-0001", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="Show me what's written in /etc/exports.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/data 192.168.1.0/24(rw,sync,no_subtree_check)\n/srv/nfs/backups 10.0.0.0/8(ro,sync)"),
    V2(id="nfs-exports_view-v2-0002", tool="nfs", operation="exports_view",
       complexity="diagnostic",
       user_input="A share isn't mounting from a new subnet — let me see the exports config to check the allowed clients.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/data 192.168.1.0/24(rw,sync,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0003", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="Cat the exports file.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/home 10.20.0.0/16(rw,sync,no_root_squash)"),
    V2(id="nfs-exports_view-v2-0004", tool="nfs", operation="exports_view",
       complexity="diagnostic",
       user_input="We had a misconfigured export causing write failures — show me the raw config so I can check the sync option.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/data 192.168.1.0/24(ro,sync,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0005", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="What exports are defined on this NFS server, straight from the config?",
       args={"operation": "exports_view"},
       answer="/srv/nfs/apps 10.0.4.0/24(rw,sync)\n/srv/nfs/logs 10.0.4.0/24(rw,sync)"),
    V2(id="nfs-exports_view-v2-0006", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="Print the contents of the exports configuration file.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/ci *(rw,async,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0007", tool="nfs", operation="exports_view",
       complexity="multi",
       user_input="Show /etc/exports and then reload it so the config takes effect.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/data 192.168.1.0/24(rw,sync,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0008", tool="nfs", operation="exports_view",
       complexity="diagnostic",
       user_input="Is the /srv/nfs/archive path even in /etc/exports, or did someone remove the line?",
       args={"operation": "exports_view"},
       answer="/srv/nfs/data 192.168.1.0/24(rw,sync)\n(no /srv/nfs/archive entry)"),
    V2(id="nfs-exports_view-v2-0009", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="Let me look at the exports file before I edit it.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/staging 172.20.0.0/24(rw,sync,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0010", tool="nfs", operation="exports_view",
       complexity="single",
       user_input="Dump /etc/exports for review.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/media 10.0.0.0/24(rw,async,no_subtree_check)"),
    V2(id="nfs-exports_view-v2-0011", tool="nfs", operation="exports_view",
       complexity="diagnostic",
       user_input="Clients are getting permission denied on write to /srv/nfs/build — check the exports config for a stray ro option.",
       args={"operation": "exports_view"},
       answer="/srv/nfs/build *(ro,sync,no_subtree_check)"),
    # nfs_start (11)
    V2(id="nfs-nfs_start-v2-0001", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="Start the nfs-server service.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0002", tool="nfs", operation="nfs_start",
       complexity="diagnostic",
       user_input="No clients can mount anything from this host — is the NFS daemon even running?",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)\nwas inactive (dead) before start"),
    V2(id="nfs-nfs_start-v2-0003", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="Bring nfs-server online.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0004", tool="nfs", operation="nfs_start",
       complexity="multi",
       user_input="Start the NFS server and then reload the exports so clients can reconnect.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0005", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="Turn on the NFS service.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0006", tool="nfs", operation="nfs_start",
       complexity="diagnostic",
       user_input="After a kernel update this box rebooted and now the build agents can't mount their share — check if nfs-server needs starting.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)\nwas inactive (dead) before start"),
    V2(id="nfs-nfs_start-v2-0007", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="Get the NFS daemon running.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0008", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="systemctl start the nfs-server unit.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0009", tool="nfs", operation="nfs_start",
       complexity="diagnostic",
       user_input="We just finished maintenance on this filer — bring the NFS service back up.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0010", tool="nfs", operation="nfs_start",
       complexity="single",
       user_input="Start nfs-server.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    V2(id="nfs-nfs_start-v2-0011", tool="nfs", operation="nfs_start",
       complexity="multi",
       user_input="Start the NFS service, then list the currently active exports to confirm everything's back.",
       args={"operation": "nfs_start"},
       answer="nfs-server.service: active (running)"),
    # nfs_stop (11)
    V2(id="nfs-nfs_stop-v2-0001", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="Stop the nfs-server service for the maintenance window.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0002", tool="nfs", operation="nfs_stop",
       complexity="diagnostic",
       user_input="NFS is chewing up CPU on this host and we need to investigate — take it offline for now.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0003", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="Shut down the NFS daemon.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0004", tool="nfs", operation="nfs_stop",
       complexity="multi",
       user_input="Stop nfs-server, then update /etc/exports before bringing it back up.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0005", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="Take the NFS service offline.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0006", tool="nfs", operation="nfs_stop",
       complexity="diagnostic",
       user_input="We're decommissioning this filer entirely — stop the NFS service since it shouldn't serve anything anymore.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0007", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="Halt nfs-server.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0008", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="systemctl stop the NFS server unit.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0009", tool="nfs", operation="nfs_stop",
       complexity="diagnostic",
       user_input="A stale NFS lock is hanging the storage array — can we just stop the service to clear it?",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0010", tool="nfs", operation="nfs_stop",
       complexity="single",
       user_input="Bring down the NFS server.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    V2(id="nfs-nfs_stop-v2-0011", tool="nfs", operation="nfs_stop",
       complexity="multi",
       user_input="Stop the NFS service and then confirm no clients are still connected.",
       args={"operation": "nfs_stop"},
       answer="nfs-server.service: inactive (dead)"),
    # mount_client (9)
    V2(id="nfs-mount_client-v2-0001", tool="nfs", operation="mount_client",
       complexity="single",
       user_input="Mount nas02.corp.local:/srv/nfs/home onto /mnt/home.",
       args={"operation": "mount_client", "server": "nas02.corp.local", "path": "/srv/nfs/home", "mountpoint": "/mnt/home"},
       answer="mounted nas02.corp.local:/srv/nfs/home on /mnt/home type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0002", tool="nfs", operation="mount_client",
       complexity="single",
       user_input="Attach 10.4.2.9:/exports/build at /mnt/build.",
       args={"operation": "mount_client", "server": "10.4.2.9", "path": "/exports/build", "mountpoint": "/mnt/build"},
       answer="mounted 10.4.2.9:/exports/build on /mnt/build type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0003", tool="nfs", operation="mount_client",
       complexity="diagnostic",
       user_input="The deployment script keeps failing because /mnt/artifacts doesn't exist as a mount — attach storage01.internal:/artifacts there.",
       args={"operation": "mount_client", "server": "storage01.internal", "path": "/artifacts", "mountpoint": "/mnt/artifacts"},
       answer="mounted storage01.internal:/artifacts on /mnt/artifacts type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0004", tool="nfs", operation="mount_client",
       complexity="single",
       user_input="Mount the /research share from fileserver.dept.edu onto /mnt/research.",
       args={"operation": "mount_client", "server": "fileserver.dept.edu", "path": "/research", "mountpoint": "/mnt/research"},
       answer="mounted fileserver.dept.edu:/research on /mnt/research type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0005", tool="nfs", operation="mount_client",
       complexity="multi",
       user_input="Check what nas01 exports, then mount its /data share at /mnt/nas-data.",
       args={"operation": "mount_client", "server": "nas01", "path": "/data", "mountpoint": "/mnt/nas-data"},
       answer="mounted nas01:/data on /mnt/nas-data type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0006", tool="nfs", operation="mount_client",
       complexity="single",
       user_input="Mount logserver.internal:/logs at /var/log/remote.",
       args={"operation": "mount_client", "server": "logserver.internal", "path": "/logs", "mountpoint": "/var/log/remote"},
       answer="mounted logserver.internal:/logs on /var/log/remote type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0007", tool="nfs", operation="mount_client",
       complexity="diagnostic",
       user_input="The deployment script can't find /mnt/shared — is it mounted at all? Go ahead and mount netstore.corp.local:/shared there.",
       args={"operation": "mount_client", "server": "netstore.corp.local", "path": "/shared", "mountpoint": "/mnt/shared"},
       answer="mounted netstore.corp.local:/shared on /mnt/shared type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0008", tool="nfs", operation="mount_client",
       complexity="single",
       user_input="Mount filer02:/projects onto /mnt/projects.",
       args={"operation": "mount_client", "server": "filer02", "path": "/projects", "mountpoint": "/mnt/projects"},
       answer="mounted filer02:/projects on /mnt/projects type nfs (rw,relatime)"),
    V2(id="nfs-mount_client-v2-0009", tool="nfs", operation="mount_client",
       complexity="multi",
       user_input="Mount archive-nas:/srv/nfs/archive at /mnt/archive and then check whether it's writable.",
       args={"operation": "mount_client", "server": "archive-nas", "path": "/srv/nfs/archive", "mountpoint": "/mnt/archive"},
       answer="mounted archive-nas:/srv/nfs/archive on /mnt/archive type nfs (rw,relatime)"),
]

from finetune.scenarios_v2 import check_module; check_module("nfs", SCENARIOS_V2)
