"""finetune/scenarios_v2/nginx.py — corpus v2 scenarios for 'nginx'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="nginx-configtest-v2-0001", tool="nginx", operation="configtest",
       complexity="single",
       user_input="Check if the nginx config on web-front-2 is valid.",
       args={"operation": "configtest"},
       answer="nginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful"),
    V2(id="nginx-configtest-v2-0002", tool="nginx", operation="configtest",
       complexity="diagnostic",
       user_input="nginx on edge-3 refused to reload a minute ago. Run a config test so I can see what's wrong.",
       args={"operation": "configtest"},
       answer="nginx: [emerg] unexpected \"}\" in /etc/nginx/conf.d/app.conf:24\nnginx: configuration file /etc/nginx/nginx.conf test failed"),
    V2(id="nginx-configtest-v2-0003", tool="nginx", operation="configtest",
       complexity="single",
       user_input="Validate the site config at /etc/nginx/conf.d/checkout.conf on payments-web-1 before we restart.",
       args={"operation": "configtest", "config": "/etc/nginx/conf.d/checkout.conf"},
       answer="nginx: the configuration file /etc/nginx/conf.d/checkout.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful"),
    V2(id="nginx-configtest-v2-0004", tool="nginx", operation="configtest",
       complexity="multi",
       user_input="Test the nginx config on api-gw-9 and if it passes, reload the service.",
       args={"operation": "configtest"},
       answer="nginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful"),
    V2(id="nginx-configtest-v2-0005", tool="nginx", operation="configtest",
       complexity="diagnostic",
       user_input="I just edited the server block for static-cdn-1, does the config still hold up?",
       args={"operation": "configtest"},
       answer="nginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: configuration file /etc/nginx/nginx.conf test is successful"),
    V2(id="nginx-configtest-v2-0006", tool="nginx", operation="configtest",
       complexity="single",
       user_input="run nginx -t on host lb-front-4",
       args={"operation": "configtest"},
       answer="nginx: [warn] conflicting server name \"api.internal\" on 0.0.0.0:443, ignored\nnginx: configuration file /etc/nginx/nginx.conf test is successful"),

    V2(id="nginx-status-v2-0001", tool="nginx", operation="status",
       complexity="single",
       user_input="Is nginx running on web-front-2?",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: active (running) since Wed 2026-09-10 12:04:01 UTC; 2 days ago\nMain PID: 1841 (nginx)"),
    V2(id="nginx-status-v2-0002", tool="nginx", operation="status",
       complexity="diagnostic",
       user_input="checkout-web-3 is throwing 502 errors for customers. Check the web server status.",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: failed (Result: exit-code) since Fri 2026-09-12 08:14:30 UTC; 40min ago\nMain PID: 0 (code=exited, status=1/FAILURE)"),
    V2(id="nginx-status-v2-0003", tool="nginx", operation="status",
       complexity="multi",
       user_input="Check nginx status on edge-3 and tell me how many worker processes are running.",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: active (running) since Mon 2026-09-08 09:00:00 UTC; 5 days ago\nMain PID: 210 (nginx)\nTasks: 5 (limit: 4681)"),
    V2(id="nginx-status-v2-0004", tool="nginx", operation="status",
       complexity="diagnostic",
       user_input="api-gw-9 crashed overnight per the alert. What does the nginx service status show now?",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: inactive (dead)\nMain PID: 0 (code=exited, status=0/SUCCESS)"),
    V2(id="nginx-status-v2-0005", tool="nginx", operation="status",
       complexity="single",
       user_input="is the web server up on static-cdn-1",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: active (running) since Sun 2026-09-07 18:22:41 UTC; 5 days ago\nMain PID: 998 (nginx)"),
    V2(id="nginx-status-v2-0006", tool="nginx", operation="status",
       complexity="multi",
       user_input="After the OS package upgrade on lb-front-4, check if nginx is still active and healthy.",
       args={"operation": "status"},
       answer="nginx.service - The nginx HTTP and reverse proxy server\nActive: active (running) since Fri 2026-09-12 03:00:12 UTC; 6h ago\nMain PID: 512 (nginx)"),

    V2(id="nginx-start-v2-0001", tool="nginx", operation="start",
       complexity="single",
       user_input="Start nginx on web-front-2.",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 2204 (nginx)"),
    V2(id="nginx-start-v2-0002", tool="nginx", operation="start",
       complexity="diagnostic",
       user_input="The checkout site is currently down entirely, checkout-web-3 shows nothing on port 443. Bring nginx up.",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 3341 (nginx)"),
    V2(id="nginx-start-v2-0003", tool="nginx", operation="start",
       complexity="multi",
       user_input="Start nginx on edge-3 and then check its status to confirm it came up.",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 1912 (nginx)"),
    V2(id="nginx-start-v2-0004", tool="nginx", operation="start",
       complexity="multi",
       user_input="static-cdn-1's web server is down. Test the config first, and if it's clean, start nginx.",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 774 (nginx)"),
    V2(id="nginx-start-v2-0005", tool="nginx", operation="start",
       complexity="single",
       user_input="launch the nginx service on api-gw-9",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 5502 (nginx)"),
    V2(id="nginx-start-v2-0006", tool="nginx", operation="start",
       complexity="single",
       user_input="Bring nginx back up on lb-front-4 now that the maintenance window is over.",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 660 (nginx)"),
    V2(id="nginx-start-v2-0007", tool="nginx", operation="start",
       complexity="single",
       user_input="start nginx on payments-web-1 if it isn't already running",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 2087 (nginx)"),
    V2(id="nginx-start-v2-0008", tool="nginx", operation="start",
       complexity="single",
       user_input="turn nginx on for host media-stream-2",
       args={"operation": "start"},
       answer="Started nginx.service\nMain PID: 9012 (nginx)"),

    V2(id="nginx-stop-v2-0001", tool="nginx", operation="stop",
       complexity="single",
       user_input="Stop nginx on web-front-2.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0002", tool="nginx", operation="stop",
       complexity="single",
       user_input="Bring nginx down on static-cdn-1 for the maintenance window.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0003", tool="nginx", operation="stop",
       complexity="multi",
       user_input="Stop nginx on edge-3 and confirm it has fully exited.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0004", tool="nginx", operation="stop",
       complexity="diagnostic",
       user_input="checkout-web-3's nginx worker is pegging the CPU at 100%. Stop it immediately.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0005", tool="nginx", operation="stop",
       complexity="single",
       user_input="shut down the web server on api-gw-9",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0006", tool="nginx", operation="stop",
       complexity="single",
       user_input="Take nginx offline on lb-front-4 before we rotate the TLS certificate.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0007", tool="nginx", operation="stop",
       complexity="multi",
       user_input="Stop nginx on media-stream-2 and then verify no worker processes remain.",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0008", tool="nginx", operation="stop",
       complexity="single",
       user_input="pull the plug on nginx for host payments-web-1, we're decommissioning it",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),
    V2(id="nginx-stop-v2-0009", tool="nginx", operation="stop",
       complexity="single",
       user_input="stop the web server process on internal-docs-1",
       args={"operation": "stop"},
       answer="Stopped nginx.service\nnginx.service: Deactivated successfully"),

    V2(id="nginx-restart-v2-0001", tool="nginx", operation="restart",
       complexity="single",
       user_input="Restart nginx on web-front-2.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 4410 (nginx)"),
    V2(id="nginx-restart-v2-0002", tool="nginx", operation="restart",
       complexity="single",
       user_input="Bounce nginx on static-cdn-1 to pick up the new TLS certificates.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 5561 (nginx)"),
    V2(id="nginx-restart-v2-0003", tool="nginx", operation="restart",
       complexity="multi",
       user_input="Restart nginx on edge-3 and check its status to confirm it came back cleanly.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 2091 (nginx)"),
    V2(id="nginx-restart-v2-0004", tool="nginx", operation="restart",
       complexity="diagnostic",
       user_input="api-gw-9's nginx is behaving strangely, workers not respawning. Restart it to clear the issue.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 6702 (nginx)"),
    V2(id="nginx-restart-v2-0005", tool="nginx", operation="restart",
       complexity="single",
       user_input="restart the web server on payments-web-1 after the config change",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 1122 (nginx)"),
    V2(id="nginx-restart-v2-0006", tool="nginx", operation="restart",
       complexity="multi",
       user_input="Test the nginx config on lb-front-4 and if it's valid, restart the service.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 887 (nginx)"),
    V2(id="nginx-restart-v2-0007", tool="nginx", operation="restart",
       complexity="multi",
       user_input="After patching the nginx package on media-stream-2, restart it and verify it's running.",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 3390 (nginx)"),
    V2(id="nginx-restart-v2-0008", tool="nginx", operation="restart",
       complexity="single",
       user_input="cycle nginx on internal-docs-1",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 445 (nginx)"),
    V2(id="nginx-restart-v2-0009", tool="nginx", operation="restart",
       complexity="single",
       user_input="do a full restart of the web server on checkout-web-3, not just a reload",
       args={"operation": "restart"},
       answer="Stopped nginx.service\nStarted nginx.service\nMain PID: 7788 (nginx)"),

    V2(id="nginx-reload-v2-0001", tool="nginx", operation="reload",
       complexity="single",
       user_input="Reload nginx on web-front-2 to pick up the new virtual host block.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0002", tool="nginx", operation="reload",
       complexity="single",
       user_input="Apply the config changes on static-cdn-1 without restarting.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0003", tool="nginx", operation="reload",
       complexity="multi",
       user_input="Test the config on edge-3 first, then reload it gracefully.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0004", tool="nginx", operation="reload",
       complexity="single",
       user_input="send a HUP to nginx on api-gw-9 to reload config",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0005", tool="nginx", operation="reload",
       complexity="single",
       user_input="I updated the upstream block on lb-front-4, reload nginx without dropping active connections.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0006", tool="nginx", operation="reload",
       complexity="single",
       user_input="reload the nginx configuration on payments-web-1",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0007", tool="nginx", operation="reload",
       complexity="multi",
       user_input="Reload nginx on media-stream-2 after updating the rate-limiting rules, and verify it's still running.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0008", tool="nginx", operation="reload",
       complexity="diagnostic",
       user_input="A new server block on internal-docs-1 isn't taking effect yet. Reload the config so it picks it up.",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
    V2(id="nginx-reload-v2-0009", tool="nginx", operation="reload",
       complexity="single",
       user_input="graceful reload of nginx on checkout-web-3 please, changed the rate limits",
       args={"operation": "reload"},
       answer="Reloading nginx.service\nnginx.service: Reload succeeded"),
]

from finetune.scenarios_v2 import check_module; check_module("nginx", SCENARIOS_V2)
