"""finetune/scenarios_v2/nmcli.py — corpus v2 scenarios for 'nmcli'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="nmcli-device_status-v2-0001", tool="nmcli", operation="device_status",
       complexity="single",
       user_input="Show me the state of every network device NetworkManager knows about.",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\neno1    ethernet  connected  eno1-static\nwlan0   wifi      disconnected  --"),
    V2(id="nmcli-device_status-v2-0002", tool="nmcli", operation="device_status",
       complexity="diagnostic",
       user_input="eno2 won't come up after the switch port change \u2014 what does NetworkManager see for it?",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE         CONNECTION\neno2    ethernet  unavailable   --"),
    V2(id="nmcli-device_status-v2-0003", tool="nmcli", operation="device_status",
       complexity="single",
       user_input="List the current device and connection state for all interfaces.",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\nens192  ethernet  connected  ens192-static\nlo      loopback  unmanaged  --"),
    V2(id="nmcli-device_status-v2-0004", tool="nmcli", operation="device_status",
       complexity="diagnostic",
       user_input="The bonded interface dropped one leg overnight \u2014 what's the device status on this host right now?",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\nbond0   bond      connected  bond0\nens224  ethernet  unavailable  --"),
    V2(id="nmcli-device_status-v2-0005", tool="nmcli", operation="device_status",
       complexity="single",
       user_input="What network devices does NetworkManager currently manage?",
       args={"operation": "device_status"},
       answer="DEVICE   TYPE   STATE      CONNECTION\neth0     ethernet  connected  Wired connection 1\nwlan0    wifi      connected  OfficeWifi"),
    V2(id="nmcli-device_status-v2-0006", tool="nmcli", operation="device_status",
       complexity="multi",
       user_input="Check device status and then tell me which profile is bound to ens256.",
       args={"operation": "device_status"},
       answer="DEVICE   TYPE      STATE      CONNECTION\nens256   ethernet  connected  ens256-mgmt\nens256 -> ens256-mgmt"),
    V2(id="nmcli-device_status-v2-0007", tool="nmcli", operation="device_status",
       complexity="diagnostic",
       user_input="A ticket says this host has no network at all, but ssh got us in \u2014 what does nmcli see?",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\neth0    ethernet  connected  eth0-dhcp\neth1    ethernet  disconnected  --"),
    V2(id="nmcli-device_status-v2-0008", tool="nmcli", operation="device_status",
       complexity="single",
       user_input="Give me a table of interfaces and their connection state.",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\nens160  ethernet  connected  ens160-static"),
    V2(id="nmcli-device_status-v2-0009", tool="nmcli", operation="device_status",
       complexity="diagnostic",
       user_input="We rely on nftables NAT out of eth1, but traffic isn't leaving the box \u2014 is eth1 even connected according to NetworkManager?",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE         CONNECTION\neth1    ethernet  unavailable   --"),
    V2(id="nmcli-device_status-v2-0010", tool="nmcli", operation="device_status",
       complexity="single",
       user_input="Show the connected/disconnected state of each managed device.",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\nenp0s3  ethernet  connected  enp0s3"),
    V2(id="nmcli-device_status-v2-0011", tool="nmcli", operation="device_status",
       complexity="diagnostic",
       user_input="sssd can't reach the domain controller \u2014 before I blame DNS, what does NetworkManager report for the interface state?",
       args={"operation": "device_status"},
       answer="DEVICE  TYPE      STATE      CONNECTION\nens192  ethernet  connected  ens192-static"),
    V2(id="nmcli-connection_show-v2-0012", tool="nmcli", operation="connection_show",
       complexity="single",
       user_input="Show the full configuration of 'ens192-static'.",
       args={"name": "ens192-static", "operation": "connection_show"},
       answer="connection.id: ens192-static\nipv4.method: manual\nipv4.addresses: 10.0.1.20/24\nipv4.gateway: 10.0.1.1"),
    V2(id="nmcli-connection_show-v2-0013", tool="nmcli", operation="connection_show",
       complexity="diagnostic",
       user_input="DNS lookups are failing on this host \u2014 what does the active connection profile have set for nameservers?",
       args={"name": "eth0-static", "operation": "connection_show"},
       answer="connection.id: eth0-static\nipv4.dns: 10.0.0.53\nipv4.method: manual"),
    V2(id="nmcli-connection_show-v2-0014", tool="nmcli", operation="connection_show",
       complexity="single",
       user_input="Display all settings for the 'bond0-primary' connection.",
       args={"name": "bond0-primary", "operation": "connection_show"},
       answer="connection.id: bond0-primary\nconnection.autoconnect: yes\nbond.options: mode=active-backup,miimon=100"),
    V2(id="nmcli-connection_show-v2-0015", tool="nmcli", operation="connection_show",
       complexity="diagnostic",
       user_input="Traffic keeps leaving via the wrong gateway \u2014 check the route metric configured on 'eth1-mgmt'.",
       args={"name": "eth1-mgmt", "operation": "connection_show"},
       answer="connection.id: eth1-mgmt\nipv4.route-metric: 50\nipv4.gateway: 10.0.9.1"),
    V2(id="nmcli-connection_show-v2-0016", tool="nmcli", operation="connection_show",
       complexity="single",
       user_input="What's the current MTU set on 'storage-net'?",
       args={"name": "storage-net", "operation": "connection_show"},
       answer="connection.id: storage-net\n802-3-ethernet.mtu: 9000"),
    V2(id="nmcli-connection_show-v2-0017", tool="nmcli", operation="connection_show",
       complexity="multi",
       user_input="Show the details of 'ens224-vlan100' and then tell me if autoconnect is on.",
       args={"name": "ens224-vlan100", "operation": "connection_show"},
       answer="connection.id: ens224-vlan100\nconnection.autoconnect: no\nvlan.id: 100\nautoconnect: disabled"),
    V2(id="nmcli-connection_show-v2-0018", tool="nmcli", operation="connection_show",
       complexity="diagnostic",
       user_input="The mgmt VLAN keeps losing its IP after reboot \u2014 is 'eth0-mgmt' even set to autoconnect?",
       args={"name": "eth0-mgmt", "operation": "connection_show"},
       answer="connection.id: eth0-mgmt\nconnection.autoconnect: no\nipv4.addresses: 10.10.0.5/24"),
    V2(id="nmcli-connection_show-v2-0019", tool="nmcli", operation="connection_show",
       complexity="single",
       user_input="Print out the IP address and gateway configured on 'Wired connection 1'.",
       args={"name": "Wired connection 1", "operation": "connection_show"},
       answer="connection.id: Wired connection 1\nipv4.addresses: 192.168.1.50/24\nipv4.gateway: 192.168.1.1"),
    V2(id="nmcli-connection_show-v2-0020", tool="nmcli", operation="connection_show",
       complexity="diagnostic",
       user_input="The database node lost storage connectivity \u2014 check what interface and IP the 'db-storage' profile is bound to.",
       args={"name": "db-storage", "operation": "connection_show"},
       answer="connection.id: db-storage\nconnection.interface-name: ens256\nipv4.addresses: 172.16.10.5/24"),
    V2(id="nmcli-connection_show-v2-0021", tool="nmcli", operation="connection_show",
       complexity="single",
       user_input="Show configuration for 'guest-wifi'.",
       args={"name": "guest-wifi", "operation": "connection_show"},
       answer="connection.id: guest-wifi\n802-11-wireless.ssid: GuestNet\nconnection.autoconnect: yes"),
    V2(id="nmcli-connection_show-v2-0022", tool="nmcli", operation="connection_show",
       complexity="diagnostic",
       user_input="We suspect the backup network is on the wrong subnet \u2014 check the addresses set on 'backup-link'.",
       args={"name": "backup-link", "operation": "connection_show"},
       answer="connection.id: backup-link\nipv4.addresses: 10.50.0.10/24\nipv4.method: manual"),
    V2(id="nmcli-connection_add-v2-0023", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Create a new ethernet profile named 'eth1-static' bound to eth1.",
       args={"type": "ethernet", "con_name": "eth1-static", "ifname": "eth1", "operation": "connection_add"},
       answer="connection 'eth1-static' (a1b2c3d4-0001) successfully added"),
    V2(id="nmcli-connection_add-v2-0024", tool="nmcli", operation="connection_add",
       complexity="diagnostic",
       user_input="The second NIC on this box has never had a profile assigned \u2014 set one up for ens256.",
       args={"type": "ethernet", "con_name": "ens256-default", "ifname": "ens256", "operation": "connection_add"},
       answer="connection 'ens256-default' (a1b2c3d4-0002) successfully added"),
    V2(id="nmcli-connection_add-v2-0025", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Add a static-IP ethernet connection on eth0 with address 10.0.1.50/24 and gateway 10.0.1.1.",
       args={"type": "ethernet", "con_name": "eth0-static", "ifname": "eth0", "ip4": "10.0.1.50/24", "gw4": "10.0.1.1", "operation": "connection_add"},
       answer="connection 'eth0-static' (a1b2c3d4-0003) successfully added"),
    V2(id="nmcli-connection_add-v2-0026", tool="nmcli", operation="connection_add",
       complexity="multi",
       user_input="Create a WiFi connection profile on wlan0 and then bring it up.",
       args={"type": "wifi", "con_name": "wlan0-office", "ifname": "wlan0", "operation": "connection_add"},
       answer="connection 'wlan0-office' (a1b2c3d4-0004) successfully added\nconnection activated"),
    V2(id="nmcli-connection_add-v2-0027", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Add an ethernet profile called 'backup-link' on ens224 using DHCP.",
       args={"type": "ethernet", "con_name": "backup-link", "ifname": "ens224", "operation": "connection_add"},
       answer="connection 'backup-link' (a1b2c3d4-0005) successfully added"),
    V2(id="nmcli-connection_add-v2-0028", tool="nmcli", operation="connection_add",
       complexity="diagnostic",
       user_input="Provisioning left ens192 with no NetworkManager profile at all, which is why the deploy script keeps failing \u2014 create a static one for it.",
       args={"type": "ethernet", "con_name": "ens192-static", "ifname": "ens192", "ip4": "10.0.2.15/24", "gw4": "10.0.2.1", "operation": "connection_add"},
       answer="connection 'ens192-static' (a1b2c3d4-0006) successfully added"),
    V2(id="nmcli-connection_add-v2-0029", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Set up a bond connection profile named 'bond0' on interface bond0.",
       args={"type": "bond", "con_name": "bond0", "ifname": "bond0", "operation": "connection_add"},
       answer="connection 'bond0' (a1b2c3d4-0007) successfully added"),
    V2(id="nmcli-connection_add-v2-0030", tool="nmcli", operation="connection_add",
       complexity="diagnostic",
       user_input="The storage host was reimaged and lost its network config \u2014 create a fresh static profile for ens160 at 172.16.20.10/24.",
       args={"type": "ethernet", "con_name": "ens160-storage", "ifname": "ens160", "ip4": "172.16.20.10/24", "gw4": "172.16.20.1", "operation": "connection_add"},
       answer="connection 'ens160-storage' (a1b2c3d4-0008) successfully added"),
    V2(id="nmcli-connection_add-v2-0031", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Add a new ethernet profile 'mgmt-vlan' on ens224.100.",
       args={"type": "ethernet", "con_name": "mgmt-vlan", "ifname": "ens224.100", "operation": "connection_add"},
       answer="connection 'mgmt-vlan' (a1b2c3d4-0009) successfully added"),
    V2(id="nmcli-connection_add-v2-0032", tool="nmcli", operation="connection_add",
       complexity="diagnostic",
       user_input="Interface eth2 shows up in ip link but has no NetworkManager profile \u2014 why can't it get configured? Create one so it can be managed.",
       args={"type": "ethernet", "con_name": "eth2-managed", "ifname": "eth2", "operation": "connection_add"},
       answer="connection 'eth2-managed' (a1b2c3d4-0010) successfully added"),
    V2(id="nmcli-connection_add-v2-0033", tool="nmcli", operation="connection_add",
       complexity="single",
       user_input="Create an ethernet connection 'wan-uplink' bound to eth3 with IP 203.0.113.5/29.",
       args={"type": "ethernet", "con_name": "wan-uplink", "ifname": "eth3", "ip4": "203.0.113.5/29", "operation": "connection_add"},
       answer="connection 'wan-uplink' (a1b2c3d4-0011) successfully added"),
    V2(id="nmcli-connection_modify-v2-0034", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Set the MTU on 'storage-net' to 9000.",
       args={"name": "storage-net", "property": "802-3-ethernet.mtu", "value": "9000", "operation": "connection_modify"},
       answer="connection 'storage-net' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0035", tool="nmcli", operation="connection_modify",
       complexity="diagnostic",
       user_input="Traffic keeps leaving via the wrong uplink \u2014 set ipv4.route-metric to 50 on 'eth1-mgmt' so it wins over the default route.",
       args={"name": "eth1-mgmt", "property": "ipv4.route-metric", "value": "50", "operation": "connection_modify"},
       answer="connection 'eth1-mgmt' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0036", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Disable autoconnect on 'guest-wifi'.",
       args={"name": "guest-wifi", "property": "connection.autoconnect", "value": "no", "operation": "connection_modify"},
       answer="connection 'guest-wifi' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0037", tool="nmcli", operation="connection_modify",
       complexity="multi",
       user_input="Change the IP address on 'eth0-static' to 192.168.10.20/24 and then bring the connection back up.",
       args={"name": "eth0-static", "property": "ipv4.addresses", "value": "192.168.10.20/24", "operation": "connection_modify"},
       answer="connection 'eth0-static' successfully modified\nconnection activated"),
    V2(id="nmcli-connection_modify-v2-0038", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Set ipv4.route-metric to 100 on 'Wired connection 1'.",
       args={"name": "Wired connection 1", "property": "ipv4.route-metric", "value": "100", "operation": "connection_modify"},
       answer="connection 'Wired connection 1' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0039", tool="nmcli", operation="connection_modify",
       complexity="diagnostic",
       user_input="This node reboots into a stale IP every time \u2014 check if 'ens192-static' still needs autoconnect turned on, and enable it.",
       args={"name": "ens192-static", "property": "connection.autoconnect", "value": "yes", "operation": "connection_modify"},
       answer="connection 'ens192-static' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0040", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Turn on autoconnect for 'backup-link'.",
       args={"name": "backup-link", "property": "connection.autoconnect", "value": "yes", "operation": "connection_modify"},
       answer="connection 'backup-link' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0041", tool="nmcli", operation="connection_modify",
       complexity="diagnostic",
       user_input="Jumbo frames aren't working on the storage VLAN \u2014 is the MTU actually set to 9000 on 'ens256-storage'? Set it if not.",
       args={"name": "ens256-storage", "property": "802-3-ethernet.mtu", "value": "9000", "operation": "connection_modify"},
       answer="connection 'ens256-storage' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0042", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Set the DNS search domain on 'eth0-mgmt' to corp.example.com.",
       args={"name": "eth0-mgmt", "property": "ipv4.dns-search", "value": "corp.example.com", "operation": "connection_modify"},
       answer="connection 'eth0-mgmt' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0043", tool="nmcli", operation="connection_modify",
       complexity="diagnostic",
       user_input="The bonded interface isn't failing over \u2014 check the bond mode on 'bond0' and switch it to active-backup.",
       args={"name": "bond0", "property": "bond.options", "value": "mode=active-backup,miimon=100", "operation": "connection_modify"},
       answer="connection 'bond0' successfully modified"),
    V2(id="nmcli-connection_modify-v2-0044", tool="nmcli", operation="connection_modify",
       complexity="single",
       user_input="Change the gateway on 'ens160-storage' to 172.16.20.254.",
       args={"name": "ens160-storage", "property": "ipv4.gateway", "value": "172.16.20.254", "operation": "connection_modify"},
       answer="connection 'ens160-storage' successfully modified"),
    V2(id="nmcli-connection_up-v2-0045", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Bring up the 'eth0-static' connection.",
       args={"name": "eth0-static", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/12)"),
    V2(id="nmcli-connection_up-v2-0046", tool="nmcli", operation="connection_up",
       complexity="diagnostic",
       user_input="eth1 shows unavailable and the backup traffic is dropping \u2014 bring the 'eth1-backup' profile up.",
       args={"name": "eth1-backup", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/13)"),
    V2(id="nmcli-connection_up-v2-0047", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Activate the 'backup-link' profile.",
       args={"name": "backup-link", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/14)"),
    V2(id="nmcli-connection_up-v2-0048", tool="nmcli", operation="connection_up",
       complexity="multi",
       user_input="Bring up 'storage-net' and confirm the interface shows connected afterward.",
       args={"name": "storage-net", "operation": "connection_up"},
       answer="connection successfully activated\nDEVICE  STATE\nens256  connected"),
    V2(id="nmcli-connection_up-v2-0049", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Connect the 'ens224-vlan100' profile.",
       args={"name": "ens224-vlan100", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/15)"),
    V2(id="nmcli-connection_up-v2-0050", tool="nmcli", operation="connection_up",
       complexity="diagnostic",
       user_input="The mgmt VLAN dropped after the switch reload \u2014 try bringing 'mgmt-vlan' back up.",
       args={"name": "mgmt-vlan", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/16)"),
    V2(id="nmcli-connection_up-v2-0051", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Start the 'wan-uplink' connection profile.",
       args={"name": "wan-uplink", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/17)"),
    V2(id="nmcli-connection_up-v2-0052", tool="nmcli", operation="connection_up",
       complexity="diagnostic",
       user_input="The db-storage interface never came up after the reboot \u2014 activate it now.",
       args={"name": "db-storage", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/18)"),
    V2(id="nmcli-connection_up-v2-0053", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Bring 'bond0' online.",
       args={"name": "bond0", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/19)"),
    V2(id="nmcli-connection_up-v2-0054", tool="nmcli", operation="connection_up",
       complexity="diagnostic",
       user_input="ens160-storage shows disconnected but the switch port is up \u2014 activate the profile and see if it takes.",
       args={"name": "ens160-storage", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/20)"),
    V2(id="nmcli-connection_up-v2-0055", tool="nmcli", operation="connection_up",
       complexity="single",
       user_input="Activate 'eth2-managed'.",
       args={"name": "eth2-managed", "operation": "connection_up"},
       answer="connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/21)"),
    V2(id="nmcli-connection_down-v2-0056", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Bring down the 'guest-wifi' connection.",
       args={"name": "guest-wifi", "operation": "connection_down"},
       answer="connection 'guest-wifi' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0057", tool="nmcli", operation="connection_down",
       complexity="diagnostic",
       user_input="The storage network profile is conflicting with the mgmt interface's subnet \u2014 take it down.",
       args={"name": "storage-net", "operation": "connection_down"},
       answer="connection 'storage-net' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0058", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Disconnect 'eth1-backup' for maintenance.",
       args={"name": "eth1-backup", "operation": "connection_down"},
       answer="connection 'eth1-backup' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0059", tool="nmcli", operation="connection_down",
       complexity="multi",
       user_input="Bring down 'ens192-dhcp' and then bring up 'ens192-static' in its place.",
       args={"name": "ens192-dhcp", "operation": "connection_down"},
       answer="connection 'ens192-dhcp' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0060", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Deactivate the 'wan-uplink' profile.",
       args={"name": "wan-uplink", "operation": "connection_down"},
       answer="connection 'wan-uplink' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0061", tool="nmcli", operation="connection_down",
       complexity="diagnostic",
       user_input="Duplicate IP warnings started after 'backup-link' and 'eth0-static' both came up on the same subnet \u2014 take 'backup-link' down.",
       args={"name": "backup-link", "operation": "connection_down"},
       answer="connection 'backup-link' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0062", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Bring 'mgmt-vlan' offline.",
       args={"name": "mgmt-vlan", "operation": "connection_down"},
       answer="connection 'mgmt-vlan' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0063", tool="nmcli", operation="connection_down",
       complexity="diagnostic",
       user_input="We're decommissioning the old link \u2014 deactivate the 'ens224-vlan100' profile before removing the cable.",
       args={"name": "ens224-vlan100", "operation": "connection_down"},
       answer="connection 'ens224-vlan100' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0064", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Take down the 'bond0' connection.",
       args={"name": "bond0", "operation": "connection_down"},
       answer="connection 'bond0' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0065", tool="nmcli", operation="connection_down",
       complexity="diagnostic",
       user_input="Two profiles are fighting over the same interface and flapping the link \u2014 bring 'eth2-managed' down so only one is active.",
       args={"name": "eth2-managed", "operation": "connection_down"},
       answer="connection 'eth2-managed' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0066", tool="nmcli", operation="connection_down",
       complexity="single",
       user_input="Deactivate 'db-storage' for the migration window.",
       args={"name": "db-storage", "operation": "connection_down"},
       answer="connection 'db-storage' successfully deactivated"),
    V2(id="nmcli-connection_down-v2-0067", tool="nmcli", operation="connection_down",
       complexity="diagnostic",
       user_input="The switch port for ens160 is being replaced \u2014 bring 'ens160-storage' down before the tech pulls the cable.",
       args={"name": "ens160-storage", "operation": "connection_down"},
       answer="connection 'ens160-storage' successfully deactivated"),
    V2(id="nmcli-connection_delete-v2-0068", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Permanently delete the 'old-vpn' connection profile.",
       args={"name": "old-vpn", "operation": "connection_delete"},
       answer="connection 'old-vpn' (b2c3d4e5-0001) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0069", tool="nmcli", operation="connection_delete",
       complexity="diagnostic",
       user_input="The interface keeps bouncing between two profiles bound to the same NIC \u2014 delete the stale 'ens192-dhcp' one.",
       args={"name": "ens192-dhcp", "operation": "connection_delete"},
       answer="connection 'ens192-dhcp' (b2c3d4e5-0002) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0070", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Remove the 'test-dhcp' profile from NetworkManager.",
       args={"name": "test-dhcp", "operation": "connection_delete"},
       answer="connection 'test-dhcp' (b2c3d4e5-0003) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0071", tool="nmcli", operation="connection_delete",
       complexity="multi",
       user_input="Show the list of connection profiles, find the duplicate one, then delete it.",
       args={"name": "Wired connection 2", "operation": "connection_delete"},
       answer="connection 'Wired connection 2' (b2c3d4e5-0004) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0072", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Delete the 'Wired connection 2' profile permanently.",
       args={"name": "Wired connection 2", "operation": "connection_delete"},
       answer="connection 'Wired connection 2' (b2c3d4e5-0005) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0073", tool="nmcli", operation="connection_delete",
       complexity="diagnostic",
       user_input="This host has a leftover WiFi profile from before it went headless and it's not needed anymore \u2014 remove 'wlan0-office'.",
       args={"name": "wlan0-office", "operation": "connection_delete"},
       answer="connection 'wlan0-office' (b2c3d4e5-0006) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0074", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Get rid of the 'legacy-bond' connection profile.",
       args={"name": "legacy-bond", "operation": "connection_delete"},
       answer="connection 'legacy-bond' (b2c3d4e5-0007) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0075", tool="nmcli", operation="connection_delete",
       complexity="diagnostic",
       user_input="We're consolidating VLANs and 'mgmt-vlan-old' was replaced weeks ago \u2014 delete it so it stops showing in inventory.",
       args={"name": "mgmt-vlan-old", "operation": "connection_delete"},
       answer="connection 'mgmt-vlan-old' (b2c3d4e5-0008) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0076", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Remove the 'staging-net' profile from this host.",
       args={"name": "staging-net", "operation": "connection_delete"},
       answer="connection 'staging-net' (b2c3d4e5-0009) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0077", tool="nmcli", operation="connection_delete",
       complexity="diagnostic",
       user_input="Someone left a duplicate 'eth0-static-copy' profile after a botched migration \u2014 delete it.",
       args={"name": "eth0-static-copy", "operation": "connection_delete"},
       answer="connection 'eth0-static-copy' (b2c3d4e5-0010) successfully deleted"),
    V2(id="nmcli-connection_delete-v2-0078", tool="nmcli", operation="connection_delete",
       complexity="single",
       user_input="Permanently remove the 'sandbox-wifi' connection.",
       args={"name": "sandbox-wifi", "operation": "connection_delete"},
       answer="connection 'sandbox-wifi' (b2c3d4e5-0011) successfully deleted"),
    V2(id="nmcli-wifi_list-v2-0079", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="Show me all Wi-Fi networks visible from this machine.",
       args={"operation": "wifi_list"},
       answer="SSID          SIGNAL  SECURITY\nOfficeWifi    82      WPA2\nGuestNet      45      WPA2\nOpenLobby     30      --"),
    V2(id="nmcli-wifi_list-v2-0080", tool="nmcli", operation="wifi_list",
       complexity="diagnostic",
       user_input="The Wi-Fi keeps dropping in the warehouse \u2014 scan and show signal strength for what's visible.",
       args={"operation": "wifi_list"},
       answer="SSID          SIGNAL  SECURITY\nWarehouseNet  28      WPA2\nOfficeWifi    15      WPA2"),
    V2(id="nmcli-wifi_list-v2-0081", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="List Wi-Fi networks on wlan0.",
       args={"ifname": "wlan0", "operation": "wifi_list"},
       answer="SSID        SIGNAL  SECURITY\nCorpWireless  70    WPA2-Enterprise"),
    V2(id="nmcli-wifi_list-v2-0082", tool="nmcli", operation="wifi_list",
       complexity="multi",
       user_input="Scan for Wi-Fi networks on wlan1 and tell me which ones use WPA2.",
       args={"ifname": "wlan1", "operation": "wifi_list"},
       answer="SSID       SIGNAL  SECURITY\nLabNet     60      WPA2\nOpenTest   40      --\nWPA2 networks: LabNet"),
    V2(id="nmcli-wifi_list-v2-0083", tool="nmcli", operation="wifi_list",
       complexity="diagnostic",
       user_input="This laptop can't find the office network at all \u2014 what SSIDs does it actually see?",
       args={"operation": "wifi_list"},
       answer="SSID        SIGNAL  SECURITY\nNeighborNet  55     WPA2\nno match for 'OfficeWifi'"),
    V2(id="nmcli-wifi_list-v2-0084", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="What wireless networks are in range right now?",
       args={"operation": "wifi_list"},
       answer="SSID        SIGNAL  SECURITY\nSiteB-Wifi   65     WPA2"),
    V2(id="nmcli-wifi_list-v2-0085", tool="nmcli", operation="wifi_list",
       complexity="diagnostic",
       user_input="The site survey flagged an unknown access point nearby \u2014 scan and see what SSIDs are broadcasting.",
       args={"operation": "wifi_list"},
       answer="SSID          SIGNAL  SECURITY\nOfficeWifi    80     WPA2\nUnknownAP-42  20     WEP"),
    V2(id="nmcli-wifi_list-v2-0086", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="Scan for available Wi-Fi access points on wlan0.",
       args={"ifname": "wlan0", "operation": "wifi_list"},
       answer="SSID        SIGNAL  SECURITY\nEmergencyWifi  50   WPA2"),
    V2(id="nmcli-wifi_list-v2-0087", tool="nmcli", operation="wifi_list",
       complexity="diagnostic",
       user_input="Roaming clients report dropped connections near the loading dock \u2014 what access points are visible from there?",
       args={"operation": "wifi_list"},
       answer="SSID           SIGNAL  SECURITY\nDockNet        35      WPA2\nOfficeWifi     10      WPA2"),
    V2(id="nmcli-wifi_list-v2-0088", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="Give me the list of nearby SSIDs and their security type.",
       args={"operation": "wifi_list"},
       answer="SSID        SIGNAL  SECURITY\nCorpWireless  75    WPA2-Enterprise\nGuestNet      40   WPA2"),
    V2(id="nmcli-wifi_list-v2-0089", tool="nmcli", operation="wifi_list",
       complexity="diagnostic",
       user_input="A rogue access point alert triggered near the server room \u2014 list what's currently visible to this box.",
       args={"operation": "wifi_list"},
       answer="SSID          SIGNAL  SECURITY\nOfficeWifi    85     WPA2\nFreeWifi-Now  60     --"),
    V2(id="nmcli-wifi_list-v2-0090", tool="nmcli", operation="wifi_list",
       complexity="single",
       user_input="Rescan and show Wi-Fi networks visible on wlan2.",
       args={"ifname": "wlan2", "operation": "wifi_list"},
       answer="SSID       SIGNAL  SECURITY\nLabNet-5G  90      WPA2"),
    V2(id="nmcli-wifi_connect-v2-0091", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Connect this machine to the 'OfficeWifi' network.",
       args={"ssid": "OfficeWifi", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0092", tool="nmcli", operation="wifi_connect",
       complexity="diagnostic",
       user_input="The wired uplink just went down in the server room \u2014 join 'EmergencyWifi' as a fallback.",
       args={"ssid": "EmergencyWifi", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0093", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Join 'CorpWireless' using the passphrase Winter2026!.",
       args={"ssid": "CorpWireless", "password": "Winter2026!", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0094", tool="nmcli", operation="wifi_connect",
       complexity="multi",
       user_input="Connect to 'SiteB-Wifi' and then verify an IP address was assigned.",
       args={"ssid": "SiteB-Wifi", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')\nIP4.ADDRESS: 10.5.2.14/24"),
    V2(id="nmcli-wifi_connect-v2-0095", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Connect to the 'WarehouseNet' access point with password Forklift88.",
       args={"ssid": "WarehouseNet", "password": "Forklift88", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan1')"),
    V2(id="nmcli-wifi_connect-v2-0096", tool="nmcli", operation="wifi_connect",
       complexity="diagnostic",
       user_input="The dock scanner tablet lost its wired connection and needs to fail over \u2014 join it to 'DockNet'.",
       args={"ssid": "DockNet", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0097", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Connect wlan0 to 'LabNet-5G' with passphrase Bench2024#.",
       args={"ssid": "LabNet-5G", "password": "Bench2024#", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0098", tool="nmcli", operation="wifi_connect",
       complexity="diagnostic",
       user_input="The switch feeding this rack is being swapped tonight \u2014 connect to 'GuestNet' temporarily so monitoring stays up.",
       args={"ssid": "GuestNet", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0099", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Join the open network 'OpenLobby'.",
       args={"ssid": "OpenLobby", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0100", tool="nmcli", operation="wifi_connect",
       complexity="diagnostic",
       user_input="Field techs need connectivity while the site's main link is being fiber-spliced \u2014 connect to 'SiteB-Wifi' with password Fiber2026.",
       args={"ssid": "SiteB-Wifi", "password": "Fiber2026", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0101", tool="nmcli", operation="wifi_connect",
       complexity="single",
       user_input="Connect to 'NeighborNet' as a last resort using password Guest1234.",
       args={"ssid": "NeighborNet", "password": "Guest1234", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-wifi_connect-v2-0102", tool="nmcli", operation="wifi_connect",
       complexity="diagnostic",
       user_input="The primary uplink to the loading dock kiosk is flaky \u2014 switch it over to 'DockNet' with password Pallet55.",
       args={"ssid": "DockNet", "password": "Pallet55", "operation": "wifi_connect"},
       answer="connection successfully activated (device 'wlan0')"),
    V2(id="nmcli-dns_configure-v2-0103", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Set DNS on 'eth0-static' to 8.8.8.8 and 8.8.4.4.",
       args={"name": "eth0-static", "dns": "8.8.8.8 8.8.4.4", "operation": "dns_configure"},
       answer="connection 'eth0-static' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0104", tool="nmcli", operation="dns_configure",
       complexity="diagnostic",
       user_input="Hostname resolution is failing across the board \u2014 point the active profile at 1.1.1.1 as a quick fix.",
       args={"name": "eth0-mgmt", "dns": "1.1.1.1", "operation": "dns_configure"},
       answer="connection 'eth0-mgmt' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0105", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Configure 'storage-net' to use 192.168.1.1 for DNS.",
       args={"name": "storage-net", "dns": "192.168.1.1", "operation": "dns_configure"},
       answer="connection 'storage-net' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0106", tool="nmcli", operation="dns_configure",
       complexity="multi",
       user_input="Set DNS on 'eth0-mgmt' to the company resolvers and then reactivate the profile.",
       args={"name": "eth0-mgmt", "dns": "10.0.0.53 10.0.0.54", "operation": "dns_configure"},
       answer="connection 'eth0-mgmt' successfully modified\nconnection activated"),
    V2(id="nmcli-dns_configure-v2-0107", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Point 'Wired connection 1' at the internal DNS server 10.0.0.53.",
       args={"name": "Wired connection 1", "dns": "10.0.0.53", "operation": "dns_configure"},
       answer="connection 'Wired connection 1' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0108", tool="nmcli", operation="dns_configure",
       complexity="diagnostic",
       user_input="Internal service names resolve fine but external lookups time out \u2014 check whether 'wan-uplink' has a public resolver set, and set 8.8.8.8 if not.",
       args={"name": "wan-uplink", "dns": "8.8.8.8", "operation": "dns_configure"},
       answer="connection 'wan-uplink' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0109", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Set the nameservers on 'ens192-static' to 10.0.2.53 and 10.0.2.54.",
       args={"name": "ens192-static", "dns": "10.0.2.53 10.0.2.54", "operation": "dns_configure"},
       answer="connection 'ens192-static' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0110", tool="nmcli", operation="dns_configure",
       complexity="diagnostic",
       user_input="This box is still using the ISP resolver instead of our internal one, which is breaking split-horizon DNS \u2014 fix 'eth0-static' to use 10.0.0.10.",
       args={"name": "eth0-static", "dns": "10.0.0.10", "operation": "dns_configure"},
       answer="connection 'eth0-static' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0111", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Update 'backup-link' to resolve via 9.9.9.9.",
       args={"name": "backup-link", "dns": "9.9.9.9", "operation": "dns_configure"},
       answer="connection 'backup-link' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0112", tool="nmcli", operation="dns_configure",
       complexity="diagnostic",
       user_input="Users report intermittent name resolution on the mgmt VLAN \u2014 set 'mgmt-vlan' to use the redundant pair 10.0.0.53 10.0.0.54.",
       args={"name": "mgmt-vlan", "dns": "10.0.0.53 10.0.0.54", "operation": "dns_configure"},
       answer="connection 'mgmt-vlan' successfully modified"),
    V2(id="nmcli-dns_configure-v2-0113", tool="nmcli", operation="dns_configure",
       complexity="single",
       user_input="Set DNS to 4.2.2.2 on the 'db-storage' connection.",
       args={"name": "db-storage", "dns": "4.2.2.2", "operation": "dns_configure"},
       answer="connection 'db-storage' successfully modified"),
]

from finetune.scenarios_v2 import check_module; check_module("nmcli", SCENARIOS_V2)
