"""finetune/scenarios_v2/pam.py — corpus v2 scenarios for 'pam'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="pam-pamd_audit-v2-0001", tool="pam", operation="pamd_audit",
       complexity="single",
       user_input="Show me what's configured for the sudo PAM service.",
       args={"operation": "pamd_audit", "service": "sudo"},
       answer="#%PAM-1.0\nauth include system-auth\naccount include system-auth\nsession include postlogin"),
    V2(id="pam-pamd_audit-v2-0002", tool="pam", operation="pamd_audit",
       complexity="diagnostic",
       user_input="Users say they can log in over ssh with an expired password when they shouldn't be able to — check the sshd config in pam.d.",
       args={"operation": "pamd_audit", "service": "sshd"},
       answer="#%PAM-1.0\nauth substack password-auth\naccount required pam_nologin.so\npassword substack password-auth"),
    V2(id="pam-pamd_audit-v2-0003", tool="pam", operation="pamd_audit",
       complexity="single",
       user_input="dump the login service config",
       args={"operation": "pamd_audit", "service": "login"},
       answer="#%PAM-1.0\nauth substack system-auth\naccount required pam_nologin.so\nsession optional pam_lastlog.so"),
    V2(id="pam-pamd_audit-v2-0004", tool="pam", operation="pamd_audit",
       complexity="multi",
       user_input="Check the passwd service config, then I'll decide whether to enable pwquality.",
       args={"operation": "pamd_audit", "service": "passwd"},
       answer="#%PAM-1.0\npassword substack system-auth\npassword optional pam_gnome_keyring.so"),
    V2(id="pam-faillock_status-v2-0001", tool="pam", operation="faillock_status",
       complexity="single",
       user_input="How many failed login attempts does jsmith have?",
       args={"operation": "faillock_status", "user": "jsmith"},
       answer="jsmith:\nWhen                Type  Source\n2026-09-12 14:02:19 RHOST 10.0.4.18\nTally: 2"),
    V2(id="pam-faillock_status-v2-0002", tool="pam", operation="faillock_status",
       complexity="diagnostic",
       user_input="A contractor account keeps getting locked out overnight — can you show the faillock tallies for user cbrooks?",
       args={"operation": "faillock_status", "user": "cbrooks"},
       answer="cbrooks:\nWhen                Type  Source\n2026-09-12 02:14:07 RHOST 203.0.113.44\nTally: 7 (locked)"),
    V2(id="pam-faillock_status-v2-0003", tool="pam", operation="faillock_status",
       complexity="single",
       user_input="show faillock tallies for everyone",
       args={"operation": "faillock_status"},
       answer="jsmith: Tally 2\ncbrooks: Tally 7 (locked)\nadmin_svc: Tally 0"),
    V2(id="pam-faillock_status-v2-0004", tool="pam", operation="faillock_status",
       complexity="multi",
       user_input="Check the faillock count on rtan, then reset it if it's locked.",
       args={"operation": "faillock_status", "user": "rtan"},
       answer="rtan:\nWhen                Type  Source\n2026-09-11 19:44:52 RHOST 192.168.1.55\nTally: 5 (locked)"),
    V2(id="pam-faillock_status-v2-0005", tool="pam", operation="faillock_status",
       complexity="diagnostic",
       user_input="Ticket 6603 says svc_backup can't authenticate to sudo — is that account faillocked?",
       args={"operation": "faillock_status", "user": "svc_backup"},
       answer="svc_backup:\nWhen                Type  Source\n2026-09-12 03:00:11 RHOST 127.0.0.1\nTally: 3"),
    V2(id="pam-faillock_reset-v2-0001", tool="pam", operation="faillock_reset",
       complexity="single",
       user_input="Reset the failed login tally for cbrooks.",
       args={"operation": "faillock_reset", "user": "cbrooks"},
       answer="faillock reset for cbrooks\ntally now: 0"),
    V2(id="pam-faillock_reset-v2-0002", tool="pam", operation="faillock_reset",
       complexity="diagnostic",
       user_input="rtan is locked out of sudo again after too many wrong passwords — can you clear that?",
       args={"operation": "faillock_reset", "user": "rtan"},
       answer="faillock reset for rtan\ntally now: 0"),
    V2(id="pam-faillock_reset-v2-0003", tool="pam", operation="faillock_reset",
       complexity="single",
       user_input="clear the lockout on user dpierce",
       args={"operation": "faillock_reset", "user": "dpierce"},
       answer="faillock reset for dpierce\ntally now: 0"),
    V2(id="pam-faillock_reset-v2-0004", tool="pam", operation="faillock_reset",
       complexity="multi",
       user_input="Reset faillock for everyone, then have jsmith try logging in again.",
       args={"operation": "faillock_reset"},
       answer="faillock reset for all users\ntallies cleared: 4"),
    V2(id="pam-faillock_reset-v2-0005", tool="pam", operation="faillock_reset",
       complexity="single",
       user_input="wipe the faillock counter for svc_backup",
       args={"operation": "faillock_reset", "user": "svc_backup"},
       answer="faillock reset for svc_backup\ntally now: 0"),
    V2(id="pam-faillock_reset-v2-0006", tool="pam", operation="faillock_reset",
       complexity="diagnostic",
       user_input="After the password reset for admin_svc it's still refusing logins — could a stale faillock tally be the cause?",
       args={"operation": "faillock_reset", "user": "admin_svc"},
       answer="faillock reset for admin_svc\ntally now: 0"),
    V2(id="pam-pam_auth_update-v2-0001", tool="pam", operation="pam_auth_update",
       complexity="single",
       user_input="Enable the mkhomedir PAM profile.",
       args={"operation": "pam_auth_update", "profile": "mkhomedir", "action": "enable"},
       answer="pam-auth-update: mkhomedir enabled\nverify in a separate session before closing this one"),
    V2(id="pam-pam_auth_update-v2-0002", tool="pam", operation="pam_auth_update",
       complexity="diagnostic",
       user_input="New LDAP users aren't getting home directories created on first login — is the mkhomedir profile even turned on?",
       args={"operation": "pam_auth_update", "profile": "mkhomedir"},
       answer="pam-auth-update: mkhomedir enabled\nverify in a separate session before closing this one"),
    V2(id="pam-pam_auth_update-v2-0003", tool="pam", operation="pam_auth_update",
       complexity="single",
       user_input="turn off the faillock profile for now",
       args={"operation": "pam_auth_update", "profile": "faillock", "action": "disable"},
       answer="pam-auth-update: faillock disabled\nverify in a separate session before closing this one"),
    V2(id="pam-pam_auth_update-v2-0004", tool="pam", operation="pam_auth_update",
       complexity="multi",
       user_input="Enable pwquality, then I want to test a login with a weak password to confirm it's rejected.",
       args={"operation": "pam_auth_update", "profile": "pwquality", "action": "enable"},
       answer="pam-auth-update: pwquality enabled\nverify in a separate session before closing this one"),
]

from finetune.scenarios_v2 import check_module; check_module("pam", SCENARIOS_V2)
