"""finetune/scenarios_v2/performance.py — corpus v2 scenarios for 'performance'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # sar (8)
    V2(id="performance-sar-v2-0001", tool="performance", operation="sar", complexity="single",
       user_input="Run sar for one sample.",
       args={"operation": "sar"},
       answer="09:30:01 AM     CPU     %user     %sys   %iowait   %idle\n09:30:02 AM     all      12.40     3.10      0.50     84.00"),
    V2(id="performance-sar-v2-0002", tool="performance", operation="sar", complexity="diagnostic",
       user_input="Batch jobs on host09 are taking twice as long today — pull a 5-sample sar run at 2 second intervals to see if we're CPU bound.",
       args={"operation": "sar", "interval": 2, "count": 5},
       answer="Average:        all      88.20     6.30      1.10      4.40\nsystem time elevated across all 5 samples"),
    V2(id="performance-sar-v2-0003", tool="performance", operation="sar", complexity="single",
       user_input="sar with a 1s interval, 10 samples",
       args={"operation": "sar", "interval": 1, "count": 10},
       answer="Average:        all      22.10     4.00      0.30     73.60"),
    V2(id="performance-sar-v2-0004", tool="performance", operation="sar", complexity="multi",
       user_input="Check CPU utilization with sar over 3 samples, then look at iostat if idle time is low.",
       args={"operation": "sar", "count": 3},
       answer="Average:        all      65.00     8.20      2.00     24.80"),
    V2(id="performance-sar-v2-0005", tool="performance", operation="sar", complexity="single",
       user_input="Ticket 2210: capture a 5-second sar sample on db04 before the load test starts.",
       args={"operation": "sar", "interval": 5, "count": 1},
       answer="09:41:10 AM     CPU     %user     %sys   %iowait   %idle\n09:41:15 AM     all       9.80     2.10      0.10     87.90"),
    V2(id="performance-sar-v2-0006", tool="performance", operation="sar", complexity="diagnostic",
       user_input="Users say the web tier feels sluggish since the deploy — grab a quick sar reading to check idle CPU.",
       args={"operation": "sar"},
       answer="09:44:02 AM     CPU     %user     %sys   %iowait   %idle\n09:44:03 AM     all      95.10     3.20      0.20      1.50"),
    V2(id="performance-sar-v2-0007", tool="performance", operation="sar", complexity="single",
       user_input="Collect CPU stats, 4 samples at 3 second spacing.",
       args={"operation": "sar", "interval": 3, "count": 4},
       answer="Average:        all      30.75     5.10      0.60     63.55"),
    V2(id="performance-sar-v2-0008", tool="performance", operation="sar", complexity="single",
       user_input="one-shot sar reading on the render node please",
       args={"operation": "sar"},
       answer="09:50:00 AM     CPU     %user     %sys   %iowait   %idle\n09:50:01 AM     all      41.30     2.90      0.00     55.80"),

    # iostat (8)
    V2(id="performance-iostat-v2-0001", tool="performance", operation="iostat", complexity="single",
       user_input="Run iostat once.",
       args={"operation": "iostat"},
       answer="Device    tps    kB_read/s   kB_wrtn/s\nsda       42.00     512.00      2048.00\nnvme0n1  310.00    9800.00      4400.00"),
    V2(id="performance-iostat-v2-0002", tool="performance", operation="iostat", complexity="diagnostic",
       user_input="Writes to the database volume feel slow this afternoon — check disk throughput with iostat over 5 samples at 2s.",
       args={"operation": "iostat", "interval": 2, "count": 5},
       answer="Device    tps    kB_read/s   kB_wrtn/s   %util\nsdb      480.00    2200.00     51000.00    98.40"),
    V2(id="performance-iostat-v2-0003", tool="performance", operation="iostat", complexity="single",
       user_input="iostat, 1 second interval, 8 samples",
       args={"operation": "iostat", "interval": 1, "count": 8},
       answer="Device    tps    kB_read/s   kB_wrtn/s\nsda       18.00     100.00       900.00"),
    V2(id="performance-iostat-v2-0004", tool="performance", operation="iostat", complexity="multi",
       user_input="Pull disk I/O stats with iostat, and if %util is high on sdb, check the postgresql service status.",
       args={"operation": "iostat", "count": 3},
       answer="Device    tps    kB_read/s   kB_wrtn/s   %util\nsdb      620.00    3100.00     72000.00    99.10"),
    V2(id="performance-iostat-v2-0005", tool="performance", operation="iostat", complexity="single",
       user_input="Ticket 5510: capture a single iostat reading on the backup server before the nightly job kicks off.",
       args={"operation": "iostat"},
       answer="Device    tps    kB_read/s   kB_wrtn/s\nsda       6.00      40.00       220.00"),
    V2(id="performance-iostat-v2-0006", tool="performance", operation="iostat", complexity="diagnostic",
       user_input="Backups seem to be crawling tonight — is disk throughput actually the bottleneck, not the network?",
       args={"operation": "iostat", "interval": 2, "count": 4},
       answer="Average: sda    tps=410.00  kB_wrtn/s=48000.00  %util=97.80"),
    V2(id="performance-iostat-v2-0007", tool="performance", operation="iostat", complexity="single",
       user_input="get me 10 iostat samples at 1s each on the NAS head",
       args={"operation": "iostat", "interval": 1, "count": 10},
       answer="Average: sda    tps=90.00  kB_read/s=1200.00  kB_wrtn/s=3300.00"),
    V2(id="performance-iostat-v2-0008", tool="performance", operation="iostat", complexity="single",
       user_input="Check disk I/O on the log-shipping box, 5 samples at 3 second spacing.",
       args={"operation": "iostat", "interval": 3, "count": 5},
       answer="Average: sdc    tps=140.00  kB_wrtn/s=9800.00  %util=61.20"),

    # vmstat (9)
    V2(id="performance-vmstat-v2-0001", tool="performance", operation="vmstat", complexity="single",
       user_input="Run vmstat once.",
       args={"operation": "vmstat"},
       answer="procs -----memory---- ---swap-- -----io---- -system-- ------cpu-----\n r  b   free   buff  cache   si so   bi  bo   in   cs us sy id wa\n 2  0  81200  4400 512000  0  0    1   4  120  240 12  3 84  1"),
    V2(id="performance-vmstat-v2-0002", tool="performance", operation="vmstat", complexity="diagnostic",
       user_input="The app server keeps getting OOM-killed — check vmstat over 6 samples at 2s to see swap activity.",
       args={"operation": "vmstat", "interval": 2, "count": 6},
       answer="r  b   free   swpd   si   so\n5  2   9800   40000  120  310\nswap-in/out both nonzero across all samples"),
    V2(id="performance-vmstat-v2-0003", tool="performance", operation="vmstat", complexity="single",
       user_input="vmstat with 1s interval, 5 samples",
       args={"operation": "vmstat", "interval": 1, "count": 5},
       answer="r  b   free   buff  cache\n1  0  120400  3900 480000"),
    V2(id="performance-vmstat-v2-0004", tool="performance", operation="vmstat", complexity="multi",
       user_input="Check memory pressure with vmstat, then check the redis service status if swap is active.",
       args={"operation": "vmstat", "count": 3},
       answer="r  b   free  swpd   si  so\n0  0  15200 22000  200  180"),
    V2(id="performance-vmstat-v2-0005", tool="performance", operation="vmstat", complexity="single",
       user_input="Ticket 3391: capture one vmstat snapshot before restarting the cache warmer.",
       args={"operation": "vmstat"},
       answer="r  b   free   buff  cache\n0  0  95000  4100 500200"),
    V2(id="performance-vmstat-v2-0006", tool="performance", operation="vmstat", complexity="diagnostic",
       user_input="Is memory actually low on the analytics box, or just cached and reclaimable? Grab a vmstat reading.",
       args={"operation": "vmstat"},
       answer="r  b   free   buff   cache\n1  0  20400  6100  890200\nmost of used memory is page cache, not resident"),
    V2(id="performance-vmstat-v2-0007", tool="performance", operation="vmstat", complexity="single",
       user_input="8 vmstat samples at 2 second spacing on the queue worker",
       args={"operation": "vmstat", "interval": 2, "count": 8},
       answer="r  b   free   buff  cache\n2  1  60300  3300 410900"),
    V2(id="performance-vmstat-v2-0008", tool="performance", operation="vmstat", complexity="single",
       user_input="pull system stats with vmstat, 4 samples, 1 second apart",
       args={"operation": "vmstat", "interval": 1, "count": 4},
       answer="r  b   free   buff  cache\n0  0  71200  5000 512300"),
    V2(id="performance-vmstat-v2-0009", tool="performance", operation="vmstat", complexity="single",
       user_input="Ticket 4402: run vmstat, 3 samples at 5 seconds, on the mail relay before we bump its memory limit.",
       args={"operation": "vmstat", "interval": 5, "count": 3},
       answer="r  b   free   buff  cache\n1  0  30500  2900 220100"),

    # mpstat (9)
    V2(id="performance-mpstat-v2-0001", tool="performance", operation="mpstat", complexity="single",
       user_input="Run mpstat once for per-CPU numbers.",
       args={"operation": "mpstat"},
       answer="CPU    %usr   %sys  %iowait  %idle\nall    20.10   4.00     0.50   75.40\n0      88.00   5.00     0.10    6.90"),
    V2(id="performance-mpstat-v2-0002", tool="performance", operation="mpstat", complexity="diagnostic",
       user_input="One core seems pegged on the encoder box — check per-CPU load with mpstat over 5 samples at 2s.",
       args={"operation": "mpstat", "interval": 2, "count": 5},
       answer="CPU    %usr  %idle\nall    24.00  70.00\n3      99.10   0.20\ncore 3 saturated across all 5 samples"),
    V2(id="performance-mpstat-v2-0003", tool="performance", operation="mpstat", complexity="single",
       user_input="mpstat, 1 second interval, 10 samples",
       args={"operation": "mpstat", "interval": 1, "count": 10},
       answer="CPU    %usr   %idle\nall    15.30   80.10"),
    V2(id="performance-mpstat-v2-0004", tool="performance", operation="mpstat", complexity="multi",
       user_input="Get per-core stats with mpstat, then check whether the video-transcode service is pinned to one core.",
       args={"operation": "mpstat", "count": 3},
       answer="CPU    %usr   %idle\nall    40.00   55.00\n1      97.80    1.10"),
    V2(id="performance-mpstat-v2-0005", tool="performance", operation="mpstat", complexity="single",
       user_input="Ticket 6602: single mpstat reading on the compile farm node before we schedule the next batch.",
       args={"operation": "mpstat"},
       answer="CPU    %usr   %idle\nall    10.00   88.00"),
    V2(id="performance-mpstat-v2-0006", tool="performance", operation="mpstat", complexity="diagnostic",
       user_input="Is the load spread evenly across cores on the search index server, or is one thread hogging a CPU?",
       args={"operation": "mpstat"},
       answer="CPU    %usr   %idle\nall    30.00   62.00\n0      95.00    2.00\n1      12.00   85.00"),
    V2(id="performance-mpstat-v2-0007", tool="performance", operation="mpstat", complexity="single",
       user_input="6 mpstat samples, 2 seconds apart, on the ingest worker",
       args={"operation": "mpstat", "interval": 2, "count": 6},
       answer="CPU    %usr   %idle\nall    28.00   66.00"),
    V2(id="performance-mpstat-v2-0008", tool="performance", operation="mpstat", complexity="single",
       user_input="give me per-cpu utilization, 4 samples at 1s",
       args={"operation": "mpstat", "interval": 1, "count": 4},
       answer="CPU    %usr   %idle\nall    18.50   77.90"),
    V2(id="performance-mpstat-v2-0009", tool="performance", operation="mpstat", complexity="single",
       user_input="Ticket 7715: mpstat with 3 samples at 5 second spacing on the media server.",
       args={"operation": "mpstat", "interval": 5, "count": 3},
       answer="CPU    %usr   %idle\nall    22.00   71.00"),

    # uptime (11)
    V2(id="performance-uptime-v2-0001", tool="performance", operation="uptime", complexity="single",
       user_input="What's the uptime on db01?",
       args={"operation": "uptime"},
       answer=" 09:55:01 up 42 days,  3:10,  2 users,  load average: 0.52, 0.61, 0.58"),
    V2(id="performance-uptime-v2-0002", tool="performance", operation="uptime", complexity="diagnostic",
       user_input="Response times have crept up all week on app11 — what does the load average look like right now?",
       args={"operation": "uptime"},
       answer=" 09:56:00 up 12 days,  1:40,  4 users,  load average: 6.40, 5.90, 4.10"),
    V2(id="performance-uptime-v2-0003", tool="performance", operation="uptime", complexity="single",
       user_input="how long has this host been up",
       args={"operation": "uptime"},
       answer=" 09:57:00 up  3:02,  1 user,  load average: 0.10, 0.08, 0.05"),
    V2(id="performance-uptime-v2-0004", tool="performance", operation="uptime", complexity="multi",
       user_input="Check uptime and load average, then look at mpstat if the 1-minute figure looks high.",
       args={"operation": "uptime"},
       answer=" 09:58:00 up 5 days,  0:20,  2 users,  load average: 9.80, 7.20, 5.00"),
    V2(id="performance-uptime-v2-0005", tool="performance", operation="uptime", complexity="single",
       user_input="Ticket 1120: confirm uptime on web09 hasn't reset since the patch window last night.",
       args={"operation": "uptime"},
       answer=" 09:59:00 up 8:10,  1 user,  load average: 0.30, 0.28, 0.25"),
    V2(id="performance-uptime-v2-0006", tool="performance", operation="uptime", complexity="diagnostic",
       user_input="Nagios flagged high load on the reporting server — is that reflected in the load averages?",
       args={"operation": "uptime"},
       answer=" 10:00:00 up 30 days,  2:00,  3 users,  load average: 14.20, 12.90, 10.10"),
    V2(id="performance-uptime-v2-0007", tool="performance", operation="uptime", complexity="single",
       user_input="uptime check on the samba fileserver",
       args={"operation": "uptime"},
       answer=" 10:01:00 up 200 days,  5:40,  1 user,  load average: 0.85, 0.90, 0.88"),
    V2(id="performance-uptime-v2-0008", tool="performance", operation="uptime", complexity="single",
       user_input="How many days has the cluster head node been running?",
       args={"operation": "uptime"},
       answer=" 10:02:00 up 90 days,  0:05,  2 users,  load average: 2.10, 2.00, 1.95"),
    V2(id="performance-uptime-v2-0009", tool="performance", operation="uptime", complexity="diagnostic",
       user_input="An sssd auth timeout showed up in the logs — is the box itself under heavy load or is this isolated to auth?",
       args={"operation": "uptime"},
       answer=" 10:03:00 up 15 days,  4:00,  6 users,  load average: 1.20, 1.10, 1.00"),
    V2(id="performance-uptime-v2-0010", tool="performance", operation="uptime", complexity="single",
       user_input="Ticket 9981: pull uptime for the CI runner before we queue the next build.",
       args={"operation": "uptime"},
       answer=" 10:04:00 up 2 days,  0:00,  1 user,  load average: 3.30, 2.90, 2.20"),
    V2(id="performance-uptime-v2-0011", tool="performance", operation="uptime", complexity="single",
       user_input="give me the load averages on the kvm hypervisor",
       args={"operation": "uptime"},
       answer=" 10:05:00 up 60 days,  9:15,  1 user,  load average: 4.80, 4.50, 4.00"),

    # load (9)
    V2(id="performance-load-v2-0001", tool="performance", operation="load", complexity="single",
       user_input="Read /proc/loadavg on this node.",
       args={"operation": "load"},
       answer="0.45 0.50 0.48 2/310 18821"),
    V2(id="performance-load-v2-0002", tool="performance", operation="load", complexity="diagnostic",
       user_input="The dashboard shows spikes on this VM every few minutes — what does raw loadavg show at this moment?",
       args={"operation": "load"},
       answer="8.90 4.10 2.30 5/402 20015"),
    V2(id="performance-load-v2-0003", tool="performance", operation="load", complexity="single",
       user_input="what's the 5-minute load average",
       args={"operation": "load"},
       answer="1.10 0.95 0.80 1/280 15002"),
    V2(id="performance-load-v2-0004", tool="performance", operation="load", complexity="multi",
       user_input="Check /proc/loadavg, then run mpstat if the 15-minute figure is climbing.",
       args={"operation": "load"},
       answer="5.20 6.10 6.80 3/390 19940"),
    V2(id="performance-load-v2-0005", tool="performance", operation="load", complexity="single",
       user_input="Ticket 2288: grab the load averages on nfs-server before extending its export list.",
       args={"operation": "load"},
       answer="0.20 0.22 0.25 1/210 8801"),
    V2(id="performance-load-v2-0006", tool="performance", operation="load", complexity="diagnostic",
       user_input="Cron says the nightly backup script is still running past its usual window — is the box just overloaded?",
       args={"operation": "load"},
       answer="12.40 10.80 8.90 6/450 22110"),
    V2(id="performance-load-v2-0007", tool="performance", operation="load", complexity="single",
       user_input="pull loadavg for the message broker",
       args={"operation": "load"},
       answer="2.00 1.90 1.70 2/300 17700"),
    V2(id="performance-load-v2-0008", tool="performance", operation="load", complexity="single",
       user_input="1, 5, and 15 minute load numbers for the etcd node please",
       args={"operation": "load"},
       answer="0.60 0.55 0.50 1/190 9010"),
    V2(id="performance-load-v2-0009", tool="performance", operation="load", complexity="single",
       user_input="Ticket 3345: check loadavg on the firewall appliance host before adding another nftables ruleset.",
       args={"operation": "load"},
       answer="0.15 0.18 0.20 1/150 6600"),
]

from finetune.scenarios_v2 import check_module; check_module("performance", SCENARIOS_V2)
