"""finetune/scenarios_v2/podman.py — corpus v2 scenarios for 'podman'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # ---- ps (read, 11) ----
    V2(id="podman-ps-v2-0001", tool="podman", operation="ps", complexity="single",
       user_input="What's actually running on this box right now?",
       args={"operation": "ps"},
       answer="CONTAINER ID  IMAGE                                    STATUS       NAMES\na1c4e9f0b2d3  registry.access.redhat.com/ubi9:latest  Up 3 hours   web-app-1\n7f2b1d8e5c90  docker.io/library/redis:7.2              Up 3 hours   redis-cache"),
    V2(id="podman-ps-v2-0002", tool="podman", operation="ps", complexity="single",
       user_input="Give me a full listing, stopped ones included.",
       args={"operation": "ps", "all": True},
       answer="CONTAINER ID  IMAGE                          STATUS                     NAMES\na1c4e9f0b2d3  ubi9:latest                    Up 3 hours                 web-app-1\n5d3a2f1e0c88  postgres:16                    Exited (1) 20 minutes ago  billing-worker"),
    V2(id="podman-ps-v2-0003", tool="podman", operation="ps", complexity="diagnostic",
       user_input="Billing customers say the app is unreachable on app-node2 — is the front end even up?",
       args={"operation": "ps"},
       answer="No entry for web-front in the current list.\nLast known state: Exited (137) 8 minutes ago."),
    V2(id="podman-ps-v2-0004", tool="podman", operation="ps", complexity="multi",
       user_input="Check what's running, then pull the logs off whichever one is using the most CPU.",
       args={"operation": "ps"},
       answer="CONTAINER ID  IMAGE                    STATUS       NAMES\n9b1c0d2e4f56  quay.io/myorg/api:2.4.1  Up 12 hours  billing-worker\ncpu%% (top by usage): billing-worker 87%%"),
    V2(id="podman-ps-v2-0005", tool="podman", operation="ps", complexity="single",
       user_input="ps -a real quick, need the full picture before I file the incident ticket.",
       args={"operation": "ps", "all": True},
       answer="3 entries: 2 Up, 1 Exited (139).\ndb-prod-3    Up 6 days\nredis-cache  Up 6 days\nold-worker   Exited (139) 2 days ago"),
    V2(id="podman-ps-v2-0006", tool="podman", operation="ps", complexity="single",
       user_input="Show me containers, running only, no need for the dead ones.",
       args={"operation": "ps"},
       answer="CONTAINER ID  IMAGE                       STATUS      NAMES\ne4f5a6b7c8d9  docker.io/library/nginx:1.25 Up 2 hours  web-front"),
    V2(id="podman-ps-v2-0007", tool="podman", operation="ps", complexity="diagnostic",
       user_input="Ops handed off a ticket saying db-prod-3 keeps bouncing — first thing I want to know is whether anything with that name is up at all.",
       args={"operation": "ps", "all": True},
       answer="db-prod-3   Exited (2) 4 minutes ago\nRestart count in the last hour: 5"),
    V2(id="podman-ps-v2-0008", tool="podman", operation="ps", complexity="single",
       user_input="Quick status check on app-node2 containers.",
       args={"operation": "ps"},
       answer="CONTAINER ID  IMAGE                     STATUS       NAMES\nb2c3d4e5f6a7  quay.io/myorg/api:2.4.1  Up 45 minutes billing-worker"),
    V2(id="podman-ps-v2-0009", tool="podman", operation="ps", complexity="multi",
       user_input="List everything including stopped, then stop whatever's still marked Up for the maintenance window.",
       args={"operation": "ps", "all": True},
       answer="4 entries listed.\nUp: web-app-1, redis-cache\nExited: billing-worker, old-worker"),
    V2(id="podman-ps-v2-0010", tool="podman", operation="ps", complexity="diagnostic",
       user_input="Something feels off with the deployment on db-prod-3 — can you tell me what containers currently exist there, stopped or not?",
       args={"operation": "ps", "all": True},
       answer="1 entry.\ndb-prod-3-init   Exited (0) 1 hour ago"),
    V2(id="podman-ps-v2-0011", tool="podman", operation="ps", complexity="single",
       user_input="Any containers up on redis-cache's host right now?",
       args={"operation": "ps"},
       answer="CONTAINER ID  IMAGE                     STATUS       NAMES\nf1e2d3c4b5a6  docker.io/library/redis:7.2 Up 9 hours  redis-cache"),

    # ---- images (read, 12) ----
    V2(id="podman-images-v2-0012", tool="podman", operation="images", complexity="single",
       user_input="What images do we have sitting on app-node2?",
       args={"operation": "images"},
       answer="REPOSITORY                                TAG      IMAGE ID      SIZE\nregistry.access.redhat.com/ubi9          latest   3f4e5d6c7b8a  225MB\nquay.io/myorg/api                        2.4.1    9a8b7c6d5e4f  412MB"),
    V2(id="podman-images-v2-0013", tool="podman", operation="images", complexity="single",
       user_input="Local image inventory, please.",
       args={"operation": "images"},
       answer="4 images, 1.1GB total.\ndocker.io/library/postgres:16   612MB\ndocker.io/library/redis:7.2     117MB"),
    V2(id="podman-images-v2-0014", tool="podman", operation="images", complexity="multi",
       user_input="Before we buildah-bud a fresh copy, check what's already local so we don't duplicate storage.",
       args={"operation": "images"},
       answer="REPOSITORY                        TAG      SIZE\nquay.io/myorg/api                2.4.1    412MB\nregistry.access.redhat.com/ubi9  latest   225MB"),
    V2(id="podman-images-v2-0015", tool="podman", operation="images", complexity="diagnostic",
       user_input="We're low on disk on db-prod-3 — what's taking up the space image-wise?",
       args={"operation": "images"},
       answer="REPOSITORY                       TAG      SIZE\ndocker.io/library/postgres       16       612MB\nquay.io/myorg/api                1.9.0    398MB   <dangling>"),
    V2(id="podman-images-v2-0016", tool="podman", operation="images", complexity="single",
       user_input="List local images.",
       args={"operation": "images"},
       answer="REPOSITORY                        TAG      SIZE\ndocker.io/library/nginx          1.25     187MB"),
    V2(id="podman-images-v2-0017", tool="podman", operation="images", complexity="single",
       user_input="Can you tell me every tagged image currently cached here, not what's in the remote registry?",
       args={"operation": "images"},
       answer="3 images cached locally, none pulled in the last 24 hours."),
    V2(id="podman-images-v2-0018", tool="podman", operation="images", complexity="diagnostic",
       user_input="A teammate swears they never pulled ubi9 on this host — can you confirm whether it's actually here?",
       args={"operation": "images"},
       answer="registry.access.redhat.com/ubi9:latest   present, IMAGE ID 3f4e5d6c7b8a, pulled 6 days ago."),
    V2(id="podman-images-v2-0019", tool="podman", operation="images", complexity="multi",
       user_input="Check the local images and then tag whichever ubi9 build is newest as our base for the Containerfile.",
       args={"operation": "images"},
       answer="registry.access.redhat.com/ubi9:latest   IMAGE ID 3f4e5d6c7b8a   newest (6 days old)"),
    V2(id="podman-images-v2-0020", tool="podman", operation="images", complexity="single",
       user_input="images",
       args={"operation": "images"},
       answer="REPOSITORY   TAG      SIZE\npostgres     16       612MB\nredis        7.2      117MB"),
    V2(id="podman-images-v2-0021", tool="podman", operation="images", complexity="single",
       user_input="What's the size footprint of everything downloaded on this host so far?",
       args={"operation": "images"},
       answer="Total local storage: 1.34GB across 5 images."),
    V2(id="podman-images-v2-0022", tool="podman", operation="images", complexity="diagnostic",
       user_input="The CI job failed saying an image reference couldn't be resolved — is quay.io/myorg/api:2.4.1 even here yet?",
       args={"operation": "images"},
       answer="No match for quay.io/myorg/api:2.4.1 in local storage.\nClosest match: quay.io/myorg/api:2.3.0"),
    V2(id="podman-images-v2-0023", tool="podman", operation="images", complexity="single",
       user_input="Pull up the image list for db-prod-3, want to see what versions are cached.",
       args={"operation": "images"},
       answer="REPOSITORY                  TAG   SIZE\ndocker.io/library/postgres  16    612MB\ndocker.io/library/postgres  15    598MB"),

    # ---- inspect (read, 12) ----
    V2(id="podman-inspect-v2-0024", tool="podman", operation="inspect", complexity="single",
       user_input="Give me the full config dump for web-app-1.",
       args={"operation": "inspect", "target": "web-app-1"},
       answer="Id: a1c4e9f0b2d3\nState: running, Pid 48213\nNetworkMode: bridge, IPAddress: 10.88.0.14\nMounts: /data -> /var/lib/containers/storage/volumes/webdata"),
    V2(id="podman-inspect-v2-0025", tool="podman", operation="inspect", complexity="diagnostic",
       user_input="billing-worker keeps restarting on db-prod-3 — what does its exit status look like?",
       args={"operation": "inspect", "target": "billing-worker"},
       answer="State: exited\nExitCode: 1\nFinishedAt: 2026-09-13T02:14:07Z\nOOMKilled: false"),
    V2(id="podman-inspect-v2-0026", tool="podman", operation="inspect", complexity="single",
       user_input="Can you show the metadata on the ubi9 image itself, not a container?",
       args={"operation": "inspect", "target": "registry.access.redhat.com/ubi9:latest"},
       answer="Id: 3f4e5d6c7b8a\nCreated: 2026-08-30T11:02:00Z\nSize: 225875392\nArchitecture: amd64"),
    V2(id="podman-inspect-v2-0027", tool="podman", operation="inspect", complexity="multi",
       user_input="Inspect redis-cache to get its IP, then I'll add a firewall rule for that address.",
       args={"operation": "inspect", "target": "redis-cache"},
       answer="Id: 7f2b1d8e5c90\nIPAddress: 10.88.0.9\nPorts: 6379/tcp -> 0.0.0.0:6379"),
    V2(id="podman-inspect-v2-0028", tool="podman", operation="inspect", complexity="single",
       user_input="What mounts does db-prod-3's postgres container have set up?",
       args={"operation": "inspect", "target": "db-prod-3"},
       answer="Mounts:\n  /var/lib/postgresql/data -> /srv/pg-data (rw)\n  /etc/postgresql/postgresql.conf -> /srv/pg-conf/postgresql.conf (ro)"),
    V2(id="podman-inspect-v2-0029", tool="podman", operation="inspect", complexity="diagnostic",
       user_input="Networking seems broken between api and the cache — can you pull the connection details for billing-worker to compare?",
       args={"operation": "inspect", "target": "billing-worker"},
       answer="NetworkMode: bridge\nIPAddress: 10.88.0.22\nDNS: 10.88.0.1"),
    V2(id="podman-inspect-v2-0030", tool="podman", operation="inspect", complexity="single",
       user_input="inspect web-front",
       args={"operation": "inspect", "target": "web-front"},
       answer="Id: e4f5a6b7c8d9\nState: running, Pid 51002\nRestartCount: 0\nHealthcheck: none configured"),
    V2(id="podman-inspect-v2-0031", tool="podman", operation="inspect", complexity="single",
       user_input="I need to see the environment variables baked into old-worker.",
       args={"operation": "inspect", "target": "old-worker"},
       answer="Env:\n  APP_ENV=production\n  LOG_LEVEL=info\n  DB_HOST=db-prod-3"),
    V2(id="podman-inspect-v2-0032", tool="podman", operation="inspect", complexity="diagnostic",
       user_input="A user filed a ticket claiming redis-cache lost its data volume on restart — what's actually mounted there?",
       args={"operation": "inspect", "target": "redis-cache"},
       answer="Mounts:\n  /data -> /srv/redis-vol (rw, persisted)\nNo anonymous volumes found."),
    V2(id="podman-inspect-v2-0033", tool="podman", operation="inspect", complexity="multi",
       user_input="Inspect web-app-1 for its port mapping, then update the load balancer entry to match.",
       args={"operation": "inspect", "target": "web-app-1"},
       answer="Ports: 8080/tcp -> 0.0.0.0:8080\nIPAddress: 10.88.0.14"),
    V2(id="podman-inspect-v2-0034", tool="podman", operation="inspect", complexity="single",
       user_input="Details on the postgres:16 image, like its layers and entrypoint.",
       args={"operation": "inspect", "target": "docker.io/library/postgres:16"},
       answer="Entrypoint: [\"docker-entrypoint.sh\"]\nCmd: [\"postgres\"]\nLayers: 14"),
    V2(id="podman-inspect-v2-0035", tool="podman", operation="inspect", complexity="single",
       user_input="What labels got set on app-node2's web-front container?",
       args={"operation": "inspect", "target": "web-front"},
       answer="Labels:\n  maintainer=platform-team\n  version=1.25\n  tier=frontend"),

    # ---- logs (read, 11) ----
    V2(id="podman-logs-v2-0036", tool="podman", operation="logs", complexity="single",
       user_input="Show me the last 50 lines out of billing-worker.",
       args={"operation": "logs", "container": "billing-worker"},
       answer="2026-09-13T02:13:55Z INFO job queue drained\n2026-09-13T02:14:02Z ERROR connection to db-prod-3:5432 refused\n2026-09-13T02:14:07Z FATAL worker exiting"),
    V2(id="podman-logs-v2-0037", tool="podman", operation="logs", complexity="diagnostic",
       user_input="Customers on the checkout page are seeing timeouts — anything in web-app-1's recent output that explains it?",
       args={"operation": "logs", "container": "web-app-1"},
       answer="2026-09-13T02:10:11Z WARN upstream billing-worker timeout after 30000ms\n2026-09-13T02:10:12Z ERROR 502 returned to client 10.0.4.9"),
    V2(id="podman-logs-v2-0038", tool="podman", operation="logs", complexity="single",
       user_input="Pull the last 200 lines from redis-cache, I want to check for eviction warnings.",
       args={"operation": "logs", "container": "redis-cache", "lines": 200},
       answer="200 lines returned.\nNo eviction warnings found.\nLast line: 2026-09-13T02:15:00Z * 10 changes in 300 seconds, saving RDB"),
    V2(id="podman-logs-v2-0039", tool="podman", operation="logs", complexity="multi",
       user_input="Grab the log tail from db-prod-3, then attach it to the incident ticket if you see a crash.",
       args={"operation": "logs", "container": "db-prod-3"},
       answer="2026-09-13T02:14:01Z FATAL: could not write to file \"pg_wal/000000010000000000000042\"\n2026-09-13T02:14:01Z LOG: database system is shut down"),
    V2(id="podman-logs-v2-0040", tool="podman", operation="logs", complexity="single",
       user_input="logs from old-worker, last 500 max should cover it.",
       args={"operation": "logs", "container": "old-worker", "lines": 500},
       answer="500 lines returned.\nEarliest: 2026-09-12T22:00:00Z, Latest: 2026-09-13T02:00:00Z"),
    V2(id="podman-logs-v2-0041", tool="podman", operation="logs", complexity="diagnostic",
       user_input="Something looks stuck with the api container on app-node2 — any ERROR lines in its recent history?",
       args={"operation": "logs", "container": "api"},
       answer="2026-09-13T01:58:40Z ERROR failed to acquire lock on job 4821\n2026-09-13T01:59:00Z ERROR retry limit exceeded for job 4821"),
    V2(id="podman-logs-v2-0042", tool="podman", operation="logs", complexity="single",
       user_input="What's web-front been printing lately?",
       args={"operation": "logs", "container": "web-front"},
       answer="2026-09-13T02:12:00Z 10.0.4.9 - GET /healthz 200\n2026-09-13T02:12:05Z 10.0.4.9 - GET / 200"),
    V2(id="podman-logs-v2-0043", tool="podman", operation="logs", complexity="single",
       user_input="Can I get 100 lines of output from billing-worker instead of the default?",
       args={"operation": "logs", "container": "billing-worker", "lines": 100},
       answer="100 lines returned.\nNo FATAL entries in this window."),
    V2(id="podman-logs-v2-0044", tool="podman", operation="logs", complexity="diagnostic",
       user_input="Support says the cache seems to be dropping keys unexpectedly — does redis-cache's output mention anything about maxmemory?",
       args={"operation": "logs", "container": "redis-cache"},
       answer="2026-09-13T01:40:12Z # WARNING overcommit_memory is set to 0\nNo maxmemory eviction entries found in this window."),
    V2(id="podman-logs-v2-0045", tool="podman", operation="logs", complexity="multi",
       user_input="Check the logs on db-prod-3 for a disk-full message, then if you find one I'll go clear out old WAL segments.",
       args={"operation": "logs", "container": "db-prod-3"},
       answer="2026-09-13T02:14:01Z FATAL: could not write to file \"pg_wal/000000010000000000000042\": No space left on device"),
    V2(id="podman-logs-v2-0046", tool="podman", operation="logs", complexity="single",
       user_input="Just want a quick peek at recent output from web-app-1.",
       args={"operation": "logs", "container": "web-app-1"},
       answer="2026-09-13T02:15:20Z INFO listening on 0.0.0.0:8080\n2026-09-13T02:15:21Z INFO connected to cache at redis-cache:6379"),

    # ---- pull (write, 12) ----
    V2(id="podman-pull-v2-0047", tool="podman", operation="pull", complexity="single",
       user_input="Grab the latest ubi9 base image for us.",
       args={"operation": "pull", "image": "registry.access.redhat.com/ubi9:latest"},
       answer="Trying registry.access.redhat.com/ubi9:latest\nDigest: sha256:c1a2b3d4e5f6...\nStatus: image up to date"),
    V2(id="podman-pull-v2-0048", tool="podman", operation="pull", complexity="single",
       user_input="Fetch postgres:16 from Docker Hub.",
       args={"operation": "pull", "image": "docker.io/library/postgres:16"},
       answer="Copying blob 4a5b6c7d8e9f done\nDigest: sha256:9f8e7d6c5b4a...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0049", tool="podman", operation="pull", complexity="multi",
       user_input="Pull quay.io/myorg/api:2.4.1 and then start a container from it once it lands.",
       args={"operation": "pull", "image": "quay.io/myorg/api:2.4.1"},
       answer="Copying blob 1122aabb done\nDigest: sha256:112233aabbcc...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0050", tool="podman", operation="pull", complexity="diagnostic",
       user_input="Deploy on app-node2 is complaining the tag doesn't exist locally — can you go get quay.io/myorg/api:2.4.1?",
       args={"operation": "pull", "image": "quay.io/myorg/api:2.4.1"},
       answer="Trying quay.io/myorg/api:2.4.1\nDigest: sha256:112233aabbcc...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0051", tool="podman", operation="pull", complexity="single",
       user_input="We need redis 7.2 on this host too.",
       args={"operation": "pull", "image": "docker.io/library/redis:7.2"},
       answer="Copying blob 33ccdd44 done\nDigest: sha256:33ccdd4455ee...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0052", tool="podman", operation="pull", complexity="single",
       user_input="pull nginx:1.25",
       args={"operation": "pull", "image": "docker.io/library/nginx:1.25"},
       answer="Copying blob 55ee66ff done\nDigest: sha256:55ee66ffgg77...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0053", tool="podman", operation="pull", complexity="multi",
       user_input="Get the ubi9 image down, then I'll kick off a build from a Containerfile that uses it as the base.",
       args={"operation": "pull", "image": "registry.access.redhat.com/ubi9:latest"},
       answer="Trying registry.access.redhat.com/ubi9:latest\nDigest: sha256:c1a2b3d4e5f6...\nStatus: image up to date"),
    V2(id="podman-pull-v2-0054", tool="podman", operation="pull", complexity="single",
       user_input="Security wants us on postgres 15 instead of 16 for now, pull that version.",
       args={"operation": "pull", "image": "docker.io/library/postgres:15"},
       answer="Copying blob 77gg88hh done\nDigest: sha256:77gg88hhii99...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0055", tool="podman", operation="pull", complexity="diagnostic",
       user_input="The rollback plan needs api:2.3.0 back on db-prod-3 — is it worth pulling fresh or do we already have it?",
       args={"operation": "pull", "image": "quay.io/myorg/api:2.3.0"},
       answer="Trying quay.io/myorg/api:2.3.0\nDigest: sha256:998877665544...\nStatus: image up to date"),
    V2(id="podman-pull-v2-0056", tool="podman", operation="pull", complexity="single",
       user_input="Retrieve the ubi9 minimal variant, not the full one.",
       args={"operation": "pull", "image": "registry.access.redhat.com/ubi9/ubi-minimal:latest"},
       answer="Copying blob 99aa11bb done\nDigest: sha256:99aa11bbcc22...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0057", tool="podman", operation="pull", complexity="single",
       user_input="pull docker.io/library/nginx:1.24 too, we're keeping both versions around for now.",
       args={"operation": "pull", "image": "docker.io/library/nginx:1.24"},
       answer="Copying blob 44dd33cc done\nDigest: sha256:44dd33cc22bb...\nStatus: downloaded newer image"),
    V2(id="podman-pull-v2-0058", tool="podman", operation="pull", complexity="multi",
       user_input="Pull the latest tag for quay.io/myorg/api, then push it back out to the internal mirror once it's verified.",
       args={"operation": "pull", "image": "quay.io/myorg/api:latest"},
       answer="Copying blob aabbccdd done\nDigest: sha256:aabbccddeeff...\nStatus: downloaded newer image"),

    # ---- run (write, 12) ----
    V2(id="podman-run-v2-0059", tool="podman", operation="run", complexity="single",
       user_input="Start up a detached nginx container, call it web-front.",
       args={"operation": "run", "image": "docker.io/library/nginx:1.25", "name": "web-front", "detach": True},
       answer="e4f5a6b7c8d9\nStarted, listening on port 80 inside the container."),
    V2(id="podman-run-v2-0060", tool="podman", operation="run", complexity="single",
       user_input="Run a redis container in the background for the cache layer.",
       args={"operation": "run", "image": "docker.io/library/redis:7.2", "name": "redis-cache", "detach": True},
       answer="7f2b1d8e5c90\nStarted, listening on port 6379 inside the container."),
    V2(id="podman-run-v2-0061", tool="podman", operation="run", complexity="multi",
       user_input="Run a postgres container named db-init, then I need to check it actually stays up.",
       args={"operation": "run", "image": "docker.io/library/postgres:16", "name": "db-init", "detach": True},
       answer="5d3a2f1e0c88\nStarted, initializing database cluster."),
    V2(id="podman-run-v2-0062", tool="podman", operation="run", complexity="diagnostic",
       user_input="old-worker died and won't restart cleanly — easiest fix is probably just to run a fresh one off the same image, right?",
       args={"operation": "run", "image": "quay.io/myorg/api:2.4.1", "name": "old-worker", "detach": True},
       answer="9b1c0d2e4f56\nStarted, replacing prior instance."),
    V2(id="podman-run-v2-0063", tool="podman", operation="run", complexity="single",
       user_input="Launch a ubi9 container for me, doesn't need a specific name.",
       args={"operation": "run", "image": "registry.access.redhat.com/ubi9:latest", "detach": True},
       answer="a1c4e9f0b2d3\nStarted in background."),
    V2(id="podman-run-v2-0064", tool="podman", operation="run", complexity="single",
       user_input="run quay.io/myorg/api:2.4.1 as billing-worker, foreground is fine actually.",
       args={"operation": "run", "image": "quay.io/myorg/api:2.4.1", "name": "billing-worker", "detach": False},
       answer="Attached, streaming output.\nContainer ID 9b1c0d2e4f56"),
    V2(id="podman-run-v2-0065", tool="podman", operation="run", complexity="multi",
       user_input="Run the new api:2.4.1 image on app-node2, then swap the load balancer over to it once it's healthy.",
       args={"operation": "run", "image": "quay.io/myorg/api:2.4.1", "name": "api-v2", "detach": True},
       answer="c8d9e0f1a2b3\nStarted, listening on port 8080 inside the container."),
    V2(id="podman-run-v2-0066", tool="podman", operation="run", complexity="single",
       user_input="Spin up postgres 16 as db-prod-3.",
       args={"operation": "run", "image": "docker.io/library/postgres:16", "name": "db-prod-3", "detach": True},
       answer="5d3a2f1e0c88\nStarted, database cluster ready to accept connections."),
    V2(id="podman-run-v2-0067", tool="podman", operation="run", complexity="diagnostic",
       user_input="The Containerfile build finished fine but nothing's actually up yet — should I just run the fix:1.1 image now to get it live?",
       args={"operation": "run", "image": "fix:1.1", "name": "web-app-1", "detach": True},
       answer="d4e5f6a7b8c9\nStarted, replacing prior tagged deployment."),
    V2(id="podman-run-v2-0068", tool="podman", operation="run", complexity="single",
       user_input="Get a redis-cache container going, detached, standard config.",
       args={"operation": "run", "image": "docker.io/library/redis:7.2", "name": "redis-cache", "detach": True},
       answer="7f2b1d8e5c90\nStarted, listening on port 6379 inside the container."),
    V2(id="podman-run-v2-0069", tool="podman", operation="run", complexity="single",
       user_input="Start nginx 1.24, name it web-front-canary.",
       args={"operation": "run", "image": "docker.io/library/nginx:1.24", "name": "web-front-canary", "detach": True},
       answer="f6a7b8c9d0e1\nStarted, listening on port 80 inside the container."),
    V2(id="podman-run-v2-0070", tool="podman", operation="run", complexity="multi",
       user_input="Run the ubi9 image detached as scratch-check, then I want to exec in and inspect the filesystem layout.",
       args={"operation": "run", "image": "registry.access.redhat.com/ubi9:latest", "name": "scratch-check", "detach": True},
       answer="b3c4d5e6f7a8\nStarted in background."),

    # ---- stop (write, 12) ----
    V2(id="podman-stop-v2-0071", tool="podman", operation="stop", complexity="single",
       user_input="Take web-front down.",
       args={"operation": "stop", "container": "web-front"},
       answer="web-front\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0072", tool="podman", operation="stop", complexity="single",
       user_input="Shut redis-cache down for the maintenance window.",
       args={"operation": "stop", "container": "redis-cache"},
       answer="redis-cache\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0073", tool="podman", operation="stop", complexity="diagnostic",
       user_input="billing-worker is pegging the CPU on app-node2 and it's not recovering on its own — can we just halt it?",
       args={"operation": "stop", "container": "billing-worker"},
       answer="billing-worker\nStopped, exit code 137 (was unresponsive to SIGTERM, force-killed)."),
    V2(id="podman-stop-v2-0074", tool="podman", operation="stop", complexity="multi",
       user_input="Stop old-worker, then remove it once it's confirmed down.",
       args={"operation": "stop", "container": "old-worker"},
       answer="old-worker\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0075", tool="podman", operation="stop", complexity="single",
       user_input="stop db-prod-3",
       args={"operation": "stop", "container": "db-prod-3"},
       answer="db-prod-3\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0076", tool="podman", operation="stop", complexity="single",
       user_input="Can you halt the api container? Change window opens in 5 minutes.",
       args={"operation": "stop", "container": "api"},
       answer="api\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0077", tool="podman", operation="stop", complexity="diagnostic",
       user_input="web-app-1 seems to be leaking connections to the database — as a stopgap should we just stop it until we patch?",
       args={"operation": "stop", "container": "web-app-1"},
       answer="web-app-1\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0078", tool="podman", operation="stop", complexity="single",
       user_input="Pull the plug on scratch-check, we're done with it for now.",
       args={"operation": "stop", "container": "scratch-check"},
       answer="scratch-check\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0079", tool="podman", operation="stop", complexity="single",
       user_input="Bring down web-front-canary, the canary test is over.",
       args={"operation": "stop", "container": "web-front-canary"},
       answer="web-front-canary\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0080", tool="podman", operation="stop", complexity="multi",
       user_input="Stop db-init and then run the production postgres container in its place.",
       args={"operation": "stop", "container": "db-init"},
       answer="db-init\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0081", tool="podman", operation="stop", complexity="diagnostic",
       user_input="Support flagged that api-v2 is throwing 500s nonstop — should we stop it and fail back to the old one?",
       args={"operation": "stop", "container": "api-v2"},
       answer="api-v2\nStopped, exit code 0."),
    V2(id="podman-stop-v2-0082", tool="podman", operation="stop", complexity="single",
       user_input="Halt billing-worker right now, it's stuck in a bad loop.",
       args={"operation": "stop", "container": "billing-worker"},
       answer="billing-worker\nStopped, exit code 137 (force-killed after timeout)."),

    # ---- exec (write, 12) ----
    V2(id="podman-exec-v2-0083", tool="podman", operation="exec", complexity="single",
       user_input="Inside web-app-1, run ls /app for me.",
       args={"operation": "exec", "container": "web-app-1", "command": "ls /app"},
       answer="app.py\nrequirements.txt\nstatic/\ntemplates/"),
    V2(id="podman-exec-v2-0084", tool="podman", operation="exec", complexity="single",
       user_input="Check the process list inside db-prod-3.",
       args={"operation": "exec", "container": "db-prod-3", "command": "ps aux"},
       answer="USER   PID  COMMAND\npostgres  1  postgres -D /var/lib/postgresql/data\npostgres 42  postgres: checkpointer"),
    V2(id="podman-exec-v2-0085", tool="podman", operation="exec", complexity="diagnostic",
       user_input="The api container can't seem to reach db-prod-3 — can you exec in and try curling the database port?",
       args={"operation": "exec", "container": "api", "command": "curl -sv db-prod-3:5432"},
       answer="* Connection refused\ncurl: (7) Failed to connect to db-prod-3 port 5432"),
    V2(id="podman-exec-v2-0086", tool="podman", operation="exec", complexity="multi",
       user_input="Exec into billing-worker and run the manual queue flush, then tail its logs to confirm it worked.",
       args={"operation": "exec", "container": "billing-worker", "command": "python manage.py flush_queue"},
       answer="Flushed 42 pending jobs.\nExit code 0."),
    V2(id="podman-exec-v2-0087", tool="podman", operation="exec", complexity="single",
       user_input="Cat out /etc/resolv.conf from inside redis-cache.",
       args={"operation": "exec", "container": "redis-cache", "command": "cat /etc/resolv.conf"},
       answer="nameserver 10.88.0.1\nsearch dns.podman"),
    V2(id="podman-exec-v2-0088", tool="podman", operation="exec", complexity="single",
       user_input="Run df -h inside web-front to see how much disk it has.",
       args={"operation": "exec", "container": "web-front", "command": "df -h"},
       answer="Filesystem   Size Used Avail Use%%\noverlay      10G  2.1G  7.9G  21%%"),
    V2(id="podman-exec-v2-0089", tool="podman", operation="exec", complexity="diagnostic",
       user_input="Someone thinks old-worker never got the right environment variables set — can you check with printenv inside it?",
       args={"operation": "exec", "container": "old-worker", "command": "printenv"},
       answer="APP_ENV=production\nLOG_LEVEL=info\nDB_HOST=db-prod-3"),
    V2(id="podman-exec-v2-0090", tool="podman", operation="exec", complexity="single",
       user_input="Run a manual psql check against api-v2's app database from inside it.",
       args={"operation": "exec", "container": "api-v2", "command": "psql -U appuser -d appdb -c 'select 1;'"},
       answer=" ?column?\n----------\n        1\n(1 row)"),
    V2(id="podman-exec-v2-0091", tool="podman", operation="exec", complexity="single",
       user_input="exec whoami inside scratch-check",
       args={"operation": "exec", "container": "scratch-check", "command": "whoami"},
       answer="default"),
    V2(id="podman-exec-v2-0092", tool="podman", operation="exec", complexity="multi",
       user_input="Get into billing-worker and check disk usage, then decide if we need to grow the volume.",
       args={"operation": "exec", "container": "billing-worker", "command": "du -sh /var/lib/app"},
       answer="6.8G\t/var/lib/app"),
    V2(id="podman-exec-v2-0093", tool="podman", operation="exec", complexity="diagnostic",
       user_input="web-app-1's healthcheck is failing but nothing obvious is in the logs — mind checking if the process is even bound to the port with netstat?",
       args={"operation": "exec", "container": "web-app-1", "command": "netstat -tlnp"},
       answer="Proto  Local Address     PID/Program\ntcp    0.0.0.0:8080      (none)\nNo listener found on 8080."),
    V2(id="podman-exec-v2-0094", tool="podman", operation="exec", complexity="single",
       user_input="Kick off a manual VACUUM inside db-prod-3.",
       args={"operation": "exec", "container": "db-prod-3", "command": "psql -U postgres -c 'VACUUM;'"},
       answer="VACUUM\nExit code 0."),

    # ---- build (write, 12) ----
    V2(id="podman-build-v2-0095", tool="podman", operation="build", complexity="single",
       user_input="Build an image tagged myapp:1.0 from the current directory context.",
       args={"operation": "build", "context": ".", "tag": "myapp:1.0"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9:latest\n...\nCOMMIT myapp:1.0\nabf1c2d3e4f5"),
    V2(id="podman-build-v2-0096", tool="podman", operation="build", complexity="single",
       user_input="Kick off a build from /opt/myservice, don't need a tag yet.",
       args={"operation": "build", "context": "/opt/myservice"},
       answer="STEP 1/4: FROM docker.io/library/python:3.12-slim\n...\nCOMMIT\n1a2b3c4d5e6f"),
    V2(id="podman-build-v2-0097", tool="podman", operation="build", complexity="multi",
       user_input="Build off ./app tagged fix:1.1, then push that up once it's done.",
       args={"operation": "build", "context": "./app", "tag": "fix:1.1"},
       answer="STEP 1/5: FROM registry.access.redhat.com/ubi9:latest\n...\nCOMMIT fix:1.1\ne2f3a4b5c6d7"),
    V2(id="podman-build-v2-0098", tool="podman", operation="build", complexity="diagnostic",
       user_input="The last deploy shipped with a stale Containerfile — do we need to rebuild the release:2.0 image from scratch off /srv/build/release?",
       args={"operation": "build", "context": "/srv/build/release", "tag": "release:2.0"},
       answer="STEP 1/7: FROM quay.io/myorg/api:2.3.0\n...\nCOMMIT release:2.0\nd8e9f0a1b2c3"),
    V2(id="podman-build-v2-0099", tool="podman", operation="build", complexity="single",
       user_input="build the context at ~/projects/billing-svc, tag it billing-svc:latest",
       args={"operation": "build", "context": "~/projects/billing-svc", "tag": "billing-svc:latest"},
       answer="STEP 1/8: FROM docker.io/library/node:20-alpine\n...\nCOMMIT billing-svc:latest\nf4a5b6c7d8e9"),
    V2(id="podman-build-v2-0100", tool="podman", operation="build", complexity="single",
       user_input="Compile the image at /home/aaron/src/api using its Containerfile.",
       args={"operation": "build", "context": "/home/aaron/src/api"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9:latest\n...\nCOMMIT\nc7d8e9f0a1b2"),
    V2(id="podman-build-v2-0101", tool="podman", operation="build", complexity="multi",
       user_input="Build the api image from /opt/myservice tagged api:2.5.0, then stop the old api-v2 container before rolling it out.",
       args={"operation": "build", "context": "/opt/myservice", "tag": "api:2.5.0"},
       answer="STEP 1/6: FROM quay.io/myorg/api:2.4.1\n...\nCOMMIT api:2.5.0\na9b8c7d6e5f4"),
    V2(id="podman-build-v2-0102", tool="podman", operation="build", complexity="single",
       user_input="Run the build for the ./frontend directory, tag frontend:dev.",
       args={"operation": "build", "context": "./frontend", "tag": "frontend:dev"},
       answer="STEP 1/9: FROM docker.io/library/node:20-alpine\n...\nCOMMIT frontend:dev\nb1c2d3e4f5a6"),
    V2(id="podman-build-v2-0103", tool="podman", operation="build", complexity="diagnostic",
       user_input="Buildah on the CI runner keeps timing out on this project — worth just trying a local build of ./service to see if it even compiles?",
       args={"operation": "build", "context": "./service"},
       answer="STEP 1/5: FROM registry.access.redhat.com/ubi9:latest\n...\nCOMMIT\nd3e4f5a6b7c8"),
    V2(id="podman-build-v2-0104", tool="podman", operation="build", complexity="single",
       user_input="Build myservice:canary from /srv/canary-src.",
       args={"operation": "build", "context": "/srv/canary-src", "tag": "myservice:canary"},
       answer="STEP 1/4: FROM docker.io/library/python:3.12-slim\n...\nCOMMIT myservice:canary\ne5f6a7b8c9d0"),
    V2(id="podman-build-v2-0105", tool="podman", operation="build", complexity="single",
       user_input="Take the Containerfile in /opt/nightly-build and build it, tag nightly:2026-09-13.",
       args={"operation": "build", "context": "/opt/nightly-build", "tag": "nightly:2026-09-13"},
       answer="STEP 1/6: FROM registry.access.redhat.com/ubi9:latest\n...\nCOMMIT nightly:2026-09-13\nf7a8b9c0d1e2"),
    V2(id="podman-build-v2-0106", tool="podman", operation="build", complexity="multi",
       user_input="Build the image from ./patch-src tagged patch:1.0.1, then remove the old patch:1.0.0 image once it's confirmed working.",
       args={"operation": "build", "context": "./patch-src", "tag": "patch:1.0.1"},
       answer="STEP 1/5: FROM quay.io/myorg/api:2.4.1\n...\nCOMMIT patch:1.0.1\na1b2c3d4e5f6"),

    # ---- push (write, 13) ----
    V2(id="podman-push-v2-0107", tool="podman", operation="push", complexity="single",
       user_input="Push myapp:1.0 up to the company registry.",
       args={"operation": "push", "image": "myapp:1.0"},
       answer="Copying blob abf1c2d3e4f5 done\nDigest: sha256:aabbccddeeff...\nPush complete"),
    V2(id="podman-push-v2-0108", tool="podman", operation="push", complexity="multi",
       user_input="Build release:2.0 and push it to the registry once it's ready.",
       args={"operation": "push", "image": "release:2.0"},
       answer="Copying blob d8e9f0a1b2c3 done\nDigest: sha256:112233445566...\nPush complete"),
    V2(id="podman-push-v2-0109", tool="podman", operation="push", complexity="diagnostic",
       user_input="The deployment pipeline failed saying the tag wasn't found upstream — did we ever actually push quay.io/myorg/api:2.4.1?",
       args={"operation": "push", "image": "quay.io/myorg/api:2.4.1"},
       answer="Copying blob 9a8b7c6d5e4f done\nDigest: sha256:998877665544...\nPush complete"),
    V2(id="podman-push-v2-0110", tool="podman", operation="push", complexity="single",
       user_input="push fix:1.1",
       args={"operation": "push", "image": "fix:1.1"},
       answer="Copying blob e2f3a4b5c6d7 done\nDigest: sha256:665544332211...\nPush complete"),
    V2(id="podman-push-v2-0111", tool="podman", operation="push", complexity="single",
       user_input="Send billing-svc:latest out to the registry.",
       args={"operation": "push", "image": "billing-svc:latest"},
       answer="Copying blob f4a5b6c7d8e9 done\nDigest: sha256:334455667788...\nPush complete"),
    V2(id="podman-push-v2-0112", tool="podman", operation="push", complexity="multi",
       user_input="Push frontend:dev to the registry, then trigger the staging deploy hook.",
       args={"operation": "push", "image": "frontend:dev"},
       answer="Copying blob b1c2d3e4f5a6 done\nDigest: sha256:778899aabbcc...\nPush complete"),
    V2(id="podman-push-v2-0113", tool="podman", operation="push", complexity="single",
       user_input="Get api:2.5.0 uploaded to the registry, ops is waiting on it.",
       args={"operation": "push", "image": "api:2.5.0"},
       answer="Copying blob a9b8c7d6e5f4 done\nDigest: sha256:aabb99887766...\nPush complete"),
    V2(id="podman-push-v2-0114", tool="podman", operation="push", complexity="single",
       user_input="Push nightly:2026-09-13 up.",
       args={"operation": "push", "image": "nightly:2026-09-13"},
       answer="Copying blob f7a8b9c0d1e2 done\nDigest: sha256:ccddeeff0011...\nPush complete"),
    V2(id="podman-push-v2-0115", tool="podman", operation="push", complexity="diagnostic",
       user_input="Someone reported quay.io/myorg/api:latest looks stale on the mirror — should we push a fresh copy up right now?",
       args={"operation": "push", "image": "quay.io/myorg/api:latest"},
       answer="Copying blob aabbccdd done\nDigest: sha256:aabbccddeeff...\nPush complete"),
    V2(id="podman-push-v2-0116", tool="podman", operation="push", complexity="single",
       user_input="Push myservice:canary out for the canary rollout.",
       args={"operation": "push", "image": "myservice:canary"},
       answer="Copying blob e5f6a7b8c9d0 done\nDigest: sha256:0011223344ff...\nPush complete"),
    V2(id="podman-push-v2-0117", tool="podman", operation="push", complexity="single",
       user_input="Ship patch:1.0.1 to the registry.",
       args={"operation": "push", "image": "patch:1.0.1"},
       answer="Copying blob a1b2c3d4e5f6 done\nDigest: sha256:1122334455ff...\nPush complete"),
    V2(id="podman-push-v2-0118", tool="podman", operation="push", complexity="multi",
       user_input="Push myapp:1.0 up, and once that's confirmed, remove the old myapp:0.9 tag locally.",
       args={"operation": "push", "image": "myapp:1.0"},
       answer="Copying blob abf1c2d3e4f5 done\nDigest: sha256:aabbccddeeff...\nPush complete"),
    V2(id="podman-push-v2-0119", tool="podman", operation="push", complexity="diagnostic",
       user_input="The rollback runbook says the registry should have release:2.0 by now — is that actually true, or does it need pushing?",
       args={"operation": "push", "image": "release:2.0"},
       answer="Copying blob d8e9f0a1b2c3 done\nDigest: sha256:112233445566...\nPush complete"),

    # ---- rm (destructive, 12) ----
    V2(id="podman-rm-v2-0120", tool="podman", operation="rm", complexity="single",
       user_input="Force remove old-worker, it's dead weight now.",
       args={"operation": "rm", "container": "old-worker"},
       answer="old-worker\nRemoved."),
    V2(id="podman-rm-v2-0121", tool="podman", operation="rm", complexity="single",
       user_input="Delete the crashed billing-worker container so I can start clean.",
       args={"operation": "rm", "container": "billing-worker"},
       answer="billing-worker\nRemoved."),
    V2(id="podman-rm-v2-0122", tool="podman", operation="rm", complexity="multi",
       user_input="Stop web-front and then remove it entirely, we're replacing it with the canary.",
       args={"operation": "rm", "container": "web-front"},
       answer="web-front\nRemoved."),
    V2(id="podman-rm-v2-0123", tool="podman", operation="rm", complexity="diagnostic",
       user_input="db-init won't go away and keeps clogging the container list — is it safe to force-remove it?",
       args={"operation": "rm", "container": "db-init"},
       answer="db-init\nRemoved (forced, was in Created state)."),
    V2(id="podman-rm-v2-0124", tool="podman", operation="rm", complexity="single",
       user_input="rm scratch-check",
       args={"operation": "rm", "container": "scratch-check"},
       answer="scratch-check\nRemoved."),
    V2(id="podman-rm-v2-0125", tool="podman", operation="rm", complexity="single",
       user_input="Clear out the exited api container, we relaunched it as api-v2 already.",
       args={"operation": "rm", "container": "api"},
       answer="api\nRemoved."),
    V2(id="podman-rm-v2-0126", tool="podman", operation="rm", complexity="diagnostic",
       user_input="web-front-canary is stuck in a bad state and won't stop cleanly — can we just force it out?",
       args={"operation": "rm", "container": "web-front-canary"},
       answer="web-front-canary\nRemoved (forced)."),
    V2(id="podman-rm-v2-0127", tool="podman", operation="rm", complexity="single",
       user_input="Get rid of the redis-cache container, we're moving that workload elsewhere.",
       args={"operation": "rm", "container": "redis-cache"},
       answer="redis-cache\nRemoved."),
    V2(id="podman-rm-v2-0128", tool="podman", operation="rm", complexity="multi",
       user_input="Remove billing-worker, then run a fresh copy from the latest image tag.",
       args={"operation": "rm", "container": "billing-worker"},
       answer="billing-worker\nRemoved."),
    V2(id="podman-rm-v2-0129", tool="podman", operation="rm", complexity="single",
       user_input="Delete db-prod-3-init, that job finished a while ago.",
       args={"operation": "rm", "container": "db-prod-3-init"},
       answer="db-prod-3-init\nRemoved."),
    V2(id="podman-rm-v2-0130", tool="podman", operation="rm", complexity="diagnostic",
       user_input="Cleanup script left a stray container named old-worker-2 on app-node2 — can we confirm it's gone by removing it?",
       args={"operation": "rm", "container": "old-worker-2"},
       answer="old-worker-2\nRemoved."),
    V2(id="podman-rm-v2-0131", tool="podman", operation="rm", complexity="single",
       user_input="Remove the container named db-init, it was a one-off setup job.",
       args={"operation": "rm", "container": "db-init"},
       answer="db-init\nRemoved."),

    # ---- rmi (destructive, 12) ----
    V2(id="podman-rmi-v2-0132", tool="podman", operation="rmi", complexity="single",
       user_input="Delete the old nginx:1.24 image, we're standardizing on 1.25.",
       args={"operation": "rmi", "image": "docker.io/library/nginx:1.24"},
       answer="Untagged: docker.io/library/nginx:1.24\nDeleted: sha256:44dd33cc22bb..."),
    V2(id="podman-rmi-v2-0133", tool="podman", operation="rmi", complexity="single",
       user_input="Get rid of myapp:0.9, everyone's on 1.0 now.",
       args={"operation": "rmi", "image": "myapp:0.9"},
       answer="Untagged: myapp:0.9\nDeleted: sha256:7788990011aa..."),
    V2(id="podman-rmi-v2-0134", tool="podman", operation="rmi", complexity="diagnostic",
       user_input="Disk space is tight on db-prod-3 and postgres:15 looks unused — safe to clear it out?",
       args={"operation": "rmi", "image": "docker.io/library/postgres:15"},
       answer="Untagged: docker.io/library/postgres:15\nDeleted: sha256:77gg88hhii99..."),
    V2(id="podman-rmi-v2-0135", tool="podman", operation="rmi", complexity="multi",
       user_input="Push release:2.0, then remove the previous release:1.9 image locally to free space.",
       args={"operation": "rmi", "image": "release:1.9"},
       answer="Untagged: release:1.9\nDeleted: sha256:445566778899..."),
    V2(id="podman-rmi-v2-0136", tool="podman", operation="rmi", complexity="single",
       user_input="rmi test:latest",
       args={"operation": "rmi", "image": "test:latest"},
       answer="Untagged: test:latest\nDeleted: sha256:99aa88bb77cc..."),
    V2(id="podman-rmi-v2-0137", tool="podman", operation="rmi", complexity="single",
       user_input="Take api:2.3.0 off local storage, we're fully on 2.4.1 now.",
       args={"operation": "rmi", "image": "quay.io/myorg/api:2.3.0"},
       answer="Untagged: quay.io/myorg/api:2.3.0\nDeleted: sha256:998877665544..."),
    V2(id="podman-rmi-v2-0138", tool="podman", operation="rmi", complexity="diagnostic",
       user_input="I count three tagged versions of the frontend image sitting around — is frontend:dev safe to delete since it's not what's running?",
       args={"operation": "rmi", "image": "frontend:dev"},
       answer="Untagged: frontend:dev\nDeleted: sha256:b1c2d3e4f5a6..."),
    V2(id="podman-rmi-v2-0139", tool="podman", operation="rmi", complexity="single",
       user_input="Remove the dangling ubi-minimal image, it's not tagged to anything we use.",
       args={"operation": "rmi", "image": "registry.access.redhat.com/ubi9/ubi-minimal:latest"},
       answer="Untagged: registry.access.redhat.com/ubi9/ubi-minimal:latest\nDeleted: sha256:99aa11bbcc22..."),
    V2(id="podman-rmi-v2-0140", tool="podman", operation="rmi", complexity="single",
       user_input="Clear out patch:1.0.0 now that 1.0.1 is confirmed working.",
       args={"operation": "rmi", "image": "patch:1.0.0"},
       answer="Untagged: patch:1.0.0\nDeleted: sha256:0011223344aa..."),
    V2(id="podman-rmi-v2-0141", tool="podman", operation="rmi", complexity="multi",
       user_input="List the images real quick in your head, then remove whichever nightly build is oldest — that's nightly:2026-09-10.",
       args={"operation": "rmi", "image": "nightly:2026-09-10"},
       answer="Untagged: nightly:2026-09-10\nDeleted: sha256:ffeeddccbbaa..."),
    V2(id="podman-rmi-v2-0142", tool="podman", operation="rmi", complexity="single",
       user_input="Drop the redis:7.1 image, we upgraded everything to 7.2.",
       args={"operation": "rmi", "image": "docker.io/library/redis:7.1"},
       answer="Untagged: docker.io/library/redis:7.1\nDeleted: sha256:1234567890ab..."),
    V2(id="podman-rmi-v2-0143", tool="podman", operation="rmi", complexity="diagnostic",
       user_input="Storage alerts fired again on app-node2 — myservice:canary hasn't been referenced by any running container, worth clearing?",
       args={"operation": "rmi", "image": "myservice:canary"},
       answer="Untagged: myservice:canary\nDeleted: sha256:e5f6a7b8c9d0..."),
]

from finetune.scenarios_v2 import check_module; check_module("podman", SCENARIOS_V2)
