"""finetune/scenarios_v2/postgresql.py — corpus v2 scenarios for 'postgresql'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="postgresql-status-v2-0001", tool="postgresql", operation="status",
       complexity="single",
       user_input="Check whether the postgresql service is active on this box.",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 2044, uptime 9d 3h"),
    V2(id="postgresql-status-v2-0002", tool="postgresql", operation="status",
       complexity="diagnostic",
       user_input="The reporting app is throwing 'connection refused' against the database tier. Is postgres even running?",
       args={"operation": "status"},
       answer="postgresql.service - inactive (dead)\nLast exit code: 1"),
    V2(id="postgresql-status-v2-0003", tool="postgresql", operation="status",
       complexity="single",
       user_input="is postgres.service alive right now",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 998, uptime 41d 0h"),
    V2(id="postgresql-status-v2-0004", tool="postgresql", operation="status",
       complexity="diagnostic",
       user_input="Users say the checkout page hangs forever on submit — can you rule postgres in or out before I look at the app code?",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 1122, uptime 2d 14h"),
    V2(id="postgresql-status-v2-0005", tool="postgresql", operation="status",
       complexity="single",
       user_input="Before we start the maintenance window, confirm the database service is healthy.",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 3311, uptime 60d 2h"),
    V2(id="postgresql-status-v2-0006", tool="postgresql", operation="status",
       complexity="diagnostic",
       user_input="postgres keeps flapping every few minutes according to the alert channel — what does its current state look like?",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 4102, uptime 0d 0h 4m\nRestarted 3 times in the last hour."),
    V2(id="postgresql-status-v2-0007", tool="postgresql", operation="status",
       complexity="single",
       user_input="show postgresql status and its current PID",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 2777, uptime 5d 8h"),
    V2(id="postgresql-status-v2-0008", tool="postgresql", operation="status",
       complexity="multi",
       user_input="Check if postgresql is up, and if so show me who's connected right now.",
       args={"operation": "status"},
       answer="postgresql.service - active (running)\nPID 1900, uptime 17d 1h"),

    V2(id="postgresql-query-v2-0001", tool="postgresql", operation="query",
       complexity="single",
       user_input="Run 'SELECT count(*) FROM orders' against the shop database.",
       args={"operation": "query", "sql": "SELECT count(*) FROM orders", "database": "shop"},
       answer="count\n-------\n1842093\n(1 row)"),
    V2(id="postgresql-query-v2-0002", tool="postgresql", operation="query",
       complexity="diagnostic",
       user_input="Something is holding a lock on the invoices table in the billing database and updates are stalling — can you check pg_locks?",
       args={"operation": "query", "sql": "SELECT * FROM pg_locks WHERE relation = 'invoices'::regclass", "database": "billing"},
       answer="3 rows returned.\npid=8821  mode=RowExclusiveLock  granted=t\npid=9013  mode=AccessExclusiveLock  granted=f"),
    V2(id="postgresql-query-v2-0003", tool="postgresql", operation="query",
       complexity="single",
       user_input="what tables exist in the analytics database",
       args={"operation": "query", "sql": "\\dt", "database": "analytics"},
       answer="Schema | Name       | Type\npublic | events     | table\npublic | sessions   | table\n(2 rows)"),
    V2(id="postgresql-query-v2-0004", tool="postgresql", operation="query",
       complexity="single",
       user_input="Show the 5 largest tables in the warehouse database by size.",
       args={"operation": "query", "sql": "SELECT relname, pg_size_pretty(pg_total_relation_size(relid)) FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC LIMIT 5", "database": "warehouse"},
       answer="relname       | pg_size_pretty\nfact_sales    | 42 GB\ndim_customer  | 6 GB\n(5 rows)"),
    V2(id="postgresql-query-v2-0005", tool="postgresql", operation="query",
       complexity="diagnostic",
       user_input="Query throughput on the sales database dropped off a cliff an hour ago — check for anything long-running against it right now.",
       args={"operation": "query", "sql": "SELECT pid, now() - query_start AS duration, query FROM pg_stat_activity WHERE state != 'idle' ORDER BY duration DESC", "database": "sales"},
       answer="1 row returned.\npid=5521  duration=00:52:11  query=UPDATE sales_fact SET region_id=..."),
    V2(id="postgresql-query-v2-0006", tool="postgresql", operation="query",
       complexity="single",
       user_input="Connect as the readonly user and list the roles in the cluster.",
       args={"operation": "query", "sql": "\\du", "username": "readonly"},
       answer="Role name | Attributes\nreadonly  | \npostgres  | Superuser, Create role, Create DB\n(2 rows)"),

    V2(id="postgresql-createdb-v2-0001", tool="postgresql", operation="createdb",
       complexity="single",
       user_input="Create a new database called metrics_v2.",
       args={"operation": "createdb", "dbname": "metrics_v2"},
       answer="CREATE DATABASE\nDatabase 'metrics_v2' created."),
    V2(id="postgresql-createdb-v2-0002", tool="postgresql", operation="createdb",
       complexity="diagnostic",
       user_input="The onboarding runbook for the new tenant platform says a tenant_alpha database has to exist before the migration scripts can run — does it, and if not can you create it?",
       args={"operation": "createdb", "dbname": "tenant_alpha"},
       answer="CREATE DATABASE\nDatabase 'tenant_alpha' created."),
    V2(id="postgresql-createdb-v2-0003", tool="postgresql", operation="createdb",
       complexity="single",
       user_input="set up a database named hr_records please",
       args={"operation": "createdb", "dbname": "hr_records"},
       answer="CREATE DATABASE\nDatabase 'hr_records' created."),
    V2(id="postgresql-createdb-v2-0004", tool="postgresql", operation="createdb",
       complexity="single",
       user_input="Create a fresh testing database called qa_run_318, connecting as user pgadmin.",
       args={"operation": "createdb", "dbname": "qa_run_318", "username": "pgadmin"},
       answer="CREATE DATABASE\nDatabase 'qa_run_318' created."),
    V2(id="postgresql-createdb-v2-0005", tool="postgresql", operation="createdb",
       complexity="multi",
       user_input="Create the events_prod database and then create a role for the ingest service to use with it.",
       args={"operation": "createdb", "dbname": "events_prod"},
       answer="CREATE DATABASE\nDatabase 'events_prod' created."),
    V2(id="postgresql-createdb-v2-0006", tool="postgresql", operation="createdb",
       complexity="single",
       user_input="initialize a database called billing_stage on the staging cluster",
       args={"operation": "createdb", "dbname": "billing_stage"},
       answer="CREATE DATABASE\nDatabase 'billing_stage' created."),
    V2(id="postgresql-createdb-v2-0007", tool="postgresql", operation="createdb",
       complexity="diagnostic",
       user_input="The deploy log shows createdb failing for catalog_service with 'already exists' — is that actually true, or should we retry the create for a fresh name catalog_service_v2?",
       args={"operation": "createdb", "dbname": "catalog_service_v2"},
       answer="CREATE DATABASE\nDatabase 'catalog_service_v2' created."),
    V2(id="postgresql-createdb-v2-0008", tool="postgresql", operation="createdb",
       complexity="single",
       user_input="Make a new database named audit_log for the compliance team.",
       args={"operation": "createdb", "dbname": "audit_log"},
       answer="CREATE DATABASE\nDatabase 'audit_log' created."),

    V2(id="postgresql-createuser-v2-0001", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="Create a postgres role called ingest_svc.",
       args={"operation": "createuser", "rolename": "ingest_svc"},
       answer="CREATE ROLE\nRole 'ingest_svc' created."),
    V2(id="postgresql-createuser-v2-0002", tool="postgresql", operation="createuser",
       complexity="diagnostic",
       user_input="The new reporting dashboard can't connect to postgres at all — does a role for it even exist, and if not create dash_reader for it?",
       args={"operation": "createuser", "rolename": "dash_reader"},
       answer="CREATE ROLE\nRole 'dash_reader' created."),
    V2(id="postgresql-createuser-v2-0003", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="add a readonly role named audit_ro to the cluster",
       args={"operation": "createuser", "rolename": "audit_ro"},
       answer="CREATE ROLE\nRole 'audit_ro' created."),
    V2(id="postgresql-createuser-v2-0004", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="Create a new login role called etl_writer, connecting as pgadmin to set it up.",
       args={"operation": "createuser", "rolename": "etl_writer", "username": "pgadmin"},
       answer="CREATE ROLE\nRole 'etl_writer' created."),
    V2(id="postgresql-createuser-v2-0005", tool="postgresql", operation="createuser",
       complexity="multi",
       user_input="Create a role named webapp_svc and then grant it access to the appdb database.",
       args={"operation": "createuser", "rolename": "webapp_svc"},
       answer="CREATE ROLE\nRole 'webapp_svc' created."),
    V2(id="postgresql-createuser-v2-0006", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="add a database account for the monitor daemon called monitor_svc",
       args={"operation": "createuser", "rolename": "monitor_svc"},
       answer="CREATE ROLE\nRole 'monitor_svc' created."),
    V2(id="postgresql-createuser-v2-0007", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="Create a postgres login role named backup_runner for the nightly backup job.",
       args={"operation": "createuser", "rolename": "backup_runner"},
       answer="CREATE ROLE\nRole 'backup_runner' created."),
    V2(id="postgresql-createuser-v2-0008", tool="postgresql", operation="createuser",
       complexity="diagnostic",
       user_input="Access review flagged that the billing_svc account has never been provisioned in postgres — set up that role now.",
       args={"operation": "createuser", "rolename": "billing_svc"},
       answer="CREATE ROLE\nRole 'billing_svc' created."),
    V2(id="postgresql-createuser-v2-0009", tool="postgresql", operation="createuser",
       complexity="single",
       user_input="add a role called ci_runner for the pipeline to authenticate with",
       args={"operation": "createuser", "rolename": "ci_runner"},
       answer="CREATE ROLE\nRole 'ci_runner' created."),

    V2(id="postgresql-pg_dump-v2-0001", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="Dump the appdb database to /backup/appdb_20260913.sql.",
       args={"operation": "pg_dump", "dbname": "appdb", "output_file": "/backup/appdb_20260913.sql"},
       answer="pg_dump: dump complete.\n/backup/appdb_20260913.sql written, 214M."),
    V2(id="postgresql-pg_dump-v2-0002", tool="postgresql", operation="pg_dump",
       complexity="diagnostic",
       user_input="The migration to the new cluster is scheduled tonight and nobody can confirm a recent backup of the inventory database exists — take one now to /mnt/backups/inventory.sql.",
       args={"operation": "pg_dump", "dbname": "inventory", "output_file": "/mnt/backups/inventory.sql"},
       answer="pg_dump: dump complete.\n/mnt/backups/inventory.sql written, 88M."),
    V2(id="postgresql-pg_dump-v2-0003", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="back up the sales database to /var/backup/pg/sales.sql",
       args={"operation": "pg_dump", "dbname": "sales", "output_file": "/var/backup/pg/sales.sql"},
       answer="pg_dump: dump complete.\n/var/backup/pg/sales.sql written, 512M."),
    V2(id="postgresql-pg_dump-v2-0004", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="Export the hr_data database to /tmp/hr_data_export.sql, connecting as pgadmin.",
       args={"operation": "pg_dump", "dbname": "hr_data", "output_file": "/tmp/hr_data_export.sql", "username": "pgadmin"},
       answer="pg_dump: dump complete.\n/tmp/hr_data_export.sql written, 30M."),
    V2(id="postgresql-pg_dump-v2-0005", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="Take a snapshot of the metrics database into /srv/dumps/metrics.sql before the schema change.",
       args={"operation": "pg_dump", "dbname": "metrics", "output_file": "/srv/dumps/metrics.sql"},
       answer="pg_dump: dump complete.\n/srv/dumps/metrics.sql written, 1.4G."),
    V2(id="postgresql-pg_dump-v2-0006", tool="postgresql", operation="pg_dump",
       complexity="diagnostic",
       user_input="The last scheduled dump of catalog_service seems to have failed silently — retry it manually to /backup/catalog_service.sql.",
       args={"operation": "pg_dump", "dbname": "catalog_service", "output_file": "/backup/catalog_service.sql"},
       answer="pg_dump: dump complete.\n/backup/catalog_service.sql written, 176M."),
    V2(id="postgresql-pg_dump-v2-0007", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="dump production to /mnt/nfs/backups/prod_20260913.sql",
       args={"operation": "pg_dump", "dbname": "production", "output_file": "/mnt/nfs/backups/prod_20260913.sql"},
       answer="pg_dump: dump complete.\n/mnt/nfs/backups/prod_20260913.sql written, 3.2G."),
    V2(id="postgresql-pg_dump-v2-0008", tool="postgresql", operation="pg_dump",
       complexity="multi",
       user_input="Dump the events_prod database to /backup/events_prod.sql, then move the file to the offsite backup share.",
       args={"operation": "pg_dump", "dbname": "events_prod", "output_file": "/backup/events_prod.sql"},
       answer="pg_dump: dump complete.\n/backup/events_prod.sql written, 950M."),
    V2(id="postgresql-pg_dump-v2-0009", tool="postgresql", operation="pg_dump",
       complexity="single",
       user_input="Back up the audit_log database to /backup/audit_log_pre_purge.sql before we run the retention cleanup.",
       args={"operation": "pg_dump", "dbname": "audit_log", "output_file": "/backup/audit_log_pre_purge.sql"},
       answer="pg_dump: dump complete.\n/backup/audit_log_pre_purge.sql written, 68M."),

    V2(id="postgresql-dropdb-v2-0001", tool="postgresql", operation="dropdb",
       complexity="single",
       user_input="Drop the qa_run_318 database, the test cycle finished.",
       args={"operation": "dropdb", "dbname": "qa_run_318"},
       answer="DROP DATABASE\nDatabase 'qa_run_318' removed."),
    V2(id="postgresql-dropdb-v2-0002", tool="postgresql", operation="dropdb",
       complexity="diagnostic",
       user_input="The old_archive database has had zero connections for six months per the access logs — is it safe to drop, and can you drop it?",
       args={"operation": "dropdb", "dbname": "old_archive"},
       answer="DROP DATABASE\nDatabase 'old_archive' removed."),
    V2(id="postgresql-dropdb-v2-0003", tool="postgresql", operation="dropdb",
       complexity="multi",
       user_input="Drop the staging_clone database and then confirm it no longer appears when you list databases.",
       args={"operation": "dropdb", "dbname": "staging_clone"},
       answer="DROP DATABASE\nDatabase 'staging_clone' removed."),
    V2(id="postgresql-dropdb-v2-0004", tool="postgresql", operation="dropdb",
       complexity="single",
       user_input="remove the temp_import database, it was only for a one-time load",
       args={"operation": "dropdb", "dbname": "temp_import"},
       answer="DROP DATABASE\nDatabase 'temp_import' removed."),
    V2(id="postgresql-dropdb-v2-0005", tool="postgresql", operation="dropdb",
       complexity="single",
       user_input="The dev_sandbox database is corrupt beyond repair — drop it so we can recreate it clean.",
       args={"operation": "dropdb", "dbname": "dev_sandbox"},
       answer="DROP DATABASE\nDatabase 'dev_sandbox' removed."),
    V2(id="postgresql-dropdb-v2-0006", tool="postgresql", operation="dropdb",
       complexity="single",
       user_input="permanently delete the poc_search database, connecting as pgadmin",
       args={"operation": "dropdb", "dbname": "poc_search", "username": "pgadmin"},
       answer="DROP DATABASE\nDatabase 'poc_search' removed."),
    V2(id="postgresql-dropdb-v2-0007", tool="postgresql", operation="dropdb",
       complexity="single",
       user_input="We finished decommissioning the legacy CMS — drop the cms_legacy database.",
       args={"operation": "dropdb", "dbname": "cms_legacy"},
       answer="DROP DATABASE\nDatabase 'cms_legacy' removed."),
    V2(id="postgresql-dropdb-v2-0008", tool="postgresql", operation="dropdb",
       complexity="diagnostic",
       user_input="Disk space on the pg cluster is critically low and the unused benchmark_2024 database is the largest thing not in active use — drop it.",
       args={"operation": "dropdb", "dbname": "benchmark_2024"},
       answer="DROP DATABASE\nDatabase 'benchmark_2024' removed."),
]

from finetune.scenarios_v2 import check_module; check_module("postgresql", SCENARIOS_V2)
