"""finetune/scenarios_v2/processes.py — corpus v2 scenarios for 'processes'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id='processes-list-v2-0001', tool='processes', operation='list',
       complexity='single',
       user_input='give me the full process table right now',
       args={'operation': 'list'},
       answer='412 processes total\ntop by RSS: postgres (812MB), httpd (240MB)'),
    V2(id='processes-list-v2-0002', tool='processes', operation='list',
       complexity='diagnostic',
       user_input='the host feels sluggish, dump every running process so I can spot the culprit',
       args={'operation': 'list'},
       answer='418 processes total, 1 in D state (pid 8821, kworker)'),
    V2(id='processes-list-v2-0003', tool='processes', operation='list',
       complexity='single',
       user_input='show every process running on this host',
       args={'operation': 'list'},
       answer='412 processes total'),
    V2(id='processes-list-v2-0004', tool='processes', operation='list',
       complexity='diagnostic',
       user_input='I suspect an unauthorized process, list all processes for review',
       args={'operation': 'list'},
       answer='412 processes, none running from /tmp or /dev/shm'),
    V2(id='processes-tree-v2-0005', tool='processes', operation='tree',
       complexity='single',
       user_input='show me the process hierarchy',
       args={'operation': 'tree'},
       answer='systemd(1)\n├─sshd(890)\n│  └─bash(1204)\n└─httpd(1050)\n   ├─httpd(1051)\n   └─httpd(1052)'),
    V2(id='processes-tree-v2-0006', tool='processes', operation='tree',
       complexity='diagnostic',
       user_input='nginx keeps spawning too many workers, check the tree to confirm the fan-out',
       args={'operation': 'tree'},
       answer='nginx(2201)\n├─nginx(2202)\n├─nginx(2203)\n├─nginx(2204)\n└─nginx(2205)  -- 4 workers, matches worker_processes=4'),
    V2(id='processes-tree-v2-0007', tool='processes', operation='tree',
       complexity='single',
       user_input='give me a tree view of running processes',
       args={'operation': 'tree'},
       answer='systemd(1)\n├─sshd(890)\n└─crond(910)'),
    V2(id='processes-tree-v2-0008', tool='processes', operation='tree',
       complexity='diagnostic',
       user_input='a mystery process appeared, show the tree so I can trace its parent',
       args={'operation': 'tree'},
       answer='systemd(1)\n└─bash(4410)\n   └─python3(4433)  -- parent is an unexpected interactive shell'),
    V2(id='processes-tree-v2-0009', tool='processes', operation='tree',
       complexity='single',
       user_input='display the process parentage on this box',
       args={'operation': 'tree'},
       answer='systemd(1)\n├─auditd(300)\n└─sssd(410)\n   ├─sssd_be(411)\n   └─sssd_nss(412)'),
    V2(id='processes-tree-v2-0010', tool='processes', operation='tree',
       complexity='single',
       user_input='how deep does the process tree go on this host right now?',
       args={'operation': 'tree'},
       answer='max depth 4: systemd -> httpd -> httpd -> php-fpm'),
    V2(id='processes-top-v2-0011', tool='processes', operation='top',
       complexity='single',
       user_input="what's eating the most CPU right now?",
       args={'operation': 'top'},
       answer='postgres pid 2201: 62% CPU\nhttpd pid 1050: 18% CPU'),
    V2(id='processes-top-v2-0012', tool='processes', operation='top',
       complexity='diagnostic',
       user_input="load average just spiked, what's driving it?",
       args={'operation': 'top'},
       answer='postgres pid 2201: 71% CPU (autovacuum)\nkworker pid 88: 12% CPU'),
    V2(id='processes-top-v2-0013', tool='processes', operation='top',
       complexity='single',
       user_input='give me a CPU snapshot',
       args={'operation': 'top'},
       answer='postgres pid 2201: 62% CPU\nhttpd pid 1050: 18% CPU\nsssd_be pid 411: 3% CPU'),
    V2(id='processes-top-v2-0014', tool='processes', operation='top',
       complexity='diagnostic',
       user_input='the box is pegged at 100% CPU, snapshot the top offenders now',
       args={'operation': 'top'},
       answer='java pid 9021: 88% CPU, owned by appsvc'),
    V2(id='processes-top-v2-0015', tool='processes', operation='top',
       complexity='single',
       user_input='which process is the biggest CPU hog?',
       args={'operation': 'top'},
       answer='java pid 9021: 88% CPU, user appsvc'),
    V2(id='processes-top-v2-0016', tool='processes', operation='top',
       complexity='diagnostic',
       user_input="users are complaining of slowness, what's hogging resources right now?",
       args={'operation': 'top'},
       answer='postgres pid 2201: 62% CPU\njava pid 9021: 88% CPU'),
    V2(id='processes-info-v2-0017', tool='processes', operation='info',
       complexity='single',
       user_input='show me detailed info for pid 2201',
       args={'operation': 'info', 'pid': 2201},
       answer='pid 2201: postgres, user postgres, state S, RSS 812MB, started 06:00:12'),
    V2(id='processes-info-v2-0018', tool='processes', operation='info',
       complexity='diagnostic',
       user_input='before I send a signal to pid 4410, tell me what it actually is',
       args={'operation': 'info', 'pid': 4410},
       answer='pid 4410: bash, user deploy, state S, parent 890 (sshd), started 09:14:02'),
    V2(id='processes-info-v2-0019', tool='processes', operation='info',
       complexity='single',
       user_input='what is process 9021 doing?',
       args={'operation': 'info', 'pid': 9021},
       answer='pid 9021: java, user appsvc, state R, RSS 1.2GB, CPU 88%'),
    V2(id='processes-info-v2-0020', tool='processes', operation='info',
       complexity='single',
       user_input='look up pid 411 and tell me who owns it',
       args={'operation': 'info', 'pid': 411},
       answer='pid 411: sssd_be, user root, state S, parent 410 (sssd)'),
    V2(id='processes-info-v2-0021', tool='processes', operation='info',
       complexity='diagnostic',
       user_input='pid 8821 showed up in D state, what is it?',
       args={'operation': 'info', 'pid': 8821},
       answer='pid 8821: kworker/2:1, state D, uninterruptible sleep, no CPU usage'),
    V2(id='processes-info-v2-0022', tool='processes', operation='info',
       complexity='single',
       user_input='get the full details on pid 1050',
       args={'operation': 'info', 'pid': 1050},
       answer='pid 1050: httpd, user root, state S, children: 1051, 1052'),
    V2(id='processes-signal-v2-0023', tool='processes', operation='signal',
       complexity='single',
       user_input='send SIGTERM to pid 4410',
       args={'operation': 'signal', 'pid': 4410},
       answer='sent signal 15 to pid 4410'),
    V2(id='processes-signal-v2-0024', tool='processes', operation='signal',
       complexity='single',
       user_input="kill pid 9021 with SIGKILL, it's not responding",
       args={'operation': 'signal', 'pid': 9021, 'signal_num': 9},
       answer='sent signal 9 to pid 9021'),
    V2(id='processes-signal-v2-0025', tool='processes', operation='signal',
       complexity='diagnostic',
       user_input='pid 8821 has been stuck in D state for an hour, try SIGTERM on it',
       args={'operation': 'signal', 'pid': 8821, 'signal_num': 15},
       answer='sent signal 15 to pid 8821, process still present after 5s (uninterruptible)'),
    V2(id='processes-signal-v2-0026', tool='processes', operation='signal',
       complexity='single',
       user_input='send signal 1 to pid 411 to reload sssd_be config',
       args={'operation': 'signal', 'pid': 411, 'signal_num': 1},
       answer='sent signal 1 to pid 411'),
    V2(id='processes-signal-v2-0027', tool='processes', operation='signal',
       complexity='multi',
       user_input="check what pid 3300 is, then send it SIGTERM if it's a stale worker",
       args={'operation': 'signal', 'pid': 3300, 'signal_num': 15},
       answer='sent signal 15 to pid 3300'),
    V2(id='processes-signal-v2-0028', tool='processes', operation='signal',
       complexity='single',
       user_input="force kill pid 7070, it's been zombie for an hour",
       args={'operation': 'signal', 'pid': 7070, 'signal_num': 9},
       answer='sent signal 9 to pid 7070'),
    V2(id='processes-renice-v2-0029', tool='processes', operation='renice',
       complexity='single',
       user_input='lower the priority of pid 2201, set nice to 10',
       args={'operation': 'renice', 'pid': 2201, 'priority': 10},
       answer='pid 2201 renice: nice 0 -> 10'),
    V2(id='processes-renice-v2-0030', tool='processes', operation='renice',
       complexity='single',
       user_input='set the scheduling priority of pid 9021 to nice 15',
       args={'operation': 'renice', 'pid': 9021, 'priority': 15},
       answer='pid 9021 renice: nice 0 -> 15'),
    V2(id='processes-renice-v2-0031', tool='processes', operation='renice',
       complexity='diagnostic',
       user_input='the nightly backup at pid 5500 is slowing down the database, can we deprioritize it?',
       args={'operation': 'renice', 'pid': 5500, 'priority': 10},
       answer='pid 5500 renice: nice 0 -> 10'),
    V2(id='processes-renice-v2-0032', tool='processes', operation='renice',
       complexity='single',
       user_input='renice pid 4400 to -5 for higher priority',
       args={'operation': 'renice', 'pid': 4400, 'priority': -5},
       answer='pid 4400 renice: nice 0 -> -5'),
    V2(id='processes-renice-v2-0033', tool='processes', operation='renice',
       complexity='multi',
       user_input='take a CPU snapshot, find the worst offender, and renice it to 10',
       args={'operation': 'renice', 'pid': 9021, 'priority': 10},
       answer='pid 9021 renice: nice 0 -> 10'),
    V2(id='processes-renice-v2-0034', tool='processes', operation='renice',
       complexity='single',
       user_input='deprioritize pid 6601 by setting its nice value to 19',
       args={'operation': 'renice', 'pid': 6601, 'priority': 19},
       answer='pid 6601 renice: nice 0 -> 19'),
    V2(id='processes-renice-v2-0035', tool='processes', operation='renice',
       complexity='diagnostic',
       user_input='the reporting job at pid 6601 is competing with the web tier, lower its priority to nice 15',
       args={'operation': 'renice', 'pid': 6601, 'priority': 15},
       answer='pid 6601 renice: nice 0 -> 15'),
    V2(id='processes-renice-v2-0036', tool='processes', operation='renice',
       complexity='single',
       user_input="set pid 8800's nice value to 19 to deprioritize it",
       args={'operation': 'renice', 'pid': 8800, 'priority': 19},
       answer='pid 8800 renice: nice 0 -> 19'),
]

from finetune.scenarios_v2 import check_module; check_module('processes', SCENARIOS_V2)
