"""finetune/scenarios_v2/quota.py — corpus v2 scenarios for 'quota'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # repquota (7)
    V2(id="quota-repquota-v2-0001", tool="quota", operation="repquota",
       complexity="single",
       user_input="Run a quota usage report for /var/www.",
       args={"operation": "repquota", "filesystem": "/var/www"},
       answer="*** Report for /var/www\nuser      used   soft   hard\ndeploy   4200M  5000M  6000M"),
    V2(id="quota-repquota-v2-0002", tool="quota", operation="repquota",
       complexity="diagnostic",
       user_input="/home is nearly full again — find out which accounts are eating the most space.",
       args={"operation": "repquota", "filesystem": "/home"},
       answer="*** Report for /home\nuser      used   soft   hard\nalice   48000M 50000M 55000M +\nbob     12000M 50000M 55000M"),
    V2(id="quota-repquota-v2-0003", tool="quota", operation="repquota",
       complexity="single",
       user_input="Report quota usage across every quota-enabled filesystem.",
       args={"operation": "repquota"},
       answer="*** Report for /home\nalice 48000M/50000M\n*** Report for /data\nsvc-etl 900000M/1000000M"),
    V2(id="quota-repquota-v2-0004", tool="quota", operation="repquota",
       complexity="single",
       user_input="Show the quota report for /srv/mail.",
       args={"operation": "repquota", "filesystem": "/srv/mail"},
       answer="*** Report for /srv/mail\nuser      used   soft   hard\nmail1   1900M  2000M  2200M"),
    V2(id="quota-repquota-v2-0005", tool="quota", operation="repquota",
       complexity="diagnostic",
       user_input="Several developers say they can't save build artifacts on /data — check who's over their soft limit there.",
       args={"operation": "repquota", "filesystem": "/data"},
       answer="*** Report for /data\nuser      used    soft    hard\nci-runner 990000M 1000000M 1000000M +"),
    V2(id="quota-repquota-v2-0006", tool="quota", operation="repquota",
       complexity="single",
       user_input="Generate a quota report for the /home partition.",
       args={"operation": "repquota", "filesystem": "/home"},
       answer="*** Report for /home\nuser      used   soft   hard\ncharlie 30000M 50000M 55000M"),
    V2(id="quota-repquota-v2-0007", tool="quota", operation="repquota",
       complexity="diagnostic",
       user_input="Grace periods are expiring on /home and I need to know who's still over — pull the report.",
       args={"operation": "repquota", "filesystem": "/home"},
       answer="*** Report for /home\nuser      used   soft   hard   grace\nalice   52000M 50000M 55000M 3days"),
    # quota_user (8)
    V2(id="quota-quota_user-v2-0001", tool="quota", operation="quota_user",
       complexity="single",
       user_input="What are dave's disk quota limits?",
       args={"operation": "quota_user", "username": "dave"},
       answer="Disk quotas for user dave:\n/home 18000M 20000M 22000M"),
    V2(id="quota-quota_user-v2-0002", tool="quota", operation="quota_user",
       complexity="diagnostic",
       user_input="alice says uploads are failing on the shared drive — check her quota to see if she's maxed out.",
       args={"operation": "quota_user", "username": "alice"},
       answer="Disk quotas for user alice:\n/home 52000M 50000M 55000M (over soft limit)"),
    V2(id="quota-quota_user-v2-0003", tool="quota", operation="quota_user",
       complexity="single",
       user_input="Check the disk quota for the jenkins service account.",
       args={"operation": "quota_user", "username": "jenkins"},
       answer="Disk quotas for user jenkins:\n/home 8000M 10000M 12000M"),
    V2(id="quota-quota_user-v2-0004", tool="quota", operation="quota_user",
       complexity="single",
       user_input="How much space does bob have used and remaining?",
       args={"operation": "quota_user", "username": "bob"},
       answer="Disk quotas for user bob:\n/home 12000M 50000M 55000M (38000M remaining)"),
    V2(id="quota-quota_user-v2-0005", tool="quota", operation="quota_user",
       complexity="diagnostic",
       user_input="The nightly backup job failed with a disk full error on the backup account — check its quota.",
       args={"operation": "quota_user", "username": "backup"},
       answer="Disk quotas for user backup:\n/data 1000000M 1000000M 1000000M (at hard limit)"),
    V2(id="quota-quota_user-v2-0006", tool="quota", operation="quota_user",
       complexity="single",
       user_input="Show disk usage and limits for user erin.",
       args={"operation": "quota_user", "username": "erin"},
       answer="Disk quotas for user erin:\n/home 5000M 20000M 22000M"),
    V2(id="quota-quota_user-v2-0007", tool="quota", operation="quota_user",
       complexity="diagnostic",
       user_input="charlie is complaining he can't save a file — if he's above 80 percent of his limit tell me the hard cap too.",
       args={"operation": "quota_user", "username": "charlie"},
       answer="Disk quotas for user charlie:\n/home 44000M 50000M 55000M (88% of soft, hard=55000M)"),
    V2(id="quota-quota_user-v2-0008", tool="quota", operation="quota_user",
       complexity="single",
       user_input="Pull up frank's quota.",
       args={"operation": "quota_user", "username": "frank"},
       answer="Disk quotas for user frank:\n/home 9000M 20000M 22000M"),
    # quotaon (8)
    V2(id="quota-quotaon-v2-0001", tool="quota", operation="quotaon",
       complexity="single",
       user_input="Turn on disk quotas for /data.",
       args={"operation": "quotaon", "filesystem": "/data"},
       answer="/data: quotas turned on"),
    V2(id="quota-quotaon-v2-0002", tool="quota", operation="quotaon",
       complexity="diagnostic",
       user_input="Limits on /home aren't being enforced at all even though we set them — check if quota tracking is actually enabled and turn it on.",
       args={"operation": "quotaon", "filesystem": "/home"},
       answer="/home: quotas turned on"),
    V2(id="quota-quotaon-v2-0003", tool="quota", operation="quotaon",
       complexity="single",
       user_input="Activate quota enforcement on /srv/mail.",
       args={"operation": "quotaon", "filesystem": "/srv/mail"},
       answer="/srv/mail: quotas turned on"),
    V2(id="quota-quotaon-v2-0004", tool="quota", operation="quotaon",
       complexity="multi",
       user_input="Enable quotas on /home and then confirm they're actually active in the report.",
       args={"operation": "quotaon", "filesystem": "/home"},
       answer="/home: quotas turned on"),
    V2(id="quota-quotaon-v2-0005", tool="quota", operation="quotaon",
       complexity="single",
       user_input="Enable user and group quotas on /var/www.",
       args={"operation": "quotaon", "filesystem": "/var/www"},
       answer="/var/www: quotas turned on"),
    V2(id="quota-quotaon-v2-0006", tool="quota", operation="quotaon",
       complexity="diagnostic",
       user_input="After the reboot last night, disk limits on /data seem to have reset — turn quotas back on.",
       args={"operation": "quotaon", "filesystem": "/data"},
       answer="/data: quotas turned on"),
    V2(id="quota-quotaon-v2-0007", tool="quota", operation="quotaon",
       complexity="multi",
       user_input="Run quotacheck on /home first, then turn quotas on.",
       args={"operation": "quotaon", "filesystem": "/home"},
       answer="/home: quotas turned on"),
    V2(id="quota-quotaon-v2-0008", tool="quota", operation="quotaon",
       complexity="single",
       user_input="quotaon for the /scratch filesystem.",
       args={"operation": "quotaon", "filesystem": "/scratch"},
       answer="/scratch: quotas turned on"),
    # quotaoff (9)
    V2(id="quota-quotaoff-v2-0001", tool="quota", operation="quotaoff",
       complexity="single",
       user_input="Disable disk quotas on /data during the migration.",
       args={"operation": "quotaoff", "filesystem": "/data"},
       answer="/data: quotas turned off"),
    V2(id="quota-quotaoff-v2-0002", tool="quota", operation="quotaoff",
       complexity="single",
       user_input="Turn off quota enforcement on /srv/mail.",
       args={"operation": "quotaoff", "filesystem": "/srv/mail"},
       answer="/srv/mail: quotas turned off"),
    V2(id="quota-quotaoff-v2-0003", tool="quota", operation="quotaoff",
       complexity="multi",
       user_input="Turn off quotas on /home, run quotacheck, and then re-enable them.",
       args={"operation": "quotaoff", "filesystem": "/home"},
       answer="/home: quotas turned off"),
    V2(id="quota-quotaoff-v2-0004", tool="quota", operation="quotaoff",
       complexity="diagnostic",
       user_input="Enforcement checks on /home seem to be adding noticeable latency to writes — disable it while we investigate.",
       args={"operation": "quotaoff", "filesystem": "/home"},
       answer="/home: quotas turned off"),
    V2(id="quota-quotaoff-v2-0005", tool="quota", operation="quotaoff",
       complexity="single",
       user_input="Disable quota tracking on /var/mail.",
       args={"operation": "quotaoff", "filesystem": "/var/mail"},
       answer="/var/mail: quotas turned off"),
    V2(id="quota-quotaoff-v2-0006", tool="quota", operation="quotaoff",
       complexity="single",
       user_input="Turn off quotas on /scratch, that filesystem is being decommissioned.",
       args={"operation": "quotaoff", "filesystem": "/scratch"},
       answer="/scratch: quotas turned off"),
    V2(id="quota-quotaoff-v2-0007", tool="quota", operation="quotaoff",
       complexity="multi",
       user_input="Turn off quotas on /data and confirm the usage report no longer shows enforcement.",
       args={"operation": "quotaoff", "filesystem": "/data"},
       answer="/data: quotas turned off"),
    V2(id="quota-quotaoff-v2-0008", tool="quota", operation="quotaoff",
       complexity="single",
       user_input="quotaoff on /var/www for the maintenance window.",
       args={"operation": "quotaoff", "filesystem": "/var/www"},
       answer="/var/www: quotas turned off"),
    V2(id="quota-quotaoff-v2-0009", tool="quota", operation="quotaoff",
       complexity="diagnostic",
       user_input="We're about to run a large rsync into /home and don't want quota rejections mid-transfer — disable quotas there for now.",
       args={"operation": "quotaoff", "filesystem": "/home"},
       answer="/home: quotas turned off"),
    # quotacheck (8)
    V2(id="quota-quotacheck-v2-0001", tool="quota", operation="quotacheck",
       complexity="single",
       user_input="Rebuild the quota accounting files on /data.",
       args={"operation": "quotacheck", "filesystem": "/data"},
       answer="quotacheck: Scanning /data for quota files... done\naquota.user and aquota.group rebuilt"),
    V2(id="quota-quotacheck-v2-0002", tool="quota", operation="quotacheck",
       complexity="diagnostic",
       user_input="The usage numbers in the /home quota report look completely wrong — rebuild the accounting database there.",
       args={"operation": "quotacheck", "filesystem": "/home"},
       answer="quotacheck: Scanning /home for quota files... done\naquota.user and aquota.group rebuilt"),
    V2(id="quota-quotacheck-v2-0003", tool="quota", operation="quotacheck",
       complexity="single",
       user_input="Scan /srv/mail and update the quota files.",
       args={"operation": "quotacheck", "filesystem": "/srv/mail"},
       answer="quotacheck: Scanning /srv/mail for quota files... done\naquota.user and aquota.group rebuilt"),
    V2(id="quota-quotacheck-v2-0004", tool="quota", operation="quotacheck",
       complexity="single",
       user_input="Initialize quota tracking on /var/www, there are no quota files there yet.",
       args={"operation": "quotacheck", "filesystem": "/var/www"},
       answer="quotacheck: Scanning /var/www for quota files... done\naquota.user created"),
    V2(id="quota-quotacheck-v2-0005", tool="quota", operation="quotacheck",
       complexity="diagnostic",
       user_input="After the unclean shutdown last night, the quota database on /data might be inconsistent — check and repair it.",
       args={"operation": "quotacheck", "filesystem": "/data"},
       answer="quotacheck: Scanning /data for quota files... done\naquota.user and aquota.group rebuilt"),
    V2(id="quota-quotacheck-v2-0006", tool="quota", operation="quotacheck",
       complexity="multi",
       user_input="Disable quotas on /home, run quotacheck, then turn them back on.",
       args={"operation": "quotacheck", "filesystem": "/home"},
       answer="quotacheck: Scanning /home for quota files... done\naquota.user and aquota.group rebuilt"),
    V2(id="quota-quotacheck-v2-0007", tool="quota", operation="quotacheck",
       complexity="single",
       user_input="Check quota consistency on /scratch.",
       args={"operation": "quotacheck", "filesystem": "/scratch"},
       answer="quotacheck: Scanning /scratch for quota files... done\nno discrepancies found"),
    V2(id="quota-quotacheck-v2-0008", tool="quota", operation="quotacheck",
       complexity="multi",
       user_input="Rebuild the quota database on /home, then pull the current usage report.",
       args={"operation": "quotacheck", "filesystem": "/home"},
       answer="quotacheck: Scanning /home for quota files... done\naquota.user and aquota.group rebuilt"),
    # edquota (6)
    V2(id="quota-edquota-v2-0001", tool="quota", operation="edquota",
       complexity="single",
       user_input="Give erin a 2GB soft limit and 2.5GB hard limit on /home.",
       args={"operation": "edquota", "username": "erin", "filesystem": "/home", "soft_blocks": 2000000, "hard_blocks": 2500000},
       answer="Disk quotas for user erin updated:\n/home soft=2000000K hard=2500000K"),
    V2(id="quota-edquota-v2-0002", tool="quota", operation="edquota",
       complexity="single",
       user_input="Set a 1GB hard disk limit for user frank on /home.",
       args={"operation": "edquota", "username": "frank", "filesystem": "/home", "hard_blocks": 1000000},
       answer="Disk quotas for user frank updated:\n/home hard=1000000K"),
    V2(id="quota-edquota-v2-0003", tool="quota", operation="edquota",
       complexity="diagnostic",
       user_input="charlie keeps hitting his hard limit and it's blocking a cleanup script — temporarily raise his hard limit on /home to 60000M.",
       args={"operation": "edquota", "username": "charlie", "filesystem": "/home", "hard_blocks": 60000000},
       answer="Disk quotas for user charlie updated:\n/home hard=60000000K"),
    V2(id="quota-edquota-v2-0004", tool="quota", operation="edquota",
       complexity="single",
       user_input="Set a 10000 inode soft limit and 12000 hard limit for jenkins on /home.",
       args={"operation": "edquota", "username": "jenkins", "filesystem": "/home", "soft_inodes": 10000, "hard_inodes": 12000},
       answer="Disk quotas for user jenkins updated:\n/home soft_inodes=10000 hard_inodes=12000"),
    V2(id="quota-edquota-v2-0005", tool="quota", operation="edquota",
       complexity="single",
       user_input="Remove disk limits entirely for the backup service account on /data.",
       args={"operation": "edquota", "username": "backup", "filesystem": "/data", "soft_blocks": 0, "hard_blocks": 0},
       answer="Disk quotas for user backup updated:\n/data soft=0K (unlimited) hard=0K (unlimited)"),
    V2(id="quota-edquota-v2-0006", tool="quota", operation="edquota",
       complexity="diagnostic",
       user_input="Alice needs more room to finish her project — bump her disk quota on /home from 50GB to 80GB soft, 85GB hard.",
       args={"operation": "edquota", "username": "alice", "filesystem": "/home", "soft_blocks": 80000000, "hard_blocks": 85000000},
       answer="Disk quotas for user alice updated:\n/home soft=80000000K hard=85000000K"),
]

from finetune.scenarios_v2 import check_module; check_module("quota", SCENARIOS_V2)
