"""finetune/scenarios_v2/restic.py — corpus v2 scenarios for 'restic'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="restic-snapshots-v2-0001", tool="restic", operation="snapshots",
       complexity="single",
       user_input="List every snapshot in the /mnt/backup/restic-repo repository.",
       args={"operation": "snapshots", "repo": "/mnt/backup/restic-repo"},
       answer="ID       Time                 Host        Tags     Paths\na1b2c3d4 2026-09-12 02:00:11  db-node-3   nightly  /var/lib/postgresql\ne5f6a7b8 2026-09-11 02:00:07  db-node-3   nightly  /var/lib/postgresql\n2 snapshots."),
    V2(id="restic-snapshots-v2-0002", tool="restic", operation="snapshots",
       complexity="single",
       user_input="show snapshots tagged 'pre-deploy'",
       args={"operation": "snapshots", "tag": "pre-deploy"},
       answer="ID       Time                 Host       Tags        Paths\n99aa11bb 2026-09-10 14:22:03  web-node-1 pre-deploy  /var/www\n1 snapshot."),
    V2(id="restic-snapshots-v2-0003", tool="restic", operation="snapshots",
       complexity="diagnostic",
       user_input="The nightly cron says the backup job succeeded but I want to be sure a snapshot actually landed for host app-node-2 — can you check?",
       args={"operation": "snapshots", "host": "app-node-2"},
       answer="ID       Time                 Host        Tags     Paths\nffee0011 2026-09-12 03:15:44  app-node-2 nightly  /opt/app\n1 snapshot found — last night's backup did complete."),
    V2(id="restic-snapshots-v2-0004", tool="restic", operation="snapshots",
       complexity="diagnostic",
       user_input="A compliance review needs proof we have a recent backup of /etc from the mail server — can you pull the snapshot list for that host?",
       args={"operation": "snapshots", "host": "mail-node-1"},
       answer="ID       Time                 Host        Tags   Paths\n11223344 2026-09-11 01:00:02  mail-node-1 weekly /etc\n1 snapshot, most recent 2026-09-11."),
    V2(id="restic-snapshots-v2-0005", tool="restic", operation="snapshots",
       complexity="multi",
       user_input="List the snapshots in /srv/restic-repo and then restore the latest one to /mnt/restore-test.",
       args={"operation": "snapshots", "repo": "/srv/restic-repo"},
       answer="ID       Time                 Host       Tags    Paths\n55667788 2026-09-12 05:00:19  db-node-3 monthly /var/lib/postgresql\n1 snapshot."),

    V2(id="restic-backup-v2-0001", tool="restic", operation="backup",
       complexity="single",
       user_input="Back up /etc to the restic repo at /mnt/backup/restic-repo.",
       args={"operation": "backup", "path": "/etc", "repo": "/mnt/backup/restic-repo"},
       answer="snapshot a1b2c3d4 saved\nFiles: 1,204 new, 0 changed\nAdded to the repository: 8.3 MiB"),
    V2(id="restic-backup-v2-0002", tool="restic", operation="backup",
       complexity="single",
       user_input="take a backup of /var/www tagged 'pre-deploy'",
       args={"operation": "backup", "path": "/var/www", "tag": "pre-deploy"},
       answer="snapshot 99aa11bb saved\nFiles: 3,412 new, 12 changed\nAdded to the repository: 214 MiB"),
    V2(id="restic-backup-v2-0003", tool="restic", operation="backup",
       complexity="diagnostic",
       user_input="We're about to apply a config change to nginx — should we snapshot /etc/nginx first, and can you run that now tagged 'pre-change'?",
       args={"operation": "backup", "path": "/etc/nginx", "tag": "pre-change"},
       answer="snapshot bb22cc33 saved\nFiles: 41 new, 0 changed\nAdded to the repository: 96 KiB"),
    V2(id="restic-backup-v2-0004", tool="restic", operation="backup",
       complexity="multi",
       user_input="Back up /home to the repo at /mnt/backup/restic-repo, then list the snapshots when it's done.",
       args={"operation": "backup", "path": "/home", "repo": "/mnt/backup/restic-repo"},
       answer="snapshot dd44ee55 saved\nFiles: 8,902 new, 340 changed\nAdded to the repository: 1.4 GiB"),

    V2(id="restic-restore-v2-0001", tool="restic", operation="restore",
       complexity="single",
       user_input="Restore snapshot a1b2c3d4 to /mnt/restore-test.",
       args={"operation": "restore", "snapshot_id": "a1b2c3d4", "target": "/mnt/restore-test"},
       answer="Restoring <snapshot a1b2c3d4> to /mnt/restore-test\nrestored 1,204 files, 8.3 MiB\nExit code 0."),
    V2(id="restic-restore-v2-0002", tool="restic", operation="restore",
       complexity="single",
       user_input="restore the latest snapshot from /srv/restic-repo into /var/www.restore",
       args={"operation": "restore", "snapshot_id": "latest", "target": "/var/www.restore", "repo": "/srv/restic-repo"},
       answer="Restoring <snapshot 55667788> to /var/www.restore\nrestored 3,412 files, 214 MiB\nExit code 0."),
    V2(id="restic-restore-v2-0003", tool="restic", operation="restore",
       complexity="diagnostic",
       user_input="Someone accidentally deleted /etc/nginx/nginx.conf on web-node-1 — can we pull the pre-change snapshot back out to a scratch directory so I can grab the file?",
       args={"operation": "restore", "snapshot_id": "bb22cc33", "target": "/tmp/nginx-restore"},
       answer="Restoring <snapshot bb22cc33> to /tmp/nginx-restore\nrestored 41 files, 96 KiB\nExit code 0."),
    V2(id="restic-restore-v2-0004", tool="restic", operation="restore",
       complexity="multi",
       user_input="Restore snapshot dd44ee55 to /home.recovered and then verify the file count matches the original.",
       args={"operation": "restore", "snapshot_id": "dd44ee55", "target": "/home.recovered"},
       answer="Restoring <snapshot dd44ee55> to /home.recovered\nrestored 8,902 files, 1.4 GiB\nExit code 0."),
    V2(id="restic-restore-v2-0005", tool="restic", operation="restore",
       complexity="diagnostic",
       user_input="The postgres data directory got corrupted after last night's disk error — restore the most recent snapshot from repo /mnt/backup/restic-repo into /var/lib/postgresql.recovery so we can inspect it before swapping it in.",
       args={"operation": "restore", "snapshot_id": "latest", "target": "/var/lib/postgresql.recovery", "repo": "/mnt/backup/restic-repo"},
       answer="Restoring <snapshot a1b2c3d4> to /var/lib/postgresql.recovery\nrestored 6,004 files, 2.1 GiB\nExit code 0."),
    V2(id="restic-restore-v2-0006", tool="restic", operation="restore",
       complexity="single",
       user_input="pull snapshot ffee0011 out to /opt/app.restore",
       args={"operation": "restore", "snapshot_id": "ffee0011", "target": "/opt/app.restore"},
       answer="Restoring <snapshot ffee0011> to /opt/app.restore\nrestored 512 files, 44 MiB\nExit code 0."),

    V2(id="restic-forget-v2-0001", tool="restic", operation="forget",
       complexity="single",
       user_input="Forget snapshot e5f6a7b8, we don't need that one anymore.",
       args={"operation": "forget", "snapshot_id": "e5f6a7b8"},
       answer="removed snapshot e5f6a7b8\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0002", tool="restic", operation="forget",
       complexity="single",
       user_input="remove snapshot 99aa11bb from the index in /srv/restic-repo",
       args={"operation": "forget", "snapshot_id": "99aa11bb", "repo": "/srv/restic-repo"},
       answer="removed snapshot 99aa11bb\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0003", tool="restic", operation="forget",
       complexity="diagnostic",
       user_input="We accidentally tagged a snapshot with the wrong host name — snapshot bb22cc33 — can that just be forgotten and re-taken?",
       args={"operation": "forget", "snapshot_id": "bb22cc33"},
       answer="removed snapshot bb22cc33\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0004", tool="restic", operation="forget",
       complexity="multi",
       user_input="Forget snapshot dd44ee55 and then list the remaining snapshots to confirm it's gone.",
       args={"operation": "forget", "snapshot_id": "dd44ee55"},
       answer="removed snapshot dd44ee55\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0005", tool="restic", operation="forget",
       complexity="single",
       user_input="drop snapshot ffee0011 from the repo index at /mnt/backup/restic-repo",
       args={"operation": "forget", "snapshot_id": "ffee0011", "repo": "/mnt/backup/restic-repo"},
       answer="removed snapshot ffee0011\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0006", tool="restic", operation="forget",
       complexity="diagnostic",
       user_input="Storage on the backup target is filling up and this app-node-2 snapshot 11223344 is a duplicate of one we already kept — forget it for now?",
       args={"operation": "forget", "snapshot_id": "11223344"},
       answer="removed snapshot 11223344\n(pack data retained until next prune — run a prune to reclaim space)"),
    V2(id="restic-forget-v2-0007", tool="restic", operation="forget",
       complexity="single",
       user_input="forget the a1b2c3d4 snapshot",
       args={"operation": "forget", "snapshot_id": "a1b2c3d4"},
       answer="removed snapshot a1b2c3d4\n(pack data retained until next prune)"),
    V2(id="restic-forget-v2-0008", tool="restic", operation="forget",
       complexity="single",
       user_input="Remove the outdated snapshot 55667788 from the repository's index.",
       args={"operation": "forget", "snapshot_id": "55667788"},
       answer="removed snapshot 55667788\n(pack data retained until next prune)"),

    V2(id="restic-forget_prune-v2-0001", tool="restic", operation="forget_prune",
       complexity="single",
       user_input="Apply the retention policy keeping the last 7 snapshots and prune unreferenced data now.",
       args={"operation": "forget_prune", "keep_last": 7},
       answer="removed 9 snapshots\nrepository contains 41 packs (10.2 GiB)\nafter prune: 6.6 GiB reclaimed\nExit code 0."),
    V2(id="restic-forget_prune-v2-0002", tool="restic", operation="forget_prune",
       complexity="single",
       user_input="run forget and prune for host db-node-3, keep the last 14",
       args={"operation": "forget_prune", "keep_last": 14, "host": "db-node-3"},
       answer="removed 5 snapshots\nrepository contains 28 packs (5.4 GiB)\nafter prune: 1.8 GiB reclaimed\nExit code 0."),
    V2(id="restic-forget_prune-v2-0003", tool="restic", operation="forget_prune",
       complexity="diagnostic",
       user_input="Backup storage on /mnt/backup/restic-repo is at 95% and this is urgent — can we clean up old snapshots and actually free the disk space, not just drop them from the index?",
       args={"operation": "forget_prune", "keep_last": 5, "repo": "/mnt/backup/restic-repo"},
       answer="removed 22 snapshots\nrepository contains 60 packs (18.9 GiB)\nafter prune: 12.4 GiB reclaimed\nExit code 0."),
    V2(id="restic-forget_prune-v2-0004", tool="restic", operation="forget_prune",
       complexity="multi",
       user_input="Run forget and prune keeping the last 10 snapshots tagged 'nightly', then list what's left.",
       args={"operation": "forget_prune", "keep_last": 10, "tag": "nightly"},
       answer="removed 14 snapshots\nrepository contains 33 packs (7.7 GiB)\nafter prune: 3.9 GiB reclaimed\nExit code 0."),
    V2(id="restic-forget_prune-v2-0005", tool="restic", operation="forget_prune",
       complexity="diagnostic",
       user_input="We've been forgetting snapshots for weeks with the pack data never actually cleared — can you finally run a prune on /srv/restic-repo and confirm space comes back?",
       args={"operation": "forget_prune", "repo": "/srv/restic-repo"},
       answer="removed 3 snapshots\nrepository contains 71 packs (22.1 GiB)\nafter prune: 9.3 GiB reclaimed\nExit code 0."),
]

from finetune.scenarios_v2 import check_module; check_module("restic", SCENARIOS_V2)
