"""finetune/scenarios_v2/routing.py — corpus v2 scenarios for 'routing'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="routing-route_show-v2-0001", tool="routing", operation="route_show",
       complexity="single",
       user_input="Show the routing table on gateway-3.",
       args={"operation": "route_show"},
       answer="default via 10.0.0.1 dev eth0\n10.0.0.0/24 dev eth0 proto kernel scope link\n192.168.50.0/24 via 10.0.0.9 dev eth0"),
    V2(id="routing-route_show-v2-0002", tool="routing", operation="route_show",
       complexity="single",
       user_input="what routes does db-node-7 have configured",
       args={"operation": "route_show"},
       answer="default via 10.1.0.1 dev eth0\n10.1.0.0/24 dev eth0 proto kernel scope link"),
    V2(id="routing-route_show-v2-0003", tool="routing", operation="route_show",
       complexity="single",
       user_input="Pull table 100 on vpn-gw-2, we set up policy routing there recently.",
       args={"operation": "route_show", "table": "100"},
       answer="10.8.0.0/16 dev tun0 scope link\ndefault via 10.8.0.1 dev tun0"),
    V2(id="routing-route_show-v2-0004", tool="routing", operation="route_show",
       complexity="diagnostic",
       user_input="Traffic to 10.20.0.0/16 isn't arriving at app-node-4. Show the routing table so I can check for a missing route.",
       args={"operation": "route_show"},
       answer="default via 10.0.0.1 dev eth0\n10.0.0.0/24 dev eth0 proto kernel scope link\n(no route to 10.20.0.0/16)"),
    V2(id="routing-route_show-v2-0005", tool="routing", operation="route_show",
       complexity="diagnostic",
       user_input="edge-proxy-1 can't reach the internet at all. Check the routing table first before we touch firewalld rules.",
       args={"operation": "route_show"},
       answer="10.0.0.0/24 dev eth0 proto kernel scope link\n(no default route configured)"),
    V2(id="routing-route_show-v2-0006", tool="routing", operation="route_show",
       complexity="single",
       user_input="display the main table on lb-front-4",
       args={"operation": "route_show", "table": "main"},
       answer="default via 10.2.0.1 dev eth0\n10.2.0.0/24 dev eth0 proto kernel scope link\n10.3.0.0/24 via 10.2.0.5 dev eth0"),
    V2(id="routing-route_show-v2-0007", tool="routing", operation="route_show",
       complexity="multi",
       user_input="Show the routing table on nat-gw-2 and tell me if there's a default gateway set.",
       args={"operation": "route_show"},
       answer="default via 172.16.0.1 dev eth0\n172.16.0.0/24 dev eth0 proto kernel scope link"),
    V2(id="routing-route_show-v2-0008", tool="routing", operation="route_show",
       complexity="single",
       user_input="dump the ip route list for host build-runner-2",
       args={"operation": "route_show"},
       answer="default via 10.0.0.1 dev eth0\n10.0.0.0/24 dev eth0 proto kernel scope link"),
    V2(id="routing-route_show-v2-0009", tool="routing", operation="route_show",
       complexity="single",
       user_input="check what's in routing table 200 on multi-homed-srv-1",
       args={"operation": "route_show", "table": "200"},
       answer="192.168.20.0/24 dev eth1 scope link\ndefault via 192.168.20.1 dev eth1"),

    V2(id="routing-route_add-v2-0001", tool="routing", operation="route_add",
       complexity="single",
       user_input="Add a route to 192.168.60.0/24 via 10.0.0.5 on gateway-3.",
       args={"operation": "route_add", "dest": "192.168.60.0/24", "gateway": "10.0.0.5"},
       answer="Added route: 192.168.60.0/24 via 10.0.0.5 dev eth0"),
    V2(id="routing-route_add-v2-0002", tool="routing", operation="route_add",
       complexity="single",
       user_input="Set a default route via 10.4.0.254 on standby-router-1.",
       args={"operation": "route_add", "dest": "default", "gateway": "10.4.0.254"},
       answer="Added route: default via 10.4.0.254 dev eth0"),
    V2(id="routing-route_add-v2-0003", tool="routing", operation="route_add",
       complexity="single",
       user_input="On multi-homed-srv-1, route traffic for 172.20.0.0/12 out through eth1.",
       args={"operation": "route_add", "dest": "172.20.0.0/12", "dev": "eth1"},
       answer="Added route: 172.20.0.0/12 dev eth1 scope link"),
    V2(id="routing-route_add-v2-0004", tool="routing", operation="route_add",
       complexity="multi",
       user_input="Add a route to 10.55.0.0/16 via 10.0.0.1 with metric 200 on app-node-4, then verify it shows up in the table.",
       args={"operation": "route_add", "dest": "10.55.0.0/16", "gateway": "10.0.0.1", "metric": 200},
       answer="Added route: 10.55.0.0/16 via 10.0.0.1 dev eth0 metric 200"),
    V2(id="routing-route_add-v2-0005", tool="routing", operation="route_add",
       complexity="diagnostic",
       user_input="The VPN subnet 172.31.0.0/16 is unreachable from vpn-gw-2. Add a static route pointing to the VPN gateway 10.8.0.1.",
       args={"operation": "route_add", "dest": "172.31.0.0/16", "gateway": "10.8.0.1"},
       answer="Added route: 172.31.0.0/16 via 10.8.0.1 dev tun0"),
    V2(id="routing-route_add-v2-0006", tool="routing", operation="route_add",
       complexity="single",
       user_input="add route 192.168.5.0/24 via 10.0.0.1 metric 100 on lb-front-4",
       args={"operation": "route_add", "dest": "192.168.5.0/24", "gateway": "10.0.0.1", "metric": 100},
       answer="Added route: 192.168.5.0/24 via 10.0.0.1 dev eth0 metric 100"),
    V2(id="routing-route_add-v2-0007", tool="routing", operation="route_add",
       complexity="single",
       user_input="Create a static route for the management network 10.100.0.0/24 through gateway 10.100.0.254 on mgmt-console-1.",
       args={"operation": "route_add", "dest": "10.100.0.0/24", "gateway": "10.100.0.254"},
       answer="Added route: 10.100.0.0/24 via 10.100.0.254 dev eth0"),
    V2(id="routing-route_add-v2-0008", tool="routing", operation="route_add",
       complexity="single",
       user_input="on nat-gw-2 push traffic bound for 10.60.0.0/16 out interface eth2 with metric 50",
       args={"operation": "route_add", "dest": "10.60.0.0/16", "dev": "eth2", "metric": 50},
       answer="Added route: 10.60.0.0/16 dev eth2 metric 50"),
    V2(id="routing-route_add-v2-0009", tool="routing", operation="route_add",
       complexity="diagnostic",
       user_input="report-worker-2 keeps timing out reaching the backup subnet 10.70.0.0/16. Point it at gateway 10.0.0.9 via a static route.",
       args={"operation": "route_add", "dest": "10.70.0.0/16", "gateway": "10.0.0.9"},
       answer="Added route: 10.70.0.0/16 via 10.0.0.9 dev eth0"),

    V2(id="routing-route_del-v2-0001", tool="routing", operation="route_del",
       complexity="single",
       user_input="Remove the route to 192.168.60.0/24 on gateway-3.",
       args={"operation": "route_del", "dest": "192.168.60.0/24"},
       answer="Deleted route: 192.168.60.0/24"),
    V2(id="routing-route_del-v2-0002", tool="routing", operation="route_del",
       complexity="single",
       user_input="delete the static route for 10.55.0.0/16 on app-node-4",
       args={"operation": "route_del", "dest": "10.55.0.0/16"},
       answer="Deleted route: 10.55.0.0/16"),
    V2(id="routing-route_del-v2-0003", tool="routing", operation="route_del",
       complexity="single",
       user_input="Remove the default route on standby-router-1, we're switching gateways.",
       args={"operation": "route_del", "dest": "default"},
       answer="Deleted route: default"),
    V2(id="routing-route_del-v2-0004", tool="routing", operation="route_del",
       complexity="multi",
       user_input="On lb-front-4 delete the old route to 172.20.0.0/12 and add a new one via updated gateway 10.0.1.1.",
       args={"operation": "route_del", "dest": "172.20.0.0/12"},
       answer="Deleted route: 172.20.0.0/12"),
    V2(id="routing-route_del-v2-0005", tool="routing", operation="route_del",
       complexity="diagnostic",
       user_input="There's a duplicate route to 10.20.0.0/16 on multi-homed-srv-1 causing asymmetric routing. Remove the less preferred one via 10.0.0.2.",
       args={"operation": "route_del", "dest": "10.20.0.0/16", "gateway": "10.0.0.2"},
       answer="Deleted route: 10.20.0.0/16 via 10.0.0.2"),
    V2(id="routing-route_del-v2-0006", tool="routing", operation="route_del",
       complexity="single",
       user_input="clean up the old management route to 10.100.0.0/24 on mgmt-console-1",
       args={"operation": "route_del", "dest": "10.100.0.0/24"},
       answer="Deleted route: 10.100.0.0/24"),
    V2(id="routing-route_del-v2-0007", tool="routing", operation="route_del",
       complexity="single",
       user_input="remove the route to 192.168.200.0/24 that goes through eth2 on nat-gw-2",
       args={"operation": "route_del", "dest": "192.168.200.0/24", "dev": "eth2"},
       answer="Deleted route: 192.168.200.0/24 dev eth2"),
    V2(id="routing-route_del-v2-0008", tool="routing", operation="route_del",
       complexity="single",
       user_input="drop the route to 10.70.0.0/16 on report-worker-2, backup subnet was decommissioned",
       args={"operation": "route_del", "dest": "10.70.0.0/16"},
       answer="Deleted route: 10.70.0.0/16"),
    V2(id="routing-route_del-v2-0009", tool="routing", operation="route_del",
       complexity="single",
       user_input="Take out the route for 172.31.0.0/16 via 10.8.0.1 on vpn-gw-2, that tunnel is retired.",
       args={"operation": "route_del", "dest": "172.31.0.0/16", "gateway": "10.8.0.1"},
       answer="Deleted route: 172.31.0.0/16 via 10.8.0.1"),

    V2(id="routing-route_flush-v2-0001", tool="routing", operation="route_flush",
       complexity="single",
       user_input="Flush all routes in table 100 on vpn-gw-2.",
       args={"operation": "route_flush", "table": "100"},
       answer="Flushed routing table 100\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0002", tool="routing", operation="route_flush",
       complexity="single",
       user_input="clear all entries from table 200 on multi-homed-srv-1",
       args={"operation": "route_flush", "table": "200"},
       answer="Flushed routing table 200\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0003", tool="routing", operation="route_flush",
       complexity="multi",
       user_input="Flush table 100 on lb-front-4 and then re-add the correct routes from the runbook.",
       args={"operation": "route_flush", "table": "100"},
       answer="Flushed routing table 100\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0004", tool="routing", operation="route_flush",
       complexity="diagnostic",
       user_input="The policy routes in table 150 on nat-gw-2 are corrupted after a failed migration. Flush the table so we can start clean.",
       args={"operation": "route_flush", "table": "150"},
       answer="Flushed routing table 150\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0005", tool="routing", operation="route_flush",
       complexity="single",
       user_input="wipe table 300 on decommission-host-1, it's no longer in use",
       args={"operation": "route_flush", "table": "300"},
       answer="Flushed routing table 300\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0006", tool="routing", operation="route_flush",
       complexity="single",
       user_input="flush routing table 50 on mgmt-console-1 before we repopulate it",
       args={"operation": "route_flush", "table": "50"},
       answer="Flushed routing table 50\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0007", tool="routing", operation="route_flush",
       complexity="single",
       user_input="Clear out every entry in table 400 on app-node-4, it was left over from testing.",
       args={"operation": "route_flush", "table": "400"},
       answer="Flushed routing table 400\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0008", tool="routing", operation="route_flush",
       complexity="diagnostic",
       user_input="build-runner-2 keeps sending traffic out the wrong interface via table 120. Just flush that table.",
       args={"operation": "route_flush", "table": "120"},
       answer="Flushed routing table 120\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0009", tool="routing", operation="route_flush",
       complexity="single",
       user_input="flush the local override table 250 on standby-router-1",
       args={"operation": "route_flush", "table": "250"},
       answer="Flushed routing table 250\n0 routes remaining"),
    V2(id="routing-route_flush-v2-0010", tool="routing", operation="route_flush",
       complexity="single",
       user_input="empty routing table 110 on edge-proxy-1 entirely",
       args={"operation": "route_flush", "table": "110"},
       answer="Flushed routing table 110\n0 routes remaining"),

    V2(id="routing-policy_rule_show-v2-0001", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="Show all IP policy rules on multi-homed-srv-1.",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32764: from 10.1.0.0/24 lookup 100\n32766: from all lookup main"),
    V2(id="routing-policy_rule_show-v2-0002", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="what policy routing rules exist on lb-front-4",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main\n32767: from all lookup default"),
    V2(id="routing-policy_rule_show-v2-0003", tool="routing", operation="policy_rule_show",
       complexity="diagnostic",
       user_input="Traffic from 10.1.0.0/24 on app-node-4 is routing incorrectly. Show the policy rules.",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main\n(no rule matches 10.1.0.0/24)"),
    V2(id="routing-policy_rule_show-v2-0004", tool="routing", operation="policy_rule_show",
       complexity="multi",
       user_input="List the policy rules on nat-gw-2 and tell me which ones reference table 100.",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32764: from 10.2.0.0/24 lookup 100\n32766: from all lookup main"),
    V2(id="routing-policy_rule_show-v2-0005", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="I added policy rules yesterday on vpn-gw-2 but I'm not sure they took. List them.",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32765: from 10.8.0.0/16 lookup 50\n32766: from all lookup main"),
    V2(id="routing-policy_rule_show-v2-0006", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="print the ip rule list for host mgmt-console-1",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main\n32767: from all lookup default"),
    V2(id="routing-policy_rule_show-v2-0007", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="show ip rule output on standby-router-1",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main"),
    V2(id="routing-policy_rule_show-v2-0008", tool="routing", operation="policy_rule_show",
       complexity="diagnostic",
       user_input="report-worker-2 replies are going out the wrong interface. Check what policy rules are set up.",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main\n(no source-based rule for report-worker-2 interfaces)"),
    V2(id="routing-policy_rule_show-v2-0009", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="list every policy rule configured on build-runner-2",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32766: from all lookup main\n32767: from all lookup default"),
    V2(id="routing-policy_rule_show-v2-0010", tool="routing", operation="policy_rule_show",
       complexity="single",
       user_input="dump the policy routing rule table on decommission-host-1",
       args={"operation": "policy_rule_show"},
       answer="0: from all lookup local\n32764: from 10.5.0.0/24 lookup 200\n32766: from all lookup main"),

    V2(id="routing-policy_rule_add-v2-0001", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="Add a policy rule on multi-homed-srv-1 to route traffic from 10.1.0.0/24 via table 100.",
       args={"operation": "policy_rule_add", "src": "10.1.0.0/24", "table": "100"},
       answer="Added rule: from 10.1.0.0/24 lookup 100"),
    V2(id="routing-policy_rule_add-v2-0002", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="Create a policy routing rule on nat-gw-2 with priority 200 that sends traffic from 192.168.10.0/24 to table 200.",
       args={"operation": "policy_rule_add", "src": "192.168.10.0/24", "table": "200", "priority": 200},
       answer="Added rule: 200: from 192.168.10.0/24 lookup 200"),
    V2(id="routing-policy_rule_add-v2-0003", tool="routing", operation="policy_rule_add",
       complexity="multi",
       user_input="Add a policy rule on app-node-4 for traffic from 10.2.0.0/24 to use table 150, then verify it appears in the list.",
       args={"operation": "policy_rule_add", "src": "10.2.0.0/24", "table": "150"},
       answer="Added rule: from 10.2.0.0/24 lookup 150"),
    V2(id="routing-policy_rule_add-v2-0004", tool="routing", operation="policy_rule_add",
       complexity="diagnostic",
       user_input="The multi-homed server web-node-2 is sending replies out the wrong interface. Add a policy rule so traffic from 203.0.113.5 uses table 300.",
       args={"operation": "policy_rule_add", "src": "203.0.113.5", "table": "300"},
       answer="Added rule: from 203.0.113.5 lookup 300"),
    V2(id="routing-policy_rule_add-v2-0005", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="Add a policy rule on vpn-gw-2 with priority 100 sending all traffic from the VPN subnet 10.8.0.0/16 to table 50.",
       args={"operation": "policy_rule_add", "src": "10.8.0.0/16", "table": "50", "priority": 100},
       answer="Added rule: 100: from 10.8.0.0/16 lookup 50"),
    V2(id="routing-policy_rule_add-v2-0006", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="insert a policy routing rule on lb-front-4 for traffic destined to 172.16.0.0/12 to look up table 100",
       args={"operation": "policy_rule_add", "dest": "172.16.0.0/12", "table": "100"},
       answer="Added rule: to 172.16.0.0/12 lookup 100"),
    V2(id="routing-policy_rule_add-v2-0007", tool="routing", operation="policy_rule_add",
       complexity="multi",
       user_input="Configure policy routing for the management interface on mgmt-console-1: add a rule for 10.100.0.0/24 with priority 50 pointing to table 200, then show the rules to confirm.",
       args={"operation": "policy_rule_add", "src": "10.100.0.0/24", "table": "200", "priority": 50},
       answer="Added rule: 50: from 10.100.0.0/24 lookup 200"),
    V2(id="routing-policy_rule_add-v2-0008", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="on decommission-host-1 send traffic bound for 10.5.0.0/24 to table 250",
       args={"operation": "policy_rule_add", "dest": "10.5.0.0/24", "table": "250"},
       answer="Added rule: to 10.5.0.0/24 lookup 250"),
    V2(id="routing-policy_rule_add-v2-0009", tool="routing", operation="policy_rule_add",
       complexity="single",
       user_input="add a high priority 10 rule on standby-router-1 for source 10.9.0.0/16 to table 20",
       args={"operation": "policy_rule_add", "src": "10.9.0.0/16", "table": "20", "priority": 10},
       answer="Added rule: 10: from 10.9.0.0/16 lookup 20"),

    V2(id="routing-policy_rule_flush-v2-0001", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="Flush all policy routing rules on multi-homed-srv-1.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0002", tool="routing", operation="policy_rule_flush",
       complexity="diagnostic",
       user_input="The policy rules on nat-gw-2 are in a broken state after a botched config push. Flush them all so I can start over.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0003", tool="routing", operation="policy_rule_flush",
       complexity="multi",
       user_input="Flush all policy rules on app-node-4 and then re-add only the ones we need from the config file.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0004", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="Clear all IP policy rules on vpn-gw-2 as part of decommissioning this host's multi-homed setup.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0005", tool="routing", operation="policy_rule_flush",
       complexity="diagnostic",
       user_input="Something's wrong with the policy routing on lb-front-4 after the last change. Just wipe all the ip rules and let the defaults take over.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0006", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="wipe every ip rule on mgmt-console-1",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0007", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="reset all policy routing rules to defaults on decommission-host-1",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0008", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="clear every custom rule from ip rule on standby-router-1",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0009", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="remove all the policy rules we set up during the multi-homing test on build-runner-2",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0010", tool="routing", operation="policy_rule_flush",
       complexity="diagnostic",
       user_input="edge-proxy-1 is dropping asymmetric routed traffic and the rule list looks like a mess. Flush it.",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
    V2(id="routing-policy_rule_flush-v2-0011", tool="routing", operation="policy_rule_flush",
       complexity="single",
       user_input="strip out all ip rules from report-worker-2 before we rebuild its routing config",
       args={"operation": "policy_rule_flush"},
       answer="Flushed all policy rules\nDefault rules restored: local, main, default"),
]

from finetune.scenarios_v2 import check_module; check_module("routing", SCENARIOS_V2)
