"""finetune/scenarios_v2/rpm.py — corpus v2 scenarios for 'rpm'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="rpm-query_info-v2-0001", tool="rpm", operation="query_info",
       complexity="single",
       user_input="What version of openssl-libs is installed?",
       args={"package": "openssl-libs", "operation": "query_info"},
       answer="Name: openssl-libs\nVersion: 3.0.7\nRelease: 25.el9\nVendor: Rocky Enterprise Software Foundation"),
    V2(id="rpm-query_info-v2-0002", tool="rpm", operation="query_info",
       complexity="diagnostic",
       user_input="A CVE dropped for httpd \u2014 what version do we actually have installed here?",
       args={"package": "httpd", "operation": "query_info"},
       answer="Name: httpd\nVersion: 2.4.57\nRelease: 5.el9\nBuild Date: Fri 12 Jul 2026"),
    V2(id="rpm-query_info-v2-0003", tool="rpm", operation="query_info",
       complexity="single",
       user_input="Give me the full rpm metadata for the kernel package.",
       args={"package": "kernel", "operation": "query_info"},
       answer="Name: kernel\nVersion: 5.14.0\nRelease: 427.el9\nInstall Date: Mon 09 Sep 2026"),
    V2(id="rpm-query_info-v2-0004", tool="rpm", operation="query_info",
       complexity="multi",
       user_input="Check the installed version of curl and tell me if it's older than 7.76.0.",
       args={"package": "curl", "operation": "query_info"},
       answer="Name: curl\nVersion: 7.76.1\nRelease: 26.el9\nnot older than 7.76.0"),
    V2(id="rpm-query_info-v2-0005", tool="rpm", operation="query_info",
       complexity="diagnostic",
       user_input="Compliance is asking when glibc was actually installed on this host \u2014 can you pull that?",
       args={"package": "glibc", "operation": "query_info"},
       answer="Name: glibc\nVersion: 2.34\nRelease: 100.el9\nInstall Date: Wed 03 Jun 2026"),
    V2(id="rpm-query_info-v2-0006", tool="rpm", operation="query_info",
       complexity="single",
       user_input="Who is the vendor for the selinux-policy package?",
       args={"package": "selinux-policy", "operation": "query_info"},
       answer="Name: selinux-policy\nVendor: Rocky Enterprise Software Foundation\nVersion: 38.1.51"),
    V2(id="rpm-query_info-v2-0007", tool="rpm", operation="query_info",
       complexity="diagnostic",
       user_input="Someone flagged openssh-server as potentially vulnerable in the last scan \u2014 check if it's patched.",
       args={"package": "openssh-server", "operation": "query_info"},
       answer="Name: openssh-server\nVersion: 8.7p1\nRelease: 38.el9\nBuild Date: Thu 21 Aug 2026"),
    V2(id="rpm-query_info-v2-0008", tool="rpm", operation="query_info",
       complexity="single",
       user_input="Show the package details for python3.",
       args={"package": "python3", "operation": "query_info"},
       answer="Name: python3\nVersion: 3.9.18\nRelease: 3.el9\nGroup: Development/Languages"),
    V2(id="rpm-query_files-v2-0009", tool="rpm", operation="query_files",
       complexity="single",
       user_input="List every file the nginx package installed.",
       args={"package": "nginx", "operation": "query_files"},
       answer="/etc/nginx/nginx.conf\n/usr/sbin/nginx\n/usr/lib/systemd/system/nginx.service\n47 files"),
    V2(id="rpm-query_files-v2-0010", tool="rpm", operation="query_files",
       complexity="diagnostic",
       user_input="I can't find the httpd binary anywhere \u2014 which files does the httpd package own and where do they live?",
       args={"package": "httpd", "operation": "query_files"},
       answer="/etc/httpd/conf/httpd.conf\n/usr/sbin/httpd\n/usr/lib/systemd/system/httpd.service\n112 files"),
    V2(id="rpm-query_files-v2-0011", tool="rpm", operation="query_files",
       complexity="single",
       user_input="Show me the files that belong to the openssl package.",
       args={"package": "openssl", "operation": "query_files"},
       answer="/usr/bin/openssl\n/etc/pki/tls/openssl.cnf\n14 files"),
    V2(id="rpm-query_files-v2-0012", tool="rpm", operation="query_files",
       complexity="multi",
       user_input="List the files owned by the sudo package and check if /etc/sudoers.d is one of them.",
       args={"package": "sudo", "operation": "query_files"},
       answer="/usr/bin/sudo\n/etc/sudoers\n/etc/sudoers.d\n21 files\n/etc/sudoers.d: present"),
    V2(id="rpm-query_files-v2-0013", tool="rpm", operation="query_files",
       complexity="diagnostic",
       user_input="The /usr/lib64 tree looks bloated after the last update \u2014 which files in it belong to glibc specifically?",
       args={"package": "glibc", "operation": "query_files"},
       answer="/usr/lib64/libc.so.6\n/usr/lib64/ld-linux-x86-64.so.2\n183 files"),
    V2(id="rpm-query_files-v2-0014", tool="rpm", operation="query_files",
       complexity="single",
       user_input="What files does the coreutils package own?",
       args={"package": "coreutils", "operation": "query_files"},
       answer="/usr/bin/ls\n/usr/bin/cp\n/usr/bin/cat\n106 files"),
    V2(id="rpm-query_files-v2-0015", tool="rpm", operation="query_files",
       complexity="diagnostic",
       user_input="The bind zone files aren't loading \u2014 which config paths does the bind package actually ship?",
       args={"package": "bind", "operation": "query_files"},
       answer="/etc/named.conf\n/var/named\n/usr/sbin/named\n38 files"),
    V2(id="rpm-query_files-v2-0016", tool="rpm", operation="query_files",
       complexity="single",
       user_input="Get the file listing for the vim-enhanced package.",
       args={"package": "vim-enhanced", "operation": "query_files"},
       answer="/usr/bin/vim\n/usr/share/vim/vim90\n56 files"),
    V2(id="rpm-query_files-v2-0017", tool="rpm", operation="query_files",
       complexity="diagnostic",
       user_input="The audit team wants proof that no extra binaries got dropped alongside sudo \u2014 confirm exactly what the sudo package installs.",
       args={"package": "sudo", "operation": "query_files"},
       answer="/usr/bin/sudo\n/usr/bin/sudoedit\n/etc/sudoers\n21 files"),
    V2(id="rpm-query_file-v2-0018", tool="rpm", operation="query_file",
       complexity="single",
       user_input="Which package owns /usr/bin/bash?",
       args={"file": "/usr/bin/bash", "operation": "query_file"},
       answer="bash-5.1.8-9.el9"),
    V2(id="rpm-query_file-v2-0019", tool="rpm", operation="query_file",
       complexity="diagnostic",
       user_input="/usr/bin/python3 changed unexpectedly on this box \u2014 find out what package it should belong to.",
       args={"file": "/usr/bin/python3", "operation": "query_file"},
       answer="python3-3.9.18-3.el9"),
    V2(id="rpm-query_file-v2-0020", tool="rpm", operation="query_file",
       complexity="single",
       user_input="What package does /etc/ssh/sshd_config belong to?",
       args={"file": "/etc/ssh/sshd_config", "operation": "query_file"},
       answer="openssh-server-8.7p1-38.el9"),
    V2(id="rpm-query_file-v2-0021", tool="rpm", operation="query_file",
       complexity="multi",
       user_input="Find out which package owns /usr/lib64/libssl.so.3 and then show its full package info.",
       args={"file": "/usr/lib64/libssl.so.3", "operation": "query_file"},
       answer="openssl-libs-3.0.7-25.el9"),
    V2(id="rpm-query_file-v2-0022", tool="rpm", operation="query_file",
       complexity="diagnostic",
       user_input="The audit flagged /etc/pam.d/common-auth as modified \u2014 which package installed it originally?",
       args={"file": "/etc/pam.d/common-auth", "operation": "query_file"},
       answer="pam-1.5.1-19.el9"),
    V2(id="rpm-query_file-v2-0023", tool="rpm", operation="query_file",
       complexity="single",
       user_input="Who owns /usr/sbin/sshd?",
       args={"file": "/usr/sbin/sshd", "operation": "query_file"},
       answer="openssh-server-8.7p1-38.el9"),
    V2(id="rpm-query_file-v2-0024", tool="rpm", operation="query_file",
       complexity="diagnostic",
       user_input="/usr/bin/curl started behaving oddly after a manual copy \u2014 check what package it's actually registered to.",
       args={"file": "/usr/bin/curl", "operation": "query_file"},
       answer="curl-7.76.1-26.el9"),
    V2(id="rpm-query_file-v2-0025", tool="rpm", operation="query_file",
       complexity="single",
       user_input="Which package provides /usr/bin/gpg?",
       args={"file": "/usr/bin/gpg", "operation": "query_file"},
       answer="gnupg2-2.3.3-4.el9"),
    V2(id="rpm-query_file-v2-0026", tool="rpm", operation="query_file",
       complexity="diagnostic",
       user_input="A file integrity alert fired on /etc/nsswitch.conf \u2014 which package is it supposed to belong to?",
       args={"file": "/etc/nsswitch.conf", "operation": "query_file"},
       answer="glibc-2.34-100.el9"),
    V2(id="rpm-verify-v2-0027", tool="rpm", operation="verify",
       complexity="single",
       user_input="Verify the integrity of the openssh-server package.",
       args={"package": "openssh-server", "operation": "verify"},
       answer="..?......  c /etc/ssh/sshd_config\nverification complete"),
    V2(id="rpm-verify-v2-0028", tool="rpm", operation="verify",
       complexity="diagnostic",
       user_input="We think this host may have been compromised \u2014 verify every installed package and show anything that changed.",
       args={"operation": "verify"},
       answer="S.5....T.  c /etc/sudoers\n..?......  /usr/bin/curl\n2 discrepancies out of 1284 packages"),
    V2(id="rpm-verify-v2-0029", tool="rpm", operation="verify",
       complexity="single",
       user_input="Run an integrity check across all installed packages.",
       args={"operation": "verify"},
       answer="no discrepancies found across 1284 packages"),
    V2(id="rpm-verify-v2-0030", tool="rpm", operation="verify",
       complexity="multi",
       user_input="Verify the kernel package and show me any files that differ.",
       args={"package": "kernel", "operation": "verify"},
       answer="..?......  /boot/vmlinuz-5.14.0-427.el9.x86_64\n1 discrepancy"),
    V2(id="rpm-verify-v2-0031", tool="rpm", operation="verify",
       complexity="diagnostic",
       user_input="The compliance scanner says openssl may have been tampered with \u2014 verify it directly.",
       args={"package": "openssl", "operation": "verify"},
       answer="no discrepancies found for openssl"),
    V2(id="rpm-verify-v2-0032", tool="rpm", operation="verify",
       complexity="single",
       user_input="Check if any files in the sudo package have been modified since install.",
       args={"package": "sudo", "operation": "verify"},
       answer="no discrepancies found for sudo"),
    V2(id="rpm-verify-v2-0033", tool="rpm", operation="verify",
       complexity="diagnostic",
       user_input="glibc file sizes look off in the audit log \u2014 verify the package files against the rpm database.",
       args={"package": "glibc", "operation": "verify"},
       answer="S.5....T.  /usr/lib64/libc.so.6\n1 discrepancy"),
    V2(id="rpm-verify-v2-0034", tool="rpm", operation="verify",
       complexity="single",
       user_input="Verify that the httpd package files match what was originally installed.",
       args={"package": "httpd", "operation": "verify"},
       answer="no discrepancies found for httpd"),
    V2(id="rpm-verify-v2-0035", tool="rpm", operation="verify",
       complexity="diagnostic",
       user_input="A file-monitor daemon flagged changes under /etc/named \u2014 verify the bind package to see what actually changed.",
       args={"package": "bind", "operation": "verify"},
       answer="S.5....T.  c /etc/named.conf\n1 discrepancy"),
    V2(id="rpm-checksig-v2-0036", tool="rpm", operation="checksig",
       complexity="single",
       user_input="Verify the GPG signature on /tmp/mypackage-1.0.x86_64.rpm.",
       args={"rpm_file": "/tmp/mypackage-1.0.x86_64.rpm", "operation": "checksig"},
       answer="/tmp/mypackage-1.0.x86_64.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0037", tool="rpm", operation="checksig",
       complexity="diagnostic",
       user_input="A vendor sent us an RPM out of band at /opt/vendor/monitor-3.0.rpm \u2014 check its signature before anyone installs it.",
       args={"rpm_file": "/opt/vendor/monitor-3.0.rpm", "operation": "checksig"},
       answer="/opt/vendor/monitor-3.0.rpm: digests SIGNATURES NOT OK"),
    V2(id="rpm-checksig-v2-0038", tool="rpm", operation="checksig",
       complexity="single",
       user_input="Check if /home/admin/updates/kernel-5.14.0-1.el9.rpm is signed correctly.",
       args={"rpm_file": "/home/admin/updates/kernel-5.14.0-1.el9.rpm", "operation": "checksig"},
       answer="/home/admin/updates/kernel-5.14.0-1.el9.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0039", tool="rpm", operation="checksig",
       complexity="multi",
       user_input="Verify the signature of /tmp/custom-app-2.0.rpm and install it only if it passes.",
       args={"rpm_file": "/tmp/custom-app-2.0.rpm", "operation": "checksig"},
       answer="/tmp/custom-app-2.0.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0040", tool="rpm", operation="checksig",
       complexity="single",
       user_input="Does /var/cache/dnf/updates/openssl-3.0.7.rpm have a valid signature?",
       args={"rpm_file": "/var/cache/dnf/updates/openssl-3.0.7.rpm", "operation": "checksig"},
       answer="/var/cache/dnf/updates/openssl-3.0.7.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0041", tool="rpm", operation="checksig",
       complexity="diagnostic",
       user_input="The security review wants confirmation every RPM in /opt/staging was signed before we deploy \u2014 start with backup-tool-1.4.rpm.",
       args={"rpm_file": "/opt/staging/backup-tool-1.4.rpm", "operation": "checksig"},
       answer="/opt/staging/backup-tool-1.4.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0042", tool="rpm", operation="checksig",
       complexity="single",
       user_input="Check the signature on /tmp/offline-update.rpm.",
       args={"rpm_file": "/tmp/offline-update.rpm", "operation": "checksig"},
       answer="/tmp/offline-update.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0043", tool="rpm", operation="checksig",
       complexity="diagnostic",
       user_input="This RPM was pulled from a mirror that had a cert issue last week \u2014 verify /tmp/mirror-fetch/curl-7.88.rpm before trusting it.",
       args={"rpm_file": "/tmp/mirror-fetch/curl-7.88.rpm", "operation": "checksig"},
       answer="/tmp/mirror-fetch/curl-7.88.rpm: digests SIGNATURES NOT OK"),
    V2(id="rpm-checksig-v2-0044", tool="rpm", operation="checksig",
       complexity="single",
       user_input="Verify /home/deploy/packages/app-release-4.2.rpm's signature.",
       args={"rpm_file": "/home/deploy/packages/app-release-4.2.rpm", "operation": "checksig"},
       answer="/home/deploy/packages/app-release-4.2.rpm: digests signatures OK"),
    V2(id="rpm-checksig-v2-0045", tool="rpm", operation="checksig",
       complexity="diagnostic",
       user_input="We got a batch of RPMs from a contractor drive at /media/usb/patch-set \u2014 check the signature on the first one, security-fix-2.1.rpm.",
       args={"rpm_file": "/media/usb/patch-set/security-fix-2.1.rpm", "operation": "checksig"},
       answer="/media/usb/patch-set/security-fix-2.1.rpm: digests signatures OK"),
    V2(id="rpm-install-v2-0046", tool="rpm", operation="install",
       complexity="single",
       user_input="Install the RPM at /tmp/myapp-1.0.x86_64.rpm.",
       args={"rpm_file": "/tmp/myapp-1.0.x86_64.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nUpdating / installing...\nmyapp-1.0-1.x86_64\n1 package installed"),
    V2(id="rpm-install-v2-0047", tool="rpm", operation="install",
       complexity="diagnostic",
       user_input="dnf can't reach the repo mirror right now and we need /var/cache/kernel-update.rpm on this host immediately \u2014 install it directly.",
       args={"rpm_file": "/var/cache/kernel-update.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nUpdating / installing...\nkernel-update-1.0-1.x86_64\n1 package installed"),
    V2(id="rpm-install-v2-0048", tool="rpm", operation="install",
       complexity="single",
       user_input="Install /home/admin/patches/security-fix-1.2.rpm.",
       args={"rpm_file": "/home/admin/patches/security-fix-1.2.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nsecurity-fix-1.2-1.noarch\n1 package installed"),
    V2(id="rpm-install-v2-0049", tool="rpm", operation="install",
       complexity="multi",
       user_input="Check the signature on /opt/vendor/monitor-3.0.rpm and then install it if the signature is valid.",
       args={"rpm_file": "/opt/vendor/monitor-3.0.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nmonitor-3.0-1.x86_64\n1 package installed"),
    V2(id="rpm-install-v2-0050", tool="rpm", operation="install",
       complexity="single",
       user_input="Install the RPM package sitting at /tmp/newpkg-1.0.rpm.",
       args={"rpm_file": "/tmp/newpkg-1.0.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nnewpkg-1.0-1.x86_64\n1 package installed"),
    V2(id="rpm-install-v2-0051", tool="rpm", operation="install",
       complexity="diagnostic",
       user_input="The app broke right after the last update \u2014 install the original RPM from /backup/app-old.rpm to roll it back.",
       args={"rpm_file": "/backup/app-old.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\napp-old-2.3-1.x86_64\n1 package installed"),
    V2(id="rpm-install-v2-0052", tool="rpm", operation="install",
       complexity="single",
       user_input="Install the offline package at /tmp/offline-update.rpm since this host has no internet access.",
       args={"rpm_file": "/tmp/offline-update.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\noffline-update-1.0-1.noarch\n1 package installed"),
    V2(id="rpm-install-v2-0053", tool="rpm", operation="install",
       complexity="diagnostic",
       user_input="The build image is missing the monitor daemon package entirely and dnf is disabled on this host by policy \u2014 install /opt/monitoring/monitor-2.1.rpm directly.",
       args={"rpm_file": "/opt/monitoring/monitor-2.1.rpm", "operation": "install"},
       answer="Preparing...  ################ [100%]\nmonitor-2.1-1.x86_64\n1 package installed"),
    V2(id="rpm-rpm2cpio-v2-0054", tool="rpm", operation="rpm2cpio",
       complexity="single",
       user_input="Extract the contents of /tmp/mypkg-1.0.x86_64.rpm using rpm2cpio.",
       args={"rpm_file": "/tmp/mypkg-1.0.x86_64.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 2.1MB, 47 entries"),
    V2(id="rpm-rpm2cpio-v2-0055", tool="rpm", operation="rpm2cpio",
       complexity="diagnostic",
       user_input="The rpm database on this host looks corrupted and rpm -e refuses to run \u2014 pull the binary out of /backup/bash-5.1.rpm with rpm2cpio instead.",
       args={"rpm_file": "/backup/bash-5.1.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 1.4MB, 12 entries"),
    V2(id="rpm-rpm2cpio-v2-0056", tool="rpm", operation="rpm2cpio",
       complexity="single",
       user_input="Convert /opt/vendor/monitor-3.0.rpm to cpio format so I can inspect it without installing.",
       args={"rpm_file": "/opt/vendor/monitor-3.0.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 3.8MB, 61 entries"),
    V2(id="rpm-rpm2cpio-v2-0057", tool="rpm", operation="rpm2cpio",
       complexity="multi",
       user_input="Extract /tmp/newapp-2.0.rpm with rpm2cpio and then look at the config file shipped inside it.",
       args={"rpm_file": "/tmp/newapp-2.0.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 900KB, 8 entries"),
    V2(id="rpm-rpm2cpio-v2-0058", tool="rpm", operation="rpm2cpio",
       complexity="single",
       user_input="Pull the cpio archive out of /home/admin/test-package-1.0.noarch.rpm.",
       args={"rpm_file": "/home/admin/test-package-1.0.noarch.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 210KB, 5 entries"),
    V2(id="rpm-rpm2cpio-v2-0059", tool="rpm", operation="rpm2cpio",
       complexity="diagnostic",
       user_input="We need to compare checksums of a file before applying /tmp/security-patch.rpm \u2014 extract its cpio payload first.",
       args={"rpm_file": "/tmp/security-patch.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 640KB, 14 entries"),
    V2(id="rpm-rpm2cpio-v2-0060", tool="rpm", operation="rpm2cpio",
       complexity="single",
       user_input="Run rpm2cpio against /var/cache/dnf/openssl-3.0.7.rpm.",
       args={"rpm_file": "/var/cache/dnf/openssl-3.0.7.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 5.2MB, 22 entries"),
    V2(id="rpm-rpm2cpio-v2-0061", tool="rpm", operation="rpm2cpio",
       complexity="diagnostic",
       user_input="A config file inside the httpd update at /tmp/httpd-2.4.58.rpm needs review before we roll it out \u2014 extract it with rpm2cpio.",
       args={"rpm_file": "/tmp/httpd-2.4.58.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 4.1MB, 118 entries"),
    V2(id="rpm-rpm2cpio-v2-0062", tool="rpm", operation="rpm2cpio",
       complexity="single",
       user_input="Extract the cpio payload from /opt/staging/backup-tool-1.4.rpm.",
       args={"rpm_file": "/opt/staging/backup-tool-1.4.rpm", "operation": "rpm2cpio"},
       answer="cpio archive written to stdout, 1.9MB, 33 entries"),
]

from finetune.scenarios_v2 import check_module; check_module("rpm", SCENARIOS_V2)
