"""finetune/scenarios_v2/rsync.py — corpus v2 scenarios for 'rsync'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="rsync-dry-run-v2-0001", tool="rsync", operation="dry-run",
       complexity="single",
       user_input="Preview what would move if I rsync /srv/gitea/repos/ to /mnt/nas/gitea-backup/.",
       args={"operation": "dry-run", "src": "/srv/gitea/repos/", "dest": "/mnt/nas/gitea-backup/"},
       answer="Would transfer 412 files (3.1 GiB).\nNo changes made (dry run)."),
    V2(id="rsync-dry-run-v2-0002", tool="rsync", operation="dry-run",
       complexity="diagnostic",
       user_input="The nightly job to /backup/app/ looks like it's missing new uploads — what would a sync from /data/app/uploads/ actually pick up?",
       args={"operation": "dry-run", "src": "/data/app/uploads/", "dest": "/backup/app/uploads/"},
       answer="Would transfer 58 files (612 MiB), 3 deletions skipped (dry run).\nNo changes made."),
    V2(id="rsync-dry-run-v2-0003", tool="rsync", operation="dry-run",
       complexity="multi",
       user_input="Do a dry run from /etc/named/ to /backup/named/, then I'll decide if the real sync is worth running.",
       args={"operation": "dry-run", "src": "/etc/named/", "dest": "/backup/named/"},
       answer="Would transfer 9 files (44 KiB).\nNo changes made (dry run)."),
    V2(id="rsync-dry-run-v2-0004", tool="rsync", operation="dry-run",
       complexity="single",
       user_input="What would rsync move copying /var/lib/mysql/ to /mnt/replica/mysql/?",
       args={"operation": "dry-run", "src": "/var/lib/mysql/", "dest": "/mnt/replica/mysql/"},
       answer="Would transfer 214 files (18.4 GiB).\nNo changes made (dry run)."),
    V2(id="rsync-sync-v2-0001", tool="rsync", operation="sync",
       complexity="single",
       user_input="Sync /srv/gitea/repos/ to /mnt/nas/gitea-backup/.",
       args={"operation": "sync", "src": "/srv/gitea/repos/", "dest": "/mnt/nas/gitea-backup/"},
       answer="Transfer complete: 412 files, 3.1 GiB, 0 errors."),
    V2(id="rsync-sync-v2-0002", tool="rsync", operation="sync",
       complexity="diagnostic",
       user_input="node3's disk failed and the replacement is mounted at /mnt/new-disk/ — get the data from node1's /data/ over to it.",
       args={"operation": "sync", "src": "/data/", "dest": "/mnt/new-disk/"},
       answer="Transfer complete: 8402 files, 210 GiB, 0 errors."),
    V2(id="rsync-sync-v2-0003", tool="rsync", operation="sync",
       complexity="single",
       user_input="Copy /home/svc-deploy/ to /mnt/nfs/deploy-backup/.",
       args={"operation": "sync", "src": "/home/svc-deploy/", "dest": "/mnt/nfs/deploy-backup/"},
       answer="Transfer complete: 130 files, 2.4 GiB, 0 errors."),
    V2(id="rsync-sync-v2-0004", tool="rsync", operation="sync",
       complexity="multi",
       user_input="Sync /etc/nginx/ to /backup/nginx/ before I touch the vhost configs, then show me the last few lines of the transfer log.",
       args={"operation": "sync", "src": "/etc/nginx/", "dest": "/backup/nginx/"},
       answer="Transfer complete: 22 files, 108 KiB, 0 errors."),
    V2(id="rsync-sync-delete-v2-0001", tool="rsync", operation="sync-delete",
       complexity="single",
       user_input="Mirror /srv/www/ to /mnt/mirror/www/, deleting anything on the mirror that's no longer at the source.",
       args={"operation": "sync-delete", "src": "/srv/www/", "dest": "/mnt/mirror/www/"},
       answer="Transfer complete: 340 files updated, 12 files deleted, 0 errors."),
    V2(id="rsync-sync-delete-v2-0002", tool="rsync", operation="sync-delete",
       complexity="diagnostic",
       user_input="The DR copy at /dr/app/ has drifted from production — bring /opt/app/ over with deletion so they match exactly.",
       args={"operation": "sync-delete", "src": "/opt/app/", "dest": "/dr/app/"},
       answer="Transfer complete: 88 files updated, 41 files deleted, 0 errors."),
    V2(id="rsync-sync-delete-v2-0003", tool="rsync", operation="sync-delete",
       complexity="single",
       user_input="Sync /etc/ to /backup/etc/ with --delete so the backup exactly reflects the live config.",
       args={"operation": "sync-delete", "src": "/etc/", "dest": "/backup/etc/"},
       answer="Transfer complete: 15 files updated, 2 files deleted, 0 errors."),
    V2(id="rsync-sync-delete-v2-0004", tool="rsync", operation="sync-delete",
       complexity="multi",
       user_input="Mirror /data/releases/ to /mnt/archive/releases/ deleting stale entries, then tell me exactly which files got removed.",
       args={"operation": "sync-delete", "src": "/data/releases/", "dest": "/mnt/archive/releases/"},
       answer="Transfer complete: 5 files updated, 7 files deleted, 0 errors.\nDeleted: release-2026.03.tar.gz, release-2026.04.tar.gz."),
    V2(id="rsync-sync-delete-v2-0005", tool="rsync", operation="sync-delete",
       complexity="single",
       user_input="Keep /nfs/shared/ exactly in sync with /home/shared/, removing files that were deleted from source.",
       args={"operation": "sync-delete", "src": "/home/shared/", "dest": "/nfs/shared/"},
       answer="Transfer complete: 61 files updated, 4 files deleted, 0 errors."),
    V2(id="rsync-sync-delete-v2-0006", tool="rsync", operation="sync-delete",
       complexity="single",
       user_input="Do a full mirror of /backup/db-dumps/ from /data/db-dumps/ with deletion enabled.",
       args={"operation": "sync-delete", "src": "/data/db-dumps/", "dest": "/backup/db-dumps/"},
       answer="Transfer complete: 19 files updated, 6 files deleted, 0 errors."),
    V2(id="rsync-sync-delete-v2-0007", tool="rsync", operation="sync-delete",
       complexity="diagnostic",
       user_input="The offsite volume at /mnt/offsite/www/ has old junk not on the live site anymore — clean it up by mirroring /var/www/ over with delete.",
       args={"operation": "sync-delete", "src": "/var/www/", "dest": "/mnt/offsite/www/"},
       answer="Transfer complete: 220 files updated, 33 files deleted, 0 errors."),
    V2(id="rsync-progress-v2-0001", tool="rsync", operation="progress",
       complexity="single",
       user_input="Estimate the transfer size for copying /srv/media/ to /mnt/archive/media/.",
       args={"operation": "progress", "src": "/srv/media/", "dest": "/mnt/archive/media/"},
       answer="Estimated transfer: 1240 files, 62.7 GiB. No data copied."),
    V2(id="rsync-progress-v2-0002", tool="rsync", operation="progress",
       complexity="diagnostic",
       user_input="The backup window on maintenance night is only 90 minutes — will the /data/warehouse/ to /backup/warehouse/ transfer even fit?",
       args={"operation": "progress", "src": "/data/warehouse/", "dest": "/backup/warehouse/"},
       answer="Estimated transfer: 4102 files, 340 GiB. No data copied.\nAt typical link speed this exceeds a 90-minute window."),
    V2(id="rsync-progress-v2-0003", tool="rsync", operation="progress",
       complexity="single",
       user_input="Get transfer stats for /var/lib/postgresql/ to /backup/postgres/ without copying anything yet.",
       args={"operation": "progress", "src": "/var/lib/postgresql/", "dest": "/backup/postgres/"},
       answer="Estimated transfer: 214 files, 18.4 GiB. No data copied."),
    V2(id="rsync-progress-v2-0004", tool="rsync", operation="progress",
       complexity="multi",
       user_input="Check the rsync stats for /opt/releases/ to /mnt/archive/, then decide if we need to compress before the transfer.",
       args={"operation": "progress", "src": "/opt/releases/", "dest": "/mnt/archive/"},
       answer="Estimated transfer: 76 files, 5.2 GiB. No data copied."),
    V2(id="rsync-progress-v2-0005", tool="rsync", operation="progress",
       complexity="single",
       user_input="How much data would move syncing /home/ to /mnt/backup/home/?",
       args={"operation": "progress", "src": "/home/", "dest": "/mnt/backup/home/"},
       answer="Estimated transfer: 3021 files, 90.1 GiB. No data copied."),
]

from finetune.scenarios_v2 import check_module; check_module("rsync", SCENARIOS_V2)
