"""finetune/scenarios_v2/samba.py — corpus v2 scenarios for 'samba'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="samba-smbd_status-v2-0001", tool="samba", operation="smbd_status",
       complexity="single",
       user_input="Is the file share service up?",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Fri 2026-09-11 08:02:14\nconnected clients: 6"),
    V2(id="samba-smbd_status-v2-0002", tool="samba", operation="smbd_status",
       complexity="diagnostic",
       user_input="Finance says they lost their mapped drive to \\\\fileserver\\reports this morning — check if smbd fell over.",
       args={"operation": "smbd_status"},
       answer="smbd.service: failed (result: exit-code) since Sat 2026-09-13 06:41:02\nconnected clients: 0"),
    V2(id="samba-smbd_status-v2-0003", tool="samba", operation="smbd_status",
       complexity="single",
       user_input="check smbd health",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Thu 2026-09-10 22:15:00\nconnected clients: 3"),
    V2(id="samba-smbd_status-v2-0004", tool="samba", operation="smbd_status",
       complexity="multi",
       user_input="Confirm smbd is running, then pull testparm output to double-check the share config.",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Fri 2026-09-12 09:00:03\nconnected clients: 4"),
    V2(id="samba-smbd_status-v2-0005", tool="samba", operation="smbd_status",
       complexity="single",
       user_input="Is the SMB file service currently serving connections?",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Wed 2026-09-09 11:30:41\nconnected clients: 11"),
    V2(id="samba-smbd_status-v2-0006", tool="samba", operation="smbd_status",
       complexity="diagnostic",
       user_input="A backup job that writes over cifs to the archive share keeps timing out overnight — worth checking whether smbd restarted?",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Sat 2026-09-13 03:12:55\nrestarts today: 2"),
    V2(id="samba-smbd_status-v2-0007", tool="samba", operation="smbd_status",
       complexity="single",
       user_input="give me smbd uptime",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Mon 2026-09-07 07:00:00\nuptime: 6d 3h"),
    V2(id="samba-smbd_status-v2-0008", tool="samba", operation="smbd_status",
       complexity="single",
       user_input="Verify the smbd daemon is alive before I add a new usershare.",
       args={"operation": "smbd_status"},
       answer="smbd.service: active (running) since Fri 2026-09-12 09:00:03\nconnected clients: 4"),
    V2(id="samba-smbd_status-v2-0009", tool="samba", operation="smbd_status",
       complexity="diagnostic",
       user_input="Nobody can browse the file server from Windows Explorer right now — status of the smbd daemon?",
       args={"operation": "smbd_status"},
       answer="smbd.service: failed (result: signal) since Sat 2026-09-13 07:20:11\nconnected clients: 0"),
    V2(id="samba-nmbd_status-v2-0001", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="Is the NetBIOS name service daemon running?",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Fri 2026-09-11 08:02:20\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0002", tool="samba", operation="nmbd_status",
       complexity="diagnostic",
       user_input="Old Windows 7 clients can't find the server by name in Network Neighborhood — check nmbd's state.",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: inactive (dead) since Thu 2026-09-10 20:00:00\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0003", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="check nmbd",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Wed 2026-09-09 11:31:02\nworkgroup: CORP"),
    V2(id="samba-nmbd_status-v2-0004", tool="samba", operation="nmbd_status",
       complexity="multi",
       user_input="Check nmbd status, then restart it if it's dead.",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: inactive (dead) since Sat 2026-09-13 05:00:00\nworkgroup: CORP"),
    V2(id="samba-nmbd_status-v2-0005", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="status of the NetBIOS daemon please",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Mon 2026-09-07 07:00:10\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0006", tool="samba", operation="nmbd_status",
       complexity="diagnostic",
       user_input="Ticket 7712: legacy printer server can't resolve the fileserver hostname over WINS. Is nmbd up?",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Fri 2026-09-12 09:00:12\nworkgroup: CORP"),
    V2(id="samba-nmbd_status-v2-0007", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="is nmbd currently active",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Thu 2026-09-10 22:16:00\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0008", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="Check that the NetBIOS daemon didn't crash overnight.",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Sat 2026-09-13 00:05:00\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0009", tool="samba", operation="nmbd_status",
       complexity="diagnostic",
       user_input="Browsing the workgroup from a Linux client with smbclient -L shows nothing — is nmbd running at all?",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: inactive (dead) since Fri 2026-09-12 18:40:00\nworkgroup: WORKGROUP"),
    V2(id="samba-nmbd_status-v2-0010", tool="samba", operation="nmbd_status",
       complexity="single",
       user_input="nmbd health check",
       args={"operation": "nmbd_status"},
       answer="nmbd.service: active (running) since Wed 2026-09-09 11:31:02\nworkgroup: CORP"),
    V2(id="samba-testparm-v2-0001", tool="samba", operation="testparm",
       complexity="single",
       user_input="Validate the smb.conf syntax.",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nWeak crypto is allowed by default\nno syntax errors"),
    V2(id="samba-testparm-v2-0002", tool="samba", operation="testparm",
       complexity="diagnostic",
       user_input="smbd won't start after I hand-edited smb.conf for a new share — could the config be broken?",
       args={"operation": "testparm"},
       answer="Load smb config files from /etc/samba/smb.conf\nrlimit_max: increasing to 8192\nParams: bad option: unknown parameter 'wor group' in [global]"),
    V2(id="samba-testparm-v2-0003", tool="samba", operation="testparm",
       complexity="single",
       user_input="run testparm",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\nServer role: ROLE_STANDALONE"),
    V2(id="samba-testparm-v2-0004", tool="samba", operation="testparm",
       complexity="multi",
       user_input="Validate the config, then restart smbd if it comes back clean.",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\nServer role: ROLE_STANDALONE"),
    V2(id="samba-testparm-v2-0005", tool="samba", operation="testparm",
       complexity="single",
       user_input="check smb.conf for errors",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\n3 shares defined"),
    V2(id="samba-testparm-v2-0006", tool="samba", operation="testparm",
       complexity="diagnostic",
       user_input="Windows clients get 'network path not found' for the new engineering share — is that share even defined correctly in the config?",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\n[engineering] path = /srv/samba/engineering, valid = yes"),
    V2(id="samba-testparm-v2-0007", tool="samba", operation="testparm",
       complexity="single",
       user_input="sanity check the samba config file",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\nServer role: ROLE_STANDALONE"),
    V2(id="samba-testparm-v2-0008", tool="samba", operation="testparm",
       complexity="single",
       user_input="Does smb.conf parse cleanly right now?",
       args={"operation": "testparm"},
       answer="Loaded services file OK.\nno syntax errors\n4 shares defined"),
    V2(id="samba-testparm-v2-0009", tool="samba", operation="testparm",
       complexity="diagnostic",
       user_input="We just failed over to the DR host and smbd is stuck reloading — check if the copied smb.conf is even valid.",
       args={"operation": "testparm"},
       answer="Load smb config files from /etc/samba/smb.conf\nParams: ERROR: value is boolean but not clean (yes/no): 'workgroup = maybe'"),
    V2(id="samba-smbpasswd_add-v2-0001", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="Add jdoe to the Samba user database.",
       args={"operation": "smbpasswd_add", "username": "jdoe"},
       answer="smbpasswd: added user jdoe\nsmbpasswd db entries: 14"),
    V2(id="samba-smbpasswd_add-v2-0002", tool="samba", operation="smbpasswd_add",
       complexity="diagnostic",
       user_input="New hire mreyes has a Linux account but can't authenticate to the file share from her laptop — does she need a Samba password entry?",
       args={"operation": "smbpasswd_add", "username": "mreyes", "password": "Tr0ub4dor&3"},
       answer="smbpasswd: added user mreyes\nsmbpasswd db entries: 15"),
    V2(id="samba-smbpasswd_add-v2-0003", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="create a samba account for tlin with password Winter2026!",
       args={"operation": "smbpasswd_add", "username": "tlin", "password": "Winter2026!"},
       answer="smbpasswd: added user tlin\nsmbpasswd db entries: 16"),
    V2(id="samba-smbpasswd_add-v2-0004", tool="samba", operation="smbpasswd_add",
       complexity="multi",
       user_input="Add user kpatel to Samba, then set up a usershare she can write to.",
       args={"operation": "smbpasswd_add", "username": "kpatel"},
       answer="smbpasswd: added user kpatel\nsmbpasswd db entries: 17"),
    V2(id="samba-smbpasswd_add-v2-0005", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="onboard svc_backup as a samba user",
       args={"operation": "smbpasswd_add", "username": "svc_backup"},
       answer="smbpasswd: added user svc_backup\nsmbpasswd db entries: 18"),
    V2(id="samba-smbpasswd_add-v2-0006", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="Give rfoster a Samba login.",
       args={"operation": "smbpasswd_add", "username": "rfoster"},
       answer="smbpasswd: added user rfoster\nsmbpasswd db entries: 19"),
    V2(id="samba-smbpasswd_add-v2-0007", tool="samba", operation="smbpasswd_add",
       complexity="diagnostic",
       user_input="Ticket 9021: contractor dwhite gets 'access denied' mounting the share even though their system account works fine — probably missing from smbpasswd?",
       args={"operation": "smbpasswd_add", "username": "dwhite"},
       answer="smbpasswd: added user dwhite\nsmbpasswd db entries: 20"),
    V2(id="samba-smbpasswd_add-v2-0008", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="add samba credentials for user ngomez",
       args={"operation": "smbpasswd_add", "username": "ngomez", "password": "Sp1ral0ut!"},
       answer="smbpasswd: added user ngomez\nsmbpasswd db entries: 21"),
    V2(id="samba-smbpasswd_add-v2-0009", tool="samba", operation="smbpasswd_add",
       complexity="single",
       user_input="register bchen in the samba user db",
       args={"operation": "smbpasswd_add", "username": "bchen"},
       answer="smbpasswd: added user bchen\nsmbpasswd db entries: 22"),
    V2(id="samba-smbpasswd_delete-v2-0001", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="Remove jdoe from the Samba user database.",
       args={"operation": "smbpasswd_delete", "username": "jdoe"},
       answer="smbpasswd: deleted user jdoe\nsmbpasswd db entries: 21"),
    V2(id="samba-smbpasswd_delete-v2-0002", tool="samba", operation="smbpasswd_delete",
       complexity="diagnostic",
       user_input="A contractor's engagement ended last week but their laptop still has drive letters mapped to our share — should we pull their samba account, dwhite?",
       args={"operation": "smbpasswd_delete", "username": "dwhite"},
       answer="smbpasswd: deleted user dwhite\nsmbpasswd db entries: 20"),
    V2(id="samba-smbpasswd_delete-v2-0003", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="drop the samba login for tlin",
       args={"operation": "smbpasswd_delete", "username": "tlin"},
       answer="smbpasswd: deleted user tlin\nsmbpasswd db entries: 19"),
    V2(id="samba-smbpasswd_delete-v2-0004", tool="samba", operation="smbpasswd_delete",
       complexity="multi",
       user_input="Delete kpatel's samba access, then remove her usershare too.",
       args={"operation": "smbpasswd_delete", "username": "kpatel"},
       answer="smbpasswd: deleted user kpatel\nsmbpasswd db entries: 18"),
    V2(id="samba-smbpasswd_delete-v2-0005", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="revoke svc_backup's samba credentials",
       args={"operation": "smbpasswd_delete", "username": "svc_backup"},
       answer="smbpasswd: deleted user svc_backup\nsmbpasswd db entries: 17"),
    V2(id="samba-smbpasswd_delete-v2-0006", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="Take rfoster out of the samba user db.",
       args={"operation": "smbpasswd_delete", "username": "rfoster"},
       answer="smbpasswd: deleted user rfoster\nsmbpasswd db entries: 16"),
    V2(id="samba-smbpasswd_delete-v2-0007", tool="samba", operation="smbpasswd_delete",
       complexity="diagnostic",
       user_input="HR flagged mreyes' account for immediate offboarding — does that include cutting off her file share access?",
       args={"operation": "smbpasswd_delete", "username": "mreyes"},
       answer="smbpasswd: deleted user mreyes\nsmbpasswd db entries: 15"),
    V2(id="samba-smbpasswd_delete-v2-0008", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="delete ngomez from smbpasswd",
       args={"operation": "smbpasswd_delete", "username": "ngomez"},
       answer="smbpasswd: deleted user ngomez\nsmbpasswd db entries: 14"),
    V2(id="samba-smbpasswd_delete-v2-0009", tool="samba", operation="smbpasswd_delete",
       complexity="single",
       user_input="remove bchen's samba account entirely",
       args={"operation": "smbpasswd_delete", "username": "bchen"},
       answer="smbpasswd: deleted user bchen\nsmbpasswd db entries: 13"),
    V2(id="samba-usershare_list-v2-0001", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="List all the current usershares.",
       args={"operation": "usershare_list"},
       answer="engineering -> /srv/samba/engineering\narchive -> /srv/samba/archive\nfinance -> /srv/samba/finance"),
    V2(id="samba-usershare_list-v2-0002", tool="samba", operation="usershare_list",
       complexity="diagnostic",
       user_input="Someone said a share called 'legal-docs' used to exist and now it's gone from the network — can you check what usershares are defined?",
       args={"operation": "usershare_list"},
       answer="engineering -> /srv/samba/engineering\narchive -> /srv/samba/archive\n(no share named legal-docs)"),
    V2(id="samba-usershare_list-v2-0003", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="show current shares",
       args={"operation": "usershare_list"},
       answer="finance -> /srv/samba/finance\nhr -> /srv/samba/hr"),
    V2(id="samba-usershare_list-v2-0004", tool="samba", operation="usershare_list",
       complexity="multi",
       user_input="List usershares, then add one more for the new marketing team.",
       args={"operation": "usershare_list"},
       answer="engineering -> /srv/samba/engineering\narchive -> /srv/samba/archive\nfinance -> /srv/samba/finance"),
    V2(id="samba-usershare_list-v2-0005", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="what shares exist on this server",
       args={"operation": "usershare_list"},
       answer="engineering -> /srv/samba/engineering\nhr -> /srv/samba/hr\nfinance -> /srv/samba/finance"),
    V2(id="samba-usershare_list-v2-0006", tool="samba", operation="usershare_list",
       complexity="diagnostic",
       user_input="A user can browse the server in Explorer but sees no folders at all — are any usershares even configured?",
       args={"operation": "usershare_list"},
       answer="(no usershares defined)"),
    V2(id="samba-usershare_list-v2-0007", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="print the usershare list",
       args={"operation": "usershare_list"},
       answer="archive -> /srv/samba/archive\nengineering -> /srv/samba/engineering"),
    V2(id="samba-usershare_list-v2-0008", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="Can you enumerate the usershares configured right now?",
       args={"operation": "usershare_list"},
       answer="finance -> /srv/samba/finance\nhr -> /srv/samba/hr\narchive -> /srv/samba/archive"),
    V2(id="samba-usershare_list-v2-0009", tool="samba", operation="usershare_list",
       complexity="diagnostic",
       user_input="Ticket 5560: engineering says their project share vanished after the weekend maintenance — what usershares remain?",
       args={"operation": "usershare_list"},
       answer="archive -> /srv/samba/archive\nfinance -> /srv/samba/finance\n(no share named engineering)"),
    V2(id="samba-usershare_list-v2-0010", tool="samba", operation="usershare_list",
       complexity="single",
       user_input="list the file shares samba is exposing",
       args={"operation": "usershare_list"},
       answer="engineering -> /srv/samba/engineering\narchive -> /srv/samba/archive\nfinance -> /srv/samba/finance\nhr -> /srv/samba/hr"),
    V2(id="samba-usershare_add-v2-0001", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="Create a usershare called marketing pointing at /srv/samba/marketing.",
       args={"operation": "usershare_add", "name": "marketing", "path": "/srv/samba/marketing"},
       answer="usershare added: marketing -> /srv/samba/marketing\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0002", tool="samba", operation="usershare_add",
       complexity="diagnostic",
       user_input="The new engineering project folder at /srv/samba/proj-orion has no way for Windows users to reach it over the network — can we expose it as a share?",
       args={"operation": "usershare_add", "name": "proj-orion", "path": "/srv/samba/proj-orion", "comment": "Project Orion working files"},
       answer="usershare added: proj-orion -> /srv/samba/proj-orion\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0003", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="add a share named legal-docs at /srv/samba/legal with full access for everyone",
       args={"operation": "usershare_add", "name": "legal-docs", "path": "/srv/samba/legal", "acl": "Everyone:F"},
       answer="usershare added: legal-docs -> /srv/samba/legal\nacl: Everyone:F"),
    V2(id="samba-usershare_add-v2-0004", tool="samba", operation="usershare_add",
       complexity="multi",
       user_input="Set up a usershare for hr at /srv/samba/hr, then add kpatel's samba login so she can access it.",
       args={"operation": "usershare_add", "name": "hr", "path": "/srv/samba/hr", "comment": "HR shared documents"},
       answer="usershare added: hr -> /srv/samba/hr\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0005", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="publish /srv/samba/finance as a share named finance",
       args={"operation": "usershare_add", "name": "finance", "path": "/srv/samba/finance"},
       answer="usershare added: finance -> /srv/samba/finance\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0006", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="Create the archive usershare at /mnt/archive with full access.",
       args={"operation": "usershare_add", "name": "archive", "path": "/mnt/archive", "acl": "Everyone:F"},
       answer="usershare added: archive -> /mnt/archive\nacl: Everyone:F"),
    V2(id="samba-usershare_add-v2-0007", tool="samba", operation="usershare_add",
       complexity="diagnostic",
       user_input="Backups land in /srv/backups/weekly but there's no way to browse them from a Windows workstation — is a share the fix?",
       args={"operation": "usershare_add", "name": "weekly-backups", "path": "/srv/backups/weekly", "comment": "Read-only weekly backup archive"},
       answer="usershare added: weekly-backups -> /srv/backups/weekly\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0008", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="share out /srv/samba/design as 'design-team'",
       args={"operation": "usershare_add", "name": "design-team", "path": "/srv/samba/design"},
       answer="usershare added: design-team -> /srv/samba/design\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0009", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="Add a new usershare named scratch at /srv/samba/scratch, comment it as temp workspace.",
       args={"operation": "usershare_add", "name": "scratch", "path": "/srv/samba/scratch", "comment": "temp workspace"},
       answer="usershare added: scratch -> /srv/samba/scratch\nacl: default (Everyone:R)"),
    V2(id="samba-usershare_add-v2-0010", tool="samba", operation="usershare_add",
       complexity="single",
       user_input="expose /srv/samba/ops as an ops usershare with full access",
       args={"operation": "usershare_add", "name": "ops", "path": "/srv/samba/ops", "acl": "Everyone:F"},
       answer="usershare added: ops -> /srv/samba/ops\nacl: Everyone:F"),
]

from finetune.scenarios_v2 import check_module; check_module("samba", SCENARIOS_V2)
