"""finetune/scenarios_v2/selinux.py -- corpus v2 scenarios for 'selinux'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(
        id='selinux-sestatus-v2-0001',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='Give me the overall SELinux status on this host.',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nMode from config file: enforcing\nPolicy MLS status: enabled\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0002',
        tool='selinux',
        operation='sestatus',
        complexity='diagnostic',
        user_input='httpd keeps getting permission denied on a socket connect — first check whether SELinux is even enforcing here.',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0003',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='sestatus',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: permissive\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0004',
        tool='selinux',
        operation='sestatus',
        complexity='diagnostic',
        user_input='A vendor app install failed with an odd file access error — is SELinux enforcing on this box?',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0005',
        tool='selinux',
        operation='sestatus',
        complexity='multi',
        user_input="Check the SELinux status, then pull up the recent denials if it's enforcing.",
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0006',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='What policy type and mode is this system running under?',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: mls',
    ),
    V2(
        id='selinux-sestatus-v2-0007',
        tool='selinux',
        operation='sestatus',
        complexity='diagnostic',
        user_input="The nftables ruleset looks fine but the service still can't bind its port — could SELinux be the culprit here?",
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0008',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='Show me the SELinux status summary for the change record.',
        args={'operation': 'sestatus'},
        answer='SELinux status: disabled',
    ),
    V2(
        id='selinux-sestatus-v2-0009',
        tool='selinux',
        operation='sestatus',
        complexity='diagnostic',
        user_input='A container runtime is throwing avc-style errors — confirm SELinux is active before we dig further.',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0010',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='Is SELinux disabled, permissive, or enforcing right now?',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: permissive\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0011',
        tool='selinux',
        operation='sestatus',
        complexity='multi',
        user_input="Get the current SELinux mode, then I'll decide whether to flip it to permissive for testing.",
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0012',
        tool='selinux',
        operation='sestatus',
        complexity='single',
        user_input='Pull the full sestatus output.',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nMode from config file: enforcing\nPolicy MLS status: enabled\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-sestatus-v2-0013',
        tool='selinux',
        operation='sestatus',
        complexity='diagnostic',
        user_input='Before opening a ticket on the samba share denial, check the current SELinux enforcement state.',
        args={'operation': 'sestatus'},
        answer='SELinux status: enabled\nCurrent mode: enforcing\nPolicy from config file: targeted',
    ),
    V2(
        id='selinux-getsebool-v2-0014',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input='Is httpd_can_network_connect turned on?',
        args={'operation': 'getsebool', 'boolean': 'httpd_can_network_connect'},
        answer='httpd_can_network_connect --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0015',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input='Sendmail from a cron script is silently failing — check if httpd_can_sendmail is enabled.',
        args={'operation': 'getsebool', 'boolean': 'httpd_can_sendmail'},
        answer='httpd_can_sendmail --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0016',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input='getsebool samba_export_all_rw',
        args={'operation': 'getsebool', 'boolean': 'samba_export_all_rw'},
        answer='samba_export_all_rw --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0017',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input="Users can't upload via the FTP daemon and there's nothing in vsftpd's own config that would block it — check the ftpd_full_access boolean.",
        args={'operation': 'getsebool', 'boolean': 'ftpd_full_access'},
        answer='ftpd_full_access --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0018',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input="What's the current value of nis_enabled?",
        args={'operation': 'getsebool', 'boolean': 'nis_enabled'},
        answer='nis_enabled --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0019',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input="A reverse proxy config change isn't taking effect and network policy looks fine — check httpd_can_network_relay.",
        args={'operation': 'getsebool', 'boolean': 'httpd_can_network_relay'},
        answer='httpd_can_network_relay --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0020',
        tool='selinux',
        operation='getsebool',
        complexity='multi',
        user_input="Check the cron_can_relabel boolean, then I'll decide whether to flip it.",
        args={'operation': 'getsebool', 'boolean': 'cron_can_relabel'},
        answer='cron_can_relabel --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0021',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input='Check whether virt_use_nfs is on for the KVM host.',
        args={'operation': 'getsebool', 'boolean': 'virt_use_nfs'},
        answer='virt_use_nfs --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0022',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input='The app can reach the database over the network but SELinux logs show denials — check sshd_can_network_connect_db.',
        args={'operation': 'getsebool', 'boolean': 'sshd_can_network_connect_db'},
        answer='sshd_can_network_connect_db --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0023',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input='Show the current state of httpd_enable_cgi.',
        args={'operation': 'getsebool', 'boolean': 'httpd_enable_cgi'},
        answer='httpd_enable_cgi --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0024',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input='Zone transfers to a secondary DNS server are failing — check if named_write_master_zones is enabled.',
        args={'operation': 'getsebool', 'boolean': 'named_write_master_zones'},
        answer='named_write_master_zones --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0025',
        tool='selinux',
        operation='getsebool',
        complexity='single',
        user_input='getsebool -a | grep postgresql_can_rsync — well, just tell me its value.',
        args={'operation': 'getsebool', 'boolean': 'postgresql_can_rsync'},
        answer='postgresql_can_rsync --> off',
    ),
    V2(
        id='selinux-getsebool-v2-0026',
        tool='selinux',
        operation='getsebool',
        complexity='diagnostic',
        user_input="A confined domain can't mmap a shared file it needs — check domain_can_mmap_files.",
        args={'operation': 'getsebool', 'boolean': 'domain_can_mmap_files'},
        answer='domain_can_mmap_files --> off',
    ),
    V2(
        id='selinux-getenforce-v2-0027',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='What mode is SELinux in right now?',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0028',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input='A file copy into /var/www is being silently blocked — quick check, is SELinux enforcing?',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0029',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='getenforce',
        args={'operation': 'getenforce'},
        answer='Permissive',
    ),
    V2(
        id='selinux-getenforce-v2-0030',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input="The developer says 'it works with SELinux off' — verify what mode we're actually in before believing that.",
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0031',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='Just the enforcement mode, one word.',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0032',
        tool='selinux',
        operation='getenforce',
        complexity='multi',
        user_input="Check the current enforcement mode, then I'll set it back to enforcing if it's not.",
        args={'operation': 'getenforce'},
        answer='Permissive',
    ),
    V2(
        id='selinux-getenforce-v2-0033',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input='A newly restored VM is behaving oddly with file permissions — check if it somehow booted in permissive mode.',
        args={'operation': 'getenforce'},
        answer='Permissive',
    ),
    V2(
        id='selinux-getenforce-v2-0034',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='Confirm SELinux mode for the audit checklist.',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0035',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input="The support ticket claims 'selinux is disabled' — verify that claim.",
        args={'operation': 'getenforce'},
        answer='Disabled',
    ),
    V2(
        id='selinux-getenforce-v2-0036',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='Is the box enforcing or permissive at the moment?',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0037',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input="A test box was left in a weird state after a debugging session last week — check what mode it's currently in.",
        args={'operation': 'getenforce'},
        answer='Permissive',
    ),
    V2(
        id='selinux-getenforce-v2-0038',
        tool='selinux',
        operation='getenforce',
        complexity='single',
        user_input='What does getenforce report on this host?',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0039',
        tool='selinux',
        operation='getenforce',
        complexity='multi',
        user_input='Check the enforcement mode first, then run sestatus for the full picture.',
        args={'operation': 'getenforce'},
        answer='Enforcing',
    ),
    V2(
        id='selinux-getenforce-v2-0040',
        tool='selinux',
        operation='getenforce',
        complexity='diagnostic',
        user_input="A denial we expected to see in the audit log isn't showing up at all — check whether the box is actually enforcing.",
        args={'operation': 'getenforce'},
        answer='Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0041',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='Set SELinux to enforcing mode right now.',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0042',
        tool='selinux',
        operation='setenforce',
        complexity='diagnostic',
        user_input='We need to rule SELinux in or out as the cause of this denial — temporarily drop it to permissive.',
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0043',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='setenforce 1',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0044',
        tool='selinux',
        operation='setenforce',
        complexity='multi',
        user_input='Set enforcing mode, then run sestatus to confirm it stuck.',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0045',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='Switch to permissive mode for this debugging session.',
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0046',
        tool='selinux',
        operation='setenforce',
        complexity='diagnostic',
        user_input='A previous engineer left this box in permissive mode after testing — put it back to enforcing.',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0047',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='setenforce 0',
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0048',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input="Flip enforcement back on, we're done testing.",
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0049',
        tool='selinux',
        operation='setenforce',
        complexity='diagnostic',
        user_input="The vendor's installer refuses to proceed under enforcing SELinux — set it to permissive just for the install.",
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0050',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='Runtime enforcement mode should be enforcing on this host — set it.',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0051',
        tool='selinux',
        operation='setenforce',
        complexity='multi',
        user_input="Set the runtime mode to permissive, then I'll retry the failing operation.",
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setenforce-v2-0052',
        tool='selinux',
        operation='setenforce',
        complexity='single',
        user_input='Turn enforcing back on immediately after the test window closes.',
        args={'operation': 'setenforce', 'mode': '1'},
        answer='Enforcement mode set to: Enforcing',
    ),
    V2(
        id='selinux-setenforce-v2-0053',
        tool='selinux',
        operation='setenforce',
        complexity='diagnostic',
        user_input="We can't tell if a network policy issue or SELinux is blocking the connection — set permissive to isolate it.",
        args={'operation': 'setenforce', 'mode': '0'},
        answer='Enforcement mode set to: Permissive',
    ),
    V2(
        id='selinux-setsebool-v2-0054',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='Turn on httpd_can_network_connect and make it persist across reboots.',
        args={'operation': 'setsebool', 'boolean': 'httpd_can_network_connect', 'value': 'on', 'persist': True},
        answer='httpd_can_network_connect --> on  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0055',
        tool='selinux',
        operation='setsebool',
        complexity='diagnostic',
        user_input="A PHP app can't send outbound mail through sendmail — enable httpd_can_sendmail.",
        args={'operation': 'setsebool', 'boolean': 'httpd_can_sendmail', 'value': 'on'},
        answer='httpd_can_sendmail --> on',
    ),
    V2(
        id='selinux-setsebool-v2-0056',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input="Disable samba_export_all_rw permanently, we're locking that down.",
        args={'operation': 'setsebool', 'boolean': 'samba_export_all_rw', 'value': 'off', 'persist': True},
        answer='samba_export_all_rw --> off  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0057',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='setsebool ftpd_full_access on -P',
        args={'operation': 'setsebool', 'boolean': 'ftpd_full_access', 'value': 'on', 'persist': True},
        answer='ftpd_full_access --> on  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0058',
        tool='selinux',
        operation='setsebool',
        complexity='diagnostic',
        user_input="We're decommissioning NIS — turn off nis_enabled for now, just for this session.",
        args={'operation': 'setsebool', 'boolean': 'nis_enabled', 'value': 'off'},
        answer='nis_enabled --> off',
    ),
    V2(
        id='selinux-setsebool-v2-0059',
        tool='selinux',
        operation='setsebool',
        complexity='multi',
        user_input='Enable httpd_can_network_relay persistently, then restart httpd.',
        args={'operation': 'setsebool', 'boolean': 'httpd_can_network_relay', 'value': 'on', 'persist': True},
        answer='httpd_can_network_relay --> on  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0060',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='Turn off cron_can_relabel.',
        args={'operation': 'setsebool', 'boolean': 'cron_can_relabel', 'value': 'off'},
        answer='cron_can_relabel --> off',
    ),
    V2(
        id='selinux-setsebool-v2-0061',
        tool='selinux',
        operation='setsebool',
        complexity='diagnostic',
        user_input="Libvirt guests can't mount their NFS-backed storage — enable virt_use_nfs and persist it.",
        args={'operation': 'setsebool', 'boolean': 'virt_use_nfs', 'value': 'on', 'persist': True},
        answer='virt_use_nfs --> on  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0062',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='Enable CGI execution for httpd for this session.',
        args={'operation': 'setsebool', 'boolean': 'httpd_enable_cgi', 'value': 'on'},
        answer='httpd_enable_cgi --> on',
    ),
    V2(
        id='selinux-setsebool-v2-0063',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='Allow named to write master zones and keep it after reboot.',
        args={'operation': 'setsebool', 'boolean': 'named_write_master_zones', 'value': 'on', 'persist': True},
        answer='named_write_master_zones --> on  (persisted)',
    ),
    V2(
        id='selinux-setsebool-v2-0064',
        tool='selinux',
        operation='setsebool',
        complexity='diagnostic',
        user_input='A database replication script using rsync keeps getting denied — enable postgresql_can_rsync.',
        args={'operation': 'setsebool', 'boolean': 'postgresql_can_rsync', 'value': 'on'},
        answer='postgresql_can_rsync --> on',
    ),
    V2(
        id='selinux-setsebool-v2-0065',
        tool='selinux',
        operation='setsebool',
        complexity='single',
        user_input='Disable domain_can_mmap_files persistently per the hardening checklist.',
        args={'operation': 'setsebool', 'boolean': 'domain_can_mmap_files', 'value': 'off', 'persist': True},
        answer='domain_can_mmap_files --> off  (persisted)',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0066',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='List every file context mapping defined on this system.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0067',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='diagnostic',
        user_input="A custom web root isn't getting labeled right after restorecon — check the existing fcontext mappings for anything conflicting.",
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0068',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='semanage fcontext -l',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0069',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='multi',
        user_input="List the file context mappings, then I'll add one for our new content directory.",
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0070',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='diagnostic',
        user_input='Static files in a nonstandard directory keep losing their label after every deploy — see what mappings currently exist.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0071',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='Show all fcontext rules.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0072',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='diagnostic',
        user_input='Before adding a new mapping for /opt/appdata, check whether one already covers that path.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0073',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='Give me the full list of SELinux file context definitions.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0074',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='multi',
        user_input='Pull the fcontext list, then delete the stale one for the old /srv/legacy path.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0075',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='What file contexts are currently mapped?',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0076',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='diagnostic',
        user_input='The compliance audit wants a dump of every custom file labeling rule on this host.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0077',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='List fcontext mappings for the audit report.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0078',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='diagnostic',
        user_input='A new mount point is inheriting the wrong type — check the fcontext table for anything relevant.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_list-v2-0079',
        tool='selinux',
        operation='semanage_fcontext_list',
        complexity='single',
        user_input='Show me the semanage file context table.',
        args={'operation': 'semanage_fcontext_list'},
        answer='/srv/www(/.*)?                    httpd_sys_content_t\n/opt/appdata(/.*)?                 var_t\n/data/uploads(/.*)?                public_content_rw_t\n3 local customizations',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0080',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Label everything under /srv/www as httpd_sys_content_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'httpd_sys_content_t', 'fcontext_spec': '/srv/www(/.*)?'},
        answer='Added file context: /srv/www(/.*)?  ->  httpd_sys_content_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0081',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='diagnostic',
        user_input='Uploads to /data/uploads keep getting denied by httpd — add a proper fcontext mapping for it.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'public_content_rw_t', 'fcontext_spec': '/data/uploads(/.*)?'},
        answer='Added file context: /data/uploads(/.*)?  ->  public_content_rw_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0082',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input="semanage fcontext -a -t httpd_sys_rw_content_t '/srv/app/writable(/.*)?'",
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'httpd_sys_rw_content_t', 'fcontext_spec': '/srv/app/writable(/.*)?'},
        answer='Added file context: /srv/app/writable(/.*)?  ->  httpd_sys_rw_content_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0083',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='multi',
        user_input='Add a file context mapping for the custom log directory, then run restorecon on it.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'var_log_t', 'fcontext_spec': '/opt/customapp/logs(/.*)?'},
        answer='Added file context: /opt/customapp/logs(/.*)?  ->  var_log_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0084',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Map /opt/tools/bin as bin_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'bin_t', 'fcontext_spec': '/opt/tools/bin(/.*)?'},
        answer='Added file context: /opt/tools/bin(/.*)?  ->  bin_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0085',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='diagnostic',
        user_input='A newly mounted content volume is serving 403s from apache — add the right fcontext label for it.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'httpd_sys_content_t', 'fcontext_spec': '/mnt/webcontent(/.*)?'},
        answer='Added file context: /mnt/webcontent(/.*)?  ->  httpd_sys_content_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0086',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Add a context mapping so /opt/appdata/certs gets labeled cert_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'cert_t', 'fcontext_spec': '/opt/appdata/certs(/.*)?'},
        answer='Added file context: /opt/appdata/certs(/.*)?  ->  cert_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0087',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='diagnostic',
        user_input='The Samba share at /srv/samba/shared keeps losing its correct label after every reboot — add a persistent fcontext rule.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'samba_share_t', 'fcontext_spec': '/srv/samba/shared(/.*)?'},
        answer='Added file context: /srv/samba/shared(/.*)?  ->  samba_share_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0088',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Set the context for /data/pgdata to postgresql_db_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'postgresql_db_t', 'fcontext_spec': '/data/pgdata(/.*)?'},
        answer='Added file context: /data/pgdata(/.*)?  ->  postgresql_db_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0089',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Map /srv/containers as container_file_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'container_file_t', 'fcontext_spec': '/srv/containers(/.*)?'},
        answer='Added file context: /srv/containers(/.*)?  ->  container_file_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0090',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='diagnostic',
        user_input='A stateful service directory keeps getting mislabeled after restorecon runs — add a proper fcontext entry so it sticks.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'var_lib_t', 'fcontext_spec': '/opt/customapp/state(/.*)?'},
        answer='Added file context: /opt/customapp/state(/.*)?  ->  var_lib_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0091',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='single',
        user_input='Add /srv/static-assets(/.*)? as httpd_sys_content_t.',
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'httpd_sys_content_t', 'fcontext_spec': '/srv/static-assets(/.*)?'},
        answer='Added file context: /srv/static-assets(/.*)?  ->  httpd_sys_content_t',
    ),
    V2(
        id='selinux-semanage_fcontext_add-v2-0092',
        tool='selinux',
        operation='semanage_fcontext_add',
        complexity='diagnostic',
        user_input="Files under the new NFS mount aren't accessible to confined services — add an fcontext mapping for the mount point.",
        args={'operation': 'semanage_fcontext_add', 'fcontext_type': 'nfs_t', 'fcontext_spec': '/mnt/nfs-share(/.*)?'},
        answer='Added file context: /mnt/nfs-share(/.*)?  ->  nfs_t',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0093',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input='Remove the leftover fcontext mapping for /srv/legacy.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/srv/legacy(/.*)?'},
        answer='Removed file context mapping: /srv/legacy(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0094',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='diagnostic',
        user_input='A decommissioned app directory still has a custom fcontext rule cluttering the table — clean it up.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/opt/oldapp(/.*)?'},
        answer='Removed file context mapping: /opt/oldapp(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0095',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input="semanage fcontext -d '/data/tmp-import(/.*)?'",
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/data/tmp-import(/.*)?'},
        answer='Removed file context mapping: /data/tmp-import(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0096',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='multi',
        user_input="Delete the staging directory's fcontext mapping, then list the table to confirm it's gone.",
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/srv/staging(/.*)?'},
        answer='Removed file context mapping: /srv/staging(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0097',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input='Delete the fcontext entry for /mnt/old-nfs.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/mnt/old-nfs(/.*)?'},
        answer='Removed file context mapping: /mnt/old-nfs(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0098',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='diagnostic',
        user_input='The migration checklist says remove all leftover labeling rules for the decommissioned app path.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/opt/decommissioned/app(/.*)?'},
        answer='Removed file context mapping: /opt/decommissioned/app(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0099',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input='Remove the mapping for /srv/test-content.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/srv/test-content(/.*)?'},
        answer='Removed file context mapping: /srv/test-content(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0100',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input='Delete fcontext rule for /data/scratch.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/data/scratch(/.*)?'},
        answer='Removed file context mapping: /data/scratch(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0101',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='diagnostic',
        user_input='An old vendor install left a custom fcontext rule that now conflicts with the new install — remove it.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/opt/vendor-old(/.*)?'},
        answer='Removed file context mapping: /opt/vendor-old(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0102',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input='Remove the file context mapping tied to /srv/backup-mount.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/srv/backup-mount(/.*)?'},
        answer='Removed file context mapping: /srv/backup-mount(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0103',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='diagnostic',
        user_input='A volume was unmounted and decommissioned last week but its fcontext rule is still there — delete it.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/mnt/removed-volume(/.*)?'},
        answer='Removed file context mapping: /mnt/removed-volume(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0104',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='multi',
        user_input="Delete the v1 app path's fcontext mapping, then add a new one for v2.",
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/opt/app/v1(/.*)?'},
        answer='Removed file context mapping: /opt/app/v1(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0105',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='single',
        user_input="Delete the temporary share's context mapping.",
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/srv/tmp-share(/.*)?'},
        answer='Removed file context mapping: /srv/tmp-share(/.*)?',
    ),
    V2(
        id='selinux-semanage_fcontext_delete-v2-0106',
        tool='selinux',
        operation='semanage_fcontext_delete',
        complexity='diagnostic',
        user_input='Cleanup script flagged a stale fcontext rule for /data/old-uploads that no longer matches any real path — remove it.',
        args={'operation': 'semanage_fcontext_delete', 'fcontext_spec': '/data/old-uploads(/.*)?'},
        answer='Removed file context mapping: /data/old-uploads(/.*)?',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0107',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='List every port label mapping on this host.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0108',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='semanage port -l',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0109',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='Show all SELinux port context definitions.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0110',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='What ports are currently labeled and what type do they carry?',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0111',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='Give me the full port label table for the audit.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0112',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='List port context mappings.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0113',
        tool='selinux',
        operation='semanage_port_list',
        complexity='single',
        user_input='Show me every custom port mapping configured.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0114',
        tool='selinux',
        operation='semanage_port_list',
        complexity='multi',
        user_input='List the port mappings, then add a new one for port 8080.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0115',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input="A new service can't bind port 8443 and there's no firewall rule blocking it — check what port labels currently exist.",
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0116',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input='Before adding a label for port 9200, check whether something else already claims that port.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0117',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input='The elasticsearch service is refusing to start on its custom port — check current port label mappings first.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0118',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input="nftables looks fine but a custom listener still won't bind — check whether the port even has an SELinux label.",
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0119',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input='Compliance wants a list of every non-default port label on this box.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_list-v2-0120',
        tool='selinux',
        operation='semanage_port_list',
        complexity='diagnostic',
        user_input='A support ticket claims a port mapping is missing — verify by listing them all first.',
        args={'operation': 'semanage_port_list'},
        answer='http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443\nssh_port_t                     tcp      22\ncustom_app_port_t              tcp      8080\n3 custom port mappings',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0121',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Label TCP port 8080 as http_port_t so httpd can bind it.',
        args={'operation': 'semanage_port_add', 'port_type': 'http_port_t', 'protocol': 'tcp', 'port': '8080'},
        answer='Added port mapping: 8080/tcp  ->  http_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0122',
        tool='selinux',
        operation='semanage_port_add',
        complexity='diagnostic',
        user_input='sshd is configured on port 2222 but keeps failing to bind — add the right SELinux port label.',
        args={'operation': 'semanage_port_add', 'port_type': 'ssh_port_t', 'protocol': 'tcp', 'port': '2222'},
        answer='Added port mapping: 2222/tcp  ->  ssh_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0123',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='semanage port -a -t http_port_t -p tcp 9443',
        args={'operation': 'semanage_port_add', 'port_type': 'http_port_t', 'protocol': 'tcp', 'port': '9443'},
        answer='Added port mapping: 9443/tcp  ->  http_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0124',
        tool='selinux',
        operation='semanage_port_add',
        complexity='multi',
        user_input='Add a port label for 5433 as postgresql_port_t, then restart the database.',
        args={'operation': 'semanage_port_add', 'port_type': 'postgresql_port_t', 'protocol': 'tcp', 'port': '5433'},
        answer='Added port mapping: 5433/tcp  ->  postgresql_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0125',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Add port 11222 tcp as memcache_port_t.',
        args={'operation': 'semanage_port_add', 'port_type': 'memcache_port_t', 'protocol': 'tcp', 'port': '11222'},
        answer='Added port mapping: 11222/tcp  ->  memcache_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0126',
        tool='selinux',
        operation='semanage_port_add',
        complexity='diagnostic',
        user_input="A local DNS resolver on a nonstandard UDP port can't bind — check and add the right label.",
        args={'operation': 'semanage_port_add', 'port_type': 'dns_port_t', 'protocol': 'udp', 'port': '5353'},
        answer='Added port mapping: 5353/udp  ->  dns_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0127',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Label 8081/tcp as http_port_t for the second app instance.',
        args={'operation': 'semanage_port_add', 'port_type': 'http_port_t', 'protocol': 'tcp', 'port': '8081'},
        answer='Added port mapping: 8081/tcp  ->  http_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0128',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Add udp port 5514 as syslogd_port_t.',
        args={'operation': 'semanage_port_add', 'port_type': 'syslogd_port_t', 'protocol': 'udp', 'port': '5514'},
        answer='Added port mapping: 5514/udp  ->  syslogd_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0129',
        tool='selinux',
        operation='semanage_port_add',
        complexity='diagnostic',
        user_input='A custom RabbitMQ listener on 5673 is being denied — add the amqp_port_t label for that port.',
        args={'operation': 'semanage_port_add', 'port_type': 'amqp_port_t', 'protocol': 'tcp', 'port': '5673'},
        answer='Added port mapping: 5673/tcp  ->  amqp_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0130',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Add TCP 9991 as jboss_management_port_t.',
        args={'operation': 'semanage_port_add', 'port_type': 'jboss_management_port_t', 'protocol': 'tcp', 'port': '9991'},
        answer='Added port mapping: 9991/tcp  ->  jboss_management_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0131',
        tool='selinux',
        operation='semanage_port_add',
        complexity='diagnostic',
        user_input="A non-default Redis instance on 6390 can't bind — label the port correctly.",
        args={'operation': 'semanage_port_add', 'port_type': 'redis_port_t', 'protocol': 'tcp', 'port': '6390'},
        answer='Added port mapping: 6390/tcp  ->  redis_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0132',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='Add TCP port 3129 as http_cache_port_t for the proxy cache.',
        args={'operation': 'semanage_port_add', 'port_type': 'http_cache_port_t', 'protocol': 'tcp', 'port': '3129'},
        answer='Added port mapping: 3129/tcp  ->  http_cache_port_t',
    ),
    V2(
        id='selinux-semanage_port_add-v2-0133',
        tool='selinux',
        operation='semanage_port_add',
        complexity='single',
        user_input='semanage port -a -t nrpe_port_t -p tcp 5667',
        args={'operation': 'semanage_port_add', 'port_type': 'nrpe_port_t', 'protocol': 'tcp', 'port': '5667'},
        answer='Added port mapping: 5667/tcp  ->  nrpe_port_t',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0134',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Remove the port label for tcp/8080, that service was decommissioned.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '8080'},
        answer='Removed port mapping: 8080/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0135',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='diagnostic',
        user_input='A leftover custom port label from an old service is cluttering the table — remove the mapping for tcp/9443.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '9443'},
        answer='Removed port mapping: 9443/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0136',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='semanage port -d -p udp 5353',
        args={'operation': 'semanage_port_delete', 'protocol': 'udp', 'port': '5353'},
        answer='Removed port mapping: 5353/udp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0137',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='multi',
        user_input='Delete the port mapping for 5433/tcp, then list the table to confirm.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '5433'},
        answer='Removed port mapping: 5433/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0138',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Delete the port label for 11222/tcp.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '11222'},
        answer='Removed port mapping: 11222/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0139',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='diagnostic',
        user_input='The syslog listener on 5514/udp was retired last month but its port label is still active — clean it up.',
        args={'operation': 'semanage_port_delete', 'protocol': 'udp', 'port': '5514'},
        answer='Removed port mapping: 5514/udp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0140',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Remove the label tied to tcp port 8081.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '8081'},
        answer='Removed port mapping: 8081/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0141',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Delete port mapping tcp/5673.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '5673'},
        answer='Removed port mapping: 5673/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0142',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='diagnostic',
        user_input='An old JBoss management port mapping is no longer needed since the service moved hosts — delete it.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '9991'},
        answer='Removed port mapping: 9991/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0143',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Remove the custom Redis port label on 6390/tcp.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '6390'},
        answer='Removed port mapping: 6390/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0144',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='diagnostic',
        user_input='The proxy cache on 3129 was shut down last week — remove its lingering port mapping.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '3129'},
        answer='Removed port mapping: 3129/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0145',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Delete the nrpe port mapping on tcp/5667.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '5667'},
        answer='Removed port mapping: 5667/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0146',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='single',
        user_input='Remove the label for ssh alt port tcp/2222.',
        args={'operation': 'semanage_port_delete', 'protocol': 'tcp', 'port': '2222'},
        answer='Removed port mapping: 2222/tcp',
    ),
    V2(
        id='selinux-semanage_port_delete-v2-0147',
        tool='selinux',
        operation='semanage_port_delete',
        complexity='diagnostic',
        user_input='A retired remote-syslog-over-TLS listener still has a port label on udp/6514 — remove it.',
        args={'operation': 'semanage_port_delete', 'protocol': 'udp', 'port': '6514'},
        answer='Removed port mapping: 6514/udp',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0148',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='List all SELinux user mappings on this host.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0149',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='semanage login -l',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0150',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='Show every SELinux user mapping.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0151',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='What SELinux users exist and what roles do they map to?',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0152',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='Give me the full SELinux user mapping table.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0153',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='List semanage user entries.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0154',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='Show me the confined user mappings configured here.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0155',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='Dump all SELinux user-to-role mappings.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0156',
        tool='selinux',
        operation='semanage_user_list',
        complexity='single',
        user_input='List all SELinux user mappings on this host.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0157',
        tool='selinux',
        operation='semanage_user_list',
        complexity='diagnostic',
        user_input="A newly onboarded admin can't get sysadm_r even though their Linux account should map to it — check the current user mappings.",
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0158',
        tool='selinux',
        operation='semanage_user_list',
        complexity='diagnostic',
        user_input="Before adding a mapping for the new operator account, check what's already defined.",
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0159',
        tool='selinux',
        operation='semanage_user_list',
        complexity='diagnostic',
        user_input='An audit flagged a mismatch between Linux accounts and SELinux user roles — list current mappings to compare.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0160',
        tool='selinux',
        operation='semanage_user_list',
        complexity='diagnostic',
        user_input="A confined user keeps hitting unexpected denials — check what SELinux user they're actually mapped to.",
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_list-v2-0161',
        tool='selinux',
        operation='semanage_user_list',
        complexity='diagnostic',
        user_input='Compliance wants a dump of every SELinux user role mapping for the quarterly review.',
        args={'operation': 'semanage_user_list'},
        answer='root              staff_r sysadm_r\n__default__       user_r\nsvc_ops           staff_r\n3 user mappings',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0162',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Map opsuser to staff_r and sysadm_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'opsuser', 'roles': 'staff_r sysadm_r'},
        answer='Added SELinux user mapping: opsuser  ->  staff_r sysadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0163',
        tool='selinux',
        operation='semanage_user_add',
        complexity='diagnostic',
        user_input="jdoe's account keeps landing in the wrong SELinux context after login — add an explicit mapping to user_r.",
        args={'operation': 'semanage_user_add', 'seuser': 'jdoe_sel', 'roles': 'user_r'},
        answer='Added SELinux user mapping: jdoe_sel  ->  user_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0164',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='semanage login -a -s staff_r deployer',
        args={'operation': 'semanage_user_add', 'seuser': 'deployer', 'roles': 'staff_r'},
        answer='Added SELinux user mapping: deployer  ->  staff_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0165',
        tool='selinux',
        operation='semanage_user_add',
        complexity='multi',
        user_input='Add a user mapping for auditor to auditadm_r, then confirm with the mapping list.',
        args={'operation': 'semanage_user_add', 'seuser': 'auditor', 'roles': 'auditadm_r'},
        answer='Added SELinux user mapping: auditor  ->  auditadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0166',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Map netops to the secadm_r role.',
        args={'operation': 'semanage_user_add', 'seuser': 'netops', 'roles': 'secadm_r'},
        answer='Added SELinux user mapping: netops  ->  secadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0167',
        tool='selinux',
        operation='semanage_user_add',
        complexity='diagnostic',
        user_input='kwhite needs staff-level access under confined SELinux but currently falls back to the default user — add the mapping.',
        args={'operation': 'semanage_user_add', 'seuser': 'kwhite_sel', 'roles': 'staff_r'},
        answer='Added SELinux user mapping: kwhite_sel  ->  staff_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0168',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Add svc_backup_sel mapped to sysadm_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'svc_backup_sel', 'roles': 'sysadm_r'},
        answer='Added SELinux user mapping: svc_backup_sel  ->  sysadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0169',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Map bpatel_sel to both user_r and staff_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'bpatel_sel', 'roles': 'user_r staff_r'},
        answer='Added SELinux user mapping: bpatel_sel  ->  user_r staff_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0170',
        tool='selinux',
        operation='semanage_user_add',
        complexity='diagnostic',
        user_input="The DB admin account isn't picking up the right confined role — add a mapping for dbadmin to dbadm_r.",
        args={'operation': 'semanage_user_add', 'seuser': 'dbadmin', 'roles': 'dbadm_r'},
        answer='Added SELinux user mapping: dbadmin  ->  dbadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0171',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Add secops mapped to secadm_r and sysadm_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'secops', 'roles': 'secadm_r sysadm_r'},
        answer='Added SELinux user mapping: secops  ->  secadm_r sysadm_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0172',
        tool='selinux',
        operation='semanage_user_add',
        complexity='diagnostic',
        user_input='A read-only operator account defaulted to a role with too much access — add an explicit user_r mapping instead.',
        args={'operation': 'semanage_user_add', 'seuser': 'readonly_ops', 'roles': 'user_r'},
        answer='Added SELinux user mapping: readonly_ops  ->  user_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0173',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Map mgarcia_sel to staff_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'mgarcia_sel', 'roles': 'staff_r'},
        answer='Added SELinux user mapping: mgarcia_sel  ->  staff_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0174',
        tool='selinux',
        operation='semanage_user_add',
        complexity='single',
        user_input='Add a user mapping for tlee_sel to user_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'tlee_sel', 'roles': 'user_r'},
        answer='Added SELinux user mapping: tlee_sel  ->  user_r',
    ),
    V2(
        id='selinux-semanage_user_add-v2-0175',
        tool='selinux',
        operation='semanage_user_add',
        complexity='diagnostic',
        user_input='The audit service account has no explicit SELinux role and is falling back to the default — map it to auditadm_r.',
        args={'operation': 'semanage_user_add', 'seuser': 'svc_audit_sel', 'roles': 'auditadm_r'},
        answer='Added SELinux user mapping: svc_audit_sel  ->  auditadm_r',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0176',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Remove the SELinux user mapping for opsuser.',
        args={'operation': 'semanage_user_delete', 'seuser': 'opsuser'},
        answer='Removed SELinux user mapping: opsuser',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0177',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='diagnostic',
        user_input='jdoe left the confined-users program — remove their SELinux user mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'jdoe_sel'},
        answer='Removed SELinux user mapping: jdoe_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0178',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='semanage login -d deployer',
        args={'operation': 'semanage_user_delete', 'seuser': 'deployer'},
        answer='Removed SELinux user mapping: deployer',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0179',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='multi',
        user_input="Delete the auditor mapping, then list mappings to confirm it's gone.",
        args={'operation': 'semanage_user_delete', 'seuser': 'auditor'},
        answer='Removed SELinux user mapping: auditor',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0180',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Delete the netops SELinux user mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'netops'},
        answer='Removed SELinux user mapping: netops',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0181',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='diagnostic',
        user_input="kwhite's role changed and the old confined mapping is now wrong — remove it before adding the new one.",
        args={'operation': 'semanage_user_delete', 'seuser': 'kwhite_sel'},
        answer='Removed SELinux user mapping: kwhite_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0182',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Remove the svc_backup_sel mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'svc_backup_sel'},
        answer='Removed SELinux user mapping: svc_backup_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0183',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Delete the mapping for bpatel_sel.',
        args={'operation': 'semanage_user_delete', 'seuser': 'bpatel_sel'},
        answer='Removed SELinux user mapping: bpatel_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0184',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='diagnostic',
        user_input='The dbadmin mapping is stale after the account was renamed — delete the old entry.',
        args={'operation': 'semanage_user_delete', 'seuser': 'dbadmin'},
        answer='Removed SELinux user mapping: dbadmin',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0185',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Remove secops from the SELinux user mapping table.',
        args={'operation': 'semanage_user_delete', 'seuser': 'secops'},
        answer='Removed SELinux user mapping: secops',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0186',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='diagnostic',
        user_input='The read-only operator account was decommissioned — clean up its SELinux user mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'readonly_ops'},
        answer='Removed SELinux user mapping: readonly_ops',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0187',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input="Delete mgarcia_sel's mapping.",
        args={'operation': 'semanage_user_delete', 'seuser': 'mgarcia_sel'},
        answer='Removed SELinux user mapping: mgarcia_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0188',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='single',
        user_input='Remove the tlee_sel SELinux user mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'tlee_sel'},
        answer='Removed SELinux user mapping: tlee_sel',
    ),
    V2(
        id='selinux-semanage_user_delete-v2-0189',
        tool='selinux',
        operation='semanage_user_delete',
        complexity='diagnostic',
        user_input='The audit service account is being retired — remove its confined user mapping.',
        args={'operation': 'semanage_user_delete', 'seuser': 'svc_audit_sel'},
        answer='Removed SELinux user mapping: svc_audit_sel',
    ),
    V2(
        id='selinux-restorecon-v2-0190',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='Restore the default SELinux context under /srv/www recursively.',
        args={'operation': 'restorecon', 'path': '/srv/www'},
        answer='Relabeled: /srv/www (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0191',
        tool='selinux',
        operation='restorecon',
        complexity='diagnostic',
        user_input='Uploaded files are getting 403s from apache even though the fcontext mapping looks right — run restorecon on the directory.',
        args={'operation': 'restorecon', 'path': '/data/uploads'},
        answer='Relabeled: /data/uploads (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0192',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='restorecon -Rv /opt/appdata',
        args={'operation': 'restorecon', 'path': '/opt/appdata'},
        answer='Relabeled: /opt/appdata (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0193',
        tool='selinux',
        operation='restorecon',
        complexity='multi',
        user_input='Add the fcontext mapping, then run restorecon on /srv/app/writable to apply it.',
        args={'operation': 'restorecon', 'path': '/srv/app/writable'},
        answer='Relabeled: /srv/app/writable (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0194',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='Fix the labeling under /mnt/webcontent.',
        args={'operation': 'restorecon', 'path': '/mnt/webcontent'},
        answer='Relabeled: /mnt/webcontent (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0195',
        tool='selinux',
        operation='restorecon',
        complexity='diagnostic',
        user_input="A script under /opt/tools/bin can't execute even though permissions look fine — relabel it with restorecon.",
        args={'operation': 'restorecon', 'path': '/opt/tools/bin'},
        answer='Relabeled: /opt/tools/bin (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0196',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='Restore contexts for /opt/appdata/certs.',
        args={'operation': 'restorecon', 'path': '/opt/appdata/certs'},
        answer='Relabeled: /opt/appdata/certs (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0197',
        tool='selinux',
        operation='restorecon',
        complexity='diagnostic',
        user_input='The Samba share keeps failing to serve files after a restore from backup — run restorecon on it.',
        args={'operation': 'restorecon', 'path': '/srv/samba/shared'},
        answer='Relabeled: /srv/samba/shared (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0198',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='Recursively fix SELinux labels on /data/pgdata.',
        args={'operation': 'restorecon', 'path': '/data/pgdata'},
        answer='Relabeled: /data/pgdata (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0199',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='restorecon on /srv/containers, recursive.',
        args={'operation': 'restorecon', 'path': '/srv/containers'},
        answer='Relabeled: /srv/containers (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0200',
        tool='selinux',
        operation='restorecon',
        complexity='diagnostic',
        user_input='A stateful directory lost its correct labels after a tar-based restore — run restorecon to fix it.',
        args={'operation': 'restorecon', 'path': '/opt/customapp/state'},
        answer='Relabeled: /opt/customapp/state (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-restorecon-v2-0201',
        tool='selinux',
        operation='restorecon',
        complexity='single',
        user_input='Relabel /srv/static-assets with restorecon.',
        args={'operation': 'restorecon', 'path': '/srv/static-assets'},
        answer='Relabeled: /srv/static-assets (restorecon -Rv)\nRestored context on 3 files',
    ),
    V2(
        id='selinux-chcon-v2-0202',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='Set the type on /srv/www/index.html to httpd_sys_content_t.',
        args={'operation': 'chcon', 'context_type': 'httpd_sys_content_t', 'path': '/srv/www/index.html'},
        answer='Changed context: /srv/www/index.html  ->  httpd_sys_content_t',
    ),
    V2(
        id='selinux-chcon-v2-0203',
        tool='selinux',
        operation='chcon',
        complexity='diagnostic',
        user_input='A specific upload subfolder keeps getting denied even though the parent fcontext rule is right — set its type directly with chcon.',
        args={'operation': 'chcon', 'context_type': 'public_content_rw_t', 'path': '/data/uploads/incoming'},
        answer='Changed context: /data/uploads/incoming  ->  public_content_rw_t',
    ),
    V2(
        id='selinux-chcon-v2-0204',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='chcon -t bin_t /opt/tools/bin/runner',
        args={'operation': 'chcon', 'context_type': 'bin_t', 'path': '/opt/tools/bin/runner'},
        answer='Changed context: /opt/tools/bin/runner  ->  bin_t',
    ),
    V2(
        id='selinux-chcon-v2-0205',
        tool='selinux',
        operation='chcon',
        complexity='multi',
        user_input='Change the type on the cert file to cert_t, then restart the service that reads it.',
        args={'operation': 'chcon', 'context_type': 'cert_t', 'path': '/opt/appdata/certs/server.pem'},
        answer='Changed context: /opt/appdata/certs/server.pem  ->  cert_t',
    ),
    V2(
        id='selinux-chcon-v2-0206',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input="Set /opt/customapp/logs/app.log's type to var_log_t.",
        args={'operation': 'chcon', 'context_type': 'var_log_t', 'path': '/opt/customapp/logs/app.log'},
        answer='Changed context: /opt/customapp/logs/app.log  ->  var_log_t',
    ),
    V2(
        id='selinux-chcon-v2-0207',
        tool='selinux',
        operation='chcon',
        complexity='diagnostic',
        user_input='One file in the Samba share is still showing the wrong type after restorecon skipped it — set it directly.',
        args={'operation': 'chcon', 'context_type': 'samba_share_t', 'path': '/srv/samba/shared/readme.txt'},
        answer='Changed context: /srv/samba/shared/readme.txt  ->  samba_share_t',
    ),
    V2(
        id='selinux-chcon-v2-0208',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='Set the context type on /srv/containers/data.img to container_file_t.',
        args={'operation': 'chcon', 'context_type': 'container_file_t', 'path': '/srv/containers/data.img'},
        answer='Changed context: /srv/containers/data.img  ->  container_file_t',
    ),
    V2(
        id='selinux-chcon-v2-0209',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='chcon the cache file to httpd_sys_rw_content_t.',
        args={'operation': 'chcon', 'context_type': 'httpd_sys_rw_content_t', 'path': '/srv/app/writable/cache.db'},
        answer='Changed context: /srv/app/writable/cache.db  ->  httpd_sys_rw_content_t',
    ),
    V2(
        id='selinux-chcon-v2-0210',
        tool='selinux',
        operation='chcon',
        complexity='diagnostic',
        user_input='A single subdirectory inside pgdata has the wrong type after a manual copy — fix it with chcon.',
        args={'operation': 'chcon', 'context_type': 'postgresql_db_t', 'path': '/data/pgdata/base'},
        answer='Changed context: /data/pgdata/base  ->  postgresql_db_t',
    ),
    V2(
        id='selinux-chcon-v2-0211',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='Change the type of /mnt/nfs-share/shared.dat to nfs_t.',
        args={'operation': 'chcon', 'context_type': 'nfs_t', 'path': '/mnt/nfs-share/shared.dat'},
        answer='Changed context: /mnt/nfs-share/shared.dat  ->  nfs_t',
    ),
    V2(
        id='selinux-chcon-v2-0212',
        tool='selinux',
        operation='chcon',
        complexity='diagnostic',
        user_input='A state file retained the wrong type after being copied from a staging box — set it explicitly.',
        args={'operation': 'chcon', 'context_type': 'var_lib_t', 'path': '/opt/customapp/state/db.sqlite'},
        answer='Changed context: /opt/customapp/state/db.sqlite  ->  var_lib_t',
    ),
    V2(
        id='selinux-chcon-v2-0213',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='Set the type on the logo file to httpd_sys_content_t.',
        args={'operation': 'chcon', 'context_type': 'httpd_sys_content_t', 'path': '/srv/static-assets/logo.png'},
        answer='Changed context: /srv/static-assets/logo.png  ->  httpd_sys_content_t',
    ),
    V2(
        id='selinux-chcon-v2-0214',
        tool='selinux',
        operation='chcon',
        complexity='single',
        user_input='chcon -t etc_t /opt/customapp/config.yaml',
        args={'operation': 'chcon', 'context_type': 'etc_t', 'path': '/opt/customapp/config.yaml'},
        answer='Changed context: /opt/customapp/config.yaml  ->  etc_t',
    ),
    V2(
        id='selinux-audit2allow-v2-0215',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input='Read the audit log and see what policy rules the recent denials suggest.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0216',
        tool='selinux',
        operation='audit2allow',
        complexity='diagnostic',
        user_input="httpd is being denied something but we don't know what module would fix it — run audit2allow to see the suggested rule.",
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0217',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input='audit2allow -a',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0218',
        tool='selinux',
        operation='audit2allow',
        complexity='multi',
        user_input="Run audit2allow to get the suggested policy module, then I'll review it before applying anything.",
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0219',
        tool='selinux',
        operation='audit2allow',
        complexity='diagnostic',
        user_input='A confined service keeps hitting a denial after every restart — generate the suggested allow rule from the audit log.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0220',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input="Show me what audit2allow suggests based on today's denials.",
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0221',
        tool='selinux',
        operation='audit2allow',
        complexity='diagnostic',
        user_input="We're not sure which boolean or fcontext rule would fix the recent AVC denials — check what audit2allow proposes.",
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0222',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input='Generate policy suggestions from the denial log.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0223',
        tool='selinux',
        operation='audit2allow',
        complexity='diagnostic',
        user_input='The app team wants a policy module instead of flipping a boolean — see what audit2allow would generate.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0224',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input='What denials showed up recently and what rule would silence them?',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0225',
        tool='selinux',
        operation='audit2allow',
        complexity='multi',
        user_input="Pull the audit2allow suggestions, then we'll decide whether to persist the boolean or write a module.",
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0226',
        tool='selinux',
        operation='audit2allow',
        complexity='single',
        user_input='Check recent AVC denials and the corresponding suggested rule.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
    V2(
        id='selinux-audit2allow-v2-0227',
        tool='selinux',
        operation='audit2allow',
        complexity='diagnostic',
        user_input='A container keeps getting blocked from a bind mount — see what audit2allow recommends to fix it.',
        args={'operation': 'audit2allow'},
        answer='#============= httpd_t ==============\nallow httpd_t var_t:file { read open getattr };\n\n1 denial found; suggested module: local_httpd_var',
    ),
]

from finetune.scenarios_v2 import check_module; check_module('selinux', SCENARIOS_V2)
