"""finetune/scenarios_v2/services.py — corpus v2 scenarios for 'services'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # status (6)
    V2(id="services-status-v2-0001", tool="services", operation="status", complexity="single",
       user_input="Is crond running on batch03?",
       args={"operation": "status", "unit": "crond.service"},
       answer="crond.service: active (running); since 4d ago; PID 812"),
    V2(id="services-status-v2-0002", tool="services", operation="status", complexity="diagnostic",
       user_input="Mail isn't going out from this host — is postfix even up?",
       args={"operation": "status", "unit": "postfix.service"},
       answer="postfix.service: inactive (dead); last exited with code 1"),
    V2(id="services-status-v2-0003", tool="services", operation="status", complexity="single",
       user_input="check on the httpd unit",
       args={"operation": "status", "unit": "httpd.service"},
       answer="httpd.service: active (running); since 10d ago; 6 workers"),
    V2(id="services-status-v2-0004", tool="services", operation="status", complexity="multi",
       user_input="Check whether sssd is running, and if it's not, start it back up.",
       args={"operation": "status", "unit": "sssd.service"},
       answer="sssd.service: inactive (dead); last exited with code 0 (clean stop)"),
    V2(id="services-status-v2-0005", tool="services", operation="status", complexity="single",
       user_input="Ticket 5511: confirm the smb unit is active before the maintenance window closes.",
       args={"operation": "status", "unit": "smb.service"},
       answer="smb.service: active (running); since 20d ago"),
    V2(id="services-status-v2-0006", tool="services", operation="status", complexity="diagnostic",
       user_input="Backups aren't landing on the NFS share — has nfs-server maybe stopped on the storage box?",
       args={"operation": "status", "unit": "nfs-server.service"},
       answer="nfs-server.service: failed (Result: exit-code); main process exited, status=1/FAILURE"),

    # start (7)
    V2(id="services-start-v2-0001", tool="services", operation="start", complexity="single",
       user_input="Start the redis service.",
       args={"operation": "start", "unit": "redis.service"},
       answer="redis.service started; active (running); PID 3312"),
    V2(id="services-start-v2-0002", tool="services", operation="start", complexity="multi",
       user_input="Start postgresql, then check its status to confirm it came up clean.",
       args={"operation": "start", "unit": "postgresql.service"},
       answer="postgresql.service started; active (running); PID 4410"),
    V2(id="services-start-v2-0003", tool="services", operation="start", complexity="single",
       user_input="bring up the nginx unit on web04",
       args={"operation": "start", "unit": "nginx.service"},
       answer="nginx.service started; active (running); PID 1102"),
    V2(id="services-start-v2-0004", tool="services", operation="start", complexity="single",
       user_input="Ticket 8801: start the vsftpd service that was stopped for the audit.",
       args={"operation": "start", "unit": "vsftpd.service"},
       answer="vsftpd.service started; active (running); PID 2290"),
    V2(id="services-start-v2-0005", tool="services", operation="start", complexity="diagnostic",
       user_input="named was found dead earlier — go ahead and start it back up.",
       args={"operation": "start", "unit": "named.service"},
       answer="named.service started; active (running); PID 990; listening on 10.0.0.5:53"),
    V2(id="services-start-v2-0006", tool="services", operation="start", complexity="single",
       user_input="start docker on the build runner",
       args={"operation": "start", "unit": "docker.service"},
       answer="docker.service started; active (running); PID 5510"),
    V2(id="services-start-v2-0007", tool="services", operation="start", complexity="single",
       user_input="Turn on the chronyd time sync unit.",
       args={"operation": "start", "unit": "chronyd.service"},
       answer="chronyd.service started; active (running); PID 700"),

    # stop (8)
    V2(id="services-stop-v2-0001", tool="services", operation="stop", complexity="single",
       user_input="Stop the httpd service.",
       args={"operation": "stop", "unit": "httpd.service"},
       answer="httpd.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0002", tool="services", operation="stop", complexity="multi",
       user_input="Stop the tomcat unit and then confirm it's not listening anymore.",
       args={"operation": "stop", "unit": "tomcat.service"},
       answer="tomcat.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0003", tool="services", operation="stop", complexity="single",
       user_input="shut down vsftpd for the security review",
       args={"operation": "stop", "unit": "vsftpd.service"},
       answer="vsftpd.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0004", tool="services", operation="stop", complexity="single",
       user_input="Ticket 4402: stop the rsyncd service before rotating the backup volume.",
       args={"operation": "stop", "unit": "rsyncd.service"},
       answer="rsyncd.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0005", tool="services", operation="stop", complexity="diagnostic",
       user_input="This unused samba share is still exposed — stop the smb unit for now.",
       args={"operation": "stop", "unit": "smb.service"},
       answer="smb.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0006", tool="services", operation="stop", complexity="single",
       user_input="stop the memcached unit on cache03",
       args={"operation": "stop", "unit": "memcached.service"},
       answer="memcached.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0007", tool="services", operation="stop", complexity="single",
       user_input="Halt the elasticsearch service for the reindex.",
       args={"operation": "stop", "unit": "elasticsearch.service"},
       answer="elasticsearch.service stopped; inactive (dead)"),
    V2(id="services-stop-v2-0008", tool="services", operation="stop", complexity="single",
       user_input="Kill the jenkins unit ahead of the plugin upgrade.",
       args={"operation": "stop", "unit": "jenkins.service"},
       answer="jenkins.service stopped; inactive (dead)"),

    # restart (8)
    V2(id="services-restart-v2-0001", tool="services", operation="restart", complexity="single",
       user_input="Restart sshd on jump01.",
       args={"operation": "restart", "unit": "sshd.service"},
       answer="sshd.service restarted; active (running); PID 890"),
    V2(id="services-restart-v2-0002", tool="services", operation="restart", complexity="diagnostic",
       user_input="nginx has been throwing 502s for the last few minutes — restart it.",
       args={"operation": "restart", "unit": "nginx.service"},
       answer="nginx.service restarted; active (running); PID 1150"),
    V2(id="services-restart-v2-0003", tool="services", operation="restart", complexity="multi",
       user_input="Restart the app service and tail its logs right after to confirm a clean start.",
       args={"operation": "restart", "unit": "app.service"},
       answer="app.service restarted; active (running); PID 2201"),
    V2(id="services-restart-v2-0004", tool="services", operation="restart", complexity="single",
       user_input="cycle the postgresql service to pick up the new config",
       args={"operation": "restart", "unit": "postgresql.service"},
       answer="postgresql.service restarted; active (running); PID 4420"),
    V2(id="services-restart-v2-0005", tool="services", operation="restart", complexity="single",
       user_input="Ticket 7712: restart the named service after the zone edit.",
       args={"operation": "restart", "unit": "named.service"},
       answer="named.service restarted; active (running); PID 1005; zones reloaded"),
    V2(id="services-restart-v2-0006", tool="services", operation="restart", complexity="diagnostic",
       user_input="Something looks stuck in httpd's worker pool — bounce the unit.",
       args={"operation": "restart", "unit": "httpd.service"},
       answer="httpd.service restarted; active (running); PID 995"),
    V2(id="services-restart-v2-0007", tool="services", operation="restart", complexity="single",
       user_input="restart docker",
       args={"operation": "restart", "unit": "docker.service"},
       answer="docker.service restarted; active (running); PID 5522"),
    V2(id="services-restart-v2-0008", tool="services", operation="restart", complexity="single",
       user_input="Bounce the redis unit after the config change on cache01.",
       args={"operation": "restart", "unit": "redis.service"},
       answer="redis.service restarted; active (running); PID 3320"),

    # enable (8)
    V2(id="services-enable-v2-0001", tool="services", operation="enable", complexity="single",
       user_input="Enable chronyd to start at boot.",
       args={"operation": "enable", "unit": "chronyd.service"},
       answer="Created symlink for chronyd.service; enabled"),
    V2(id="services-enable-v2-0002", tool="services", operation="enable", complexity="multi",
       user_input="Enable the docker unit at boot and then start it now.",
       args={"operation": "enable", "unit": "docker.service"},
       answer="Created symlink for docker.service; enabled"),
    V2(id="services-enable-v2-0003", tool="services", operation="enable", complexity="single",
       user_input="make sure httpd comes up on reboot",
       args={"operation": "enable", "unit": "httpd.service"},
       answer="Created symlink for httpd.service; enabled"),
    V2(id="services-enable-v2-0004", tool="services", operation="enable", complexity="single",
       user_input="Ticket 3301: enable postgresql for boot-time start on the new db replica.",
       args={"operation": "enable", "unit": "postgresql.service"},
       answer="Created symlink for postgresql.service; enabled"),
    V2(id="services-enable-v2-0005", tool="services", operation="enable", complexity="diagnostic",
       user_input="named didn't come back after the last reboot — was it ever enabled? Enable it now.",
       args={"operation": "enable", "unit": "named.service"},
       answer="Created symlink for named.service; enabled"),
    V2(id="services-enable-v2-0006", tool="services", operation="enable", complexity="single",
       user_input="enable sssd at boot",
       args={"operation": "enable", "unit": "sssd.service"},
       answer="Created symlink for sssd.service; enabled"),
    V2(id="services-enable-v2-0007", tool="services", operation="enable", complexity="single",
       user_input="Set crond to start automatically going forward.",
       args={"operation": "enable", "unit": "crond.service"},
       answer="crond.service already enabled; no change"),
    V2(id="services-enable-v2-0008", tool="services", operation="enable", complexity="single",
       user_input="Enable the smb service for boot on the fileserver.",
       args={"operation": "enable", "unit": "smb.service"},
       answer="Created symlink for smb.service; enabled"),

    # disable (8)
    V2(id="services-disable-v2-0001", tool="services", operation="disable", complexity="single",
       user_input="Disable telnet.socket from starting at boot.",
       args={"operation": "disable", "unit": "telnet.socket"},
       answer="Removed symlink for telnet.socket; disabled"),
    V2(id="services-disable-v2-0002", tool="services", operation="disable", complexity="diagnostic",
       user_input="A hardening scan flagged rsh being enabled by default — turn off its boot-start.",
       args={"operation": "disable", "unit": "rsh.socket"},
       answer="Removed symlink for rsh.socket; disabled"),
    V2(id="services-disable-v2-0003", tool="services", operation="disable", complexity="single",
       user_input="don't let vsftpd start at boot anymore",
       args={"operation": "disable", "unit": "vsftpd.service"},
       answer="Removed symlink for vsftpd.service; disabled"),
    V2(id="services-disable-v2-0004", tool="services", operation="disable", complexity="multi",
       user_input="Disable the ftp unit for boot and stop it right now too.",
       args={"operation": "disable", "unit": "vsftpd.service"},
       answer="Removed symlink for vsftpd.service; disabled"),
    V2(id="services-disable-v2-0005", tool="services", operation="disable", complexity="single",
       user_input="Ticket 6604: disable boot-start for the legacy nis service.",
       args={"operation": "disable", "unit": "ypbind.service"},
       answer="Removed symlink for ypbind.service; disabled"),
    V2(id="services-disable-v2-0006", tool="services", operation="disable", complexity="single",
       user_input="disable cups on the headless server",
       args={"operation": "disable", "unit": "cups.service"},
       answer="Removed symlink for cups.service; disabled"),
    V2(id="services-disable-v2-0007", tool="services", operation="disable", complexity="single",
       user_input="Turn off boot-start for the avahi-daemon unit.",
       args={"operation": "disable", "unit": "avahi-daemon.service"},
       answer="Removed symlink for avahi-daemon.service; disabled"),
    V2(id="services-disable-v2-0008", tool="services", operation="disable", complexity="single",
       user_input="Stop bluetooth from auto-starting on this rack server.",
       args={"operation": "disable", "unit": "bluetooth.service"},
       answer="Removed symlink for bluetooth.service; disabled"),

    # logs (6)
    V2(id="services-logs-v2-0001", tool="services", operation="logs", complexity="single",
       user_input="Get the last 20 log lines for nginx.",
       args={"operation": "logs", "unit": "nginx.service", "lines": 20},
       answer="Sep 12 08:00:00 web03 nginx[1122]: 200 GET /health\nSep 12 08:00:12 web03 nginx[1122]: 200 GET /api/status"),
    V2(id="services-logs-v2-0002", tool="services", operation="logs", complexity="diagnostic",
       user_input="postgresql just went down — what did it log right before that?",
       args={"operation": "logs", "unit": "postgresql.service"},
       answer="Sep 12 09:10:00 db01 postgres[512]: FATAL: could not write to file 'pg_wal': No space left on device"),
    V2(id="services-logs-v2-0003", tool="services", operation="logs", complexity="single",
       user_input="pull 100 lines from the sssd unit's journal",
       args={"operation": "logs", "unit": "sssd.service", "lines": 100},
       answer="Sep 12 07:00:01 auth01 sssd[880]: Backend is offline\nSep 12 07:00:05 auth01 sssd[880]: Reconnected to LDAP"),
    V2(id="services-logs-v2-0004", tool="services", operation="logs", complexity="multi",
       user_input="Get the recent logs for httpd, and restart it if you see repeated segfaults.",
       args={"operation": "logs", "unit": "httpd.service"},
       answer="Sep 12 08:40:00 web01 httpd[990]: [notice] child pid 991 exit signal Segmentation fault"),
    V2(id="services-logs-v2-0005", tool="services", operation="logs", complexity="single",
       user_input="Ticket 2201: grab the last 50 lines of docker's journal for the incident report.",
       args={"operation": "logs", "unit": "docker.service", "lines": 50},
       answer="Sep 12 09:00:00 build01 dockerd[5510]: level=info msg=API listen on /run/docker.sock"),
    V2(id="services-logs-v2-0006", tool="services", operation="logs", complexity="single",
       user_input="show me chronyd's recent journal entries",
       args={"operation": "logs", "unit": "chronyd.service"},
       answer="Sep 12 08:00:00 host01 chronyd[700]: Selected source 10.0.0.1"),

    # mask (7)
    V2(id="services-mask-v2-0001", tool="services", operation="mask", complexity="single",
       user_input="Mask the telnet.socket unit so nobody can start it.",
       args={"operation": "mask", "unit": "telnet.socket"},
       answer="Created symlink /etc/systemd/system/telnet.socket -> /dev/null; masked"),
    V2(id="services-mask-v2-0002", tool="services", operation="mask", complexity="diagnostic",
       user_input="Someone keeps manually starting rsh after we disabled it — mask it outright.",
       args={"operation": "mask", "unit": "rsh.socket"},
       answer="Created symlink /etc/systemd/system/rsh.socket -> /dev/null; masked"),
    V2(id="services-mask-v2-0003", tool="services", operation="mask", complexity="single",
       user_input="mask vsftpd so it can never run on this host",
       args={"operation": "mask", "unit": "vsftpd.service"},
       answer="Created symlink /etc/systemd/system/vsftpd.service -> /dev/null; masked"),
    V2(id="services-mask-v2-0004", tool="services", operation="mask", complexity="multi",
       user_input="Stop nfs-server and mask it so it doesn't come back on the next reboot.",
       args={"operation": "mask", "unit": "nfs-server.service"},
       answer="Created symlink /etc/systemd/system/nfs-server.service -> /dev/null; masked"),
    V2(id="services-mask-v2-0005", tool="services", operation="mask", complexity="single",
       user_input="Ticket 5590: mask the cups unit per the hardening checklist.",
       args={"operation": "mask", "unit": "cups.service"},
       answer="Created symlink /etc/systemd/system/cups.service -> /dev/null; masked"),
    V2(id="services-mask-v2-0006", tool="services", operation="mask", complexity="single",
       user_input="fully lock out the avahi-daemon unit",
       args={"operation": "mask", "unit": "avahi-daemon.service"},
       answer="Created symlink /etc/systemd/system/avahi-daemon.service -> /dev/null; masked"),
    V2(id="services-mask-v2-0007", tool="services", operation="mask", complexity="single",
       user_input="Mask bluetooth so it can't be started even manually.",
       args={"operation": "mask", "unit": "bluetooth.service"},
       answer="Created symlink /etc/systemd/system/bluetooth.service -> /dev/null; masked"),
]

from finetune.scenarios_v2 import check_module; check_module("services", SCENARIOS_V2)
