"""finetune/scenarios_v2/ssh_keys.py — corpus v2 scenarios for 'ssh_keys'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="ssh_keys-keygen-v2-0001", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="Generate an ed25519 key pair for the svc-deploy user at /home/svc-deploy/.ssh/id_ed25519.",
       args={"operation": "keygen", "path": "/home/svc-deploy/.ssh/id_ed25519", "key_type": "ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/svc-deploy/.ssh/id_ed25519\nFingerprint: SHA256:9fJ3kLp2..."),
    V2(id="ssh_keys-keygen-v2-0002", tool="ssh_keys", operation="keygen",
       complexity="diagnostic",
       user_input="The new backup runner box can't authenticate to the storage server at all — has a key pair even been generated for the backup-runner user yet? If not, create one at /home/backup-runner/.ssh/id_ed25519.",
       args={"operation": "keygen", "path": "/home/backup-runner/.ssh/id_ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/backup-runner/.ssh/id_ed25519\nFingerprint: SHA256:2mQp8Zx1..."),
    V2(id="ssh_keys-keygen-v2-0003", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="create a 4096-bit RSA key at /root/.ssh/id_rsa_offsite for the offsite sync job",
       args={"operation": "keygen", "path": "/root/.ssh/id_rsa_offsite", "key_type": "rsa", "bits": 4096},
       answer="Generating public/private rsa key pair.\nYour identification has been saved as /root/.ssh/id_rsa_offsite\nFingerprint: SHA256:7bNq4Vw0..."),
    V2(id="ssh_keys-keygen-v2-0004", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="Generate an ecdsa key for the netops user at /home/netops/.ssh/id_ecdsa, protected with a passphrase.",
       args={"operation": "keygen", "path": "/home/netops/.ssh/id_ecdsa", "key_type": "ecdsa", "passphrase": "N3tOps!Guard"},
       answer="Generating public/private ecdsa key pair.\nYour identification has been saved as /home/netops/.ssh/id_ecdsa\nFingerprint: SHA256:1kLm9Rt3..."),
    V2(id="ssh_keys-keygen-v2-0005", tool="ssh_keys", operation="keygen",
       complexity="multi",
       user_input="Generate a fresh ed25519 key for the ansible-runner user at /home/ansible-runner/.ssh/id_ed25519 and then add it to the target host's authorized_keys.",
       args={"operation": "keygen", "path": "/home/ansible-runner/.ssh/id_ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/ansible-runner/.ssh/id_ed25519\nFingerprint: SHA256:5xTd0Pk7..."),
    V2(id="ssh_keys-keygen-v2-0006", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="make a new SSH key at /home/gitlab-runner/.ssh/id_ed25519 for the CI runner user",
       args={"operation": "keygen", "path": "/home/gitlab-runner/.ssh/id_ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/gitlab-runner/.ssh/id_ed25519\nFingerprint: SHA256:0wYc6Hn2..."),
    V2(id="ssh_keys-keygen-v2-0007", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="Create a 2048-bit RSA key pair at /home/legacyapp/.ssh/id_rsa for a vendor system that only supports RSA.",
       args={"operation": "keygen", "path": "/home/legacyapp/.ssh/id_rsa", "key_type": "rsa", "bits": 2048},
       answer="Generating public/private rsa key pair.\nYour identification has been saved as /home/legacyapp/.ssh/id_rsa\nFingerprint: SHA256:3vBg1Sq8..."),
    V2(id="ssh_keys-keygen-v2-0008", tool="ssh_keys", operation="keygen",
       complexity="diagnostic",
       user_input="The monitoring collector on node09 keeps failing 'permission denied (publickey)' when it tries to reach the metrics host — was a key pair ever generated for the monitor user? Set one up at /home/monitor/.ssh/id_ed25519.",
       args={"operation": "keygen", "path": "/home/monitor/.ssh/id_ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/monitor/.ssh/id_ed25519\nFingerprint: SHA256:8cRp5Wj4..."),
    V2(id="ssh_keys-keygen-v2-0009", tool="ssh_keys", operation="keygen",
       complexity="single",
       user_input="Generate an ed25519 key at /home/terraform/.ssh/id_ed25519 for the provisioning account and show me the fingerprint.",
       args={"operation": "keygen", "path": "/home/terraform/.ssh/id_ed25519"},
       answer="Generating public/private ed25519 key pair.\nYour identification has been saved as /home/terraform/.ssh/id_ed25519\nFingerprint: SHA256:6nDf2Xz9..."),

    V2(id="ssh_keys-authorized_keys_list-v2-0001", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="List every key allowed to log in as the deploy user.",
       args={"operation": "authorized_keys_list", "user": "deploy"},
       answer="/home/deploy/.ssh/authorized_keys: 3 entries\nssh-ed25519 AAAAC3... jdoe@workstation\nssh-rsa AAAAB3... ci-bot@jenkins"),
    V2(id="ssh_keys-authorized_keys_list-v2-0002", tool="ssh_keys", operation="authorized_keys_list",
       complexity="diagnostic",
       user_input="A contractor says they can't SSH in as the appuser account even though we set them up last week — check whether their key actually landed in authorized_keys.",
       args={"operation": "authorized_keys_list", "user": "appuser"},
       answer="/home/appuser/.ssh/authorized_keys: 1 entry\nssh-ed25519 AAAAC3... ops-team@shared\nNo entry matching the contractor's key comment."),
    V2(id="ssh_keys-authorized_keys_list-v2-0003", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="what keys can log in as root on this host",
       args={"operation": "authorized_keys_list", "user": "root"},
       answer="/root/.ssh/authorized_keys: 2 entries\nssh-ed25519 AAAAC3... bastion@edge01\nssh-rsa AAAAB3... admin@laptop"),
    V2(id="ssh_keys-authorized_keys_list-v2-0004", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="Show the authorized_keys entries for the jenkins user, we're doing a key rotation audit.",
       args={"operation": "authorized_keys_list", "user": "jenkins"},
       answer="/home/jenkins/.ssh/authorized_keys: 4 entries\nssh-ed25519 AAAAC3... ci-old@jenkins\nssh-ed25519 AAAAC3... ci-new@jenkins"),
    V2(id="ssh_keys-authorized_keys_list-v2-0005", tool="ssh_keys", operation="authorized_keys_list",
       complexity="diagnostic",
       user_input="Security review wants proof of exactly who can log in as the ansible service account — pull the list.",
       args={"operation": "authorized_keys_list", "user": "ansible"},
       answer="/home/ansible/.ssh/authorized_keys: 2 entries\nssh-ed25519 AAAAC3... ansible-old@control-node\nssh-ed25519 AAAAC3... ansible-new@control-node"),
    V2(id="ssh_keys-authorized_keys_list-v2-0006", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="list the authorized keys for backupuser",
       args={"operation": "authorized_keys_list", "user": "backupuser"},
       answer="/home/backupuser/.ssh/authorized_keys: 1 entry\nssh-rsa AAAAB3... backup01@backup-svc"),
    V2(id="ssh_keys-authorized_keys_list-v2-0007", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="Dump the admin account's authorized_keys file for the CIS benchmark checklist.",
       args={"operation": "authorized_keys_list", "user": "admin"},
       answer="/home/admin/.ssh/authorized_keys: 2 entries\nssh-ed25519 AAAAC3... admin@laptop\nssh-ed25519 AAAAC3... admin@phone"),
    V2(id="ssh_keys-authorized_keys_list-v2-0008", tool="ssh_keys", operation="authorized_keys_list",
       complexity="multi",
       user_input="Show me the monitor user's authorized keys and then remove any that look stale.",
       args={"operation": "authorized_keys_list", "user": "monitor"},
       answer="/home/monitor/.ssh/authorized_keys: 3 entries\nssh-ed25519 AAAAC3... monitor@old-collector\nssh-ed25519 AAAAC3... monitor@new-collector"),
    V2(id="ssh_keys-authorized_keys_list-v2-0009", tool="ssh_keys", operation="authorized_keys_list",
       complexity="single",
       user_input="check which public keys are trusted for the etl_svc account",
       args={"operation": "authorized_keys_list", "user": "etl_svc"},
       answer="/home/etl_svc/.ssh/authorized_keys: 1 entry\nssh-ed25519 AAAAC3... etl-pipeline@warehouse"),

    V2(id="ssh_keys-authorized_keys_add-v2-0001", tool="ssh_keys", operation="authorized_keys_add",
       complexity="single",
       user_input="Add 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGx... jdoe@workstation' to the deploy user's authorized_keys.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGx... jdoe@workstation", "user": "deploy"},
       answer="Key appended to /home/deploy/.ssh/authorized_keys.\nFile now has 4 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0002", tool="ssh_keys", operation="authorized_keys_add",
       complexity="diagnostic",
       user_input="The new bastion host at 10.20.0.5 can't reach the app tier because its key was never added to root's authorized_keys — add 'ssh-ed25519 AAAAC3... bastion@edge02' now.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... bastion@edge02", "user": "root"},
       answer="Key appended to /root/.ssh/authorized_keys.\nFile now has 3 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0003", tool="ssh_keys", operation="authorized_keys_add",
       complexity="single",
       user_input="allow the new sysadmin to log in as admin, add 'ssh-rsa AAAAB3NzaC1yc2E... newadmin@laptop'",
       args={"operation": "authorized_keys_add", "key": "ssh-rsa AAAAB3NzaC1yc2E... newadmin@laptop", "user": "admin"},
       answer="Key appended to /home/admin/.ssh/authorized_keys.\nFile now has 3 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0004", tool="ssh_keys", operation="authorized_keys_add",
       complexity="multi",
       user_input="Add the backup server's key 'ssh-ed25519 AAAAC3... backup02@backup-svc' to the backupuser account and then list the file to verify.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... backup02@backup-svc", "user": "backupuser"},
       answer="Key appended to /home/backupuser/.ssh/authorized_keys.\nFile now has 2 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0005", tool="ssh_keys", operation="authorized_keys_add",
       complexity="single",
       user_input="the monitoring collector can't connect, add its key 'ssh-ed25519 AAAAC3... monitor@collector03' to the monitor user",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... monitor@collector03", "user": "monitor"},
       answer="Key appended to /home/monitor/.ssh/authorized_keys.\nFile now has 4 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0006", tool="ssh_keys", operation="authorized_keys_add",
       complexity="single",
       user_input="Add the shared ops key 'ssh-ed25519 AAAAC3... ops-team@shared' to the appuser account.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... ops-team@shared", "user": "appuser"},
       answer="Key appended to /home/appuser/.ssh/authorized_keys.\nFile now has 2 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0007", tool="ssh_keys", operation="authorized_keys_add",
       complexity="multi",
       user_input="Add the new gitlab-runner key 'ssh-ed25519 AAAAC3... runner@ci-host2' to root and then show the full authorized_keys.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... runner@ci-host2", "user": "root"},
       answer="Key appended to /root/.ssh/authorized_keys.\nFile now has 3 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0008", tool="ssh_keys", operation="authorized_keys_add",
       complexity="diagnostic",
       user_input="A rehired employee's laptop was never re-provisioned for the ansible account and their pull requests keep failing over SSH — add their new key 'ssh-ed25519 AAAAC3... jsmith@newlaptop'.",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... jsmith@newlaptop", "user": "ansible"},
       answer="Key appended to /home/ansible/.ssh/authorized_keys.\nFile now has 3 entries."),
    V2(id="ssh_keys-authorized_keys_add-v2-0009", tool="ssh_keys", operation="authorized_keys_add",
       complexity="single",
       user_input="add key 'ssh-ed25519 AAAAC3... etl-pipeline2@warehouse' to etl_svc's authorized_keys",
       args={"operation": "authorized_keys_add", "key": "ssh-ed25519 AAAAC3... etl-pipeline2@warehouse", "user": "etl_svc"},
       answer="Key appended to /home/etl_svc/.ssh/authorized_keys.\nFile now has 2 entries."),

    V2(id="ssh_keys-authorized_keys_remove-v2-0001", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="single",
       user_input="Remove the key commented 'jdoe@workstation' from the deploy user's authorized_keys.",
       args={"operation": "authorized_keys_remove", "key_comment": "jdoe@workstation", "user": "deploy"},
       answer="1 matching entry removed from /home/deploy/.ssh/authorized_keys.\nFile now has 2 entries."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0002", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="diagnostic",
       user_input="The pen test report flagged an unknown key labeled 'attacker@unknown' in the admin user's authorized_keys — that needs to come out immediately.",
       args={"operation": "authorized_keys_remove", "key_comment": "attacker@unknown", "user": "admin"},
       answer="1 matching entry removed from /home/admin/.ssh/authorized_keys.\nFile now has 1 entry."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0003", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="single",
       user_input="revoke the key 'contractor@external-firm' from appuser's authorized_keys",
       args={"operation": "authorized_keys_remove", "key_comment": "contractor@external-firm", "user": "appuser"},
       answer="1 matching entry removed from /home/appuser/.ssh/authorized_keys.\nFile now has 1 entry."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0004", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="multi",
       user_input="Remove the compromised key 'backup-old@backup01' from root and then confirm it's actually gone.",
       args={"operation": "authorized_keys_remove", "key_comment": "backup-old@backup01", "user": "root"},
       answer="1 matching entry removed from /root/.ssh/authorized_keys.\nFile now has 2 entries."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0005", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="single",
       user_input="the ex-employee's key with comment 'msmith@oldlaptop' needs to be pulled from the ansible user's authorized_keys",
       args={"operation": "authorized_keys_remove", "key_comment": "msmith@oldlaptop", "user": "ansible"},
       answer="1 matching entry removed from /home/ansible/.ssh/authorized_keys.\nFile now has 1 entry."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0006", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="single",
       user_input="Strip every key with the comment 'temp-access' out of the deploy user's authorized_keys.",
       args={"operation": "authorized_keys_remove", "key_comment": "temp-access", "user": "deploy"},
       answer="2 matching entries removed from /home/deploy/.ssh/authorized_keys.\nFile now has 1 entry."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0007", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="diagnostic",
       user_input="Offboarding checklist for the departed contractor says their key comment was 'contractor2@laptop' — has it actually been removed from root's authorized_keys, and remove it if not?",
       args={"operation": "authorized_keys_remove", "key_comment": "contractor2@laptop", "user": "root"},
       answer="1 matching entry removed from /root/.ssh/authorized_keys.\nFile now has 2 entries."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0008", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="multi",
       user_input="Remove the key labeled 'ci-old@jenkins' from the jenkins user's authorized_keys, then confirm only the new one is left.",
       args={"operation": "authorized_keys_remove", "key_comment": "ci-old@jenkins", "user": "jenkins"},
       answer="1 matching entry removed from /home/jenkins/.ssh/authorized_keys.\nFile now has 1 entry."),
    V2(id="ssh_keys-authorized_keys_remove-v2-0009", tool="ssh_keys", operation="authorized_keys_remove",
       complexity="single",
       user_input="remove the stale key 'monitor@old-collector' from the monitor user's authorized_keys",
       args={"operation": "authorized_keys_remove", "key_comment": "monitor@old-collector", "user": "monitor"},
       answer="1 matching entry removed from /home/monitor/.ssh/authorized_keys.\nFile now has 2 entries."),

    V2(id="ssh_keys-known_hosts_list-v2-0001", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="Show the known_hosts entries for root.",
       args={"operation": "known_hosts_list", "user": "root"},
       answer="/root/.ssh/known_hosts: 6 entries\nprod-db01.example.com ssh-ed25519 AAAAC3...\napp01.example.com ssh-rsa AAAAB3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0002", tool="ssh_keys", operation="known_hosts_list",
       complexity="diagnostic",
       user_input="A deploy script for the deploy user keeps failing with 'host key verification failed' against git.company.com — what does its known_hosts actually have on file?",
       args={"operation": "known_hosts_list", "user": "deploy"},
       answer="/home/deploy/.ssh/known_hosts: 4 entries\ngit.company.com ssh-ed25519 AAAAC3...\napp01.example.com ssh-rsa AAAAB3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0003", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="what hosts does the ansible user already trust",
       args={"operation": "known_hosts_list", "user": "ansible"},
       answer="/home/ansible/.ssh/known_hosts: 12 entries\nprod-db01.example.com ssh-ed25519 AAAAC3...\n192.168.1.100 ssh-rsa AAAAB3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0004", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="Dump the backup user's known_hosts file, we're checking for stale entries.",
       args={"operation": "known_hosts_list", "user": "backupuser"},
       answer="/home/backupuser/.ssh/known_hosts: 3 entries\nbackup.internal ssh-ed25519 AAAAC3...\nstorage02.internal ssh-rsa AAAAB3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0005", tool="ssh_keys", operation="known_hosts_list",
       complexity="diagnostic",
       user_input="The jenkins user's git clone step just started throwing REMOTE HOST IDENTIFICATION HAS CHANGED for git.company.com — check what's currently trusted before we touch anything.",
       args={"operation": "known_hosts_list", "user": "jenkins"},
       answer="/home/jenkins/.ssh/known_hosts: 5 entries\ngit.company.com ssh-rsa AAAAB3...\napp02.example.com ssh-ed25519 AAAAC3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0006", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="show the known hosts for the admin account, I want a list of all trusted servers",
       args={"operation": "known_hosts_list", "user": "admin"},
       answer="/home/admin/.ssh/known_hosts: 9 entries\nbastion.example.com ssh-ed25519 AAAAC3...\nvpn-gw.example.com ssh-rsa AAAAB3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0007", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="check the etl_svc user's known_hosts for the warehouse host entry",
       args={"operation": "known_hosts_list", "user": "etl_svc"},
       answer="/home/etl_svc/.ssh/known_hosts: 2 entries\nwarehouse-db.internal ssh-ed25519 AAAAC3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0008", tool="ssh_keys", operation="known_hosts_list",
       complexity="multi",
       user_input="List the netops user's known_hosts, then remove the entry for the switch that got RMA'd.",
       args={"operation": "known_hosts_list", "user": "netops"},
       answer="/home/netops/.ssh/known_hosts: 15 entries\nsw-core-01.internal ssh-rsa AAAAB3...\nsw-core-02.internal ssh-ed25519 AAAAC3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0009", tool="ssh_keys", operation="known_hosts_list",
       complexity="single",
       user_input="what's in the monitor user's known_hosts file",
       args={"operation": "known_hosts_list", "user": "monitor"},
       answer="/home/monitor/.ssh/known_hosts: 7 entries\ncollector01.internal ssh-ed25519 AAAAC3..."),
    V2(id="ssh_keys-known_hosts_list-v2-0010", tool="ssh_keys", operation="known_hosts_list",
       complexity="diagnostic",
       user_input="Compliance is asking whether root trusts any hosts outside the documented inventory — pull the full known_hosts list so we can cross-check.",
       args={"operation": "known_hosts_list", "user": "root"},
       answer="/root/.ssh/known_hosts: 6 entries\nprod-db01.example.com ssh-ed25519 AAAAC3...\n203.0.113.9 ssh-rsa AAAAB3..."),

    V2(id="ssh_keys-known_hosts_remove-v2-0001", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="Remove 'prod-db01.example.com' from root's known_hosts, the box was rebuilt with a new host key.",
       args={"operation": "known_hosts_remove", "hostname": "prod-db01.example.com", "user": "root"},
       answer="Host prod-db01.example.com removed from /root/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0002", tool="ssh_keys", operation="known_hosts_remove",
       complexity="diagnostic",
       user_input="The ansible playbook is refusing to connect with REMOTE HOST IDENTIFICATION HAS CHANGED for app01.example.com — clear that stale entry out of root's known_hosts.",
       args={"operation": "known_hosts_remove", "hostname": "app01.example.com", "user": "root"},
       answer="Host app01.example.com removed from /root/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0003", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="the staging box IP changed, remove '10.0.0.50' from the deploy user's known_hosts",
       args={"operation": "known_hosts_remove", "hostname": "10.0.0.50", "user": "deploy"},
       answer="Host 10.0.0.50 removed from /home/deploy/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0004", tool="ssh_keys", operation="known_hosts_remove",
       complexity="multi",
       user_input="Remove the stale entry for 'backup.internal' from the backupuser account and then retry the connection.",
       args={"operation": "known_hosts_remove", "hostname": "backup.internal", "user": "backupuser"},
       answer="Host backup.internal removed from /home/backupuser/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0005", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="clear the entry for 'git.company.com' from jenkins' known_hosts, the git server migrated to new hardware",
       args={"operation": "known_hosts_remove", "hostname": "git.company.com", "user": "jenkins"},
       answer="Host git.company.com removed from /home/jenkins/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0006", tool="ssh_keys", operation="known_hosts_remove",
       complexity="multi",
       user_input="Remove the entry for '192.168.1.100' from the ansible user's known_hosts since that address was reassigned, then list the file to confirm.",
       args={"operation": "known_hosts_remove", "hostname": "192.168.1.100", "user": "ansible"},
       answer="Host 192.168.1.100 removed from /home/ansible/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0007", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="remove the switch entry 'sw-core-02.internal' from the netops user's known_hosts, it was replaced",
       args={"operation": "known_hosts_remove", "hostname": "sw-core-02.internal", "user": "netops"},
       answer="Host sw-core-02.internal removed from /home/netops/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0008", tool="ssh_keys", operation="known_hosts_remove",
       complexity="diagnostic",
       user_input="The warehouse host got reimaged over the weekend and now etl_svc's sync job refuses to connect — prune 'warehouse-db.internal' from its known_hosts.",
       args={"operation": "known_hosts_remove", "hostname": "warehouse-db.internal", "user": "etl_svc"},
       answer="Host warehouse-db.internal removed from /home/etl_svc/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0009", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="drop 'vpn-gw.example.com' from the admin user's known_hosts, the gateway certificate was reissued",
       args={"operation": "known_hosts_remove", "hostname": "vpn-gw.example.com", "user": "admin"},
       answer="Host vpn-gw.example.com removed from /home/admin/.ssh/known_hosts.\n1 line pruned."),
    V2(id="ssh_keys-known_hosts_remove-v2-0010", tool="ssh_keys", operation="known_hosts_remove",
       complexity="single",
       user_input="Remove the collector01.internal entry from monitor's known_hosts since we decommissioned that host.",
       args={"operation": "known_hosts_remove", "hostname": "collector01.internal", "user": "monitor"},
       answer="Host collector01.internal removed from /home/monitor/.ssh/known_hosts.\n1 line pruned."),

    V2(id="ssh_keys-sshd_config_audit-v2-0001", tool="ssh_keys", operation="sshd_config_audit",
       complexity="single",
       user_input="Show the effective sshd configuration on this server.",
       args={"operation": "sshd_config_audit"},
       answer="port 22\npermitrootlogin no\npasswordauthentication no\nmaxauthtries 3"),
    V2(id="ssh_keys-sshd_config_audit-v2-0002", tool="ssh_keys", operation="sshd_config_audit",
       complexity="diagnostic",
       user_input="A security scanner flagged this host as possibly allowing root to log in over SSH — check the actual effective setting.",
       args={"operation": "sshd_config_audit"},
       answer="port 22\npermitrootlogin no\npasswordauthentication no\nmaxauthtries 4"),
    V2(id="ssh_keys-sshd_config_audit-v2-0003", tool="ssh_keys", operation="sshd_config_audit",
       complexity="single",
       user_input="is password auth enabled for sshd right now",
       args={"operation": "sshd_config_audit"},
       answer="port 22\npasswordauthentication no\npubkeyauthentication yes"),
    V2(id="ssh_keys-sshd_config_audit-v2-0004", tool="ssh_keys", operation="sshd_config_audit",
       complexity="diagnostic",
       user_input="Users report getting locked out after a handful of failed logins — what are MaxAuthTries and LoginGraceTime actually set to on this box?",
       args={"operation": "sshd_config_audit"},
       answer="maxauthtries 3\nlogingracetime 30\npermitrootlogin no"),
    V2(id="ssh_keys-sshd_config_audit-v2-0005", tool="ssh_keys", operation="sshd_config_audit",
       complexity="single",
       user_input="what port is sshd actually listening on",
       args={"operation": "sshd_config_audit"},
       answer="port 2222\naddressfamily any\npermitrootlogin no"),
    V2(id="ssh_keys-sshd_config_audit-v2-0006", tool="ssh_keys", operation="sshd_config_audit",
       complexity="diagnostic",
       user_input="Compliance wants confirmation the CIS hardening baseline is actually applied here, not just in the config template — pull the live effective sshd settings.",
       args={"operation": "sshd_config_audit"},
       answer="port 22\npermitrootlogin no\npasswordauthentication no\nx11forwarding no\nmaxauthtries 3"),
    V2(id="ssh_keys-sshd_config_audit-v2-0007", tool="ssh_keys", operation="sshd_config_audit",
       complexity="single",
       user_input="check whether X11 forwarding and SSH forwarding of the local key store are turned off in the running sshd config",
       args={"operation": "sshd_config_audit"},
       answer="x11forwarding no\nallowagentforwarding no\npermitrootlogin no"),
    V2(id="ssh_keys-sshd_config_audit-v2-0008", tool="ssh_keys", operation="sshd_config_audit",
       complexity="single",
       user_input="Give me the full running sshd config for the change ticket attachment.",
       args={"operation": "sshd_config_audit"},
       answer="port 22\npermitrootlogin no\npasswordauthentication no\npubkeyauthentication yes\nmaxauthtries 3\nx11forwarding no"),
    V2(id="ssh_keys-sshd_config_audit-v2-0009", tool="ssh_keys", operation="sshd_config_audit",
       complexity="diagnostic",
       user_input="Firewall rules look fine and nftables shows the port open, but SSH logins are still failing for everyone — check the effective sshd settings for anything that would reject connections outright.",
       args={"operation": "sshd_config_audit"},
       answer="port 22\ndenyusers *\npermitrootlogin no\npasswordauthentication no"),
]

from finetune.scenarios_v2 import check_module; check_module("ssh_keys", SCENARIOS_V2)
