"""finetune/scenarios_v2/sssd.py — corpus v2 scenarios for 'sssd'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id='sssd-status-v2-0001', tool='sssd', operation='status',
       complexity='single',
       user_input='is the sssd daemon actually running?',
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420'),
    V2(id='sssd-status-v2-0002', tool='sssd', operation='status',
       complexity='diagnostic',
       user_input="users can't log in with domain accounts, first check if sssd is even up",
       args={'operation': 'status'},
       answer='sssd.service: inactive (dead) -- likely cause'),
    V2(id='sssd-status-v2-0003', tool='sssd', operation='status',
       complexity='single',
       user_input='check sssd health on this host',
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420'),
    V2(id='sssd-status-v2-0004', tool='sssd', operation='status',
       complexity='diagnostic',
       user_input='sudo is failing for a domain account, is sssd healthy?',
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420, domain corp.example.com online'),
    V2(id='sssd-status-v2-0005', tool='sssd', operation='status',
       complexity='single',
       user_input='give me the systemd status for sssd',
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420, uptime 4d'),
    V2(id='sssd-status-v2-0006', tool='sssd', operation='status',
       complexity='diagnostic',
       user_input="getent isn't resolving domain users, is sssd running at all?",
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420'),
    V2(id='sssd-status-v2-0007', tool='sssd', operation='status',
       complexity='single',
       user_input='status of sssd, please',
       args={'operation': 'status'},
       answer='sssd.service: active (running), pid 1420'),
    V2(id='sssd-status-v2-0008', tool='sssd', operation='status',
       complexity='diagnostic',
       user_input='domain logins started failing right after the reboot, check sssd status first',
       args={'operation': 'status'},
       answer='sssd.service: failed (exit code 1) -- crashed on start'),
    V2(id='sssd-id_lookup-v2-0009', tool='sssd', operation='id_lookup',
       complexity='single',
       user_input='look up the identity of jdoe',
       args={'operation': 'id_lookup', 'user': 'jdoe'},
       answer='uid=145601(jdoe) gid=145600(domain users) groups=145600,20045(vpn-users)'),
    V2(id='sssd-id_lookup-v2-0010', tool='sssd', operation='id_lookup',
       complexity='diagnostic',
       user_input="a domain user can't access /data, check their identity and groups first",
       args={'operation': 'id_lookup', 'user': 'mwilliams'},
       answer='uid=145812(mwilliams) gid=145600(domain users) groups=145600 -- no access to data-share group'),
    V2(id='sssd-id_lookup-v2-0011', tool='sssd', operation='id_lookup',
       complexity='single',
       user_input='what uid and gid does the account svcbackup have?',
       args={'operation': 'id_lookup', 'user': 'svcbackup'},
       answer='uid=145900(svcbackup) gid=145600(domain users)'),
    V2(id='sssd-id_lookup-v2-0012', tool='sssd', operation='id_lookup',
       complexity='single',
       user_input='show the groups for bob.jones',
       args={'operation': 'id_lookup', 'user': 'bob.jones'},
       answer='uid=146002(bob.jones) gid=145600(domain users) groups=145600,20033(sudoers-tier2)'),
    V2(id='sssd-id_lookup-v2-0013', tool='sssd', operation='id_lookup',
       complexity='diagnostic',
       user_input="sudo says the user dan isn't in sudoers, confirm his identity and group membership",
       args={'operation': 'id_lookup', 'user': 'dan'},
       answer='uid=146110(dan) gid=145600(domain users) groups=145600 -- not in any sudoers-tier group'),
    V2(id='sssd-id_lookup-v2-0014', tool='sssd', operation='id_lookup',
       complexity='single',
       user_input='look up the identity of frank@corp.example.com',
       args={'operation': 'id_lookup', 'user': 'frank@corp.example.com'},
       answer='uid=146200(frank@corp.example.com) gid=145600(domain users) groups=145600'),
    V2(id='sssd-id_lookup-v2-0015', tool='sssd', operation='id_lookup',
       complexity='diagnostic',
       user_input='getent is showing a different uid than the id command for grace, look her up to compare',
       args={'operation': 'id_lookup', 'user': 'grace'},
       answer='uid=146301(grace) gid=145600(domain users) groups=145600,20010(finance)'),
    V2(id='sssd-cache_flush-v2-0016', tool='sssd', operation='cache_flush',
       complexity='single',
       user_input='flush the sssd identity cache',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0017', tool='sssd', operation='cache_flush',
       complexity='diagnostic',
       user_input="a user's AD group membership changed but this box still shows the old groups, clear the cache",
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0018', tool='sssd', operation='cache_flush',
       complexity='single',
       user_input='clear the sssd cache entirely',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0019', tool='sssd', operation='cache_flush',
       complexity='multi',
       user_input='flush the sssd cache and then look up carol to confirm the new group data comes through',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0020', tool='sssd', operation='cache_flush',
       complexity='diagnostic',
       user_input="users are seeing stale auth failures even after an AD password reset, flush sssd's cache",
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0021', tool='sssd', operation='cache_flush',
       complexity='single',
       user_input='invalidate the whole identity cache for sssd',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0022', tool='sssd', operation='cache_flush',
       complexity='single',
       user_input='run a full sss_cache flush',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0023', tool='sssd', operation='cache_flush',
       complexity='diagnostic',
       user_input='a deprovisioned account is still resolving locally, could the cache be stale? flush it',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-cache_flush-v2-0024', tool='sssd', operation='cache_flush',
       complexity='single',
       user_input='clear cached identities in sssd',
       args={'operation': 'cache_flush'},
       answer='sss_cache -E\ncache flushed for all domains'),
    V2(id='sssd-realm_list-v2-0025', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='show me the realms this host is enrolled in',
       args={'operation': 'realm_list'},
       answer='realm-list: corp.example.com (configured, kerberos-member)'),
    V2(id='sssd-realm_list-v2-0026', tool='sssd', operation='realm_list',
       complexity='diagnostic',
       user_input='domain auth broke after the rebuild, list the enrolled realms to check the join',
       args={'operation': 'realm_list'},
       answer='realm-list: (none) -- host is not currently joined to any realm'),
    V2(id='sssd-realm_list-v2-0027', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='which AD domain is this server joined to?',
       args={'operation': 'realm_list'},
       answer='realm-list: corp.example.com (configured, kerberos-member)'),
    V2(id='sssd-realm_list-v2-0028', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='list all configured realms',
       args={'operation': 'realm_list'},
       answer='realm-list: corp.example.com (configured, kerberos-member)'),
    V2(id='sssd-realm_list-v2-0029', tool='sssd', operation='realm_list',
       complexity='diagnostic',
       user_input='is this box actually joined to idm.internal or did the join silently fail?',
       args={'operation': 'realm_list'},
       answer='realm-list: (none) -- not joined to idm.internal or any realm'),
    V2(id='sssd-realm_list-v2-0030', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='show enrolled realms on this node',
       args={'operation': 'realm_list'},
       answer='realm-list: idm.internal (configured, sssd)'),
    V2(id='sssd-realm_list-v2-0031', tool='sssd', operation='realm_list',
       complexity='diagnostic',
       user_input='after the reimage, what domain if any is this host part of?',
       args={'operation': 'realm_list'},
       answer='realm-list: (none)'),
    V2(id='sssd-realm_list-v2-0032', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='list the AD/IdM realms discovered by this host',
       args={'operation': 'realm_list'},
       answer='realm-list: corp.example.com (configured)'),
    V2(id='sssd-realm_list-v2-0033', tool='sssd', operation='realm_list',
       complexity='single',
       user_input='what realm is this machine currently joined to?',
       args={'operation': 'realm_list'},
       answer='realm-list: corp.example.com (configured, kerberos-member)'),
    V2(id='sssd-realm_join-v2-0034', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='join this server to corp.example.com',
       args={'operation': 'realm_join', 'domain': 'corp.example.com'},
       answer='realm join corp.example.com: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0035', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='enroll this host in the idm.internal domain',
       args={'operation': 'realm_join', 'domain': 'idm.internal'},
       answer='realm join idm.internal: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0036', tool='sssd', operation='realm_join',
       complexity='diagnostic',
       user_input='this server was re-imaged and lost domain membership, rejoin it to corp.example.com',
       args={'operation': 'realm_join', 'domain': 'corp.example.com'},
       answer='realm join corp.example.com: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0037', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='join this machine to ad.company.org',
       args={'operation': 'realm_join', 'domain': 'ad.company.org'},
       answer='realm join ad.company.org: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0038', tool='sssd', operation='realm_join',
       complexity='multi',
       user_input='join corp.example.com and then flush the sssd cache afterward',
       args={'operation': 'realm_join', 'domain': 'corp.example.com'},
       answer='realm join corp.example.com: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0039', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='enroll this node in dc.infra.local',
       args={'operation': 'realm_join', 'domain': 'dc.infra.local'},
       answer='realm join dc.infra.local: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0040', tool='sssd', operation='realm_join',
       complexity='diagnostic',
       user_input='the sudo/login failures are because this box was never joined, join it to test.lab now for QA',
       args={'operation': 'realm_join', 'domain': 'test.lab'},
       answer='realm join test.lab: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0041', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='join this host to the datacenter realm prod.corp.com',
       args={'operation': 'realm_join', 'domain': 'prod.corp.com'},
       answer='realm join prod.corp.com: joined successfully, kerberos-member'),
    V2(id='sssd-realm_join-v2-0042', tool='sssd', operation='realm_join',
       complexity='single',
       user_input='add this server to the corp.example.com Active Directory domain',
       args={'operation': 'realm_join', 'domain': 'corp.example.com'},
       answer='realm join corp.example.com: joined successfully, kerberos-member'),
    V2(id='sssd-realm_leave-v2-0043', tool='sssd', operation='realm_leave',
       complexity='single',
       user_input='remove this server from corp.example.com',
       args={'operation': 'realm_leave', 'domain': 'corp.example.com'},
       answer='realm leave corp.example.com: left successfully, domain logins now unavailable'),
    V2(id='sssd-realm_leave-v2-0044', tool='sssd', operation='realm_leave',
       complexity='single',
       user_input='leave the idm.internal realm',
       args={'operation': 'realm_leave', 'domain': 'idm.internal'},
       answer='realm leave idm.internal: left successfully, domain logins now unavailable'),
    V2(id='sssd-realm_leave-v2-0045', tool='sssd', operation='realm_leave',
       complexity='diagnostic',
       user_input='this server is being decommissioned, take it off corp.example.com',
       args={'operation': 'realm_leave', 'domain': 'corp.example.com'},
       answer='realm leave corp.example.com: left successfully, domain logins now unavailable'),
    V2(id='sssd-realm_leave-v2-0046', tool='sssd', operation='realm_leave',
       complexity='single',
       user_input='unenroll this machine from ad.company.org',
       args={'operation': 'realm_leave', 'domain': 'ad.company.org'},
       answer='realm leave ad.company.org: left successfully, domain logins now unavailable'),
    V2(id='sssd-realm_leave-v2-0047', tool='sssd', operation='realm_leave',
       complexity='multi',
       user_input='leave the current domain corp.example.com and then join prod.corp.com instead',
       args={'operation': 'realm_leave', 'domain': 'corp.example.com'},
       answer='realm leave corp.example.com: left successfully, domain logins now unavailable'),
    V2(id='sssd-realm_leave-v2-0048', tool='sssd', operation='realm_leave',
       complexity='single',
       user_input='detach this node from the dc.infra.local Active Directory realm',
       args={'operation': 'realm_leave', 'domain': 'dc.infra.local'},
       answer='realm leave dc.infra.local: left successfully, domain logins now unavailable'),
]

from finetune.scenarios_v2 import check_module; check_module('sssd', SCENARIOS_V2)
