"""finetune/scenarios_v2/stratis.py — corpus v2 scenarios for 'stratis'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # pool-list (9)
    V2(id="stratis-pool-list-v2-0001", tool="stratis", operation="pool-list",
       complexity="single",
       user_input="What stratis pools are configured on this host?",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\ndatapool   500 GiB\nlogpool    100 GiB"),
    V2(id="stratis-pool-list-v2-0002", tool="stratis", operation="pool-list",
       complexity="diagnostic",
       user_input="The app server reports its stratis-backed volume is missing — first confirm what pools even exist.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\ndatapool   500 GiB\n(no volumepool present)"),
    V2(id="stratis-pool-list-v2-0003", tool="stratis", operation="pool-list",
       complexity="single",
       user_input="List all stratis storage pools with their capacity.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\nprodpool   2 TiB"),
    V2(id="stratis-pool-list-v2-0004", tool="stratis", operation="pool-list",
       complexity="single",
       user_input="Check available stratis pools.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\nbackuppool 750 GiB"),
    V2(id="stratis-pool-list-v2-0005", tool="stratis", operation="pool-list",
       complexity="multi",
       user_input="Show the stratis pools, then list the filesystems inside prodpool.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\nprodpool   2 TiB"),
    V2(id="stratis-pool-list-v2-0006", tool="stratis", operation="pool-list",
       complexity="diagnostic",
       user_input="I think Stratis is set up on this box but I'm not sure what's actually provisioned — pull the pool list.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\nhomespool  300 GiB"),
    V2(id="stratis-pool-list-v2-0007", tool="stratis", operation="pool-list",
       complexity="single",
       user_input="stratis pool list, please.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\ntestpool   50 GiB"),
    V2(id="stratis-pool-list-v2-0008", tool="stratis", operation="pool-list",
       complexity="single",
       user_input="Give me the list of Stratis pools on this system.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\napppool    1 TiB\nlogpool    100 GiB"),
    V2(id="stratis-pool-list-v2-0009", tool="stratis", operation="pool-list",
       complexity="diagnostic",
       user_input="LVM shows no free extents but I recall we moved some disks to stratis — confirm which pools are using them now.",
       args={"operation": "pool-list"},
       answer="Name       Total Physical\ndevpool    200 GiB"),
    # pool-create (8)
    V2(id="stratis-pool-create-v2-0001", tool="stratis", operation="pool-create",
       complexity="single",
       user_input="Create a stratis pool called mediapool on /dev/sdc.",
       args={"operation": "pool-create", "pool": "mediapool", "blockdev": "/dev/sdc"},
       answer="Pool 'mediapool' created on /dev/sdc"),
    V2(id="stratis-pool-create-v2-0002", tool="stratis", operation="pool-create",
       complexity="single",
       user_input="Set up a new stratis pool named etlpool using /dev/nvme2n1.",
       args={"operation": "pool-create", "pool": "etlpool", "blockdev": "/dev/nvme2n1"},
       answer="Pool 'etlpool' created on /dev/nvme2n1"),
    V2(id="stratis-pool-create-v2-0003", tool="stratis", operation="pool-create",
       complexity="diagnostic",
       user_input="The new /dev/sdd disk was just added to this host — provision it as a stratis pool called scratchpool.",
       args={"operation": "pool-create", "pool": "scratchpool", "blockdev": "/dev/sdd"},
       answer="Pool 'scratchpool' created on /dev/sdd"),
    V2(id="stratis-pool-create-v2-0004", tool="stratis", operation="pool-create",
       complexity="single",
       user_input="Make a stratis pool named vmpool on /dev/vdc for VM disk images.",
       args={"operation": "pool-create", "pool": "vmpool", "blockdev": "/dev/vdc"},
       answer="Pool 'vmpool' created on /dev/vdc"),
    V2(id="stratis-pool-create-v2-0005", tool="stratis", operation="pool-create",
       complexity="multi",
       user_input="Create pool reportpool on /dev/sde and then create a filesystem called monthly inside it.",
       args={"operation": "pool-create", "pool": "reportpool", "blockdev": "/dev/sde"},
       answer="Pool 'reportpool' created on /dev/sde"),
    V2(id="stratis-pool-create-v2-0006", tool="stratis", operation="pool-create",
       complexity="single",
       user_input="Create a stratis storage pool named archivepool on /dev/sdf.",
       args={"operation": "pool-create", "pool": "archivepool", "blockdev": "/dev/sdf"},
       answer="Pool 'archivepool' created on /dev/sdf"),
    V2(id="stratis-pool-create-v2-0007", tool="stratis", operation="pool-create",
       complexity="single",
       user_input="Provision a new stratis pool called ciartifacts on /dev/nvme3n1 for build artifacts.",
       args={"operation": "pool-create", "pool": "ciartifacts", "blockdev": "/dev/nvme3n1"},
       answer="Pool 'ciartifacts' created on /dev/nvme3n1"),
    V2(id="stratis-pool-create-v2-0008", tool="stratis", operation="pool-create",
       complexity="diagnostic",
       user_input="We're running out of space on the existing LVM volumes — spin up a fresh stratis pool named growpool on /dev/sdg to take the overflow.",
       args={"operation": "pool-create", "pool": "growpool", "blockdev": "/dev/sdg"},
       answer="Pool 'growpool' created on /dev/sdg"),
    # pool-destroy (10)
    V2(id="stratis-pool-destroy-v2-0001", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Destroy the mediapool stratis pool, it's no longer needed.",
       args={"operation": "pool-destroy", "pool": "mediapool"},
       answer="Pool 'mediapool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0002", tool="stratis", operation="pool-destroy",
       complexity="diagnostic",
       user_input="The disk under scratchpool has been throwing SMART errors and we're about to swap it — tear down the pool first.",
       args={"operation": "pool-destroy", "pool": "scratchpool"},
       answer="Pool 'scratchpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0003", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Remove the etlpool pool, that project got cancelled.",
       args={"operation": "pool-destroy", "pool": "etlpool"},
       answer="Pool 'etlpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0004", tool="stratis", operation="pool-destroy",
       complexity="multi",
       user_input="Confirm testpool has no filesystems left, then destroy it.",
       args={"operation": "pool-destroy", "pool": "testpool"},
       answer="Pool 'testpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0005", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Tear down the vmpool stratis pool.",
       args={"operation": "pool-destroy", "pool": "vmpool"},
       answer="Pool 'vmpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0006", tool="stratis", operation="pool-destroy",
       complexity="diagnostic",
       user_input="devpool was only ever used for a dev sandbox that got decommissioned — reclaim the underlying disk by destroying it.",
       args={"operation": "pool-destroy", "pool": "devpool"},
       answer="Pool 'devpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0007", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Destroy archivepool and free its block devices.",
       args={"operation": "pool-destroy", "pool": "archivepool"},
       answer="Pool 'archivepool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0008", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Get rid of growpool.",
       args={"operation": "pool-destroy", "pool": "growpool"},
       answer="Pool 'growpool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0009", tool="stratis", operation="pool-destroy",
       complexity="diagnostic",
       user_input="We migrated everything off homespool onto the new NAS — destroy it so we can repurpose the disk.",
       args={"operation": "pool-destroy", "pool": "homespool"},
       answer="Pool 'homespool' destroyed"),
    V2(id="stratis-pool-destroy-v2-0010", tool="stratis", operation="pool-destroy",
       complexity="single",
       user_input="Destroy the ciartifacts pool.",
       args={"operation": "pool-destroy", "pool": "ciartifacts"},
       answer="Pool 'ciartifacts' destroyed"),
    # filesystem-list (9)
    V2(id="stratis-filesystem-list-v2-0001", tool="stratis", operation="filesystem-list",
       complexity="single",
       user_input="Show all stratis filesystems on this host.",
       args={"operation": "filesystem-list"},
       answer="Pool       Filesystem  Used\ndatapool   appdata     40 GiB\nlogpool    logdata     8 GiB"),
    V2(id="stratis-filesystem-list-v2-0002", tool="stratis", operation="filesystem-list",
       complexity="single",
       user_input="List the filesystems inside the prodpool.",
       args={"operation": "filesystem-list", "pool": "prodpool"},
       answer="Pool       Filesystem  Used\nprodpool   dbdata      120 GiB"),
    V2(id="stratis-filesystem-list-v2-0003", tool="stratis", operation="filesystem-list",
       complexity="diagnostic",
       user_input="A mount point for the backup share is missing — check which filesystems actually exist in backuppool.",
       args={"operation": "filesystem-list", "pool": "backuppool"},
       answer="Pool       Filesystem  Used\nbackuppool backupdata  200 GiB"),
    V2(id="stratis-filesystem-list-v2-0004", tool="stratis", operation="filesystem-list",
       complexity="single",
       user_input="What filesystems live in homespool?",
       args={"operation": "filesystem-list", "pool": "homespool"},
       answer="Pool       Filesystem  Used\nhomespool  homefs      60 GiB"),
    V2(id="stratis-filesystem-list-v2-0005", tool="stratis", operation="filesystem-list",
       complexity="multi",
       user_input="List all stratis filesystems, then tell me which ones are over 100 GiB used.",
       args={"operation": "filesystem-list"},
       answer="Pool       Filesystem  Used\nprodpool   dbdata      120 GiB\nbackuppool backupdata  200 GiB"),
    V2(id="stratis-filesystem-list-v2-0006", tool="stratis", operation="filesystem-list",
       complexity="diagnostic",
       user_input="logpool's mount seems to have failed on boot — confirm the filesystem is actually still there.",
       args={"operation": "filesystem-list", "pool": "logpool"},
       answer="Pool       Filesystem  Used\nlogpool    logdata     8 GiB"),
    V2(id="stratis-filesystem-list-v2-0007", tool="stratis", operation="filesystem-list",
       complexity="single",
       user_input="Show me the filesystems in devpool.",
       args={"operation": "filesystem-list", "pool": "devpool"},
       answer="Pool       Filesystem  Used\ndevpool    devscratch  5 GiB"),
    V2(id="stratis-filesystem-list-v2-0008", tool="stratis", operation="filesystem-list",
       complexity="single",
       user_input="stratis filesystem list across everything.",
       args={"operation": "filesystem-list"},
       answer="Pool       Filesystem  Used\ndatapool   appdata     40 GiB"),
    V2(id="stratis-filesystem-list-v2-0009", tool="stratis", operation="filesystem-list",
       complexity="diagnostic",
       user_input="Before running maintenance on testpool, list what filesystems it currently holds so we know what to snapshot first.",
       args={"operation": "filesystem-list", "pool": "testpool"},
       answer="Pool       Filesystem  Used\ntestpool   testfs      2 GiB"),
    # filesystem-create (9)
    V2(id="stratis-filesystem-create-v2-0001", tool="stratis", operation="filesystem-create",
       complexity="single",
       user_input="Create a stratis filesystem called reports in reportpool.",
       args={"operation": "filesystem-create", "pool": "reportpool", "filesystem": "reports"},
       answer="Filesystem 'reports' created in pool 'reportpool'"),
    V2(id="stratis-filesystem-create-v2-0002", tool="stratis", operation="filesystem-create",
       complexity="single",
       user_input="Set up a new filesystem named vmdisks in vmpool.",
       args={"operation": "filesystem-create", "pool": "vmpool", "filesystem": "vmdisks"},
       answer="Filesystem 'vmdisks' created in pool 'vmpool'"),
    V2(id="stratis-filesystem-create-v2-0003", tool="stratis", operation="filesystem-create",
       complexity="diagnostic",
       user_input="The analytics team needs dedicated storage carved out — create a filesystem named analytics in etlpool for them.",
       args={"operation": "filesystem-create", "pool": "etlpool", "filesystem": "analytics"},
       answer="Filesystem 'analytics' created in pool 'etlpool'"),
    V2(id="stratis-filesystem-create-v2-0004", tool="stratis", operation="filesystem-create",
       complexity="single",
       user_input="Create filesystem ciout in ciartifacts.",
       args={"operation": "filesystem-create", "pool": "ciartifacts", "filesystem": "ciout"},
       answer="Filesystem 'ciout' created in pool 'ciartifacts'"),
    V2(id="stratis-filesystem-create-v2-0005", tool="stratis", operation="filesystem-create",
       complexity="multi",
       user_input="Add a stratis filesystem named monthly to reportpool and then mount it at /srv/reports.",
       args={"operation": "filesystem-create", "pool": "reportpool", "filesystem": "monthly"},
       answer="Filesystem 'monthly' created in pool 'reportpool'"),
    V2(id="stratis-filesystem-create-v2-0006", tool="stratis", operation="filesystem-create",
       complexity="single",
       user_input="Create a stratis filesystem named sandbox in devpool.",
       args={"operation": "filesystem-create", "pool": "devpool", "filesystem": "sandbox"},
       answer="Filesystem 'sandbox' created in pool 'devpool'"),
    V2(id="stratis-filesystem-create-v2-0007", tool="stratis", operation="filesystem-create",
       complexity="single",
       user_input="Create tempdata filesystem inside growpool.",
       args={"operation": "filesystem-create", "pool": "growpool", "filesystem": "tempdata"},
       answer="Filesystem 'tempdata' created in pool 'growpool'"),
    V2(id="stratis-filesystem-create-v2-0008", tool="stratis", operation="filesystem-create",
       complexity="diagnostic",
       user_input="We need a spot for postgres to write WAL segments — create a filesystem named waldata in prodpool.",
       args={"operation": "filesystem-create", "pool": "prodpool", "filesystem": "waldata"},
       answer="Filesystem 'waldata' created in pool 'prodpool'"),
    V2(id="stratis-filesystem-create-v2-0009", tool="stratis", operation="filesystem-create",
       complexity="multi",
       user_input="Create filesystem media in mediapool and list the pool's filesystems afterward to confirm.",
       args={"operation": "filesystem-create", "pool": "mediapool", "filesystem": "media"},
       answer="Filesystem 'media' created in pool 'mediapool'"),
    # filesystem-snapshot (9)
    V2(id="stratis-filesystem-snapshot-v2-0001", tool="stratis", operation="filesystem-snapshot",
       complexity="single",
       user_input="Snapshot the dbdata filesystem in prodpool as dbdata-pre-patch.",
       args={"operation": "filesystem-snapshot", "pool": "prodpool", "filesystem": "dbdata", "snapshot": "dbdata-pre-patch"},
       answer="Snapshot 'dbdata-pre-patch' of filesystem 'dbdata' created in pool 'prodpool'"),
    V2(id="stratis-filesystem-snapshot-v2-0002", tool="stratis", operation="filesystem-snapshot",
       complexity="diagnostic",
       user_input="We're about to run a risky schema migration on the waldata filesystem in prodpool — snapshot it first as waldata-before-migration.",
       args={"operation": "filesystem-snapshot", "pool": "prodpool", "filesystem": "waldata", "snapshot": "waldata-before-migration"},
       answer="Snapshot 'waldata-before-migration' of filesystem 'waldata' created in pool 'prodpool'"),
    V2(id="stratis-filesystem-snapshot-v2-0003", tool="stratis", operation="filesystem-snapshot",
       complexity="single",
       user_input="Take a snapshot of homefs in homespool called homefs-weekly.",
       args={"operation": "filesystem-snapshot", "pool": "homespool", "filesystem": "homefs", "snapshot": "homefs-weekly"},
       answer="Snapshot 'homefs-weekly' of filesystem 'homefs' created in pool 'homespool'"),
    V2(id="stratis-filesystem-snapshot-v2-0004", tool="stratis", operation="filesystem-snapshot",
       complexity="single",
       user_input="Create a snapshot named ciout-snap1 of ciout in ciartifacts.",
       args={"operation": "filesystem-snapshot", "pool": "ciartifacts", "filesystem": "ciout", "snapshot": "ciout-snap1"},
       answer="Snapshot 'ciout-snap1' of filesystem 'ciout' created in pool 'ciartifacts'"),
    V2(id="stratis-filesystem-snapshot-v2-0005", tool="stratis", operation="filesystem-snapshot",
       complexity="multi",
       user_input="Snapshot appdata in datapool as appdata-rollback and then verify it shows up in the filesystem list.",
       args={"operation": "filesystem-snapshot", "pool": "datapool", "filesystem": "appdata", "snapshot": "appdata-rollback"},
       answer="Snapshot 'appdata-rollback' of filesystem 'appdata' created in pool 'datapool'"),
    V2(id="stratis-filesystem-snapshot-v2-0006", tool="stratis", operation="filesystem-snapshot",
       complexity="diagnostic",
       user_input="Before we let the intern touch the sandbox filesystem in devpool, snapshot it as sandbox-clean so we can revert if needed.",
       args={"operation": "filesystem-snapshot", "pool": "devpool", "filesystem": "sandbox", "snapshot": "sandbox-clean"},
       answer="Snapshot 'sandbox-clean' of filesystem 'sandbox' created in pool 'devpool'"),
    V2(id="stratis-filesystem-snapshot-v2-0007", tool="stratis", operation="filesystem-snapshot",
       complexity="single",
       user_input="Snapshot logdata in logpool, name it logdata-snap-20260913.",
       args={"operation": "filesystem-snapshot", "pool": "logpool", "filesystem": "logdata", "snapshot": "logdata-snap-20260913"},
       answer="Snapshot 'logdata-snap-20260913' of filesystem 'logdata' created in pool 'logpool'"),
    V2(id="stratis-filesystem-snapshot-v2-0008", tool="stratis", operation="filesystem-snapshot",
       complexity="single",
       user_input="Take a snapshot of backupdata in backuppool called backupdata-snap.",
       args={"operation": "filesystem-snapshot", "pool": "backuppool", "filesystem": "backupdata", "snapshot": "backupdata-snap"},
       answer="Snapshot 'backupdata-snap' of filesystem 'backupdata' created in pool 'backuppool'"),
    V2(id="stratis-filesystem-snapshot-v2-0009", tool="stratis", operation="filesystem-snapshot",
       complexity="multi",
       user_input="Snapshot media in mediapool as media-archive-2026 and then check disk usage on the pool.",
       args={"operation": "filesystem-snapshot", "pool": "mediapool", "filesystem": "media", "snapshot": "media-archive-2026"},
       answer="Snapshot 'media-archive-2026' of filesystem 'media' created in pool 'mediapool'"),
    # filesystem-destroy (10)
    V2(id="stratis-filesystem-destroy-v2-0001", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Destroy the tempdata filesystem in growpool, we're done with it.",
       args={"operation": "filesystem-destroy", "pool": "growpool", "filesystem": "tempdata"},
       answer="Filesystem 'tempdata' destroyed from pool 'growpool'"),
    V2(id="stratis-filesystem-destroy-v2-0002", tool="stratis", operation="filesystem-destroy",
       complexity="diagnostic",
       user_input="The sandbox-clean snapshot in devpool is stale and just taking up space — get rid of it.",
       args={"operation": "filesystem-destroy", "pool": "devpool", "filesystem": "sandbox-clean"},
       answer="Filesystem 'sandbox-clean' destroyed from pool 'devpool'"),
    V2(id="stratis-filesystem-destroy-v2-0003", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Delete the testfs filesystem from testpool, it's no longer needed.",
       args={"operation": "filesystem-destroy", "pool": "testpool", "filesystem": "testfs"},
       answer="Filesystem 'testfs' destroyed from pool 'testpool'"),
    V2(id="stratis-filesystem-destroy-v2-0004", tool="stratis", operation="filesystem-destroy",
       complexity="multi",
       user_input="Unmount ciout-snap1 and then destroy it from ciartifacts.",
       args={"operation": "filesystem-destroy", "pool": "ciartifacts", "filesystem": "ciout-snap1"},
       answer="Filesystem 'ciout-snap1' destroyed from pool 'ciartifacts'"),
    V2(id="stratis-filesystem-destroy-v2-0005", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Remove the dbdata-pre-patch snapshot from prodpool.",
       args={"operation": "filesystem-destroy", "pool": "prodpool", "filesystem": "dbdata-pre-patch"},
       answer="Filesystem 'dbdata-pre-patch' destroyed from pool 'prodpool'"),
    V2(id="stratis-filesystem-destroy-v2-0006", tool="stratis", operation="filesystem-destroy",
       complexity="diagnostic",
       user_input="The migration on waldata went fine, waldata-before-migration in prodpool is stale now — destroy it to free space.",
       args={"operation": "filesystem-destroy", "pool": "prodpool", "filesystem": "waldata-before-migration"},
       answer="Filesystem 'waldata-before-migration' destroyed from pool 'prodpool'"),
    V2(id="stratis-filesystem-destroy-v2-0007", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Destroy the homefs-weekly snapshot in homespool.",
       args={"operation": "filesystem-destroy", "pool": "homespool", "filesystem": "homefs-weekly"},
       answer="Filesystem 'homefs-weekly' destroyed from pool 'homespool'"),
    V2(id="stratis-filesystem-destroy-v2-0008", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Permanently remove the backupdata-snap filesystem from backuppool.",
       args={"operation": "filesystem-destroy", "pool": "backuppool", "filesystem": "backupdata-snap"},
       answer="Filesystem 'backupdata-snap' destroyed from pool 'backuppool'"),
    V2(id="stratis-filesystem-destroy-v2-0009", tool="stratis", operation="filesystem-destroy",
       complexity="diagnostic",
       user_input="logdata-snap-20260913 in logpool was only needed for a one-time audit that's now finished — destroy it.",
       args={"operation": "filesystem-destroy", "pool": "logpool", "filesystem": "logdata-snap-20260913"},
       answer="Filesystem 'logdata-snap-20260913' destroyed from pool 'logpool'"),
    V2(id="stratis-filesystem-destroy-v2-0010", tool="stratis", operation="filesystem-destroy",
       complexity="single",
       user_input="Destroy the media-archive-2026 snapshot from mediapool.",
       args={"operation": "filesystem-destroy", "pool": "mediapool", "filesystem": "media-archive-2026"},
       answer="Filesystem 'media-archive-2026' destroyed from pool 'mediapool'"),
]

from finetune.scenarios_v2 import check_module; check_module("stratis", SCENARIOS_V2)
