"""finetune/scenarios_v2/subscription.py — corpus v2 scenarios for 'subscription'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="subscription-status-v2-0001", tool="subscription", operation="status",
       complexity="single",
       user_input="Check whether this host has a valid Red Hat subscription.",
       args={"operation": "status"},
       answer="Overall Status: Current\nSystem Purpose Status: Matched\n2 subscriptions attached."),
    V2(id="subscription-status-v2-0002", tool="subscription", operation="status",
       complexity="single",
       user_input="is this system registered and current",
       args={"operation": "status"},
       answer="Overall Status: Current\nSystem Purpose Status: Matched\n1 subscription attached."),
    V2(id="subscription-status-v2-0003", tool="subscription", operation="status",
       complexity="diagnostic",
       user_input="dnf is throwing 'This system is not registered' errors on every update — what does the subscription status say?",
       args={"operation": "status"},
       answer="Overall Status: Unknown\nSystem is not registered with an entitlement server.\nUse register to attach a subscription."),
    V2(id="subscription-status-v2-0004", tool="subscription", operation="status",
       complexity="diagnostic",
       user_input="Security patching failed on app-node-2 last night with a repo access error — can you confirm the subscription is still valid?",
       args={"operation": "status"},
       answer="Overall Status: Invalid\nOne or more subscriptions have expired.\nRun list to see which subscriptions are attached."),
    V2(id="subscription-status-v2-0005", tool="subscription", operation="status",
       complexity="multi",
       user_input="Check the subscription status and then list what repos are currently enabled.",
       args={"operation": "status"},
       answer="Overall Status: Current\nSystem Purpose Status: Matched\n1 subscription attached."),
    V2(id="subscription-status-v2-0006", tool="subscription", operation="status",
       complexity="single",
       user_input="run subscription-manager status on the freshly rebuilt db-node-3",
       args={"operation": "status"},
       answer="Overall Status: Unknown\nSystem is not registered with an entitlement server."),
    V2(id="subscription-status-v2-0007", tool="subscription", operation="status",
       complexity="single",
       user_input="confirm our Red Hat subscription hasn't lapsed",
       args={"operation": "status"},
       answer="Overall Status: Current\nSystem Purpose Status: Matched\n3 subscriptions attached."),
    V2(id="subscription-status-v2-0008", tool="subscription", operation="status",
       complexity="diagnostic",
       user_input="Before we run the nftables hardening pass on this box, make sure we're not going to lose repo access mid-change — check the subscription state.",
       args={"operation": "status"},
       answer="Overall Status: Current\nSystem Purpose Status: Matched\n1 subscription attached."),

    V2(id="subscription-list-v2-0001", tool="subscription", operation="list",
       complexity="single",
       user_input="List the subscriptions currently attached to this system.",
       args={"operation": "list", "what": "consumed"},
       answer="Subscription Name: Red Hat Enterprise Linux Server\nSKU: RH00003\nQuantity Used: 1\nStatus: Active\n1 subscription consumed."),
    V2(id="subscription-list-v2-0002", tool="subscription", operation="list",
       complexity="single",
       user_input="what subscriptions could we still attach to this host",
       args={"operation": "list", "what": "available"},
       answer="Subscription Name: Red Hat Enterprise Linux Server, Premium\nPool ID: 8a85f9c1a2b3c4d5\nQuantity: 15 available\n2 pools available."),
    V2(id="subscription-list-v2-0003", tool="subscription", operation="list",
       complexity="diagnostic",
       user_input="We think the subscription on mail-node-1 expired last month — list what's currently consumed so I can see the end date.",
       args={"operation": "list", "what": "consumed"},
       answer="Subscription Name: Red Hat Enterprise Linux Server\nSKU: RH00003\nEnds: 2026-08-15\nStatus: Expired\n1 subscription consumed."),
    V2(id="subscription-list-v2-0004", tool="subscription", operation="list",
       complexity="single",
       user_input="show which subscriptions are consumed on this node",
       args={"operation": "list", "what": "consumed"},
       answer="Subscription Name: Red Hat Enterprise Linux Server\nSKU: RH00003\nQuantity Used: 1\nStatus: Active\n1 subscription consumed."),
    V2(id="subscription-list-v2-0005", tool="subscription", operation="list",
       complexity="multi",
       user_input="List the available subscription pools and then register this host to the right one.",
       args={"operation": "list", "what": "available"},
       answer="Subscription Name: Red Hat Enterprise Linux Server, Standard\nPool ID: 8a85f9c1a2b3c4d5\nQuantity: 8 available\n1 pool available."),
    V2(id="subscription-list-v2-0006", tool="subscription", operation="list",
       complexity="diagnostic",
       user_input="We can't enable the appstream repo on this box — can you list the consumed subscriptions to see if the right entitlement is even attached?",
       args={"operation": "list", "what": "consumed"},
       answer="No consumed subscription pools were found.\nThis system may need to be registered or attached to a pool."),
    V2(id="subscription-list-v2-0007", tool="subscription", operation="list",
       complexity="single",
       user_input="pull the list of consumed Red Hat subscriptions on web-node-1",
       args={"operation": "list", "what": "consumed"},
       answer="Subscription Name: Red Hat Enterprise Linux Server\nSKU: RH00003\nQuantity Used: 1\nStatus: Active\n1 subscription consumed."),
    V2(id="subscription-list-v2-0008", tool="subscription", operation="list",
       complexity="single",
       user_input="what subscription pools are available for attaching to this system",
       args={"operation": "list", "what": "available"},
       answer="Subscription Name: Red Hat Enterprise Linux Server\nPool ID: 8a85f9c1a2b3c4d5\nQuantity: 20 available\n1 pool available."),

    V2(id="subscription-register-v2-0001", tool="subscription", operation="register",
       complexity="single",
       user_input="Register this system using activation key rhel9-baseline-key.",
       args={"operation": "register", "activationkey": "rhel9-baseline-key", "org": "7042013"},
       answer="The system has been registered with ID: 4b2f8a91-33cc-4d5e-8f21-9a0b1c2d3e4f\nActivation key rhel9-baseline-key applied."),
    V2(id="subscription-register-v2-0002", tool="subscription", operation="register",
       complexity="single",
       user_input="register this server to our Red Hat account, username svc-rhsm",
       args={"operation": "register", "username": "svc-rhsm"},
       answer="The system has been registered with ID: 8899aabb-1122-3344-5566-778899aabbcc"),
    V2(id="subscription-register-v2-0003", tool="subscription", operation="register",
       complexity="diagnostic",
       user_input="dnf update is failing with a 'not registered' error on this freshly built box — can you register it with org 7042013 and activation key rhel9-baseline-key?",
       args={"operation": "register", "org": "7042013", "activationkey": "rhel9-baseline-key"},
       answer="The system has been registered with ID: 12233445-5667-7889-9001-122334455667\nActivation key rhel9-baseline-key applied."),
    V2(id="subscription-register-v2-0004", tool="subscription", operation="register",
       complexity="multi",
       user_input="Register this host to org 7042013 and then enable the baseos and appstream repos.",
       args={"operation": "register", "org": "7042013", "activationkey": "rhel9-baseline-key"},
       answer="The system has been registered with ID: 99aa11bb-2233-4455-6677-8899aabbccdd\nActivation key rhel9-baseline-key applied."),
    V2(id="subscription-register-v2-0005", tool="subscription", operation="register",
       complexity="single",
       user_input="attach this node to our subscription server using username svc-rhsm and password on file",
       args={"operation": "register", "username": "svc-rhsm", "password": "S3rv1ceAcct!"},
       answer="The system has been registered with ID: 33445566-7788-99aa-bbcc-ddeeff001122"),
    V2(id="subscription-register-v2-0006", tool="subscription", operation="register",
       complexity="single",
       user_input="register the box, org id 7042013, activation key ci-runner-key",
       args={"operation": "register", "org": "7042013", "activationkey": "ci-runner-key"},
       answer="The system has been registered with ID: 55667788-99aa-bbcc-ddee-ff0011223344\nActivation key ci-runner-key applied."),
    V2(id="subscription-register-v2-0007", tool="subscription", operation="register",
       complexity="diagnostic",
       user_input="This VM was cloned from a template and inherited an unregistered state — can you register it fresh under org 7042013 with the standard activation key?",
       args={"operation": "register", "org": "7042013", "activationkey": "rhel9-baseline-key"},
       answer="The system has been registered with ID: 77889900-aabb-ccdd-eeff-001122334455\nActivation key rhel9-baseline-key applied."),
    V2(id="subscription-register-v2-0008", tool="subscription", operation="register",
       complexity="single",
       user_input="sign this host up with the Red Hat account, username svc-rhsm",
       args={"operation": "register", "username": "svc-rhsm"},
       answer="The system has been registered with ID: aabbccdd-0011-2233-4455-667788990011"),

    V2(id="subscription-unregister-v2-0001", tool="subscription", operation="unregister",
       complexity="single",
       user_input="Unregister this system from the subscription server entirely.",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0002", tool="subscription", operation="unregister",
       complexity="diagnostic",
       user_input="We're decommissioning db-node-3 and don't want it holding a subscription seat anymore — can you unregister it?",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0003", tool="subscription", operation="unregister",
       complexity="multi",
       user_input="Unregister this host and then confirm the status shows unregistered.",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0004", tool="subscription", operation="unregister",
       complexity="single",
       user_input="pull this node off our Red Hat subscription, it's being retired",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0005", tool="subscription", operation="unregister",
       complexity="diagnostic",
       user_input="This VM was cloned with the original host's registration ID still attached — should we unregister it before re-registering under its own identity?",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed.\nContent repositories are now inaccessible until re-registration."),
    V2(id="subscription-unregister-v2-0006", tool="subscription", operation="unregister",
       complexity="single",
       user_input="detach this box from the subscription entirely",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0007", tool="subscription", operation="unregister",
       complexity="single",
       user_input="run subscription-manager unregister on web-node-1, we're moving it off RHEL support",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0008", tool="subscription", operation="unregister",
       complexity="diagnostic",
       user_input="Our subscription count from Red Hat looks over budget by one seat — can you unregister the old app-node-2 host that was replaced last week?",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),
    V2(id="subscription-unregister-v2-0009", tool="subscription", operation="unregister",
       complexity="single",
       user_input="remove this system's registration, it's going back to the image template pool",
       args={"operation": "unregister"},
       answer="System has been unregistered.\nAll subscription entitlements removed."),

    V2(id="subscription-repos_enable-v2-0001", tool="subscription", operation="repos_enable",
       complexity="single",
       user_input="Enable the rhel-9-for-x86_64-appstream-rpms repo.",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-appstream-rpms"},
       answer="Repository 'rhel-9-for-x86_64-appstream-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0002", tool="subscription", operation="repos_enable",
       complexity="diagnostic",
       user_input="dnf can't find the postgresql package on this host — is the appstream repo even enabled, and if not can you turn it on?",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-appstream-rpms"},
       answer="Repository 'rhel-9-for-x86_64-appstream-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0003", tool="subscription", operation="repos_enable",
       complexity="single",
       user_input="turn on the baseos repo for x86_64",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-baseos-rpms"},
       answer="Repository 'rhel-9-for-x86_64-baseos-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0004", tool="subscription", operation="repos_enable",
       complexity="multi",
       user_input="Register this host and then enable the baseos repo.",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-baseos-rpms"},
       answer="Repository 'rhel-9-for-x86_64-baseos-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0005", tool="subscription", operation="repos_enable",
       complexity="single",
       user_input="switch on the rhel-9-for-x86_64-supplementary-rpms channel",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-supplementary-rpms"},
       answer="Repository 'rhel-9-for-x86_64-supplementary-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0006", tool="subscription", operation="repos_enable",
       complexity="diagnostic",
       user_input="A build broke because a devel package wasn't found — should the codeready-builder repo be on, and can you enable it if not?",
       args={"operation": "repos_enable", "repo": "codeready-builder-for-rhel-9-x86_64-rpms"},
       answer="Repository 'codeready-builder-for-rhel-9-x86_64-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0007", tool="subscription", operation="repos_enable",
       complexity="single",
       user_input="enable rhel-9-for-x86_64-appstream-rpms on the freshly registered ci-runner-4",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-appstream-rpms"},
       answer="Repository 'rhel-9-for-x86_64-appstream-rpms' is enabled for this system."),
    V2(id="subscription-repos_enable-v2-0008", tool="subscription", operation="repos_enable",
       complexity="single",
       user_input="get the rhel-9-for-x86_64-highavailability-rpms repo turned on for the cluster nodes",
       args={"operation": "repos_enable", "repo": "rhel-9-for-x86_64-highavailability-rpms"},
       answer="Repository 'rhel-9-for-x86_64-highavailability-rpms' is enabled for this system."),

    V2(id="subscription-repos_disable-v2-0001", tool="subscription", operation="repos_disable",
       complexity="single",
       user_input="Disable the rhel-9-for-x86_64-supplementary-rpms repo, we don't use it.",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-supplementary-rpms"},
       answer="Repository 'rhel-9-for-x86_64-supplementary-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0002", tool="subscription", operation="repos_disable",
       complexity="diagnostic",
       user_input="A security scan flagged that the codeready-builder repo is enabled on production hosts where it shouldn't be — can you disable it here?",
       args={"operation": "repos_disable", "repo": "codeready-builder-for-rhel-9-x86_64-rpms"},
       answer="Repository 'codeready-builder-for-rhel-9-x86_64-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0003", tool="subscription", operation="repos_disable",
       complexity="single",
       user_input="turn off the highavailability repo on this standalone node",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-highavailability-rpms"},
       answer="Repository 'rhel-9-for-x86_64-highavailability-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0004", tool="subscription", operation="repos_disable",
       complexity="multi",
       user_input="Disable the appstream repo temporarily and then re-enable baseos to reset dnf's view.",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-appstream-rpms"},
       answer="Repository 'rhel-9-for-x86_64-appstream-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0005", tool="subscription", operation="repos_disable",
       complexity="single",
       user_input="shut off rhel-9-for-x86_64-baseos-debug-rpms, it's just noise in dnf repolist",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-baseos-debug-rpms"},
       answer="Repository 'rhel-9-for-x86_64-baseos-debug-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0006", tool="subscription", operation="repos_disable",
       complexity="diagnostic",
       user_input="This host somehow has the supplementary channel on and it's pulling in packages we don't want during updates — can you disable it?",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-supplementary-rpms"},
       answer="Repository 'rhel-9-for-x86_64-supplementary-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0007", tool="subscription", operation="repos_disable",
       complexity="single",
       user_input="disable codeready-builder-for-rhel-9-x86_64-rpms on prod-web-2",
       args={"operation": "repos_disable", "repo": "codeready-builder-for-rhel-9-x86_64-rpms"},
       answer="Repository 'codeready-builder-for-rhel-9-x86_64-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0008", tool="subscription", operation="repos_disable",
       complexity="single",
       user_input="I need rhel-9-for-x86_64-highavailability-rpms turned off, we dropped the pacemaker cluster setup",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-highavailability-rpms"},
       answer="Repository 'rhel-9-for-x86_64-highavailability-rpms' is disabled for this system."),
    V2(id="subscription-repos_disable-v2-0009", tool="subscription", operation="repos_disable",
       complexity="diagnostic",
       user_input="dnf keeps offering debug symbol packages we never want installed — is the baseos-debug repo on, and can you disable it?",
       args={"operation": "repos_disable", "repo": "rhel-9-for-x86_64-baseos-debug-rpms"},
       answer="Repository 'rhel-9-for-x86_64-baseos-debug-rpms' is disabled for this system."),
]

from finetune.scenarios_v2 import check_module; check_module("subscription", SCENARIOS_V2)
