"""finetune/scenarios_v2/sysctl.py — corpus v2 scenarios for 'sysctl'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="sysctl-list-v2-0001", tool="sysctl", operation="list",
       complexity="single",
       user_input="Show me every kernel parameter on db-node-7.",
       args={"operation": "list"},
       answer="net.ipv4.ip_forward = 0\nvm.swappiness = 60\nkernel.panic = 0\nfs.file-max = 786432\n... 412 more"),
    V2(id="sysctl-list-v2-0002", tool="sysctl", operation="list",
       complexity="diagnostic",
       user_input="Networking team suspects a misconfigured kernel parameter is causing packet drops on edge-proxy-1. Show all the network-related sysctl values.",
       args={"operation": "list"},
       answer="net.ipv4.tcp_syncookies = 1\nnet.ipv4.ip_forward = 1\nnet.core.somaxconn = 128\nnet.ipv4.conf.all.rp_filter = 1"),
    V2(id="sysctl-list-v2-0003", tool="sysctl", operation="list",
       complexity="multi",
       user_input="Dump all kernel parameters on cache-node-9 and tell me if vm.swappiness is set above 60.",
       args={"operation": "list"},
       answer="vm.swappiness = 10\nvm.dirty_ratio = 20\nvm.overcommit_memory = 0\nnet.ipv4.ip_forward = 0"),
    V2(id="sysctl-list-v2-0004", tool="sysctl", operation="list",
       complexity="single",
       user_input="security team wants a baseline of all kernel parameters on payments-web-1 before patching",
       args={"operation": "list"},
       answer="kernel.randomize_va_space = 2\nkernel.kptr_restrict = 1\nnet.ipv4.tcp_syncookies = 1\nfs.suid_dumpable = 0\n... 398 more"),
    V2(id="sysctl-list-v2-0005", tool="sysctl", operation="list",
       complexity="diagnostic",
       user_input="After the OOM kill on batch-node-5 last night, I want to see all vm.* and kernel.* parameters.",
       args={"operation": "list"},
       answer="vm.swappiness = 60\nvm.overcommit_memory = 0\nvm.dirty_ratio = 20\nkernel.panic = 0\nkernel.oom_kill_allocating_task = 0"),
    V2(id="sysctl-list-v2-0006", tool="sysctl", operation="list",
       complexity="single",
       user_input="get a full sysctl dump for build-runner-2, show all vm.* settings",
       args={"operation": "list"},
       answer="vm.swappiness = 30\nvm.dirty_ratio = 20\nvm.dirty_background_ratio = 10\nvm.overcommit_memory = 0"),

    V2(id="sysctl-get-v2-0001", tool="sysctl", operation="get",
       complexity="single",
       user_input="What is vm.swappiness currently set to on db-replica-2?",
       args={"operation": "get", "key": "vm.swappiness"},
       answer="vm.swappiness = 60"),
    V2(id="sysctl-get-v2-0002", tool="sysctl", operation="get",
       complexity="diagnostic",
       user_input="A container on router-vm-1 seems to be forwarding packets it shouldn't. Is IP forwarding actually enabled there?",
       args={"operation": "get", "key": "net.ipv4.ip_forward"},
       answer="net.ipv4.ip_forward = 1"),
    V2(id="sysctl-get-v2-0003", tool="sysctl", operation="get",
       complexity="single",
       user_input="check fs.file-max on media-stream-2",
       args={"operation": "get", "key": "fs.file-max"},
       answer="fs.file-max = 393216"),
    V2(id="sysctl-get-v2-0004", tool="sysctl", operation="get",
       complexity="diagnostic",
       user_input="Connections are being dropped at peak load on lb-front-4. Check net.ipv4.tcp_max_syn_backlog.",
       args={"operation": "get", "key": "net.ipv4.tcp_max_syn_backlog"},
       answer="net.ipv4.tcp_max_syn_backlog = 128"),

    V2(id="sysctl-set-v2-0001", tool="sysctl", operation="set",
       complexity="single",
       user_input="Set vm.swappiness to 10 on db-replica-2 to reduce swapping.",
       args={"operation": "set", "key": "vm.swappiness", "value": "10"},
       answer="vm.swappiness = 10"),
    V2(id="sysctl-set-v2-0002", tool="sysctl", operation="set",
       complexity="single",
       user_input="Enable IP forwarding right now on router-vm-1 without a reboot.",
       args={"operation": "set", "key": "net.ipv4.ip_forward", "value": "1"},
       answer="net.ipv4.ip_forward = 1"),
    V2(id="sysctl-set-v2-0003", tool="sysctl", operation="set",
       complexity="diagnostic",
       user_input="lb-front-4 is timing out connections under peak load, bump net.core.somaxconn to 65535.",
       args={"operation": "set", "key": "net.core.somaxconn", "value": "65535"},
       answer="net.core.somaxconn = 65535"),
    V2(id="sysctl-set-v2-0004", tool="sysctl", operation="set",
       complexity="multi",
       user_input="Set fs.file-max to 2097152 on media-stream-2 and then verify the new value.",
       args={"operation": "set", "key": "fs.file-max", "value": "2097152"},
       answer="fs.file-max = 2097152"),

    V2(id="sysctl-persist-v2-0001", tool="sysctl", operation="persist",
       complexity="single",
       user_input="Make vm.swappiness=10 survive reboots on db-replica-2.",
       args={"operation": "persist", "key": "vm.swappiness", "value": "10"},
       answer="Wrote /etc/sysctl.d/99-vm.swappiness.conf\nsysctl --system applied"),
    V2(id="sysctl-persist-v2-0002", tool="sysctl", operation="persist",
       complexity="single",
       user_input="Permanently enable IP forwarding on router-vm-1.",
       args={"operation": "persist", "key": "net.ipv4.ip_forward", "value": "1"},
       answer="Wrote /etc/sysctl.d/99-net.ipv4.ip_forward.conf\nsysctl --system applied"),
    V2(id="sysctl-persist-v2-0003", tool="sysctl", operation="persist",
       complexity="diagnostic",
       user_input="The swappiness on cache-node-9 keeps resetting to 60 after reboots. Persist it at 10 permanently.",
       args={"operation": "persist", "key": "vm.swappiness", "value": "10", "filename": "99-swappiness.conf"},
       answer="Wrote /etc/sysctl.d/99-swappiness.conf\nsysctl --system applied"),
    V2(id="sysctl-persist-v2-0004", tool="sysctl", operation="persist",
       complexity="multi",
       user_input="Write net.core.somaxconn=65535 to sysctl.d on lb-front-4 and then confirm the file was created.",
       args={"operation": "persist", "key": "net.core.somaxconn", "value": "65535"},
       answer="Wrote /etc/sysctl.d/99-net.core.somaxconn.conf\nsysctl --system applied"),
]

from finetune.scenarios_v2 import check_module; check_module("sysctl", SCENARIOS_V2)
