"""finetune/scenarios_v2/systemd_timers.py — corpus v2 scenarios for 'systemd_timers'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="systemd_timers-list-timers-v2-0001", tool="systemd_timers", operation="list-timers",
       complexity="single",
       user_input="Show me every timer unit currently scheduled.",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT   LAST    UNIT\nSat 2026-09-13 02:00:00 UTC 8h    n/a   backup.timer\n1 timers listed"),
    V2(id="systemd_timers-list-timers-v2-0002", tool="systemd_timers", operation="list-timers",
       complexity="diagnostic",
       user_input="The disk keeps filling up around 3am with no obvious cause \u2014 list the timers to see what's actually firing then.",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT   LAST                        UNIT\nSat 2026-09-13 03:00:00 UTC 6h    Fri 2026-09-12 03:00:00 UTC dnf-makecache.timer"),
    V2(id="systemd_timers-list-timers-v2-0003", tool="systemd_timers", operation="list-timers",
       complexity="single",
       user_input="List all timers, including inactive ones.",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT   LAST  UNIT\nn/a                         n/a    n/a   old-cleanup.timer (inactive)"),
    V2(id="systemd_timers-list-timers-v2-0004", tool="systemd_timers", operation="list-timers",
       complexity="multi",
       user_input="Show all timers and tell me which ones haven't run in the last 7 days.",
       args={"operation": "list-timers"},
       answer="NEXT                       LAST                        UNIT\nSat 2026-09-13 01:00:00 UTC Fri 2026-09-05 01:00:00 UTC audit-report.timer\nstale: audit-report.timer"),
    V2(id="systemd_timers-list-timers-v2-0005", tool="systemd_timers", operation="list-timers",
       complexity="diagnostic",
       user_input="Log rotation isn't happening \u2014 is the logrotate timer even scheduled?",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT  LAST                        UNIT\nSat 2026-09-13 00:00:00 UTC 10h   Fri 2026-09-12 00:00:00 UTC logrotate.timer"),
    V2(id="systemd_timers-list-timers-v2-0006", tool="systemd_timers", operation="list-timers",
       complexity="single",
       user_input="When is the next dnf-makecache run scheduled?",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT  UNIT\nSat 2026-09-13 06:00:00 UTC 4h    dnf-makecache.timer"),
    V2(id="systemd_timers-list-timers-v2-0007", tool="systemd_timers", operation="list-timers",
       complexity="diagnostic",
       user_input="This is an SSD-only host \u2014 check whether fstrim.timer is actually enabled here.",
       args={"operation": "list-timers"},
       answer="NEXT                        LEFT  UNIT\nSun 2026-09-14 00:00:00 UTC 1d    fstrim.timer"),
    V2(id="systemd_timers-list-timers-v2-0008", tool="systemd_timers", operation="list-timers",
       complexity="single",
       user_input="Give me the full list of active and inactive timers on this host.",
       args={"operation": "list-timers"},
       answer="NEXT                        LAST                        UNIT\nSat 2026-09-13 02:00:00 UTC Fri 2026-09-12 02:00:00 UTC backup.timer\n5 timers listed"),
    V2(id="systemd_timers-timer-show-v2-0009", tool="systemd_timers", operation="timer-show",
       complexity="single",
       user_input="Show the properties of backup.timer.",
       args={"timer": "backup.timer", "operation": "timer-show"},
       answer="Unit=backup.service\nOnCalendar=*-*-* 02:00:00\nActiveState=active\nTriggers: backup.service"),
    V2(id="systemd_timers-timer-show-v2-0010", tool="systemd_timers", operation="timer-show",
       complexity="diagnostic",
       user_input="The dnf-makecache timer fired right at the start of the CPU spike this morning \u2014 what's its actual schedule?",
       args={"timer": "dnf-makecache.timer", "operation": "timer-show"},
       answer="Unit=dnf-makecache.service\nOnCalendar=*-*-* *:00/30\nLastTriggerUSec: Fri 2026-09-12 03:00:00 UTC"),
    V2(id="systemd_timers-timer-show-v2-0011", tool="systemd_timers", operation="timer-show",
       complexity="single",
       user_input="What's the schedule for logrotate.timer?",
       args={"timer": "logrotate.timer", "operation": "timer-show"},
       answer="Unit=logrotate.service\nOnCalendar=daily\nAccuracySec=12h"),
    V2(id="systemd_timers-timer-show-v2-0012", tool="systemd_timers", operation="timer-show",
       complexity="multi",
       user_input="Show the properties of db-backup.timer and tell me which service it triggers.",
       args={"timer": "db-backup.timer", "operation": "timer-show"},
       answer="Unit=db-backup.service\nOnCalendar=*-*-* 01:30:00\nTriggers: db-backup.service"),
    V2(id="systemd_timers-timer-show-v2-0013", tool="systemd_timers", operation="timer-show",
       complexity="diagnostic",
       user_input="The cert-renewal window came and went but the cert is still expired \u2014 show the timer properties to see what happened.",
       args={"timer": "cert-renewal.timer", "operation": "timer-show"},
       answer="Unit=cert-renewal.service\nOnCalendar=*-*-01 03:00:00\nLastTriggerUSec: n/a\nActiveState=inactive"),
    V2(id="systemd_timers-timer-show-v2-0014", tool="systemd_timers", operation="timer-show",
       complexity="single",
       user_input="Show the current state of fstrim.timer.",
       args={"timer": "fstrim.timer", "operation": "timer-show"},
       answer="Unit=fstrim.service\nOnCalendar=weekly\nActiveState=active"),
    V2(id="systemd_timers-timer-show-v2-0015", tool="systemd_timers", operation="timer-show",
       complexity="diagnostic",
       user_input="We deployed cleanup.timer last week but nobody has confirmed it's actually working \u2014 show its properties.",
       args={"timer": "cleanup.timer", "operation": "timer-show"},
       answer="Unit=cleanup.service\nOnCalendar=daily\nLastTriggerUSec: Fri 2026-09-12 00:00:00 UTC"),
    V2(id="systemd_timers-timer-show-v2-0016", tool="systemd_timers", operation="timer-show",
       complexity="single",
       user_input="Show me the properties for audit-report.timer.",
       args={"timer": "audit-report.timer", "operation": "timer-show"},
       answer="Unit=audit-report.service\nOnCalendar=weekly\nActiveState=active"),
    V2(id="systemd_timers-create-v2-0017", tool="systemd_timers", operation="create",
       complexity="single",
       user_input="Create a daily backup.timer that fires at 2am.",
       args={"timer": "backup.timer", "content": "[Unit]\nDescription=Daily backup\n\n[Timer]\nOnCalendar=*-*-* 02:00:00\nPersistent=true\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/backup.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0018", tool="systemd_timers", operation="create",
       complexity="diagnostic",
       user_input="The audit-report script has never had a schedule attached \u2014 create a weekly timer for it.",
       args={"timer": "audit-report.timer", "content": "[Unit]\nDescription=Weekly audit report\n\n[Timer]\nOnCalendar=weekly\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/audit-report.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0019", tool="systemd_timers", operation="create",
       complexity="single",
       user_input="Install a weekly log-archive.timer that runs every Sunday at midnight.",
       args={"timer": "log-archive.timer", "content": "[Unit]\nDescription=Weekly log archive\n\n[Timer]\nOnCalendar=Sun *-*-* 00:00:00\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/log-archive.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0020", tool="systemd_timers", operation="create",
       complexity="multi",
       user_input="Create a cert-renewal.timer that fires monthly, then enable it right after.",
       args={"timer": "cert-renewal.timer", "content": "[Unit]\nDescription=Monthly cert renewal\n\n[Timer]\nOnCalendar=*-*-01 03:00:00\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/cert-renewal.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0021", tool="systemd_timers", operation="create",
       complexity="single",
       user_input="Write a timer unit for db-vacuum that runs every night at 3am.",
       args={"timer": "db-vacuum.timer", "content": "[Unit]\nDescription=Nightly db vacuum\n\n[Timer]\nOnCalendar=*-*-* 03:00:00\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/db-vacuum.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0022", tool="systemd_timers", operation="create",
       complexity="diagnostic",
       user_input="Temp files are piling up under /var/tmp with no cleanup process at all \u2014 create a daily cleanup.timer.",
       args={"timer": "cleanup.timer", "content": "[Unit]\nDescription=Daily temp cleanup\n\n[Timer]\nOnCalendar=daily\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/cleanup.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0023", tool="systemd_timers", operation="create",
       complexity="single",
       user_input="Create a timer to run health-check.service every 15 minutes.",
       args={"timer": "health-check.timer", "content": "[Unit]\nDescription=Health check every 15 minutes\n\n[Timer]\nOnCalendar=*:0/15\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/health-check.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-create-v2-0024", tool="systemd_timers", operation="create",
       complexity="diagnostic",
       user_input="The offsite sync used to run manually and someone always forgets \u2014 set up a nightly rsync-offsite.timer for 1am.",
       args={"timer": "rsync-offsite.timer", "content": "[Unit]\nDescription=Nightly offsite sync\n\n[Timer]\nOnCalendar=*-*-* 01:00:00\n\n[Install]\nWantedBy=timers.target\n", "operation": "create"},
       answer="/etc/systemd/system/rsync-offsite.timer written\nsystemd reloaded"),
    V2(id="systemd_timers-enable-v2-0025", tool="systemd_timers", operation="enable",
       complexity="single",
       user_input="Enable backup.timer so it starts at boot.",
       args={"timer": "backup.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/backup.timer\nbackup.timer enabled"),
    V2(id="systemd_timers-enable-v2-0026", tool="systemd_timers", operation="enable",
       complexity="diagnostic",
       user_input="The health-check timer isn't firing after last night's reboot \u2014 enable it.",
       args={"timer": "health-check.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/health-check.timer\nhealth-check.timer enabled"),
    V2(id="systemd_timers-enable-v2-0027", tool="systemd_timers", operation="enable",
       complexity="single",
       user_input="Make logrotate.timer start automatically.",
       args={"timer": "logrotate.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer\nlogrotate.timer enabled"),
    V2(id="systemd_timers-enable-v2-0028", tool="systemd_timers", operation="enable",
       complexity="multi",
       user_input="Enable cert-renewal.timer and confirm it shows enabled afterward.",
       args={"timer": "cert-renewal.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/cert-renewal.timer\ncert-renewal.timer enabled\nUnitFileState=enabled"),
    V2(id="systemd_timers-enable-v2-0029", tool="systemd_timers", operation="enable",
       complexity="single",
       user_input="Enable db-vacuum.timer on this database host.",
       args={"timer": "db-vacuum.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/db-vacuum.timer\ndb-vacuum.timer enabled"),
    V2(id="systemd_timers-enable-v2-0030", tool="systemd_timers", operation="enable",
       complexity="diagnostic",
       user_input="This SSD host has never had trim scheduled \u2014 enable fstrim.timer.",
       args={"timer": "fstrim.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/fstrim.timer\nfstrim.timer enabled"),
    V2(id="systemd_timers-enable-v2-0031", tool="systemd_timers", operation="enable",
       complexity="single",
       user_input="Enable cleanup.timer and list all timers so I can see it in the schedule.",
       args={"timer": "cleanup.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/cleanup.timer\ncleanup.timer enabled"),
    V2(id="systemd_timers-enable-v2-0032", tool="systemd_timers", operation="enable",
       complexity="diagnostic",
       user_input="After the rebuild, rsync-offsite.timer went back to disabled \u2014 turn it on again.",
       args={"timer": "rsync-offsite.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/rsync-offsite.timer\nrsync-offsite.timer enabled"),
    V2(id="systemd_timers-enable-v2-0033", tool="systemd_timers", operation="enable",
       complexity="single",
       user_input="Enable audit-report.timer.",
       args={"timer": "audit-report.timer", "operation": "enable"},
       answer="Created symlink /etc/systemd/system/timers.target.wants/audit-report.timer\naudit-report.timer enabled"),
    V2(id="systemd_timers-disable-v2-0034", tool="systemd_timers", operation="disable",
       complexity="single",
       user_input="Disable backup.timer \u2014 we're moving to a different backup solution.",
       args={"timer": "backup.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/backup.timer\nbackup.timer disabled"),
    V2(id="systemd_timers-disable-v2-0035", tool="systemd_timers", operation="disable",
       complexity="diagnostic",
       user_input="dnf-makecache.timer keeps causing I/O spikes at random times \u2014 stop it from running.",
       args={"timer": "dnf-makecache.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/dnf-makecache.timer\ndnf-makecache.timer disabled"),
    V2(id="systemd_timers-disable-v2-0036", tool="systemd_timers", operation="disable",
       complexity="single",
       user_input="Disable old-cleanup.timer and confirm it's no longer in the enabled list.",
       args={"timer": "old-cleanup.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/old-cleanup.timer\nold-cleanup.timer disabled"),
    V2(id="systemd_timers-disable-v2-0037", tool="systemd_timers", operation="disable",
       complexity="diagnostic",
       user_input="The db-vacuum job keeps running during peak hours and slowing queries \u2014 disable its timer.",
       args={"timer": "db-vacuum.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/db-vacuum.timer\ndb-vacuum.timer disabled"),
    V2(id="systemd_timers-disable-v2-0038", tool="systemd_timers", operation="disable",
       complexity="single",
       user_input="Disable audit-report.timer on this decommissioned host.",
       args={"timer": "audit-report.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/audit-report.timer\naudit-report.timer disabled"),
    V2(id="systemd_timers-disable-v2-0039", tool="systemd_timers", operation="disable",
       complexity="multi",
       user_input="Turn off cert-renewal.timer while the PKI is being replaced, then verify it's gone from the enabled list.",
       args={"timer": "cert-renewal.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/cert-renewal.timer\ncert-renewal.timer disabled\nUnitFileState=disabled"),
    V2(id="systemd_timers-disable-v2-0040", tool="systemd_timers", operation="disable",
       complexity="single",
       user_input="Disable health-check.timer and show me the timer list to confirm it's gone.",
       args={"timer": "health-check.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/health-check.timer\nhealth-check.timer disabled"),
    V2(id="systemd_timers-disable-v2-0041", tool="systemd_timers", operation="disable",
       complexity="diagnostic",
       user_input="The offsite sync is saturating the uplink during business hours because the timer never got tuned \u2014 disable it for now.",
       args={"timer": "rsync-offsite.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/rsync-offsite.timer\nrsync-offsite.timer disabled"),
    V2(id="systemd_timers-disable-v2-0042", tool="systemd_timers", operation="disable",
       complexity="single",
       user_input="Turn off log-archive.timer.",
       args={"timer": "log-archive.timer", "operation": "disable"},
       answer="Removed /etc/systemd/system/timers.target.wants/log-archive.timer\nlog-archive.timer disabled"),
    V2(id="systemd_timers-systemd-run-v2-0043", tool="systemd_timers", operation="systemd-run",
       complexity="single",
       user_input="Run /usr/local/bin/backup.sh once right now as a transient unit.",
       args={"command": "/usr/local/bin/backup.sh", "operation": "systemd-run"},
       answer="Running as unit: run-u12345.service"),
    V2(id="systemd_timers-systemd-run-v2-0044", tool="systemd_timers", operation="systemd-run",
       complexity="diagnostic",
       user_input="The scheduled backup didn't fire last night and we can't wait for the next window \u2014 trigger it manually now.",
       args={"command": "/usr/local/bin/backup.sh", "unit_name": "backup-manual", "operation": "systemd-run"},
       answer="Running as unit: backup-manual.service"),
    V2(id="systemd_timers-systemd-run-v2-0045", tool="systemd_timers", operation="systemd-run",
       complexity="single",
       user_input="Schedule a one-time disk cleanup to run in 30 seconds.",
       args={"command": "/usr/local/bin/disk_cleanup.sh", "on_calendar": "*-*-* *:*:30", "operation": "systemd-run"},
       answer="Running timer as unit: run-u12346.timer\nWill trigger disk_cleanup at *-*-* *:*:30"),
    V2(id="systemd_timers-systemd-run-v2-0046", tool="systemd_timers", operation="systemd-run",
       complexity="multi",
       user_input="Use systemd-run to trigger the db-vacuum script now and then check the journal for its output.",
       args={"command": "/usr/local/bin/vacuumdb_all.sh", "unit_name": "db-vacuum-manual", "operation": "systemd-run"},
       answer="Running as unit: db-vacuum-manual.service"),
    V2(id="systemd_timers-systemd-run-v2-0047", tool="systemd_timers", operation="systemd-run",
       complexity="single",
       user_input="Run /usr/local/bin/cert-renew.sh once right now.",
       args={"command": "/usr/local/bin/cert-renew.sh", "operation": "systemd-run"},
       answer="Running as unit: run-u12347.service"),
    V2(id="systemd_timers-systemd-run-v2-0048", tool="systemd_timers", operation="systemd-run",
       complexity="diagnostic",
       user_input="Nobody remembers scheduling anything for the log archive and the disk is nearly full \u2014 run the archive script immediately as a one-off.",
       args={"command": "/usr/local/bin/archive_logs.sh", "unit_name": "log-archive-manual", "operation": "systemd-run"},
       answer="Running as unit: log-archive-manual.service"),
    V2(id="systemd_timers-systemd-run-v2-0049", tool="systemd_timers", operation="systemd-run",
       complexity="single",
       user_input="Schedule /usr/sbin/aide --check to run once in 5 minutes.",
       args={"command": "/usr/sbin/aide --check", "on_calendar": "*-*-* *:+5:00", "operation": "systemd-run"},
       answer="Running timer as unit: run-u12348.timer\nWill trigger aide check at *-*-* *:+5:00"),
    V2(id="systemd_timers-systemd-run-v2-0050", tool="systemd_timers", operation="systemd-run",
       complexity="diagnostic",
       user_input="We suspect a stuck lock file is blocking the report generator \u2014 run it once now, outside of its normal schedule, and confirm it exits cleanly.",
       args={"command": "/usr/local/bin/gen_report.sh", "unit_name": "report-manual", "operation": "systemd-run"},
       answer="Running as unit: report-manual.service\nresult: exited, status=0/SUCCESS"),
    V2(id="systemd_timers-systemd-run-v2-0051", tool="systemd_timers", operation="systemd-run",
       complexity="single",
       user_input="Trigger a one-shot run of /usr/local/bin/uptime_ping.sh right now.",
       args={"command": "/usr/local/bin/uptime_ping.sh", "operation": "systemd-run"},
       answer="Running as unit: run-u12349.service"),
]

from finetune.scenarios_v2 import check_module; check_module("systemd_timers", SCENARIOS_V2)
