"""finetune/scenarios_v2/tar.py — corpus v2 scenarios for 'tar'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="tar-list-v2-0001", tool="tar", operation="list",
       complexity="single",
       user_input="What's inside /backup/etc-2026-08-01.tar?",
       args={"operation": "list", "archive": "/backup/etc-2026-08-01.tar"},
       answer="142 entries.\n-rw-r--r-- root/root 2048 etc/hosts\n-rw-r--r-- root/root 512 etc/resolv.conf"),
    V2(id="tar-list-v2-0002", tool="tar", operation="list",
       complexity="diagnostic",
       user_input="Last night's restore of nginx.conf came back empty — what's actually in /backup/nginx-conf.tar?",
       args={"operation": "list", "archive": "/backup/nginx-conf.tar"},
       answer="38 entries.\nnginx.conf not present in archive listing — confirms it was missed at backup time."),
    V2(id="tar-list-v2-0003", tool="tar", operation="list",
       complexity="single",
       user_input="List the contents of /mnt/nas/db-dump-2026-09-01.tar.bz2.",
       args={"operation": "list", "archive": "/mnt/nas/db-dump-2026-09-01.tar.bz2"},
       answer="6 entries.\n-rw------- postgres/postgres 4294967296 pgdata.dump"),
    V2(id="tar-list-v2-0004", tool="tar", operation="list",
       complexity="single",
       user_input="Show what's packed into /var/backups/home-2026-07-01.tar.xz.",
       args={"operation": "list", "archive": "/var/backups/home-2026-07-01.tar.xz"},
       answer="2140 entries.\ndrwx------ alice/alice 0 home/alice/\ndrwx------ bob/bob 0 home/bob/"),
    V2(id="tar-list-v2-0005", tool="tar", operation="list",
       complexity="multi",
       user_input="List what's in /backup/configs.tar, then check whether httpd.conf made it into the archive.",
       args={"operation": "list", "archive": "/backup/configs.tar"},
       answer="54 entries.\nhttpd.conf found: etc/httpd/conf/httpd.conf"),
    V2(id="tar-list-v2-0006", tool="tar", operation="list",
       complexity="diagnostic",
       user_input="Before I extract /backup/weekly-full.tar.gz onto the live filesystem, what does it actually contain?",
       args={"operation": "list", "archive": "/backup/weekly-full.tar.gz"},
       answer="8302 entries.\n-rw-r--r-- root/root 8192 var/log/messages"),
    V2(id="tar-list-v2-0007", tool="tar", operation="list",
       complexity="single",
       user_input="Count how many files are inside /backup/pgdata-2026-08-15.tar.",
       args={"operation": "list", "archive": "/backup/pgdata-2026-08-15.tar"},
       answer="912 entries total."),
    V2(id="tar-list-v2-0008", tool="tar", operation="list",
       complexity="single",
       user_input="Dump the file listing for /opt/archives/app-release-3.2.tar.gz.",
       args={"operation": "list", "archive": "/opt/archives/app-release-3.2.tar.gz"},
       answer="410 entries.\n-rwxr-xr-x deploy/deploy 18432 bin/app-server"),
    V2(id="tar-create-v2-0001", tool="tar", operation="create",
       complexity="single",
       user_input="Archive /etc into /backup/etc-2026-09-12.tar.",
       args={"operation": "create", "archive": "/backup/etc-2026-09-12.tar", "sources": ["/etc"]},
       answer="Archive created: /backup/etc-2026-09-12.tar (18 MiB, 1420 entries)."),
    V2(id="tar-create-v2-0002", tool="tar", operation="create",
       complexity="diagnostic",
       user_input="Before I roll back the nginx upgrade on web05, snapshot /etc/nginx so we have a fallback.",
       args={"operation": "create", "archive": "/backup/nginx-pre-rollback.tar", "sources": ["/etc/nginx"]},
       answer="Archive created: /backup/nginx-pre-rollback.tar (240 KiB, 38 entries)."),
    V2(id="tar-create-v2-0003", tool="tar", operation="create",
       complexity="single",
       user_input="Pack /var/lib/postgresql/data into /backup/pgdata-snapshot.tar.",
       args={"operation": "create", "archive": "/backup/pgdata-snapshot.tar", "sources": ["/var/lib/postgresql/data"]},
       answer="Archive created: /backup/pgdata-snapshot.tar (14.2 GiB, 6104 entries)."),
    V2(id="tar-create-v2-0004", tool="tar", operation="create",
       complexity="multi",
       user_input="Bundle /opt/app into /backup/app-snapshot.tar, then list its contents to make sure everything's there.",
       args={"operation": "create", "archive": "/backup/app-snapshot.tar", "sources": ["/opt/app"]},
       answer="Archive created: /backup/app-snapshot.tar (620 MiB, 812 entries)."),
    V2(id="tar-create-v2-0005", tool="tar", operation="create",
       complexity="single",
       user_input="Archive both /etc/ssh and /etc/pam.d into /backup/auth-config.tar.",
       args={"operation": "create", "archive": "/backup/auth-config.tar", "sources": ["/etc/ssh", "/etc/pam.d"]},
       answer="Archive created: /backup/auth-config.tar (1.1 MiB, 62 entries)."),
    V2(id="tar-create-v2-0006", tool="tar", operation="create",
       complexity="single",
       user_input="Create a tar of /home/deploy before we run the upgrade script.",
       args={"operation": "create", "archive": "/backup/deploy-home.tar", "sources": ["/home/deploy"]},
       answer="Archive created: /backup/deploy-home.tar (3.4 GiB, 940 entries)."),
    V2(id="tar-create-v2-0007", tool="tar", operation="create",
       complexity="diagnostic",
       user_input="I'm worried the /opt/legacy-app rollback plan won't have a fallback — capture it into an archive first.",
       args={"operation": "create", "archive": "/backup/legacy-app-fallback.tar", "sources": ["/opt/legacy-app"]},
       answer="Archive created: /backup/legacy-app-fallback.tar (1.8 GiB, 3021 entries)."),
    V2(id="tar-create-v2-0008", tool="tar", operation="create",
       complexity="single",
       user_input="Tar up /var/log into /backup/logs-2026-09-12.tar.",
       args={"operation": "create", "archive": "/backup/logs-2026-09-12.tar", "sources": ["/var/log"]},
       answer="Archive created: /backup/logs-2026-09-12.tar (2.1 GiB, 512 entries)."),
    V2(id="tar-extract-v2-0001", tool="tar", operation="extract",
       complexity="single",
       user_input="Extract /backup/etc-2026-08-01.tar into /restore/etc.",
       args={"operation": "extract", "archive": "/backup/etc-2026-08-01.tar", "dest": "/restore/etc"},
       answer="Extracted 142 entries to /restore/etc."),
    V2(id="tar-extract-v2-0002", tool="tar", operation="extract",
       complexity="diagnostic",
       user_input="nginx.conf on web05 got corrupted by a bad edit — pull the good copy back out of /backup/nginx-conf.tar into /etc/nginx.",
       args={"operation": "extract", "archive": "/backup/nginx-conf.tar", "dest": "/etc/nginx"},
       answer="Extracted 38 entries to /etc/nginx."),
    V2(id="tar-extract-v2-0003", tool="tar", operation="extract",
       complexity="single",
       user_input="Unpack /mnt/backup/home-archive.tar.bz2 into /home.",
       args={"operation": "extract", "archive": "/mnt/backup/home-archive.tar.bz2", "dest": "/home"},
       answer="Extracted 2140 entries to /home."),
    V2(id="tar-extract-v2-0004", tool="tar", operation="extract",
       complexity="single",
       user_input="Untar /backup/pgdata-snapshot.tar into /var/lib/postgresql/data.",
       args={"operation": "extract", "archive": "/backup/pgdata-snapshot.tar", "dest": "/var/lib/postgresql/data"},
       answer="Extracted 6104 entries to /var/lib/postgresql/data."),
    V2(id="tar-extract-v2-0005", tool="tar", operation="extract",
       complexity="multi",
       user_input="Extract /backup/configs.tar.xz to /tmp/restore-check and then confirm the files landed correctly.",
       args={"operation": "extract", "archive": "/backup/configs.tar.xz", "dest": "/tmp/restore-check"},
       answer="Extracted 54 entries to /tmp/restore-check."),
    V2(id="tar-extract-v2-0006", tool="tar", operation="extract",
       complexity="single",
       user_input="Restore /backup/app-snapshot.tar into /opt/app-restore.",
       args={"operation": "extract", "archive": "/backup/app-snapshot.tar", "dest": "/opt/app-restore"},
       answer="Extracted 812 entries to /opt/app-restore."),
    V2(id="tar-extract-v2-0007", tool="tar", operation="extract",
       complexity="diagnostic",
       user_input="The SSL cert directory on web05 got wiped by accident — restore it from /backup/ssl-certs.tar into /etc/ssl.",
       args={"operation": "extract", "archive": "/backup/ssl-certs.tar", "dest": "/etc/ssl"},
       answer="Extracted 24 entries to /etc/ssl."),
    V2(id="tar-extract-v2-0008", tool="tar", operation="extract",
       complexity="single",
       user_input="Extract /backup/deploy-home.tar to the default current directory.",
       args={"operation": "extract", "archive": "/backup/deploy-home.tar"},
       answer="Extracted 940 entries to ."),
    V2(id="tar-verify-v2-0001", tool="tar", operation="verify",
       complexity="single",
       user_input="Verify that /backup/etc-2026-08-01.tar still matches what's live on disk.",
       args={"operation": "verify", "archive": "/backup/etc-2026-08-01.tar"},
       answer="Compared 142 entries: 140 match, 2 differ (etc/hosts, etc/resolv.conf)."),
    V2(id="tar-verify-v2-0002", tool="tar", operation="verify",
       complexity="diagnostic",
       user_input="I'm about to delete the source files under /var/lib/postgresql/data — is the backup archive actually intact first?",
       args={"operation": "verify", "archive": "/backup/pgdata-snapshot.tar"},
       answer="Compared 6104 entries: 6104 match, 0 differ. Safe to proceed."),
    V2(id="tar-verify-v2-0003", tool="tar", operation="verify",
       complexity="single",
       user_input="Check if last night's /backup/weekly-full.tar.gz is consistent with the current filesystem state.",
       args={"operation": "verify", "archive": "/backup/weekly-full.tar.gz"},
       answer="Compared 8302 entries: 8290 match, 12 differ."),
    V2(id="tar-verify-v2-0004", tool="tar", operation="verify",
       complexity="single",
       user_input="Does /backup/ssl-certs.tar match the certs currently installed on web05?",
       args={"operation": "verify", "archive": "/backup/ssl-certs.tar"},
       answer="Compared 24 entries: 22 match, 2 differ (etc/ssl/certs/api.crt, etc/ssl/private/api.key)."),
    V2(id="tar-verify-v2-0005", tool="tar", operation="verify",
       complexity="diagnostic",
       user_input="The overnight job to /backup/app-snapshot.tar completed but I'm not confident it grabbed everything — check it against the source.",
       args={"operation": "verify", "archive": "/backup/app-snapshot.tar"},
       answer="Compared 812 entries: 780 match, 32 differ. Backup missed recent changes."),
    V2(id="tar-verify-v2-0006", tool="tar", operation="verify",
       complexity="single",
       user_input="Verify /backup/nginx-conf.tar against the live /etc/nginx tree and report any changed files.",
       args={"operation": "verify", "archive": "/backup/nginx-conf.tar"},
       answer="Compared 38 entries: 36 match, 2 differ (nginx.conf, conf.d/ssl.conf)."),
    V2(id="tar-verify-v2-0007", tool="tar", operation="verify",
       complexity="multi",
       user_input="Verify /backup/deploy-home.tar first, and if it's clean go ahead and remove the source directory.",
       args={"operation": "verify", "archive": "/backup/deploy-home.tar"},
       answer="Compared 940 entries: 940 match, 0 differ. Safe to remove source."),
    V2(id="tar-verify-v2-0008", tool="tar", operation="verify",
       complexity="diagnostic",
       user_input="Restore drills are coming up — is /backup/logs-2026-09-12.tar even trustworthy against the current /var/log?",
       args={"operation": "verify", "archive": "/backup/logs-2026-09-12.tar"},
       answer="Compared 512 entries: 505 match, 7 differ (rotated log files changed since capture)."),
    V2(id="tar-verify-v2-0009", tool="tar", operation="verify",
       complexity="single",
       user_input="Run an integrity check comparing /backup/legacy-app-fallback.tar against /opt/legacy-app.",
       args={"operation": "verify", "archive": "/backup/legacy-app-fallback.tar"},
       answer="Compared 3021 entries: 3021 match, 0 differ."),
    V2(id="tar-verify-v2-0010", tool="tar", operation="verify",
       complexity="single",
       user_input="Confirm /backup/auth-config.tar is still accurate against /etc/ssh and /etc/pam.d.",
       args={"operation": "verify", "archive": "/backup/auth-config.tar"},
       answer="Compared 62 entries: 61 match, 1 differs (etc/ssh/sshd_config)."),
    V2(id="tar-create_gz-v2-0001", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Make a gzip-compressed archive of /etc as /backup/etc-2026-09-12.tar.gz.",
       args={"operation": "create_gz", "archive": "/backup/etc-2026-09-12.tar.gz", "sources": ["/etc"]},
       answer="Archive created: /backup/etc-2026-09-12.tar.gz (4.8 MiB, 1420 entries)."),
    V2(id="tar-create_gz-v2-0002", tool="tar", operation="create_gz",
       complexity="diagnostic",
       user_input="Disk usage on log-collector1 is at 92% — compress the old logs under /var/log into a .tar.gz to free space.",
       args={"operation": "create_gz", "archive": "/backup/varlog-2026-09-12.tar.gz", "sources": ["/var/log"]},
       answer="Archive created: /backup/varlog-2026-09-12.tar.gz (410 MiB, 512 entries)."),
    V2(id="tar-create_gz-v2-0003", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Create a tgz of /opt/app for shipping to the staging server.",
       args={"operation": "create_gz", "archive": "/tmp/app-deploy.tar.gz", "sources": ["/opt/app"]},
       answer="Archive created: /tmp/app-deploy.tar.gz (118 MiB, 812 entries)."),
    V2(id="tar-create_gz-v2-0004", tool="tar", operation="create_gz",
       complexity="multi",
       user_input="Compress the web root at /var/www/html into a .tar.gz, then verify it before I upload it to the CDN origin.",
       args={"operation": "create_gz", "archive": "/backup/webroot.tar.gz", "sources": ["/var/www/html"]},
       answer="Archive created: /backup/webroot.tar.gz (62 MiB, 3020 entries)."),
    V2(id="tar-create_gz-v2-0005", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Gzip-archive /home/analyst3 into /backup/analyst3-home.tar.gz before the account is disabled.",
       args={"operation": "create_gz", "archive": "/backup/analyst3-home.tar.gz", "sources": ["/home/analyst3"]},
       answer="Archive created: /backup/analyst3-home.tar.gz (890 MiB, 640 entries)."),
    V2(id="tar-create_gz-v2-0006", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Bundle /etc/httpd into a compressed tar.gz for the config change log.",
       args={"operation": "create_gz", "archive": "/backup/httpd-conf-2026-09-12.tar.gz", "sources": ["/etc/httpd"]},
       answer="Archive created: /backup/httpd-conf-2026-09-12.tar.gz (310 KiB, 44 entries)."),
    V2(id="tar-create_gz-v2-0007", tool="tar", operation="create_gz",
       complexity="diagnostic",
       user_input="Before decommissioning app-node6, get a compressed copy of /opt/app-node6-data off it to save disk on the archive share.",
       args={"operation": "create_gz", "archive": "/backup/app-node6-data.tar.gz", "sources": ["/opt/app-node6-data"]},
       answer="Archive created: /backup/app-node6-data.tar.gz (2.2 GiB, 1900 entries)."),
    V2(id="tar-create_gz-v2-0008", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Create a gzip tar of /srv/git-repos for the offsite copy.",
       args={"operation": "create_gz", "archive": "/backup/git-repos.tar.gz", "sources": ["/srv/git-repos"]},
       answer="Archive created: /backup/git-repos.tar.gz (1.4 GiB, 2100 entries)."),
    V2(id="tar-create_gz-v2-0009", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Compress /var/lib/mysql into /backup/mysql-2026-09-12.tar.gz.",
       args={"operation": "create_gz", "archive": "/backup/mysql-2026-09-12.tar.gz", "sources": ["/var/lib/mysql"]},
       answer="Archive created: /backup/mysql-2026-09-12.tar.gz (5.1 GiB, 480 entries)."),
    V2(id="tar-create_gz-v2-0010", tool="tar", operation="create_gz",
       complexity="single",
       user_input="Build a .tar.gz of /etc/pki for the certificate audit.",
       args={"operation": "create_gz", "archive": "/backup/pki-audit.tar.gz", "sources": ["/etc/pki"]},
       answer="Archive created: /backup/pki-audit.tar.gz (2.9 MiB, 130 entries)."),
    V2(id="tar-create_gz-v2-0011", tool="tar", operation="create_gz",
       complexity="multi",
       user_input="Gzip up /data/reports for the month, and then list the archive contents so I can confirm all 30 days made it in.",
       args={"operation": "create_gz", "archive": "/backup/reports-2026-09.tar.gz", "sources": ["/data/reports"]},
       answer="Archive created: /backup/reports-2026-09.tar.gz (740 MiB, 30 entries)."),
    V2(id="tar-create_bz2-v2-0001", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Create a bzip2 backup of /etc/nginx as /backup/nginx-conf.tar.bz2.",
       args={"operation": "create_bz2", "archive": "/backup/nginx-conf.tar.bz2", "sources": ["/etc/nginx"]},
       answer="Archive created: /backup/nginx-conf.tar.bz2 (198 KiB, 38 entries)."),
    V2(id="tar-create_bz2-v2-0002", tool="tar", operation="create_bz2",
       complexity="diagnostic",
       user_input="Before migrating the database host, I want a compact archive of everything under /var/lib/pgsql — bzip2 gives the smallest result here.",
       args={"operation": "create_bz2", "archive": "/backup/pgsql-migration.tar.bz2", "sources": ["/var/lib/pgsql"]},
       answer="Archive created: /backup/pgsql-migration.tar.bz2 (9.8 GiB, 5100 entries)."),
    V2(id="tar-create_bz2-v2-0003", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Archive /var/lib/mysql with bzip2 compression to /backup/mysql-data.tar.bz2.",
       args={"operation": "create_bz2", "archive": "/backup/mysql-data.tar.bz2", "sources": ["/var/lib/mysql"]},
       answer="Archive created: /backup/mysql-data.tar.bz2 (3.9 GiB, 480 entries)."),
    V2(id="tar-create_bz2-v2-0004", tool="tar", operation="create_bz2",
       complexity="multi",
       user_input="Create a .tar.bz2 of /home for all users, then check how big the resulting file is.",
       args={"operation": "create_bz2", "archive": "/backup/all-homes.tar.bz2", "sources": ["/home"]},
       answer="Archive created: /backup/all-homes.tar.bz2 (68 GiB, 9020 entries)."),
    V2(id="tar-create_bz2-v2-0005", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Pack /srv/www with bzip2 compression for the weekly offsite backup.",
       args={"operation": "create_bz2", "archive": "/backup/srv-www-weekly.tar.bz2", "sources": ["/srv/www"]},
       answer="Archive created: /backup/srv-www-weekly.tar.bz2 (44 MiB, 2900 entries)."),
    V2(id="tar-create_bz2-v2-0006", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Compress /opt/warehouse-etl using bzip2 into /backup/warehouse-etl.tar.bz2.",
       args={"operation": "create_bz2", "archive": "/backup/warehouse-etl.tar.bz2", "sources": ["/opt/warehouse-etl"]},
       answer="Archive created: /backup/warehouse-etl.tar.bz2 (1.1 GiB, 640 entries)."),
    V2(id="tar-create_bz2-v2-0007", tool="tar", operation="create_bz2",
       complexity="diagnostic",
       user_input="Storage on the archive share is tight, and this data compresses well — bzip2 the /data/audit-logs directory.",
       args={"operation": "create_bz2", "archive": "/backup/audit-logs.tar.bz2", "sources": ["/data/audit-logs"]},
       answer="Archive created: /backup/audit-logs.tar.bz2 (312 MiB, 1500 entries)."),
    V2(id="tar-create_bz2-v2-0008", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Create a bzip2 archive of /etc/samba as /backup/samba-conf.tar.bz2.",
       args={"operation": "create_bz2", "archive": "/backup/samba-conf.tar.bz2", "sources": ["/etc/samba"]},
       answer="Archive created: /backup/samba-conf.tar.bz2 (18 KiB, 6 entries)."),
    V2(id="tar-create_bz2-v2-0009", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Archive /var/lib/rpm with bzip2 for the pre-upgrade snapshot.",
       args={"operation": "create_bz2", "archive": "/backup/rpm-db-snapshot.tar.bz2", "sources": ["/var/lib/rpm"]},
       answer="Archive created: /backup/rpm-db-snapshot.tar.bz2 (140 MiB, 22 entries)."),
    V2(id="tar-create_bz2-v2-0010", tool="tar", operation="create_bz2",
       complexity="single",
       user_input="Bzip2-compress /opt/legacy-app before the final decommission.",
       args={"operation": "create_bz2", "archive": "/backup/legacy-app-final.tar.bz2", "sources": ["/opt/legacy-app"]},
       answer="Archive created: /backup/legacy-app-final.tar.bz2 (1.3 GiB, 3021 entries)."),
    V2(id="tar-create_bz2-v2-0011", tool="tar", operation="create_bz2",
       complexity="multi",
       user_input="Bzip2 archive /var/spool/mail, then extract it into a scratch directory just to confirm it unpacks cleanly.",
       args={"operation": "create_bz2", "archive": "/backup/mail-spool.tar.bz2", "sources": ["/var/spool/mail"]},
       answer="Archive created: /backup/mail-spool.tar.bz2 (2.6 GiB, 410 entries)."),
    V2(id="tar-create_xz-v2-0001", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Create an xz-compressed archive of /etc for long-term storage.",
       args={"operation": "create_xz", "archive": "/backup/etc-longterm.tar.xz", "sources": ["/etc"]},
       answer="Archive created: /backup/etc-longterm.tar.xz (3.6 MiB, 1420 entries)."),
    V2(id="tar-create_xz-v2-0002", tool="tar", operation="create_xz",
       complexity="diagnostic",
       user_input="The NFS backup target for db-primary1 is nearly full — use the compression that shrinks it the most for /var/lib/postgresql/data.",
       args={"operation": "create_xz", "archive": "/backup/pgdata-compact.tar.xz", "sources": ["/var/lib/postgresql/data"]},
       answer="Archive created: /backup/pgdata-compact.tar.xz (8.9 GiB, 6104 entries)."),
    V2(id="tar-create_xz-v2-0003", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Archive /home with xz compression to save space on the backup server.",
       args={"operation": "create_xz", "archive": "/backup/home-all.tar.xz", "sources": ["/home"]},
       answer="Archive created: /backup/home-all.tar.xz (52 GiB, 9020 entries)."),
    V2(id="tar-create_xz-v2-0004", tool="tar", operation="create_xz",
       complexity="multi",
       user_input="Create a .tar.xz of the entire /opt directory, then verify the result matches the source.",
       args={"operation": "create_xz", "archive": "/backup/opt-full.tar.xz", "sources": ["/opt"]},
       answer="Archive created: /backup/opt-full.tar.xz (6.2 GiB, 8900 entries)."),
    V2(id="tar-create_xz-v2-0005", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Compress /var/lib/postgresql/data into a .tar.xz backup.",
       args={"operation": "create_xz", "archive": "/backup/pgdata-2026-09-12.tar.xz", "sources": ["/var/lib/postgresql/data"]},
       answer="Archive created: /backup/pgdata-2026-09-12.tar.xz (8.9 GiB, 6104 entries)."),
    V2(id="tar-create_xz-v2-0006", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Build an xz tar of /srv/git-repos for cold storage.",
       args={"operation": "create_xz", "archive": "/backup/git-repos-cold.tar.xz", "sources": ["/srv/git-repos"]},
       answer="Archive created: /backup/git-repos-cold.tar.xz (890 MiB, 2100 entries)."),
    V2(id="tar-create_xz-v2-0007", tool="tar", operation="create_xz",
       complexity="diagnostic",
       user_input="The tape library rotation only has room for the smallest form of this backup — xz-compress /data/warehouse before writing it out.",
       args={"operation": "create_xz", "archive": "/backup/warehouse-cold.tar.xz", "sources": ["/data/warehouse"]},
       answer="Archive created: /backup/warehouse-cold.tar.xz (210 GiB, 4102 entries)."),
    V2(id="tar-create_xz-v2-0008", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Create an xz archive of /etc/pki for long-term retention.",
       args={"operation": "create_xz", "archive": "/backup/pki-longterm.tar.xz", "sources": ["/etc/pki"]},
       answer="Archive created: /backup/pki-longterm.tar.xz (2.1 MiB, 130 entries)."),
    V2(id="tar-create_xz-v2-0009", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Xz-compress /opt/app-node6-data before shipping it to the cold-storage bucket.",
       args={"operation": "create_xz", "archive": "/backup/app-node6-data.tar.xz", "sources": ["/opt/app-node6-data"]},
       answer="Archive created: /backup/app-node6-data.tar.xz (1.6 GiB, 1900 entries)."),
    V2(id="tar-create_xz-v2-0010", tool="tar", operation="create_xz",
       complexity="single",
       user_input="Create a .tar.xz of /var/lib/mysql for the annual archive.",
       args={"operation": "create_xz", "archive": "/backup/mysql-annual.tar.xz", "sources": ["/var/lib/mysql"]},
       answer="Archive created: /backup/mysql-annual.tar.xz (3.5 GiB, 480 entries)."),
    V2(id="tar-create_xz-v2-0011", tool="tar", operation="create_xz",
       complexity="multi",
       user_input="Xz-archive /data/audit-logs for retention, and confirm the entry count matches what's on disk now.",
       args={"operation": "create_xz", "archive": "/backup/audit-logs.tar.xz", "sources": ["/data/audit-logs"]},
       answer="Archive created: /backup/audit-logs.tar.xz (260 MiB, 1500 entries)."),
]

from finetune.scenarios_v2 import check_module; check_module("tar", SCENARIOS_V2)
