"""finetune/scenarios_v2/tuned.py — corpus v2 scenarios for 'tuned'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(id="tuned-list-v2-0001", tool="tuned", operation="list",
       complexity="single",
       user_input="What performance profiles can I switch to?",
       args={"operation": "list"},
       answer="balanced\nthroughput-performance\nlatency-performance\nvirtual-guest\npowersave"),
    V2(id="tuned-list-v2-0002", tool="tuned", operation="list",
       complexity="diagnostic",
       user_input="Database queries are getting inconsistent latency spikes — what tuning profiles are even available to try?",
       args={"operation": "list"},
       answer="balanced\nthroughput-performance\nlatency-performance\nnetwork-latency"),
    V2(id="tuned-list-v2-0003", tool="tuned", operation="list",
       complexity="single",
       user_input="show available tuning profiles",
       args={"operation": "list"},
       answer="balanced\npowersave\nthroughput-performance\nvirtual-guest"),
    V2(id="tuned-list-v2-0004", tool="tuned", operation="list",
       complexity="multi",
       user_input="List the available profiles, then switch to throughput-performance.",
       args={"operation": "list"},
       answer="balanced\nthroughput-performance\nlatency-performance\npowersave"),
    V2(id="tuned-list-v2-0005", tool="tuned", operation="list",
       complexity="single",
       user_input="what profiles does tuned-adm offer here",
       args={"operation": "list"},
       answer="balanced\nvirtual-guest\nnetwork-throughput\npowersave"),
    V2(id="tuned-list-v2-0006", tool="tuned", operation="list",
       complexity="diagnostic",
       user_input="Someone mentioned firewalld rules might be interacting with power management — what tuning profiles are installed on this node?",
       args={"operation": "list"},
       answer="balanced\nthroughput-performance\nlatency-performance\nvirtual-guest\npowersave"),
    V2(id="tuned-active-v2-0001", tool="tuned", operation="active",
       complexity="single",
       user_input="Which tuned profile is active right now?",
       args={"operation": "active"},
       answer="Current active profile: balanced"),
    V2(id="tuned-active-v2-0002", tool="tuned", operation="active",
       complexity="diagnostic",
       user_input="This VM feels sluggish under disk load compared to last month — what profile is it actually running?",
       args={"operation": "active"},
       answer="Current active profile: powersave"),
    V2(id="tuned-active-v2-0003", tool="tuned", operation="active",
       complexity="single",
       user_input="check current tuned profile",
       args={"operation": "active"},
       answer="Current active profile: throughput-performance"),
    V2(id="tuned-active-v2-0004", tool="tuned", operation="active",
       complexity="multi",
       user_input="Tell me the active profile, then switch to latency-performance if it isn't already.",
       args={"operation": "active"},
       answer="Current active profile: balanced"),
    V2(id="tuned-active-v2-0005", tool="tuned", operation="active",
       complexity="single",
       user_input="what's the running tuning profile on this host",
       args={"operation": "active"},
       answer="Current active profile: virtual-guest"),
    V2(id="tuned-active-v2-0006", tool="tuned", operation="active",
       complexity="diagnostic",
       user_input="A hypervisor migration job mentioned CPU governor mismatches — which tuning profile is currently applied here?",
       args={"operation": "active"},
       answer="Current active profile: network-latency"),
    V2(id="tuned-recommend-v2-0001", tool="tuned", operation="recommend",
       complexity="single",
       user_input="What profile does tuned recommend for this hardware?",
       args={"operation": "recommend"},
       answer="Recommended profile: throughput-performance"),
    V2(id="tuned-recommend-v2-0002", tool="tuned", operation="recommend",
       complexity="diagnostic",
       user_input="We just moved this workload to bare metal from a VM — is the current profile still the right pick?",
       args={"operation": "recommend"},
       answer="Recommended profile: throughput-performance"),
    V2(id="tuned-recommend-v2-0003", tool="tuned", operation="recommend",
       complexity="single",
       user_input="what's the suggested tuning profile here",
       args={"operation": "recommend"},
       answer="Recommended profile: virtual-guest"),
    V2(id="tuned-recommend-v2-0004", tool="tuned", operation="recommend",
       complexity="multi",
       user_input="Show the recommended profile, then apply it if it's different from what's active.",
       args={"operation": "recommend"},
       answer="Recommended profile: latency-performance"),
    V2(id="tuned-recommend-v2-0005", tool="tuned", operation="recommend",
       complexity="single",
       user_input="tell me the best-fit profile for this system",
       args={"operation": "recommend"},
       answer="Recommended profile: balanced"),
    V2(id="tuned-recommend-v2-0006", tool="tuned", operation="recommend",
       complexity="diagnostic",
       user_input="This box got repurposed from a desktop into a database server last week — should the tuning profile change?",
       args={"operation": "recommend"},
       answer="Recommended profile: throughput-performance"),
    V2(id="tuned-recommend-v2-0007", tool="tuned", operation="recommend",
       complexity="single",
       user_input="get tuned's recommendation for this node's hardware",
       args={"operation": "recommend"},
       answer="Recommended profile: network-throughput"),
    V2(id="tuned-recommend-v2-0008", tool="tuned", operation="recommend",
       complexity="diagnostic",
       user_input="I noticed samba transfers to this fileserver are slower than they used to be — is the tuning profile out of date for this workload?",
       args={"operation": "recommend"},
       answer="Recommended profile: throughput-performance"),
    V2(id="tuned-profile-v2-0001", tool="tuned", operation="profile",
       complexity="single",
       user_input="Switch to the throughput-performance profile.",
       args={"operation": "profile", "profile": "throughput-performance"},
       answer="Switched to profile: throughput-performance\nactive: throughput-performance"),
    V2(id="tuned-profile-v2-0002", tool="tuned", operation="profile",
       complexity="diagnostic",
       user_input="This database node keeps missing its p99 latency SLA under load — should we move it onto the latency-performance profile?",
       args={"operation": "profile", "profile": "latency-performance"},
       answer="Switched to profile: latency-performance\nactive: latency-performance"),
    V2(id="tuned-profile-v2-0003", tool="tuned", operation="profile",
       complexity="single",
       user_input="apply the virtual-guest tuning profile",
       args={"operation": "profile", "profile": "virtual-guest"},
       answer="Switched to profile: virtual-guest\nactive: virtual-guest"),
    V2(id="tuned-profile-v2-0004", tool="tuned", operation="profile",
       complexity="multi",
       user_input="Set the profile to network-throughput, then confirm it took effect.",
       args={"operation": "profile", "profile": "network-throughput"},
       answer="Switched to profile: network-throughput\nactive: network-throughput"),
    V2(id="tuned-off-v2-0001", tool="tuned", operation="off",
       complexity="single",
       user_input="Turn off tuning entirely on this host.",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
    V2(id="tuned-off-v2-0002", tool="tuned", operation="off",
       complexity="diagnostic",
       user_input="We're trying to isolate whether throughput-performance is causing the odd network jitter — can we disable tuning to rule it out?",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
    V2(id="tuned-off-v2-0003", tool="tuned", operation="off",
       complexity="single",
       user_input="disable the active tuning profile",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
    V2(id="tuned-off-v2-0004", tool="tuned", operation="off",
       complexity="multi",
       user_input="Deactivate tuning for now, then reapply balanced once the benchmark finishes.",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
    V2(id="tuned-off-v2-0005", tool="tuned", operation="off",
       complexity="single",
       user_input="stop tuned from applying any profile",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
    V2(id="tuned-off-v2-0006", tool="tuned", operation="off",
       complexity="diagnostic",
       user_input="A vendor support case for the storage controller asked us to rule out any active performance tuning — can that be switched off temporarily?",
       args={"operation": "off"},
       answer="tuned profile deactivated\nactive: none"),
]

from finetune.scenarios_v2 import check_module; check_module("tuned", SCENARIOS_V2)
