"""finetune/scenarios_v2/users.py -- corpus v2 scenarios for 'users'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    V2(
        id='users-list-v2-0001',
        tool='users',
        operation='list',
        complexity='single',
        user_input='Show me every local account configured on this host.',
        args={'operation': 'list'},
        answer='root:0:0\ndeploy:1001:1001\njdoe:1002:1002\nsvc-backup:1003:1003\nnginx:993:990\n5 accounts listed',
    ),
    V2(
        id='users-list-v2-0002',
        tool='users',
        operation='list',
        complexity='diagnostic',
        user_input="A login attempt from a name we don't recognize was flagged in the audit log — list the accounts so I can check if it even exists here.",
        args={'operation': 'list'},
        answer="root:0:0\ndeploy:1001:1001\njdoe:1002:1002\nasmith:1004:1004\n4 accounts listed; no account named 'mkovacs' found",
    ),
    V2(
        id='users-list-v2-0003',
        tool='users',
        operation='list',
        complexity='single',
        user_input='list every local user',
        args={'operation': 'list'},
        answer='root:0:0\nadm:3:4\ndeploy:1001:1001\nsvc-monitor:1005:1005\n4 accounts listed',
    ),
    V2(
        id='users-list-v2-0004',
        tool='users',
        operation='list',
        complexity='multi',
        user_input="List all accounts, then I'll check which ones still have a login shell set.",
        args={'operation': 'list'},
        answer='root:0:0:/bin/bash\ndeploy:1001:1001:/bin/bash\njdoe:1002:1002:/bin/bash\nsvc-backup:1003:1003:/sbin/nologin\n4 accounts listed',
    ),
    V2(
        id='users-list-v2-0005',
        tool='users',
        operation='list',
        complexity='diagnostic',
        user_input="Onboarding says a 'kwhite' account should already exist on this box — is it there?",
        args={'operation': 'list'},
        answer="root:0:0\ndeploy:1001:1001\njdoe:1002:1002\n3 accounts listed; no account named 'kwhite' found",
    ),
    V2(
        id='users-list-v2-0006',
        tool='users',
        operation='list',
        complexity='single',
        user_input='What users are configured on this machine right now?',
        args={'operation': 'list'},
        answer='root:0:0\ndeploy:1001:1001\nsvc-backup:1003:1003\nsvc-monitor:1005:1005\n4 accounts listed',
    ),
    V2(
        id='users-list-v2-0007',
        tool='users',
        operation='list',
        complexity='diagnostic',
        user_input="sssd is throwing auth errors for a local fallback account — can you list what's actually defined locally?",
        args={'operation': 'list'},
        answer='root:0:0\ndeploy:1001:1001\njdoe:1002:1002\n3 accounts listed',
    ),
    V2(
        id='users-info-v2-0008',
        tool='users',
        operation='info',
        complexity='single',
        user_input='Show me the account record for deploy.',
        args={'operation': 'info', 'user': 'deploy'},
        answer='uid=1001(deploy) gid=1001(deploy) groups=1001(deploy),10(wheel)\nShell: /bin/bash\nHome: /home/deploy\nLocked: no',
    ),
    V2(
        id='users-info-v2-0009',
        tool='users',
        operation='info',
        complexity='single',
        user_input="Pull up jdoe's account details.",
        args={'operation': 'info', 'user': 'jdoe'},
        answer='uid=1002(jdoe) gid=1002(jdoe) groups=1002(jdoe)\nShell: /bin/bash\nHome: /home/jdoe\nLocked: no',
    ),
    V2(
        id='users-info-v2-0010',
        tool='users',
        operation='info',
        complexity='diagnostic',
        user_input='The nightly backup job started failing with a permissions error — check what groups svc-backup actually belongs to.',
        args={'operation': 'info', 'user': 'svc-backup'},
        answer='uid=1003(svc-backup) gid=1003(svc-backup) groups=1003(svc-backup),994(backup)\nShell: /sbin/nologin\nHome: /var/lib/svc-backup\nLocked: no',
    ),
    V2(
        id='users-info-v2-0011',
        tool='users',
        operation='info',
        complexity='diagnostic',
        user_input="HR flagged that asmith's account should have been disabled last week — check its current state.",
        args={'operation': 'info', 'user': 'asmith'},
        answer='uid=1004(asmith) gid=1004(asmith) groups=1004(asmith)\nShell: /bin/bash\nHome: /home/asmith\nLocked: yes',
    ),
    V2(
        id='users-info-v2-0012',
        tool='users',
        operation='info',
        complexity='single',
        user_input='info for svc-monitor',
        args={'operation': 'info', 'user': 'svc-monitor'},
        answer='uid=1005(svc-monitor) gid=1005(svc-monitor) groups=1005(svc-monitor)\nShell: /sbin/nologin\nHome: /var/lib/svc-monitor\nLocked: no',
    ),
    V2(
        id='users-info-v2-0013',
        tool='users',
        operation='info',
        complexity='multi',
        user_input='Show the root account record, then I want to compare its groups against wheel membership.',
        args={'operation': 'info', 'user': 'root'},
        answer='uid=0(root) gid=0(root) groups=0(root)\nShell: /bin/bash\nHome: /root\nLocked: no',
    ),
    V2(
        id='users-info-v2-0014',
        tool='users',
        operation='info',
        complexity='single',
        user_input="What's the shell and home directory set for kwhite?",
        args={'operation': 'info', 'user': 'kwhite'},
        answer='uid=1006(kwhite) gid=1006(kwhite) groups=1006(kwhite),10(wheel)\nShell: /bin/zsh\nHome: /home/kwhite\nLocked: no',
    ),
    V2(
        id='users-add-v2-0015',
        tool='users',
        operation='add',
        complexity='single',
        user_input='Create a new account for kwhite.',
        args={'operation': 'add', 'user': 'kwhite'},
        answer="Account 'kwhite' created.\nuid=1006(kwhite) gid=1006(kwhite)\nHome: /home/kwhite",
    ),
    V2(
        id='users-add-v2-0016',
        tool='users',
        operation='add',
        complexity='single',
        user_input='We need a service account named svc-report for the new reporting job.',
        args={'operation': 'add', 'user': 'svc-report'},
        answer="Account 'svc-report' created.\nuid=1007(svc-report) gid=1007(svc-report)\nHome: /home/svc-report",
    ),
    V2(
        id='users-add-v2-0017',
        tool='users',
        operation='add',
        complexity='multi',
        user_input='Add an account for bpatel, then put them in the wheel group.',
        args={'operation': 'add', 'user': 'bpatel'},
        answer="Account 'bpatel' created.\nuid=1008(bpatel) gid=1008(bpatel)\nHome: /home/bpatel",
    ),
    V2(
        id='users-add-v2-0018',
        tool='users',
        operation='add',
        complexity='diagnostic',
        user_input='The onboarding ticket for tlee is still open because no account exists yet — create it.',
        args={'operation': 'add', 'user': 'tlee'},
        answer="Account 'tlee' created.\nuid=1009(tlee) gid=1009(tlee)\nHome: /home/tlee",
    ),
    V2(
        id='users-add-v2-0019',
        tool='users',
        operation='add',
        complexity='single',
        user_input='useradd svc-deploy2',
        args={'operation': 'add', 'user': 'svc-deploy2'},
        answer="Account 'svc-deploy2' created.\nuid=1010(svc-deploy2) gid=1010(svc-deploy2)\nHome: /home/svc-deploy2",
    ),
    V2(
        id='users-add-v2-0020',
        tool='users',
        operation='add',
        complexity='single',
        user_input='New hire mgarcia starts Monday — get their local account created.',
        args={'operation': 'add', 'user': 'mgarcia'},
        answer="Account 'mgarcia' created.\nuid=1011(mgarcia) gid=1011(mgarcia)\nHome: /home/mgarcia",
    ),
    V2(
        id='users-add-v2-0021',
        tool='users',
        operation='add',
        complexity='diagnostic',
        user_input="The audit tooling can't run because there's no dedicated account for it — set one up called svc-audit.",
        args={'operation': 'add', 'user': 'svc-audit'},
        answer="Account 'svc-audit' created.\nuid=1012(svc-audit) gid=1012(svc-audit)\nHome: /home/svc-audit",
    ),
    V2(
        id='users-set_shell-v2-0022',
        tool='users',
        operation='set_shell',
        complexity='single',
        user_input="Change jdoe's login shell to zsh.",
        args={'operation': 'set_shell', 'user': 'jdoe', 'shell': '/bin/zsh'},
        answer="Shell for 'jdoe' set to /bin/zsh",
    ),
    V2(
        id='users-set_shell-v2-0023',
        tool='users',
        operation='set_shell',
        complexity='single',
        user_input="Lock down the shell for svc-backup so it can't be used to log in interactively.",
        args={'operation': 'set_shell', 'user': 'svc-backup', 'shell': '/sbin/nologin'},
        answer="Shell for 'svc-backup' set to /sbin/nologin",
    ),
    V2(
        id='users-set_shell-v2-0024',
        tool='users',
        operation='set_shell',
        complexity='multi',
        user_input="Set deploy's shell to bash, then add them to the docker group.",
        args={'operation': 'set_shell', 'user': 'deploy', 'shell': '/bin/bash'},
        answer="Shell for 'deploy' set to /bin/bash",
    ),
    V2(
        id='users-set_shell-v2-0025',
        tool='users',
        operation='set_shell',
        complexity='single',
        user_input='kwhite wants fish as their default shell.',
        args={'operation': 'set_shell', 'user': 'kwhite', 'shell': '/bin/fish'},
        answer="Shell for 'kwhite' set to /bin/fish",
    ),
    V2(
        id='users-set_shell-v2-0026',
        tool='users',
        operation='set_shell',
        complexity='diagnostic',
        user_input="asmith's account shows an interactive shell even though it's supposed to be a locked-out service login — fix the shell.",
        args={'operation': 'set_shell', 'user': 'asmith', 'shell': '/sbin/nologin'},
        answer="Shell for 'asmith' set to /sbin/nologin",
    ),
    V2(
        id='users-set_shell-v2-0027',
        tool='users',
        operation='set_shell',
        complexity='single',
        user_input='set-shell bpatel /bin/bash',
        args={'operation': 'set_shell', 'user': 'bpatel', 'shell': '/bin/bash'},
        answer="Shell for 'bpatel' set to /bin/bash",
    ),
    V2(
        id='users-set_shell-v2-0028',
        tool='users',
        operation='set_shell',
        complexity='diagnostic',
        user_input='The monitor daemon account somehow got an interactive shell during the last provisioning run — correct that.',
        args={'operation': 'set_shell', 'user': 'svc-monitor', 'shell': '/sbin/nologin'},
        answer="Shell for 'svc-monitor' set to /sbin/nologin",
    ),
    V2(
        id='users-set_shell-v2-0029',
        tool='users',
        operation='set_shell',
        complexity='single',
        user_input="Set tlee's shell to csh, that's what their old workstation used.",
        args={'operation': 'set_shell', 'user': 'tlee', 'shell': '/bin/csh'},
        answer="Shell for 'tlee' set to /bin/csh",
    ),
    V2(
        id='users-add_to_group-v2-0030',
        tool='users',
        operation='add_to_group',
        complexity='single',
        user_input='Add jdoe to the docker group so they can run containers.',
        args={'operation': 'add_to_group', 'user': 'jdoe', 'group': 'docker'},
        answer="'jdoe' added to group 'docker'",
    ),
    V2(
        id='users-add_to_group-v2-0031',
        tool='users',
        operation='add_to_group',
        complexity='single',
        user_input='deploy needs sudo access — add them to wheel.',
        args={'operation': 'add_to_group', 'user': 'deploy', 'group': 'wheel'},
        answer="'deploy' added to group 'wheel'",
    ),
    V2(
        id='users-add_to_group-v2-0032',
        tool='users',
        operation='add_to_group',
        complexity='multi',
        user_input='Add kwhite to the developers group, then set their shell to bash.',
        args={'operation': 'add_to_group', 'user': 'kwhite', 'group': 'developers'},
        answer="'kwhite' added to group 'developers'",
    ),
    V2(
        id='users-add_to_group-v2-0033',
        tool='users',
        operation='add_to_group',
        complexity='diagnostic',
        user_input='The backup job keeps failing with a permission denied on /var/backups — check if svc-backup is even in the backup group and add it if not.',
        args={'operation': 'add_to_group', 'user': 'svc-backup', 'group': 'backup'},
        answer="'svc-backup' added to group 'backup'",
    ),
    V2(
        id='users-add_to_group-v2-0034',
        tool='users',
        operation='add_to_group',
        complexity='single',
        user_input='add bpatel to wheel',
        args={'operation': 'add_to_group', 'user': 'bpatel', 'group': 'wheel'},
        answer="'bpatel' added to group 'wheel'",
    ),
    V2(
        id='users-add_to_group-v2-0035',
        tool='users',
        operation='add_to_group',
        complexity='single',
        user_input='Put asmith into the sales group per the reorg ticket.',
        args={'operation': 'add_to_group', 'user': 'asmith', 'group': 'sales'},
        answer="'asmith' added to group 'sales'",
    ),
    V2(
        id='users-add_to_group-v2-0036',
        tool='users',
        operation='add_to_group',
        complexity='diagnostic',
        user_input="The monitor daemon can't read /var/log entries it needs — it's probably missing from the adm group, add it.",
        args={'operation': 'add_to_group', 'user': 'svc-monitor', 'group': 'adm'},
        answer="'svc-monitor' added to group 'adm'",
    ),
    V2(
        id='users-lock-v2-0037',
        tool='users',
        operation='lock',
        complexity='single',
        user_input="Lock asmith's account, they left the company yesterday.",
        args={'operation': 'lock', 'user': 'asmith'},
        answer="Account 'asmith' locked.",
    ),
    V2(
        id='users-lock-v2-0038',
        tool='users',
        operation='lock',
        complexity='diagnostic',
        user_input="Security flagged repeated failed logins on kwhite's account — lock it until we investigate.",
        args={'operation': 'lock', 'user': 'kwhite'},
        answer="Account 'kwhite' locked.",
    ),
    V2(
        id='users-lock-v2-0039',
        tool='users',
        operation='lock',
        complexity='single',
        user_input='lock tlee',
        args={'operation': 'lock', 'user': 'tlee'},
        answer="Account 'tlee' locked.",
    ),
    V2(
        id='users-lock-v2-0040',
        tool='users',
        operation='lock',
        complexity='multi',
        user_input="Lock the svc-report account, then we'll delete it next sprint.",
        args={'operation': 'lock', 'user': 'svc-report'},
        answer="Account 'svc-report' locked.",
    ),
    V2(
        id='users-lock-v2-0041',
        tool='users',
        operation='lock',
        complexity='single',
        user_input='bpatel is on extended leave — lock their account for now.',
        args={'operation': 'lock', 'user': 'bpatel'},
        answer="Account 'bpatel' locked.",
    ),
    V2(
        id='users-lock-v2-0042',
        tool='users',
        operation='lock',
        complexity='diagnostic',
        user_input="HR says mgarcia's contract ended last Friday but the account still shows active — lock it.",
        args={'operation': 'lock', 'user': 'mgarcia'},
        answer="Account 'mgarcia' locked.",
    ),
    V2(
        id='users-lock-v2-0043',
        tool='users',
        operation='lock',
        complexity='single',
        user_input="Freeze the svc-audit account, we're rotating credentials.",
        args={'operation': 'lock', 'user': 'svc-audit'},
        answer="Account 'svc-audit' locked.",
    ),
    V2(
        id='users-delete-v2-0044',
        tool='users',
        operation='delete',
        complexity='single',
        user_input='Delete the tlee account, offboarding is complete.',
        args={'operation': 'delete', 'user': 'tlee'},
        answer="Account 'tlee' deleted.",
    ),
    V2(
        id='users-delete-v2-0045',
        tool='users',
        operation='delete',
        complexity='single',
        user_input="Remove the svc-report service account, it's no longer used.",
        args={'operation': 'delete', 'user': 'svc-report'},
        answer="Account 'svc-report' deleted.",
    ),
    V2(
        id='users-delete-v2-0046',
        tool='users',
        operation='delete',
        complexity='diagnostic',
        user_input="asmith's account has been locked for 90 days per policy with no reinstatement request — clean it up.",
        args={'operation': 'delete', 'user': 'asmith'},
        answer="Account 'asmith' deleted.",
    ),
    V2(
        id='users-delete-v2-0047',
        tool='users',
        operation='delete',
        complexity='multi',
        user_input="Delete bpatel's account, then confirm with a fresh account list.",
        args={'operation': 'delete', 'user': 'bpatel'},
        answer="Account 'bpatel' deleted.",
    ),
    V2(
        id='users-delete-v2-0048',
        tool='users',
        operation='delete',
        complexity='single',
        user_input='userdel svc-old',
        args={'operation': 'delete', 'user': 'svc-old'},
        answer="Account 'svc-old' deleted.",
    ),
    V2(
        id='users-delete-v2-0049',
        tool='users',
        operation='delete',
        complexity='diagnostic',
        user_input='The exit checklist for kwhite is fully signed off — remove their local account.',
        args={'operation': 'delete', 'user': 'kwhite'},
        answer="Account 'kwhite' deleted.",
    ),
    V2(
        id='users-delete-v2-0050',
        tool='users',
        operation='delete',
        complexity='single',
        user_input="mgarcia's contract account should be fully removed now, not just locked.",
        args={'operation': 'delete', 'user': 'mgarcia'},
        answer="Account 'mgarcia' deleted.",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0051',
        tool='users',
        operation='remove_from_privgroup',
        complexity='single',
        user_input="Take jdoe out of the sudoers group, they don't need admin rights anymore.",
        args={'operation': 'remove_from_privgroup', 'user': 'jdoe'},
        answer="'jdoe' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0052',
        tool='users',
        operation='remove_from_privgroup',
        complexity='diagnostic',
        user_input="A security review found deploy has standing sudo access it shouldn't — pull that privilege.",
        args={'operation': 'remove_from_privgroup', 'user': 'deploy'},
        answer="'deploy' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0053',
        tool='users',
        operation='remove_from_privgroup',
        complexity='single',
        user_input='remove bpatel from wheel',
        args={'operation': 'remove_from_privgroup', 'user': 'bpatel'},
        answer="'bpatel' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0054',
        tool='users',
        operation='remove_from_privgroup',
        complexity='multi',
        user_input='Remove kwhite from the privileged group, then lock their account.',
        args={'operation': 'remove_from_privgroup', 'user': 'kwhite'},
        answer="'kwhite' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0055',
        tool='users',
        operation='remove_from_privgroup',
        complexity='single',
        user_input="asmith's role changed and no longer needs elevated access — revoke it.",
        args={'operation': 'remove_from_privgroup', 'user': 'asmith'},
        answer="'asmith' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0056',
        tool='users',
        operation='remove_from_privgroup',
        complexity='diagnostic',
        user_input='The audit flagged a service account with sudo it never should have had — strip that from svc-deploy2.',
        args={'operation': 'remove_from_privgroup', 'user': 'svc-deploy2'},
        answer="'svc-deploy2' removed from privileged group 'wheel'",
    ),
    V2(
        id='users-remove_from_privgroup-v2-0057',
        tool='users',
        operation='remove_from_privgroup',
        complexity='single',
        user_input='Pull mgarcia off the admin group, their access request was denied.',
        args={'operation': 'remove_from_privgroup', 'user': 'mgarcia'},
        answer="'mgarcia' removed from privileged group 'wheel'",
    ),
]

from finetune.scenarios_v2 import check_module; check_module('users', SCENARIOS_V2)
