"""finetune/scenarios_v2/virsh.py — corpus v2 scenarios for 'virsh'."""
from finetune.scenarios_v2 import V2

SCENARIOS_V2 = [
    # list (11)
    V2(id="virsh-list-v2-0001", tool="virsh", operation="list", complexity="single",
       user_input="Show all defined domains on this hypervisor.",
       args={"operation": "list"},
       answer=" Id   Name          State\n 1    web-vm01      running\n -    build-vm02    shut off"),
    V2(id="virsh-list-v2-0002", tool="virsh", operation="list", complexity="diagnostic",
       user_input="A tenant says their VM vanished from the console — is it still defined on this host at all?",
       args={"operation": "list"},
       answer=" Id   Name          State\n 3    db-vm03       running\n -    legacy-vm04   shut off"),
    V2(id="virsh-list-v2-0003", tool="virsh", operation="list", complexity="single",
       user_input="which domains are shut off right now",
       args={"operation": "list"},
       answer=" Id   Name          State\n -    stage-vm05    shut off\n -    test-vm06     shut off"),
    V2(id="virsh-list-v2-0004", tool="virsh", operation="list", complexity="multi",
       user_input="List all VMs, then pull dominfo for whichever one is running.",
       args={"operation": "list"},
       answer=" Id   Name          State\n 2    cache-vm07    running"),
    V2(id="virsh-list-v2-0005", tool="virsh", operation="list", complexity="single",
       user_input="Ticket 4410: confirm how many domains are defined on kvm-host2 before the capacity review.",
       args={"operation": "list"},
       answer=" Id   Name          State\n 1    app-vm08      running\n 4    app-vm09      running\n -    old-vm10      shut off"),
    V2(id="virsh-list-v2-0006", tool="virsh", operation="list", complexity="diagnostic",
       user_input="The hypervisor is under strange load — first, what domains does it think are running?",
       args={"operation": "list"},
       answer=" Id   Name          State\n 5    render-vm11   running\n 6    render-vm12   running\n 7    render-vm13   running"),
    V2(id="virsh-list-v2-0007", tool="virsh", operation="list", complexity="single",
       user_input="list every VM on the box, including inactive ones",
       args={"operation": "list"},
       answer=" Id   Name          State\n 8    mail-vm14     running\n -    mail-vm15     shut off"),
    V2(id="virsh-list-v2-0008", tool="virsh", operation="list", complexity="single",
       user_input="How many virtual machines are configured on kvm-host3?",
       args={"operation": "list"},
       answer=" Id   Name          State\n -    demo-vm16     shut off"),
    V2(id="virsh-list-v2-0009", tool="virsh", operation="list", complexity="diagnostic",
       user_input="Monitoring shows this hypervisor's CPU pegged — which guest domains are actually up?",
       args={"operation": "list"},
       answer=" Id   Name          State\n 9    encode-vm17   running\n 10   encode-vm18   running"),
    V2(id="virsh-list-v2-0010", tool="virsh", operation="list", complexity="single",
       user_input="Ticket 9902: list domains on the lab hypervisor before decommissioning unused ones.",
       args={"operation": "list"},
       answer=" Id   Name          State\n -    sandbox-vm19  shut off\n -    sandbox-vm20  shut off"),
    V2(id="virsh-list-v2-0011", tool="virsh", operation="list", complexity="single",
       user_input="show me the VM inventory on this box",
       args={"operation": "list"},
       answer=" Id   Name          State\n 11   proxy-vm21    running"),

    # dominfo (11)
    V2(id="virsh-dominfo-v2-0001", tool="virsh", operation="dominfo", complexity="single",
       user_input="Show detailed info for web-vm01.",
       args={"operation": "dominfo", "domain": "web-vm01"},
       answer="Id: 1\nName: web-vm01\nState: running\nCPU(s): 4\nMax memory: 8388608 KiB"),
    V2(id="virsh-dominfo-v2-0002", tool="virsh", operation="dominfo", complexity="diagnostic",
       user_input="db-vm03 seems to be swapping heavily — what's it actually provisioned with?",
       args={"operation": "dominfo", "domain": "db-vm03"},
       answer="Id: 3\nName: db-vm03\nState: running\nCPU(s): 2\nMax memory: 4194304 KiB"),
    V2(id="virsh-dominfo-v2-0003", tool="virsh", operation="dominfo", complexity="single",
       user_input="give me dominfo for legacy-vm04",
       args={"operation": "dominfo", "domain": "legacy-vm04"},
       answer="Id: -\nName: legacy-vm04\nState: shut off\nCPU(s): 1\nMax memory: 2097152 KiB"),
    V2(id="virsh-dominfo-v2-0004", tool="virsh", operation="dominfo", complexity="multi",
       user_input="Pull dominfo on cache-vm07, then start it if it shows shut off.",
       args={"operation": "dominfo", "domain": "cache-vm07"},
       answer="Id: -\nName: cache-vm07\nState: shut off\nCPU(s): 2\nMax memory: 4194304 KiB"),
    V2(id="virsh-dominfo-v2-0005", tool="virsh", operation="dominfo", complexity="single",
       user_input="Ticket 3312: confirm the vCPU count on app-vm08 before the resize request.",
       args={"operation": "dominfo", "domain": "app-vm08"},
       answer="Id: 1\nName: app-vm08\nState: running\nCPU(s): 8\nMax memory: 16777216 KiB"),
    V2(id="virsh-dominfo-v2-0006", tool="virsh", operation="dominfo", complexity="diagnostic",
       user_input="render-vm11 keeps stalling mid-job — check its autostart flag and current state.",
       args={"operation": "dominfo", "domain": "render-vm11"},
       answer="Id: 5\nName: render-vm11\nState: running\nAutostart: disable\nCPU(s): 4"),
    V2(id="virsh-dominfo-v2-0007", tool="virsh", operation="dominfo", complexity="single",
       user_input="dominfo on mail-vm14 please",
       args={"operation": "dominfo", "domain": "mail-vm14"},
       answer="Id: 8\nName: mail-vm14\nState: running\nCPU(s): 2\nMax memory: 4194304 KiB"),
    V2(id="virsh-dominfo-v2-0008", tool="virsh", operation="dominfo", complexity="single",
       user_input="How much memory is demo-vm16 configured with?",
       args={"operation": "dominfo", "domain": "demo-vm16"},
       answer="Id: -\nName: demo-vm16\nState: shut off\nMax memory: 1048576 KiB"),
    V2(id="virsh-dominfo-v2-0009", tool="virsh", operation="dominfo", complexity="diagnostic",
       user_input="Something about encode-vm17's persistence flag looks wrong in the console — check its domain info.",
       args={"operation": "dominfo", "domain": "encode-vm17"},
       answer="Id: 9\nName: encode-vm17\nState: running\nPersistent: yes\nAutostart: enable"),
    V2(id="virsh-dominfo-v2-0010", tool="virsh", operation="dominfo", complexity="single",
       user_input="Ticket 6650: get dominfo for sandbox-vm19 ahead of teardown.",
       args={"operation": "dominfo", "domain": "sandbox-vm19"},
       answer="Id: -\nName: sandbox-vm19\nState: shut off\nCPU(s): 1\nMax memory: 1048576 KiB"),
    V2(id="virsh-dominfo-v2-0011", tool="virsh", operation="dominfo", complexity="single",
       user_input="show me detail on proxy-vm21",
       args={"operation": "dominfo", "domain": "proxy-vm21"},
       answer="Id: 11\nName: proxy-vm21\nState: running\nCPU(s): 2\nMax memory: 2097152 KiB"),

    # start (11)
    V2(id="virsh-start-v2-0001", tool="virsh", operation="start", complexity="single",
       user_input="Start the cache-vm07 domain.",
       args={"operation": "start", "domain": "cache-vm07"},
       answer="Domain cache-vm07 started"),
    V2(id="virsh-start-v2-0002", tool="virsh", operation="start", complexity="diagnostic",
       user_input="cache-vm07 shows shut off but should be serving traffic — bring it up.",
       args={"operation": "start", "domain": "cache-vm07"},
       answer="Domain cache-vm07 started"),
    V2(id="virsh-start-v2-0003", tool="virsh", operation="start", complexity="multi",
       user_input="Start demo-vm16 and then check dominfo to confirm it's running.",
       args={"operation": "start", "domain": "demo-vm16"},
       answer="Domain demo-vm16 started"),
    V2(id="virsh-start-v2-0004", tool="virsh", operation="start", complexity="single",
       user_input="boot up sandbox-vm19",
       args={"operation": "start", "domain": "sandbox-vm19"},
       answer="Domain sandbox-vm19 started"),
    V2(id="virsh-start-v2-0005", tool="virsh", operation="start", complexity="single",
       user_input="Ticket 7712: power on stage-vm05 for the QA run.",
       args={"operation": "start", "domain": "stage-vm05"},
       answer="Domain stage-vm05 started"),
    V2(id="virsh-start-v2-0006", tool="virsh", operation="start", complexity="single",
       user_input="start test-vm06",
       args={"operation": "start", "domain": "test-vm06"},
       answer="Domain test-vm06 started"),
    V2(id="virsh-start-v2-0007", tool="virsh", operation="start", complexity="diagnostic",
       user_input="mail-vm15 has been sitting shut off since the migration — start it back up.",
       args={"operation": "start", "domain": "mail-vm15"},
       answer="Domain mail-vm15 started"),
    V2(id="virsh-start-v2-0008", tool="virsh", operation="start", complexity="single",
       user_input="Ticket 8834: start old-vm10 for a one-off data recovery.",
       args={"operation": "start", "domain": "old-vm10"},
       answer="Domain old-vm10 started"),
    V2(id="virsh-start-v2-0009", tool="virsh", operation="start", complexity="single",
       user_input="power up sandbox-vm20",
       args={"operation": "start", "domain": "sandbox-vm20"},
       answer="Domain sandbox-vm20 started"),
    V2(id="virsh-start-v2-0010", tool="virsh", operation="start", complexity="multi",
       user_input="Start legacy-vm04, then tail its console logs for boot errors.",
       args={"operation": "start", "domain": "legacy-vm04"},
       answer="Domain legacy-vm04 started"),
    V2(id="virsh-start-v2-0011", tool="virsh", operation="start", complexity="single",
       user_input="get build-vm02 running again",
       args={"operation": "start", "domain": "build-vm02"},
       answer="Domain build-vm02 started"),

    # shutdown (11)
    V2(id="virsh-shutdown-v2-0001", tool="virsh", operation="shutdown", complexity="single",
       user_input="Gracefully shut down web-vm01.",
       args={"operation": "shutdown", "domain": "web-vm01"},
       answer="Domain web-vm01 is being shut down"),
    V2(id="virsh-shutdown-v2-0002", tool="virsh", operation="shutdown", complexity="diagnostic",
       user_input="We're decommissioning old-vm10 tonight — send it a clean shutdown first.",
       args={"operation": "shutdown", "domain": "old-vm10"},
       answer="Domain old-vm10 is being shut down"),
    V2(id="virsh-shutdown-v2-0003", tool="virsh", operation="shutdown", complexity="multi",
       user_input="Shut down db-vm03 cleanly, then undefine it once it's off.",
       args={"operation": "shutdown", "domain": "db-vm03"},
       answer="Domain db-vm03 is being shut down"),
    V2(id="virsh-shutdown-v2-0004", tool="virsh", operation="shutdown", complexity="single",
       user_input="power down app-vm09 the graceful way",
       args={"operation": "shutdown", "domain": "app-vm09"},
       answer="Domain app-vm09 is being shut down"),
    V2(id="virsh-shutdown-v2-0005", tool="virsh", operation="shutdown", complexity="single",
       user_input="Ticket 5521: shut down render-vm12 for the maintenance window.",
       args={"operation": "shutdown", "domain": "render-vm12"},
       answer="Domain render-vm12 is being shut down"),
    V2(id="virsh-shutdown-v2-0006", tool="virsh", operation="shutdown", complexity="single",
       user_input="shutdown mail-vm14",
       args={"operation": "shutdown", "domain": "mail-vm14"},
       answer="Domain mail-vm14 is being shut down"),
    V2(id="virsh-shutdown-v2-0007", tool="virsh", operation="shutdown", complexity="diagnostic",
       user_input="encode-vm18 is done with its job queue — shut it down to free capacity.",
       args={"operation": "shutdown", "domain": "encode-vm18"},
       answer="Domain encode-vm18 is being shut down"),
    V2(id="virsh-shutdown-v2-0008", tool="virsh", operation="shutdown", complexity="single",
       user_input="Ticket 6612: gracefully power off proxy-vm21 ahead of the network change.",
       args={"operation": "shutdown", "domain": "proxy-vm21"},
       answer="Domain proxy-vm21 is being shut down"),
    V2(id="virsh-shutdown-v2-0009", tool="virsh", operation="shutdown", complexity="single",
       user_input="send an ACPI shutdown to render-vm13",
       args={"operation": "shutdown", "domain": "render-vm13"},
       answer="Domain render-vm13 is being shut down"),
    V2(id="virsh-shutdown-v2-0010", tool="virsh", operation="shutdown", complexity="multi",
       user_input="Shut down encode-vm17, then check virsh list to confirm it's off.",
       args={"operation": "shutdown", "domain": "encode-vm17"},
       answer="Domain encode-vm17 is being shut down"),
    V2(id="virsh-shutdown-v2-0011", tool="virsh", operation="shutdown", complexity="single",
       user_input="cleanly power off cache-vm07",
       args={"operation": "shutdown", "domain": "cache-vm07"},
       answer="Domain cache-vm07 is being shut down"),

    # define (12)
    V2(id="virsh-define-v2-0001", tool="virsh", operation="define", complexity="single",
       user_input="Define a new domain from /tmp/newapp-vm.xml.",
       args={"operation": "define", "xmlfile": "/tmp/newapp-vm.xml"},
       answer="Domain newapp-vm defined from /tmp/newapp-vm.xml"),
    V2(id="virsh-define-v2-0002", tool="virsh", operation="define", complexity="multi",
       user_input="Define the domain from /root/staging-vm.xml, then start it.",
       args={"operation": "define", "xmlfile": "/root/staging-vm.xml"},
       answer="Domain staging-vm defined from /root/staging-vm.xml"),
    V2(id="virsh-define-v2-0003", tool="virsh", operation="define", complexity="single",
       user_input="register a domain using /var/lib/libvirt/xml/qa-vm.xml",
       args={"operation": "define", "xmlfile": "/var/lib/libvirt/xml/qa-vm.xml"},
       answer="Domain qa-vm defined from /var/lib/libvirt/xml/qa-vm.xml"),
    V2(id="virsh-define-v2-0004", tool="virsh", operation="define", complexity="single",
       user_input="Ticket 9911: define the replacement VM described in /tmp/db-replica-vm.xml.",
       args={"operation": "define", "xmlfile": "/tmp/db-replica-vm.xml"},
       answer="Domain db-replica-vm defined from /tmp/db-replica-vm.xml"),
    V2(id="virsh-define-v2-0005", tool="virsh", operation="define", complexity="diagnostic",
       user_input="The provisioning script dropped an XML at /tmp/gen-vm-042.xml but nothing shows in the domain list — define it manually.",
       args={"operation": "define", "xmlfile": "/tmp/gen-vm-042.xml"},
       answer="Domain gen-vm-042 defined from /tmp/gen-vm-042.xml"),
    V2(id="virsh-define-v2-0006", tool="virsh", operation="define", complexity="single",
       user_input="define /home/opuser/lab-vm.xml as a new guest",
       args={"operation": "define", "xmlfile": "/home/opuser/lab-vm.xml"},
       answer="Domain lab-vm defined from /home/opuser/lab-vm.xml"),
    V2(id="virsh-define-v2-0007", tool="virsh", operation="define", complexity="single",
       user_input="Ticket 2245: define the analytics worker VM from /tmp/analytics-vm3.xml.",
       args={"operation": "define", "xmlfile": "/tmp/analytics-vm3.xml"},
       answer="Domain analytics-vm3 defined from /tmp/analytics-vm3.xml"),
    V2(id="virsh-define-v2-0008", tool="virsh", operation="define", complexity="single",
       user_input="load the domain config at /tmp/edge-router-vm.xml",
       args={"operation": "define", "xmlfile": "/tmp/edge-router-vm.xml"},
       answer="Domain edge-router-vm defined from /tmp/edge-router-vm.xml"),
    V2(id="virsh-define-v2-0009", tool="virsh", operation="define", complexity="multi",
       user_input="Define /tmp/monitor-vm.xml and confirm it's listed afterward.",
       args={"operation": "define", "xmlfile": "/tmp/monitor-vm.xml"},
       answer="Domain monitor-vm defined from /tmp/monitor-vm.xml"),
    V2(id="virsh-define-v2-0010", tool="virsh", operation="define", complexity="single",
       user_input="Ticket 3391: define the disaster-recovery standby from /srv/dr-standby-vm.xml.",
       args={"operation": "define", "xmlfile": "/srv/dr-standby-vm.xml"},
       answer="Domain dr-standby-vm defined from /srv/dr-standby-vm.xml"),
    V2(id="virsh-define-v2-0011", tool="virsh", operation="define", complexity="single",
       user_input="use /tmp/etl-worker-vm.xml to define a new guest",
       args={"operation": "define", "xmlfile": "/tmp/etl-worker-vm.xml"},
       answer="Domain etl-worker-vm defined from /tmp/etl-worker-vm.xml"),
    V2(id="virsh-define-v2-0012", tool="virsh", operation="define", complexity="single",
       user_input="Define the sandbox guest from /tmp/sandbox-vm21.xml before the demo.",
       args={"operation": "define", "xmlfile": "/tmp/sandbox-vm21.xml"},
       answer="Domain sandbox-vm21 defined from /tmp/sandbox-vm21.xml"),

    # destroy (11)
    V2(id="virsh-destroy-v2-0001", tool="virsh", operation="destroy", complexity="single",
       user_input="Force power off render-vm11, it's completely unresponsive.",
       args={"operation": "destroy", "domain": "render-vm11"},
       answer="Domain render-vm11 destroyed"),
    V2(id="virsh-destroy-v2-0002", tool="virsh", operation="destroy", complexity="diagnostic",
       user_input="test-vm06 is hung and won't respond to a graceful shutdown — force it off.",
       args={"operation": "destroy", "domain": "test-vm06"},
       answer="Domain test-vm06 destroyed"),
    V2(id="virsh-destroy-v2-0003", tool="virsh", operation="destroy", complexity="single",
       user_input="hard kill sandbox-vm20 now",
       args={"operation": "destroy", "domain": "sandbox-vm20"},
       answer="Domain sandbox-vm20 destroyed"),
    V2(id="virsh-destroy-v2-0004", tool="virsh", operation="destroy", complexity="multi",
       user_input="Force off legacy-vm04, then undefine it entirely.",
       args={"operation": "destroy", "domain": "legacy-vm04"},
       answer="Domain legacy-vm04 destroyed"),
    V2(id="virsh-destroy-v2-0005", tool="virsh", operation="destroy", complexity="single",
       user_input="Ticket 4471: forcibly power off stage-vm05 after the failed patch left it stuck.",
       args={"operation": "destroy", "domain": "stage-vm05"},
       answer="Domain stage-vm05 destroyed"),
    V2(id="virsh-destroy-v2-0006", tool="virsh", operation="destroy", complexity="single",
       user_input="pull the plug on demo-vm16",
       args={"operation": "destroy", "domain": "demo-vm16"},
       answer="Domain demo-vm16 destroyed"),
    V2(id="virsh-destroy-v2-0007", tool="virsh", operation="destroy", complexity="diagnostic",
       user_input="encode-vm18's guest OS is deadlocked, shutdown isn't getting through — destroy it.",
       args={"operation": "destroy", "domain": "encode-vm18"},
       answer="Domain encode-vm18 destroyed"),
    V2(id="virsh-destroy-v2-0008", tool="virsh", operation="destroy", complexity="single",
       user_input="Ticket 5582: abruptly stop old-vm10, it's stuck mid-migration.",
       args={"operation": "destroy", "domain": "old-vm10"},
       answer="Domain old-vm10 destroyed"),
    V2(id="virsh-destroy-v2-0009", tool="virsh", operation="destroy", complexity="single",
       user_input="destroy build-vm02 right now, no graceful shutdown",
       args={"operation": "destroy", "domain": "build-vm02"},
       answer="Domain build-vm02 destroyed"),
    V2(id="virsh-destroy-v2-0010", tool="virsh", operation="destroy", complexity="single",
       user_input="Force off mail-vm15, it's not responding to ACPI events.",
       args={"operation": "destroy", "domain": "mail-vm15"},
       answer="Domain mail-vm15 destroyed"),
    V2(id="virsh-destroy-v2-0011", tool="virsh", operation="destroy", complexity="multi",
       user_input="Destroy proxy-vm21 immediately, then check the pool it stored disks in for orphaned volumes.",
       args={"operation": "destroy", "domain": "proxy-vm21"},
       answer="Domain proxy-vm21 destroyed"),

    # undefine (11)
    V2(id="virsh-undefine-v2-0001", tool="virsh", operation="undefine", complexity="single",
       user_input="Undefine legacy-vm04, we don't need the definition anymore.",
       args={"operation": "undefine", "domain": "legacy-vm04"},
       answer="Domain legacy-vm04 has been undefined"),
    V2(id="virsh-undefine-v2-0002", tool="virsh", operation="undefine", complexity="diagnostic",
       user_input="old-vm10 was decommissioned last week and is still cluttering virsh list — remove its definition.",
       args={"operation": "undefine", "domain": "old-vm10"},
       answer="Domain old-vm10 has been undefined"),
    V2(id="virsh-undefine-v2-0003", tool="virsh", operation="undefine", complexity="single",
       user_input="remove the sandbox-vm19 domain definition and wipe its disks too",
       args={"operation": "undefine", "domain": "sandbox-vm19", "remove_storage": True},
       answer="Domain sandbox-vm19 has been undefined\nVolume 'vda'(/var/lib/libvirt/images/sandbox-vm19.qcow2) removed"),
    V2(id="virsh-undefine-v2-0004", tool="virsh", operation="undefine", complexity="multi",
       user_input="Shut down demo-vm16, then undefine it and delete its storage.",
       args={"operation": "undefine", "domain": "demo-vm16", "remove_storage": True},
       answer="Domain demo-vm16 has been undefined\nVolume 'vda'(/var/lib/libvirt/images/demo-vm16.qcow2) removed"),
    V2(id="virsh-undefine-v2-0005", tool="virsh", operation="undefine", complexity="single",
       user_input="Ticket 6650: undefine test-vm06 without touching its disk image, we still need it for forensics.",
       args={"operation": "undefine", "domain": "test-vm06"},
       answer="Domain test-vm06 has been undefined"),
    V2(id="virsh-undefine-v2-0006", tool="virsh", operation="undefine", complexity="single",
       user_input="permanently delete sandbox-vm20 including its disks",
       args={"operation": "undefine", "domain": "sandbox-vm20", "remove_storage": True},
       answer="Domain sandbox-vm20 has been undefined\nVolume 'vda'(/var/lib/libvirt/images/sandbox-vm20.qcow2) removed"),
    V2(id="virsh-undefine-v2-0007", tool="virsh", operation="undefine", complexity="single",
       user_input="Ticket 7761: drop the definition for build-vm02, it was replaced by a fresh image last night.",
       args={"operation": "undefine", "domain": "build-vm02"},
       answer="Domain build-vm02 has been undefined"),
    V2(id="virsh-undefine-v2-0008", tool="virsh", operation="undefine", complexity="diagnostic",
       user_input="stage-vm05's storage pool is nearly full — can we reclaim space by undefining it with its volumes?",
       args={"operation": "undefine", "domain": "stage-vm05", "remove_storage": True},
       answer="Domain stage-vm05 has been undefined\nVolume 'vda'(/var/lib/libvirt/images/stage-vm05.qcow2) removed"),
    V2(id="virsh-undefine-v2-0009", tool="virsh", operation="undefine", complexity="single",
       user_input="undefine mail-vm15, keep the qcow2 file for now",
       args={"operation": "undefine", "domain": "mail-vm15"},
       answer="Domain mail-vm15 has been undefined"),
    V2(id="virsh-undefine-v2-0010", tool="virsh", operation="undefine", complexity="multi",
       user_input="Destroy render-vm12 first, then undefine it along with its storage.",
       args={"operation": "undefine", "domain": "render-vm12", "remove_storage": True},
       answer="Domain render-vm12 has been undefined\nVolume 'vda'(/var/lib/libvirt/images/render-vm12.qcow2) removed"),
    V2(id="virsh-undefine-v2-0011", tool="virsh", operation="undefine", complexity="single",
       user_input="Ticket 8802: remove the encode-vm17 domain definition, storage stays intact for reuse.",
       args={"operation": "undefine", "domain": "encode-vm17"},
       answer="Domain encode-vm17 has been undefined"),

    # pool-list (13)
    V2(id="virsh-pool-list-v2-0001", tool="virsh", operation="pool-list", complexity="single",
       user_input="List all storage pools on this hypervisor.",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\nfast-ssd    active     yes"),
    V2(id="virsh-pool-list-v2-0002", tool="virsh", operation="pool-list", complexity="diagnostic",
       user_input="A VM won't start and complains about missing storage — are all the storage pools even active?",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\narchive     inactive   no"),
    V2(id="virsh-pool-list-v2-0003", tool="virsh", operation="pool-list", complexity="single",
       user_input="what storage pools are defined",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes"),
    V2(id="virsh-pool-list-v2-0004", tool="virsh", operation="pool-list", complexity="multi",
       user_input="List the storage pools, then check dominfo for any VM whose disk lives in an inactive one.",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\nbackup-nfs  inactive   no"),
    V2(id="virsh-pool-list-v2-0005", tool="virsh", operation="pool-list", complexity="single",
       user_input="Ticket 3320: confirm pool state on kvm-host2 before adding a new volume.",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\nfast-ssd    active     yes"),
    V2(id="virsh-pool-list-v2-0006", tool="virsh", operation="pool-list", complexity="single",
       user_input="show pool-list output",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\niso-images  active     no"),
    V2(id="virsh-pool-list-v2-0007", tool="virsh", operation="pool-list", complexity="diagnostic",
       user_input="Disk provisioning failed for the last two VMs — is the target storage pool even up?",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\nfast-ssd    inactive   no"),
    V2(id="virsh-pool-list-v2-0008", tool="virsh", operation="pool-list", complexity="single",
       user_input="Ticket 4471: list storage pools on the DR hypervisor for the audit.",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\ndr-pool     active     yes"),
    V2(id="virsh-pool-list-v2-0009", tool="virsh", operation="pool-list", complexity="single",
       user_input="which pools are set to autostart",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\narchive     active     no"),
    V2(id="virsh-pool-list-v2-0010", tool="virsh", operation="pool-list", complexity="single",
       user_input="pull the storage pool list for the lab kvm host",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\nlab-pool    active     yes"),
    V2(id="virsh-pool-list-v2-0011", tool="virsh", operation="pool-list", complexity="diagnostic",
       user_input="Someone reported orphaned disk images taking up space — first, what pools exist here?",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\nscratch     inactive   no"),
    V2(id="virsh-pool-list-v2-0012", tool="virsh", operation="pool-list", complexity="single",
       user_input="Ticket 5591: list pools before we define a new one for the analytics cluster.",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes"),
    V2(id="virsh-pool-list-v2-0013", tool="virsh", operation="pool-list", complexity="single",
       user_input="show me every defined storage pool, active or not",
       args={"operation": "pool-list"},
       answer="Name        State      Autostart\ndefault     active     yes\ncold-storage inactive  no"),

    # pool-define (12)
    V2(id="virsh-pool-define-v2-0001", tool="virsh", operation="pool-define", complexity="single",
       user_input="Define a new storage pool from /tmp/fast-ssd-pool.xml.",
       args={"operation": "pool-define", "xmlfile": "/tmp/fast-ssd-pool.xml"},
       answer="Pool fast-ssd defined from /tmp/fast-ssd-pool.xml"),
    V2(id="virsh-pool-define-v2-0002", tool="virsh", operation="pool-define", complexity="multi",
       user_input="Define the pool at /tmp/backup-nfs-pool.xml, then start it.",
       args={"operation": "pool-define", "xmlfile": "/tmp/backup-nfs-pool.xml"},
       answer="Pool backup-nfs defined from /tmp/backup-nfs-pool.xml"),
    V2(id="virsh-pool-define-v2-0003", tool="virsh", operation="pool-define", complexity="single",
       user_input="register the storage pool config in /root/dr-pool.xml",
       args={"operation": "pool-define", "xmlfile": "/root/dr-pool.xml"},
       answer="Pool dr-pool defined from /root/dr-pool.xml"),
    V2(id="virsh-pool-define-v2-0004", tool="virsh", operation="pool-define", complexity="single",
       user_input="Ticket 6604: define the new archive pool from /tmp/archive-pool.xml.",
       args={"operation": "pool-define", "xmlfile": "/tmp/archive-pool.xml"},
       answer="Pool archive defined from /tmp/archive-pool.xml"),
    V2(id="virsh-pool-define-v2-0005", tool="virsh", operation="pool-define", complexity="diagnostic",
       user_input="A provisioning run generated /tmp/lab-pool.xml but virsh doesn't know about it — define it.",
       args={"operation": "pool-define", "xmlfile": "/tmp/lab-pool.xml"},
       answer="Pool lab-pool defined from /tmp/lab-pool.xml"),
    V2(id="virsh-pool-define-v2-0006", tool="virsh", operation="pool-define", complexity="single",
       user_input="load /tmp/iso-images-pool.xml as a new storage pool",
       args={"operation": "pool-define", "xmlfile": "/tmp/iso-images-pool.xml"},
       answer="Pool iso-images defined from /tmp/iso-images-pool.xml"),
    V2(id="virsh-pool-define-v2-0007", tool="virsh", operation="pool-define", complexity="single",
       user_input="Ticket 7712: define the scratch pool from /tmp/scratch-pool.xml for the render farm.",
       args={"operation": "pool-define", "xmlfile": "/tmp/scratch-pool.xml"},
       answer="Pool scratch defined from /tmp/scratch-pool.xml"),
    V2(id="virsh-pool-define-v2-0008", tool="virsh", operation="pool-define", complexity="single",
       user_input="define cold-storage using /srv/xml/cold-storage-pool.xml",
       args={"operation": "pool-define", "xmlfile": "/srv/xml/cold-storage-pool.xml"},
       answer="Pool cold-storage defined from /srv/xml/cold-storage-pool.xml"),
    V2(id="virsh-pool-define-v2-0009", tool="virsh", operation="pool-define", complexity="multi",
       user_input="Define the new pool from /tmp/etl-pool.xml, then run pool-list to confirm it registered.",
       args={"operation": "pool-define", "xmlfile": "/tmp/etl-pool.xml"},
       answer="Pool etl-pool defined from /tmp/etl-pool.xml"),
    V2(id="virsh-pool-define-v2-0010", tool="virsh", operation="pool-define", complexity="single",
       user_input="Ticket 8823: define the second-site replica pool from /tmp/replica-pool.xml.",
       args={"operation": "pool-define", "xmlfile": "/tmp/replica-pool.xml"},
       answer="Pool replica-pool defined from /tmp/replica-pool.xml"),
    V2(id="virsh-pool-define-v2-0011", tool="virsh", operation="pool-define", complexity="single",
       user_input="use /tmp/media-pool.xml to define a new pool for the encode farm",
       args={"operation": "pool-define", "xmlfile": "/tmp/media-pool.xml"},
       answer="Pool media-pool defined from /tmp/media-pool.xml"),
    V2(id="virsh-pool-define-v2-0012", tool="virsh", operation="pool-define", complexity="single",
       user_input="Define the sandbox storage pool described in /tmp/sandbox-pool.xml.",
       args={"operation": "pool-define", "xmlfile": "/tmp/sandbox-pool.xml"},
       answer="Pool sandbox-pool defined from /tmp/sandbox-pool.xml"),

    # pool-destroy (11)
    V2(id="virsh-pool-destroy-v2-0001", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="Stop and destroy the archive storage pool.",
       args={"operation": "pool-destroy", "pool": "archive"},
       answer="Pool archive destroyed"),
    V2(id="virsh-pool-destroy-v2-0002", tool="virsh", operation="pool-destroy", complexity="diagnostic",
       user_input="The backup-nfs mount is stale and hanging I/O — take that pool down.",
       args={"operation": "pool-destroy", "pool": "backup-nfs"},
       answer="Pool backup-nfs destroyed"),
    V2(id="virsh-pool-destroy-v2-0003", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="destroy the scratch pool, we're retiring the render farm",
       args={"operation": "pool-destroy", "pool": "scratch"},
       answer="Pool scratch destroyed"),
    V2(id="virsh-pool-destroy-v2-0004", tool="virsh", operation="pool-destroy", complexity="multi",
       user_input="Destroy the iso-images pool, then undefine it too.",
       args={"operation": "pool-destroy", "pool": "iso-images"},
       answer="Pool iso-images destroyed"),
    V2(id="virsh-pool-destroy-v2-0005", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="Ticket 9910: destroy the cold-storage pool ahead of the SAN decommission.",
       args={"operation": "pool-destroy", "pool": "cold-storage"},
       answer="Pool cold-storage destroyed"),
    V2(id="virsh-pool-destroy-v2-0006", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="take down the dr-pool storage pool",
       args={"operation": "pool-destroy", "pool": "dr-pool"},
       answer="Pool dr-pool destroyed"),
    V2(id="virsh-pool-destroy-v2-0007", tool="virsh", operation="pool-destroy", complexity="diagnostic",
       user_input="lab-pool is throwing stale NFS handle errors on every guest that touches it — destroy the pool.",
       args={"operation": "pool-destroy", "pool": "lab-pool"},
       answer="Pool lab-pool destroyed"),
    V2(id="virsh-pool-destroy-v2-0008", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="Ticket 1123: destroy the replica-pool now that failover testing is complete.",
       args={"operation": "pool-destroy", "pool": "replica-pool"},
       answer="Pool replica-pool destroyed"),
    V2(id="virsh-pool-destroy-v2-0009", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="stop the etl-pool storage pool",
       args={"operation": "pool-destroy", "pool": "etl-pool"},
       answer="Pool etl-pool destroyed"),
    V2(id="virsh-pool-destroy-v2-0010", tool="virsh", operation="pool-destroy", complexity="single",
       user_input="destroy media-pool, the encode farm has been shut down for good",
       args={"operation": "pool-destroy", "pool": "media-pool"},
       answer="Pool media-pool destroyed"),
    V2(id="virsh-pool-destroy-v2-0011", tool="virsh", operation="pool-destroy", complexity="multi",
       user_input="Destroy the sandbox-pool and then check pool-list to confirm it's gone.",
       args={"operation": "pool-destroy", "pool": "sandbox-pool"},
       answer="Pool sandbox-pool destroyed"),
]

from finetune.scenarios_v2 import check_module; check_module("virsh", SCENARIOS_V2)
